### ISSUE TITLE
[Bug]: Tor browser installed with `scoop install tor-browser` launches a non-functional tor

### ISSUE THREAD

**Issue by udit** [ScoopInstaller/Extras#10035]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

tor-browser

### Expected/Current Behaviour

After the recent tor browser update to 12.0 or 12.0.1 (I am not sure which one), Tor does not connect to the network at all. It keeps showing "connecting..." indefinitely. The buttons to test the internet connection in the settings also do not work.

The issue must be with the installer script, because I manually installed tor in a different location from the same installer in the cache folder and it works without any issues.

### Steps to Reproduce

```console
`>scoop install tor-browser`
Above installation fails to connect to the tor network

Now install tor manually from the installer in the cache to any other location on the system to check that it connects to tor network without any issues.
```

### Possible Solution

The installer script is probably incompatible with the new major Tor upgrade to 12.0

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
9e2747fd1 (HEAD -> master, origin/master, origin/HEAD) mpv-git: Update to version 20221218

'java' bucket:
c4383759 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.362-6.0.202212161950

'main' bucket:
96d5d76ef (HEAD -> master, origin/master, origin/HEAD) edgedriver: Update to version 110.0.1564.0
```

### Scoop Config

```console
last_update                       aria2-enabled scoop_branch scoop_repo
-----------                       ------------- ------------ ----------
2022-12-18T11:08:28.9864796+05:30          True master       https://github.com/lukesampson/scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jacklsw** [comment]
I can confirm I have the same issue, can't connect to network with tor-browser 12.0/12.0.1 installed through scoop. If I install the app directly from the installer file from the scoop's cache, it works fine.

Might be the custom profile for tor-browser in scoop installer which causes it to have trouble connecting to internet.

**Comment by samiksome92** [comment]
The issue seems to be with moving the files under `TorBrowser/Data/Tor` to `TorBrowser/Tor`. Once the files are moved back to their original location tor browser connects properly.

However persisting torrc in `TorBrowser/Data/Tor/torrc` does not seem to work. A work around is to persist the whole `TorBrowser/Data/Tor` directory.

I have created a pull request. https://github.com/ScoopInstaller/Extras/pull/10039
