### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by ATrogolo** [ScoopInstaller/Extras#10031]
  D:\ scoop install avidemux                                                                    
WARN  Purging previous failed installation of avidemux.                                           
ERROR 'avidemux' isn't installed correctly.                                                       
Removing older version (2.8.1).                                                                   
'avidemux' was uninstalled.                                                                       
Installing 'avidemux' (2.8.1) [64bit] from extras bucket                                          
Loading Avidemux_2.8.1.VC++.64bits.exe from cache                                                 
Checking hash of Avidemux_2.8.1.VC++.64bits.exe ... ok.                                           
Extracting dl.7z ... ERROR Exit code was 2!                                                       
Failed to extract files from C:\Users\Andrea\scoop\apps\avidemux\2.8.1\dl.7z.                     
Log file:                                                                                         
  ~\scoop\apps\avidemux\2.8.1\7zip.log                                                            
                                                                                                  
Please try again or create a new issue by using the following link and paste your console output: 
https://github.com/lukesampson/scoop-extras/issues/new?title=avidemux%402.8.1%3a+decompress+error

**Comment by HUMORCE** [comment]
#9689

**Comment by ATrogolo** [comment]
So the solution is: 

> In the meantime you could install the nightly version avidemux-nightly from the versions bucket
