### ISSUE TITLE
autohotkey@2.0.0: decompress error

### ISSUE THREAD

**Issue by dertuxmalwieder** [ScoopInstaller/Extras#10066]
```
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: d404b5|OK  |   2.3MiB/s|C:/Users/stop_/scoop/cache/autohotkey#2.0.0#https_github.com_Lexikos_AutoHotkey_L_releases_download_v2.0.0_AutoHotkey_2.0.0_setup.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of AutoHotkey_2.0.0_setup.exe ... ok.
Uninstalling 'autohotkey' (1.1.36.02)
Installing 'autohotkey' (2.0.0) [64bit] from extras bucket
Loading AutoHotkey_2.0.0_setup.exe from cache.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\stop_\scoop\apps\autohotkey\2.0.0\dl.7z.
Log file:
  ~\scoop\apps\autohotkey\2.0.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=autohotkey%402.0.0%3a+decompress+error
```

Contents of said log:

```
7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 2910208 bytes (2842 KiB)

Extracting archive: C:\Users\stop_\scoop\apps\autohotkey\2.0.0\dl.7z
WARNING:
C:\Users\stop_\scoop\apps\autohotkey\2.0.0\dl.7z
Cannot open the file as [7z] archive
The file is open as [PE] archive

--
Path = C:\Users\stop_\scoop\apps\autohotkey\2.0.0\dl.7z
Open WARNING: Cannot open the file as [7z] archive
Type = PE
Physical Size = 2910208
CPU = x86
Characteristics = Executable 32-bit NoRelocs
Created = 2022-12-20 08:14:22
Headers Size = 4096
Checksum = 0
Image Size = 5414912
Section Alignment = 4096
File Alignment = 512
Code Size = 2875392
Initialized Data Size = 40960
Uninitialized Data Size = 2494464
Linker Version = 14.33
OS Version = 6.0
Image Version = 0.0
Subsystem Version = 6.0
Subsystem = Windows GUI
Stack Reserve = 4194304
Stack Commit = 4096
Heap Reserve = 1048576
Heap Commit = 4096
Image Base = 4194304
Comment =
{
FileVersion: 2.0.0.0
FileVersion: 2.0.0
ProductVersion: 2.0.0.0
ProductVersion: 2.0.0
FileDescription: AutoHotkey installer
ProductName: AutoHotkey Setup
InternalName: AutoHotkey Setup
}


Sub items Errors: 40

Archives with Errors: 1

Sub items Errors: 40
ERROR: Data Error : .rsrc\MENU\211
ERROR: Data Error : .rsrc\DIALOG\205
ERROR: Data Error : .rsrc\DIALOG\500
ERROR: Data Error : .rsrc\ACCELERATOR\212
ERROR: Data Error : .rsrc\RCDATA\AUTOHOTKEY.CHM
ERROR: Data Error : .rsrc\RCDATA\AUTOHOTKEY32.EXE
ERROR: Data Error : .rsrc\RCDATA\AUTOHOTKEY64.EXE
ERROR: Data Error : .rsrc\RCDATA\INSTALL.CMD
ERROR: Data Error : .rsrc\RCDATA\LICENSE.TXT
ERROR: Data Error : .rsrc\RCDATA\UX\INC\BOUNCE-V1.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\COMMANDLINETOARGS.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\COMMON.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\CONFIG.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\CREATEAPPSHORTCUT.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\ENABLEUIACCESS.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\GETGITHUBRELEASEASSETURL.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\HASHFILE.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\IDENTIFY.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\IDENTIFY_REGEX.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\LAUNCHER-COMMON.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\README.TXT
ERROR: Data Error : .rsrc\RCDATA\UX\INC\SHELLRUN.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INC\SPY.ICO
ERROR: Data Error : .rsrc\RCDATA\UX\INC\UI-BASE.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INSTALL-AHK2EXE.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INSTALL-VERSION.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\INSTALL.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\LAUNCHER.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\RELOAD-V1.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\RESET-ASSOC.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\TEMPLATES\MINIMAL FOR V2.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\UI-DASH.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\UI-EDITOR.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\UI-LAUNCHERCONFIG.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\UI-NEWSCRIPT.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\UI-SETUP.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\UI-UNINSTALL.AHK
ERROR: Data Error : .rsrc\RCDATA\UX\WINDOWSPY.AHK
ERROR: Data Error : .rsrc\RCDATA\WINDOWSPY.AHK
ERROR: Data Error : .rsrc\RCDATA\1
```

**Comment by iamsilvio** [comment]
The decompression error comes from the wrong url, the url ended in dl.7z but is actually an .exe

But apart from that the package should not update to 2.0 if there is an explicit autohotkey2, because 2.0 has braking changes which is not bad but makes an inplace upgrade impossible.

**Comment by NSP-0123456** [comment]
Setup format changed between 2.0 and 1.1 it is not possible to just extract from AutoHotkey_2.0.0_setup.exe as it was with 1.1 version. Also autohotkey 2 is not backward compatible with all 1/1.1 code.
A good compromise could be to have an autohotkey1.1 entry to stay on 1.1 version ! 

You can use zip file instead https://www.autohotkey.com/download/ahk-v2.zip  or https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.0/AutoHotkey_2.0.0.zip

**Comment by iamsilvio** [comment]
According to the pull request from @HUMORCE  we don't care about compatibility problems between 1.* and 2.0
and just move forward and break things

**Comment by iamsilvio** [comment]
The problem is that with the 2.0 installer the 1.* interpreter is not installed

if you define `#Requires AutoHotkey v1.1.35 ;` in a script, the execution will simply fail
So you must have an older version installed to run an older interpreter.

Batteries not included

![image](https://user-images.githubusercontent.com/1840449/208889504-1d90d726-a388-4510-aa4e-310ed341ae6e.png)

**Comment by HUMORCE** [comment]
![screenshot_20221221111236](https://user-images.githubusercontent.com/4353480/208892162-b9490e87-bd9b-4105-98fb-10b6deb6258a.png)

See below, if this prompt window does not show up when open a 1/1.1 AHK script file.

```
cd (scoop prefix autohotkey)

# install v1.1
.\UX\AutoHotkeyUX.exe /script .\UX\install-version.ahk

# if you want uninstall sub-version(s) installed by AHK2 itself
.\UX\AutoHotkeyUX.exe /script .\UX\install-version.ahk
```

**Comment by iamsilvio** [comment]
> .\UX\AutoHotkeyUX.exe /script .\UX\install-version.ahk <version>

where did you find the documentation for this
the message did not pop up on my test :/
you are awesome 🥇

**Comment by HUMORCE** [comment]
> where did you find the documentation for this

No documentation,

First time I opened `a.ahk`: `#Requires AutoHotkey v1.1.35 ;`, it prompt this(this may be related to the fact that I have not used AHK before), then dir `v1.1.36.02` was created in autohotkey dir, but when I deleted dir `v1.1.36.02` and reopen `a.ahk`, error show up and this prompt missing. then I checked the built-in ahk files and found these.

**Comment by NSP-0123456** [comment]
autohotkey 1.1 can be installed with autohotkey1.1 entry.

**Comment by neoOpus** [comment]
ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://www.autohotkey.com/download/2.0/AutoHotkey_2.0.4.zip
    referer=https://www.autohotkey.com/download/2.0/
    dir=C:\Users\neoop\scoop\cache
    out=autohotkey#2.0.4#https_www.autohotkey.com_download_2.0_AutoHotkey_2.0.4.zip

ERROR & 'C:\Users\neoop\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\neoop\scoop\cache\autohotkey.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=14956 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=autohotkey%402.0.4%3a+download+via+aria2+failed
