### ISSUE TITLE
[Request]: wavosaur

### ISSUE THREAD

**Issue by milnak** [ScoopInstaller/Extras#10069]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

wavosaur

### Description

Free sound editor, audio editor, wav editor software for editing, processing and recording sounds, wav and mp3 files. 

### Homepage

https://www.wavosaur.com/

### Download Link(s)

https://www.wavosaur.com/download/files/Wavosaur.1.7.0.0-x64.zip

### Some Indication of Popularity/Repute

Been using it myself for quite a while, and has a bunch of donations.

**Comment by Zliced13** [comment]
@milnak Could you please show me all the names of the **wavosaur** config files? They should be named similarly like the picture below:
![(explorer)m7a1l8_12-22-2022](https://user-images.githubusercontent.com/101912712/209082611-8ff582e4-7b5d-4156-ad0a-3dd71b09000c.jpg)

**Comment by Zliced13** [comment]
Never mind found out, myself.
