### ISSUE TITLE
[Request]: ShareX DevBuilds

### ISSUE THREAD

**Issue by bachig26** [ScoopInstaller/Extras#10073]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

ShareX Dev

### Description

ShareX is a free and open source program that lets you capture or record any area of your screen and share it with a single press of a key. It also allows uploading images, text or other types of files to many supported destinations you can choose from.

### Homepage

https://getsharex.com/

### Download Link(s)

https://getsharex.com/downloads?repo=ShareX/DevBuilds

### Some Indication of Popularity/Repute

ShareX Main Repo Stars: 22.5k
ShareX DevBuils Repo Stars: 6

URLs:
https://github.com/ShareX/DevBuilds
https://github.com/ShareX/DevBuilds/releases

**Comment by Zliced13** [comment]
Should I add the latest version, or should I add the pre-release version?

**Comment by bachig26** [comment]
> Should I add the latest version, or should I add the pre-release version?

This repo is exclusively for the pre-release or deb builds, so I believe it will be published as latest version.

The stable or public version is published in the main repo.
