### ISSUE TITLE
[Bug]: TranslucentTB Portable only works on Win11

### ISSUE THREAD

**Issue by SiyuChen** [ScoopInstaller/Extras#10071]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

TranslucentTB 

### Expected/Current Behaviour

See https://github.com/TranslucentTB/TranslucentTB. It says: 
`A portable version of the app is also available [on GitHub releases](https://github.com/TranslucentTB/TranslucentTB/releases) as TranslucentTB.zip, but this version only works on Windows 11.`

On Win10, it leads to 
![image](https://user-images.githubusercontent.com/22484673/208809692-f5876792-4a57-4ac9-bf81-d23df21a5b58.png)

### Steps to Reproduce

```console
\
```

### Possible Solution

One should use [TranslucentTB.appinstaller](https://github.com/TranslucentTB/TranslucentTB/releases/download/2022.1/TranslucentTB.appinstaller).

### Scoop and Buckets Version

```console
\
```

### Scoop Config

```console
\
```

### PowerShell Version

```console
\
```

**Comment by Zliced13** [comment]
This seems like an issue you should send to the developer of **TranslucentTB**, the devs here in scoop can't really do much since this is an external issue beyond Scoop.

**Comment by SiyuChen** [comment]
> This seems like an issue you should send to the developer of **TranslucentTB**, the devs here in scoop can't really do much since this is an external issue that's beyond Scoop.

I believe that the early version of [translucenttb.json](https://github.com/ScoopInstaller/Extras/commit/bdb12b16c66604f13fe1d18bab9d94e704417fb6) which downloads TranslucentTB.appinstaller (instead of TranslucentTB-portable-x64.zip) and uses the command  

"Add-AppxPackage \"$dir\\TranslucentTB.appinstaller\" -AppInstaller" 

to install the package is a more suitable way, because it applies to both Win10 and Win11. The developer of TranslucentTB has provided TranslucentTB.appinstaller in the latest version:

See https://github.com/TranslucentTB/TranslucentTB/releases


TranslucentTB-portable-x64.zip only works on Windows 11 and we should avoid using it.

**Comment by Zliced13** [comment]
Ok I'll see what I can do.

**Comment by Zliced13** [comment]
I made a non-portable version to counter this issue. I will soon make a PR for it.
