### ISSUE TITLE
[Bug]: Cant install autohotkey@1.1.36.02

### ISSUE THREAD

**Issue by kinsan2007** [ScoopInstaller/Extras#10080]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

autohotkey

### Expected/Current Behaviour

Could not find hash in https://www.autohotkey.com/download/2.0/AutoHotkey_1.1.36.02.zip.sha256
Downloading AutoHotkey_1.1.36.02.zip to compute hashes!
Downloading https://www.autohotkey.com/download/2.0/AutoHotkey_1.1.36.02.zip (-1 B)...

### Steps to Reproduce

```console
WARN  Given version (1.1.36.02) does not match manifest (2.0.0)
WARN  Attempting to generate manifest for 'autohotkey' (1.1.36.02)
Autoupdating autohotkey
Searching hash for AutoHotkey_1.1.36.02.zip in https://www.autohotkey.com/download/2.0/AutoHotkey_1.1.36.02.zip.sha256
远程服务器返回错误: (404) 未找到。
URL https://www.autohotkey.com/download/2.0/AutoHotkey_1.1.36.02.zip.sha256 is not valid
Could not find hash in https://www.autohotkey.com/download/2.0/AutoHotkey_1.1.36.02.zip.sha256
Downloading AutoHotkey_1.1.36.02.zip to compute hashes!
Downloading https://www.autohotkey.com/download/2.0/AutoHotkey_1.1.36.02.zip (-1 B)...
```

### Possible Solution

may change (I not sure)
https://github.com/ScoopInstaller/Extras/blob/master/bucket/autohotkey.json

    "autoupdate": {
        "url": "https://www.autohotkey.com/download/2.0/AutoHotkey_$version.zip",
        "hash": {
            "url": "$url.sha256"
        }

to 

    "autoupdate": {
        "url": "https://www.autohotkey.com/download/$version/AutoHotkey_$version.zip",
        "hash": {
            "url": "$url.sha256"
        }

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'dorado' bucket:
f98c303f (HEAD -> master, origin/master, origin/HEAD) tradingview: Update to version 2.0.0

'extras' bucket:
ff6dddf6e (HEAD -> master, origin/master, origin/HEAD) plex-desktop: Update to version 1.60.1.3413-533a7645

'main' bucket:
90642741c (HEAD -> master, origin/master, origin/HEAD) trufflehog: Update to version 3.21.0

'nonportable' bucket:
44ef241 (HEAD -> master, origin/master, origin/HEAD) spotx-np: Update to version 0.78

'nuke' bucket:
390c6f5 (HEAD -> master, origin/master, origin/HEAD) sdcc-snapshot-i586: Update to version 20221221-13772
```

### Scoop Config

```console
**
```

### PowerShell Version

```console
**
```

**Comment by HUMORCE** [comment]
```
❯ scoop info autohotkey

Name        : autohotkey
Description : The ultimate automation scripting language for Windows.
Version     : 2.0.0
Bucket      : extras
Website     : https://www.autohotkey.com
License     : GPL-2.0-or-later
Updated at  : 12/22/2022 3:36:11 AM
Updated by  : HUMORCE
Installed   : 2.0.0
Binaries    : autohotkey.exe | autohotkey32.exe
Notes       : Install specific version of interpreter(Default: Latest 1.x):
                - 'autohotkey /script <root>\UX\install-version.ahk [version]'
              Uninstall Sub-versions of Interpreter:
                - 'autohotkey /script <root>\UX\ui-uninstall.ahk'
              See also: https://github.com/ScoopInstaller/Extras/issues/10066
```

related: https://github.com/ScoopInstaller/Extras/issues/10066#issuecomment-1361187616 #10075 #10081

If you need version 1.x only: https://github.com/ScoopInstaller/Versions/pull/864
```
scoop bucket add versions
scoop install autohotkey
```
