### ISSUE TITLE
Rawtherapee package not updated to 5.9 probably due to change in release name/format

### ISSUE THREAD

**Issue by ghotz** [ScoopInstaller/Extras#10092]
I'm not familiar enough with how Scoop manifests work, but from what I've understood the new version should have been automatically detected (not sure by whom though...) as a new file in the builds repository: `https://rawtherapee.com/shared/builds/windows`.

The `autoupdate` section in `rawtherapee.json` searches for this filename pattern `RawTherapee_$version.exe` but the lastest build is named `RawTherapee_5.9_win64.zip` which is also a ZIP archive instead of the executable installer (the archive contains the executable 'RawTherapee_5.9_win64.exe').

**Comment by ghotz** [comment]
I tried updating amd it's not working (maybe because the EXE installer is inside the ZIP archive).

Repro:
```
scoop update rawtherapee
rawtherapee: 5.8 -> 5.9
Updating one outdated app:
Updating 'rawtherapee' (5.8 -> 5.9)
Downloading new version
RawTherapee_5.9_win64.zip (32,7 MB) [...] 100%
Checking hash of RawTherapee_5.9_win64.zip ... ok.
Uninstalling 'rawtherapee' (5.8)
Removing shim 'rawtherapee.shim'.
Removing shim 'rawtherapee.exe'.
Removing shim 'rawtherapee-cli.shim'.
Removing shim 'rawtherapee-cli.exe'.
Unlinking C:\Utils\Scoop\apps\rawtherapee\current
Installing 'rawtherapee' (5.9) [64bit] from extras bucket
Loading RawTherapee_5.9_win64.zip from cache
Extracting RawTherapee_5.9_win64.zip ... ERROR Exit code was 1!
Failed to extract files from C:\Utils\Scoop\apps\rawtherapee\5.9\RawTherapee_5.9_win64.zip.
Log file:
  C:\Utils\Scoop\apps\rawtherapee\5.9\innounp.log
```

The log contains just the following:

_The setup files are corrupted or made by incompatible version. Maybe it's not an Inno Setup installation at all.
(00492DAA)_

**Comment by HUMORCE** [comment]
I forgot to check the internal files for that.
