### ISSUE TITLE
dbeaver@22.3.1: hash check failed

### ISSUE THREAD

**Issue by sgtlaggy** [ScoopInstaller/Extras#10112]
Current incorrect hash: 1edea8f1da8f4df4bcf443c64ee466c9fde24e1b361fcb16b69cee47ba846440
Correct hash: 697c9eca25a8c2200d94491ac633935bf4ebefccca082ff030e57ed596ff3133
Tested against CDN and GitHub release.

**Comment by pcdd-group** [comment]
I ran into the same situation, which I solved by adding the -s parameter:.
scoop install dbeaver -s
 -s or --skip Skip hash validation (use with caution!)
