### ISSUE TITLE
[Request]: Modboy

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#10161]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Modboy

### Description

It's a tool to help download, install and manage mods available through Gamebanana for a variety of different games.

### Homepage

https://gamebanana.com/tools/6321

### Download Link(s)

https://gamebanana.com/tools/6321

### Some Indication of Popularity/Repute

It is located on the homepage on the middle-right side of the screen.

![1](https://user-images.githubusercontent.com/22171451/210176469-68b4fc46-f2b0-4251-ad9c-c39d165af65f.png)

**Comment by anderlli0053** [comment]
Thanks!

**Comment by aliesbelik** [comment]
Please submit to the [games](https://github.com/Calinou/scoop-games) bucket instead.

**Comment by anderlli0053** [comment]
Funny how it took 1 year to even process this... But ok
