### ISSUE TITLE
[Request]:  wsl2-distro-manager

### ISSUE THREAD

**Issue by ringerl** [ScoopInstaller/Extras#10217]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

 wsl2-distro-manager

### Description

A quick way to manage your WSL instances with a GUI.

### Homepage

https://apps.microsoft.com/store/detail/wsl-manager/9NWS9K95NMJB?hl=en-us&gl=us

### Download Link(s)

https://github.com/bostrot/wsl2-distro-manager/releases

### Some Indication of Popularity/Repute

- Available in 8 languages
- Reviewed and starred on Microsoft App Store
- ~400stars on GitHub
- 43 forks in GitHub
- featured in [Awesome-WSL](https://github.com/sirredbeard/Awesome-WSL#for-managing-wsl-installations)

**Comment by MlgGurke** [comment]
I'm going to work on this issue.
