### ISSUE TITLE
[Bug]: mpv command not found in gitbash

### ISSUE THREAD

**Issue by DanSM-5** [ScoopInstaller/Extras#10221]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

mpv

### Expected/Current Behaviour

I noticed that on the latest version of mpv 0.35.0 the `mpv` command stop working under gitbash.

This was confusing because the exact same version was installed on another PC and the command is working in gitbash without workarounds (alias or script file to map mpv.com). The cause for this issue was the change from shimming to use the path to mpv.

https://github.com/ScoopInstaller/Extras/pull/9662

From the PR I see that's something related to mpv.net which I'm not very familiar with. Is this change required for the simple mpv? Because without the shim gitbash won't recognize mpv.

There are workarounds as I've mentioned before like aliasing mpv to mpv.com or simply creating a shell scrip to map to mpv.com but I'd like to know if this change if required for mpv in the first place.

### Steps to Reproduce

1. On latest version of scoop install mpv

```
scoop install mpv

```
2. Open a bash shell (gitbash) and type `mpv`.
3. Observe that the mpv command is not recognized as a valid command.

You can verify that previous version using the shim does work by installing mpv using the previous manifest.

1. Install mpv with manifest that creates a shim (one commit before the change).
```
scoop install https://raw.githubusercontent.com/ScoopInstaller/Extras/a7f6726ad34dd8abca908c1882d1e150f0662477/bucket/mpv.json
```
2. Open a bash shell (gitbash)
3. Use `mpv` command and observe the output that it recognizes mpv.

### Possible Solution

* Revert the changes in mpv.json to use a shim file again instead of adding mpv to the path.
* Do nothing and recommend alternatives like the ones mentioned in the steps to reproduce.

### Scoop and Buckets Version

```console
** Will update once I have the affected computer back **
```

### Scoop Config

```console
** Will update once I have the affected computer back **
```

### PowerShell Version

```console
** Will update once I have the affected computer back **
```

### Additional Softwares

Git bash for Windows
Windows Terminal

**Comment by HUMORCE** [comment]
```
$ mpv
bash: mpv: command not found

$ mpv.exe
mpv 0.35.0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Mon Nov 14 04:47:57 2022
...
```

**Comment by DanSM-5** [comment]
Using the binary with extension works (in my case I need to use `mpv.com` instead of mpv.exe or it will just open the player ui instead of outputing information), I know and that solution is fine for simple use cases but it doesn't work when `mpv` is expected on scripts.

The reason I found this issue is because it stopped working on [ani-cli](https://github.com/pystardust/ani-cli) and I found an issue opened regarding that https://github.com/pystardust/ani-cli/issues/959.

That's why I wanted to ask if the change made to use a path instead of a shim is required for mpv as the PR that makes the change stated that the issue is for mpv.net.

In any case if this change is going to stay, I'd like to add a better solution for anyone finding this issue.

1. Create a file in directory that it is in your path (E.g. `$HOME/.local/bin`) and named it `mpv`.
2. Open it with a text editor and add the following lines
```bash
#!/usr/bin/env bash
mpv.com "$@"
```
3. Add executable permissions to the file. E.g.
```bash
chmod +x "$HOME/.local/bin/mpv"
```
That should map the binary (`mpv.com` in my case) to a script that gitbash can find. That way there is no need to add the extension and modify scripts of binaries that expect mpv (without extensions).

edited(30-09-2025): fixed bad script name

**Comment by HUMORCE** [comment]
> That's why I wanted to ask if the change made to use a path instead of a shim is required for mpv as the PR that makes the change stated that the issue is for mpv.net.

the current situation is more in line with expectations either itself or Windows, IMO.

You can also do it with scoop-shim(`scoop help shim`).

```
scoop shim add mpv 'C:\Users\humorce\scoop\apps\mpv\current\mpv.com'
```

**Comment by Lauloque** [comment]
I also am blocked by mpv not being found when used from ani-cli in the terminal (but it works in vanilla git bash), as explained more in detail in the above mention.

I tried both solutions proposed by DanSM-5 and HUMCORE:

While running "mpv.com" works in all terminal profiles and git bash, the first solution still gets "bash: mpv: command not found" and the last gets `ERROR: Command path does not exist: 'C:\Users\Lauloque\scoop\apps\mpv\current\mpv.com'` even though that path is valid. (And I also tried with ".exe" instead of ".com").

However this works:

[Cant detect mpv · Issue #959 · pystardust/ani-cli](https://github.com/pystardust/ani-cli/issues/959#issuecomment-1376594983)

> try deleting the mpv folder and try again it should work ![mpv](https://user-images.githubusercontent.com/36833664/211441474-d0532d3f-cea2-46a8-bf9a-3b66e7fdea47.PNG)

But that will probably break at next update and idk how much that folder is important to mpv

----

Edit: I was [pointed out](https://github.com/pystardust/ani-cli/issues/1529#issuecomment-3239422081) that I used `%GIT_INSTALL_ROOT%\usr\bin\bash.exe` instead of `%GIT_INSTALL_ROOT%\bin\bash.exe`, that fixed it even with the mpv folder.
