### ISSUE TITLE
[Request]: Files

### ISSUE THREAD

**Issue by bachig26** [ScoopInstaller/Extras#10245]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Files

### Description

Files is a file manager that lets you easily organize content on your device. Robust multitasking experiences, helpful tags, and deep integrations add to an intuitive design.

### Homepage

https://files.community/

### Download Link(s)

https://github.com/files-community/Files/releases/

### Some Indication of Popularity/Repute

GitHub Repo: https://github.com/files-community/Files

Stars: 25.9k

**Comment by anderlli0053** [comment]
What is going on with this.. I see that the pull request was closed prematurely... Should the issue be opened in NP bucket or what? @MlgGurke @HUMORCE

**Comment by HUMORCE** [comment]
Nonportable bucket is recommended. This type of package should not be added to Extras bucket, IMO

Even though other members can accept this type of package, it is complete manifest: https://github.com/ScoopInstaller/Extras/blob/master/bucket/maple.json

**Comment by Zliced13** [comment]
@HUMORCE this should be closed now, it has already been added to the [nonportable](https://github.com/ScoopInstaller/Nonportable) bucket as `files-np`.
