### ISSUE TITLE
[Request]: Lark

### ISSUE THREAD

**Issue by cvladan** [ScoopInstaller/Extras#10253]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Lark

### Description

Team productivity suite that boosts creativity

### Homepage

https://www.larksuite.com/

### Download Link(s)

https://www.larksuite.com/download

### Some Indication of Popularity/Repute

First, it is a product of company ByteDance, authors of TikTok

![image](https://user-images.githubusercontent.com/1913156/212682350-1becd139-cb89-4392-915f-908d8d73b612.png)

It is completely free for teams of up to 50 users

![image](https://user-images.githubusercontent.com/1913156/212682545-4e02c977-2814-45a5-badb-018c06b117e8.png)

And about popularity — their mobile app has more than a million downloads:

![image](https://user-images.githubusercontent.com/1913156/212682667-fa6c1098-8600-4815-9096-de98abe88798.png)

**Comment by StarsbySea** [comment]
I have written a manifest file that applies to Lark here in #10561. Could you please review it and try it out to see if it works, and leave your comments, please? A team member might be able to merge it into the mainline branch after a while, if everything works properly.
