### ISSUE TITLE
[Request]: Lark

### ISSUE THREAD

**Issue by SiyuChen** [ScoopInstaller/Extras#10272]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Lark

### Description

Team productivity suite that boosts creativity and engagement

### Homepage

https://www.larksuite.com/

### Download Link(s)

https://www.larksuite.com/download

### Some Indication of Popularity/Repute

see https://www.getapp.co.uk/reviews/132875/lark

**Comment by SiyuChen** [comment]
Sorry, just noticed the request is a duplicate of https://github.com/ScoopInstaller/Extras/issues/10253

**Comment by StarsbySea** [comment]
I have written a manifest file that applies to Lark here in #10561. Could you please review it and try it out to see if it works, and leave your comments, please? A team member might be able to merge it into the mainline branch after a while, if everything works properly.
