### ISSUE TITLE
spotify@1.2.3.1115.gd61a8f5c: hash check failed

### ISSUE THREAD

**Issue by IsaacWangTT** [ScoopInstaller/Extras#10277]

**Comment by zuluion** [comment]
I also encountered the same problem with the following error message.
I have ruled out possible problems with the network and cache.

>ERROR Hash check failed!
>App:         extras/spotify
>URL:         https://download.scdn.co/SpotifyFullSetup.exe       
>First bytes: 4D 5A 90 00 03 00 00 00
>Expected:    0f90c8602ec4baced6d7ae1ccdd5b1fd9154653f555c4847e269a24dec4715d4
>Actual:      9e2429f5ab41493cb86aef5daa0115c9cabe773ca21d83cba652bb50f5a9d986
