### ISSUE TITLE
[Bug]: Deprecate toggl

### ISSUE THREAD

**Issue by AucaCoyan** [ScoopInstaller/Extras#10316]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

toggle

### Expected/Current Behaviour

Hi! I recently installed it with `scoop install toggle` and the app showed me that it's going to be deprecated soon and it will be replaced with [this other windows app](https://toggl.com/track/time-tracking-windows/)

This is the [current manifest](https://github.com/ScoopInstaller/Extras/blob/master/bucket/toggl.json).

May I ask for deprecate the current toggl package?
Thanks!

### Steps to Reproduce

```console
scoop install toggle

# open toggle
# toggle will warn you of the deprecation of the app
```

### Possible Solution

Deprecate the current package of `toggl` and possibly create a new package with the windows version (if it's even possible)

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'anderlli0053_DEV-tools' bucket:
26a8d41ce (HEAD -> master, origin/master, origin/HEAD) ti-nspire-cx-student-software-np: Update to version 6.0.3.374

'extras' bucket:
15cdbd7ff (HEAD -> master, origin/master, origin/HEAD) x64dbg: Update to version 2023-01-24_13-49

'main' bucket:
7aa27aed3 (HEAD -> master, origin/master, origin/HEAD) scaleway-cli: Update to version 2.10.0

'nerd-fonts' bucket:
971f0e0 (HEAD -> master, origin/master, origin/HEAD) iA-Writer-NF: Update to version 2.3.2
```

### Scoop Config

```console
scoop config

last_update        scoop_repo                              scoop_branch
-----------        ----------                              ------------
24/1/2023 15:31:27 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
toggl v7 is an opensource project, while v8 seems to have turned to commercial. 

I installed extras/toggl and it can be use, maybe I just opend it on short time, I did not seen it to be deprecated, you should request to add Toggl Track v8.

**Comment by eevleevs** [comment]
Confirmed no longer working.
