### ISSUE TITLE
[Request]: OpenIV

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#10356]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

OpenIV

### Description

OpenIV is a multi-purpose editor and archive manager for PC versions of Grand Theft Auto V, Grand Theft Auto IV/EFLC and Max Payne 3.   OFFICIAL DESCRIPTION:  OpenIV is a free modding toolset for Grand Theft Auto 5 and other games that allows you to view and alter the game data. Because of restrictions set by Rockstar Games, the game’s publisher, you should only mod GTA5 in offline mode or risk being banned from the game.  This toolkit is a convenient way to keep track of mods for multiple games in one spot. Modding games are becoming increasingly popular around the world, but if you want to explore some GTA5-specific choices, check out GTA5 Prison and Chaos Mod V.

### Homepage

https://openiv.org/

### Download Link(s)

https://ntscorp.ru/ovi/setup/ovisetup.exe (forwarded from https://openiv.org/dl )

### Some Indication of Popularity/Repute

Related to: https://github.com/Calinou/scoop-games/issues/750 but i do not know if i created that issues in the right bucket, as i see that many game modding tools and other game tools are in this Extras bucket as well

**Comment by Zliced13** [comment]
There is no silent installation for the installer, so unfortunately this cannot be added to official buckets.

**Comment by anderlli0053** [comment]
> There is no silent installation for the installer, so unfortunately this cannot be added to official buckets.

That's sad.. I'll be closing this here and in the Games bucket too
