### ISSUE TITLE
[Bug]: Extremly Outdated Package in yapa.json

### ISSUE THREAD

**Issue by cvladan** [ScoopInstaller/Extras#10369]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

yapa

### Expected/Current Behaviour

YAPA is no longer maintened, for further updates and new releases check out [YAPA 2.0](https://github.com/YetAnotherPomodoroApp/YAPA-2)

### Steps to Reproduce

```console
-
```

### Possible Solution

Either replace with [YAPA2](https://github.com/YetAnotherPomodoroApp/YAPA-2) or remove completely and include the new, better and more polished alternatives:

1. [JakubGluszek/intentio](https://github.com/JakubGluszek/intentio) in Rust
2. [ayoisaiah/focus](https://github.com/ayoisaiah/focus) for command-line written in Go

### Scoop and Buckets Version

```console
-
```

### Scoop Config

```console
-
```

### PowerShell Version

```console
-
```

### Additional Softwares

-

**Comment by Zliced13** [comment]
@HUMORCE should the package `yapa` be removed from this bucket?

**Comment by HUMORCE** [comment]
> Do you think should the package yapa be removed from this bucket, or should it be moved to the depracted folder inside this bucket?

- Copy to `versions/yapa1` and then Update `extras/yapa` to 2.x
- OR created `extras/yapa2` only.

**Comment by Zliced13** [comment]
I don't think [Intentio](https://github.com/JakubGluszek/intentio) can be added due to low stars, unless the members want to make an exception for the app.

**Comment by Zliced13** [comment]
@cvladan I added it to my personal bucket, you are welcome to try it.

To add this bucket, run
```
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
```
To install, do
```
scoop install intentio
```
