### ISSUE TITLE
[Request]: PowerShell 7

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#10428]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

PowerShell 7

### Description

Cross-platform (Windows, Linux, and macOS) automation and configuration tool/framework that works well with your existing tools and is optimized for dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object models. It includes a command-line shell, an associated scripting language and a framework for processing cmdlets.

### Homepage

https://github.com/PowerShell/PowerShell

### Download Link(s)

https://github.com/PowerShell/PowerShell/releases

### Some Indication of Popularity/Repute

_The portable ZIP package can be used for the manifest instead of extracting MSI._

**37.1k stars and 6.3k forks**

**Comment by HUMORCE** [comment]
`main/pwsh`
