### ISSUE TITLE
[Bug]: 7zip-zstd missing persist causing asar7z to not install properly

### ISSUE THREAD

**Issue by leumasme** [ScoopInstaller/Extras#10445]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

_~~asar7z~~_ 7zip-zstd

### Expected/Current Behaviour

Installing asar7z (a 7zip plugin) should automatically move the plugin dll to the 7zip "Formats" folder (and remove it when uninstalled).

For this, the asar7z preinstall script uses "scoop which 7z" to locate 7zip. 7zip-zstd overwrites the "7z" shim, so it is used instead.
7zip-std does not seem to have the "Formats" folder by default however, which leads to the script instead moving the dll to a file called "Formats" where the folder should be. This does not register the plugin dll correctly.
When uninstalling, an error is thrown as the dll does not exist

### Steps to Reproduce

```console
> scoop install 7zip-zstd
# ...
> scoop install asar7z
Installing 'asar7z' (1.4) [64bit] from extras bucket
Loading Asar.zip from cache
Checking hash of Asar.zip ... ok.
Extracting Asar.zip ... done.
Running pre_install script...
Linking S:\Apps\Scoop\apps\asar7z\current => S:\Apps\Scoop\apps\asar7z\1.4
'asar7z' (1.4) was installed successfully!
> # asar7z is not correctly installed right now!
> scoop uninstall asar7z
Uninstalling 'asar7z' (1.4).
Running pre_uninstall script...
Remove-Item : Cannot find path 'S:\Apps\Scoop\apps\7zip-zstd\current\Formats\Asar.64.dll' because it does not exist.
At line:3 char:34
+ ... tecture -eq '64bit') { Remove-Item "$7z_folder\Formats\Asar.64.dll" }
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (S:\Apps\Scoop\a...ats\Asar.64.dll:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Unlinking S:\Apps\Scoop\apps\asar7z\current
'asar7z' was uninstalled.
```

### Possible Solution

asar7z should create the Formats folder if it does not exist. Doing this manually lets the installation work correctly.

Alternatively, this could be a postinstall step of 7zip-zstd as the regular 7zip installation seems to have this folder by default. (Why does 7zip-zstd even depend on 7zip if it's completely independent?)

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
ad57b9013 (HEAD -> master, origin/master, origin/HEAD) losslesscut: Update to version 3.50.0

'games' bucket:
63ca95d1 (HEAD -> master, origin/master, origin/HEAD) yuzu: Update to version 0-1330

'java' bucket:
261d4c3d (HEAD -> master, origin/master, origin/HEAD) temurin19-nightly-jdk: Update to version 19.0.2-7.0.202302040347

'main' bucket:
30b38da9b (HEAD -> master, origin/master, origin/HEAD) openshift-okd-client: Update to version 4.12.0-0.okd-2023-02-04-212953

'nirsoft' bucket:
28db834 (HEAD -> master, origin/master, origin/HEAD) Excluded two pad files that require a password. They need to be updated manually.

'versions' bucket:
c24110b90 (HEAD -> master, origin/master, origin/HEAD) ipfilter-nightly@1675526497: Fix hash (Closes #984)
```

### Scoop Config

```console
last_update                       aria2-enabled scoop_branch scoop_repo
-----------                       ------------- ------------ ----------
2023-02-05T19:35:36.0413616+01:00         False master       https://github.com/lukesampson/scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by leumasme** [comment]
It seems that scoop `7zip` intentonally adds `Formats` and `Codecs` to `persist` which `7zip-zstd` does not, so this should probably be changed in `7zip-zstd` instead of `asar7z`.
See https://github.com/ScoopInstaller/Main/issues/1081 ; https://github.com/ScoopInstaller/Main/pull/1797

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Versions/pull/1149

**Comment by HUMORCE** [comment]
I merged https://github.com/ScoopInstaller/Versions/pull/1149, bc no external installation considered for now.
