### ISSUE TITLE
[Request]: nosleep

### ISSUE THREAD

**Issue by CHerSun** [ScoopInstaller/Extras#10469]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

nosleep

### Description

A tool that prevents Windows from automatically going into ScreenSaver / Sleep / Lock modes

### Homepage

https://github.com/CHerSun/NoSleep

### Download Link(s)

https://github.com/CHerSun/NoSleep/releases

### Some Indication of Popularity/Repute

88 github stars. A minimalistic tool with no need to install.

**Comment by Zliced13** [comment]
@sitiom Should this be added even though it has below 100+ stars?

**Comment by sitiom** [comment]
Let's wait until it reaches 100 stars. In the meantime, I recommend using PowerToys Awake, as mentioned in the readme.

**Comment by Zliced13** [comment]
Cool

**Comment by CHerSun** [comment]
> Let's wait until it reaches 100 stars. In the meantime, I recommend using PowerToys Awake, as mentioned in the readme.

102 stars now. I'd appreciate if it could be added. 

PS: PowerToys is something like 2 GB in size, so if 1 doesn't really wants it - that's too much for just 1 minor tool.

**Comment by sitiom** [comment]
> PS: PowerToys is something like 2 GB in size

How would it reach 2GB?
![image](https://github.com/ScoopInstaller/Extras/assets/56180050/9991e0b0-32b9-45e7-a067-6593478b4391)

**Comment by CHerSun** [comment]
@sitiom Scoop's Powertoys installation:
![image](https://github.com/ScoopInstaller/Extras/assets/14203878/effeb61b-3723-4695-a850-c121aa1ccf20)

3.5 GB, 2 GB compressed.

**Comment by CHerSun** [comment]
@HUMORCE  Wow, that's nice, thanks. I've updated and it's indeed ~0.5 GB now, 0.3 GB compressed:
![image](https://github.com/ScoopInstaller/Extras/assets/14203878/3a5c8605-9ec2-4777-9896-0793f123d0a1)

Much appreciated powertoys change tbh, I like the tool.
