### ISSUE TITLE
dosbox-x@0.84.2: Checkver/autoupdate is broken

### ISSUE THREAD

**Issue by kriswilk** [ScoopInstaller/Extras#10474]
Checkver / autoupdate has failed to pick up the latest version (2022.12.26) of dosbox-x, presumably because of a change in versioning format. This application seems to have some inconsistent version naming in recent releases...not sure what's up with it but we're on an old version in the Extras bucket...

**Comment by kriswilk** [comment]
Upon closer inspection, the problem is first and foremost an unresolved [bug in scoop](https://github.com/ScoopInstaller/Scoop/issues/5190). GitHub no longer serves the release asset names in the HTML at ".../releases/latest", so the checker regex cannot match the necessary details to work properly.

This app manifest, and many, many others like it will be broken until the bug is fixed...

**Comment by sitiom** [comment]
Should work now:
![image](https://user-images.githubusercontent.com/56180050/218656532-79f9ada6-cbf4-4eed-8a72-3f540761236a.png)

Regarding the inconsistent versioning, please open an issue to the upstream repo.
