### ISSUE TITLE
[Bug]: Rstudio can't find the R executable binary although R is installed.

### ISSUE THREAD

**Issue by hungpham3112** [ScoopInstaller/Extras#10533]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

Rstudio

### Expected/Current Behaviour

![image](https://user-images.githubusercontent.com/75968004/218655121-f275602a-789c-48aa-82b3-80e35e4d48e6.png)

### Steps to Reproduce

```console
- scoop install r
- scoop install rstudio
- open rstudio
```

### Possible Solution

I opened the `config.json` in `%appdata%\RStudio` and added the R path but it didn't work.
```
	"platform": {
		"windows": {
			"rBinDir": "%userprofile%/scoop/apps/r/current/bin/",
			"preferR64": true,
			"rExecutablePath": "%userprofile%/scoop/apps/r/current/bin/R.exe"
		}
	},
```

### Scoop and Buckets Version

```console
scoop bucket: cmd 'version' not supported
Usage: scoop bucket add|list|known|rm [<args>]

C:\Users\sofia>scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
dbd366953 (HEAD -> master, origin/master, origin/HEAD) todolist: Update to version 8.1.18

'main' bucket:
e47c8fb23 (HEAD -> master, origin/master, origin/HEAD) vals: Update to version 0.22.0

'nerd-fonts' bucket:
fatal: detected dubious ownership in repository at 'C:/Users/sofia/scoop/buckets/nerd-fonts'
'C:/Users/sofia/scoop/buckets/nerd-fonts' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-214374172-4155058524-4096456531-1000'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/sofia/scoop/buckets/nerd-fonts

'versions' bucket:
fatal: detected dubious ownership in repository at 'C:/Users/sofia/scoop/buckets/versions'
'C:/Users/sofia/scoop/buckets/versions' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-214374172-4155058524-4096456531-1000'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/sofia/scoop/buckets/versions
```

### Scoop Config

```console
alias
-----
@{reinstall=scoop-reinstall; i=scoop-i; add=scoop-add; rm=scoop-rm; remove=scoop-remove; ls=scoop-ls; u=scoop-u; upgrade=scoop-upgrade; ua=scoop-ua; ca=scoo…
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by fleimgruber** [comment]
Additional information: When trying to open RStudio on the CLI via `rstudio` this error is printed multiple times:

```
ERROR: The system was unable to find the specified registry key or value.
```

so I guess the R installation did not set registry keys or not the ones that RStudio expects? A quick search pointed me to these keys:

```
HKEY_LOCAL_MACHINE\Software\R-core\R\Current Version
HKEY_LOCAL_MACHINE\Software\R-core\R\version\InstallPath
```

Which are not set after installing R via `scoop install r`.

**Comment by hungpham3112** [comment]
Thank you for the solution.

The system variable for R should be set via "Environment Variables".
![image](https://user-images.githubusercontent.com/75968004/222150072-c555dfed-08f1-4da0-a35a-2f1876bc6872.png)

I confirm the solution of @fleimgruber works.

**Comment by niheaven** [comment]
`desktop.ini` works, and please update buckets and try `scoop update rstudio -f` (remember removing envvar `RSTUDIO_WHICH_R`)

**Comment by niheaven** [comment]
Closed by https://github.com/ScoopInstaller/Extras/commit/fbcf30f6a858d2ae5a7483e094c0e5841c2c32fd

**Comment by hungpham3112** [comment]
The problem is still there.

**Comment by hungpham3112** [comment]
> What's in your `$env:AppData\RStudio\desktop.ini`? It's under `Roaming` subdir of AppData

I deleted the old `RStudio` folder and reinstall rstudio. It seems rstudio still use the old state in RStudio folder. Thanks for your help.
