### ISSUE TITLE
authy@2.2.3: Decompress error

### ISSUE THREAD

**Issue by tordenflesk** [ScoopInstaller/Extras#10538]
Failed to extract files from C:\Users\Tordenflesk\scoop\apps\authy\2.2.3\authy-2.2.3-full.nupkg.
Log file:
  ~\scoop\apps\authy\2.2.3\7zip.log:

7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 84580957 bytes (81 MiB)

Extracting archive: C:\Users\Tordenflesk\scoop\apps\authy\2.2.3\authy-2.2.3-full.nupkg
--
Path = C:\Users\Tordenflesk\scoop\apps\authy\2.2.3\authy-2.2.3-full.nupkg
Type = zip
ERRORS:
Unexpected end of archive
Physical Size = 84580957
Characteristics = Local

Sub items Errors: 1

Archives with Errors: 1

Open Errors: 1

Sub items Errors: 1

**Comment by StarsbySea** [comment]
Duplicate with #10532, please consider closing this issue and leaving a comment under the previous issue.

**Comment by HUMORCE** [comment]
Dupcalite of #10532
