### ISSUE TITLE
authy@2.2.3: decompress error

### ISSUE THREAD

**Issue by Joker1718** [ScoopInstaller/Extras#10540]
Failed to extract files from C:\Users\Administrator\scoop\apps\authy\2.2.3\authy-2.2.3-full.nupkg.
Log file:
 ~\scoop\apps\authy\2.2.3\7zip.log

**Comment by StarsbySea** [comment]
Duplicate with #10532, please consider closing this issue and leaving a comment under the previous issue.

**Comment by HUMORCE** [comment]
Dupcalite of #10532
