### ISSUE TITLE
sweethome3d@7.0.2: decompress error

### ISSUE THREAD

**Issue by tssva** [ScoopInstaller/Extras#10547]
Decompressing the 7-zip for Sweet Home 3D fails. The extract_dir is "SweetHome3D-7.0.2-portable". A subdirectory of the extract_dir is the macOS app for Sweet Home 3D. The macOS app directory contains symlinks which 7-zip fails trying to create which causes the installation of the scoop package to fail.

PS C:\Users\Tim> scoop install sweethome3d
Installing 'sweethome3d' (7.0.2) [64bit] from extras bucket
Loading SweetHome3D-7.0.2-portable.7z from cache
Checking hash of SweetHome3D-7.0.2-portable.7z ... ok.
Extracting SweetHome3D-7.0.2-portable.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Tim\scoop\apps\sweethome3d\7.0.2\SweetHome3D-7.0.2-portable.7z.
Log file:
  ~\scoop\apps\sweethome3d\7.0.2\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=sweethome3d%407.0.2%3a+decompress+error

**Comment by mook** [comment]
Note that by default users in the Administrators group have [permissions to create symlinks](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links), so the issue might not reproduce for those users (as in #9960).  This also means it's possible to work around the issue if you're willing to grant that to the relevant user.

This is still an issue for sweethome3d 7.1.
