### ISSUE TITLE
[Request]: MuseHub (beta)

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#10599]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

MuseHub (beta)

### Description

Muse Hub simplifies the process of getting some of the world’s most popular creative apps, quickly and securely. Get MuseScore, Audacity and others with just one click. Enjoy incredible and exclusive free content like the amazing Muse Sounds, MuseFX and drag n' drop SFX to enhance your creative projects.

### Homepage

https://www.musehub.com/

### Download Link(s)

https://pub-c7a32e5b5d834ec9aeef400105452a42.r2.dev/Muse_Hub_Beta.exe

### Some Indication of Popularity/Repute

It is beta version of this -> https://github.com/ScoopInstaller/Extras/issues/10598

**Comment by sedlund** [comment]
non stable goes in the Versions bucket: 
 https://github.com/ScoopInstaller/Versions

**Comment by anderlli0053** [comment]
> non stable goes in the Versions bucket: 
>  https://github.com/ScoopInstaller/Versions

I'll create another issue in versions for this then, thanks!
