### ISSUE TITLE
[Request]: Add thunderbird beta version

### ISSUE THREAD

**Issue by dsm** [ScoopInstaller/Extras#10597]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

thunderbird-beta

### Description

normal thunderbird version ok but no beta version in scoop

### Homepage

https://www.thunderbird.net/

### Download Link(s)

https://www.thunderbird.net/en-US/download/beta/

### Some Indication of Popularity/Repute

can you add thunderbird beta version ?

**Comment by sedlund** [comment]
I believe non stable versions go in Versions bucket:  https://github.com/ScoopInstaller/Versions/
