### ISSUE TITLE
[Bug]: librewolf not updating to 110.0

### ISSUE THREAD

**Issue by monosans** [ScoopInstaller/Extras#10591]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

librewolf

### Expected/Current Behaviour

Librewolf version in bucket is 109.0.1-2, although 110.0-1 came out a couple of days ago.

https://github.com/ScoopInstaller/Extras/actions/runs/4249420704/jobs/7389557014#step:3:612

### Possible Solution

For some reason, the GitLab API for the new version of Librewolf gives a completely different download link that regex can't find.

Link for 109.0.1: <https://gitlab.com/librewolf-community/browser/windows/uploads/57d8047683deafd009c94df4d7dabda3/librewolf-109.0.1-2.en-US.win64-portable.zip>
Link for 110.0: <https://gitlab.com/librewolf-community/browser/windows/-/package_files/69100830/download>

**Comment by sedlund** [comment]
This is also currently breaking the update of the Extras bucket:

https://github.com/ScoopInstaller/Extras/actions/runs/4259353120/jobs/7411494923#step:3:578

see notes here: https://github.com/ScoopInstaller/Extras/issues/10596#issuecomment-1442898275

**Comment by zachvlat** [comment]
Is there a way to manually update librewolf without breaking stuff? I can't use it right now for security reasons...

**Comment by basketshoe** [comment]
The link to download the version 111.0 is https://gitlab.com/librewolf-community/browser/windows/-/package_files/73020469/download#/librewolf-111.0.1-1.en-US.win64-portable.zip and I'm pretty sure it can be added to scoop
