### ISSUE TITLE
Obsidian update to version 1.1.15

### ISSUE THREAD

**Issue by FlorianMittag** [ScoopInstaller/Extras#10594]
[Obsidian](https://obsidian.md/) has a new version [1.1.15](https://github.com/obsidianmd/obsidian-releases/releases/tag/v1.1.15), which is not reflected in the bucket, yet.

**Comment by sedlund** [comment]
Github action is failing to update the whole Extras bucket automatically.

see notes here: https://github.com/ScoopInstaller/Extras/issues/10596#issuecomment-1442898275

**Comment by FlorianMittag** [comment]
Obsolete through commit 59a1432
