### ISSUE TITLE
Tabby Update to version 1.0.189

### ISSUE THREAD

**Issue by W0n9** [ScoopInstaller/Extras#10592]
I noticed that [tabby](https://github.com/Eugeny/tabby) have been updated to version [1.0.189](https://github.com/Eugeny/tabby/releases/tag/v1.0.189), but scoop stayed at version 1.0.188.

**Comment by sedlund** [comment]
Github action is failing to update the whole Extras bucket automatically.

see notes here: https://github.com/ScoopInstaller/Extras/issues/10596#issuecomment-1442898275
