### ISSUE TITLE
[Bug]: netbeans version

### ISSUE THREAD

**Issue by Zalk0** [ScoopInstaller/Extras#10613]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

netbeans

### Expected/Current Behaviour

Autoupdating to v17

### Possible Solution

The homepage is incorrect so checkver isn't working.

**Comment by sedlund** [comment]
Github action is failing to update the whole Extras bucket automatically.

see notes here: https://github.com/ScoopInstaller/Extras/issues/10596#issuecomment-1442898275
