### ISSUE TITLE
[Bug]: Termius version is not correct

### ISSUE THREAD

**Issue by xsm1997** [ScoopInstaller/Extras#10622]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

termius

### Expected/Current Behaviour

The version is not the latest version but the hash is correct. Users cannot update the app but can fresh install the app.

Checkver.ps1 works and can auto update the manifest file. It seems that the bot had not update this app. #10602 updated the hash but did not update the app version.

### Steps to Reproduce

```console
scoop update termius
```

### Possible Solution

Update the manifest file and change the version to 7.56.3.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
a94065816 (HEAD -> master, origin/master, origin/HEAD) thisiswin11@1.4.1: Fix hash (Closes #10620)

'java' bucket:
8ac344ed (HEAD -> master, origin/master, origin/HEAD) temurin19-nightly-jdk: Update to version 19.0.2-7.0.202302250348

'main' bucket:
5e254d482 (HEAD -> master, origin/master, origin/HEAD) x265: Update to version 3.5+95-38cf1c3

'nonportable' bucket:
bfb3c02 (HEAD -> master, origin/master, origin/HEAD) spotx-np: Update to version 1.7-20230226-02533c

'versions' bucket:
e0ee459ae (HEAD -> master, origin/master, origin/HEAD) firefox-nightly: Update to version 112.0a1.20230226094119
```

### Scoop Config

```console
PS> scoop config

shim                  : kiennq
last_update           : 2023/2/27 0:10:50
aria2-enabled         : True
aria2-warning-enabled : False
scoop_branch          : master
scoop_repo            : https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22623
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by sedlund** [comment]
https://github.com/ScoopInstaller/GithubActions/issues/32

**Comment by Zliced13** [comment]
Termius is now at the correct version, https://github.com/ScoopInstaller/Extras/blob/master/bucket/termius.json
