### ISSUE TITLE
[Bug]: install miniconda3 4.12.0 failed

### ISSUE THREAD

**Issue by yvvw** [ScoopInstaller/Extras#10826]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

miniconda3

### Expected/Current Behaviour

install success

### Steps to Reproduce

```console
PS> scoop install extras/miniconda3
Installing 'miniconda3' (23.1.0-1) [64bit] from extras bucket
Loading Miniconda3-py310_23.1.0-1-Windows-x86_64.exe from cache.
Checking hash of Miniconda3-py310_23.1.0-1-Windows-x86_64.exe ... ok.
Running installer script...
Linking D:\Program Files\Scoop\apps\miniconda3\current => D:\Program Files\Scoop\apps\miniconda3\23.1.0-1
Creating shim for 'python'.
Creating shim for 'pythonw'.
Can't shim 'pythonw.exe': File doesn't exist.
```

### Possible Solution

idk

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'dorado' bucket:
cc333026 (HEAD -> master, origin/master, origin/HEAD) openai-translator: Update to version 0.0.32

'extras' bucket:
0aa15b045 (HEAD -> master, origin/master, origin/HEAD) onecommander: Update to version 3.37.1.0

'java' bucket:
9d5f0e45 (HEAD -> master, origin/master, origin/HEAD) zulufx-jre: Update to version 20.28.85

'main' bucket:
272f880e4 (HEAD -> master, origin/master, origin/HEAD) trid: Update to version 2.24-23.03.21
```

### Scoop Config

```console
PS> scoop config

last_update           : 2023/3/22 13:05:59
aria2-warning-enabled : False
aria2-enabled         : True
scoop_repo            : https://github.com/ScoopInstaller/Scoop
scoop_branch          : master
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by niheaven** [comment]
Could not reproduce. What's under you `apps\miniconda3\current\` now?

**Comment by yvvw** [comment]
Thank you for your response. The previous version was working fine, but after updating, this error occurred.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/15168529/226843488-f802c708-8eee-4f1b-ab75-9d262d20a728.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/15168529/226843620-349a9ee9-c625-4eda-8e04-ba61e82a7df4.png">
<img width="232" alt="image" src="https://user-images.githubusercontent.com/15168529/226843654-92af3314-00be-4183-9481-3c9629941e8e.png">
<img width="302" alt="image" src="https://user-images.githubusercontent.com/15168529/226843677-ea290ac4-e8bc-43e6-b785-54d6a24eae54.png">
<img width="267" alt="image" src="https://user-images.githubusercontent.com/15168529/226843706-a84b1809-9b47-45a1-b7a1-e6d1ce869ee2.png">

**Comment by niheaven** [comment]
![image](https://user-images.githubusercontent.com/5832170/226943137-2a434403-b113-4117-9ad2-fddb120a1377.png)
![image](https://user-images.githubusercontent.com/5832170/226943200-592b89eb-fb57-448d-8b0e-a22a615f2484.png)

It works for me...

**Comment by yvvw** [comment]
Is there any way to fix installation failure caused by spaces in the installation path?
![image](https://user-images.githubusercontent.com/15168529/226970975-59a201e4-f337-4868-815c-cf5974049e1c.png)
![image](https://user-images.githubusercontent.com/15168529/226970508-0c3c8ee9-5c81-46aa-a0db-d2c987406f1c.png)

**Comment by ackshually** [comment]
Having same issue while installing anaconda3.

scoop install anaconda3
Installing 'anaconda3' (2023.03) [64bit] from extras bucket
Anaconda3-2023.03-Windows-x86_64.exe (786.0 MB) [===========================================================================================] 100%
Checking hash of Anaconda3-2023.03-Windows-x86_64.exe ... ok.
Running installer script...
Installing Anaconda 3. This can take up to 30 minutes on an HDD.
Linking ~\scoop\apps\anaconda3\current => ~\scoop\apps\anaconda3\2023.03
Creating shim for 'python'.
Creating shim for 'pythonw'.
Can't shim 'pythonw.exe': File doesn't exist.

**scoop --version**
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
cfd1f8504 (HEAD -> master, origin/master, origin/HEAD) signal: Update to version 6.11.0

'main' bucket:
02c87513c (HEAD -> master, origin/master, origin/HEAD) x265: Update to version 3.5+96-c07d076

'nonportable' bucket:
d716697 (HEAD -> master, origin/master, origin/HEAD) spotx-np: Update to version 1.7-20230322-019a2c

'sysinternals' bucket:
42eb76d (HEAD -> main, origin/main, origin/HEAD) sysinternals-suite: Update to version 2023.03.09

**scoop config**
last_update       scoop_branch scoop_repo
-----------       ------------ ----------
23-Mar-23 3:49:03 master       https://github.com/ScoopInstaller/Scoop

**$PSVersionTable**

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by silicer** [comment]
> 

Same issue here.

**Comment by niheaven** [comment]
Ping @Lutra-Fs

**Comment by Lutra-Fs** [comment]
I’ll have a look. However I cannot reproduce in my machine. If anyone could have a screenshot about `scoop/apps/miniconda`? Is there a setup.exe?

**Comment by Lutra-Fs** [comment]
@niheaven can you merge the old version to `versions` bucket? There is a PR on that

**Comment by Lutra-Fs** [comment]
> > Having same issue while installing anaconda3.
> 
> Same issue here.

Is there a space in your scoop folder?

**Comment by niheaven** [comment]
Setup is there, now it seems like spaces.

**Comment by ackshually** [comment]
no spaces here

**Comment by silicer** [comment]
> > > Having same issue while installing anaconda3.
> > 
> > 
> > Same issue here.
> 
> Is there a space in your scoop path? @silicer @ackshually

no

**Comment by ackshually** [comment]
same here

**Comment by Lutra-Fs** [comment]
Hi @ackshually is your issue related to anaconda3?

**Comment by Lutra-Fs** [comment]
Anaconda3 needs to be update as well. I just missed with that in PR. It is an expected behavior now.

**Comment by ackshually** [comment]
for me it's anaconda3

**Comment by Lutra-Fs** [comment]
Pls raise a new issue regarding on anaconda3

**Comment by Lutra-Fs** [comment]
> Thank you for your response. The previous version was working fine, but after updating, this error occurred.
> 
> <img alt="image" width="426" src="https://user-images.githubusercontent.com/15168529/226843488-f802c708-8eee-4f1b-ab75-9d262d20a728.png">
> 
> <img alt="image" width="549" src="https://user-images.githubusercontent.com/15168529/226843620-349a9ee9-c625-4eda-8e04-ba61e82a7df4.png">
> 
> <img alt="image" width="232" src="https://user-images.githubusercontent.com/15168529/226843654-92af3314-00be-4183-9481-3c9629941e8e.png">
> 
> <img alt="image" width="302" src="https://user-images.githubusercontent.com/15168529/226843677-ea290ac4-e8bc-43e6-b785-54d6a24eae54.png">
> 
> <img alt="image" width="267" src="https://user-images.githubusercontent.com/15168529/226843706-a84b1809-9b47-45a1-b7a1-e6d1ce869ee2.png">

@yvvw could you try using a elevated shell?

**Comment by yvvw** [comment]
@Lutra-Fs Lu I copied the installation command and modified the \D parameter to a path without spaces, and I was able to install it successfully.

All installations failed on git shell, pwsh, powershell7, and cmd.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/15168529/227143136-cc17ff94-101a-412e-ad74-620ef6e1c590.png">

**Comment by Lutra-Fs** [comment]
> @Lutra-Fs Lu I copied the installation command and modified the \D parameter to a path without spaces, and I was able to install it successfully.
> 
> All installations failed on git shell, pwsh, powershell7, and cmd.
> 
> <img alt="image" width="1003" src="https://user-images.githubusercontent.com/15168529/227143136-cc17ff94-101a-412e-ad74-620ef6e1c590.png">

I am able to reproduce this issue with scoop whose installation path includes space.

**Comment by Lutra-Fs** [comment]
> @Lutra-Fs Lu I copied the installation command and modified the \D parameter to a path without spaces, and I was able to install it successfully.
> 
> All installations failed on git shell, pwsh, powershell7, and cmd.
> 
> <img alt="image" width="1003" src="https://user-images.githubusercontent.com/15168529/227143136-cc17ff94-101a-412e-ad74-620ef6e1c590.png">

Hi @yvvw , after some investigation, there is an extra confirmation process when there is a space in your installation path, which cannot be bypassed in CLI. I would like to suggest you raise an issue upstream.
![image](https://user-images.githubusercontent.com/36790218/227229034-e75294f6-8f26-4695-8ffe-c90a15e167da.png)

**Comment by Lutra-Fs** [comment]
Maybe this is an intended behaviour, see https://github.com/conda/constructor/issues/463
