### ISSUE TITLE
[Request]: Kicad 7.0.1

### ISSUE THREAD

**Issue by mesmariusz** [ScoopInstaller/Extras#10865]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Kicad

### Description

version 7.0.1

### Homepage

https://www.kicad.org/download/windows/

### Download Link(s)

https://github.com/KiCad/kicad-source-mirror/releases/download/7.0.1/kicad-7.0.1-x86_64.exe

### Some Indication of Popularity/Repute

Who is responsible about release new Kicad installers for scoop ?
Is the version 7.0.1 planed to be introduced and when ?

**Comment by ca1e** [comment]
/pull/10579
