### ISSUE TITLE
[Bug]: Chrome Update broken

### ISSUE THREAD

**Issue by alclonky** [ScoopInstaller/Extras#10877]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

googlechrome

### Expected/Current Behaviour

google chrome update (normal and beta (versions bucket)) is broken since Google droped Windows 7 Support.

### Steps to Reproduce

```console
scoop update googlechrome
installs 109 and not 111
```

### Possible Solution

PR in UpdateTracker with fix
https://github.com/ScoopInstaller/UpdateTracker/pull/13

### Scoop and Buckets Version

```console
not relevant
```

### Scoop Config

```console
not relevant
```

### PowerShell Version

```console
not relevant
```

**Comment by unwillinglyawesome** [comment]
@alclonky thank you for mentioning this problem. I was thinking it would be a good idea to create a new manifest `googlechrome109` in order to enable Scoop to install Google Chrome on Windows 8.1 and older.

**Comment by alclonky** [comment]
Its not on me to decide if Scoop needs to support EOL Windows Versions.
But the Chrome Update is broken now! And should be fixed as soon as possible.

**Comment by Lutra-Fs** [comment]
> /cc @Lutra-Fs

This one has been reported months ago. I have add some about GPL notice for chrome series check. Once it get merged I will fix it immediately. Already fixed upstream
