### ISSUE TITLE
rtss@7.3.4: decompress error

### ISSUE THREAD

**Issue by meltylang** [ScoopInstaller/Extras#10886]
ERROR Exit code was 7!
Failed to extract files from C:\SCOOP\apps\rtss\7.3.4\RTSSSetup*.exe.

**Comment by soarqin** [comment]
You can change `"Expand-7zipArchive \"$dir\\RTSSSetup*.exe\" -Removal",` to `"Expand-7zipArchive \"$dir\\*RTSSSetup*.exe\" -Removal",` in `bucket\rtss.json` as a temporary solution.

**Comment by RavenMacDaddy** [comment]
Confirmed to successfully install with the suggested change, which makes sense; newer versions seems to append Guru3D.com to the beginning to attribute its source. 

Making a PR.
