### ISSUE TITLE
[Request]: DuckDuckGo Browser

### ISSUE THREAD

**Issue by basketshoe** [ScoopInstaller/Extras#10928]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

DuckDuckGo Browser

### Description

Tracker and ad-blocking browser

### Homepage

https://duckduckgo.com/windows

### Download Link(s)

https://staticcdn.duckduckgo.com/windows-desktop-browser/DuckDuckGo.appinstaller

### Some Indication of Popularity/Repute

Browser of the widely known DDG search engine

**Comment by StarsbySea** [comment]
At the moment an invitation code is required to use the software, perhaps we'll start working on the manifest file when it starts public testing.
![图片](https://user-images.githubusercontent.com/66008060/230719010-3003b59d-b48b-4c4e-b178-bedd02957334.png)

**Comment by StarsbySea** [comment]
At the moment an invitation code is required to use the software, perhaps we'll start working on the manifest file when it starts public testing.
![图片](https://user-images.githubusercontent.com/66008060/230719402-54c9c263-d392-4f56-b4f7-c2a99c549d8e.png)

**Comment by basketshoe** [comment]
Not anymore in private beta
