### ISSUE TITLE
[Request]: Tracy

### ISSUE THREAD

**Issue by Likeny3** [ScoopInstaller/Extras#10942]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Tracy

### Description

A real time, nanosecond resolution, remote telemetry, hybrid frame and sampling profiler for games and other applications.

### Homepage

https://github.com/wolfpld/tracy

### Download Link(s)

https://github.com/wolfpld/tracy/releases

### Some Indication of Popularity/Repute

Repository watched by 73, forked by 387, starred by 5.4k.

**Comment by aliesbelik** [comment]
Resolved by #11681.
