### ISSUE TITLE
[Request]: neovide 0.10.4

### ISSUE THREAD

**Issue by xarthurx** [ScoopInstaller/Extras#10947]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [ ] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

neovide

### Description

A popular GUI for neovim

### Homepage

neovide.dev/

### Download Link(s)

https://github.com/neovide/neovide/releases/tag/0.10.4

### Some Indication of Popularity/Repute

The package exist in the `extra` bucket, but was not automatically updated.

`v0.10.4` is critical as the current `v0.10.3` version doesn't work on the latest stable `neovim - v0.9.0`.

**Comment by HUMORCE** [comment]
#10977
