### ISSUE TITLE
add pandoc

### ISSUE THREAD

**Issue by guillermooo** [ScoopInstaller/Extras#11]
Pandoc is a Haskell library/cmdline tool to convert many formats.

http://johnmacfarlane.net/pandoc/

**Comment by DOFfactory** [comment]
why did this got removed?

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Main/blob/master/bucket/pandoc.json

**Comment by DOFfactory** [comment]
thanks, this is news to me
