### ISSUE TITLE
openai-translator@0.0.37: decompress error

### ISSUE THREAD

**Issue by joostshao** [ScoopInstaller/Extras#11021]
PS C:\Users\Administrator> scoop install openai-translator
WARN  Purging previous failed installation of openai-translator.
ERROR 'openai-translator' isn't installed correctly.
Removing older version (0.0.37).
'openai-translator' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'openai-translator' (0.0.37) [64bit] from extras bucket
Loading OpenAI.Translator_0.0.37_x64_en-US.msi from cache.
Checking hash of OpenAI.Translator_0.0.37_x64_en-US.msi ... ok.
Extracting OpenAI.Translator_0.0.37_x64_en-US.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\scoop\apps\openai-translator\0.0.37\OpenAI.Translator_0.0.37_x64_en-US.msi.
Log file:
  C:\scoop\apps\openai-translator\0.0.37\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=openai-translator%400.0.37%3a+decompress+error

**Comment by joostshao** [comment]
PS C:\Users\Administrator> cat C:\scoop\apps\openai-translator\0.0.37\msi.log
=== Logging started: 2023/4/12  14:47:42 ===
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2503. The arguments are: , ,
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2502. The arguments are: , ,
=== Logging stopped: 2023/4/12  14:47:42 ===

**Comment by HUMORCE** [comment]
`Extracting OpenAI.Translator_0.0.37_x64_en-US.msi ... ERROR Exit code was 1603!`:

<html>
<body>


ERROR_INSTALL_FAILURE | 1603 | A fatal error occurred during installation.
-- | -- | --



</body>
</html>

Cannot reproduce. try toggle this config item or reboot pc before install the app:

`scoop config use_lessmsi true|false`.

```
> scoop install openai-translator -u
WARN  Scoop is out of date.
Installing 'openai-translator' (0.0.37) [64bit] from extras bucket
OpenAI.Translator_0.0.37_x64_en-US.msi (9.9 MB) [====================================================================================] 100%
Checking hash of OpenAI.Translator_0.0.37_x64_en-US.msi ... ok.
Extracting OpenAI.Translator_0.0.37_x64_en-US.msi ... done.
Linking ~\scoop\apps\openai-translator\current => ~\scoop\apps\openai-translator\0.0.37
Creating shortcut for OpenAI Translator (OpenAI Translator.exe)
'openai-translator' (0.0.37) was installed successfully!
```

**Comment by joostshao** [comment]
> `Extracting OpenAI.Translator_0.0.37_x64_en-US.msi ... ERROR Exit code was 1603!`:
> 
> ERROR_INSTALL_FAILURE	1603	A fatal error occurred during installation.
> Cannot reproduce. try toggle this config item or reboot pc before install the app:
> 
> `scoop config use_lessmsi true|false`.
> 
> ```
> > scoop install openai-translator -u
> WARN  Scoop is out of date.
> Installing 'openai-translator' (0.0.37) [64bit] from extras bucket
> OpenAI.Translator_0.0.37_x64_en-US.msi (9.9 MB) [====================================================================================] 100%
> Checking hash of OpenAI.Translator_0.0.37_x64_en-US.msi ... ok.
> Extracting OpenAI.Translator_0.0.37_x64_en-US.msi ... done.
> Linking ~\scoop\apps\openai-translator\current => ~\scoop\apps\openai-translator\0.0.37
> Creating shortcut for OpenAI Translator (OpenAI Translator.exe)
> 'openai-translator' (0.0.37) was installed successfully!
> ```

thank you , It worked out
