### ISSUE TITLE
[Bug]: [appflowy] app_flowy.exe -> AppFlowy.exe

### ISSUE THREAD

**Issue by Konecho** [ScoopInstaller/Extras#11045]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

appflowy

### Expected/Current Behaviour

Creating shortcut for AppFlowy (app_flowy.exe) failed: Couldn't find C:\Users\\scoop\apps\appflowy\current\app_flowy.exe

### Steps to Reproduce

```console
.
```

### Possible Solution

rename it

### Scoop and Buckets Version

```console
.
```

### Scoop Config

```console
.
```

### PowerShell Version

```console
.
```

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/commit/a517c9ad6590fb54468883827603fdf2e94b4bde
