### ISSUE TITLE
[Bug]: Keyviz@1.0.6: decompress error

### ISSUE THREAD

**Issue by tch123** [ScoopInstaller/Extras#11090]
ERROR Exit code was 1!
Failed to extract files from C:\Users\name\scoop\apps\Keyviz\1.0.6\Keyviz-v1.0.6.exe.
Log file:
  ~\scoop\apps\Keyviz\1.0.6\innounp.log

-------------
Signature detected: Inno Setup Setup Data (6.1.0) (u)
This is not directly supported, but i'll try to unpack it as version 6000
; Version detected: 6100 (Unicode)
Unpacking failed. This version is not supported.

**Comment by HUMORCE** [comment]
Cannot reproduce.

```
❯ scoop install keyviz
Installing 'keyviz' (1.0.6) [64bit] from extras bucket
keyviz-v1.0.6.zip (8.4 MB) [==============================================================================================] 100%
Checking hash of keyviz-v1.0.6.zip ... ok.
Extracting keyviz-v1.0.6.zip ... done.
Running pre_install script...
Linking ~\scoop\apps\keyviz\current => ~\scoop\apps\keyviz\1.0.6
Creating shortcut for Keyviz (keyviz.exe)
'keyviz' (1.0.6) was installed successfully!
'keyviz' suggests installing 'extras/vcredist2022'.
```

**Comment by HUMORCE** [comment]
Fell
