### ISSUE TITLE
Kate@22.12.3-2008: decompress error

### ISSUE THREAD

**Issue by Ryonez** [ScoopInstaller/Extras#11102]
ERROR 'Kate' isn't installed correctly.
Kate: 22.08.0 -> 22.12.3-2008
Updating one outdated app:
Updating 'Kate' (22.08.0 -> 22.12.3-2008)
Downloading new version
Downloading https://binary-factory.kde.org/job/Kate_Release_win64/2008/artifact/kate-22.12.3-2008-windows-cl-msvc2019-x86_64.7z (65.7 MB)...
Checking hash of kate-22.12.3-2008-windows-cl-msvc2019-x86_64.7z ... ok.
Uninstalling 'Kate' (22.08.0)
Installing 'Kate' (22.12.3-2008) [64bit] from extras bucket
Loading kate-22.12.3-2008-windows-cl-msvc2019-x86_64.7z from cache
Extracting kate-22.12.3-2008-windows-cl-msvc2019-x86_64.7z ... Invoke-ExternalCommand : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At C:\Users\ryonia\scoop\apps\scoop\current\lib\decompress.ps1:45 char:38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand
Failed to extract files from C:\Users\ryonia\scoop\apps\Kate\22.12.3-2008\kate-22.12.3-2008-windows-cl-msvc2019-x86_64.7z.
Log file:
~\scoop\apps\Kate\22.12.3-2008\7zip.log
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=Kate%4022.12.3-2008%3a+decompress+error

**Comment by HUMORCE** [comment]
Cannot reproduce. please provide more information, e.g. `~\scoop\apps\Kate\22.12.3-2008\7zip.log`

```
❯ scoop install kate
Installing 'kate' (22.12.3-2008) [64bit] from extras bucket
kate-22.12.3-2008-windows-cl-msvc2019-x86_64.7z (65.7 MB) [===============================================================] 100%
Checking hash of kate-22.12.3-2008-windows-cl-msvc2019-x86_64.7z ... ok.
Extracting kate-22.12.3-2008-windows-cl-msvc2019-x86_64.7z ... done.
Linking ~\scoop\apps\kate\current => ~\scoop\apps\kate\22.12.3-2008
Creating shim for 'kate'.
Creating shortcut for Kate (kate.exe)
'kate' (22.12.3-2008) was installed successfully!
```

**Comment by Ryonez** [comment]
There's no such log in that location.

Looking at the log above, it's failing validation before actually invoking the external command.

**Comment by HUMORCE** [comment]
```
where.exe 7z
scoop which 7z
get-command 7z
```

**Comment by Ryonez** [comment]
Looking at those, scoop's version of 7zipdidn't exist. I un-installed it, scoop got it it again when I tried installing Kate again, and this time it went through.

Thank you for those commands, let me find that 7zip didn't exist. Pity it didn't fall back on my system's copy of 7zip.

**Comment by HUMORCE** [comment]
> Pity it didn't fall back on my system's copy of 7zip.

```
❯ scoop help config

...
Settings
--------

use_external_7zip: $true|$false
      External 7zip (from path) will be used for archives extraction.
...
```
