### ISSUE TITLE
[Request]: Lobster programming language

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#11118]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

lobster

### Description

The Lobster Programming Language

### Homepage

https://strlen.com/lobster/

### Download Link(s)

https://github.com/aardappel/lobster/releases

### Some Indication of Popularity/Repute

https://github.com/aardappel/lobster

**1,8k stars
97 forks**

[Creator GitHub profile](https://github.com/aardappel)

**Comment by aliesbelik** [comment]
Already in `main` (ScoopInstaller/Main#4977).
