### ISSUE TITLE
Update Obsidian to 1.2.7

### ISSUE THREAD

**Issue by ilvetz** [ScoopInstaller/Extras#11204]
[Obsidian](https://obsidian.md/) has a new version [1.2.7](https://github.com/obsidianmd/obsidian-releases/releases/tag/v1.2.7), which is not reflected in the bucket, yet.

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/commit/36d39df81a31f793bc0d8e1e71aa380f91ef13b7
