### ISSUE TITLE
[Request]: Add VSCodium shim

### ISSUE THREAD

**Issue by Kreijstal** [ScoopInstaller/Extras#11248]
the package vscodium exists, but its not added to path, or shimmed, it'd be nice to get it added on path, despite it being a graphical interface

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/blob/35a7b83684e91c4cb1e4846dacd1cae7b504bf03/bucket/vscodium.json#L24

`codium.exe`

**Comment by Kreijstal** [comment]
excuse me how you're supposed to read that from the manifest?

![image](https://github.com/ScoopInstaller/Extras/assets/2415206/fe8f96e7-cae6-4108-81ca-0cba8c4314ef)

There is not `codium.exe` there, only vscodium..

**Comment by HUMORCE** [comment]
> excuse me how you're supposed to read that from the manifest?

No, but I learned that the `bin` dir has been added to the $env:PATH.
