### ISSUE TITLE
[Request]: retrobar

### ISSUE THREAD

**Issue by vanhecke** [ScoopInstaller/Extras#11258]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

retrobar

### Description

 Classic Windows 95, 98, Me, 2000, XP, Vista taskbar for modern versions of Windows .

### Homepage

https://github.com/dremin/RetroBar

### Download Link(s)

https://github.com/dremin/RetroBar/releases/tag/v1.12.39

### Some Indication of Popularity/Repute

1.6k stars, 143 forks, >2 years old.

Single binary, runs portable.

**Comment by foxydevloper** [comment]
Retrobar doesn't run completely portably, it stores user config in %LocalAppData%/RetroBar

**Comment by aliesbelik** [comment]
Completed in #12483.
