### ISSUE TITLE
winaero-tweaker@01.52.0.0 hash check failed

### ISSUE THREAD

**Issue by ShawnTheShadow** [ScoopInstaller/Extras#11259]
### Prerequisites

- [X] I have used the predefined issue title. (e.g. "xxx@xxx&#58; hash check failed")
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name and Version

winaero-tweaker@01.52.0.0

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/commit/5e1ef7d22a4bacbd8cd2c7209a8385f71ff6bf55
