### ISSUE TITLE
[Request]: TETR.IO Desktop

### ISSUE THREAD

**Issue by nonperforming** [ScoopInstaller/Extras#11268]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

tetrio

### Description

TETR.IO is a free-to-win modern yet familiar online stacker. Play multiplayer games against friends and foes all over the world, or claim a spot on the leaderboards - the stacker future is yours!

### Homepage

https://tetr.io/

### Download Link(s)

https://tetr.io/about/desktop/builds/TETR.IO%20Setup.exe

### Some Indication of Popularity/Repute

https://ch.tetr.io/ - "6,856,717 players"
https://www.twitch.tv/directory/game/TETR.IO - "35.5k followers"

**Comment by nonperforming** [comment]
Appears to use a custom self-updater

**Comment by anderlli0053** [comment]
@nonperforming  This should go into ['games'](https://github.com/Calinou/scoop-games) bucket!

**Comment by nonperforming** [comment]
Moved to ['games'](https://github.com/Calinou/scoop-games/issues/942) bucket
