### ISSUE TITLE
[Update]: Chatterino7 to 7.4.4 version

### ISSUE THREAD

**Issue by xd-mau5** [ScoopInstaller/Extras#11270]
The current version of Chatterino7 in scoop is 7.4.3. the lastest version is the 7.4.4
https://github.com/SevenTV/chatterino7/releases/tag/v7.4.4

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/commit/35c2f51dd9aa1cf2e7318108c67e091612bfebc5
