### ISSUE TITLE
[Bug]: anaconda3@2023.03-1 failed to install on PowerShell Core(pwsh)

### ISSUE THREAD

**Issue by Lutra-Fs** [ScoopInstaller/Extras#11309]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

anaconda3

### Expected/Current Behaviour

```
$scoop install anaconda3
Installing 'anaconda3' (2023.03-1) [64bit] from extras bucket
Loading Anaconda3-2023.03-1-Windows-x86_64.exe from cache
Checking hash of Anaconda3-2023.03-1-Windows-x86_64.exe ... ok.
Running pre_install script...
Running installer script...
Installing Anaconda 3. This can take up to 30 minutes on an HDD.
Linking ~\scoop\apps\anaconda3\current => ~\scoop\apps\anaconda3\2023.03-1
Creating shim for 'python'.
Creating shim for 'pythonw'.
Can't shim 'pythonw.exe': File doesn't exist.
```

### Steps to Reproduce

Using PowerShell Core 7 and successfully reproducing the issue.

### Possible Solution

As a workaround pls use windows powershell to install anaconda

### Scoop and Buckets Version

```console
--
```

### Scoop Config

```console
--
```

### PowerShell Version

```console
--
```

**Comment by Lutra-Fs** [comment]
originally posted in https://github.com/ScoopInstaller/Extras/issues/10829

**Comment by fhb302** [comment]
I have the same problem when I use the powershell7 and install the anaconda, it buzzled me a lot of time, hope it can be fix in the fulture.
