### ISSUE TITLE
firefoxpwa 2.6.0: not runing

### ISSUE THREAD

**Issue by candrapersada** [ScoopInstaller/Extras#11321]
how to run FirefoxPWA on Scoop aftar install?
![gambar](https://github.com/ScoopInstaller/Extras/assets/36833664/0af37559-41d0-4ba4-9b3b-6ce1fcc75563)

**Comment by CryoRenegade** [comment]
@candrapersada can you try now?

**Comment by candrapersada** [comment]
not working 2.6.2

**Comment by HUMORCE** [comment]
> yes but not working 2.6.2

I tested it and it works

**Comment by candrapersada** [comment]
but it happened before completed #11499
and now it works fine
