### ISSUE TITLE
[Request]: PowerShell Core

### ISSUE THREAD

**Issue by xmha97** [ScoopInstaller/Extras#11340]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

PowerShell Core

### Description

PowerShell is a cross-platform (Windows, Linux, and macOS) automation and configuration tool/framework that works well with your existing tools and is optimized for dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object models.

### Homepage

https://microsoft.com/PowerShell

### Download Link(s)

https://github.com/PowerShell/PowerShell/releases/download/v7.3.4/PowerShell-7.3.4-win-x64.zip

### Some Indication of Popularity/Repute

Cross-platform (Windows, Linux, and macOS)

**Comment by HUMORCE** [comment]
`main/pwsh`

**Comment by xmha97** [comment]
OK, thanks.
