### ISSUE TITLE
Updating from everything@1.4.1.1020 requires Admin Rights

### ISSUE THREAD

**Issue by 0xvividmirage** [ScoopInstaller/Extras#11364]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

everything

### Expected/Current Behaviour

I want to upgrade from everything@1.4.1.1020 but I am using a computer that I do not have admin rights, so I cannot upgrade past this version.

![image](https://github.com/ScoopInstaller/Extras/assets/41744832/cbc79347-964f-4788-b1cf-b9afba688038)

### Steps to Reproduce

```console
PS C:\WINDOWS\system32\WindowsPowerShell\v1.0> scoop update everything
everything: 1.4.1.1020 -> 1.4.1.1024
Updating one outdated app:
Updating 'everything' (1.4.1.1020 -> 1.4.1.1024)
Downloading new version
Loading Everything-1.4.1.1024.x64.zip from cache
Checking hash of Everything-1.4.1.1024.x64.zip ... ok.
Running pre_uninstall script...
ERROR Admin rights are required to stop Everything service
```
```


### Possible Solution

Remove "everything" to "nonportable" bucket or make it not require admin rights. I prefer the latter because I use it as an enhancement for the "wox" package.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
b46db2c49 (HEAD -> master, origin/master, origin/HEAD) tev: Update to version 1.26

'main' bucket:
84833390f (HEAD -> master, origin/master, origin/HEAD) scala: Update to version 3.3.0
```

### Scoop Config

```console
PS C:\WINDOWS\system32\WindowsPowerShell\v1.0> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-05-30T08:50:59.4315145-04:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\WINDOWS\system32\WindowsPowerShell\v1.0> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

wox

**Comment by 0xvividmirage** [comment]
> 

I installed this via -- `scoop install everything`

This situation is it installs a service that cannot be stopped by a normal user. It used to upgrade fine until the version I've indicated. Come to think of it, I can try uninstalling `wox`, then rebooting, then uninstall `everything`. Then reinstall wox then everything, but I think the situation will be the same.

**Comment by HUMORCE** [comment]
The manifest has never had an aotomatic installation for everything service.

**Comment by 0xvividmirage** [comment]
After installing wox, it recommends both `everything` and `python`. I then manually install them using scoop.

**Comment by 0xvividmirage** [comment]
How did you get that popup? As I said previously, I installed `everything` myself, but after a vcertain version I had the problem that prompted me to start this ticket. I use this at work and do not have Admin access.

**Comment by HUMORCE** [comment]
Everything Service cannot be installed without admin rights, if you have not admin account, then other users in this PC installed everything and enabled service.

```
❯ sc.exe qc everything
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: everything
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 0   IGNORE
        BINARY_PATH_NAME   : "C:\Users\humorce\scoop\apps\everything\current\Everything.exe" -svc
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : Everything
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem
```

**Comment by HUMORCE** [comment]
I have tested in VMs and merged PR #11368 . `scoop update; scoop update everything`

If still unable to update, please provide the output of `sc.exe qc everything` and reopen issue.

**Comment by 0xvividmirage** [comment]
> 

```
[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.
```

**Comment by HUMORCE** [comment]
> It used to be true that everything could be installed without admin rights. however, as of the version I indicated, it requires admin rights.

Script for service operation was added in 2022-06-11 (UTC), https://github.com/ScoopInstaller/Extras/commit/d97684b5f4ce782087ce9c3ac598663d2f679443.

> PS C:\WINDOWS\system32\WindowsPowerShell\v1.0> sc.exe qc everything
> [SC] OpenService FAILED 1060:
> 
> The specified service does not exist as an installed service.

Try to find the Everything service in `services.msc`.

---

Still cannot update after #11368?
