### ISSUE TITLE
[Bug]: XAMPP Control Panel doesn't detect running modules?

### ISSUE THREAD

**Issue by gphg** [ScoopInstaller/Extras#11372]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

xampp

### Expected/Current Behaviour

![image](https://github.com/ScoopInstaller/Extras/assets/46024870/5f802975-3fee-43a3-9d6f-89cb636eeed1)
I started the module and it stuck at this message. This applies to all modules:
```
17:46:09  [Apache] 	Attempting to start Apache app...
19:39:49  [mysql] 	Attempting to start MySQL app...
19:42:38  [filezilla] 	Attempting to start FileZilla app...
19:42:46  [mercury] 	Attempting to start Mercury app...
19:42:55  [Tomcat] 	Attempting to start Tomcat app...
```
The module itself is running on background. When I re-hit the "start" the error obviously occurs because other program occupies the port.

### Steps to Reproduce

```console
1. Get XAMPP installed
2. Open XAMPP Control Panel
3. Run any module
4. Rerun after moments later
5. Try to stop it.
```

### Possible Solution

Because the module doesn't detect the running programs, I have to stop the running programs from command-line or terminate it with task manager.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
9040a51fb (HEAD -> master, origin/master, origin/HEAD) standardnotes: Update to version 3.160.19

'games' bucket:
7809b4eb (HEAD -> master, origin/master, origin/HEAD) yuzu: Update to version 0-1453

'main' bucket:
e40ae52f4 (HEAD -> master, origin/master, origin/HEAD) wp-cli: Update to version 2.8.0
```

### Scoop Config

```console
PS> scoop config

last_update                       debug scoop_branch scoop_repo
-----------                       ----- ------------ ----------
2023-06-01T04:41:29.5917813+07:00  True master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment]
![screenshot_230602_103533](https://github.com/ScoopInstaller/Extras/assets/4353480/d77a5c60-44a7-40e8-b4dc-64c7453f4b70)

Detection works when service installed.

**Comment by HUMORCE** [comment]
This is the design of the program.
