### ISSUE TITLE
[Request]: foobar2000 x64

### ISSUE THREAD

**Issue by rsp4jack** [ScoopInstaller/Extras#11427]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

foobar2000-x64

### Description

x64 version of foobar2000

### Homepage

https://www.foobar2000.org/

### Download Link(s)

https://www.foobar2000.org/download

### Some Indication of Popularity/Repute

foobar2000 is already included in this bucket, but there is no x64 version of it.

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/commit/c202cf1d9bb319685d76dc2af9b55b685c91dceb
