### ISSUE TITLE
gpu-z@2.54.0: Download via aria2 failed

### ISSUE THREAD

**Issue by gema-arta** [ScoopInstaller/Extras#11515]
Download failed! 

ERROR Download failed! (Error 3) Resource was not found
ERROR http://us2-dl.techpowerup.com/files/GPU-Z.2.54.0.exe#/GPU-Z.exe
    referer=http://us2-dl.techpowerup.com/files/GPU-Z.2.54.0.exe#/
    dir=C:\Users\0\scoop\cache
    out=gpu-z#2.54.0#http_us2-dl.techpowerup.com_files_GPU-Z.2.54.0.exe_GPU-Z.exe

ERROR & 'C:\Users\0\scoop\apps\aria2\1.36.0-1\aria2c.exe' --input-file='C:\Users\0\scoop\cache\gpu-z.txt' --user-agent='Shovel/1.0 (+https://shovel.ash258.com) PowerShell/5.1 (Windows NT 10.0.22000.0; Win64; x64;)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=3 --split=6 --max-connection-per-server=12 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=25808 --continue --summary-interval 0  -l C:\Users\0\AppData\Local\Temp\aria2.log  --save-cookies=C:\Users\0\AppData\Local\Temp\aria2.db --continue
ERROR Download failed! (Error 3) Resource was not found

**Comment by HUMORCE** [comment]
```
❯ scoop download gpu-z
INFO  Downloading 'gpu-z' [64bit] from extras bucket
GPU-Z.2.54.0.exe (9.0 MB) [===========================================================================================] 100%
Checking hash of GPU-Z.2.54.0.exe ... ok.
'gpu-z' (2.54.0) was downloaded successfully!
```
