### ISSUE TITLE
[Request]: Altus

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#11514]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Altus

### Description

Altus is an Electron-based WhatsApp client with themes and multiple account support, available for Windows, Mac and Linux. 

### Homepage

https://amanharwara.com/work/altus

### Download Link(s)

https://github.com/amanharwara/altus/releases/download/4.8.6/Altus-Setup-4.8.6.exe

### Some Indication of Popularity/Repute

it is 100 Github Stars

BTW, Whatsapp deprecated exe version and forced to use Microsoft Store. But, certain corporate environments disallow Microsoft store. hence, alternative is important.

**Comment by cfvescovo** [comment]
This project has now ~500 stars on Github. Closing this issue in #13537
