### ISSUE TITLE
[Request]: CompactGUI

### ISSUE THREAD

**Issue by QPOZP** [ScoopInstaller/Extras#11530]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

CompactGUI

### Description

Frontend for compact.exe

### Homepage

https://github.com/IridiumIO/CompactGUI

### Download Link(s)

https://github.com/IridiumIO/CompactGUI/releases/download/v3.0.0-beta.1/CompactGUI.exe, https://github.com/IridiumIO/CompactGUI/releases/download/v3.0.0-beta.1/CompactGUI-Integrated.zip

### Some Indication of Popularity/Repute

200 forks and 3.7k stars
Already present, needs update.

**Comment by aliesbelik** [comment]
Already in `Extras` (using `CompactGUI.exe`).
For separate manifest (using `CompactGUI-Integrated.zip`) please create another PR (in `Versions` scoop, I guess).
