### ISSUE TITLE
[Bug]: Wireshark not detecting USBPcap

### ISSUE THREAD

**Issue by nanangp** [ScoopInstaller/Extras#11545]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

wireshark

### Expected/Current Behaviour

After installing wireshark, and following the manifest note to install usbpcap from the `apps/wireshark` dir, we expect to be able to perform USB capture. 

This is currently not the case. USBPcap is not detected when wireshark is run.

### Steps to Reproduce

```console
- `scoop install wireshark`
- `\scoop\apps\wireshark\current\USBPcapSetup-installer.exe`
- Reboot
- Run Wireshark
- USBPcap interfaces not listed
```

### Possible Solution

Currently, to allow Wireshark to detect USBPcap, we need to create `$dir\Data\extcap\`, then manually copying `\Program Files\USBPcap\USBPcapCMD.exe` there.

`$dir\Data\` is already persisted, so the new dir should survive updates & uninstalls.

This could either simply be added to the manifest note, or someone could get fancy and script the USBPcap install process (requires escalation).

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
39a54cc86 (HEAD -> master, origin/master, origin/HEAD)
```

### Scoop Config

```console
last_update  : 3/07/2023 3:50:29 PM
scoop_repo   : https://github.com/ScoopInstaller/Scoop
scoop_branch : master
```

### PowerShell Version

```console
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

USBPcap 1.5.4.0 (included as part of Wireshark download)

**Comment by HUMORCE** [comment]
Can you create a PR for the improvement?
