### ISSUE TITLE
[Bug]: czkawka-gui wrong autoupdate url

### ISSUE THREAD

**Issue by zsuatem** [ScoopInstaller/Extras#11552]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

czkawka-gui

### Expected/Current Behaviour

Autoupdate can not update czkawka-gui to version 6.0.0 because the file name has been changed.

### Steps to Reproduce

```console
PS D:\_Projekty\Scoop-Extras> .\bin\checkver.ps1 -u czkawka-gui
czkawka-gui: 6.0.0 (scoop version is 5.1.0) autoupdate available
Autoupdating czkawka-gui
Downloading windows_czkawka_gui.zip to compute hashes!
The remote server returned an error: (404) Not Found.
URL https://github.com/qarmin/czkawka/releases/download/6.0.0/windows_czkawka_gui.zip is not valid
ERROR Could not update czkawka-gui, hash for windows_czkawka_gui.zip failed!
```

### Possible Solution

Reanme `windows_czkawka_gui.zip` to `windows_czkawka_gui2.zip` in the autoupdate URL as in the latest version https://github.com/qarmin/czkawka/releases/tag/6.0.0

### Scoop and Buckets Version

```console
PS C:\Users\mateu> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
be5cf4557 (HEAD -> master, origin/master, origin/HEAD) teamviewer: Update to version 15.43.7

'main' bucket:
be4906d57 (HEAD -> master, origin/master, origin/HEAD) jenkins: Update to version 2.413
```

### Scoop Config

```console
PS C:\Users\mateu> scoop config

last_update         scoop_repo                              scoop_branch
-----------         ----------                              ------------
04.07.2023 21:26:20 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
PS C:\Users\mateu> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by goldenrold** [comment]
I think changing the base install url and keeping the autoupdate url template should work. The two at the end seems like a one-off change since none of the other urls in this release or previous releases have it.

**Comment by goldenrold** [comment]
Working on it.

**Comment by goldenrold** [comment]
Actions bot wouldn't take unless the autoupdate field pointed to an extant url, so updated both base and autoupdate urls in the manifest.
