### ISSUE TITLE
furmark@1.35.0.0: hash check failed

### ISSUE THREAD

**Issue by robinrehbein** [ScoopInstaller/Extras#11557]
PS C:\Users\me> scoop install furmark
Installing 'furmark' (1.35.0.0) [64bit] from extras bucket
Downloading https://geeks3d.com/dl/get/720#/FurMark_1.35.0.0_Setup.exe (-1 B)...

Checking hash of FurMark_1.35.0.0_Setup.exe ... ERROR Hash check failed!
App:         extras/furmark
URL:         https://geeks3d.com/dl/get/720#/FurMark_1.35.0.0_Setup.exe
First bytes: 3C 21 64 6F 63 74 79 70
Expected:    abba3e5ee274a0a5a8755e83accae5e2f36671e967ea36d0f445151a0b7cc1fe
Actual:      0e6ec2abcf0353892c9c3c669dfefe9d7e81487a2c342574be16340e0c7171b3

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=furmark%401.35.0.0%3a+hash+check+failed
PS C:\Users\me>

**Comment by HUMORCE** [comment]
```
"notes": "This manifest may fail to download under Powershell 5.x for now.",
```
