### ISSUE TITLE
[Bug]: mambaforge installation fails

### ISSUE THREAD

**Issue by AchimGaedkeLynker** [ScoopInstaller/Extras#11570]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

mambaforge

### Expected/Current Behaviour

The installation of mambaforge on Windows 11 fails for me with `Can't shim 'pythonw.exe': File doesn't exist.`

I would expect mamba/conda relying the conda script/binary only and  locating to the python interpreter internally, so no python binary shims needed here.

### Steps to Reproduce

```console
(base) PS> scoop install extras/mambaforge
Updating Scoop...
[...]
Scoop was updated successfully!
Installing 'mambaforge' (23.1.0-3) [64bit] from extras bucket
Loading Mambaforge-23.1.0-3-Windows-x86_64.exe from cache
Checking hash of Mambaforge-23.1.0-3-Windows-x86_64.exe ... ok.
Running pre_install script...
Running installer script...
Linking ~\scoop\apps\mambaforge\current => ~\scoop\apps\mambaforge\23.1.0-3
Creating shim for 'python'.
Creating shim for 'pythonw'.
Can't shim 'pythonw.exe': File doesn't exist.
```

### Possible Solution

Just removing `pythonw.exe` seems to help. But (as above) I'd expect the conda script to find a suitable python executable in the condabin env (If things work roughly as they do under Linux).

I'm new to this all under MS Windows, so I'm rather guessing ... and that's why there's no pull request... need some feedback!

### Scoop and Buckets Version

```console
scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
7edad1e25 (HEAD -> master, origin/master, origin/HEAD) okular: Update to version 23.04.3-1448

'main' bucket:
f70e3d9fe (HEAD -> master, origin/master, origin/HEAD) sbt: Update to version 1.9.2
```

### Scoop Config

```console
scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-07-10T18:24:59.5691948+12:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

Looked for python and pythonw before installing

```
> get-command -All python

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     python.exe                                         0.0.0.0    C:\Users\xxx\AppData\Local\Microsoft\WindowsApps\python.exe
```

no pythonw found...

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/pull/11366#issuecomment-1568774012

**Comment by AchimGaedkeLynker** [comment]
After endless trying and reading, my problem is fixed with adding `/CheckPathLength=0`.

**Comment by AchimGaedkeLynker** [comment]
Here we go: https://github.com/conda/constructor/blob/main/constructor/construct.py#L446

>Check the length of the path where the distribution is installed to ensure nodejs
can be installed.  Raise a message to request shorter path (less than 46 character)
or enable long path on windows > 10 (require admin right). Default is True. (Windows only).
> 
> Read notes about the particularities of Windows silent mode `/S` in the
`installer_type` documentation.

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/lib/diagnostic.ps1#L40-L55

Long paths related will prompt when executing `scoop checkup`

**Comment by AchimGaedkeLynker** [comment]
Cool, that's sorta useful. In order to prevent someone else having an experience like me... What can I do?

* make sure there's no silent failure
* mention the `scoop checkup`, long path issue in the JSON file notes?
* add the `/CheckLongPath 0` unconditionally?

**Comment by AchimGaedkeLynker** [comment]
Cool! Given the awkwardness of enabling a log file or error messages for such installers, that's a reasonable solution to close this issue. Google will help people finding it...

And many thanks.

**Comment by AchimGaedkeLynker** [comment]
If this is about the missing error messages/logs... I'm referring to the comments about `/S` in https://github.com/conda/constructor/blob/main/constructor/construct.py#L180 - enabling logs seems to require `scons`...

The notes are only shown on success, so ... not much help when it fails... Anyway, it is an improvement.
