### ISSUE TITLE
crystaldiskinfo@9.1.0: download via aria2 failed

### ISSUE THREAD

**Issue by shoucandanghehe** [ScoopInstaller/Extras#11604]
Installing 'crystaldiskinfo' (9.1.0) [64bit] from extras bucket
Starting download with aria2 ...
Download: Download Results:                                                                                                                 ip
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 431ba7|ERR |       0B/s|C:/Users/17486/scoop/cache/crystaldiskinfo#9.1.0#https_dotsrc.dl.osdn.net_osdn_crystaldiskinfo_78950_CrystalDiskInfo9_1_0.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://dotsrc.dl.osdn.net/osdn/crystaldiskinfo/78950/CrystalDiskInfo9_1_0.zip
    referer=https://dotsrc.dl.osdn.net/osdn/crystaldiskinfo/78950/
    dir=C:\Users\17486\scoop\cache
    out=crystaldiskinfo#9.1.0#https_dotsrc.dl.osdn.net_osdn_crystaldiskinfo_78950_CrystalDiskInfo9_1_0.zip

ERROR & 'C:\Users\17486\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\17486\scoop\cache\crystaldiskinfo.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.3 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=9892 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=crystaldiskinfo%409.1.0%3a+download+via+aria2+failed

**Comment by HUMORCE** [comment]
OSDN's download service is temporarily unavailable.
