### ISSUE TITLE
[Bug]: makemkv installation doesn't add makemkvcon to PATH

### ISSUE THREAD

**Issue by crisalis2** [ScoopInstaller/Extras#11613]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

makemkv

### Expected/Current Behaviour

I installed makemkv through scoop and expected its command line utility, makemkvcon.exe, to be easily accessible in a terminal by typing "makemkvcon.exe", because scoop does do that with other GUI programs that include some command line versions (like mpv.exe and mpv.com), but makemkvcon.exe wasn't in the path.

### Steps to Reproduce

```console
scoop install extras/makemkv
And no makemkvcon.exe in path.
```

### Possible Solution

Add makemkvcon.exe to path.
More info about makemkvcon.exe: https://www.makemkv.com/developers/usage.txt

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
29aa68a63 (HEAD -> master, origin/master, origin/HEAD) forkgram: Update to version 4.8.6 (#11610)

'main' bucket:
ba07a1130 (HEAD -> master, origin/master, origin/HEAD) adb@34.0.4: Fix hash (Closes #4965)

'nonportable' bucket:
8d10947 (HEAD -> master, origin/master, origin/HEAD) goodsync-np: Update to version 12.2.8

'versions' bucket:
e659ef149 (HEAD -> master, origin/master, origin/HEAD) idea-ultimate-rc: Update to version 2023.2-232.8660.142
```

### Scoop Config

```console
last_update         scoop_repo                              scoop_branch
-----------         ----------                              ------------
2023-07-22 21:36:39 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
Thank you for the report.
