### ISSUE TITLE
syncbackpro@11.0.0.25 hash check failed

### ISSUE THREAD

**Issue by alliter8** [ScoopInstaller/Extras#11682]
### Prerequisites

- [X] I have used the predefined issue title. (e.g. "xxx@xxx&#58; hash check failed")
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name and Version

synbackpro@11.0.0.25

**Comment by HUMORCE** [comment]
Cannot reproduce.

```
❯ scoop download syncbackpro -u
INFO  Downloading 'syncbackpro' [64bit] from extras bucket
SyncBackPro64_Setup_NI.zip (76.0 MB) [================================================================================] 100%
Checking hash of SyncBackPro64_Setup_NI.zip ... ok.
'syncbackpro' (11.0.0.25) was downloaded successfully!
```
