### ISSUE TITLE
FontForge@20230101: decompress error

### ISSUE THREAD

**Issue by tch123** [ScoopInstaller/Extras#11691]
Installing 'FontForge' (20230101) [64bit] from extras bucket
FontForge-2023-01-01-Windows.exe (22.5 MB) [==================================================================] 100%
Checking hash of FontForge-2023-01-01-Windows.exe ... ok.
Extracting FontForge-2023-01-01-Windows.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\Name\scoop\apps\FontForge\20230101\FontForge-2023-01-01-Windows.exe.
Log file:
  ~\scoop\apps\FontForge\20230101\innounp.log
        >  Signature detected: Inno Setup Setup Data (6.1.0) (u)
        > This is not directly supported, but i'll try to unpack it as version 6000
        > ; Version detected: 6100 (Unicode)
        > Unpacking failed. This version is not supported.

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=FontForge%4020230101%3a+decompress+error

**Comment by HUMORCE** [comment]
Cannot reproduce.

Update `innounp`, if it's already latest version, leave more information.

**Comment by HUMORCE** [comment]
Temporarily closed, feel free to reopen this issue.

**Reasons:**
- Cannot reproduce.
- No response and additional information
