### ISSUE TITLE
[Request]: gramps

### ISSUE THREAD

**Issue by Aravinth-Earth** [ScoopInstaller/Extras#11705]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

gramps

### Description

Gramps is a free software project and community. Which strive to produce a genealogy program that is both intuitive for hobbyists and feature-complete for professional genealogists. It is a community project, created, developed and governed by genealogists.

### Homepage

https://gramps-project.org/blog/

### Download Link(s)

https://github.com/gramps-project/gramps/releases

### Some Indication of Popularity/Repute

At this time of issue creation[7th Aug 2023 IST], the repository metrics
- watching -> 112
- fork -> 358
- stars -> 1.8K

**Comment by danielpauldd** [comment]
Please see: https://github.com/ScoopInstaller/Extras/issues/12439#issuecomment-1902757345

**Comment by aliesbelik** [comment]
@Aravinth-Earth, @danielpauldd, please feel free to submit a PR if you a ready.
