### ISSUE TITLE
autohotkey@2.0.4: download via aria2 failed

### ISSUE THREAD

**Issue by neoOpus** [ScoopInstaller/Extras#11731]
ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://www.autohotkey.com/download/2.0/AutoHotkey_2.0.4.zip
    referer=https://www.autohotkey.com/download/2.0/
    dir=C:\Users\neoop\scoop\cache
    out=autohotkey#2.0.4#https_www.autohotkey.com_download_2.0_AutoHotkey_2.0.4.zip

ERROR & 'C:\Users\xxx\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\xxx\scoop\cache\autohotkey.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=14956 --continue --summary-interval=0 --auto-save-interval=1

**Comment by HUMORCE** [comment]
cloudflare protect

**Comment by neoOpus** [comment]
I didn't think it could be this, the normal download worked. Thank you. 

In any case, I believe it would be more reliable if Scoop employed [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) to palliate such case scenarios

**Comment by HUMORCE** [comment]
Zip does not published in its github repo, so just wating its official installer supports portable(WIP), then switch.
