### ISSUE TITLE
Scratch does not install/update anymore: Couldn't find manifest for 'winrar-helper'.

### ISSUE THREAD

**Issue by reinpeter** [ScoopInstaller/Extras#11753]
Installing scratch complains about missing dependency 'winrar-helper'
Prob has smth to do with: https://github.com/ScoopInstaller/Extras/commit/51d99bfd9ca7fdd08c4af665ac6e63590228af9b

```
$ scoop install scratch
Couldn't find manifest for 'winrar-helper'.
```

**Comment by HUMORCE** [comment]
Fixed.

When I noticed `winrar-helper` that it was used for this manifest only then I made change https://github.com/ScoopInstaller/Extras/commit/51d99bfd9ca7fdd08c4af665ac6e63590228af9b, but I forgot to commit changes to `scratch.json`.

**Comment by reinpeter** [comment]
👍 thx
👏 for your response time
