### ISSUE TITLE
[Bug]: Android Studio url incorrect certificate

### ISSUE THREAD

**Issue by TylerTemp** [ScoopInstaller/Extras#11789]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

android-studio

### Expected/Current Behaviour

install android studio

### Steps to Reproduce

```console
> scoop install android-studio
WARN  Purging previous failed installation of android-studio.
ERROR 'android-studio' isn't installed correctly.
Removing older version (2022.3.1.19).
'android-studio' was uninstalled.
Installing 'android-studio' (2022.3.1.19) [64bit] from extras bucket
The remote certificate is invalid according to the validation procedure.
URL https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2022.3.1.19/android-studio-2022.3.1.19-windows.zip is not valid
```

### Possible Solution

Not sure if it's scoop or if should I report it to Google.

`android-studio.json` uses <https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2022.3.1.19/android-studio-2022.3.1.19-windows.zip>, which redirects to [r3---sn-j5o76n7e.gvt1-cn.com](https://r3---sn-j5o76n7e.gvt1-cn.com/edgedl/android/studio/ide-zips/2022.3.1.19/android-studio-2022.3.1.19-windows.zip?mh=9Y&pl=23&shardbypass=sd&redirect_counter=1&rm=sn-ni5ek7l&req_id=17b8052fd3b33dce&cms_redirect=yes&cmsv=e&ipbypass=yes&mip=1.119.178.62&mm=28&mn=sn-j5o76n7e&ms=nvh&mt=1692930738&mv=u&mvi=3&rmhost=r1---sn-j5o76n7e.gvt1-cn.com&smhost=r3---sn-j5o7dn7l.gvt1-cn.com). However, the later tls is incorrect and gives a certificate of `*.googlevideo.com`, leads to a dismatch.

### Scoop and Buckets Version

```console
> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
670c8ce51 (HEAD -> master, origin/master, origin/HEAD) adwcleaner@8.4.0: Fix hash (Closes #11788)

'main' bucket:
b668cae9c (HEAD -> master, origin/master, origin/HEAD) ugrep: Update to version 4.0.3
```

### Scoop Config

```console
> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-08-25T10:53:01.1439126+08:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment]
Cannot reproduce.

```
❯ scoop download android-studio
INFO  Downloading 'android-studio' [64bit] from extras bucket
android-studio-2022.3.1.19-windows.zip (1.0 GB) [=====================================================================] 100%
Checking hash of android-studio-2022.3.1.19-windows.zip ... ok.
'android-studio' (2022.3.1.19) was downloaded successfully!
```

**Comment by HUMORCE** [comment]
I noticed that you may be using Scoop behind a Proxy Server with rule filters(e.g. v2ray, clash, etc.). This is caused by wrong config of proxy server, fix the rule or use a global proxy then retry.

btw, in mainland China, you can connect to most of resources provided via Google (android studio, chrome, go, gcloud, libwebp, etc) without a proxy server/VPN.
