### ISSUE TITLE
foxit-reader@12.1.3.15356: decompress error

### ISSUE THREAD

**Issue by rpm0372** [ScoopInstaller/Extras#11841]
Fresh scoop install on fresh Windows 11.  Am I missing something scoop-specific to decompress .msi?
I'm showing the output because the log file does not exist.

Installing 'foxit-reader' (12.1.3.15356) [64bit] from extras bucket
Loading FoxitPDFReader1213_L10N_Setup.msi from cache
Checking hash of FoxitPDFReader1213_L10N_Setup.msi ... ok.
Extracting FoxitPDFReader1213_L10N_Setup.msi ... ERROR Exit code was 1622!
Failed to extract files from C:\Users\Ray\scoop\apps\foxit-reader\12.1.3.15356\FoxitPDFReader1213_L10N_Setup.msi.
Log file:
  ~\scoop\apps\foxit-reader\12.1.3.15356\msi.log

**Comment by HUMORCE** [comment]
Check the error code on this page: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes

1. Restart PC then retry install the manifest
2. Use alternative MSI extractor by toggle config item `scoop config use_lessmsi true|false` (default: false)
