### ISSUE TITLE
[Bug]: totalcommander cleanup delete wincmd.ini

### ISSUE THREAD

**Issue by panathos** [ScoopInstaller/Extras#11840]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

totalcommander

### Expected/Current Behaviour

scoop cleanup *
Removing totalcommander: 11.01Remove-Item : Impossibile rimuovere l'elemento D:\scoop\apps\totalcommander\11.01\plugins: Accesso al percorso
'plugins' negato.
In D:\scoop\apps\scoop\current\libexec\scoop-cleanup.ps1:50 car:9
+         Remove-Item $dir -ErrorAction Stop -Recurse -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (plugins:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : DeleteSymbolicLinkFailed,Microsoft.PowerShell.Commands.RemoveItemCommand

### Steps to Reproduce

```console
scoop update totalcommander
scoop cleanup *
```

### Possible Solution

No suggestion, trying editing totalcommander.json to stop deleting wincmd.ini or other current files.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'bear' bucket:
4375a2d (HEAD -> master, origin/master, origin/HEAD) update wiznote

'extras' bucket:
999c7d2d2 (HEAD -> master, origin/master, origin/HEAD) threema: Update to version 1.2.36
```

### Scoop Config

```console
last_update                       aria2-warning-enabled scoop_branch scoop_repo
-----------                       --------------------- ------------ ----------
2023-09-04T10:31:38.0074810+02:00                 False master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment]
```
> scoop update totalcommander -f
totalcommander: 11.02 -> 11.02
Updating one outdated app:
Updating 'totalcommander' (11.02 -> 11.02)
Downloading new version
Loading tcmd1102x64.exe from cache
Checking hash of tcmd1102x64.exe ... ok.
Uninstalling 'totalcommander' (11.02)
Removing shim 'TOTALCMD64.shim'.
Removing shim 'TOTALCMD64.exe'.
Unlinking ~\scoop\apps\totalcommander\current
Installing 'totalcommander' (11.02) [64bit] from extras bucket
Loading tcmd1102x64.exe from cache
Running pre_install script...
Linking ~\scoop\apps\totalcommander\current => ~\scoop\apps\totalcommander\11.02
Creating shim for 'TOTALCMD64'.
Creating shortcut for Total Commander (TOTALCMD64.EXE)
Persisting plugins
Persisting DEFAULT.BAR
Persisting default.br2
Persisting VERTICAL.BAR
Persisting vertical.br2
Persisting usercmd.ini
Persisting wcx_ftp.ini
Persisting wincmd.ini
Persisting wincmd.key
Persisting contplug.ini
Persisting fsplugin.ini
Persisting lsplugin.ini
Persisting pkplugin.ini
'totalcommander' (11.02) was installed successfully!
> scoop cleanup *
Removing totalcommander: _11.02.old
Everything is shiny now!
```

Cannot reproduce.

May related: https://github.com/ScoopInstaller/Scoop/pull/5552

**Comment by HUMORCE** [comment]
Scoop trying remove versioned app dir when you executed `scoop cleanup <app>`, but relevant files may be being occupied.

---

Temporarily closed, feel free to leave a comment below.

**Reasons:**
- Cannot reproduce.
- No response and additional information
