### ISSUE TITLE
flutter 3.13.3 - hash error

### ISSUE THREAD

**Issue by dodumosu** [ScoopInstaller/Extras#11860]
### Prerequisites

- [X] I have used the predefined issue title. (e.g. "xxx@xxx&#58; hash check failed")
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name and Version

3.13.3

**Comment by Arian-D** [comment]
I am also getting this error. The actual hash is `f55a027c1c73bc80104d0f390a3d569c9d5073fd918b5b07d0c84ab557cf8ce7` while the manifest expects `7dcb77a6688ef034ea3b1b482444e656c68013e22bc90ccc6f9de4dde67830af`.
