### ISSUE TITLE
[Request]: Gossip

### ISSUE THREAD

**Issue by badonyx** [ScoopInstaller/Extras#11892]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

gossip

### Description

Desktop client for nostr protocol

### Homepage

https://github.com/mikedilger/gossip

### Download Link(s)

https://github.com/mikedilger/gossip/releases/download/v0.8.0/gossip.0.8.0.msi

### Some Indication of Popularity/Repute

~500 stars on github

**Comment by babonyx** [comment]
I have a manifest for this already.
