### ISSUE TITLE
imagine@1.1.7: decompress error

### ISSUE THREAD

**Issue by vmt1997** [ScoopInstaller/Extras#11905]
Downloading new version
Imagine_1.1.7_x64_Unicode.zip (2.0 KB) [======================================================================] 100%
Checking hash of Imagine_1.1.7_x64_Unicode.zip ... ok.
Uninstalling 'imagine' (1.1.6)
Removing shim 'Imagine64.shim'.
Removing shim 'Imagine64.exe'.
Removing shim 'Imagine.shim'.
Removing shim 'Imagine.exe'.
Unlinking ~\scoop\apps\imagine\current
Installing 'imagine' (1.1.7) [64bit] from extras bucket
Loading Imagine_1.1.7_x64_Unicode.zip from cache
Extracting Imagine_1.1.7_x64_Unicode.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\vmt1997\scoop\apps\imagine\1.1.7\Imagine_1.1.7_x64_Unicode.zip.
Log file:
  ~\scoop\apps\imagine\1.1.7\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=imagine%401.1.7%3a+decompress+error

**Comment by HUMORCE** [comment]
#12006
