### ISSUE TITLE
imageglass@8.10.9.27: hash check failed

### ISSUE THREAD

**Issue by StudentWeis** [ScoopInstaller/Extras#11943]
imageglass: 8.9.6.9 -> 8.10.9.27
Updating one outdated app:
Updating 'imageglass' (8.9.6.9 -> 8.10.9.27)
Downloading new version
ImageGlass_Kobe_8.10.9.27_x64.zip (19.1 MB) [============================================================] 100%
Checking hash of ImageGlass_Kobe_8.10.9.27_x64.zip ... ERROR Hash check failed!
App:         extras/imageglass
URL:         https://github.com/d2phap/ImageGlass/releases/download/8.10.9.27/ImageGlass_Kobe_8.10.9.27_x64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    f8149236eef50cc4726dbeb34721bf6b6f294d64
Actual:      0af64d67e4095e914a97b6056ac34843098fa5fb

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/pull/12319
