### ISSUE TITLE
[Request]: Bruno

### ISSUE THREAD

**Issue by Zottelchen** [ScoopInstaller/Extras#11969]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

bruno

### Description

Opensource IDE For Exploring and Testing Api's (lightweight alternative to postman/insomnia)

### Homepage

https://www.usebruno.com/

### Download Link(s)

https://github.com/usebruno/bruno/releases/download/v0.16.5/bruno_0.16.5_x64_win.exe

### Some Indication of Popularity/Repute

- [1169 stars](https://github.com/usebruno/bruno/stargazers) 
- [61 forks](https://github.com/usebruno/bruno/forks)
- featured on [Console #177](https://console.substack.com/p/console-177)

**Comment by helloanoop** [comment]
Hi,

This is the creator of Bruno.
Looking forward for Bruno to be scoopable :)

Thanks @Zottelchen !
