### ISSUE TITLE
listary@6.2.0.42: decompress error

### ISSUE THREAD

**Issue by shpodg** [ScoopInstaller/Extras#11975]
ERROR 'listary' isn't installed correctly.
listary: 5.00.2843 -> 6.2.0.42
Updating one outdated app:
Updating 'listary' (5.00.2843 -> 6.2.0.42)
Downloading new version
Loading Listary.exe from cache
Checking hash of Listary.exe ... ok.
Uninstalling 'listary' (5.00.2843)
Installing 'listary' (6.2.0.42) [64bit] from extras bucket
Loading Listary.exe from cache
Extracting dl.exe ... ERROR Exit code was 1!
Failed to extract files from D:\ProgramGreen\scoop\apps\listary\6.2.0.42\dl.exe.
Log file:
  D:\ProgramGreen\scoop\apps\listary\6.2.0.42\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=listary%406.2.0.42%3a+decompress+error

**Comment by HUMORCE** [comment]
```
> scoop install listary
Installing 'listary' (6.2.0.42) [64bit] from extras bucket
Listary.exe (6.4 MB) [========================================================================================] 100%
Checking hash of Listary.exe ... ok.
Extracting dl.exe ... done.
Linking ~\scoop\apps\listary\current => ~\scoop\apps\listary\6.2.0.42
Creating shortcut for Listary (Listary.exe)
'listary' (6.2.0.42) was installed successfully!
```

Cannot reproduce.

**Comment by HUMORCE** [comment]
Temporarily closed, feel free to reopen this issue.

**Reasons:**
- Cannot reproduce.
- No response and additional information
