### ISSUE TITLE
[Bug]: gnucash 5.4 URL is not valid

### ISSUE THREAD

**Issue by kalanzun** [ScoopInstaller/Extras#11999]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

gnucash

### Expected/Current Behaviour

scoop install gnucash results in an error:
"URL https://github.com/Gnucash/gnucash/releases/download/5.4/gnucash-5.4.setup.exe is not valid"

Seems the gnucash people have pushed a bugfix release version 5.4-1 to the same release tag and dropped the 5.4 setup.exe. The new URL is:
https://github.com/Gnucash/gnucash/releases/download/5.4/gnucash-5.4-1.setup.exe

### Steps to Reproduce

```console
scoop install gnucash
```

### Possible Solution

Update the download URL to https://github.com/Gnucash/gnucash/releases/download/5.4/gnucash-5.4-1.setup.exe

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
ffe13b310 (HEAD -> master, origin/master, origin/HEAD) zettlr: Update to version 3.0.2

'main' bucket:
eb82dd2a8 (HEAD -> master, origin/master, origin/HEAD) terragrunt: Update to version 0.52.1

'nerd-fonts' bucket:
f583c44 (HEAD -> master, origin/master, origin/HEAD) LXGW-Bright: Update to version 5.311

'nonportable' bucket:
c351da9 (HEAD -> master, origin/master, origin/HEAD) calibre-np: Update to version 6.28.1
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-10-08T17:33:30.8566912+02:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by lcosmin** [comment]
I noticed GnuCash being broken for a while now, is this still maintained or should I switch to an alternative install method?
