### ISSUE TITLE
ngspice@41: hash check failed

### ISSUE THREAD

**Issue by sapien243** [ScoopInstaller/Extras#12018]
Installing 'ngspice' (41) [64bit] from extras bucket
ngspice-41_64.7z (6.6 MB) [=================================================================] 100%
Checking hash of ngspice-41_64.7z ... ERROR Hash check failed!
App:         extras/ngspice
URL:         https://downloads.sourceforge.net/project/ngspice/ng-spice-rework/41/ngspice-41_64.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    e6677bb4932ea4e7ceb9f44af5e60df05fec320b
Actual:      5600b3a129d220e58921324bfc27a598c86b88f4
SourceForge.net is known for causing hash validation fails. Please try again before opening a ticket.

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=ngspice%4041%3a+hash+check+failed

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/pull/12242
