### ISSUE TITLE
reaper@7.001: Shim creation fail

### ISSUE THREAD

**Issue by 4x0v7** [ScoopInstaller/Extras#12051]
Cannot shim 'reamote.exe': File does not exist

```sh
 PS> scoop install reaper
Installing 'reaper' (7.001) [64bit] [extras]
WARN  By installing you accept following license: Proprietary (https://www.reaper.fm/dist-agreement.php)
reaper7001_x64-install.exe (14.9 MB) [============================================================================================================] 100%
Checking hash of reaper7001_x64-install.exe ... ok.
Extracting dl.7z ... done.
Running installer script...
Linking ~\scoop\apps\reaper\current => ~\scoop\apps\reaper\7.001
Creating shim for 'reaper'.
Creating shim for 'reamote'.
ERROR Cannot shim 'reamote.exe': File does not exist
```

**Comment by pomberger** [comment]
I got the same error and fixed it by manually removing the shim creation for reamote in the manifest.

The `reamote.exe` is missing in the reaper 7.001 installation. This is why the shim creation fails.
I couldn't find out, if this is intended in the new release of reaper.  However, if you download and run the installer manually from reaper.fm you see, there is no more option to install reamote, as it was in the installer of reaper 6.x.

Seems to be the same in the macOS installation:
https://forum.cockos.com/showpost.php?p=2722121&postcount=135
