### ISSUE TITLE
[Bug]: Tuxguitar doesn't install due to architecture error 

### ISSUE THREAD

**Issue by seaty6** [ScoopInstaller/Extras#12082]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

tuxguitar

### Expected/Current Behaviour

When installing tuxguitar, it will not install with the following error message: "ERROR 'tuxguitar' doesn't support current architecture!"

### Steps to Reproduce

```console
scoop install extras/tuxguitar
ERROR 'tuxguitar' doesn't support current architecture!
```

### Possible Solution

I believe there is only an x86 build available, and I am running a 64bit operating system. 

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
895b296dd (HEAD -> master, origin/master, origin/HEAD) filelight: Update to version 23.08.2-1508

'main' bucket:
00cf24c0c (HEAD -> master, origin/master, origin/HEAD) dependency-check: Update to version 8.4.2
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-10-22T18:46:47.7492293-04:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.2428
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2428
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by CryoRenegade** [comment]
It looks like whoever introduced the package only had the 32-bit version configured; I can fix that quickly.

**Comment by fodi** [comment]
That's not a bug. You can install the 32 bit (x86) version with:
`scoop install tuxguitar -a 32bit`

**Comment by CryoRenegade** [comment]
Yeah, I saw that
I just reconfigured the package to not only allow x86 installs by default. Also looks like their homepage got jacked, so I changed that over to their sf page jic.

**Comment by seaty6** [comment]
Thank you!
