### ISSUE TITLE
[Request]: Update sumatrapdf to latest version

### ISSUE THREAD

**Issue by serifold** [ScoopInstaller/Extras#12095]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

sumatrapdf

### Description

PDF, eBook (epub, mobi), comic book (cbz/cbr), DjVu, XPS, CHM, image viewer for Windows.

### Homepage

https://www.sumatrapdfreader.org/free-pdf-reader

### Download Link(s)

https://www.sumatrapdfreader.org/dl/rel/3.5.1/SumatraPDF-3.5.1-64.zip

### Some Indication of Popularity/Repute

It's [github repo](https://github.com/sumatrapdfreader/sumatrapdf) has 11.4k stars. It's "Fast, small, packed with features, customizable, free.".

The current sumatrapdf in extra bucket was updated a year ago, I thought maybe it's another software that is no longer maintained. However, I went to sumatrapdf's homepage, then I found it's still updating, and it's latest stable version is 3.5.1. Please update sumatrapdf to latest version, thank you.

**Comment by YDX-2147483647** [comment]
This might be fixed by #12057.

(It's the same software but auto-updating is somehow broken)

**Comment by serifold** [comment]
> This might be fixed by #12057 or #12104.
> 
> It's the same software but auto-updating is broken because scoop cannot download the latest version. [#12057 (comment)](https://github.com/ScoopInstaller/Extras/pull/12057#issuecomment-1784009851)

Thank you for the reminding, I'll follow that PR.
