### ISSUE TITLE
[Bug]: CamStudio requires mfc100.dll - from Microsoft Visual C++ 2010 Redistributable (x64 and x86)

### ISSUE THREAD

**Issue by kgarlow** [ScoopInstaller/Extras#12116]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

camstudio

### Expected/Current Behaviour

Initially when I installed camstudio 2.7.4-r354 via scoop, the application was not usable due to a missing DLL (mfc100.dll).

### Steps to Reproduce

```console
scoop install camstudio
Installing 'camstudio' (2.7.4-r354) [64bit] from extras bucket
Loading CamStudioSetup.exe from cache
Checking hash of CamStudioSetup.exe ... ok.
Loading CamStudioCodec_1.5_Setup.exe from cache
Checking hash of CamStudioCodec_1.5_Setup.exe ... ok.
Running pre_install script...
Linking ~\scoop\apps\camstudio\current => ~\scoop\apps\camstudio\2.7.4-r354
Creating shim for 'CamCommandLine'.
Creating shortcut for CamStudio (Recorder.exe)
Persisting controller\controller.ini
Persisting ffmpeg.log
'camstudio' (2.7.4-r354) was installed successfully!


When attempting to run ~\scoop\apps\camstudio\current\Recorder.exe, application does not load; reports missing mfc100.dll file.
```

### Possible Solution

To troubleshoot how to resolve, I installed the file from camstudio.org (https://eu2.contabostorage.com/a4054a9f5df24ecf87c4a33ac9b6477b:camstudio/CamStudioSetup.exe). When I ran it, it also installed the **Microsoft Visual C++ 2010 Redistributable packages (x86, x64), version 10.0.40219.** These then appeared under settings, Apps & features.

The mfc100.dll was then present in  c:\Windows\System32
06/11/2011  01:15 AM         5,574,984 **mfc100.dll**

I then uninstalled the Camtasia app, which still left the Redistributable packages still installed. After re-installing via scoop, the application then worked. 

I assume that the camstudio package for scoop could likewise install the necessary Redistributable packages so that the error does not occur.

### Scoop and Buckets Version

```console
v0.3.1 - Released at 2022-11-15

'extras' bucket:
9dad6d240 (HEAD -> master, origin/master, origin/HEAD) x64dbg: Update to version 2023-10-28_15-22

'main' bucket:
36be6c7fe (HEAD -> master, origin/master, origin/HEAD) x264: Update to version 3156

'nonportable' bucket:
1a8a97c (HEAD -> master, origin/master, origin/HEAD) 10x-np: Update to version 1.0.88

'sysinternals' bucket:
b17427d (HEAD -> main, origin/main, origin/HEAD) vmmap: Update to version 3.4

'versions' bucket:
ebfba5e79 (HEAD -> master, origin/master, origin/HEAD) zig-dev: Update to version 0.12.0-dev.1319
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-10-28T14:02:00.0882381-06:00 master       https://github.com/lukesampson/scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.3570
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3570
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment]
Thank you for reporting.
