### ISSUE TITLE
sumatrapdf@3.4.6: download via aria2 failed

### ISSUE THREAD

**Issue by Unixware** [ScoopInstaller/Extras#12174]
sumatrapdf is broken and can't be installed

C:\Windows\system32>scoop install sumatrapdf
WARN  Purging previous failed installation of sumatrapdf.
ERROR 'sumatrapdf' isn't installed correctly.
Removing older version (3.4.6).
'sumatrapdf' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'sumatrapdf' (3.4.6) [64bit] from extras bucket
Starting download with aria2 ...
Download: 11/05 14:20:08 [ERROR] CUID#8 - Download aborted. URI=https://files.sumatrapdfreader.org/file/kjk-files/softwaDownload: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://files.sumatrapdfreader.org/file/kjk-files/softwareDownload:   -> [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure: Error: The message received was unexpected orDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 1f4c0d|ERR |       0B/s|D:/scoop/cache/sumatrapdf#3.4.6#https_files.sumatrapdfreader.org_file_kjk-files_software_sumatrapdf_rel_3.4.6_SumatraPDF-3.4.6-64.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip
    referer=https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/
    dir=D:\scoop\cache
    out=sumatrapdf#3.4.6#https_files.sumatrapdfreader.org_file_kjk-files_software_sumatrapdf_rel_3.4.6_SumatraPDF-3.4.6-64.zip

ERROR & 'D:\scoop\apps\aria2\current\aria2c.exe' --input-file='D:\scoop\cache\sumatrapdf.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3432 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=sumatrapdf%403.4.6%3a+download+via+aria2+failed

C:\Windows\system32>

C:\Windows\system32>scoop install sumatrapdf
WARN  Purging previous failed installation of sumatrapdf.
ERROR 'sumatrapdf' isn't installed correctly.
Removing older version (3.4.6).
'sumatrapdf' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'sumatrapdf' (3.4.6) [64bit] from extras bucket
Starting download with aria2 ...
Download: 11/05 14:20:08 [ERROR] CUID#8 - Download aborted. URI=https://files.sumatrapdfreader.org/file/kjk-files/softwaDownload: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://files.sumatrapdfreader.org/file/kjk-files/softwareDownload:   -> [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure: Error: The message received was unexpected orDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 1f4c0d|ERR |       0B/s|D:/scoop/cache/sumatrapdf#3.4.6#https_files.sumatrapdfreader.org_file_kjk-files_software_sumatrapdf_rel_3.4.6_SumatraPDF-3.4.6-64.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip
    referer=https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/
    dir=D:\scoop\cache
    out=sumatrapdf#3.4.6#https_files.sumatrapdfreader.org_file_kjk-files_software_sumatrapdf_rel_3.4.6_SumatraPDF-3.4.6-64.zip

ERROR & 'D:\scoop\apps\aria2\current\aria2c.exe' --input-file='D:\scoop\cache\sumatrapdf.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3432 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=sumatrapdf%403.4.6%3a+download+via+aria2+failed

**Comment by Unixware** [comment]
nope... no corporate/firewall/proxy etc and country UK
disabling  the aria2 still issues:

C:\Windows\system32>scoop install sumatrapdf
WARN  Purging previous failed installation of sumatrapdf.
ERROR 'sumatrapdf' isn't installed correctly.
Removing older version (3.4.6).
'sumatrapdf' was uninstalled.
Installing 'sumatrapdf' (3.4.6) [64bit] from extras bucket
The request was aborted: Could not create SSL/TLS secure channel.
URL https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip is not valid

indeed the effin URL is broken, can't get it with copy/paste on web browser.

**Comment by Unixware** [comment]
PS fuck the bots

**Comment by eliozh** [comment]
Take it easy bro, there is a PR #12153 waiting to be reviewed. Be patient.🤣
