### ISSUE TITLE
[Bug]: github: wrong version number update from 3.3.5 to 7000

### ISSUE THREAD

**Issue by c-ortbauer** [ScoopInstaller/Extras#12205]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

github

### Expected/Current Behaviour

The version number was updated by the github actions bot from 3.3.5 to 7000 (commit 7494a9a).
This seems like an error to me.

### Steps to Reproduce

```console
scoop update *
```

### Possible Solution

Revert the commit

### Scoop and Buckets Version

```console
PS C:\Users\orc> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
b34905134 (HEAD -> master, origin/master, origin/HEAD) potplayer@231102: Fix hash (Closes #12203)

'main' bucket:
06b21e9df (HEAD -> master, origin/master, origin/HEAD) sing-box: Update to version 1.6.3
```

### Scoop Config

```console
PS C:\Users\orc> scoop config


use_lessmsi           : True
last_update           : 2023-11-10T06:53:56.4238905+01:00
aria2-warning-enabled : False
scoop_branch          : master
scoop_repo            : https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\Users\orc> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3570
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3570
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by TayouVR** [comment]
the faulty tag has been reverted. Not sure if scoop can do much automatically to revert local installs of that tag.
To manually return to the latest real release, do `scoop install github@3.3.5`, then `scoop update github`, in case there is a newer release by the time you run this.

**Comment by c-ortbauer** [comment]
Thank you, after scoop uninstall/install github, I now have 3.3.5 again.
