### ISSUE TITLE
publii@0.44.0: hash check failed

### ISSUE THREAD

**Issue by crazyuploader** [ScoopInstaller/Extras#12223]
PS C:\Users\jugal> scoop update publii
publii: 0.43.1 -> 0.44.0
Updating one outdated app:
Updating 'publii' (0.43.1 -> 0.44.0)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 8d7d99|OK  |   5.3MiB/s|C:/Users/jugal/scoop/cache/publii#0.44.0#https_cdn.getpublii.com_Publii-0.44.0.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of Publii-0.44.0.exe ... ERROR Hash check failed!
App:         extras/publii
URL:         https://cdn.getpublii.com/Publii-0.44.0.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    a6fc7ec4bac25e95ade94633583186541cf67f312f139141cd37a8bbb1251eff
Actual:      e7f3e9e0dee9de55b850c16354ebe0ce7031154fe95f50cf601bfc1488512513

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=publii%400.44.0%3a+hash+check+failed

**Comment by fodi** [comment]
I'm having this issue as well and I was able to reproduce it like this:
1. Downloading the Publii 0.44.0 installer from `https://cdn.getpublii.com/Publii-0.44.0.exe`
2. Running `sha256sum Publii-0.44.0.exe` - the result is:
`e7f3e9e0dee9de55b850c16354ebe0ce7031154fe95f50cf601bfc1488512513  Publii-0.44.0.exe`

...which indeed differs from the `a6fc7ec4bac25e95ade94633583186541cf67f312f139141cd37a8bbb1251eff` hash in the manifest.
