### ISSUE TITLE
[Bug]: sumatrapdf  download link is invalid or expired.

### ISSUE THREAD

**Issue by cyzzxc** [ScoopInstaller/Extras#12252]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

sumatrapdf

### Expected/Current Behaviour

The file download link is invalid or expired. 

### Steps to Reproduce

```console
➜ scoop install sumatrapdf
Installing 'sumatrapdf' (3.4.6) [64bit] from extras bucket
The SSL connection could not be established, see inner exception.
URL https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip is not valid
```

### Possible Solution

update to latest download url, I try and it work

https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.6/SumatraPDF-3.4.6-64.zip -->
https://www.sumatrapdfreader.org/dl/rel/3.5.2/SumatraPDF-3.5.2-64.zip

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
b8b8f0d57 (HEAD -> master, origin/master, origin/HEAD) streamlabs-obs: Update to version 1.15.1

'main' bucket:
497c914a4 (HEAD -> master, origin/master, origin/HEAD) terragrunt: Update to version 0.53.4
```

### Scoop Config

```console
last_update   : 2023/11/17 9:34:23
aria2-enabled : False
alias         :
scoop_branch  : master
scoop_repo    : https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PSVersion                      7.3.9
PSEdition                      Core
GitCommitId                    7.3.9
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
#12251
