### ISSUE TITLE
[Bug]: Summatrapdf installation is broken for over a month now

### ISSUE THREAD

**Issue by kfot** [ScoopInstaller/Extras#12281]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

sumatrapdf

### Expected/Current Behaviour

[The PR](https://github.com/ScoopInstaller/Extras/pull/12057) that fixes the URLs is merged ASAP, so the package can be installed 

### Steps to Reproduce

```console
scoop install sumatrapdf
```

### Possible Solution

Merge [the PR](https://github.com/ScoopInstaller/Extras/pull/12057)

### Scoop and Buckets Version

```console
❯ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
04c920ce0 (HEAD -> master, origin/master, origin/HEAD) zoom: Update to version 5.16.10.26186

'main' bucket:
64a70570c (HEAD -> master, origin/master, origin/HEAD) uncrustify: Update to version 0.78.1
```

### Scoop Config

```console
❯ scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-11-20T14:57:56.5884415+01:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3693
PSEdition                      Desktop
```

### Additional Softwares

Doesn't matter, URLs are broken!

**Comment by HUMORCE** [comment]
#12251
