### ISSUE TITLE
imageglass@9.0.7.1125: download via aria2 failed

### ISSUE THREAD

**Issue by BlackTeaEnjoyer** [ScoopInstaller/Extras#12313]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/d2phap/ImageGlass/releases/download/9.0.7.1125/ImageGlass_Kobe_9.0.7.1125_x64.zip
    referer=https://github.com/d2phap/ImageGlass/releases/download/9.0.7.1125/
    dir=C:\Users\home\scoop\cache
    out=imageglass#9.0.7.1125#https_github.com_d2phap_ImageGlass_releases_download_9.0.7.1125_ImageGlass_Kobe_9.0.7.1125_x64.zip

ERROR & 'C:\Users\home\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\home\scoop\cache\imageglass.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=9820 --continue --summary-interval=0 --auto-save-interval=1

**Comment by StarLuxana** [comment]
Maybe the download link should be "https://github.com/d2phap/ImageGlass/releases/download/9.0.7.1125/ImageGlass_9.0.7.1125_x64.zip" rather than "https://github.com/d2phap/ImageGlass/releases/download/9.0.7.1125/ImageGlass**_Kobe**_9.0.7.1125_x64.zip"

**Comment by StudentWeis** [comment]
too

**Comment by Xelbayria** [comment]
the link URL has "KOBE" in the old version. Version 9 doesn't have "KOBE".
