### ISSUE TITLE
wireshark@4.2.0: decompress error

### ISSUE THREAD

**Issue by xd-mau5** [ScoopInstaller/Extras#12375]
Updating 'wireshark' (4.0.10 -> 4.2.0)
Downloading new version
Loading Wireshark-4.2.0-x64.exe from cache
Checking hash of Wireshark-4.2.0-x64.exe ... ok.
Uninstalling 'wireshark' (4.0.10)
Installing 'wireshark' (4.2.0) [64bit] from extras bucket
Loading Wireshark-4.2.0-x64.exe from cache
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\elect\scoop\apps\wireshark\4.2.0\dl.7z.
Log file:
  ~\scoop\apps\wireshark\4.2.0\7zip.log
[7zip.log](https://github.com/ScoopInstaller/Extras/files/13506939/7zip.log)

**Comment by HUMORCE** [comment]
#12359
