### ISSUE TITLE
rancher-desktop@1.11.1: decompress error

### ISSUE THREAD

**Issue by killme00** [ScoopInstaller/Extras#12386]
Updating 'rancher-desktop' (1.11.0 -> 1.11.1)
Downloading new version
Rancher.Desktop.Setup.1.11.1.msi (691.4 MB) [======================================================================================================================================================================================] 100%
Checking hash of Rancher.Desktop.Setup.1.11.1.msi ... ok.
Uninstalling 'rancher-desktop' (1.11.0)
Unlinking ~\scoop\apps\rancher-desktop\current
Installing 'rancher-desktop' (1.11.1) [64bit] from extras bucket
Loading Rancher.Desktop.Setup.1.11.1.msi from cache
Extracting Rancher.Desktop.Setup.1.11.1.msi ... ERROR Exit code was 1618!
Failed to extract files from C:\Users\killm\scoop\apps\rancher-desktop\1.11.1\Rancher.Desktop.Setup.1.11.1.msi.
Log file:
  ~\scoop\apps\rancher-desktop\1.11.1\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=rancher-desktop%401.11.1%3a+decompress+error

**Comment by HUMORCE** [comment]
```
> scoop install extras/rancher-desktop
Installing 'rancher-desktop' (1.11.1) [64bit] from extras bucket
Loading Rancher.Desktop.Setup.1.11.1.msi from cache
Checking hash of Rancher.Desktop.Setup.1.11.1.msi ... ok.
Extracting Rancher.Desktop.Setup.1.11.1.msi ... done.
Linking ~\scoop\apps\rancher-desktop\current => ~\scoop\apps\rancher-desktop\1.11.1
Creating shortcut for Rancher Desktop (Rancher Desktop.exe)
'rancher-desktop' (1.11.1) was installed successfully!
Notes
-----
Rancher Desktop requires WSL (Windows Subsystem for Linux) to work properly.
Learn more about WSL: https://aka.ms/wsl2
```

Cannot reproduce.

---

This is usually caused by a msiexec process exception, go one of them:

- Restart the PC then retry.
- Switch to alternative MSI extractor: `scoop config use_lessmsi true` (Default: false)
- Resolve the msiexec exception then retry, If you know about it.

Learn more: https://learn.microsoft.com/en-us/windows/win32/msi/error-codes

**Comment by HUMORCE** [comment]
Temporarily closed, feel free to reopen this issue.

**Reasons:**
- Cannot reproduce.
- No response and additional information
