### ISSUE TITLE
[Request]: Betterbird

### ISSUE THREAD

**Issue by basketshoe** [ScoopInstaller/Extras#12415]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Betterbird

### Description

Betterbird is a fine-tuned version of Mozilla Thunderbird.

### Homepage

https://www.betterbird.eu/

### Download Link(s)

https://www.betterbird.eu/downloads/WindowsPortable/BetterbirdPortable-115.5.1-bb19-build2.en-US.win64.zip

### Some Indication of Popularity/Repute

300 stars on GH

**Comment by Ra2-IFV** [comment]
Hi there,
Would you try this [bucket](https://github.com/ifvlaboratory/ScoopBucket-ifvlab)? I'm planning to open a pull request but I'm not sure if I did anything wrong.

```bash
scoop bucket add ifvlab https://github.com/ifvlaboratory/ScoopBucket-ifvlab
scoop install betterbird
```
Also a preview version available with `betterbird-preview`, *should* have no conflicts with `betterbird`

**Comment by basketshoe** [comment]
@Ra2-IFV tested, seems to work fine

**Comment by basketshoe** [comment]
> I want to use the newer version which is Betterbird 128 Should I open a new issue?

Nope, it should update by itself but there must be a problem with the checkver
