### ISSUE TITLE
[Bug]: Everything installs the x86_64 version instead of arm64 on Windows on ARM

### ISSUE THREAD

**Issue by Xazax-hun** [ScoopInstaller/Extras#12434]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

everything

### Expected/Current Behaviour

Expected: install the arm64 version on Windows on ARM
Current: install the x86_64 version

### Steps to Reproduce

```console
scoop install everything
```

### Possible Solution

Add the arm64 version to the json file.

### Scoop and Buckets Version

```console
> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
674a0a86a (HEAD -> master, origin/master, origin/HEAD) dolphin: Update to version 23.08.4-2113

'main' bucket:
0a79b4d6c (HEAD -> master, origin/master, origin/HEAD) teleport: Update to version 14.2.2
```

### Scoop Config

```console
> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-12-08T19:07:33.5738477-08:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.26002.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.26002.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment]
The manifest did not contain arm64 before. I have added it now, but I did not fully test it, install and open it only.
