### ISSUE TITLE
[Request]: Gramps

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#12439]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

gramps

### Description

Gramps is a free software project and community. We strive to produce a genealogy program that is both intuitive for hobbyists and feature-complete for professional genealogists. It is a community project, created, developed and governed by genealogists.

### Homepage

https://gramps-project.org/blog/

### Download Link(s)

https://gramps-project.org/blog/download/

### Some Indication of Popularity/Repute

It has GitHub repo which has **1.9k stars** and **376 forks** ➡️  https://github.com/gramps-project/gramps

Also for the download page it has releases ➡️ https://github.com/gramps-project/gramps/releases

**Comment by danielpauldd** [comment]
I created a manifest for Gramps.

Currently it's provided in my scoop bucket:
https://github.com/danielpauldd/scoop-bucket.git

Please test and if desired, I can file a PR for integration into this bucket.

**Comment by aliesbelik** [comment]
> I created a manifest for Gramps.
> 
> Currently it's provided in my scoop bucket: https://github.com/danielpauldd/scoop-bucket.git
> 
> Please test and if desired, I can file a PR for integration into this bucket.

@danielpauldd Do not hesitate to submit a PR (preferably with a working and tested manifest) if you a ready.

**Comment by aliesbelik** [comment]
Closing as duplicate in favor of #11705.
