### ISSUE TITLE
foobar2000@2.0: decompress error

### ISSUE THREAD

**Issue by Hasix1** [ScoopInstaller/Extras#12454]
It looks like the Scoop download a binary installer(.exe) of foobar then simply rename it to .7z, and try to unzip it, which caused error.

> 7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
> 
> Scanning the drive for archives:
> 1 file, 6663937 bytes (6508 KiB)
> 
> Extracting archive: D:\Apps\Scoop\apps\foobar2000\2.0\dl.7z
> 
> Can't open as archive: 1
> Files: 0
> Size:       0
> Compressed: 0
> ERROR: D:\Apps\Scoop\apps\foobar2000\2.0\dl.7z
> D:\Apps\Scoop\apps\foobar2000\2.0\dl.7z
> Open ERROR: Can not open the file as [Nsis] archive

**Comment by HUMORCE** [comment]
> It looks like the Scoop download a binary installer(.exe) of foobar then simply rename it to .7z, and try to unzip it, which caused error.

Scoop makes the app as portable as possible.

---

Cannot reproduce, please update 7zip to latest version then retry.

```
> scoop install foobar2000
Installing 'foobar2000' (2.0) [arm64] from extras bucket
Loading foobar2000-arm64ec_v2.0.exe from cache
Checking hash of foobar2000-arm64ec_v2.0.exe ... ok.
Extracting dl.7z ... done.
Running installer script...
Linking ~\scoop\apps\foobar2000\current => ~\scoop\apps\foobar2000\2.0
Creating shim for 'foobar2000'.
Creating shortcut for Foobar2000 (foobar2000.exe)
Persisting profile
Running post_install script...
'foobar2000' (2.0) was installed successfully!
'foobar2000' suggests installing 'extras/foobar2000-encoders'.
> scoop uninstall foobar2000
Uninstalling 'foobar2000' (2.0).
Removing shim 'foobar2000.shim'.
Removing shim 'foobar2000.exe'.
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Foobar2000.lnk
Unlinking ~\scoop\apps\foobar2000\current
'foobar2000' was uninstalled.
> scoop install foobar2000 -a 64bit
Installing 'foobar2000' (2.0) [64bit] from extras bucket
foobar2000-x64_v2.0.exe (6.4 MB) [============================================================================] 100%
Checking hash of foobar2000-x64_v2.0.exe ... ok.
Extracting dl.7z ... done.
Running installer script...
Linking ~\scoop\apps\foobar2000\current => ~\scoop\apps\foobar2000\2.0
Creating shim for 'foobar2000'.
Creating shortcut for Foobar2000 (foobar2000.exe)
Persisting profile
Running post_install script...
'foobar2000' (2.0) was installed successfully!
'foobar2000' suggests installing 'extras/foobar2000-encoders'.
```

**Comment by HUMORCE** [comment]
Temporarily closed, feel free to reopen this issue.

**Reasons:**
- Cannot reproduce.
- No response and additional information
