### ISSUE TITLE
[Request]: Floorp

### ISSUE THREAD

**Issue by tizio04** [ScoopInstaller/Extras#12460]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Floorp

### Description

Floorp is built on Firefox and was built in Japan and is a new browser with excellent privacy & flexibility.

### Homepage

https://floorp.app/en/

### Download Link(s)

https://floorp.app/en/download/

### Some Indication of Popularity/Repute

It has GitHub repo which has 1.95k stars and 60 forks ➡️ https://github.com/Floorp-Projects/Floorp

Also for the download page it has releases ➡️ https://github.com/Floorp-Projects/Floorp/releases

**Comment by aliesbelik** [comment]
Portable version added in #12646.
