### ISSUE TITLE
[Request]: kubecolor

### ISSUE THREAD

**Issue by applejag** [ScoopInstaller/Extras#12492]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

kubecolor

### Description

Wraps kubectl with colorful output

### Homepage

https://github.com/kubecolor/kubecolor

### Download Link(s)

https://github.com/kubecolor/kubecolor/releases

### Some Indication of Popularity/Repute

The [kubecolor/kubecolor](https://github.com/kubecolor/kubecolor) is the sole successor to the [hidetatz/kubecolor](https://github.com/hidetatz/kubecolor) repo, which had 1.4k stars and 104 forks.

**Comment by applejag** [comment]
Should this package be placed in Main instead of here in Extras?

The issue (https://github.com/ScoopInstaller/Main/issues/5202) and PR (https://github.com/ScoopInstaller/Main/pull/5378) in Main seems to have been closed in favor of this issue and the PR (#12493) on this repo.

The new [kubecolor/kubecolor](https://github.com/kubecolor/kubecolor) repo does not have enough stars and forks for being in Main, but the predecessor repo ([hidetatz/kubecolor](https://github.com/hidetatz/kubecolor)) certainly has enough stars (1.4k). It was only missing the requirement for 150 forks (currently has 105 forks).

Would the new repo still qualify for being in Main, even though it technically doesn't have enough forks and stars?

**Comment by HUMORCE** [comment]
Please do it

**Comment by applejag** [comment]
Done :)

Closing in favor of new attempt at adding to Main bucket:

- issue: https://github.com/ScoopInstaller/Main/issues/5424
- PR: https://github.com/ScoopInstaller/Main/pull/5425
