### ISSUE TITLE
[Request]: otvdm

### ISSUE THREAD

**Issue by filip2cz** [ScoopInstaller/Extras#12533]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

otvdm

### Description

16-bit Windows (Windows 1.x, 2.x, 3.0, 3.1, etc.) emulator for 64-bit Windows.

### Homepage

https://github.com/otya128/winevdm/

### Download Link(s)

https://github.com/otya128/winevdm/releases/download/v0.9.0/otvdm-v0.9.0.zip

### Some Indication of Popularity/Repute

Stars: 2.3k
Forks: 137

**Comment by StudentWeis** [comment]
#12534
