### ISSUE TITLE
[Bug]: WeChat downloading returns 404

### ISSUE THREAD

**Issue by felixmaker** [ScoopInstaller/Extras#12597]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

wechat

### Expected/Current Behaviour

Installing 'wechat' (3.9.8.25) [64bit] from extras bucket
远程服务器返回错误: (404) 未找到。
URL https://webcdn.m.qq.com/spcmgr/download/WeChat3.9.8.25.exe#/dl.7z is not valid

404 from server

### Steps to Reproduce

```console
PS> scoop install wechat
```

### Possible Solution

change the download url to https://dldir1v6.qq.com/weixin/Windows/WeChatSetup.exe

https://github.com/microsoft/winget-pkgs/blob/11a18ba96d92e399c47c2ba21fec72fa28e48384/manifests/t/Tencent/WeChat/3.9.8.25/Tencent.WeChat.installer.yaml#L13C68-L13C68

### Scoop and Buckets Version

```console
v0.3.1 - Released at 2022-11-15

'extras' bucket:
8968c8759 (HEAD -> master, origin/master, origin/HEAD) strawberry: Update to version 1.0.23

'felixmaker' bucket:
e61cc5e (HEAD -> master, origin/master, origin/HEAD) Add quark shortcuts

'main' bucket:
93829e7a4 (HEAD -> master, origin/master, origin/HEAD) trid: Update to version 2.24-24.01.12

'versions' bucket:
68e8002a4 (HEAD -> master, origin/master, origin/HEAD) ipfilter-nightly@1704949644: Fix hash (Closes #1532)
```

### Scoop Config

```console
~ $ scoop config


last_update   : 2024-01-12T15:35:20.4852821+08:00
aria2-enabled : False
aria2-split   : 5
scoop_branch  : master
scoop_repo    : http://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\Users\Felixmaker> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by felixmaker** [comment]
It seems the download url `https://sw.pcmgr.qq.com/c8491cddaa9f701a66a08d256781a7bd/65a27d91/spcmgr/download/202401/WeChat3.9.8.25.exe#/dl.7z` is a temporary url.

**Comment by HUMORCE** [comment]
Switched to official download urls: https://github.com/ScoopInstaller/Extras/commit/244baf0709bae0598a821212c8161f55a9604d87

unmaintainable app.
