### ISSUE TITLE
[Request]: Floorp Browser

### ISSUE THREAD

**Issue by CryoRenegade** [ScoopInstaller/Extras#12645]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Floorp

### Description

A Browser build for keeping the Open, Private and Sustainable Web alive. Based on Mozilla Firefox.

### Homepage

https://github.com/Floorp-Projects

### Download Link(s)

https://github.com/Floorp-Projects/Floorp-Portable/releases/download/11.7.1-portable/floorp-11.7.1-portable-windows-x86_64.zip

### Some Indication of Popularity/Repute

2.5k stars on github

**Comment by aliesbelik** [comment]
Duplicates #12460.
