### ISSUE TITLE
AppFlowy@0.4.2: There is no such package name.

### ISSUE THREAD

**Issue by cnxv** [ScoopInstaller/Extras#12647]
ERROR https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.4.2/AppFlowy-0.4.2-windows-x86_64.zip
![image](https://github.com/ScoopInstaller/Extras/assets/102273178/c38b613f-f1bf-47ca-b959-45cf95720471)

There is also an issue with the download link. The remote server returns the error: (404) Not Found.

**Comment by Xelbayria** [comment]
& Appflowy has been updated to v4.3

**Comment by Xelbayria** [comment]
Someone should run a test by running the app and see if it works.  the reason is a comment left by a dev is here: [AppFlowy-issue#4430](https://github.com/AppFlowy-IO/AppFlowy/issues/4430#issuecomment-1902182387)

**Comment by Xelbayria** [comment]
The ZIP version has returned to v4.3. 

that's all, folks!
