### ISSUE TITLE
[Bug]: Will opencppCoverage works with a dll ?

### ISSUE THREAD

**Issue by pradeep0608** [ScoopInstaller/Extras#12640]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

0.9.9.0

### Expected/Current Behaviour

C:\Users\se513f>"C:\USERS\SE513F\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_33F6B16D\EXTENSIONS\I24U1A4J.CGO\OpenCppCoverage-x64\OpenCppCoverage.exe" --config_file "C:\Users\se513f\AppData\Local\Temp\wvgjffvq.4e1" -- "C:\MST\Repos\mst-737-ng\planeLogic\vcSim\bin\Debug\SimDriverUnitTests.dll"
[info] Start Program:
Path:"C:\\MST\\Repos\\mst-737-ng\\planeLogic\\vcSim\\bin\\Debug\\SimDriverUnitTests.dll"
Arguments:
Working directory: "C:\\MST\\Repos\\mst-737-ng\\planeLogic\\SimDriverUnitTests\\"
Modules: Selected: C:\MST\Repos\mst-737-ng\planeLogic\vcSim\SourceCode\CSFCodeGen\Debug\CSFCodeGen.lib C:\MST\Repos\mst-737-ng\planeLogic\vcSim\bin\Debug\SimDriver.dll C:\MST\Repos\mst-737-ng\planeLogic\vcSim\bin\Debug\SimDriverUnitTests.dll Excluded:
Sources: Selected: C:\MST\Repos\mst-737-ng\planeLogic\SourceCode\SimDriver\CodeGen C:\MST\Repos\mst-737-ng\planeLogic\vcSim\SourceCode\CSFCodeGen C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\3rdParty\Choreograph\src\choreograph C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\3rdParty\sqliteorm C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\3rdParty\stackwalker C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\InputSystem C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\Source C:\MST\Repos\mst-737-ng\planeLogic\SimCommonNG-MAX\Source\Components C:\MST\Repos\mst-737-ng\planeLogic\SourceCode\SimDriver\CodeGen\ExecSpecific C:\MST\Repos\mst-737-ng\planeLogic\SourceCode\SimDriver\Components C:\MST\Repos\mst-737-ng\planeLogic\vcSim\SourceCode\SimDriver C:\MST\Repos\mst-737-ng\planeLogic\SimDriverUnitTests Excluded:
Log Level: Normal
Cover Children: 0
Aggregate by file: 1
Continue after C++ exception: 0
Optimized build support: 0
Export: binary C:\Users\se513f\AppData\Local\Temp\h3zgt2vl.v1p
Input coverage:
Unified diff:
Excluded line regular expressions:
Substitute pdb source paths:

[error] Error: Cannot run process, check if it is a valid executable:
Path:"C:\\MST\\Repos\\mst-737-ng\\planeLogic\\vcSim\\bin\\Debug\\SimDriverUnitTests.dll"
Arguments:
Working directory: "C:\\MST\\Repos\\mst-737-ng\\planeLogic\\SimDriverUnitTests\\"Last error code:193

### Steps to Reproduce

```console
C:\Users\se513f>"C:\USERS\SE513F\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_33F6B16D\EXTENSIONS\I24U1A4J.CGO\OpenCppCoverage-x64\OpenCppCoverage.exe" --config_file "C:\Users\se513f\AppData\Local\Temp\wvgjffvq.4e1" -- "C:\MST\Repos\mst-737-ng\planeLogic\vcSim\bin\Debug\SimDriverUnitTests.dll"
[info] Start Program:
Path:"C:\\MST\\Repos\\mst-737-ng\\planeLogic\\vcSim\\bin\\Debug\\SimDriverUnitTests.dll"
Arguments:
Working directory: "C:\\MST\\Repos\\mst-737-ng\\planeLogic\\SimDriverUnitTests\\"
Modules: Selected: C:\MST\Repos\mst-737-ng\planeLogic\vcSim\SourceCode\CSFCodeGen\Debug\CSFCodeGen.lib C:\MST\Repos\mst-737-ng\planeLogic\vcSim\bin\Debug\SimDriver.dll C:\MST\Repos\mst-737-ng\planeLogic\vcSim\bin\Debug\SimDriverUnitTests.dll Excluded:
Sources: Selected: C:\MST\Repos\mst-737-ng\planeLogic\SourceCode\SimDriver\CodeGen C:\MST\Repos\mst-737-ng\planeLogic\vcSim\SourceCode\CSFCodeGen C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\3rdParty\Choreograph\src\choreograph C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\3rdParty\sqliteorm C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\3rdParty\stackwalker C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\InputSystem C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\Source C:\MST\Repos\mst-737-ng\planeLogic\SimCommonNG-MAX\Source\Components C:\MST\Repos\mst-737-ng\planeLogic\SourceCode\SimDriver\CodeGen\ExecSpecific C:\MST\Repos\mst-737-ng\planeLogic\SourceCode\SimDriver\Components C:\MST\Repos\mst-737-ng\planeLogic\vcSim\SourceCode\SimDriver C:\MST\Repos\mst-737-ng\planeLogic\SimDriverUnitTests Excluded:
Log Level: Normal
Cover Children: 0
Aggregate by file: 1
Continue after C++ exception: 0
Optimized build support: 0
Export: binary C:\Users\se513f\AppData\Local\Temp\h3zgt2vl.v1p
Input coverage:
Unified diff:
Excluded line regular expressions:
Substitute pdb source paths:

[error] Error: Cannot run process, check if it is a valid executable:
Path:"C:\\MST\\Repos\\mst-737-ng\\planeLogic\\vcSim\\bin\\Debug\\SimDriverUnitTests.dll"
Arguments:
Working directory: "C:\\MST\\Repos\\mst-737-ng\\planeLogic\\SimDriverUnitTests\\"Last error code:193
```

### Possible Solution

I Have written units in cpp with cppunit framework.I have created a dll solution SimDriverTests.dll to write unit tests for  SimDriver.dll.Please let me know if we can code coverage for SimDriverTests.dll

### Scoop and Buckets Version

```console
C:\Users\se513f>"C:\USERS\SE513F\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_33F6B16D\EXTENSIONS\I24U1A4J.CGO\OpenCppCoverage-x64\OpenCppCoverage.exe" --config_file "C:\Users\se513f\AppData\Local\Temp\wvgjffvq.4e1" -- "C:\MST\Repos\mst-737-ng\planeLogic\vcSim\bin\Debug\SimDriverUnitTests.dll"
[info] Start Program:
Path:"C:\\MST\\Repos\\mst-737-ng\\planeLogic\\vcSim\\bin\\Debug\\SimDriverUnitTests.dll"
Arguments:
Working directory: "C:\\MST\\Repos\\mst-737-ng\\planeLogic\\SimDriverUnitTests\\"
Modules: Selected: C:\MST\Repos\mst-737-ng\planeLogic\vcSim\SourceCode\CSFCodeGen\Debug\CSFCodeGen.lib C:\MST\Repos\mst-737-ng\planeLogic\vcSim\bin\Debug\SimDriver.dll C:\MST\Repos\mst-737-ng\planeLogic\vcSim\bin\Debug\SimDriverUnitTests.dll Excluded:
Sources: Selected: C:\MST\Repos\mst-737-ng\planeLogic\SourceCode\SimDriver\CodeGen C:\MST\Repos\mst-737-ng\planeLogic\vcSim\SourceCode\CSFCodeGen C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\3rdParty\Choreograph\src\choreograph C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\3rdParty\sqliteorm C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\3rdParty\stackwalker C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\InputSystem C:\MST\Repos\mst-737-ng\planeLogic\SimCommon\Source C:\MST\Repos\mst-737-ng\planeLogic\SimCommonNG-MAX\Source\Components C:\MST\Repos\mst-737-ng\planeLogic\SourceCode\SimDriver\CodeGen\ExecSpecific C:\MST\Repos\mst-737-ng\planeLogic\SourceCode\SimDriver\Components C:\MST\Repos\mst-737-ng\planeLogic\vcSim\SourceCode\SimDriver C:\MST\Repos\mst-737-ng\planeLogic\SimDriverUnitTests Excluded:
Log Level: Normal
Cover Children: 0
Aggregate by file: 1
Continue after C++ exception: 0
Optimized build support: 0
Export: binary C:\Users\se513f\AppData\Local\Temp\h3zgt2vl.v1p
Input coverage:
Unified diff:
Excluded line regular expressions:
Substitute pdb source paths:

[error] Error: Cannot run process, check if it is a valid executable:
Path:"C:\\MST\\Repos\\mst-737-ng\\planeLogic\\vcSim\\bin\\Debug\\SimDriverUnitTests.dll"
Arguments:
Working directory: "C:\\MST\\Repos\\mst-737-ng\\planeLogic\\SimDriverUnitTests\\"Last error code:193
```

### Scoop Config

```console
NA
```

### PowerShell Version

```console
NA
```

### Additional Softwares

NA

**Comment by aliesbelik** [comment]
@pradeep0608, OpenCppCoverage is not at the moment in scoop's Extras bucket.
I guess this issue belongs [to the original repo](https://github.com/OpenCppCoverage/OpenCppCoverage/issues).

**Comment by aliesbelik** [comment]
Closing as not related.
