### ISSUE TITLE
thorium@119.0.6045.214: Decompress Error

### ISSUE THREAD

**Issue by Icey-Glitch** [ScoopInstaller/Extras#12654]
Could not find 'Thorium_119.0.6045.214 in C:\Users\'user'\scoop\apps\thorium\119.0.6045.214'!

**Comment by RobMcRob24** [comment]
Hi, 

I've the same problem!

> scoop install thorium
Installing 'thorium' (119.0.6045.214) [64bit] from extras bucket
Loading Thorium_119.0.6045.214.zip from cache
Checking hash of Thorium_119.0.6045.214.zip ... ok.
Extracting Thorium_119.0.6045.214.zip ... Exception: C:\rsc\scoop\apps\scoop\current\lib\core.ps1:638
Line |
 638 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'Thorium_119.0.6045.214'! (error 16)

Can you please help?

Thanks!

**Comment by aliesbelik** [comment]
Please update, fixed for the current version.
