### ISSUE TITLE
[Bug]: LibreOffice gets updates to pre-release and unpublished builds

### ISSUE THREAD

**Issue by csdivad** [ScoopInstaller/Extras#12652]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

libreoffice

#### Expected Behaviour
Package stays on latest fresh/stable version.

#### Current Behaviour
Package gets updates to pre-release or unpublished builds.

#### Description

A new update rolled out to LibreOffice in cef7e5698743f44e6d56338589a5c225b8280cd9 that went from `7.6.4.1 fresh/stable` to `24.2.0.2 pre-release`. I don't think this package should be updated to such versions. Rather there should be a separate libreoffice-prerelease package if someone needs that.

Also I remember some older Scoop LibreOffice versions that were never published on their main website. They pushed some build into [this download archive site](https://downloadarchive.documentfoundation.org/libreoffice/old/) but they were not published on the main libreoffice.org page. The Scoop package however was updated to it.
That can be confusing to users. They check the latest version on LibreOffice website and it is older than what scoop installed. Some might think that scoop does something nasty. Also there might be a reason that the build is not published on the main site. Maybe it was recalled due to a bug. But I guess these version bumps are automated so it might not be as easy to always be on the same version as being advertised on their website. Also see the "Possible Solution" section.

### Steps to Reproduce

```console
PS> scoop install libreoffice
```

### Possible Solution

Use https://download.documentfoundation.org/libreoffice/stable/ as the source archive site instead of https://downloadarchive.documentfoundation.org/libreoffice/old/.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
447d6335b (HEAD -> master, origin/master, origin/HEAD) privacy.sexy: Update to version 0.12.10

'main' bucket:
455878a98 (HEAD -> master, origin/master, origin/HEAD) mingw-nuwen: Update to version 19.0

'versions' bucket:
e163e5733 (HEAD -> master, origin/master, origin/HEAD) logseq-nightly: Update to version 0.10.4-20240118
```

### Scoop Config

```console
PS> scoop config

last_update                       show_manifest scoop_branch scoop_repo
-----------                       ------------- ------------ ----------
2024-01-18T15:05:01.9589377+01:00          True master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by amreus** [comment]
Which version of LibreOffice should `libreoffice.json` refer to?  Still or Fresh?

The LibreOffice site does not make it easy to pick out versions automatically. A good link may be the Release Notes page which specifies both the version name and version number:

https://www.libreoffice.org/download/release-notes/

I do not see where they publish the hash keys needed for verification. Can the update be automated without a published hash key?

**Comment by csdivad** [comment]
The bug mentioned here is actually neither.
However I think there should be two libreoffice package, one for still and one for fresh.
I'm a fresh user myself.

**Comment by amreus** [comment]
@csdivad I did make a pull request that updates the manifest to the current Fresh release.  

If you really need it, you can use `scoop install https://raw.githubusercontent.com/amreus/scoop-extras/e2784824954bfc12304364ffd398e9b66007b69e/bucket/libreoffice.json` to install. Then when the official Extras bucket is updated, you can uninstall and reinstall normally.

**Comment by amreus** [comment]
> However I think there should be two libreoffice package, one for still and one for fresh. I'm a fresh user myself.

I agree, but there's a trade-off between having the choice vs the complexity of the manifest file.  The manifest I made will do for now to get package back to latest 'Fresh" release, and will pick up future Fresh stable releases.
