### ISSUE TITLE
[Request]: bzip3

### ISSUE THREAD

**Issue by LinArcX** [ScoopInstaller/Extras#12674]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

bzip3

### Description

A better and stronger spiritual successor to BZip2.

### Homepage

https://github.com/kspalaiologos/bzip3

### Download Link(s)

https://github.com/kspalaiologos/bzip3/releases

### Some Indication of Popularity/Repute

It has more features than normal bzip and bzip2.

**Comment by aliesbelik** [comment]
Fixed by #12835.
