### ISSUE TITLE
ddu@18.0.7.1: decompress error

### ISSUE THREAD

**Issue by WXZhao7** [ScoopInstaller/Extras#12692]
C:\Users\wxz>scoop install ddu
Installing 'ddu' (18.0.7.1) [64bit] from extras bucket
%5BGuru3D.com%5D-DDU.zip (1.0 MB) [===========================================================================] 100%
Checking hash of %5BGuru3D.com%5D-DDU.zip ... ok.
Extracting %5BGuru3D.com%5D-DDU.zip ... done.
Running pre_install script...
ERROR Exit code was 2!
Failed to extract files from C:\Users\wxz\scoop\apps\ddu\18.0.7.1/DDU v18.0.7.1.exe.
Log file:
  ~\scoop\apps\ddu\18.0.7.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=ddu%4018.0.7.1%3a+decompress+error

**Comment by aliesbelik** [comment]
Fixed in c91b531.
In fact it was linked to 18.0.7.2, looks like Excavator script didn't update manifest on time.
