### ISSUE TITLE
[Request]: gramps

### ISSUE THREAD

**Issue by ivaquero** [ScoopInstaller/Extras#12725]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

gramps

### Description

a genealogy program that is both intuitive for hobbyists and feature-complete for professional genealogists

### Homepage

https://github.com/gramps-project/gramps

### Download Link(s)

https://github.com/gramps-project/gramps/releases/download/v5.1.6/GrampsAIO-5.1.6-1_win64.exe

### Some Indication of Popularity/Repute

GitHub stars: 1.9k

**Comment by aliesbelik** [comment]
> ### Prerequisites
> 
>     * [x]  I have searched all issues/PRs to ensure it has not already been reported or fixed.

Duplicates #11705, #12439, already added in #12680.

**Comment by ivaquero** [comment]
Sorry, I missed this result..
