### ISSUE TITLE
hexo-client@1.3.6: decompress error

### ISSUE THREAD

**Issue by systemcaller** [ScoopInstaller/Extras#12734]
I want to install hexo, but error ,  logs :

PS C:\Users\zuoyu> scoop install hexo-client
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'hexo-client' (1.3.6) [64bit] from extras bucket
proxy: https://github.com/gaoyoubo/hexo-client/releases/download/v1.3.6/HexoClient-Setup-1.3.6.exe#/dl.7z

Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: da199c|OK  |   838KiB/s|D:/Program Files For Code/Scoop/cache/hexo-client#1.3.6#https_github.com_gaoyoubo_hexo-client_releases_download_v1.3.6_HexoClient-Setup-1.3.6.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of HexoClient-Setup-1.3.6.exe ... ok.
Extracting dl.7z ... done.
Running installer script...
ERROR Exit code was 2!
Failed to extract files from D:\Program Files For Code\Scoop\apps\hexo-client\1.3.6\$PLUGINSDIR\app-32.7z.
Log file:
  D:\Program Files For Code\Scoop\apps\hexo-client\1.3.6\$PLUGINSDIR\7zip.log

Please try again or create a new issue by using the following link and paste your console output:

**Comment by systemcaller** [comment]
7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:

ERROR: 系统找不到指定的文件。
D:\Program Files For Code\Scoop\apps\hexo-client\1.3.6\$PLUGINSDIR\app-32.7z

------------------------------not have app-32.7z, but have app-64.7z ---------------------------
PS D:\Program Files For Code\Scoop\apps\hexo-client\1.3.6\$PLUGINSDIR> ls


    目录: D:\Program Files For Code\Scoop\apps\hexo-client\1.3.6\$PLUGINSDIR


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         2024/2/2     22:45            286 7zip.log
-a----       2020/11/14     13:39       46869927 app-64.7z
-a----         2024/2/2     22:45           6656 nsExec.dll
-a----         2024/2/2     22:45         434176 nsis7z.dll
-a----         2024/2/2     22:45           4608 nsProcess.dll
-a----         2024/2/2     22:45           9216 SpiderBanner.dll
-a----         2024/2/2     22:45         102400 StdUtils.dll
-a----         2024/2/2     22:45          11776 System.dll
-a----         2024/2/2     22:45           3072 WinShell.dll

**Comment by aliesbelik** [comment]
Same as #4986, looks like it wasn't fixed since closed by stale bot.
Thank you for raising PR.
