### ISSUE TITLE
[Request]: MediaElch

### ISSUE THREAD

**Issue by bfcns** [ScoopInstaller/Extras#12749]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

mediaelch

### Description

Media Manager for Kodi

### Homepage

https://mediaelch.github.io/mediaelch-doc/about.html

### Download Link(s)

https://github.com/Komet/MediaElch/releases/download/v2.10.6/MediaElch_win_10_or_later_Qt6_2.10.6_2023-12-03_git-6121419e.zip

### Some Indication of Popularity/Repute

It is almost on all package managers on linux, being using it for years.
It already has a manifest at https://github.com/Youxikong/selfscoop, but I think it belongs to extras.

**Comment by aliesbelik** [comment]
@bfcns Feel free to raise a PR if your manifest is ready.
