### ISSUE TITLE
vcredist2022@14.38.33130.0: hash check failed

### ISSUE THREAD

**Issue by Nic-Vladimir** [ScoopInstaller/Extras#12750]
I get a "Hash check failed" error when installing vcredist2022 with scoop.

I first did:
`scoop install neovim`

It then said Neovim recommends to install vcredist2022 so I tried getting that but it won't let me. 
This was the console output:

> Installing 'vcredist2022' (14.38.33130.0) [64bit] from extras bucket
> vc_redist.x64.exe (24.2 MB) [=================================================================================] 100%
> Checking hash of vc_redist.x64.exe ... ERROR Hash check failed!
> App:         extras/vcredist2022
> URL:         https://aka.ms/vs/17/release/vc_redist.x64.exe
> First bytes: 4D 5A 90 00 03 00 00 00
> Expected:    4dfe83c91124cd542f4222fe2c396cabeac617bb6f59bdcbdf89fd6f0df0a32f
> Actual:      1ad7988c17663cc742b01bef1a6df2ed1741173009579ad50a94434e54f56073

I know hash checks are used to verify the source and integrity of a file, if it has been tempered with or whatever so I didn't install **vc_redist.x64.exe** manually even though the URL in the console output provides the file.

**Comment by aliesbelik** [comment]
Seems to be ok as for actual (`14.38.33135.0`) version:

```
λ scoop download vcredist2022
INFO  Starting download for vcredist2022...
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 25fa45|OK  |   1.2MiB/s|C:/Users/test/scoop/cache/vcredist2022#14.38.33135.0#https_aka.ms_vs_17_release_vc_redist.x86.exe
Download: 49dd4c|OK  |   2.1MiB/s|C:/Users/test/scoop/cache/vcredist2022#14.38.33135.0#https_aka.ms_vs_17_release_vc_redist.x64.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of vc_redist.x64.exe ... ok.
Checking hash of vc_redist.x86.exe ... ok.
'vcredist2022' (14.38.33135.0) was downloaded successfully!
```

**Comment by DioChuks** [comment]
scoop install vcredist2022 throws error " Couldn't find manifest for 'vcredist2022'" i checked the repo, and it seems the manifest is not there either. Any other way to get extras/vcredist2022?

**Comment by DioChuks** [comment]
Got the url for the updated vcredist from microsoft: [vcredist](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
downloaded the updated vcredist2015-2022
and clicked repair, since i already had one installed earlier. 
it showed repairing to the version: `14.38.33135.0` and restarted.
former version was : `14.36.32532.0`

all this was due to `zig` suggesting to install `extras/vcredist2022`
