### ISSUE TITLE
postman@10.23.0: download via aria2 failed

### ISSUE THREAD

**Issue by rupertbenbrook** [ScoopInstaller/Extras#12777]
postman: 10.22.0 -> 10.23.0
Updating one outdated app:
Updating 'postman' (10.22.0 -> 10.23.0)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: d70a3c|ERR |       0B/s|C:/Users/ruper/scoop/cache/postman#10.23.0#https_dl.pstmn.io_download_10.23.0_Postman-win64-10.23.0-Setup.exe_dl.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://dl.pstmn.io/download/10.23.0/Postman-win64-10.23.0-Setup.exe#/dl.7z
    referer=https://dl.pstmn.io/download/10.23.0/Postman-win64-10.23.0-Setup.exe#/
    dir=C:\Users\ruper\scoop\cache
    out=postman#10.23.0#https_dl.pstmn.io_download_10.23.0_Postman-win64-10.23.0-Setup.exe_dl.7z

ERROR & 'C:\Users\ruper\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\ruper\scoop\cache\postman.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=19288 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=postman%4010.23.0%3a+download+via+aria2+failed

**Comment by m4ss1m0g** [comment]
Tried also without aria2

```
 111 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.
```

**Comment by aliesbelik** [comment]
```
λ scoop install postman
Installing 'postman' (10.23.0) [64bit] from extras bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 08e34d|OK  |   2.7MiB/s|C:/Users/test/scoop/cache/postman#10.23.0#https_dl.pstmn.io_download_10.23.0_Postman-win64-10.23.0-Setup.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of Postman-win64-10.23.0-Setup.exe ... ok.
Extracting dl.7z ... done.
Running installer script...
Linking ~\scoop\apps\postman\current => ~\scoop\apps\postman\10.23.0
Creating shortcut for Postman (Postman.exe)
'postman' (10.23.0) was installed successfully!
```

**Comment by rupertbenbrook** [comment]
Now resolved for me. Maybe the CDN is still populating?

**Comment by aliesbelik** [comment]
Not reproducible both with and without aria:
```
λ scoop download postman
INFO  Starting download for postman...
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 05f41c|OK  |   2.8MiB/s|C:/Users/test/scoop/cache/postman#10.23.0#https_dl.pstmn.io_download_10.23.0_Postman-win64-10.23.0-Setup.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of Postman-win64-10.23.0-Setup.exe ... ok.
'postman' (10.23.0) was downloaded successfully!
```
```
λ scoop download postman
INFO  Starting download for postman...
Postman-win64-10.23.0-Setup.exe (132.2 MB) [==================================================================================================================] 100%
Checking hash of Postman-win64-10.23.0-Setup.exe ... ok.
'postman' (10.23.0) was downloaded successfully!
```
