### ISSUE TITLE
[Request]: QQ-NT

### ISSUE THREAD

**Issue by argvchs** [ScoopInstaller/Extras#12803]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

QQ-NT

### Description

An instant messaging tool that gives you the best way to keep in touch with your friends and family, build with Electron.

### Homepage

https://im.qq.com/pcqq/index.shtml

### Download Link(s)

https://dldir1.qq.com/qqfile/qq/QQNT/897bf087/QQ9.9.7.21484_x64.exe

### Some Indication of Popularity/Repute

QQ-NT is an instant messaging software that is widely used in mainland China and is also used by some foreigners when they study and work in China. The software is produced by Tencent and has a very large number of users.

#11329 #11546 #11554

**Comment by Yakkhini** [comment]
I vote for this. It seems like several PR was created and QQ-NT not been merged by some trivial reason. It is worth to update QQ to 9.9 version which [is a official release now](https://im.qq.com/index/).
