### ISSUE TITLE
[Request]: Doublecmd-beta

### ISSUE THREAD

**Issue by kroteau** [ScoopInstaller/Extras#12823]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [ ] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

doublecmd-beta

### Description

Two pane file manager inspired by Total Commander (Beta)

### Homepage

https://doublecmd.sourceforge.io/

### Download Link(s)

https://sourceforge.net/p/doublecmd/wiki/Download-Beta/

### Some Indication of Popularity/Repute

After version 1.0.11, active development transitioned to 'beta' versions, which are tagged as pre-releases on GitHub.
SourceForge stable releases and 'beta' versions have separate download pages now.

**Comment by kroteau** [comment]
Since "beta" are not matching "Latest stable version" might not fit here.

**Comment by goyalyashpal** [comment]
@kroteau please open this request. there are lots of packages on scoop with "-git" prefix, which themselves mostly are like snapshots.

**Comment by aliesbelik** [comment]
@goyalyashpal already submitted in Versions (ScoopInstaller/Versions#1604 / ScoopInstaller/Versions#1605).
