### ISSUE TITLE
[Request]: ShareX

### ISSUE THREAD

**Issue by xiaoxstz** [ScoopInstaller/Extras#12844]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

SharpX

### Description

ShareX is a free and open source program that lets you capture or record any area of your screen and share it with a single press of a key. It also allows uploading images, text or other types of files to many supported destinations you can choose from.

### Homepage

https://github.com/ShareX/ShareX/tree/master

### Download Link(s)

https://github.com/ShareX/ShareX/releases

### Some Indication of Popularity/Repute

GitHub stars: 26.9k

GitHub forks: 3k

**Comment by aliesbelik** [comment]
Already in Extras.
