### ISSUE TITLE
[Request]: FurMark 2

### ISSUE THREAD

**Issue by Herobrine-ymf** [ScoopInstaller/Extras#12861]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

FurMark 2

### Description

FurMark 2 is the successor of the FurMark 1

### Homepage

https://geeks3d.com/furmark/

### Download Link(s)

https://geeks3d.com/furmark/downloads/

### Some Indication of Popularity/Repute

-

**Comment by brian6932** [comment]
Should this be a separate package, or should `furmark` be updated and a `furmark1` be put into the Versions bucket?
I'm leaning towards the latter.

**Comment by hismailbulut** [comment]
> FurMark 2
FurMark 2 is the successor of the venerable FurMark 1 and is a very intensive GPU stress test on Windows (32-bit and 64-bit) and Linux (32-bit and 64-bit) platforms. It's also a quick OpenGL and Vulkan graphics benchmark with [online scores](https://gpumagick.com/scores/). FurMark 2 has an improved [command line](https://geeks3d.com/furmark/command-line/) support and is built with [GeeXLab](https://geeks3d.com/geexlab/).

> FurMark 1
FurMark 1 is still there and will be maintained for several more years. FurMark 1 is a very intensive graphics card stress test on Windows 32-bit platform. It's also a quick OpenGL benchmark with [online scores](https://gpuscore.top/furmark/).

I think there is no need for both versions in extras bucket. The old version should be in Versions bucket.
