### ISSUE TITLE
okular@23.08.4-1673: download via aria2 failed

### ISSUE THREAD

**Issue by H3T-Shah** [ScoopInstaller/Extras#12896]
The log I got after running the command
`scoop install okular`

`WARN  Purging previous failed installation of okular.
ERROR 'okular' isn't installed correctly.
Removing older version (23.08.4-1673).
'okular' was uninstalled.
Starting download with aria2 ...
Download: 03/03 15:54:10 [ERROR] CUID#8 - Download aborted. URI=https://binary-factory.kde.org/job/Okular_Release_win64/Download: Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://binary-factory.kde.org/job/Okular_Release_win64/1Download:   -> [AbstractCommand.cc:789] errorCode=19 CUID#8 - Name resolution for binary-factory.kde.org failed:Domain nDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 2baf71|ERR |       0B/s|D:/Program Files/Scoop/cache/okular#23.08.4-1673#https_binary-factory.kde.org_job_Okular_Release_win64_1673_artifact_okular-23.08.4-1673-windows-cl-msvc2019-x86_64.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 19) Name resolution failed
ERROR https://binary-factory.kde.org/job/Okular_Release_win64/1673/artifact/okular-23.08.4-1673-windows-cl-msvc2019-x86_64.7z
    referer=https://binary-factory.kde.org/job/Okular_Release_win64/1673/artifact/
    dir=D:\Program Files\Scoop\cache
    out=okular#23.08.4-1673#https_binary-factory.kde.org_job_Okular_Release_win64_1673_artifact_okular-23.08.4-1673-windows-cl-msvc2019-x86_64.7z

ERROR & 'D:\Program Files\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Program Files\Scoop\cache\okular.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3548 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=okular%4023.08.4-1673%3a+download+via+aria2+failed`

Maybe some of you would say, you should have `scoop install extras/okular` run these!
But the error persist

Also I found a file named "okular.txt" in cache folder with,
`https://binary-factory.kde.org/job/Okular_Release_win64/1673/artifact/okular-23.08.4-1673-windows-cl-msvc2019-x86_64.7z
    referer=https://binary-factory.kde.org/job/Okular_Release_win64/1673/artifact/
    dir=D:\Program Files\Scoop\cache
    out=okular#23.08.4-1673#https_binary-factory.kde.org_job_Okular_Release_win64_1673_artifact_okular-23.08.4-1673-windows-cl-msvc2019-x86_64.7z

`
these in it.
Need something else I didn't provide let me know

**Comment by H3T-Shah** [comment]
Tried using ` scoop config aria2-enabled false `
still ` No such host is known. (binary-factory.kde.org:443) URL https://binary-factory.kde.org/job/Okular_Release_win64/1673/artifact/okular-23.08.4-1673-windows-cl-msvc2019-x86_64.7z is not valid `

**Comment by aliesbelik** [comment]
Relates to #12897.
