### ISSUE TITLE
[Bug]: Trojan detected Discord 1.0.9035-18

### ISSUE THREAD

**Issue by basketshoe** [ScoopInstaller/Extras#12946]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

Discord

### Expected/Current Behaviour

Trojan detected by [MS Defender](https://imgbox.com/ljqyJx36) and [VirusTotal](https://www.virustotal.com/gui/file/21cb59a22af9f25a4587ce0eb5263e0fe753078a6e43c3cf931521dff2297009)

Also see https://github.com/portapps/discord-portable/issues/118

### Steps to Reproduce

```console
PS> scoop install discord
```

### Possible Solution

N/A

### Scoop and Buckets Version

```console
N/A
```

### Scoop Config

```console
N/A
```

### PowerShell Version

```console
N/A
```

**Comment by Skyppex** [comment]
When i do this and quarantine the trojan file, discord doesn't launch. Is there any progress on this issue?

**Comment by basketshoe** [comment]
@Skyppex see https://github.com/portapps/discord-portable/issues/118#issuecomment-1994134317
