### ISSUE TITLE
[Bug]: Cleanup Command deletes all Floorp data

### ISSUE THREAD

**Issue by WNnitro** [ScoopInstaller/Extras#12958]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

Floorp

### Expected/Current Behaviour

I'm trying to run `scoop cleanup *` to delete previous installations of my packages. However, this command deletes the `Profiles` folder of my `Floorp` installation instead, which is not what im expecting.
![img-2024-03-15-18-19-05](https://github.com/ScoopInstaller/Extras/assets/70445335/ca88a6e6-da59-404d-880a-6032a98aa40c)

### Steps to Reproduce

```console
1. Install Scoop
2. run 'scoop bucket add extras'
3. run 'scoop install extras/floorp'
4. open Floorp, close it.
5. run 'scoop cleanup *'
```

### Possible Solution

not deleting the profiles folder.

### Scoop and Buckets Version

```console
PS C:\Users\Administrator> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
2a36a45d4 (HEAD -> master, origin/master, origin/HEAD) tidal: Add version 2.36.2 (#12941)

'LuoHuiRu_ScoopBucket' bucket:
3fdae5c (HEAD -> master, origin/master, origin/HEAD) VSCode-Nightly: Update to version 1.88.0-insider_1710392702683

'main' bucket:
471486b0d (HEAD -> master, origin/master, origin/HEAD) oh-my-posh: Update to version 19.17.2

'nerd-fonts' bucket:
db6ccd1 (HEAD -> master, origin/master, origin/HEAD) LXGWNeoXiHei@1.120.1: Fix hash (Closes #280)

'nonportable' bucket:
25964b17 (HEAD -> master, origin/master, origin/HEAD) office-365-apps-minimal-np: Update to version 0.7.7.0

'okibcn_ScoopMaster' bucket:
f86fdde1b3 (HEAD -> master, origin/master, origin/HEAD) Update timestamp 2024-03-15T10:52:54Z

'versions' bucket:
749fc6345 (HEAD -> master, origin/master, origin/HEAD) zig-dev: Update to version 0.12.0-dev.3303
```

### Scoop Config

```console
scoop config

last_update                       alias                      scoop_branch scoop_repo
-----------                       -----                      ------------ ----------
2024-03-15T21:48:45.4486962+07:00 @{outdated=scoop-outdated} master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

Floorp

**Comment by kyan001** [comment]
The Scoop version of Floorp saves the persistent profile path in `Scoop/apps/floorp/Profiles/AppData/Floorp/profiles.ini`.

However, Scoop sees the `Scoop/apps/floorp/Profiles/` directory as an old version of Floorp, which will be removed when executing the `scoop cleanup *` command and prints `Removing floorp: Profiles` on the screen. Finally, on the next Floorp startup, a new `Scoop/apps/floorp/Profiles/` is created, and the profile data is reset.
