### ISSUE TITLE
[Request]: teracopy

### ISSUE THREAD

**Issue by NamelessUzer** [ScoopInstaller/Extras#12966]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

teracopy

### Description

With its array of features, TeraCopy stands as a renowned file transfer utility, meticulously crafted to enhance and streamline the process of copying and moving files.

### Homepage

https://www.codesector.com/

### Download Link(s)

https://www.codesector.com/files/teracopy.exe

### Some Indication of Popularity/Repute

TeraCopy is a [freemium](https://en.wikipedia.org/wiki/Freemium) [file transfer](https://en.wikipedia.org/wiki/File_transfer) utility designed as an alternative for the built-in [Windows Explorer](https://en.wikipedia.org/wiki/Windows_Explorer) file transfer feature. Its focus is data integrity, file transfer reliability and the ability to pause or resume file transfers.

**Comment by aliesbelik** [comment]
Duplicates #4800.
