### ISSUE TITLE
kate@23.08.4-2311: download via aria2 failed

### ISSUE THREAD

**Issue by aawadeus** [ScoopInstaller/Extras#13011]
Installing 'kate' (23.08.4-2311) [64bit] from extras bucket
Starting download with aria2 ...
Download: Download Results:                                                                                                                                                       z
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 4d8ddb|ERR |       0B/s|C:/Users/alexg/scoop/cache/kate#23.08.4-2311#https_binary-factory.kde.org_job_Kate_Release_win64_2311_artifact_kate-23.08.4-2311-windows-cl-msvc2019-x86_64.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 19) Name resolution failed
ERROR https://binary-factory.kde.org/job/Kate_Release_win64/2311/artifact/kate-23.08.4-2311-windows-cl-msvc2019-x86_64.7z
    referer=https://binary-factory.kde.org/job/Kate_Release_win64/2311/artifact/
    dir=C:\Users\alexg\scoop\cache
    out=kate#23.08.4-2311#https_binary-factory.kde.org_job_Kate_Release_win64_2311_artifact_kate-23.08.4-2311-windows-cl-msvc2019-x86_64.7z

ERROR & 'C:\Users\alexg\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\alexg\scoop\cache\kate.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=5652 --continue --summary-interval=0 --auto-save-interval=1

**Comment by aliesbelik** [comment]
Relates to #12897.

**Comment by aawadeus** [comment]
> Relates to #12897.

Thanks for the information o7
