### ISSUE TITLE
[Request]: MultiMC

### ISSUE THREAD

**Issue by vvirtues** [ScoopInstaller/Extras#13018]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [ ] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

MultiMC

### Description

A custom launcher for Minecraft that allows you to easily manage multiple installations of Minecraft at once

### Homepage

https://multimc.org

### Download Link(s)

https://files.multimc.org/downloads/mmc-develop-win32.zip

### Some Indication of Popularity/Repute

GitHub reviews and other reputable sites like https://download.fo

**Comment by vvirtues** [comment]
Downloads as a zip file, requries unzipping to use

**Comment by lwd-temp** [comment]
Calinou/scoop-games

**Comment by vvirtues** [comment]
oh bless
I thought there was an official one under the org's account but I didnt see it
