### ISSUE TITLE
[Request]: NotepadNext

### ISSUE THREAD

**Issue by daeho-ro** [ScoopInstaller/Extras#13025]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

notepad-next

### Description

A cross-platform, reimplementation of Notepad++.

### Homepage

https://github.com/dail8859/NotepadNext

### Download Link(s)

https://github.com/dail8859/NotepadNext/releases/tag/v0.7

### Some Indication of Popularity/Repute

github stars ~ 7.9k

**Comment by aliesbelik** [comment]
Already in Extras.
