### ISSUE TITLE
wezterm@20240203-110809-5046fc22: hash check failed

### ISSUE THREAD

**Issue by JoshBenn** [ScoopInstaller/Extras#13033]
Environment: 
- Windows 10 Pro Version 10.0.19045 Build 19045
- CPU: 9900k
- RAM: 32GB
- Running scoop through raised privileged powershell terminal
- Tons of space on SSD
- Other applications install fine via scoop

PS C:\Users\Kokurio\Desktop\Code\FableWorks\FableWorks-UI> scoop install wezterm
WARN  Purging previous failed installation of wezterm.
ERROR 'wezterm' isn't installed correctly.
Removing older version (20240203-110809-5046fc22).
'wezterm' was uninstalled.
Installing 'wezterm' (20240203-110809-5046fc22) [64bit] from extras bucket
WezTerm-windows-20240203-110809-5046fc22.zip (63.1 MB) [===========================================================================================] 100%
Checking hash of WezTerm-windows-20240203-110809-5046fc22.zip ... Get-FileHash : The file 'C:\Users\Kokurio\scoop\apps\wezterm\20240203-110809-5046fc22\WezTerm-windows-20240203-110809-5046fc22.zip' cannot be read:
Operation did not complete successfully because the file contains a virus or potentially unwanted software.
At C:\Users\Kokurio\scoop\apps\scoop\current\lib\install.ps1:674 char:16
+     $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T ...
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\Users\Kokuri...09-5046fc22.zip:PSObject) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FileReadError,Get-FileHash

You cannot call a method on a null-valued expression.
At C:\Users\Kokurio\scoop\apps\scoop\current\lib\install.ps1:674 char:5
+     $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Operation did not complete successfully because the file contains a virus or potentially unwanted software.
At C:\Users\Kokurio\scoop\apps\scoop\current\lib\core.ps1:1176 char:16
+         return Get-Content $file -Encoding byte -TotalCount 8
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\Users\Kokuri...09-5046fc22.zip:String) [Get-Content], IOException
    + FullyQualifiedErrorId : GetContentReaderIOError,Microsoft.PowerShell.Commands.GetContentCommand

ERROR Hash check failed!
App:         extras/wezterm
URL:         https://github.com/wez/wezterm/releases/download/20240203-110809-5046fc22/WezTerm-windows-20240203-110809-5046fc22.zip
First bytes:
Expected:    57e5d03b585303d81e8b8e96d1230362852eb39aca92b3b29c7a42cfb82f9ac4
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=wezterm%4020240203-110809-5046fc22%3a+hash+check+failed

**Comment by JoshBenn** [comment]
> Cannot reproduce
> 
> Are you sure your scoop is up to date? Clean cache and reinstall Please run `scoop update; scoop cache rm wezterm;` and update/reinstall application
> 
> Hash mismatch could be caused by these factors:
> 
>     * Network error
> 
>     * Antivirus configuration
> 
>     * Blocked site (Great Firewall of China, Corporate restrictions, ...)

![image](https://github.com/ScoopInstaller/Extras/assets/134667610/ee65b766-6fae-4592-b587-e2a26319371c)
- Network looks to be just fine
- I'm using windows defender if that's an issue
- AFAIK I'm not blocking anything to do with that site

**Comment by aliesbelik** [comment]
> Get-Content : Operation did not complete successfully because the file contains a virus or potentially unwanted software.

> I'm using windows defender if that's an issue.

Looks like your antivirus could block installation or quarantine downloaded binary in case of threat detection.
I see at least several issues concerning malware detections (possibly false positive) by Windows Defender reported for `wezterm@20240203-110809-5046fc22`:
 - wez/wezterm#5208,
 - wez/wezterm#5198,
 - wez/wezterm#5074.

Please ensure first that it's not your case.

**Comment by kalocsaibotond** [comment]
> > Get-Content : Operation did not complete successfully because the file contains a virus or potentially unwanted software.
> 
> > I'm using windows defender if that's an issue.
> 
> Looks like your antivirus could block installation or quarantine downloaded binary in case of threat detection. I see at least several issues concerning malware detections (possibly false positive) by Windows Defender reported for `wezterm@20240203-110809-5046fc22`:
> 
> * [Backdoor!!!!!!!!!!!! wez/wezterm#5208](https://github.com/wez/wezterm/issues/5208),
> * [Windows Defender detects C:\Program Files\WezTerm\strip-ansi-escapes.exe as malware wez/wezterm#5198](https://github.com/wez/wezterm/issues/5198),
> * [Winget installation flagged as a trojan by windows security wez/wezterm#5074](https://github.com/wez/wezterm/issues/5074).
> 
> ```
> λ scoop virustotal wezterm
> WARN  extras/wezterm: 23/63, see https://www.virustotal.com/gui/file/57e5d03b585303d81e8b8e96d1230362852eb39aca92b3b29c7a42cfb82f9ac4
> ```
> 
> Please ensure first that it's not your case.

Your assesment was proven correct.
After I excluded the Scop cache and wezterm library from the Windows Defender inspected directories via the following commands (that require admin rights)
```
Add-MpPreference -ExclusionPath "$HOME\scoop\cache"
Add-MpPreference -ExclusionPath "$HOME\scoop\apps\wezterm"
```
the installation went down as usual, and wezterm works as intended.

Thank you for your input!

I hope, I did not expoesed my system to malware threats with adding these two directories to be among the excluded.

**Comment by JoshBenn** [comment]
> > > Get-Content : Operation did not complete successfully because the file contains a virus or potentially unwanted software.
> > 
> > 
> > > I'm using windows defender if that's an issue.
> > 
> > 
> > Looks like your antivirus could block installation or quarantine downloaded binary in case of threat detection. I see at least several issues concerning malware detections (possibly false positive) by Windows Defender reported for `wezterm@20240203-110809-5046fc22`:
> > 
> > * [Backdoor!!!!!!!!!!!! wez/wezterm#5208](https://github.com/wez/wezterm/issues/5208),
> > * [Windows Defender detects C:\Program Files\WezTerm\strip-ansi-escapes.exe as malware wez/wezterm#5198](https://github.com/wez/wezterm/issues/5198),
> > * [Winget installation flagged as a trojan by windows security wez/wezterm#5074](https://github.com/wez/wezterm/issues/5074).
> > 
> > ```
> > λ scoop virustotal wezterm
> > WARN  extras/wezterm: 23/63, see https://www.virustotal.com/gui/file/57e5d03b585303d81e8b8e96d1230362852eb39aca92b3b29c7a42cfb82f9ac4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please ensure first that it's not your case.
> 
> Your assesment was proven correct. After I excluded the Scop cache and wezterm library from the Windows Defender inspected directories via the following commands (that require admin rights)
> 
> ```
> Add-MpPreference -ExclusionPath "$HOME\scoop\cache"
> Add-MpPreference -ExclusionPath "$HOME\scoop\apps\wezterm"
> ```
> 
> the installation went down as usual, and wezterm works as intended.
> 
> Thank you for your input!
> 
> I hope, I did not expoesed my system to malware threats with adding these two directories to be among the excluded.

This resolves it, but the concern is still there adding the entire directory -- I guess we'll have to just see what comes of it

**Comment by rogersanctus** [comment]
I am also having the same problem when trying to install this version in Windows with Windows Defender. I had followed the https://github.com/wez/wezterm/issues/3980 already and my AV signatures are updated. I am not going to just ignore the advices/alerts as they are being reported by another antivirus sofwares, as well.
What I am going to do, as a last effort, is to compile from source and see what happens.
