### ISSUE TITLE
[Bug] KDE applications are no longer hosted at "Binary-factory.kde.org" affecting Kate

### ISSUE THREAD

**Issue by danieljudd** [ScoopInstaller/Extras#13034]
#### Current Behavior
Kate (KDE's IDE software) is not fetching from the set URL anymore:
```bash
The remote name could not be resolved: 'binary-factory.kde.org'
URL https://binary-factory.kde.org/job/Kate_Release_win64/2311/artifact/kate-23.08.4-2311-windows-cl-msvc2019-x86_64.7z is not valid
```

#### Expected Behavior
Binaries should be fetched or built from: 
- https://cdn.kde.org/ci-builds/utilities/kate/master/windows/
- https://invent.kde.org/explore

??Other KDE+Windows binaries??:
https://community.kde.org/Windows

#### Additional context/output
URL moved permanently
Nightly version is similarly broken

#### Possible Solution
1. Hash done in SHA3-256??
2. Not sure how scoop pipeline is done but a new configuration might look like:
```json
{
    "version": "24.28.3-6832",
    "description": "Multi-document editor",
    "homepage": "https://kate-editor.org",
    "license": "LGPL-2.0-only",
    "notes": "If you want to get the latest development branch-based installer, please install `kate-nightly` from Versions bucket.",
    "architecture": {
        "64bit": {
            "url": "https://cdn.kde.org/ci-builds/utilities/kate/master/windows/kate-master-6832-windows-cl-msvc2022-x86_64.exe",
            "hash": "d02fbc4dc46281089f7c54337ca99e64c61f07ff425e6c36404b733c0afef11f"
        }
    },
    "bin": "bin\\kate.exe",
    "shortcuts": [
        [
            "bin\\kate.exe",
            "Kate"
        ]
    ],
    "checkver": {
        "url": "https://cdn.kde.org/ci-builds/utilities/kate/master/windows/",
        "regex": "kate-([\\d.-]+)-windows-cl-(?<lib>\\w+)-x86_64\\.7z"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://cdn.kde.org/ci-builds/utilities/kate/master/windows/kate-$version-windows-cl-$matchLib-x86_64.7z",
                "hash": {
                    "url": "$url.sha256"
                }
            }
        }
    }
}
```

### System details

**Windows version:** 10

**OS architecture:** Windows 64bit

**Comment by aliesbelik** [comment]
Relates to #12897.

There are currently no stable releases published after moving from binary-factory (compare with [kdenlive](https://cdn.kde.org/ci-builds/multimedia/kdenlive/), for example) and using versions built from `master` belongs rather to scoop's `Versions` bucket.

**Comment by danieljudd** [comment]
Ah okay I see my mistake @aliesbelik. 

Do you think this could lead to nightly builds being added to scoop as a patch, or is https://cdn.kde.org/ci-builds/ not recommended?

**Comment by aliesbelik** [comment]
Seems the first release after migration:
https://cdn.kde.org/ci-builds/utilities/kate/release-24.02/

...On Kate [download page](https://kate-editor.org/get-it/) I see that links for _nightly installers_ point to `master` directory, so IMO newly added builds correspond to scoop's buckets as following:

/ci-builds/utilities/kate/master/ - nightly builds for corresponding manifest in `Versions` bucket ([kate-nightly](https://github.com/ScoopInstaller/Versions/blob/master/bucket/kate-nightly.json));
/ci-builds/utilities/kate/release-xx.xx/ - stable builds for `Extras` bucket ([kate](https://github.com/ScoopInstaller/Extras/blob/master/bucket/kate.json)).

**Comment by hgkamath** [comment]
As of 20240404, a search of code in the Extras repo gives this list of apps with manifest files having binary-factory 
- [bucket/filelight.json](https://github.com/ScoopInstaller/Extras/blob/7d9c435bc3843a584c30e5dae02e6b9fe535d611/bucket/filelight.json) 
- [bucket/kate.json](https://github.com/ScoopInstaller/Extras/blob/7d9c435bc3843a584c30e5dae02e6b9fe535d611/bucket/kate.json) 
- [bucket/elisa.json](https://github.com/ScoopInstaller/Extras/blob/7d9c435bc3843a584c30e5dae02e6b9fe535d611/bucket/elisa.json) 
- [bucket/okular.json](https://github.com/ScoopInstaller/Extras/blob/7d9c435bc3843a584c30e5dae02e6b9fe535d611/bucket/okular.json) 
- [bucket/dolphin.json](https://github.com/ScoopInstaller/Extras/blob/7d9c435bc3843a584c30e5dae02e6b9fe535d611/bucket/dolphin.json) 

https://github.com/search?q=repo%3AScoopInstaller%2FExtras+binary-factory.kde.org&type=code

**Comment by aliesbelik** [comment]
@hgkamath, nightly versions updated in scope of ScoopInstaller/Versions#1662.
For `Extras` versions please track #12897 or raise PR if ready.

**Comment by 2xG** [comment]
I can see Okular windows release here https://cdn.kde.org/ci-builds/graphics/okular/release-23.08/windows/

**Comment by hgkamath** [comment]
likewize
- okular: https://cdn.kde.org/ci-builds/graphics/okular/master/windows/ 
- kate: https://cdn.kde.org/ci-builds/utilities/kate/master/windows/ 
- filelight: https://cdn.kde.org/ci-builds/utilities/filelight/master/windows/
- dolphin: https://cdn.kde.org/ci-builds/system/dolphin/master/windows/ 
- elisa: can't find yet
- labplot: https://cdn.kde.org/ci-builds/education/labplot/master/windows/
- kdenlive: https://cdn.kde.org/ci-builds/multimedia/kdenlive/master/windows/
- neochat: https://cdn.kde.org/ci-builds/network/neochat/master/windows/
- konversation: can't find yet

**Comment by aliesbelik** [comment]
Manifest for kate [updated](c7e7d5c), for the rest of KDE apps please track #12897.
