### ISSUE TITLE
[Bug]: tabby - Persisted data may be accidentally overwritten when updating

### ISSUE THREAD

**Issue by libenc** [ScoopInstaller/Extras#13030]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

tabby

### Expected/Current Behaviour

Currently, if the user has installed tabby _via official installer_ and started it at least once, the persisted configuration files of tabby which installed through scoop will be overwritten by the configs generated by the _official installation of tabby_ on each `scoop update tabby`. This will casuing a data loss in the scoop installation of tabby.

In detail, the `post_install` in [tabby's manifest](https://github.com/ScoopInstaller/Extras/blob/2d43bd474ac39fe0a14d2fe1f3509db624c15a00/bucket/tabby.json#L14) is used to migrate configs from the official installation:
```
            "post_install": [
                "if (Test-Path $env:APPDATA\\Tabby) {",
                "    Copy-Item -Path $env:APPDATA\\Tabby\\* -Destination \"$persist_dir\\data\" -Force -Recurse",
                "}"
            ]
```
Since `post_install` is also executed in every `scoop update tabby`, and `Copy-Item` has a `-Force` flag, any config files exist under `%APPDATA%\Tabby\` (which is the default data folder of tabby) will just overwrite the persisted data of scoop installation of tabby.

### Steps to Reproduce

```console
1. User install _tabby via official installer_ and started it at least once, so the configs is generated under `%APPDATA%\Tabby`.
2. User install tabby through scoop, `post_install` tries to copy configs under `%APPDATA%\Tabby\` to `$persist_dir\data\`.
3. Regardless of the _tabby installed via official installer_ is uninstalled or not, every `scoop update tabby` will causing the scoop persisted config files be overwritten by the configs under `%APPDATA%\Tabby\`.
```

### Possible Solution

Add logic to determine if tabby's configuration file already exists, and only perform the migration if tabby is freshly installed. 

I have completed the relevant fixes and ready to create the PR soon.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
2d43bd474 (HEAD -> master, origin/master, origin/HEAD) mpv-git: Update to version 20240331
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2024-03-31T10:10:00.1922110+08:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.4170
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.4170
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by aliesbelik** [comment]
Fixed by #13031.
