### ISSUE TITLE
[Bug]: WindTerm's file name is not same as the tag

### ISSUE THREAD

**Issue by skymkmk** [ScoopInstaller/Extras#13046]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

windterm

### Expected/Current Behaviour

404 Not Found

### Steps to Reproduce

```console
scoop install windterm
WARN  Purging previous failed installation of windterm.
ERROR 'windterm' isn't installed correctly.
Removing older version (2.6.0).
'windterm' was uninstalled.
Installing 'windterm' (2.6.0) [64bit] from extras bucket
远程服务器返回错误: (404) 未找到。
URL https://github.com/kingToolbox/WindTerm/releases/download/2.6.0/WindTerm_2.6.0_Windows_Portable_x86_64.zip is not valid
```

### Possible Solution

When I install this software, scoop notified me that the download link throwed a not found error. After investigating, I found that the file names provided on the WindTerm release page do not match the tags, which affects the automatic matching in the autoupdate section.

Here is a valid link:

https://github.com/kingToolbox/WindTerm/releases/download/2.6.0/WindTerm_2.6.1_Windows_Portable_x86_64.zip

However, the link given in the manifest is:

https://github.com/kingToolbox/WindTerm/releases/download/2.6.0/WindTerm_2.6.0_Windows_Portable_x86_64.zip

This is definitely an issue on WindTerm's side, but how should we resolve this issue now? I'm not familiar with the structure of scoop, so I don't know if it's robust to only modify the architecture without changing the autoupdate part, so I opened this issue in hopes of an official solution.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
d49a410c3 (HEAD -> master, origin/master, origin/HEAD) wavebox: Update to version 10.123.9.2
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2024-04-04T17:36:54.4070222+08:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by aliesbelik** [comment]
Thank you for reporting this.
Should be ok now.
