### ISSUE TITLE
wireshark@4.2.4: decompress error

### ISSUE THREAD

**Issue by Ryclock** [ScoopInstaller/Extras#13056]
## Terminal screenshot
<img width="574" alt="image" src="https://github.com/ScoopInstaller/Extras/assets/91328552/9144cae5-5c32-46a4-acff-20764867a269">

The [7zip.log](https://github.com/ScoopInstaller/Extras/files/14893156/7zip.log) mentioned above

## notes
4.2.3 decompress error issues is #12853

**Comment by aliesbelik** [comment]
#12359
