### ISSUE TITLE
[Request]: vipsdisp

### ISSUE THREAD

**Issue by o-l-a-v** [ScoopInstaller/Extras#13051]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

vipsdisp

### Description

Tiny libvips / gtk+4 image viewer

### Homepage

https://github.com/jcupitt/vipsdisp

### Download Link(s)

https://github.com/jcupitt/vipsdisp/releases

### Some Indication of Popularity/Repute

More than 100 stars on GitHub. 

It's on Flathub too:

* <https://flathub.org/apps/org.libvips.vipsdisp>

**Comment by aliesbelik** [comment]
> I started on a manifest but discovered the following that makes authoring it not as straight forward as I thought: Here's the dir hierarchy inside the downloaded zip ( https://github.com/jcupitt/vipsdisp/releases/download/v3.0.4/vipsdisp-3.0.4-w64.zip ):
> 
>     * `vipsdisp-3.0.4\bin\vipsdisp.exe`
> 
> 
> Where the first folder/dir name will be dynamic, changing each version. Right now I don't know how to solve that.
> 
> Manifest so far:
> Click to view

Use `extract_dir` (along with `url` and `hash`), both for download section and in `autoupdate`.
See e.g. [nodejs](https://github.com/ScoopInstaller/Main/blob/master/bucket/nodejs.json), [nginx](https://github.com/ScoopInstaller/Main/blob/master/bucket/nginx.json) manifests.
Remove the dynamic path from `shortcuts` as well.
