### ISSUE TITLE
filelight@23.08.4-1625: download via aria2 failed

### ISSUE THREAD

**Issue by aaronleo** [ScoopInstaller/Extras#13064]
ERROR Download failed! (Error 19) Name resolution failed
ERROR https://binary-factory.kde.org/job/Filelight_Release_win64/1625/artifact/filelight-23.08.4-1625-windows-cl-msvc2019-x86_64.7z
    referer=https://binary-factory.kde.org/job/Filelight_Release_win64/1625/artifact/
    dir=C:\Users\Aaron\scoop\cache
    out=filelight#23.08.4-1625#https_binary-factory.kde.org_job_Filelight_Release_win64_1625_artifact_filelight-23.08.4-1625-windows-cl-msvc2019-x86_64.7z

ERROR & 'C:\Users\Aaron\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Aaron\scoop\cache\filelight.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=29144 --continue --summary-interval=0 --auto-save-interval=1

**Comment by aliesbelik** [comment]
Relates to #12897.
