### ISSUE TITLE
[Request]: godots

### ISSUE THREAD

**Issue by shiena** [ScoopInstaller/Extras#13095]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

godots

### Description

Ultimate go-to hub for managing your Godot versions and projects! 

### Homepage

https://github.com/MakovWait/godots

### Download Link(s)

https://github.com/MakovWait/godots/releases

### Some Indication of Popularity/Repute

godots has 227 stars and 20 forks at the moment.

**Comment by aliesbelik** [comment]
Closed by #13026.
