### ISSUE TITLE
[Bug]: qbittorent download url is not valid anymore

### ISSUE THREAD

**Issue by Julpikar** [ScoopInstaller/Extras#13180]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

qbittorent

### Expected/Current Behaviour

install succed but now cannot

### Steps to Reproduce

```console
scoop install qbittorent
```

### Possible Solution

fix url from source

### Scoop and Buckets Version

```console
scoop --version
Current Scoop version:
105e4161 (HEAD -> master, tag: v0.4.0, origin/master, origin/HEAD) chore(release): Bump to version 0.4.0 (#5424)

'main' bucket:
3232f6eb8 (HEAD -> master, origin/master, origin/HEAD) memcached: Update to version 1.6.26

'extras' bucket:
ee042680b (HEAD -> master, origin/master, origin/HEAD) wavebox: Update to version 10.124.17.2

'versions' bucket:
a89c3f014 (HEAD -> master, origin/master, origin/HEAD) zig-dev: Update to version 0.13.0-dev.40
```

### Scoop Config

```console
s
```

### PowerShell Version

```console
s
```

**Comment by SegoCode** [comment]
>scoop install qbittorent

You are trying to install a manifest that does not exist
The https://github.com/ScoopInstaller/Extras/blob/master/bucket/qbittorrent.json works fine 

Try run:
```
scoop install extras/qbittorrent
```
