### ISSUE TITLE
[Request]: Gitu

### ISSUE THREAD

**Issue by nightscape** [ScoopInstaller/Extras#13195]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

gitu

### Description

A TUI Git client inspired by Magit

### Homepage

https://github.com/altsem/gitu

### Download Link(s)

https://github.com/altsem/gitu/releases/download/v0.19.2/gitu-v0.19.2-x86_64-pc-windows-msvc.zip

### Some Indication of Popularity/Repute

1500 ⭐ 
82 forks

**Comment by nightscape** [comment]
Added in https://github.com/ScoopInstaller/Extras/pull/13175

**Comment by aliesbelik** [comment]
Looks like it could be promoted into `Main` since completely fits [criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket).

**Comment by nightscape** [comment]
It only has 82 forks instead of 150. Not sure how important that is?

**Comment by aliesbelik** [comment]
You are right, my mistake.
Еhen leaving it in Extras.
