### ISSUE TITLE
[Bug]: sqlitebrowser 3.12.2 failes to install

### ISSUE THREAD

**Issue by crohan-99** [ScoopInstaller/Extras#13255]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

sqlitebrowser

### Expected/Current Behaviour

Scoop cannot seem to install sqlitebrowser. It downloads the archive from the repo, but 7-Zip does not find any files inside to extract.

### Steps to Reproduce

```console
PS> scoop install sqlitebrowser
Installing 'sqlitebrowser' (3.12.2) [64bit] from 'extras' bucket
Loading DB.Browser.for.SQLite-3.12.2-win64.zip from cache
Checking hash of DB.Browser.for.SQLite-3.12.2-win64.zip ... ok.
Extracting DB.Browser.for.SQLite-3.12.2-win64.zip ... Could not find 'DB Browser for SQLite'! (error 16)
At C:\Users\user\scoop\apps\scoop\current\lib\core.ps1:860 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...te'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'DB Browser for SQLite'! (error 16)
```

### Possible Solution

7-Zip seems to not be able to find any files inside the archive. The 7-Zip log is as follows:

7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20

Scanning the drive for archives:
1 file, 20446868 bytes (20 MiB)

Extracting archive: C:\Users\user\scoop\apps\sqlitebrowser\3.12.2\DB.Browser.for.SQLite-3.12.2-win64.zip
\--
Path = C:\Users\user\scoop\apps\sqlitebrowser\3.12.2\DB.Browser.for.SQLite-3.12.2-win64.zip
Type = zip
Physical Size = 20446868

No files to process
Everything is Ok

Files: 0
Size:       0
Compressed: 20446868

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
d285bb08 (HEAD -> master, tag: v0.4.1, origin/master, origin/HEAD) chore(release): Bump to version 0.4.1 (#5924)

'main' bucket:
99baa6cea (HEAD -> master, origin/master, origin/HEAD) nodejs@22.1.0: Fix hash (Closes #5809)

'extras' bucket:
99b90d231 (HEAD -> master, origin/master, origin/HEAD) github@3.3.15: Fix hash (Closes #13254)

'aoisummer' bucket:
cf0c18d (HEAD -> master, origin/master, origin/HEAD) update bucket

'foosel' bucket:
393d557 (HEAD -> main, origin/main, origin/HEAD) freecad-weekly: Update to version 36391

'scoop-bucket' bucket:
04d891e (HEAD -> master, origin/master, origin/HEAD) Release v0.23.0

'wsl' bucket:
9689ba6 (HEAD -> master, origin/master, origin/HEAD) resolves issue #4
```

### Scoop Config

```console
PS> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2024-05-08T10:27:18.9962082-05:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by amreus** [comment]
I believe this is a bug in Scoop itself rather than a bug with the manifest. 

Possibly because `$ExtractDir` contains spaces? (file `lib\decompress.ps1` line 35)

https://github.com/ScoopInstaller/Scoop/blob/d285bb08d4852e0a7d524387fee53aa47c7b2a99/lib/decompress.ps1#L35

**Comment by amreus** [comment]
This issue may be related: #13221

**Comment by amreus** [comment]
This is already being addressed here: https://github.com/ScoopInstaller/Scoop/pull/5945
