### ISSUE TITLE
[Bug]: KeePassXC us missing a dependency

### ISSUE THREAD

**Issue by lapo-luchini** [ScoopInstaller/Extras#13253]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

keepassxc

### Expected/Current Behaviour

Running correctly.

### Steps to Reproduce

```console
PS> scoop install keepassxc
try to open KeePassXC
a popup appears saying that `MSVCP140_1.dll` is missing.
```

### Possible Solution

Add a dependency on `vcredist` scoop package.

### Scoop and Buckets Version

```console
v0.4.1
```

### Scoop Config

```console
(default)
```

### PowerShell Version

```console
5.1.22621.2506
```

**Comment by aliesbelik** [comment]
Already added as suggested in #13038.
