### ISSUE TITLE
[postman] checkver has been updated

### ISSUE THREAD

**Issue by anmoti** [ScoopInstaller/Extras#13304]
I can't update to v11 because postman's checkver has changed.
I don't understand the scoop manifest, so I'd like someone to do it for me.

https://dl.pstmn.io/changelog?channel=stable&platform=win64
↓
https://dl.pstmn.io/update/status?channel=stable&currentVersion=10.24.16&platform=win64

**Comment by amreus** [comment]
The version of `postman` in the Extras repo appears to be the latest version: `11.1.0`

https://github.com/ScoopInstaller/Extras/blob/master/bucket/postman.json

Does this solve your issue? If so, please <kbd>close</kbd>
