### ISSUE TITLE
qtemu@2.1: hash check failed

### ISSUE THREAD

**Issue by frn1** [ScoopInstaller/Extras#13316]
```
ERROR Hash check failed!
App:         extras/qtemu
URL:         https://web.archive.org/web/20210417194244/https://carlavilla.es/qtemu/qtemu_portable_x86_64.zip
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    4e6c744b580753a536b8cdc2213856da8e270584de419977144a5413e73a53e8
Actual:      a561982d643044b3b81378885b31217d224fe438ab87587964a47dedb18afae5
```

**Comment by frn1** [comment]
Uhhhhhhhhhhhhhhhhhhhhhhhhh
I dont know why but the hash changed again??????????????????????????????
```
ERROR Hash check failed!
App:         extras/qtemu
URL:         https://web.archive.org/web/20210417194244/https://carlavilla.es/qtemu/qtemu_portable_x86_64.zip
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    000eecb3d04bac9be726048f99793145260da9f3a01765cf52ff55eb64521301
Actual:      c4ab08af8d02e85f1558524a8114f233b772752695a116f373f0ebf1024f306b
```

**Comment by aliesbelik** [comment]
> Uhhhhhhhhhhhhhhhhhhhhhhhhh I dont know why but the hash changed again?????????????????????????????? Maybe there might be extra data being added into the file
> 
> ```
> ERROR Hash check failed!
> App:         extras/qtemu
> URL:         https://web.archive.org/web/20210417194244/https://carlavilla.es/qtemu/qtemu_portable_x86_64.zip
> First bytes: 3C 21 44 4F 43 54 59 50
> Expected:    000eecb3d04bac9be726048f99793145260da9f3a01765cf52ff55eb64521301
> Actual:      c4ab08af8d02e85f1558524a8114f233b772752695a116f373f0ebf1024f306b
> ```

#12574
