### ISSUE TITLE
[Request]: Kando

### ISSUE THREAD

**Issue by sbstn87** [ScoopInstaller/Extras#13365]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Kando

### Description

Kando is a highly customizable pie menu for the desktop which allows you to create your own menus and actions. For instance, you can use it to control your music player, to open your favorite websites, or to simulate shortcuts. It is available for Windows, Linux and macOS.

### Homepage

https://github.com/kando-menu/kando

### Download Link(s)

https://github.com/kando-menu/kando/releases

### Some Indication of Popularity/Repute

https://alternativeto.net/software/kando-1/about/

900 stars on GitHub

**Comment by Akasiek** [comment]
Working on it 😉

**Comment by archtur** [comment]
There is already V1.2.0 - https://github.com/kando-menu/kando/releases
