### ISSUE TITLE
[Request]: RustRover

### ISSUE THREAD

**Issue by chenyitian** [ScoopInstaller/Extras#13372]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [x] Full version (i.e. not a trial version)
- [x] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

RustRover

### Description

A powerhouse IDE for Rust developers

### Homepage

https://www.jetbrains.com/rust/

### Download Link(s)

https://data.services.jetbrains.com/products/releases?code=RR&latest=true&platform=zip&type=release

### Some Indication of Popularity/Repute

jetbrains family and free for individual, non-commercial use

**Comment by jamesWalker55** [comment]
Looking at https://data.services.jetbrains.com/products/releases?code=RR&latest=true&platform=zip&type=release, it seems JetBrains doesn't offer portable ZIP versions of RustRover (as opposed to CLion which does have ZIP versions https://data.services.jetbrains.com/products/releases?code=CL&latest=true&platform=zip&type=release)

**Comment by xyalter** [comment]
I have submitted a pull request and am waiting for the results.
