### ISSUE TITLE
[Request]: PicView

### ISSUE THREAD

**Issue by Ruben2776** [ScoopInstaller/Extras#13388]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

PicView

### Description

Fast, free and customizable image viewer for Windows 10 and 11. 

### Homepage

https://picview.org/

### Download Link(s)

https://github.com/Ruben2776/PicView/releases/download/2.2.7/PicView-v.2.2.7-win-x64.zip https://github.com/Ruben2776/PicView/releases/download/2.2.7/PicView-v.2.2.7-win-arm64.zip

### Some Indication of Popularity/Repute

PicView as of writing has more than 900 stars on GitHub and has several download mirrors such as 
[FossHub](https://www.fosshub.com/PicView.html)
[MajorGeeks](https://www.majorgeeks.com/files/details/picview.html)
[SourceForge](https://sourceforge.net/projects/picview/)
[uptodown](https://picview.en.uptodown.com/windows)

The package links the portable version

**Comment by aliesbelik** [comment]
Closed by #13389.
