### ISSUE TITLE
[Request]: Parsec Portable

### ISSUE THREAD

**Issue by SunsetMkt** [ScoopInstaller/Extras#13414]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Parsec

### Description

Remote Gaming

### Homepage

https://parsec.app/

### Download Link(s)

https://builds.parsec.app/package/parsec-flat-windows.zip

### Some Indication of Popularity/Repute

https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/parsec-np.json

**Comment by lwd-temp** [comment]
https://github.com/ScoopInstaller/Extras/pull/13411
