### ISSUE TITLE
[Bug]: inno-setup@6.3.1: decompress error

### ISSUE THREAD

**Issue by msuesskraut** [ScoopInstaller/Extras#13444]
`scoop update inno-setup` fails for inno-setup 6.3.0 and 6.3.1 (see below for newer version):

```
Extracting innosetup-6.3.0.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\Martin\scoop\apps\inno-setup\6.3.0\innosetup-6.3.0.exe.
```

Content of log file `~\scoop\apps\inno-setup\6.3.0\innounp.log`

```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

**Comment by msuesskraut** [comment]
The same happens for inno-setup@6.3.1.

The logfile:
```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

**Comment by c-s-w** [comment]
A new version of [innounp](https://innounp.sourceforge.net/) would be required, which supports the latest data format.

**Comment by xoriath** [comment]
https://sourceforge.net/p/innounp/discussion/353235/thread/ef0e2c5c41/

**Comment by hgkamath** [comment]
- ```innounp``` hasn't been updated since 202212
  - Do you think it has been abandoned ?
  - If so then what ? 
-  There s a GUI tool _Windows InnoUnpacker 1.9.2_ 
    - is made by Jürgen Rathlev, is author of https://www.rathlev-home.de/index-e.html?home-e.html#unpack
    - has a patched fork/build of innounp to handle unicode
      - called innounp-16x
      - source/binary on website 
        - https://www.rathlev-home.de/tools/download/innounp16x.zip
        - https://www.rathlev-home.de/sources/download/d10/innounp16xsrc.zip
- innosetup  
  - is made by Jordan Russel
  - has a BSD like attribution and disclaimer license
  - https://jrsoftware.org/isdl.php
  - has a administrative install that unpacks to user profile directory but also modifies registry keys.

**Comment by MMKubicki** [comment]
As seen in [Scoop v0.5.0](https://github.com/ScoopInstaller/Scoop/releases/tag/v0.5.0):

> ### Features
> [...]
>  - decompress: Use innounp-unicode as default Inno Setup Unpacker (https://github.com/ScoopInstaller/Scoop/pull/6028)

Uninstall `innounp` etc. and install `innounp-unicode`
