### ISSUE TITLE
mattermost@5.8.1: download via aria2 failed

### ISSUE THREAD

**Issue by fschoenm** [ScoopInstaller/Extras#13462]
Updating 'mattermost' (5.8.0 -> 5.8.1)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 5492cb|ERR |       0B/s|C:/Users/scf5nu3/scoop/cache/mattermost#5.8.1#https_releases.mattermost.com_desktop_5.8.1_mattermost-desktop-5.8.1-win64.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://releases.mattermost.com/desktop/5.8.1/mattermost-desktop-5.8.1-win64.zip
    referer=https://releases.mattermost.com/desktop/5.8.1/
    dir=C:\Users\scf5nu3\scoop\cache
    out=mattermost#5.8.1#https_releases.mattermost.com_desktop_5.8.1_mattermost-desktop-5.8.1-win64.zip

ERROR & 'C:\Users\scf5nu3\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\scf5nu3\scoop\cache\mattermost.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=26032 --continue --summary-interval=0 --auto-save-interval=1 --all-proxy='localhost:3128'

**Comment by aliesbelik** [comment]
Seems to relate to mattermost/desktop#3069.
