### ISSUE TITLE
saber@0.23.3: Decompress error

### ISSUE THREAD

**Issue by r3tr0g4m3r** [ScoopInstaller/Extras#13477]
Failed to extract files from C:\Users\retrogamer\scoop\apps\saber\0.23.3\SaberInstaller_v0.23.3.exe.
Log file:
  ~\scoop\apps\saber\0.23.3\innounp.log

Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by xoriath** [comment]
Pending fix in innounp I'd guess: https://sourceforge.net/p/innounp/discussion/353235/thread/ef0e2c5c41/

**Comment by xoriath** [comment]
See #13444

**Comment by aliesbelik** [comment]
With [Scoop v0.5.0](https://github.com/ScoopInstaller/Scoop/releases/tag/v0.5.0):
```
scoop uninstall innounp
scoop bucket add versions
scoop install versions/innounp-unicode
```
as a temporary workaround.
