### ISSUE TITLE
librewolf: Remove unnecessary updates files

### ISSUE THREAD

**Issue by SegoCode** [ScoopInstaller/Extras#13516]
Hello,

Currently, the LibreWolf package disables auto-update... so while navigating through its container folder, I noticed that there are two .ps1 files: `ScheduledTask-Create.ps1` and `ScheduledTask-Remove.ps1` initially, I thought they are from Scoop...

```
25/06/2024  14:09    <DIR>          .
25/06/2024  14:09    <DIR>          ..
25/06/2024  14:09                60 install.json
18/05/2024  15:19    <DIR>          LibreWolf
25/04/2024  01:28           913.408 LibreWolf-Portable.exe
21/05/2024  09:55             3.040 manifest.json
25/06/2024  14:09    <JUNCTION>     Profiles [\??\C:\Users\SegoCode\scoop\persist\librewolf\Profiles]
19/10/2023  22:33             1.506 ScheduledTask-Create.ps1
30/09/2023  21:55               795 ScheduledTask-Remove.ps1
```
For my surprise, weren't from Scoop, they were from the LibreWolf download itself...

Currently, the manifest removes a file `LibreWolf-WinUpdater.exe`, and these .ps1 files remain as residue. To avoid confusion and reduce the package size, I propose adding the following to the manifest:

```
 "Remove-Item \"$dir\\ScheduledTask-Create.ps1\"",
 "Remove-Item \"$dir\\ScheduledTask-Remove.ps1\"",
```

https://github.com/ScoopInstaller/Extras/blob/master/bucket/librewolf.json#L18

**Comment by aliesbelik** [comment]
Hm, looks like was already done in #10958 but later rewritten for some reason by #11052.

**Comment by SegoCode** [comment]
So, I've seen it, kinda weird... those ps1 scheduledTask files depend on the deleted update executable and I haven't seen any dependency from them by the main run binary. I did a test on a fresh install of Windows 11 and the installation works perfectly without those scheduledTask ps1 files 🤷‍♂️ 

![2024-06-26_09-53](https://github.com/ScoopInstaller/Extras/assets/35817798/a27df1fc-6401-4939-ab2a-e30abd7ff2f7)

Maybe have been added again by accident...
