### ISSUE TITLE
appflowy@0.6.1: decompress error

### ISSUE THREAD

**Issue by myAlterX** [ScoopInstaller/Extras#13518]
The log from: scoop\apps\appflowy\0.6.1\innounp.log

Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by myAlterX** [comment]
However hash is valid:

Checking hash of AppFlowy-0.6.1-windows-x86_64.exe ... ok.
Extracting AppFlowy-0.6.1-windows-x86_64.exe ... ERROR Exit code was 1!

**Comment by aliesbelik** [comment]
Duplicates #13487.
