### ISSUE TITLE
whatsapp@2.2326.10: download via aria2 failed

### ISSUE THREAD

**Issue by the7day** [ScoopInstaller/Extras#13528]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://web.whatsapp.com/desktop/windows/release/x64/WhatsApp-2.2326.10-full.nupkg#/dl.7z
    referer=https://web.whatsapp.com/desktop/windows/release/x64/WhatsApp-2.2326.10-full.nupkg#/
    dir=D:\software\Scoop\cache
    out=whatsapp#2.2326.10#https_web.whatsapp.com_desktop_windows_release_x64_WhatsApp-2.2326.10-full.nupkg_dl.7z

ERROR & 'D:\software\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\software\Scoop\cache\whatsapp.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=23712 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=whatsapp%402.2326.10%3a+download+via+aria2+failed

**Comment by aliesbelik** [comment]
Duplicates #13310.
