### ISSUE TITLE
Wezterm get flag as a virus

### ISSUE THREAD

**Issue by g-berthiaume** [ScoopInstaller/Extras#13524]
When downloading Wezterm, it gets flagged as a virus.
![image](https://github.com/ScoopInstaller/Extras/assets/19377511/5646ba5c-b399-4d7f-8c52-37d701f88cbd)

**Comment by aliesbelik** [comment]
Guess this relates more to wezterm than to scoop itself: wez/wezterm#5746.
Duplicates e.g. #13033.

**Comment by g-berthiaume** [comment]
Thanks. My apology for the duplication.
