### ISSUE TITLE
appflowy@0.6.2: decompress error

### ISSUE THREAD

**Issue by ancion** [ScoopInstaller/Extras#13556]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'appflowy' (0.6.2) [64bit] from 'extras' bucket
Starting download with aria2 ...
Download: [#4ee7ac 3.4MiB/31MiB(10%) CN:4 DL:152KiB ETA:3m10s]                               Download: 07/02 21:38:55 [ERROR] CUID#11 - Download aborted. URI=https://github.com/AppFlowy-Download: Exception: [AbstractCommand.cc:351] errorCode=24 URI=https://objects.githubusercontent.com/github-production-release-asset-2e65be/377496562/e555d6f9-2be7-4d48-8473-80c754e91ab4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240702%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240702T132930Z&X-Amz-Expires=300&X-Amz-Signature=b6d4efd31e45bdd92ab8416c1e7a3407e49539d221f69e1d06b58201fcdc46c0&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=377496562&response-content-disposition=attachment%3B%20filename%3DAppFlowy-Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 4ee7ac|OK  |    39KiB/s|D:/Scoop/cache/appflowy#0.6.2#https_github.com_AppFlowy-IO_AppFlowy_releases_download_0.6.2_AppFlowy-0.6.2-windows-x86_64.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of AppFlowy-0.6.2-windows-x86_64.exe ... ok.
Extracting AppFlowy-0.6.2-windows-x86_64.exe ... ERROR Exit code was 1!
Failed to extract files from D:\Scoop\apps\appflowy\0.6.2\AppFlowy-0.6.2-windows-x86_64.exe.
Log file:
  D:\Scoop\apps\appflowy\0.6.2\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=appflowy%400.6.2%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #13487.
