### ISSUE TITLE
inno-setup@6.3.2: decompress error

### ISSUE THREAD

**Issue by Roadrunner67** [ScoopInstaller/Extras#13583]
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by niheaven** [comment]
Install `innounp-unicode` and try again.

`scoop install versions/innounp-unicode`
