### ISSUE TITLE
[Request]: godu

### ISSUE THREAD

**Issue by koffydrop** [ScoopInstaller/Extras#13587]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

godu

### Description

Simple golang utility helping to discover large files/folders.

### Homepage

https://github.com/viktomas/godu

### Download Link(s)

https://github.com/viktomas/godu/releases/latest

### Some Indication of Popularity/Repute

[519 Stars on github](https://github.com/viktomas/godu/stargazers)

**Comment by koffydrop** [comment]
I've created and tested a manifest for it on my personal repo and figured why not try adding it here?

- Autoupdate and checkver both work
- Installs, uninstalls and runs seemingly without issue
- Single portable executable install

Waiting for maintainer approval before opening a PR

**Comment by aliesbelik** [comment]
As a non-GUI tool could be submitted into the `main` bucket instead, since meeting the [Main criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket).

Seems that ready-to-use manifest is already available in several personal buckets:
https://scoop.sh/#/apps?q=godu
