### ISSUE TITLE
windjview@2.1: hash check failed - The real issue is that windows defender finds a virus in the download

### ISSUE THREAD

**Issue by chhh** [ScoopInstaller/Extras#13601]
From windows defender:
```
PUA:Win32/Vigua.A
file: C:\Users\...\scoop\apps\windjview\2.1\dl.7z
file: C:\Users\...\scoop\cache\windjview#2.1#afc576c.7z.download
```

![image](https://github.com/user-attachments/assets/71006364-61ab-4c8f-bb08-b06f5c9b1ac8)

**Comment by sfunx** [comment]
Me too: fresh install, updated scoop; windjview intsallation package indeed contains malware.
![image](https://github.com/user-attachments/assets/8cae2229-260c-44f5-90a0-d168c5cebfe3)
![image](https://github.com/user-attachments/assets/1aa13be0-62aa-4f0f-8f8b-be98f41d088a)

**Comment by sfunx** [comment]
Please, consider reopening
