### ISSUE TITLE
lenovolegiontoolkit@2.23.0: decompress error

### ISSUE THREAD

**Issue by yachen4ever** [ScoopInstaller/Extras#13617]
Installing 'lenovolegiontoolkit' (2.23.0) [64bit] from 'extras' bucket
Loading LenovoLegionToolkitSetup.exe from cache
Extracting LenovoLegionToolkitSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\YaCHEN\scoop\apps\lenovolegiontoolkit\2.23.0\LenovoLegionToolkitSetup.exe.
Log file:
  ~\scoop\apps\lenovolegiontoolkit\2.23.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=lenovolegiontoolkit%402.23.0%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates ScoopInstaller/Extras#13547.
