### ISSUE TITLE
clash-verge-rev@1.7.5: download via aria2 failed

### ISSUE THREAD

**Issue by sparkslyz** [ScoopInstaller/Extras#13628]
Updating 'clash-verge-rev' (1.7.3 -> 1.7.5)
Downloading new version
Starting download with aria2 ...
Download: 07/16 19:58:02 [ERROR] CUID#8 - Download aborted. URI=https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v1.7.5/Clash.Verge_1.7.5_x64_portabDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v1.7.5/Clash.Verge_1.7.5_x64_portableDownload: Download Results:                                               ound
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: d3e823|ERR |       0B/s|E:/Application/Scoop/cache/clash-verge-rev#1.7.5#56ecd57.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v1.7.5/Clash.Verge_1.7.5_x64_portable.zip
    referer=https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v1.7.5/
    dir=E:\Application\Scoop\cache
    out=clash-verge-rev#1.7.5#56ecd57.zip

ERROR & 'E:\Application\Scoop\apps\aria2\current\aria2c.exe' --input-file='E:\Application\Scoop\cache\clash-verge-rev.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=19708 --continue --summary-interval=0 --auto-save-interval=1

**Comment by aliesbelik** [comment]
Please update and re-check.
Seems assets for v1.7.5 were re-uploaded after release, hashes updated by #13631.
