### ISSUE TITLE
[Bug]: thunderbird checkver needs update

### ISSUE THREAD

**Issue by hgkamath** [ScoopInstaller/Extras#13633]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

thunderbird

### Expected/Current Behaviour

I think the `checkver` section of the json manifest is not working 
Hence, the manifest file has a old version. 
Thunderbird 128 was launched on 20240712 (about 4 days ago)  
https://blog.thunderbird.net/2024/07/welcome-to-thunderbird-128-nebula/   

- currently the manifest points to `https://www.thunderbird.net/thunderbird/all/` 
  - which redirects to https://www.thunderbird.net/en-US/thunderbird/all/
- The old page is [https://web.archive.org/web/20240413053246/https://www.thunderbird.net/en-US/thunderbird/all/](https://web.archive.org/web/20240413053246/https://www.thunderbird.net/en-US/thunderbird/all/)
- The website change and redirection may have happened in the last few months
  - See [https://web.archive.org/web/20240000000000*/https://www.thunderbird.net/thunderbird/all/](https://web.archive.org/web/20240000000000*/https://www.thunderbird.net/thunderbird/all/) . It shows that the url captures slowly changed around march from a blue circled captures to a green circled redirects. 
  - This might be why the update is not working 

### Steps to Reproduce

```console
PS C:\> scoop search thunderbird
Results from local buckets...

Name        Version  Source Binaries
----        -------  ------ --------
thunderbird 115.12.2 extras
```

### Possible Solution

- Figure out how to correctly determine presently released version for the present state of website/webpage.   
- Alternatively, request thunderbird.net to make the old listing of downloads available on a different url.  
  - but thunderbird.net may additionally have to restart updating these pages, as they may have stopped updating them
    - for ex : [https://www.thunderbird.net/en-US/thunderbird/releases/](https://www.thunderbird.net/en-US/thunderbird/releases/) no longer has releases after 115

In the archived releases directory [https://archive.mozilla.org/pub/thunderbird/releases/](https://archive.mozilla.org/pub/thunderbird/releases/) one can see the directory for ```128.0esr``` but not ```128.0```. Usually, a esr release directory is side by side the regular release. This may be another subproblem to iron out.  

### Scoop and Buckets Version

```console
PS C:\> scoop --version
Current Scoop version:
716b6db3 (HEAD -> master, tag: v0.5.0, origin/master, origin/HEAD) chore(release): Bump to version 0.5.0 (#6035)

'main' bucket:
6e21ddc52 (HEAD -> master, origin/master, origin/HEAD) nunit-extension-nunit-v2-result-writer: Update to version 3.8.0

'extras' bucket:
108512116 (HEAD -> master, origin/master, origin/HEAD) clash-verge-rev@1.7.5: Fix hash (Closes #13631)

'versions' bucket:
09b48d6c4 (HEAD -> master, origin/master, origin/HEAD) zig-dev: Update to version 0.14.0-dev.321

'java' bucket:
fdb41b89 (HEAD -> master, origin/master, origin/HEAD) temurin17-nightly-jre: Update to version 17.0.12-6.0.ea
```

### Scoop Config

```console
PS C:\> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2024-07-16T19:58:17.6625676+05:30 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\> echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.3880
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.3880
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by aliesbelik** [comment]
Looks like https://product-details.mozilla.org/1.0/thunderbird_versions.json could be an option:

```
"checkver": {
    "url": "https://product-details.mozilla.org/1.0/thunderbird_versions.json",
    "jsonpath": "$.LATEST_THUNDERBIRD_VERSION"
},
``` 

However 115.x (115.13.0 at the moment) still pointed as latest stable version.

ESR versions, I guess, could be tracked as separate manifest here in `Extras` bucket, all the other (alpha/beta, dev, nightly) - in `Versions`.

**Comment by aliesbelik** [comment]
ESR version added as a separate manifest (`extras/thunderbird-esr`).
