### ISSUE TITLE
[Bug]: obsidian not update

### ISSUE THREAD

**Issue by guzzhao** [ScoopInstaller/Extras#13643]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

obsidian

### Expected/Current Behaviour

Results from local buckets...

obsidian 1.6.3   extras

the latest version is 1.6.5

https://github.com/obsidianmd/obsidian-releases/releases

### Steps to Reproduce

```console
no
```

### Possible Solution

no

### Scoop and Buckets Version

```console
no
```

### Scoop Config

```console
no
```

### PowerShell Version

```console
no
```

**Comment by aliesbelik** [comment]
Unified installer used for 64bit/32bit/arm64 versions [since v1.6.5](https://obsidian.md/changelog/2024-06-25-desktop-v1.6.5/).
