### ISSUE TITLE
mpv@0.38.0: decompress error

### ISSUE THREAD

**Issue by CalvinMbaula** [ScoopInstaller/Extras#13648]
Extracting mpv-0.38.0-x86_64.7z ... ERROR Exit code was 259!
Failed to extract files from C:\Users\Calvin\scoop\apps\mpv\0.38.0\mpv-0.38.0-x86_64.7z.
Log file:
  ~\scoop\apps\mpv\0.38.0\7zip.log

**Comment by rhaishiun009** [comment]
I have same problem, is there any fix?

**Comment by aliesbelik** [comment]
May relate to mpv-player/mpv#13950.

Depending on the antivirus software you are using and its settings it could block installation or quarantine binary in case of threat detection.
Ensure first that it's not your case: re-check with the latest version and check that downloaded binary wasn't removed/quarantined.

**Comment by rhaishiun009** [comment]
thanks for the reply but so far, anti-virus is disabled.
