### ISSUE TITLE
[Request]: RimSort

### ISSUE THREAD

**Issue by Raizanad** [ScoopInstaller/Extras#13657]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

RimSort

### Description

A mod manager and updater for RimWorld.

### Homepage

https://github.com/RimSort/RimSort

### Download Link(s)

https://github.com/RimSort/RimSort/releases/tag/v1.0.8

### Some Indication of Popularity/Repute

Hello, making a request for RimSort to be added to scoop extras.
It is a mod manager for a game named RimWorld. It does fulfill the requirements of the bucket (i.e. over 200 stars).

```
{
    "version": "1.0.8",
    "description": "Mod manager for RimWorld",
    "homepage": "https://github.com/RimSort/RimSort",
    "license": "GPL-3.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/RimSort/RimSort/releases/download/v1.0.8/RimSort-v1.0.8-Windows_x86_64.zip",
            "hash": "935c021bcc26f5156a8f6d69a6e95de7c9bc463e788d337887b85792202659f2"
        },
        "32bit": {
            "url": "https://github.com/RimSort/RimSort/releases/download/v1.0.8/RimSort-v1.0.8-Windows_x86_64.zip",
            "hash": "935c021bcc26f5156a8f6d69a6e95de7c9bc463e788d337887b85792202659f2"
        }
    },
    "shortcuts": [
        [
            "RimSort/RimSort.exe",
            "RimSort"
        ]
    ],
    "persist": [
        "User Files"
    ],
    "checkver": {
        "github": "https://github.com/RimSort/RimSort"
    },
    "autoupdate": {
        "url": "https://github.com/RimSort/RimSort/releases/download/v$version/RimSort-v$version-Windows_x86_64.zip"
    }
}
```

I made this by reading the wiki on scoop. It may contain errors that need polishing.
For example:
Currently it is not following the usual scoop installation protocol where you have a version then the installation folder proper. To better explain, it installs the app as:
Scoop/Apps/RimSort/1.0.8/RimSort/RimSort.exe
Instead of
Scoop/Apps/RimSort/1.0.8/RimSort.exe

The releases themselves on the rimsort page are actually portable installations.

On the other hand, scoop rm RimSort won't do a complete cleanup since the userfiles and config from RimSort are installed in AppData/Local/ which is desirable so RimSort user setting persist but may be annoying from Scoop perspective. So I created a persist but I don't know if on the scoop side it can be used or I have to make a request at the rimsort side.

Can you recommend me a bucket where I can make a request for help putting together a pre-release version manifest? They are very active so I find it useful and desirable.

**Comment by Raizanad** [comment]
The above snippet is tested working on my scoop installation.

**Comment by aliesbelik** [comment]
Belongs to the [games](https://github.com/Calinou/scoop-games) bucket.
