### ISSUE TITLE
windows11-classic-context-menu@1.2: hash check failed

### ISSUE THREAD

**Issue by soredake** [ScoopInstaller/Extras#13694]
### Prerequisites

- [X] I have used the predefined issue title. (e.g. "xxx@xxx&#58; hash check failed")
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name and Version

windows11-classic-context-menu@1.2

**Comment by aliesbelik** [comment]
Fixed with #13695.
