### ISSUE TITLE
rnote@0.11.0: decompress error

### ISSUE THREAD

**Issue by sibouras** [ScoopInstaller/Extras#13696]
Installing 'rnote' (0.11.0) [64bit] from 'extras' bucket
rnote-win-installer-0.11.0-x86_64.exe (68.2 MB) [=====================================================] 100%
Checking hash of rnote-win-installer-0.11.0-x86_64.exe ... ok.
Extracting rnote-win-installer-0.11.0-x86_64.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\user\scoop\apps\rnote\0.11.0\setup.exe.
Log file:
  ~\scoop\apps\rnote\0.11.0\innounp.log

```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

```

**Comment by aliesbelik** [comment]
Relates to #13444.

With **scoop v0.5.0+:**

```
scoop bucket add versions
scoop install versions/innounp-unicode
```

as a workaround.
