### ISSUE TITLE
[Request]: Netbird

### ISSUE THREAD

**Issue by Cikaros** [ScoopInstaller/Extras#13700]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Netbird

### Description

Netbird VPN

### Homepage

https://netbird.io/

### Download Link(s)

https://github.com/netbirdio/netbird/releases/tag/latest

### Some Indication of Popularity/Repute

Start 10.1K

**Comment by aliesbelik** [comment]
Relates to netbirdio/netbird#2312.
