### ISSUE TITLE
wingetui@3.1.1: decompress error

### ISSUE THREAD

**Issue by abelian424** [ScoopInstaller/Extras#13713]
> Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

Error persists even if I redownload installer.

**Comment by cscnk52** [comment]
can be fixed by https://github.com/ScoopInstaller/Extras/issues/13547#issuecomment-2210208796

**Comment by aliesbelik** [comment]
Duplicates #13709.
