### ISSUE TITLE
wingetui@3.1.1: decompress error

### ISSUE THREAD

**Issue by joostshao** [ScoopInstaller/Extras#13717]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: a8ff98|OK  |   5.8MiB/s|C:/scoop/cache/wingetui#3.1.1#9444487.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of WingetUI.Installer.exe ... ok.
Uninstalling 'wingetui' (3.1.0)
Installing 'wingetui' (3.1.1) [64bit] from 'extras' bucket
Loading WingetUI.Installer.exe from cache.
Extracting WingetUI.Installer.exe ... ERROR Exit code was 1!
Failed to extract files from C:\scoop\apps\wingetui\3.1.1\WingetUI.Installer.exe.
Log file:
  C:\scoop\apps\wingetui\3.1.1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=wingetui%403.1.1%3a+decompress+error
Removing wingetui: 3.1.1
Everything is shiny now!
Removing wingetui#3.1.1#9444487.exe...

**Comment by aliesbelik** [comment]
Duplicates #13709.
