### ISSUE TITLE
wingetui@3.1.1: decompress error

### ISSUE THREAD

**Issue by docjeff** [ScoopInstaller/Extras#13714]
Console output:

PS C:\Users\Win10_Pro> scoop install wingetui
Installing 'wingetui' (3.1.1) [64bit] from 'extras' bucket
WingetUI.Installer.exe (51.2 MB) [=============================================================================================================================================================] 100%
Checking hash of WingetUI.Installer.exe ... ok.
Extracting WingetUI.Installer.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\Win10_Pro\scoop\apps\wingetui\3.1.1\WingetUI.Installer.exe.
Log file:
  ~\scoop\apps\wingetui\3.1.1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=wingetui%403.1.1%3a+decompress+error
PS C:\Users\Win10_Pro>

End console output

**Comment by aliesbelik** [comment]
Duplicates #13709.
