### ISSUE TITLE
wingetui@3.1.1: decompress error

### ISSUE THREAD

**Issue by lcyan** [ScoopInstaller/Extras#13711]
Starting package update operation for package id=wingetui with Manager name=Scoop
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Windows\system32\windowspowershell\v1.0\powershell.exe
Process Call Arguments :  -NoProfile -ExecutionPolicy Bypass -Command scoop update extras/wingetui --global
Working Directory      : C:\Users\Administrator
Process Start Time     : 2024/7/29 9:35:25
    | ERROR 'wingetui' isn't installed correctly.
    | wingetui: 3.1.0 -> 3.1.1 (global)
    | Updating one outdated app:
    | Updating 'wingetui' (3.1.0 -> 3.1.1)
    | Downloading new version
    | Downloading https://github.com/martinet101/WingetUI/releases/download/3.1.1/WingetUI.Installer.exe (51.2 MB)...
    | Checking hash of WingetUI.Installer.exe ... ok.
    | Uninstalling 'wingetui' (3.1.0)
    | Installing 'wingetui' (3.1.1) [64bit] from 'extras' bucket
    | Loading WingetUI.Installer.exe from cache
    | Extracting WingetUI.Installer.exe ... ERROR Exit code was 1!
    | Failed to extract files from D:\GlobalScoopApps\apps\wingetui\3.1.1\WingetUI.Installer.exe.
    | Log file:
    |   D:\GlobalScoopApps\apps\wingetui\3.1.1\innounp.log
    | Please try again or create a new issue by using the following link and paste your console output:
    | https://github.com/ScoopInstaller/Extras/issues/new?title=wingetui%403.1.1%3a+decompress+error
Process Exit Code      : 1
Process End Time       : 2024/7/29 9:35:39
[innounp.log](https://github.com/user-attachments/files/16406150/innounp.log)

**Comment by cscnk52** [comment]
can be fixed by https://github.com/ScoopInstaller/Extras/issues/13547#issuecomment-2210208796

**Comment by aliesbelik** [comment]
Duplicates #13709.
