### ISSUE TITLE
halloy@2024.9: decompress error

### ISSUE THREAD

**Issue by eet-eet** [ScoopInstaller/Extras#13739]
ARN  Purging previous failed installation of halloy.
ERROR 'halloy' isn't installed correctly.
Removing older version (2024.9).
'halloy' was uninstalled.
Installing 'halloy' (2024.9) [64bit] from 'extras' bucket
Loading halloy-installer.msi from cache.
Checking hash of halloy-installer.msi ... ok.
Extracting halloy-installer.msi ... Exception: D:\scoop\apps\scoop\current\lib\core.ps1:889
Line |
 889 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'Halloy'! (error 16)

**Comment by aliesbelik** [comment]
Duplicates #13733, fixed by #13734.
