### ISSUE TITLE
wingetui@3.1.1: decompress error

### ISSUE THREAD

**Issue by howardsun-dev** [ScoopInstaller/Extras#13742]
Extracting WingetUI.Installer.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\xxxxx\scoop\apps\wingetui\3.1.1\WingetUI.Installer.exe.
Log file:
  ~\scoop\apps\wingetui\3.1.1\innounp.log

Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by xingchen-c** [comment]
You can try this [#13444](https://github.com/ScoopInstaller/Extras/issues/13444#issuecomment-2213509434)

**Comment by hylianux** [comment]
> You can try this [#13444](https://github.com/ScoopInstaller/Extras/issues/13444#issuecomment-2213509434)

That worked for me.

**Comment by aliesbelik** [comment]
Duplicates #13709.
