### ISSUE TITLE
[Request]: Arc browser

### ISSUE THREAD

**Issue by SiyuChen** [ScoopInstaller/Extras#13749]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [ ] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Arc

### Description

web browser

### Homepage

https://arc.net/

### Download Link(s)

https://releases.arc.net/windows/ArcInstaller.exe

### Some Indication of Popularity/Repute

Way more powerful than Chrome. Arc looks like the future of browsers.
@BEEBOMCO
Arc brought order to the chaos that was my online life. There’s no going back.
@KATELAURIELEE
Arc lives up to the hype. So intuitive, playful and pretty.
@FIVEBOIII
I just tried using a computer without Arc and it was miserable.
@MARKFISHMAN_XYZ

**Comment by aliesbelik** [comment]
Duplicates #13199.
