### ISSUE TITLE
wingetui@3.1.1: decompress error

### ISSUE THREAD

**Issue by sunshe35** [ScoopInstaller/Extras#13778]
wingetui: 3.1.0 -> 3.1.1
Updating one outdated app:
Updating 'wingetui' (3.1.0 -> 3.1.1)
Downloading new version
Loading WingetUI.Installer.exe from cache
Checking hash of WingetUI.Installer.exe ... ok.
Uninstalling 'wingetui' (3.1.0)
Installing 'wingetui' (3.1.1) [64bit] from 'extras' bucket
Loading WingetUI.Installer.exe from cache
Extracting WingetUI.Installer.exe ... ERROR Exit code was 1!
Failed to extract files from D:\ScoopApp\apps\wingetui\3.1.1\WingetUI.Installer.exe.
Log file:
  D:\ScoopApp\apps\wingetui\3.1.1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=wingetui%403.1.1%3a+decompress+error

the log file:  D:\ScoopApp\apps\wingetui\3.1.1\innounp.log
```bash
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

**Comment by aliesbelik** [comment]
Duplicates #13709.
