### ISSUE TITLE
foxit-reader@2024.2.3: hash check failed

### ISSUE THREAD

**Issue by jhuebner79** [ScoopInstaller/Extras#13789]
Please don't auto-close - when four people are filing a ticket during 24 hours it might be a real issue.

```
Updating 'foxit-reader' (2024.2.2 -> 2024.2.3)
Downloading new version
FoxitPDFReader202423_enu_Setup_Prom.exe (113,9 MB) [======================================================================] 100%
Checking hash of FoxitPDFReader202423_enu_Setup_Prom.exe ... ERROR Hash check failed!
App:         extras/foxit-reader
URL:         https://cdn78.foxitsoftware.com/product/reader/desktop/win/2024.2.3/FoxitPDFReader202423_enu_Setup_Prom.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    0bd3513df6e2bbe2f394154c81278e5fd997c93232a76ff047d61ee25dddbc7b
Actual:      2a40501c6f663d29b7d7865f7166b6665fc5b689ab8e8a575a1656c4c5e7f526
```

**Comment by jhuebner79** [comment]
Wow - all four people that opened this issue have the same actual hash of `2a40501c6f663d29b7d7865f7166b6665fc5b689ab8e8a575a1656c4c5e7f526`

**Comment by jhuebner79** [comment]
@aliesbelik @catnaut can you have a look, I chose you randomly from people who merged to master :)

**Comment by andi0b** [comment]
And github actions bot changed it back to the old and broken hash: https://github.com/ScoopInstaller/Extras/issues/13805

What's happening here? :D

**Comment by aliesbelik** [comment]
#13830
🤷
