### ISSUE TITLE
foxit-pdf-reader@2024.2.3: hash check failed

### ISSUE THREAD

**Issue by cscnk52** [ScoopInstaller/Extras#13782]
Checking hash of FoxitPDFReader202423_enu_Setup_Prom.exe ... ERROR Hash check failed!
App:         extras/foxit-pdf-reader
URL:         https://cdn78.foxitsoftware.com/product/reader/desktop/win/2024.2.3/FoxitPDFReader202423_enu_Setup_Prom.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    0bd3513df6e2bbe2f394154c81278e5fd997c93232a76ff047d61ee25dddbc7b
Actual:      2a40501c6f663d29b7d7865f7166b6665fc5b689ab8e8a575a1656c4c5e7f526

**Comment by jhuebner79** [comment]
I can reproduce.
