### ISSUE TITLE
inno-setup@6.3.3: decompress error

### ISSUE THREAD

**Issue by suiahae** [ScoopInstaller/Extras#13788]
install command

    scoop update -a
    inno-setup: 6.2.2 -> 6.3.3
    Updating 1 outdated apps:
    Updating 'inno-setup' (6.2.2 -> 6.3.3)
    Downloading new version
    Loading innosetup-6.3.3.exe from cache
    Checking hash of innosetup-6.3.3.exe ... ok.
    Uninstalling 'inno-setup' (6.2.2)
    Installing 'inno-setup' (6.3.3) [64bit] from 'extras' bucket
    Loading innosetup-6.3.3.exe from cache
    Extracting innosetup-6.3.3.exe ... ERROR Exit code was 1!
    Failed to extract files from C:\Users\anonym\scoop\apps\inno-setup\6.3.3\innosetup-6.3.3.exe.
    Log file:
      ~\scoop\apps\inno-setup\6.3.3\innounp.log
    
    Please try again or create a new issue by using the following link and paste your console output:
    https://github.com/ScoopInstaller/Extras/issues/new?title=inno-setup%406.3.3%3a+decompress+error

innounp.log

    Signature detected: Inno Setup Setup Data (6.3.0)
    This is not directly supported, but i'll try to unpack it as version 5602
    ; Version detected: 6300
    Critical error: The setup files are corrupted. Please obtain a new copy of the program.

What makes me wonder is that I have 6.3.3 installed, but it is 6.3.0 in the logs, could this be the cause of the error?

**Comment by aliesbelik** [comment]
Duplicates #13444.
