### ISSUE TITLE
foxit-reader@2024.2.3: hash check failed

### ISSUE THREAD

**Issue by pedershk** [ScoopInstaller/Extras#13786]
Starting package update operation for package id=foxit-reader with Manager name=Scoop
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
Process Call Arguments :  -NoProfile -ExecutionPolicy Bypass -Command scoop update extras/foxit-reader
Working Directory      : C:\Users\hekilset
Process Start Time     : 09.08.2024 21:45:52
    | foxit-reader: 2024.2.2 -> 2024.2.3
    | Updating one outdated app:
    | Updating 'foxit-reader' (2024.2.2 -> 2024.2.3)
    | Downloading new version
    | Downloading https://cdn78.foxitsoftware.com/product/reader/desktop/win/2024.2.3/FoxitPDFReader202423_enu_Setup_Prom.exe (113,9 MB)...
    | Checking hash of FoxitPDFReader202423_enu_Setup_Prom.exe ... ERROR Hash check failed!
    | App:         extras/foxit-reader
    | URL:         https://cdn78.foxitsoftware.com/product/reader/desktop/win/2024.2.3/FoxitPDFReader202423_enu_Setup_Prom.exe
    | First bytes: 4D 5A 50 00 02 00 00 00
    | Expected:    0bd3513df6e2bbe2f394154c81278e5fd997c93232a76ff047d61ee25dddbc7b
    | Actual:      2a40501c6f663d29b7d7865f7166b6665fc5b689ab8e8a575a1656c4c5e7f526
    | Please try again or create a new issue by using the following link and paste your console output:
    | https://github.com/ScoopInstaller/Extras/issues/new?title=foxit-reader%402024.2.3%3a+hash+check+failed
Process Exit Code      : 1
Process End Time       : 09.08.2024 21:46:00

**Comment by jhuebner79** [comment]
I can reproduce.
