### ISSUE TITLE
spotube@3.8.0: decompress error

### ISSUE THREAD

**Issue by onionadmn** [ScoopInstaller/Extras#13802]
ERROR 'spotube' isn't installed correctly.
spotube: 3.7.1 -> 3.8.0
Updating one outdated app:
Updating 'spotube' (3.7.1 -> 3.8.0)
Downloading new version
Loading Spotube-windows-x86_64-setup.exe from cache
Checking hash of Spotube-windows-x86_64-setup.exe ... ok.
Uninstalling 'spotube' (3.7.1)
Installing 'spotube' (3.8.0) [64bit] from 'extras' bucket
Loading Spotube-windows-x86_64-setup.exe from cache
Extracting Spotube-windows-x86_64-setup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Tools\Scoop\apps\spotube\3.8.0\Spotube-windows-x86_64-setup.exe.
Log file:
  C:\Tools\Scoop\apps\spotube\3.8.0\innounp.log

Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by aliesbelik** [comment]
Relates to #13444.

With **scoop v0.5.0+**:

```
scoop bucket add versions
scoop install versions/innounp-unicode
```

as a workaround.
