### ISSUE TITLE
spotube@3.8.0: decompress error

### ISSUE THREAD

**Issue by sKGu8gxV** [ScoopInstaller/Extras#13814]
Updating 'spotube' (3.7.1 -> 3.8.0)
Downloading new version
Loading Spotube-windows-x86_64-setup.exe from cache
Checking hash of Spotube-windows-x86_64-setup.exe ... ok.
Uninstalling 'spotube' (3.7.1)
Installing 'spotube' (3.8.0) [64bit] from 'extras' bucket
Loading Spotube-windows-x86_64-setup.exe from cache
Extracting Spotube-windows-x86_64-setup.exe ... ERROR Exit code was 1!
Failed to extract files from path\Spotube-windows-x86_64-setup.exe.
Log file:
  
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Unpacking failed. This version is not supported.

**Comment by aliesbelik** [comment]
Duplicates #13802.
