### ISSUE TITLE
spotube@3.8.0: decompress error

### ISSUE THREAD

**Issue by eevleevs** [ScoopInstaller/Extras#13819]
Installing 'spotube' (3.8.0) [64bit] from 'extras' bucket
Loading Spotube-windows-x86_64-setup.exe from cache
Checking hash of Spotube-windows-x86_64-setup.exe ... ok.
Extracting Spotube-windows-x86_64-setup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\giuli\scoop\apps\spotube\3.8.0\Spotube-windows-x86_64-setup.exe.
Log file:
  ~\scoop\apps\spotube\3.8.0\innounp.log

> Signature detected: Inno Setup Setup Data (6.3.0)
> This is not directly supported, but i'll try to unpack it as version 5602
> ; Version detected: 6300
> Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by aliesbelik** [comment]
Duplicates #13802.
