### ISSUE TITLE
spotube@3.8.0: decompress error

### ISSUE THREAD

**Issue by DrVektor** [ScoopInstaller/Extras#13816]
Checking hash of Spotube-windows-x86_64-setup.exe ... ok.
Extracting Spotube-windows-x86_64-setup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\ProgramData\Scoop\apps\spotube\3.8.0\Spotube-windows-x86_64-setup.exe.
Log file:
  C:\ProgramData\Scoop\apps\spotube\3.8.0\innounp.log

**Comment by aliesbelik** [comment]
Duplicates #13802.
