### ISSUE TITLE
[Request]: Add zotero7

### ISSUE THREAD

**Issue by ZhenyuXiao** [ScoopInstaller/Extras#13821]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Zotero 7

### Description

Zotero is a free, easy-to-use tool to help you collect, organize, annotate, cite, and share research.

### Homepage

https://www.zotero.org/

### Download Link(s)

https://www.zotero.org/download/

### Some Indication of Popularity/Repute

Zotero 7 is the redesigned version of Zotero 6: https://www.zotero.org/blog/zotero-7/.
Zotero 7 Github: https://github.com/zotero/zotero

**Comment by H-Tung** [comment]
I think you mean update [Zotero's manifest](https://github.com/ScoopInstaller/Extras/blob/master/bucket/zotero.json) to version 7 and (maybe) add Zotero 6.x to Version bucket?
 Anyway, I believe there's need to update the manifest as checkver apparently didn't work anymore.

**Comment by ZhenyuXiao** [comment]
Yes, I think so. And there is evidence that Zotero 6 can automatically update to Zotero 7.
https://forums.zotero.org/discussion/116628/now-available-zotero-7

> If you're running Zotero 6, you can update now by going to Help → "Check for Updates…". We'll begin offering Zotero 7 as an automatic update within the next few weeks.
