### ISSUE TITLE
ntlite@2024.8.10014: decompress error

### ISSUE THREAD

**Issue by Maxim4711** [ScoopInstaller/Extras#13834]
❯ scoop install ntlite
WARN  Purging previous failed installation of ntlite.
ERROR 'ntlite' isn't installed correctly.
Removing older version (2024.8.10014).
'ntlite' was uninstalled.
Installing 'ntlite' (2024.8.10014) [64bit] from 'extras' bucket
Loading NTLite_setup_x64.exe from cache
Checking hash of NTLite_setup_x64.exe ... ok.
Running pre_install script...done.
Running installer script...ERROR Exit code was 1!
Failed to extract files from D:\data\dev\tools\scoop\apps\ntlite\2024.8.10014\NTLite_setup_x64.exe.
Log file:
  D:\data\dev\tools\scoop\apps\ntlite\2024.8.10014\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=ntlite%402024.8.10014%3a+decompress+error

**Comment by aliesbelik** [comment]
Relates to #13444.

With **scoop v0.5.0+**:

```
scoop bucket add versions
scoop install versions/innounp-unicode
```

as a workaround.
