### ISSUE TITLE
foxit-reader@2024.2.3: hash check failed

### ISSUE THREAD

**Issue by nfolin** [ScoopInstaller/Extras#13832]
Console told me to report, I report...
Have a nice day :o)

Updating 'foxit-reader' (2024.2.2 -> 2024.2.3)
Downloading new version
FoxitPDFReader202423_enu_Setup_Prom.exe (113,9 MB) [==========================================================] 100%
Checking hash of FoxitPDFReader202423_enu_Setup_Prom.exe ... ERROR Hash check failed!
App:         extras/foxit-reader
URL:         https://cdn78.foxitsoftware.com/product/reader/desktop/win/2024.2.3/FoxitPDFReader202423_enu_Setup_Prom.exeFirst bytes: 4D 5A 50 00 02 00 00 00
Expected:    0bd3513df6e2bbe2f394154c81278e5fd997c93232a76ff047d61ee25dddbc7b
Actual:      2a40501c6f663d29b7d7865f7166b6665fc5b689ab8e8a575a1656c4c5e7f526

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=foxit-reader%402024.2.3%3a+hash+check+failed

**Comment by nfolin** [comment]
No, I don't think I made a mistake...

Maybe scoop+Foxit cannot handle a '-g/global' installation ?

C:\Windows\system32>scoop update * -g
foxit-reader: 2024.2.2 -> 2024.2.3 (global)
Updating one outdated app:
Updating 'foxit-reader' (2024.2.2 -> 2024.2.3)
Downloading new version
FoxitPDFReader202423_enu_Setup_Prom.exe (113,9 MB) [===================================================================================================================] 100%
Checking hash of FoxitPDFReader202423_enu_Setup_Prom.exe ... ERROR Hash check failed!
App:         extras/foxit-reader
URL:         https://cdn78.foxitsoftware.com/product/reader/desktop/win/2024.2.3/FoxitPDFReader202423_enu_Setup_Prom.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    0bd3513df6e2bbe2f394154c81278e5fd997c93232a76ff047d61ee25dddbc7b
Actual:      2a40501c6f663d29b7d7865f7166b6665fc5b689ab8e8a575a1656c4c5e7f526

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=foxit-reader%402024.2.3%3a+hash+check+failed

C:\Windows\system32>scoop update
Updating Scoop...
Updating Buckets...
 * e3739d82d109 ueli: Update to version 9.3.2                            extras       3 minutes ago
 * 259bd68ed57f ucheck: Update to version 5.6.1                          extras       3 minutes ago
 * b7e3f1401b08 tutanota: Update to version 240.240816.0                 extras       3 minutes ago
 * 99014c499d95 swyh-rs: Update to version 1.11.1                        extras       3 minutes ago
 * 248a5d9f6717 stirling-pdf: Update to version 0.28.1                   extras       3 minutes ago
 * 219f480fefb6 sidekick-browser: Update to version 122.59.1.38681-203.. extras       3 minutes ago
 * 6a74c33aa9e1 okular: Update to version 24.08-5227                     extras       3 minutes ago
 * 53c3b8d91a1d mongosh: Update to version 2.3.0                         extras       3 minutes ago
 * 0dd036aa4687 media-downloader: Update to version 5.0.0                extras       3 minutes ago
 * 921f02b3a68d kate: Update to version 24.08-7743                       extras       3 minutes ago
 * 6fe7a8ac3c2d filelight: Update to version 24.08-1479                  extras       3 minutes ago
 * 4b0cdd16ac36 7tt: Update to version 5.15.2                            extras       3 minutes ago
Scoop was updated successfully!

C:\Windows\system32>scoop cache rm foxit-reader
Removing foxit-reader#12.1.2.15332#https_cdn06.foxitsoftware.com_product_reader_desktop_win_12.1.2_FoxitPDFReader1212_L10N_Setup.msi...
Removing foxit-reader#12.1.3.15356#https_cdn06.foxitsoftware.com_product_reader_desktop_win_12.1.3_FoxitPDFReader1213_L10N_Setup.msi...
Removing foxit-reader#2023.3.0#https_cdn78.foxitsoftware.com_product_reader_desktop_win_2023.3.0_FoxitPDFReader20233_enu_Setup_Prom.exe...
Removing foxit-reader#2024.1.0#https_cdn78.foxitsoftware.com_product_reader_desktop_win_2024.1.0_FoxitPDFReader20241_enu_Setup_Prom.exe...
Removing foxit-reader#2024.2.0#https_cdn78.foxitsoftware.com_product_reader_desktop_win_2024.2.0_FoxitPDFReader20242_enu_Setup_Prom.exe...
Removing foxit-reader#2024.2.1#https_cdn78.foxitsoftware.com_product_reader_desktop_win_2024.2.1_FoxitPDFReader202421_enu_Setup_Prom.exe...
Removing foxit-reader#2024.2.2#https_cdn78.foxitsoftware.com_product_reader_desktop_win_2024.2.2_FoxitPDFReader202422_enu_Setup_Prom.exe...
Deleted: 7 files, 1,1 GB

C:\Windows\system32>scoop update foxit-reader -g
foxit-reader: 2024.2.2 -> 2024.2.3 (global)
Updating one outdated app:
Updating 'foxit-reader' (2024.2.2 -> 2024.2.3)
Downloading new version
FoxitPDFReader202423_enu_Setup_Prom.exe (113,9 MB) [===================================================================================================================] 100%
Checking hash of FoxitPDFReader202423_enu_Setup_Prom.exe ... ERROR Hash check failed!
App:         extras/foxit-reader
URL:         https://cdn78.foxitsoftware.com/product/reader/desktop/win/2024.2.3/FoxitPDFReader202423_enu_Setup_Prom.exe
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    0bd3513df6e2bbe2f394154c81278e5fd997c93232a76ff047d61ee25dddbc7b
Actual:      2a40501c6f663d29b7d7865f7166b6665fc5b689ab8e8a575a1656c4c5e7f526

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=foxit-reader%402024.2.3%3a+hash+check+failed

C:\Windows\system32>

**Comment by nfolin** [comment]
And how to reopen this issue ? Nasty bot closed it without brain (no offense, it's a bot...)

**Comment by aliesbelik** [comment]
#13830
