### ISSUE TITLE
spotube@3.8.0: decompress error

### ISSUE THREAD

**Issue by morxs** [ScoopInstaller/Extras#13841]
Hi, just want to let you know there is error when extract

Extracting Spotube-windows-x86_64-setup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\hp\scoop\apps\spotube\3.8.0\Spotube-windows-x86_64-setup.exe.
Log file:
  ~\scoop\apps\spotube\3.8.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=spotube%403.8.0%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #13802.
