### ISSUE TITLE
deltachat@1.46.1: decompress error

### ISSUE THREAD

**Issue by ISouthRain** [ScoopInstaller/Extras#13854]
Commands Test:
scoop install extras/deltachat
Out: 
WARN  Purging previous failed installation of deltachat.
ERROR 'deltachat' isn't installed correctly.
Removing older version (1.46.1).
'deltachat' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'deltachat' (1.46.1) [64bit] from 'extras' bucket
Loading DeltaChat%201.46.1.exe from cache.
Checking hash of DeltaChat%201.46.1.exe ... ok.
Extracting DeltaChat%201.46.1.exe ... done.
Running installer script...ERROR Exit code was 2!
Failed to extract files from F:\App\Scoop\apps\deltachat\1.46.1\$PLUGINSDIR\app-64.7z.
Log file:
  F:\App\Scoop\apps\deltachat\1.46.1\$PLUGINSDIR\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=deltachat%401.46.1%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #13461.
