### ISSUE TITLE
battery-care@0.9.36: hash check failed

### ISSUE THREAD

**Issue by Shxvi** [ScoopInstaller/Extras#13876]
![image](https://github.com/user-attachments/assets/da052d03-232c-4a58-9c53-f33dda58041f)

**Comment by Shxvi** [comment]
scoop up-to-date, any other package installs without problems
![image](https://github.com/user-attachments/assets/1cd963d0-13d3-433f-bda5-c88b1f31c8d8)

**Comment by aliesbelik** [comment]
As from both logs

> BatteryCarePortable.zip (1.5 KB) [======================

zip size seems to small for original archive (~1.2. MB).
Looks like kind of error page is downloaded instead of the binary.
