### ISSUE TITLE
[Request]: Upgrade QQ 9.7.23.240423 to 9.9.15_240822

### ISSUE THREAD

**Issue by chatterzhao** [ScoopInstaller/Extras#13886]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [ ] Full version (i.e. not a trial version)
- [ ] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

QQ

### Description

Upgrade QQ 9.7.23.240423 to 9.9.15_240822

### Homepage

https://github.com/ScoopInstaller/Extras/blob/master/bucket/qq.json

### Download Link(s)

https://dldir1.qq.com/qqfile/qq/QQNT/Windows/QQ_9.9.15_240822_x64_01.exe

### Some Indication of Popularity/Repute

Upgrade QQ 9.7.23.240423 to 9.9.15_240822

**Comment by cscnk52** [comment]
you can trying to install from bucket dorado.
```
scoop bucket add dorado https://github.com/chawyehsu/dorado
scoop install dorado/qqnt
```

**Comment by aliesbelik** [comment]
Relates to #12803/#12866.

**Comment by aliesbelik** [comment]
Added as separate manifest - `extras\qq-nt`.
