### ISSUE TITLE
[Request]: GitHub Desktop

### ISSUE THREAD

**Issue by stomydent** [ScoopInstaller/Extras#13944]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [x] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

github-desktop

### Description

GIT GUI Client

### Homepage

https://desktop.github.com

### Download Link(s)

https://desktop.github.com/download/

### Some Indication of Popularity/Repute

https://git-scm.com/downloads/guis - 1st option

It's not found in scoop official/known buckets,

**Comment by aliesbelik** [comment]
`extras/github`
