### ISSUE TITLE
poedit@3.5: decompress error

### ISSUE THREAD

**Issue by gonwe** [ScoopInstaller/Extras#13967]
Extracting Poedit-3.5-setup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\Lin\scoop\apps\poedit\3.5\Poedit-3.5-setup.exe.
Log file:
  ~\scoop\apps\poedit\3.5\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=poedit%403.5%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #13922.
