### ISSUE TITLE
digital@0.31: hash check failed

### ISSUE THREAD

**Issue by yinyue200** [ScoopInstaller/Extras#13980]
ERROR Hash check failed!
App:         extras/digital
URL:         https://github.com/hneemann/Digital/releases/download/v0.31/Digital.zip
First bytes: 50 4B 03 04 0A 00 00 08
Expected:    f165c40e55b702fe4e42935ac3aaa9f74cd1d18b9e296204064fff2e2c13f222
Actual:      12f014c8b99140554f8f7464ebc771bbe3de6af39c83c20463492bcb892afc69

**Comment by aliesbelik** [comment]
Fixed by #13981.
