### ISSUE TITLE
[Bug]: Slack package is critically outdated

### ISSUE THREAD

**Issue by judehunter** [ScoopInstaller/Extras#14003]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

slack

### Expected/Current Behaviour

The currently listed version of extra/slack (4.33.84) is outdated by more than a year and causes this error popup:

<img src="https://github.com/user-attachments/assets/811cbe32-6c27-4b40-a8cc-2265ec4e6077" width="60%">

The latest version seems to be 4.40.126 - I'm not sure why it wasn't automatically picked up by the bot.

Note that the beta version seems to be up to date, but it shouldn't be the only usable option.

### Steps to Reproduce

```console
`scoop install slack`
- installs version v4.33.84 which is no longer supported
```

### Possible Solution

I'm not sure how the bot works and why it failed to keep it up to date

### Scoop and Buckets Version

```console
Current Scoop version:
859d1db5 (HEAD -> master, tag: v0.5.2, origin/master, origin/HEAD) chore(release): Bump to version 0.5.2 (#6080)

'main' bucket:
e1f905c45 (HEAD -> master, origin/master, origin/HEAD) surrealdb: Update to version 1.5.5

'extras' bucket:
fb2186401 (HEAD -> master, origin/master, origin/HEAD) sidekick-browser: Update to version 124.61.1.50157-02818a4

'versions' bucket:
e03e7fa49 (HEAD -> master, origin/master, origin/HEAD) vscode-insiders@1.94.0-1725944772446: Fix hash (Closes #1942)

'nonportable' bucket:
e6e6db96 (HEAD -> master, origin/master, origin/HEAD) 10x-np: Update to version 1.0.215
```

### Scoop Config

```console
last_update                       scoop_repo                              scoop_branch
-----------                       ----------                              ------------
2024-09-11T09:47:35.8738679+02:00 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.4111
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.4111
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by silver886** [comment]
I created #14033 to address the root cause and #14034 to fix the issue.
