### ISSUE TITLE
tableplus@6.1.1.278: decompress error

### ISSUE THREAD

**Issue by Stanzilla** [ScoopInstaller/Extras#14032]
Updating 'tableplus' (6.1.0.276 -> 6.1.1.278)
Downloading new version
Loading TablePlusSetup.exe from cache
Checking hash of TablePlusSetup.exe ... ok.
Uninstalling 'tableplus' (6.1.0.276)
Installing 'tableplus' (6.1.1.278) [64bit] from 'extras' bucket
Loading TablePlusSetup.exe from cache
Extracting TablePlusSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\Stan\scoop\apps\tableplus\6.1.1.278\TablePlusSetup.exe.
Log file:
  ~\scoop\apps\tableplus\6.1.1.278\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=tableplus%406.1.1.278%3a+decompress+error

```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

**Comment by aliesbelik** [comment]
Duplicates #14012.
