### ISSUE TITLE
[Request]: GoofCord

### ISSUE THREAD

**Issue by Milkshiift** [ScoopInstaller/Extras#14065]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

GoofCord

### Description

An alternative standalone Discord client

### Homepage

https://github.com/Milkshiift/GoofCord

### Download Link(s)

https://github.com/Milkshiift/GoofCord/releases

### Some Indication of Popularity/Repute

~191 stars ⭐

**Comment by aliesbelik** [comment]
Relates to Milkshiift/GoofCord#19.
