### ISSUE TITLE
poedit@3.5: decompress error

### ISSUE THREAD

**Issue by transmixer** [ScoopInstaller/Extras#14073]
```cli
Installing 'poedit' (3.5) [64bit] from 'extras' bucket
Loading Poedit-3.5-setup.exe from cache
Extracting Poedit-3.5-setup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\install\Scoop\apps\poedit\3.5\Poedit-3.5-setup.exe.
Log file:
    \Scoop\apps\poedit\3.5\innounp.log
```
Contents in innounp.log:
>Signature detected: Inno Setup Setup Data (6.3.0)
>This is not directly supported, but i'll try to unpack it as version 5602
>; Version detected: 6300
>Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by mattcargile** [comment]
I assume you have `scoop install innounp`? Not sure if that would help. You can run `scoop checkup` to see if you do have it.

**Comment by transmixer** [comment]
Unfortunately, `innounp` was already installed. No idea what happend to `poedit`.
```cli
> scoop list innounp
Installed apps matching 'innounp':

Name    Version Source Updated             Info
----    ------- ------ -------             ----
innounp 0.50    main   2022-04-28 00:49:17
```

**Comment by aliesbelik** [comment]
Duplicates #13922.
