### ISSUE TITLE
spotube@3.8.1: decompress error

### ISSUE THREAD

**Issue by Detet** [ScoopInstaller/Extras#14101]
❯ scoop install spotube
WARN  Purging previous failed installation of spotube.
ERROR 'spotube' isn't installed correctly.
Removing older version (3.8.1).
'spotube' was uninstalled.
Installing 'spotube' (3.8.1) [64bit] from 'extras' bucket
Loading Spotube-windows-x86_64-setup.exe from cache
Checking hash of Spotube-windows-x86_64-setup.exe ... ok.
Extracting Spotube-windows-x86_64-setup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\Detet\scoop\apps\spotube\3.8.1\Spotube-windows-x86_64-setup.exe.
Log file:
  ~\scoop\apps\spotube\3.8.1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=spotube%403.8.1%3a+decompress+error

❯ cat   ~\scoop\apps\spotube\3.8.1\innounp.log
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by Detet** [comment]
Deleted cache and tried redownloading and installing but same.

❯  scoop cache rm spotube
Removing spotube#3.8.1#04e0deb.exe...
Deleted: 1 file, 25,3 MB

❯ scoop install spotube
WARN  Purging previous failed installation of spotube.
ERROR 'spotube' isn't installed correctly.
Removing older version (3.8.1).
'spotube' was uninstalled.
Installing 'spotube' (3.8.1) [64bit] from 'extras' bucket
Spotube-windows-x86_64-setup.exe (25,3 MB) [==================================================================] 100%
Checking hash of Spotube-windows-x86_64-setup.exe ... ok.
Extracting Spotube-windows-x86_64-setup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\Detet\scoop\apps\spotube\3.8.1\Spotube-windows-x86_64-setup.exe.
Log file:
  ~\scoop\apps\spotube\3.8.1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=spotube%403.8.1%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #13802.
