### ISSUE TITLE
ollama-full@0.3.12: decompress error

### ISSUE THREAD

**Issue by YXPD** [ScoopInstaller/Extras#14120]
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\pod\scoop\apps\ollama-full\0.3.12\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama-full\0.3.12\innounp.log

Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Unpacking failed. This version is not supported.

**Comment by aliesbelik** [comment]
Relates to #13444, ScoopInstaller/Main#6065.
