### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by office-allow** [ScoopInstaller/Extras#14126]
Updating 'gimp' (2.10.38 -> 2.10.38-1)
Downloading new version
Loading gimp-2.10.38-setup-1.exe from cache.
Checking hash of gimp-2.10.38-setup-1.exe ... ok.
Uninstalling 'gimp' (2.10.38)
Installing 'gimp' (2.10.38-1) [64bit] from 'extras' bucket
Loading gimp-2.10.38-setup-1.exe from cache.
Extracting gimp-2.10.38-setup-1.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\nz6nkj\scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.
Log file:
  ~\scoop\apps\gimp\2.10.38-1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=gimp%402.10.38-1%3a+decompress+error

**Comment by pmolodo** [comment]
I had a similar issue, except my innoup.log was (very slightly) different:

```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

**Comment by clayton-errington** [comment]
This is what the log shows for my installation error: 

```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

I even cleaned the scoop cache to redownload the file, and got the same error message. 

`scoop cache rm *`

**Comment by aliesbelik** [comment]
Relates to #13444.

With **scoop v0.5.0+**:

```
scoop bucket add versions
scoop install versions/innounp-unicode
```

as a workaround.

**Comment by pmolodo** [comment]
Also - is there a plan for an eventual non-workaround fix, that will "just work"?  Changing the requirements to explicitly list innounp-unicode instead of innounp, or somehow making innounp-unicode an official replacement/upgrade for innounp?

**Comment by bartvanandel** [comment]
@pmolodo `innounp` is an Inno Setup Unpacker. The one in the versions bucket is newer, and is a unicode variant. The whole point of the [versions bucket`](https://github.com/ScoopInstaller/Versions) is to provide "alternative" versions of packages, including development versions and pinned versions. See the linked description.

Output of `scoop info main/innounp` on my machine (after running `scoop update` to retrieve the latest digests):
```
Name        : innounp
Description : Inno Setup Unpacker
Version     : 0.50
Bucket      : main
Website     : https://innounp.sourceforge.net
License     : GPL-3.0-only
Updated at  : 2023-03-09 19:33:29
Updated by  : StarsbySea
Installed   : 0.50 *global*
Binaries    : innounp.exe
```

Output of `scoop info versions/innounp-unicode`:
```
Name        : innounp-unicode
Description : Inno Setup Unpacker (Unicode)
Version     : 1.73
Bucket      : versions
Website     : https://www.rathlev-home.de/tools/prog-e.html#unpack
License     : GPL-3.0-only
Updated at  : 2024-10-10 3:57:12
Updated by  : github-actions[bot]
Binaries    : innounp.exe
```

So yeah, quite a bit newer.

**Comment by RaphaelTarita** [comment]
why does `main/innounp` not receive an update when it's so old and already causing problems?

**Comment by bartvanandel** [comment]
I don't know, I just wrote what I know after first running into this problem myself this morning.

**Comment by pmolodo** [comment]
Is there any chance to getting this MR merged so we can stop getting this error (and stop new tickets for this issue from being created repeatedly)?

https://github.com/ScoopInstaller/Main/pull/6261

(Thanks @Daviteusz !)
