### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by DCUDG** [ScoopInstaller/Extras#14139]
Extracting gimp-2.10.38-setup-1.exe ... ERROR Exit code was 1!
Failed to extract files from E:\Applications\Scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.
Log file:
  E:\Applications\Scoop\apps\gimp\2.10.38-1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=gimp%402.10.38-1%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #14126.
