### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by sohnman** [ScoopInstaller/Extras#14133]
I got error while trying to update gimp app and error message was
```
PS C:\Users\evan> scoop update gimp
gimp: 2.10.38 -> 2.10.38-1
Updating one outdated app:
Updating 'gimp' (2.10.38 -> 2.10.38-1)
Downloading new version
Loading gimp-2.10.38-setup-1.exe from cache
Checking hash of gimp-2.10.38-setup-1.exe ... ok.
Uninstalling 'gimp' (2.10.38)
Installing 'gimp' (2.10.38-1) [64bit] from 'extras' bucket
Loading gimp-2.10.38-setup-1.exe from cache
Extracting gimp-2.10.38-setup-1.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\evan\scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.
Log file:
  ~\scoop\apps\gimp\2.10.38-1\innounp.log
```

innounp.log said
```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

**Comment by aliesbelik** [comment]
Duplicates #14126.

**Comment by lolo32** [comment]
How can you close with a "not planned", @aliesbelik, even if it's no more possible to install/update gimp without any comment to help us?
Is not possible to update InnoSetup or anythong else to solve these issue?

**Comment by aliesbelik** [comment]
> How can you close with a "not planned", @aliesbelik, even if it's no more possible to install/update gimp without any comment to help us? Is not possible to update InnoSetup or anythong else to solve these issue?

@lolo32, seems you are not paying enough attention.
Please find my comment and link to duplicated issue above.
You'll be surprised, but you're not the first one who created a task without [trying to search first](https://github.com/ScoopInstaller/Extras/issues?q=gimp+and+created%3A%3E2024-10-01).
