### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by skyvanfall** [ScoopInstaller/Extras#14141]
Installing 'gimp' (2.10.38-1) [64bit] from 'extras' bucket
gimp-2.10.38-setup-1.exe (323.0 MB) [=========================================================================] 100%
Checking hash of gimp-2.10.38-setup-1.exe ... ok.
Extracting gimp-2.10.38-setup-1.exe ... ERROR Exit code was 1!
Failed to extract files from D:\bin\scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.
Log file:
  D:\bin\scoop\apps\gimp\2.10.38-1\innounp.log

**Comment by aliesbelik** [comment]
Duplicates #14126.
