### ISSUE TITLE
[Bug]tableplus@6.1.1.278: decompress error

### ISSUE THREAD

**Issue by julianramirezch** [ScoopInstaller/Extras#14148]
Quick description of the issue

```
scoop install extras/tableplus
Installing 'tableplus' (6.1.1.278) [64bit] from 'extras' bucket
TablePlusSetup.exe (213,9 MB) [===============================================================================] 100%
Checking hash of TablePlusSetup.exe ... ok.
Extracting TablePlusSetup.exe ... ERROR Exit code was 1!
Log file:
  ~\scoop\apps\tableplus\6.1.1.278\innounp.log
```

# Log File
`Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
`

**Comment by aliesbelik** [comment]
Duplicates #14012.

**Comment by julianramirezch** [comment]
The workaround works, thank you
