### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by vgi0ax12** [ScoopInstaller/Extras#14151]
WARN  Purging previous failed installation of gimp.
ERROR 'gimp' isn't installed correctly.
Removing older version (2.10.38-1).
'gimp' was uninstalled.
Installing 'gimp' (2.10.38-1) [64bit] from 'extras' bucket
Loading gimp-2.10.38-setup-1.exe from cache
Checking hash of gimp-2.10.38-setup-1.exe ... ok.
Extracting gimp-2.10.38-setup-1.exe ... ERROR Exit code was 1!
Failed to extract files from D:\Programme\scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.
Log file:
  D:\Programme\scoop\apps\gimp\2.10.38-1\innounp.log
  
  D:\>cat D:\Programme\scoop\apps\gimp\2.10.38-1\innounp.log
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by aliesbelik** [comment]
Duplicates #14126.
