### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by Sawansunar56** [ScoopInstaller/Extras#14164]
Failed to extract files from C:\Users\sawan\scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.
Log file:
  ~\scoop\apps\gimp\2.10.38-1\innounp.log

**Comment by aliesbelik** [comment]
Duplicates #14126.

**Comment by charudatta10** [comment]
###  Working FIX:

```powershell
scoop uninstall innounp
scoop bucket add versions
scoop install versions/innounp-unicode
```

**Comment by Sawansunar56** [comment]
@charudatta10 Thanks for that. It fixed the problem.
