### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by X-Ella-X** [ScoopInstaller/Extras#14172]
Extracting gimp-2.10.38-setup-1.exe ... ERROR Exit code was 1!                                                          
Failed to extract files from C:\Users\efels\scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.                        
Log file:                                                                                                                 
~\scoop\apps\gimp\2.10.38-1\innounp.log

**Comment by aliesbelik** [comment]
Duplicates #14126.
