### ISSUE TITLE
wingetui@3.1.1: decompress error

### ISSUE THREAD

**Issue by lassenie** [ScoopInstaller/Extras#14184]
PS C:\Users\103386> scoop update *
wingetui: 3.0.2 -> 3.1.1
Updating one outdated app:
Updating 'wingetui' (3.0.2 -> 3.1.1)
Downloading new version
Loading WingetUI.Installer.exe from cache
Checking hash of WingetUI.Installer.exe ... ok.
Uninstalling 'wingetui' (3.0.2)
Installing 'wingetui' (3.1.1) [64bit] from 'extras' bucket
Loading WingetUI.Installer.exe from cache
Extracting WingetUI.Installer.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\103386\scoop\apps\wingetui\3.1.1\WingetUI.Installer.exe.
Log file:
  ~\scoop\apps\wingetui\3.1.1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=wingetui%403.1.1%3a+decompress+error

Log file: [innounp.log](https://github.com/user-attachments/files/17338320/innounp.log)

**Comment by lassenie** [comment]
Attached log file:
[innounp.log](https://github.com/user-attachments/files/17338334/innounp.log)

**Comment by aliesbelik** [comment]
Duplicates #13709.
