### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by univerz1977** [ScoopInstaller/Extras#14191]
Updating 'gimp' (2.10.38 -> 2.10.38-1)
Downloading new version
Loading gimp-2.10.38-setup-1.exe from cache
Checking hash of gimp-2.10.38-setup-1.exe ... ok.
Uninstalling 'gimp' (2.10.38)
Installing 'gimp' (2.10.38-1) [64bit] from 'extras' bucket
Loading gimp-2.10.38-setup-1.exe from cache
Extracting gimp-2.10.38-setup-1.exe ... Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请 提供一个不为 Null 或空的参数，然后重试
该命令。
所在位置 C:\scoop\apps\scoop\current\lib\decompress.ps1:253 字符: 38
+ ... tus = Invoke-ExternalCommand (Get-HelperPath -Helper Innounp) $ArgLis ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

Failed to extract files from C:\scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.
Log file:
  C:\scoop\apps\gimp\2.10.38-1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=gimp%402.10.38-1%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #14126.
