### ISSUE TITLE
msiafterburner@4.6.5: decompress error

### ISSUE THREAD

**Issue by felix-zheng91** [ScoopInstaller/Extras#14204]
Installing 'msiafterburner' (4.6.5) [64bit] from 'extras' bucket
MSIAfterburnerSetup.zip (56.2 MB) [===========================================] 100%
Checking hash of MSIAfterburnerSetup.zip ... ok.
Extracting MSIAfterburnerSetup.zip ... done.
Running pre_install script...ERROR Exit code was 7!
Failed to extract files from D:\Scoop\apps\msiafterburner\4.6.5\MSIAfterburnerSetup*.exe.
Log file:
  D:\Scoop\apps\msiafterburner\4.6.5\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=msiafterburner%404.6.5%3a+decompress+error

**Comment by Daviteusz** [comment]
Use this for now: From #13671 
```powershell
scoop install https://raw.githubusercontent.com/ScoopInstaller/Extras/f8aced773f644a601ff38479a1ffc1f3615122c7/bucket/msiafterburner.json
```
