### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by devenstudio** [ScoopInstaller/Extras#14242]
Installing 'gimp' (2.10.38-1) [64bit] from 'extras' bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: ce34cb|OK  |    13MiB/s|C:/Users/deven/scoop/cache/gimp#2.10.38-1#1eb8f86.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of gimp-2.10.38-setup-1.exe ... ok.
Extracting gimp-2.10.38-setup-1.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\deven\scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.
Log file:
  ~\scoop\apps\gimp\2.10.38-1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=gimp%402.10.38-1%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #14126.
