### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by JPFigurati** [ScoopInstaller/Extras#14265]
Attempting to install Gimp v2.10.38-1 with the command 'scoop install extras/gimp' gives the current following error:

"Failed to extract files from C:\Users\JPWheeler\scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.
Log file:
  ~\scoop\apps\gimp\2.10.38-1\innounp.log"

Mentions the setup executable is corrupted.  However, I've tried the command at least five times with the same result.  Perhaps the checksum is invalid?

Log file attached.

[innounp.log](https://github.com/user-attachments/files/17463403/innounp.log)

**Comment by aliesbelik** [comment]
Duplicates #14126.
