### ISSUE TITLE
[Bug]: Gramps - Download link not working

### ISSUE THREAD

**Issue by mpathy** [ScoopInstaller/Extras#14278]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

gramps

### Expected/Current Behaviour

I wanted to install the genealogy programm "gramps" from the extras bucket

### Steps to Reproduce

```console
PS C:\Users\XXXXXXXXXXXX> scoop install gramps

Installing 'gramps' (5.2.3) [64bit] from 'extras' bucket
Die Anfrage wurde abgebrochen: Die Verbindung wurde unerwartet getrennt..
URL https://github.com/gramps-project/gramps/releases/download/v5.2.3/GrampsAIO-5.2.3-1_win64.exe#/dl.7z is not valid
```

### Possible Solution

The solution is to use the correct link to the package.
At best, already use the newest package (5.2.3-2 instead 5.2.3-1)

Download URL:
https://github.com/gramps-project/gramps/releases/download/v5.2.3/GrampsAIO-5.2.3-2_win64.exe

And next time testing it before commit

### Scoop and Buckets Version

```console
Current Scoop version:
859d1db5 (HEAD -> master, tag: v0.5.2, origin/master, origin/HEAD) chore(release): Bump to version 0.5.2 (#6080)

'main' bucket:
e67995ed7 (HEAD -> master, origin/master, origin/HEAD) lefthook: Update to version 1.8.1

'extras' bucket:
8b12f7e2a (HEAD -> master, origin/master, origin/HEAD) zoom: Update to version 6.2.5.48876

'nerd-fonts' bucket:
6b3d7fcc (HEAD -> master, origin/master, origin/HEAD) LXGWNeoZhiSong: Update to version 1.020

'games' bucket:
ddb0df36f (HEAD -> master, origin/master, origin/HEAD) cataclysm-dda-tiles-experimental: Update to version 2024-10-23-0605
```

### Scoop Config

```console
last_update                       scoop_repo                              scoop_branch
-----------                       ----------                              ------------
2024-10-23T14:10:18.4923789+02:00 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.26100.1882
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.26100.1882
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by aliesbelik** [comment]
> And next time testing it before commit

I guess (at least by [comparing dates when release was created and last version of .exe was added](https://api.github.com/repos/gramps-project/gramps/releases/latest)) that win64 binary was silently updated after release (5.2.3-1 -> 5.2.3-2) and that's not something scoop could normally detect.
