### ISSUE TITLE
ollama-full@0.3.14: decompress error

### ISSUE THREAD

**Issue by PixelJuice** [ScoopInstaller/Extras#14272]
Installing 'innounp' (0.50) [64bit] from 'main' bucket
Loading innounp050.rar from cache
Checking hash of innounp050.rar ... ok.
Extracting innounp050.rar ... done.
Linking ~\scoop\apps\innounp\current => ~\scoop\apps\innounp\0.50
Creating shim for 'innounp'.
'innounp' (0.50) was installed successfully!
Installing 'ollama-full' (0.3.14) [64bit] from 'extras' bucket
Loading OllamaSetup.exe from cache
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\username\scoop\apps\ollama-full\0.3.14\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama-full\0.3.14\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=ollama-full%400.3.14%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #14120.
