### ISSUE TITLE
[Important, I need a human review] reduce-memory@1.6: hash check failed

### ISSUE THREAD

**Issue by JetC10** [ScoopInstaller/Extras#14287]
[Important, I need a human review]

I have reported this problem before, but the error is still there when running the command `scoop install reduce-memory`

PS C:\Users\user> scoop install reduce-memory
Installing 'reduce-memory' (1.6) [64bit] from 'extras' bucket
ReduceMemory.zip (959,3 KB) [==============================================================================] 100%
Checking hash of ReduceMemory.zip ... ERROR Hash check failed!
App:         extras/reduce-memory
URL:         https://www.sordum.org/files/download/reduce-memory/ReduceMemory.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    ec7607f7f1721f372badf67d897a0932fce96418346e90a960d067fbbbfc024d
Actual:      ce2ac82e484a52ad763bade09957646cd36ba9bc8639d0d4b20ad9f1599d581a

![imagen](https://github.com/user-attachments/assets/12c9710c-5c51-499e-8b47-666c237f554b)

The problem I think is that the hash in the Scoop/extras repository does not match the hash on the official program page [https://www.sordum.org/9197/reduce-memory-v1-6/](url). When I download the original file from the Sordum page and scan it with VirusTotal I get exactly the same hash when I run the command, but I expect a different one.

![imagen](https://github.com/user-attachments/assets/b569ae7d-1452-4c30-9a16-1db4a0b5394f)

**Comment by Daviteusz** [comment]
```
Installing 'reduce-memory' (1.6) [64bit] from 'extras' bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 37bdd6|OK  |   478KiB/s|C:/Users/Mateusz/scoop/cache/reduce-memory#1.6#6f67979.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of ReduceMemory.zip ... ok.
Extracting ReduceMemory.zip ... done.
Running pre_install script...done.
Linking ~\scoop\apps\reduce-memory\current => ~\scoop\apps\reduce-memory\1.6
Creating shim for 'ReduceMemory'.
Making C:\Users\Mateusz\scoop\shims\reducememory.exe a GUI binary.
Creating shortcut for Reduce Memory (ReduceMemory.exe)
Persisting ReduceMemory.ini
'reduce-memory' (1.6) was installed successfully!
```

Works for me
