### ISSUE TITLE
onlyoffice-desktopeditors@8.2.0: decompress error

### ISSUE THREAD

**Issue by samederdem** [ScoopInstaller/Extras#14289]
console log:
Updating 'onlyoffice-desktopeditors' (8.1.1 -> 8.2.0)
Downloading new version
Loading DesktopEditors_x64.exe from cache.
Checking hash of DesktopEditors_x64.exe ... ok.
Uninstalling 'onlyoffice-desktopeditors' (8.1.1)
Installing 'onlyoffice-desktopeditors' (8.2.0) [64bit] from 'extras' bucket
Loading DesktopEditors_x64.exe from cache.
Extracting DesktopEditors_x64.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\smder\scoop\apps\onlyoffice-desktopeditors\8.2.0\DesktopEditors_x64.exe.
Log file:
  ~\scoop\apps\onlyoffice-desktopeditors\8.2.0\innounp.log

  ~\scoop\apps\onlyoffice-desktopeditors\8.2.0\innounp.log:
Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=onlyoffice-desktopeditors%408.2.0%3a+decompress+error
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by aliesbelik** [comment]
Duplicates #14271.
