### ISSUE TITLE
[Request]: gojq

### ISSUE THREAD

**Issue by Gitoffthelawn** [ScoopInstaller/Extras#14298]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

gojq

### Description

Portable pure Go implementation of jq

### Homepage

https://github.com/itchyny/gojq

### Download Link(s)

https://github.com/itchyny/gojq/releases

### Some Indication of Popularity/Repute

3.3K stars on GitHub

**Comment by aliesbelik** [comment]
As a non-GUI tool could be submitted into the `main` bucket instead, since meeting the [Main criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket).

**Comment by Gitoffthelawn** [comment]
@aliesbelik Thanks Aliaksandr.  I will close here and submit there instead.

**Comment by Gitoffthelawn** [comment]
Submitted to `main` package instead: https://github.com/ScoopInstaller/Main/issues/6284
