### ISSUE TITLE
wingetui@3.1.2: decompress error

### ISSUE THREAD

**Issue by VassiliTM** [ScoopInstaller/Extras#14290]
Hi, when I try to install wingetui I have this issue. It start at 3.1.1
I use NanaZip.
When I'm trying to install manually I don't have any problem.

PS C:\Users\xxx\Desktop> scoop install extras/wingetui
Installing 'wingetui' (3.1.2) [64bit] from 'extras' bucket
WingetUI.Installer.exe (52,9 MB) [============================================================================] 100%
Checking hash of WingetUI.Installer.exe ... ok.
Extracting WingetUI.Installer.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\xxx\scoop\apps\wingetui\3.1.2\WingetUI.Installer.exe.
Log file:
[innounp.log](https://github.com/user-attachments/files/17517738/innounp.log)

  ~\scoop\apps\wingetui\3.1.2\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=wingetui%403.1.2%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #13709.
