### ISSUE TITLE
wingetui@3.1.3: decompress error

### ISSUE THREAD

**Issue by chenchun0629** [ScoopInstaller/Extras#14317]
cat ~\scoop\apps\wingetui\3.1.3\innounp.log

Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by aliesbelik** [comment]
Duplicates #13709.
