### ISSUE TITLE
onlyoffice-desktopeditors@8.2.0: decompress error

### ISSUE THREAD

**Issue by TechPro424** [ScoopInstaller/Extras#14310]
Updating 'onlyoffice-desktopeditors' (8.1.1 -> 8.2.0)
Downloading new version
Loading DesktopEditors_x64.exe from cache
Checking hash of DesktopEditors_x64.exe ... ok.
Uninstalling 'onlyoffice-desktopeditors' (8.1.1)
Installing 'onlyoffice-desktopeditors' (8.2.0) [64bit] from 'extras' bucket
Loading DesktopEditors_x64.exe from cache
Extracting DesktopEditors_x64.exe ... ERROR Exit code was 1!
Failed to extract files from C:\ProgramData\scoop\apps\onlyoffice-desktopeditors\8.2.0\DesktopEditors_x64.exe.
Log file:
  C:\ProgramData\scoop\apps\onlyoffice-desktopeditors\8.2.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=onlyoffice-desktopeditors%408.2.0%3a+decompress+error

**Comment by aliesbelik** [comment]
Duplicates #14271.
