### ISSUE TITLE
gimp@2.10.38-1: decompress error

### ISSUE THREAD

**Issue by shenka** [ScoopInstaller/Extras#14377]
PS C:\Users\DSMVG> scoop install extras/gimp
Updating Scoop...
Updating Buckets...
 * 92cce765fc89 trufflehog: Update to version 3.83.5                     main         3 hours ago
 * e60360cc8e61 ngrok: Update to version 3.18.3                          main         3 hours ago
 * 794ad8a06dc7 groovy: Update to version 4.0.24                         main         3 hours ago
 * b2b46c49e58a edgedriver: Update to version 130.0.2849.80              main         3 hours ago
 * ec4fab7512d7 vale: Update to version 3.9.0                            main         7 hours ago
 * e75ce0c2060f uv: Update to version 0.5.0                              main         7 hours ago
 * 4af5b6a1ab41 trid: Update to version 2.24-24.11.07                    main         7 hours ago
 * 952d295454c3 slang: Update to version 2024.14.5                       main         7 hours ago
 * 636ad984e348 schemacrawler: Update to version 16.22.3                 main         7 hours ago
 * f17489f0421c minio: Update to version 2024-11-07T00-52-20Z            main         7 hours ago
 * 02f170390bc2 minio-client: Update to version 2024-11-05T11-29-45Z     main         7 hours ago
 * c810cef0b193 istioctl: Update to version 1.24.0                       main         7 hours ago
 * 726ab7e102fb firebase: Update to version 13.24.2                      main         7 hours ago
 * befc8f57d444 d2: Update to version 0.6.8                              main         7 hours ago
 * cdda9110304c atmos: Update to version 1.100.1                         main         7 hours ago
 * c4289598343e terragrunt: Update to version 0.68.8                     main         11 hours ago
 * 8b3012e01b0c terraform-provider-ibm: Update to version 1.71.1         main         11 hours ago
 * 01696282111e oh-my-posh: Update to version 24.1.0                     main         11 hours ago
 * b7872195c2d8 mediainfo: Update to version 24.11                       main         11 hours ago
 * f060d35e664b kiota: Update to version 1.20.0                          main         11 hours ago
 * 9eaac24c1b4d jx: Update to version 3.10.180                           main         11 hours ago
 * a1bed2462e9e jdtls: Update to version 1.42.0-202411071643             main         11 hours ago
 * a203a45d33a4 garnet: Update to version 1.0.36                         main         11 hours ago
 * 19361cdd4d54 flyctl: Update to version 0.3.34                         main         11 hours ago
 * ca49dfde6801 dnsproxy: Update to version 0.73.3                       main         11 hours ago
 * f95a7f063f3e codeql: Update to version 2.19.3                         main         11 hours ago
 * 7a05920d0f62 cc65: Update to version 11730284444                      main         11 hours ago
 * 5080bb32f6ef aws: Update to version 2.19.3                            main         11 hours ago
 * 4d3aa9d9a6ee 1password-cli: Update to version 2.30.3                  main         11 hours ago
 * 028734d1ad80 hjson: Update to version 4.4.0, add checkver, fix auto.. main         14 hours ago
 * 597ec8ea05cb mdbook: Update to version 0.4.42                         main         15 hours ago
 * 5db9d9ea625a gh: Update to version 2.61.0                             main         15 hours ago
 * 987a778c9ce9 docker-compose: Update to version 2.30.3                 main         15 hours ago
 * 2e9ccfc88115 cmake: Update to version 3.31.0                          main         15 hours ago
 * 385bd30e569f arduino-cli: Update to version 1.1.0                     main         15 hours ago
 * bfc185c6b832 erlang@27.1.2: Update suggestion (Close #6289)           main         16 hours ago
 * d8813f59adf9 supabase: Update to version 1.219.2                      main         19 hours ago
 * 3a3c706baf10 okteto: Update to version 3.1.0                          main         19 hours ago
 * aff213dfc548 oh-my-posh: Update to version 24.0.11                    main         19 hours ago
 * 4381c441fd41 mongodb-atlas-cli: Update to version 1.31.0              main         19 hours ago
 * 3137313b5665 meilisearch: Update to version 1.11.1                    main         19 hours ago
 * c9121b917944 kube-linter: Update to version 0.7.1                     main         19 hours ago
 * 4e4e94565aba flyway: Update to version 10.21.0                        main         19 hours ago
 * e435702c7ce4 eza: Update to version 0.20.7                            main         19 hours ago
 * 39e39ff4ff4a conan: Update to version 2.9.2                           main         19 hours ago
 * d75e146336e3 sucrose: Update to version 24.11.8.0                     extras       3 hours ago
 * 4f174203e392 propertree: Update to version 0.2024.11.08               extras       3 hours ago
 * 3c7b47eb7427 calibre: Update to version 7.21.0                        extras       3 hours ago
 * 1abd4f1a5469 calibre-normal: Update to version 7.21.0                 extras       3 hours ago
 * 2eef53d2ed10 vscode: Update to version 1.95.2                         extras       7 hours ago
 * 10c53d4cc95a slack: Update to version 4.41.97                         extras       7 hours ago
 * 68009ebb75c4 imdone: Update to version 1.47.0                         extras       7 hours ago
 * e77034876167 catalyst: Update to version 3.9.4                        extras       7 hours ago
 * 44d282f98c0e vivaldi: Update to version 7.0.3495.11                   extras       11 hours ago
 * 8d5f2dd1d9ca spicetify-themes: Update to version 2024-11-07T20.02.36  extras       11 hours ago
 * caa8efa08146 mediainfo-gui: Update to version 24.11                   extras       11 hours ago
 * eed254e2ff05 keyboard-chatter-blocker: Update to version 1.18         extras       11 hours ago
 * 326905adb97d kdenlive: Update to version 24.08.3                      extras       11 hours ago
 * 0c368b062630 innounpacker: Update to version 1.10.2                   extras       11 hours ago
 * fc32e1a143f2 innounpacker: Add version 1.10.0 (#14351)                extras       12 hours ago
 * 71b05c0c4556 tsukimi: Update to version 0.17.0                        extras       15 hours ago
 * ff1d5327a704 sysgauge: Update to version 11.3.12                      extras       15 hours ago
 * a55f30e96d3a metasploit-framework: Update to version 6.4.36-2024110.. extras       15 hours ago
 * 3200d117217e hoppscotch: Update to version 24.10.1-0                  extras       15 hours ago
 * e85e0521fc6e rustrover: Update to version 2024.2.5-242.23726.162      extras       19 hours ago
 * e1116bd690a9 joplin: Update to version 3.1.23                         extras       19 hours ago
 * 51a6514675ff gsmartcontrol: Update to version 2.0.0                   extras       19 hours ago
 * 0c4fa37f298c gitextensions: Update to version 5.1.0.17965             extras       19 hours ago
 * 943af0b11883 android-messages@5.5.0: Fix hash (Closes #14371)         extras       19 hours ago
Scoop was updated successfully!
WARN  Purging previous failed installation of gimp.
ERROR 'gimp' isn't installed correctly.
Removing older version (2.10.38-1).
'gimp' was uninstalled.
Installing 'gimp' (2.10.38-1) [64bit] from 'extras' bucket
Loading gimp-2.10.38-setup-1.exe from cache
Checking hash of gimp-2.10.38-setup-1.exe ... ok.
Extracting gimp-2.10.38-setup-1.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\DSMVG\scoop\apps\gimp\2.10.38-1\gimp-2.10.38-setup-1.exe.
Log file:
  ~\scoop\apps\gimp\2.10.38-1\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=gimp%402.10.38-1%3a+decompress+error
PS C:\Users\DSMVG>

**Comment by Daviteusz** [comment]
Can not reproduce. To solve your issue:
```
scoop update innounp
```

**Comment by shenka** [comment]
Thank you! It works!

PS C:\Users\DSMVG> scoop update innounp
Updating Scoop...
Updating Buckets...
 * 4da3358f7aef luau-lsp: Update to version 1.35.0                       main         76 minutes ago
 * 2f11972cc491 fzf: Update to version 0.56.1                            main         76 minutes ago
 * e8a912dc839b deno: Update to version 2.0.6                            main         9 hours ago
 * 80ca63233f54 tree-sitter: Update to version 0.24.4                    main         13 hours ago
 * 5994176b47a6 openssh: Update to version 9.8.1.0p1                     main         13 hours ago
 * 3bc1d429a902 openssh: Update to version 9.8.0.0p1 (#6239)             main         15 hours ago
 * a365349dff81 tflint: Update to version 0.54.0                         main         21 hours ago
 * 576f459eebb1 imagemagick: Update to version 7.1.1-40                  main         21 hours ago
 * bc1c0593ef4b imagemagick-lean: Update to version 7.1.1-40             main         21 hours ago
 * 7f9c400bb072 dbmate: Update to version 2.22.0                         main         21 hours ago
 * 5427c744bb12 chezmoi: Update to version 2.54.0                        main         21 hours ago
 * d0aabb30160e cc65: Update to version 11758771506                      main         21 hours ago
 * d3f48fe6d9d9 sqlcl: Update to version 24.3.1.311.1631                 main         25 hours ago
 * 2efcf1b656a6 ruby: Update to version 3.3.6-2                          main         29 hours ago
 * c2d866611732 oxlint: Update to version 0.11.1                         main         29 hours ago
 * addd87008038 ov: Update to version 0.37.0                             main         29 hours ago
 * 26f4692c3366 oh-my-posh: Update to version 24.2.2                     main         29 hours ago
 * b0af53a6a9d9 cargo-binstall: Update to version 1.10.12                main         29 hours ago
 * f244eb73a7cf ghq: Update to version 1.7.1                             main         33 hours ago
 * 6854e7b4f4f2 luau: Update to version 0.651                            main         2 days ago
 * a4175fcf5a63 ghq: Update to version 1.7.0                             main         2 days ago
 * 41c964e96016 dynamorio: Update to version 11.0.20034                  main         2 days ago
 * c51bc2f7df7c uv: Update to version 0.5.1                              main         2 days ago
 * 425d8a61642e red: Update to version 08nov24                           main         2 days ago
 * 9b52eda19d38 red-view: Update to version 08nov24                      main         2 days ago
 * c42e440a40e1 red-toolchain: Update to version 08nov24                 main         2 days ago
 * 58d917f98e44 ollama: Update to version 0.4.1                          main         2 days ago
 * 171b50fa260b kind: Update to version 0.25.0                           main         2 days ago
 * a71cc3e74064 jx: Update to version 3.10.182                           main         2 days ago
 * 10e101f9aa41 gitql: Update to version 0.30.0                          main         2 days ago
 * 3abe0d538e51 dagger: Update to version 0.14.0                         main         2 days ago
 * a84f5bafccb1 croc: Update to version 10.1.0                           main         2 days ago
 * 921be0ea0137 aws: Update to version 2.19.4                            main         2 days ago
 * bf51920162e0 wstunnel: Update to version 10.1.6                       main         2 days ago
 * cf1c16176e63 typos: Update to version 1.27.3                          main         2 days ago
 * 27600c658e72 restic: Update to version 0.17.3                         main         2 days ago
 * 8ebf5f646dfa ispc: Update to version 1.25.3                           main         2 days ago
 * 9dbe5b038c54 coursier: Update to version 2.1.17                       main         2 days ago
 * db93ba6bee11 terragrunt: Update to version 0.68.9                     main         2 days ago
 * 3b52b9ee38ab oh-my-posh: Update to version 24.2.1                     main         2 days ago
 * e9661056f538 nomad: Update to version 1.9.2                           main         2 days ago
 * b55de4fa9e9d jx: Update to version 3.10.181                           main         2 days ago
 * b1b99b6d38e0 hcloud: Update to version 1.49.0                         main         2 days ago
 * f295e3737252 atmos: Update to version 1.101.0                         main         2 days ago
 * 0b56280b7eb6 ruff: Update to version 0.7.3                            main         2 days ago
 * 70ef323a92f0 p4: Update to version 2024.2-2675662                     main         2 days ago
 * ee9c4470e1ce mailpit: Update to version 1.21.2                        main         2 days ago
 * 6fafca2e2ef6 git-machete: Update to version 3.31.0                    main         2 days ago
 * b8c971f4edb8 aws-sam-cli@1.127.0: Fix extraction (Close #5653)        main         2 days ago
 * d868cefba0ca aws-sam-cli@1.127.0: Fix extraction (Close #4980)        main         2 days ago
 * 9175c66e6db4 saber: Update to version 0.25.2                          extras       73 minutes ago
 * 25d0411b8a6a miru: Update to version 5.5.7                            extras       73 minutes ago
 * 0d9ce6e4bc55 ffmpeg-batch: Update to version 3.1.0                    extras       73 minutes ago
 * e644f788358e msiafterburner@4.6.5: Fix install (#14251)               extras       3 hours ago
 * be8f24e556be riff: Update to version 3.3.7                            extras       5 hours ago
 * 1e9f703f7ed7 reqable: Update to version 2.29.0                        extras       5 hours ago
 * e4968a5d67e9 doublecmd: Update to version 1.1.20                      extras       5 hours ago
 * 949763b98003 treesheets: Update to version 11763373864                extras       9 hours ago
 * b2861cb55737 jackett: Update to version 0.22.902                      extras       9 hours ago
 * 0dd4e6a0fc4e mpv-git: Update to version 20241110                      extras       13 hours ago
 * 0bdd6ccf7968 win10_brightnessslider: Update to version 1.8.11         extras       17 hours ago
 * ef672238b0ca stirling-pdf: Update to version 0.32.0                   extras       17 hours ago
 * 4883e94ca21e mtuner: Update to version 4.8.1                          extras       17 hours ago
 * 08881b54a511 grasshopper: Update to version 1.3.1                     extras       17 hours ago
 * 96486dd0301c determined: Update to version 0.35.1                     extras       17 hours ago
 * 2bb5ee64a148 win10_brightnessslider: Update to version 1.8.10         extras       21 hours ago
 * b573d6d43d12 librewolf: Update to version 132.0.1-1                   extras       21 hours ago
 * 7aa89cba7b8a ungoogled-chromium: Update to version 130.0.6723.116-1.1 extras       24 hours ago
 * 48f675373f98 stranslate: Update to version 1.2.7.1110                 extras       24 hours ago
 * 08f43ac1c8e8 sirikali: Update to version 1.7.0                        extras       24 hours ago
 * e3dbaaa0d896 skype: Update to version 8.131.0.202, fix checkver       extras       24 hours ago
 * 781fc936fc93 deltachat: Update to version 1.48.0, fix autoupdate      extras       25 hours ago
 * 54f4f953405b joplin: Update to version 3.1.24                         extras       25 hours ago
 * f8a25c823b67 altair: Update to version 8.0.2                          extras       25 hours ago
 * 77b23e2651a5 vscodium: Update to version 1.95.2.24313                 extras       29 hours ago
 * dfeb0177d5f9 flclash: Update to version 0.8.67                        extras       29 hours ago
 * 82c683701c05 netron: Update to version 8.0.0                          extras       33 hours ago
 * 23a9a8e7511c mediainfo-gui: Update to version 24.11.1                 extras       33 hours ago
 * c0538cd089cd jackett: Update to version 0.22.898                      extras       33 hours ago
 * c21cb258e8e4 gitextensions: Update to version 5.1.1.17970             extras       33 hours ago
 * 1385cc9672d2 dolphin: Update to version 24.12-4780                    extras       2 days ago
 * 89b8502a31b4 treesheets: Add version 11693219263 (#14357)             extras       2 days ago
 * aa448af5205a onecommander: Update version to 3.91.1.0 (#14370)        extras       2 days ago
 * 623de8d5bd94 openai-translator@0.4.33: Update github urls & license   extras       2 days ago
 * 670be62cd422 openai-translator@0.4.33: Fix shortcut (#14381)          extras       2 days ago
 * 06a491f83f6e perfview: Update to version 3.1.17                       extras       2 days ago
 * 3267954d1df1 ollama-full: Update to version 0.4.1                     extras       2 days ago
 * 103313009989 qownnotes: Update to version 24.11.1                     extras       2 days ago
 * b106e4805641 picpick: Update to version 7.2.9                         extras       2 days ago
 * 92e6213bbea9 fork: Update to version 2.2.3                            extras       2 days ago
 * 1ddbc2849eb9 basecamp: Update to version 2.3.17                       extras       2 days ago
 * c2e0d2fbce86 sqlitespy: Update to version 1.9.26                      extras       2 days ago
 * 1705d5c2181f pritunl-client: Update to version 1.3.4075.60            extras       2 days ago
 * 9ac407aee41d q-dir: Update to version 11.88                           extras       2 days ago
 * 4c6ca1494897 postman: Update to version 11.19.0                       extras       2 days ago
 * cde2d41bd2c0 kcc: Update to version 6.2.2                             extras       2 days ago
 * 911f244f05b9 jackett: Update to version 0.22.893                      extras       2 days ago
 * 9fded13d8da2 gitbutler: Update to version 0.13.13                     extras       2 days ago
 * b6d0ec9b7723 binance: Update to version 1.54.1                        extras       2 days ago
 * 78c59f7fddf4 appflowy: Update to version 0.7.3                        extras       2 days ago
Scoop was updated successfully!
innounp: 0.50 -> 1.76
Updating one outdated app:
Updating 'innounp' (0.50 -> 1.76)
Downloading new version
innounp-1.zip (518,6 KB) [====================================================================================] 100%
Checking hash of innounp-1.zip ... ok.
Uninstalling 'innounp' (0.50)
Removing shim 'innounp.shim'.
Removing shim 'innounp.exe'.
Unlinking ~\scoop\apps\innounp\current
Installing 'innounp' (1.76) [64bit] from 'main' bucket
Loading innounp-1.zip from cache
Extracting innounp-1.zip ... done.
Linking ~\scoop\apps\innounp\current => ~\scoop\apps\innounp\1.76
Creating shim for 'innounp'.
'innounp' (1.76) was installed successfully!

PS C:\Users\DSMVG>  scoop install extras/gimp
WARN  Purging previous failed installation of gimp.
ERROR 'gimp' isn't installed correctly.
Removing older version (2.10.38-1).
'gimp' was uninstalled.
Installing 'gimp' (2.10.38-1) [64bit] from 'extras' bucket
Loading gimp-2.10.38-setup-1.exe from cache
Checking hash of gimp-2.10.38-setup-1.exe ... ok.
Extracting gimp-2.10.38-setup-1.exe ... done.
Running installer script...done.
Linking ~\scoop\apps\gimp\current => ~\scoop\apps\gimp\2.10.38-1
Creating shim for 'gimp-console-2.10'.
Creating shim for 'gimp-console'.
Creating shim for 'gimp'.
Creating shim for 'gimptool-2.0'.
Creating shim for 'gimptool'.
Creating shortcut for GIMP (gimp-2.10.exe)
'gimp' (2.10.38-1) was installed successfully!

**Comment by shenka** [comment]
Thank you! It Works!
