### ISSUE TITLE
[UPDATE] Update GlazeWM to v3.5.0

### ISSUE THREAD

**Issue by jeffersonbenson** [ScoopInstaller/Extras#14401]
# Name
GlazeWM

## Current version in Extras
v2.1.1

## Current upstream version
v3.5.0

## URL to download
https://github.com/glzr-io/glazewm/releases/download/v3.5.0/glazewm-v3.5.0.exe

## SHA-256 Hash of File
426fc9a4e3c60b09cbfd63bd1acbcec2bb050157

**Comment by nukhes** [comment]
Hello, I was investigating this but I couldn't solve the problem properly, currently the installer of this program strictly requires administrator permissions, which makes it pointless to build a manifest for it, you can request this software in some bucket that accepts programs that escape the central premise of Scoop which is to install everything only in the current user.

**Comment by dillacorn** [comment]
Certaintly there is a solution for this? I've had to run scoop to install software that required administrative privileges before..

**Comment by LeoAdL** [comment]
This solution worked for me: https://github.com/glzr-io/glazewm/issues/645#issuecomment-2488978386

**Comment by dillacorn** [comment]
after a few revisions here is the finalized `glazewm.json` that works with both `x64` and `arm64` systems: https://github.com/glzr-io/glazewm/issues/645#issuecomment-2489396754

please commit [glazewm.json](https://github.com/ScoopInstaller/Extras/blob/master/bucket/glazewm.json)

**Comment by aliesbelik** [comment]
#13963, #14112
