### ISSUE TITLE
vscode@1.96.0-insider: download via aria2 failed

### ISSUE THREAD

**Issue by s0racat** [ScoopInstaller/Extras#14427]

**Comment by Miqueas** [comment]
The latest stable is still 1.95.3, idk why the manifest was changed, the version clearly says insider, that's a whole another channel 🤔

**Comment by mattcargile** [comment]
Yes, I would expect _insiders_ version to be installed from the `versions` bucket.

**Comment by aliesbelik** [comment]
Fixed by 5e481d29e.

**Comment by TheLastZombie** [comment]
It broke again: 6d1418c522d05ab36804934bf49b77db3eaab7d1

**Comment by s0racat** [comment]
shoud i reopen this issue?

**Comment by TheLastZombie** [comment]
I guess so. Not sure if maintainers get notifications regarding closed issues.

**Comment by s0racat** [comment]
I reopened this issue

**Comment by Skylark13** [comment]
Looks like it got re-updated (downgraded?) to 1.95.3 (1.96.0-insider at 7:34 AM EST, 1.95.3 at 9:28 AM EST)
https://github.com/ScoopInstaller/Extras/commit/a1885dd67e321c5e4709afd47410bafda25b4068
Is it just ping-ponging between versions at this point?

**Comment by as000fm** [comment]
When back to not working version 1.96.0-insider _just an hour ago..._
Why this version is in the Extra bucket instead of being in the Version bucket **only**?

**Comment by OPVL** [comment]
+1
