### ISSUE TITLE
vscode@1.96.0-insider: download via aria2 failed

### ISSUE THREAD

**Issue by esidav** [ScoopInstaller/Extras#14439]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://update.code.visualstudio.com/1.96.0-insider/win32-x64-archive/stable#/dl.7z
    referer=https://update.code.visualstudio.com/1.96.0-insider/win32-x64-archive/stable#/
    dir=C:\Users\<username>\scoop\cache
    out=vscode#1.96.0-insider#f1b08a7.7z

ERROR & 'C:\Users\Kouhei\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\<username>\scoop\cache\vscode.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=15304 --continue --summary-interval=0 --auto-save-interval=1

**Comment by aliesbelik** [comment]
Fixed by bot in 90ce402.
