### ISSUE TITLE
mpc-hc@1.7.13: download via aria2 failed

### ISSUE THREAD

**Issue by kaichuan** [ScoopInstaller/Extras#14451]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://binaries.mpc-hc.org/MPC%20HomeCinema%20-%20x64/MPC-HC_v1.7.13_x64/MPC-HC.1.7.13.x64.7z
    referer=https://binaries.mpc-hc.org/MPC%20HomeCinema%20-%20x64/MPC-HC_v1.7.13_x64/
    dir=D:\scoop\cache
    out=mpc-hc#1.7.13#4caca62.7z

ERROR & 'D:\scoop\apps\aria2\current\aria2c.exe' --input-file='D:\scoop\cache\mpc-hc.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https
--min-tls-version=TLSv1.2 --stop-with-process=79444 --continue --summary-interval=0 --auto-save-interval=1 --all-proxy='127.0.0.1:7890'

**Comment by aliesbelik** [comment]
Switched to [github release binaries](https://github.com/mpc-hc/mpc-hc/releases/tag/1.7.13).
