### ISSUE TITLE
musicbee@3.5.8698: download via aria2 failed

### ISSUE THREAD

**Issue by ko-ic** [ScoopInstaller/Extras#14486]
I tried to install musicbee via scoop, but the error occured bellow.
-------------
ERROR Download failed! (Error 3) Resource was not found
ERROR https://files1.majorgeeks.com/10afebdbffcd4742c81a3cb0f6ce4092156b4375/multimedia/MusicBeePortable_3_5.zip
    referer=https://files1.majorgeeks.com/10afebdbffcd4742c81a3cb0f6ce4092156b4375/multimedia/
    dir=D:\Applications\Scoop\cache
    out=musicbee#3.5.8698#5990688.zip

ERROR & 'D:\Applications\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Applications\Scoop\cache\musicbee.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=16272 --continue --summary-interval=0 --auto-save-interval=1

**Comment by CryoTheRenegade** [comment]
Looks like majorgeeks moved it? I'll look for an alternative link.
