### ISSUE TITLE
qutebrowser@3.3.1: hash check failed

### ISSUE THREAD

**Issue by andreaskundig** [ScoopInstaller/Extras#14544]
andre@snefrou MSYS ~/workspace/bouboucle/packages/looper-ui-custom-element (main)
$ scoop install qutebrowser
WARN  Purging previous failed installation of qutebrowser.
ERROR 'qutebrowser' isn't installed correctly.
Removing older version (3.3.1).
'qutebrowser' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'qutebrowser' (3.3.1) [64bit] from 'extras' bucket
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 156bee|OK  |   3.8MiB/s|C:/Users/andre/scoop/cache/qutebrowser#3.3.1#619c6ab.zip
Download: Status Legend:
Download: (OK):download completed.
Get-Content: C:\Users\andre\scoop\apps\scoop\current\lib\core.ps1:1376
Line |
1376 |          return Get-Content $file -AsByteStream -TotalCount 8
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation did not complete successfully because the file contains a virus or potentially unwanted software. :
     | 'C:\Users\andre\scoop\cache\qutebrowser#3.3.1#619c6ab.zip'

Checking hash of qutebrowser-3.3.1-windows-standalone.zip ... Get-FileHash: C:\Users\andre\scoop\apps\scoop\current\lib\install.ps1:634
Line |
 634 |      $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T …
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation did not complete successfully because the file contains a virus or potentially unwanted software. :
     | 'C:\Users\andre\scoop\cache\qutebrowser#3.3.1#619c6ab.zip'

InvalidOperation: C:\Users\andre\scoop\apps\scoop\current\lib\install.ps1:634
Line |
 634 |      $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Get-Content: C:\Users\andre\scoop\apps\scoop\current\lib\core.ps1:1376
Line |
1376 |          return Get-Content $file -AsByteStream -TotalCount 8
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation did not complete successfully because the file contains a virus or potentially unwanted software. :
     | 'C:\Users\andre\scoop\cache\qutebrowser#3.3.1#619c6ab.zip'

ERROR Hash check failed!
App:         extras/qutebrowser
URL:         https://github.com/qutebrowser/qutebrowser/releases/download/v3.3.1/qutebrowser-3.3.1-windows-standalone.zip
First bytes:
Expected:    2258c38cd86d8cb505ed58c8b57aa1e0f6335b32151f97ea05bb9cdee314ee73
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=qutebrowser%403.3.1%3a+hash+check+failed

**Comment by aliesbelik** [comment]
> | Operation did not complete successfully because the file contains a virus or potentially unwanted software. :
| 'C:\Users\andre\scoop\cache\qutebrowser#3.3.1#619c6ab.zip'

https://github.com/ScoopInstaller/Extras/issues/14538#issuecomment-2527597005
