### ISSUE TITLE
ccleaner@6.31.11415: hash check failed

### ISSUE THREAD

**Issue by rodgui** [ScoopInstaller/Extras#14557]
ccleaner: 6.30.11385 -> 6.31.11415
nodejs: 23.3.0 -> 23.4.0
Updating 2 outdated apps:
Updating 'ccleaner' (6.30.11385 -> 6.31.11415)
Downloading new version
ccsetup631.zip (76,3 MB) [====================================================================================] 100%
Checking hash of ccsetup631.zip ... Get-FileHash: C:\Users\XXX\scoop\apps\scoop\current\lib\install.ps1:634
Line |
 634 |      $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T …
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Não foi possível concluir a operação com êxito porque o arquivo contém um vírus ou software possivelmente
     | indesejado. : 'C:\Users\XXXX\scoop\cache\ccleaner#6.31.11415#d694d67.zip'
InvalidOperation: C:\Users\XXXX\scoop\apps\scoop\current\lib\install.ps1:634
Line |
 634 |      $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
Get-Content: C:\Users\XXXX\scoop\apps\scoop\current\lib\core.ps1:1376
Line |
1376 |          return Get-Content $file -AsByteStream -TotalCount 8
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Não foi possível concluir a operação com êxito porque o arquivo contém um vírus ou software possivelmente
     | indesejado. : 'C:\Users\XXXXX\scoop\cache\ccleaner#6.31.11415#d694d67.zip'
ERROR Hash check failed!
App:         extras/ccleaner
URL:         https://download.ccleaner.com/portable/ccsetup631.zip
First bytes:
Expected:    b46536583aeb52000a5caef55e6a0b0dc05bfc93841bb08d59049ad919fe7ad3
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=ccleaner%406.31.11415%3a+hash+check+failed

**Comment by elisimpson** [comment]
I have this issue too. Windows Security is removing the file for some reason so the hash check fails.
