### ISSUE TITLE
Notepad++: add autoCompletion folder and userDefineLang.xml to persist

### ISSUE THREAD

**Issue by zhaocai** [ScoopInstaller/Extras#1579]
https://github.com/lukesampson/scoop-extras/blob/10e5f2c568cf6f201cc1294080c1e572277699b5/notepadplusplus.json#L18

For example: [jNizM/ahk_notepad-plus-plus: Setup Notepad++ for AutoHotkey](https://github.com/jNizM/ahk_notepad-plus-plus)

1. User defined Syntax-Highlighting is added to `userDefineLang.xml`
2. autocomplete file `AutoHotkey.xml` is placed in `autoCompletion` folder

**Comment by gothicx** [comment]
The file userDefineLang.xml is already in persist. The AutoHotkey.xml is more difficult as the persist only covers the whole folder and not a single file inside a folder.

**Comment by gothicx** [comment]
I have tested this and the file userDefineLang_AHK.xml should be stored inside the folder userDefineLangs and the AutoHotkey.xml should be stored inside plugins\APIs. You can close this issue.
