### ISSUE TITLE
How to bundle regkeys with beyondcompare

### ISSUE THREAD

**Issue by f0ff886f** [ScoopInstaller/Extras#1645]
Beyond Compare is very useful due to the Explorer context options it adds (Select as "Left" for file compare), etc.

The program has an option to by default integrate itself into the Explorer shell menu, but it seems broken with the 64bit version of Beyond Compare.

The reason is that in the key `Computer\HKEY_CURRENT_USER\Software\Classes\CLSID\{57FA2D12-D22D-490A-805A-5CB48E84F12A}\InProcServer32` Beyond Compare by default adds the path to the `BCShellEx.dll` file, whereas `BCShellEx64.dll` is required instead.

Is it possible to bundle a regkey that users can double click to install BC4 to the explorer (similar to the functionality of TortoiseSVN)? Or to download two source files, since ScooterSoft distributes a fix for the issue here: https://www.scootersoftware.com/BC4ShellExFix.zip but it needs to have the path modified to support the scoop path.

**Comment by MathewBlock** [comment]
I've just made some recent changes to the vscode associations so if no one is looking at this any longer I'm happy to do the work.

**Comment by rashil2000** [comment]
This thread seems to be inactive for quite some time.

Please go ahead @MathewBlock :)
