### ISSUE TITLE
portable-virtualbox install error

### ISSUE THREAD

**Issue by nickcorona** [ScoopInstaller/Extras#1655]
Installing 'portable-virtualbox' (6.4.10) [64bit]
Loading Portable-VirtualBox_v5.1.22-Starter_v6.4.10-Win_all.exe from cache
Checking hash of Portable-VirtualBox_v5.1.22-Starter_v6.4.10-Win_all.exe ... ok.
Loading VirtualBox-5.1.22-115126-Win.exe from cache
Checking hash of VirtualBox-5.1.22-115126-Win.exe ... ok.
Loading Oracle_VM_VirtualBox_Extension_Pack-5.1.22-115126.vbox-extpack from cache
Checking hash of Oracle_VM_VirtualBox_Extension_Pack-5.1.22-115126.vbox-extpack ..
. ok.
Extracting dl.7z ... done.
Linking ~\scoop\apps\portable-virtualbox\current => ~\scoop\apps\portable-virtualb
ox\6.4.10
Creating shim for 'Portable-VirtualBox'.
Can't shim 'Portable-VirtualBox.exe': File doesn't exist

**Comment by janpio** [comment]
I could actually install `portable-virtualbox` just fine:

```
PS C:\Users\Jan> scoop install portable-virtualbox
Installing 'portable-virtualbox' (6.4.10) [64bit]
Loading Portable-VirtualBox_v5.1.22-Starter_v6.4.10-Win_all.exe from cache
Checking hash of Portable-VirtualBox_v5.1.22-Starter_v6.4.10-Win_all.exe ... ok.
Loading VirtualBox-5.1.22-115126-Win.exe from cache
Checking hash of VirtualBox-5.1.22-115126-Win.exe ... ok.
Loading Oracle_VM_VirtualBox_Extension_Pack-5.1.22-115126.vbox-extpack from cache
Checking hash of Oracle_VM_VirtualBox_Extension_Pack-5.1.22-115126.vbox-extpack ... ok.
Extracting dl.7z ... done.
Linking ~\scoop\apps\portable-virtualbox\current => ~\scoop\apps\portable-virtualbox\6.4.10
Creating shim for 'Portable-VirtualBox'.
Creating shortcut for Portable VirtualBox (Portable-VirtualBox.exe)
'portable-virtualbox' (6.4.10) was installed successfully!
PS C:\Users\Jan>
```

**Comment by gothicx** [comment]
No problem for me either.

**Comment by AyoungDukie** [comment]
Just a note, there appears to be an issue with the default download location URL (maybe certificate related?)
![image](https://user-images.githubusercontent.com/5449443/85787862-0af30780-b6fa-11ea-9aec-06668891a7aa.png)

While updating the URL in portable-virtualbox.json file to point to the link referenced on the homepage "https://www.vbox.me/".... instead of "https://files.vbox.me/".... appears to resolve the issue
