### ISSUE TITLE
[Request] Add Ghidra

### ISSUE THREAD

**Issue by NatoBoram** [ScoopInstaller/Extras#1814]
* https://www.nsa.gov/resources/everyone/ghidra/
* https://ghidra-sre.org/
* https://github.com/NationalSecurityAgency/ghidra

It's a stand-alone decompiler. Uses Java 11+.

**Comment by TheCjw** [comment]
ghidra has been added to [scoop-retools](https://github.com/TheCjw/scoop-retools).

You can use the following commands to install ghidra:

```bash
scoop bucket add retools https://github.com/TheCjw/scoop-retools.git
scoop install ghidra
```
