### ISSUE TITLE
[Request] Add SyncToy

### ISSUE THREAD

**Issue by NamelessUzer** [ScoopInstaller/Extras#2073]
SyncToy 2.1 is a free application that synchronizes files and folders between locations. Typical uses include sharing files, such as photos, with other computers and creating backup copies of files and folders.

Website:
http://microsoft.com/download/en/details.aspx?id=15155

**Comment by NatoBoram** [comment]
> Website:
> http://microsoft.com/download/en/details.aspx?id=15155

404

**Comment by ssfjhh** [comment]
> > Website:
> > http://microsoft.com/download/en/details.aspx?id=15155
> 
> 404

Shit. M$ removed synctoy from its site.  I'm sure the url is available before.
![image](https://user-images.githubusercontent.com/5350867/110562606-cffc0b80-8184-11eb-8240-7c7ae2d06a94.png)
