### ISSUE TITLE
Doublecmd .msi instead portable edition?

### ISSUE THREAD

**Issue by rpinolf** [ScoopInstaller/Extras#2181]
This is not an issue itself but an observation. Since doublecmd has a portable zipped version would not be better to use that rather using the regular msi, unpacking, etc.?

Benefit here would be that portable edition stores config files in the portable app directorty instead than in the roaming profile (as the regular .msi does this by default).

Changing installation from .msi to the .zip edition would require to preserve some files in the portable app when updating but I think this is something scoop does in the manifests.

Thanks,
Ricard

**Comment by hoilc** [comment]
It seems that Doublecmd does't recognize hard-linked config files.

By the time persistence rework (https://github.com/lukesampson/scoop/pull/3212) is done, we could switch the manifest to portable version.

**Comment by goyalyashpal** [comment]
what's the status of this issue?

**Comment by goyalyashpal** [comment]
* i have created 2 manifests locally:
* one for the dev releases, and other for snapshot builds.
* both are using the portable package i.e. `*.zip` for dev, and `*.7z` for snapshot
* both seem to be working fine with the `"persist": "settings"`
* so, i think the move should be made now... i'll be happy to provide a pr if that's wanted.
