### ISSUE TITLE
Alacritty configuration

### ISSUE THREAD

**Issue by Zumochi** [ScoopInstaller/Extras#2430]
Alacritty on Windows automatically creates its configuration file in `%APPDATA%\alacritty\alacritty.yml`. To make it persistent and portable in a scoop fashion, this should probably be made into a persisting file.

Fortunately, alacritty has a parameter to configure the location of this file:

    --config-file <config-file>
        Specify alternative configuration file [default: $XDG_CONFIG_HOME/alacritty/alacritty.yml]

**Comment by Luckz** [comment]
So a future `alacritty-portable` would always have to be launched with that parameter?

**Comment by Zumochi** [comment]
That is also an option, and in which case, yes.

**Comment by nixpulvis** [comment]
Technically alacritty shouldn't need a config file to load the defaults. So depending on your intentions it could be possible to avoid a config altogether.

**Comment by CGMossa** [comment]
Yeah, this is still an issue.

**Comment by rashil2000** [comment]
Would you be able to send a fix?

**Comment by Gleydar** [comment]
Hi, I'm currently in the process of (hopefully) fixing this. This is my first contribution to scoop, so I'm sorry if it takes a while
