### ISSUE TITLE
Maybe we need to dismiss this version of firefox-beta

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Extras#2796]
Maybe we need to dismiss this version of firefox-beta. It's a candidate version which is in another directory https://archive.mozilla.org/pub/firefox/candidates/ .  https://download.mozilla.org/?product=firefox-beta-latest&os=win&lang=en-US will be redirected to 69.0b16, so 69.0b16 is the latest beta version.
We can download all beta version from https://archive.mozilla.org/pub/firefox/candidates/ . But url for 69.0build2 is https://archive.mozilla.org/pub/firefox/candidates/69.0-candidates/build2/... while url for 69.0b16 is https://archive.mozilla.org/pub/firefox/candidates/69.0b16-candidates/build1/... . We need a page to match `build1`.
We can also use the url in https://aus5.mozilla.org/update/6/Firefox/60.0/_/WINNT_x86_64-msvc-x64/en-US/beta/_/_/_/_/update.xml . But it's a mar file which can't be unzip with 7zip. See https://wiki.mozilla.org/Software_Update:MAR .
Or we can checkver from https://download.mozilla.org/?product=firefox-beta-latest&os=win&lang=en-US if scoop can checkver from redirect url.

_Originally posted by @linsui in https://github.com/lukesampson/scoop-extras/issues/2308#issuecomment-526883136_

**Comment by linsui** [comment]
The response of https://aus5.mozilla.org/update/6/Firefox/60.0/_/WINNT_x86_64-msvc-x64/en-US/beta/_/_/_/_/update.xml 

```xml
<?xml version="1.0"?>
<updates>
    <update actions="showURL" appVersion="69.0" buildID="20190827005903" detailsURL="https://www.mozilla.org/en-US/firefox/69.0/releasenotes/" displayVersion="69.0" openURL="https://www.mozilla.org/en-US/firefox/69.0beta/whatsnew/?oldversion=%OLD_VERSION%" type="minor">
        <patch type="complete" URL="http://download.mozilla.org/?product=firefox-69.0build2-complete&amp;os=win64&amp;lang=en-US" hashFunction="sha512" hashValue="59ac5c86ff07310554b818e087fc89b258a01603293d62a2eaf7f981d50aecf8c2c8bc9ddad6de7049b1d2bd2460e6ecaea4fb5152e3c6c8ae7e289787ec2fb4" size="53212394"/>
    </update>
</updates>
```

**Comment by ratatoeey** [comment]
this is outdated. current firefox-beta is 71.0b5.

**Comment by asd-collab** [comment]
above comment is outdated. consider adding bot for that.

/close

# firefox-beta packge needs updating.

remove if package updates can't be automated. same for all scoop packages. 

tag as non-compliant for all packages that need coaxing to use them in scoop. look for popular cli packages, first.

---

asd-collab

**Comment by digitalentiert** [comment]
I have changed the checkver part in my own manifest to this:
```
    "checkver": {
        "url": "https://www.mozilla.org/de/firefox/all/",
        "regex": "<option value=\"desktop_beta\">([\\db.]+)"
    },
```
and it works like a chrm.
