### ISSUE TITLE
Un-deprecate Nightlies bucket?

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Extras#2821]
In my opinion, anything that has a version of “nightly”, or that updates daily, or more often, should live in the (currently unused) [nightlies](https://github.com/ScoopInstaller/Nightlies) bucket. I would think the following would be candidates to move there:

#### Main bucket:
1. [docker-nightly](https://github.com/ScoopInstaller/Main/search?q=docker-nightly&type=Commits)
1. [glslang-nightly](https://github.com/ScoopInstaller/Main/search?q=glslang-nightly&type=Commits)
1. [jar2app](https://github.com/ScoopInstaller/Main/search?q=jar2app&type=Commits)
1. [jx](https://github.com/ScoopInstaller/Main/search?q=jx&type=Commits)
1. [ffmpeg-nightly](https://github.com/ScoopInstaller/Main/search?q=ffmpeg-nightly&type=Commits)

#### Extras bucket:
1. [cheat-engine](https://github.com/lukesampson/scoop-extras/search?q=cheat-engine&type=Commits)
1. [firefox-nightly](https://github.com/lukesampson/scoop-extras/search?q=firefox-nightly&type=Commits)
1. [jdownloader](https://github.com/lukesampson/scoop-extras/search?q=jdownloader&type=Commits)
1. [lightshot](https://github.com/lukesampson/scoop-extras/search?q=lightshot&type=Commits)
1. [oneget](https://github.com/lukesampson/scoop-extras/search?q=oneget&type=Commits)
1. [rust-msvc-nightly](https://github.com/lukesampson/scoop-extras/search?q=rust-msvc-nightly&type=Commits)
1. [rust-nightly](https://github.com/lukesampson/scoop-extras/search?q=rust-nightly&type=Commits)
1. [uplay](https://github.com/lukesampson/scoop-extras/search?q=uplay&type=Commits)
1. [vscode-insiders](https://github.com/lukesampson/scoop-extras/search?q=vscode-insiders&type=Commits)
1. [vscode-insiders-portable](https://github.com/lukesampson/scoop-extras/search?q=vscode-insiders-portable&type=Commits)
1. [watchman-nightly](https://github.com/lukesampson/scoop-extras/search?q=watchman-nightly&type=Commits)

_Originally posted by @rasa in https://github.com/lukesampson/scoop-extras/pull/2814#issuecomment-528957813_

**Comment by niheaven** [comment]
I've asked in Discord, it's reasonable to use `nightlies`.

**Comment by rasa** [comment]
The other option would be to use the versions bucket, and name them all _app_-nightly.

**Comment by linsui** [comment]
Any update? I want to add a nightly app, but I don't know which bucket to use?

**Comment by rasa** [comment]
You could throw it in nightlies if you want. I think we are eventually going to need to trim down extras by spinning off select groups of apps, so might as well start now.

I would move forward on this idea, if a consensus formed.

**Comment by linsui** [comment]
I would like to do it. But Nightlies doesn't get automated updates...

**Comment by niheaven** [comment]
Yes, nightlies needn't autoupdate.

> I think we are eventually going to need to trim down extras by spinning off select groups of apps, so might as well start now.

We could make `extras` as meta bucket, that when user adds this bucket they actually adds several related sub-buckets. But why we need to trim down this bucket? A large one is difficult to clone, that's the only shortcoming, I thought. It is autoupdated by Excavator, and most manifests in it is well maintained.

**Comment by rasa** [comment]
My thought is that we may want to eventually break up extras into logical groups to allow us to divy up the maintenance. Perhaps we break it up like Debian does, and have free and non-free (non-open source) buckets. Or we could go even further, and have open (open-source), free (free but not open source), and non-free (shareware/proprietary).

**Comment by linsui** [comment]
Maybe some apps which use commit sha as version (for example, zeronet) should also be put in nightlies?

**Comment by pratikpc** [comment]
I personally think all new nightlies should be added exclusively to the nightlies bucket.

We can take a decision on whether to move or not based on what discussions we have here

@rasa views?

**Comment by rashil2000** [comment]
+1 from me

**Comment by rashil2000** [comment]
_From #7285:_

> If we are to revive it, we will need to transfer 8 manifests from the Main bucket, 3 (+1 this one) manifests from the Extras bucket and 2 manifests from the Versions bucket there

**Comment by pratikpc** [comment]
Not really

Firefox Nightly, Neovim Nightly, Vim Nightly and the 4 FFMPEG Nightly update via excavator.

Only glslang and Docker in main do not update automatically.

And only 2 Rust nightlys in extras are independent of excavator.

**Comment by rashil2000** [comment]
We will re-enable Excavator for Nightlies too, if and when it gets un-deprecated. There aren't a lot of apps there, so it won't be much of a problem.

**Comment by rasa** [comment]
> I personally think all new nightlies should be added exclusively to the nightlies bucket.
> 
> We can take a decision on whether to move or not based on what discussions we have here
> 
> @rasa views?

I completely agree. IMO, nighties should live in their own repo for two reasons:

1, They are by definition more unstable, and should therefore take extra effort to install.
2. Buckets should be limited to 1,000 packages, due to GitHub hard limit, so anything that shrinks a bucket's size should be supported.

**Comment by rashil2000** [comment]
Let's compile a list of transfers then, based on https://github.com/ScoopInstaller/Extras/issues/2821#issue-490708605 and the current contents of Main, Extras and Versions

**Comment by Lutra-Fs** [comment]
google-chrome-canary is a nightly version as well.

**Comment by rashil2000** [comment]
> Also, is vscode-insider a nightly version?

Yes, according to their wiki
