### ISSUE TITLE
No fonts in libreoffice-stable

### ISSUE THREAD

**Issue by angelog0** [ScoopInstaller/Extras#2824]
It seems that the `libreoffice-stable` package comes with a limited number of fonts. The [Portable Apps](https://portableapps.com/apps/office/libreoffice_portable) site suggests to add them from a zip package. I wonder if you can create a full stable package. TIA

**Comment by linsui** [comment]
I would like to change it to nonportable version in https://github.com/lukesampson/scoop-extras/pull/2809 because portable version is published a little later. I'm not sure is it a good idea.

**Comment by angelog0** [comment]
Hmm... upstream, what you call `stable` is really `portable` (in collaboration with Portable Apps, I think). They call `still' the stable version (which is nothing else that an old `fresh`).

BTW, could you explain how you install from `.msi.` (all `fresh` are in that format)? Just extract the `.msi` and create symlinks? or what else? TIA.

**Comment by linsui** [comment]
Scoop unpack msi with `lessmsi` .

> Hmm... upstream, what you call stable is really portable (in collaboration with Portable Apps, I think). They call still the stable version (which is nothing else that an old fresh).

Yeah, I know. They publish portable version along with stable version.

**Comment by angelog0** [comment]
@linsui wrote:
>
> Scoop unpack msi with lessmsi 

I see that unpacking the `.msi` for Libreoffice it creates the tree

```
SourceDir
    Fonts
    LibreOffice
        ....
    System64
        ....
```
So I tried

`
  C:\LibreOffice_6.3.2.2_Win_x64\SourceDir\LibreOffice\program\soffice.exe

`
but it sees only Windows fonts not its own fonts (in Fonts)...

**Comment by angelog0** [comment]
Just for completeness, usually I merge the last portable with the last MSI-x64 versions to get a portable x64 last version. After downloading the PAF and the MSI for Help-Lang and binaries, and unpacking them as `7z` and `msi` archives (dl.7z, dh.msi, dl.msi) :

```
echo -n " ===> Creating 'settings' and 'fonts' directories ... "
mkdir -p LibreOffice/Data/settings
mkdir -p dl/SourceDir/LibreOffice/share/fonts/truetype
echo "done."

echo "[LibreOfficePortableSettings]" > \
     LibreOffice/Data/settings/LibreOfficePortableSettings.ini

echo "InvalidPackageWarningShown=${release}" >> \
     LibreOffice/Data/settings/LibreOfficePortableSettings.ini

echo -n " ===> Cleaning 'Other' and '\$PLUGINSDIR' ... "
rm LibreOffice/{Other,\$PLUGINSDIR} -rf
echo "done."

mv dl/SourceDir/System64/* dl/SourceDir/LibreOffice/program/
rm dl/SourceDir/System64 -rf

## Synchronize folders
rsync -ac --delete dl/SourceDir/LibreOffice/ LibreOffice/App/libreoffice/

## DO NOT use '--delete'!
echo -n " ===> Installing the lang pack ... "
rsync -ac dh/SourceDir/LibreOffice/help/ LibreOffice/App/libreoffice/help/
echo "done."

echo -n " ===> Moving the fonts ... "
rsync -ac --delete dl/SourceDir/Fonts/ \
      LibreOffice/App/libreoffice/share/fonts/truetype/
echo "done."
```

Usually this is done with a bash script running in MSYS2 and the script cleans also all languages I will never use so that the installation is almost `multilingual standard`

With the fonts in `LibreOffice/Data/fonts`, LO starts very very slow! Instead with the fonts in `[...]/share/fonts/truetype` it starts normally, faster ... Maybe [people](https://portableapps.com/apps/office/libreoffice_portable) which suggests to install fonts in `Data\fonts` and which think that this is a bug from Win 10 anniversary edition should know this.
