### ISSUE TITLE
VS Code registers one file icon when installed via Scoop

### ISSUE THREAD

**Issue by dev-nicolaos** [ScoopInstaller/Extras#2882]
# Environment
```none
Windows Build: 10.0.18362.0
Current Scoop Version: 3e55a709
```

# Steps to Reproduce
Assuming scoop is installed, vs code is not, and the extras bucket has been added:
1. Run `scoop install vscode`
1. Run `$dir\\vscode-install-context.reg` to add VS Code as a context menu option
1. In Explorer, create a folder with various file types supported by VS Code
1. For each file:
- Select "Open With..."
- Find VS Code in the list of applications OR if it's not there, select "Look for another app on this PC" and browse to the VS Code executable in scoop
- Check the "Always use this app to open '.file-ext' files" box

# Current Behavior
Each file type uses the same VS code icon in Windows explorer
![image](https://user-images.githubusercontent.com/29005473/65578348-7e2cda80-df2a-11e9-9764-30405b12f23c.png)

# Expected Behavior
Each file type uses it's own icon, as described in the [October 2018 release notes](https://code.visualstudio.com/updates/v1_29#_updated-file-icons-per-file-type). This is the normal behavior when VS Code is installed normally rather than with Scoop.

**Comment by r15ch13** [comment]
https://github.com/microsoft/vscode/blob/e06678160f016e3063c687243a88fe13b5fb52aa/build/win32/code.iss#L101-L971

**Comment by ratatoeey** [comment]
just download https://github.com/microsoft/vscode/blob/e06678160f016e3063c687243a88fe13b5fb52aa/build/win32/code.iss, if its painful to read it omn github.

---
regards  ratatoeey

**Comment by dev-nicolaos** [comment]
@r15ch13 @ratatoeey 

Not being an expert in the details of Windows application installation process, my best guess is that the file you linked to runs during normal installations of VS Code and is responsible for associating VS code and it's icons with the relevant file types? (please correct me if this assumption is incorrect).

Two questions:
1. Are you suggesting that I run the relevant lines separately (post `scoop install`)? If so how would I do that?
2. Why isn't this file running during `scoop install`? Is there a way we can alter the config so it does? If not I imagine we'd have to repeat step 1 every time the icons were updated.


Thanks

**Comment by ratatoeey** [comment]
you don't have to read it. link was in case, you wanted to try to see what its contents are its easier to download.

which is hard to do, cause there no button on the page to download it.

---

I'm no expert either at Windows application installation. I have some trivia to share from Google for `read .iss files`  -> first result is https://fileinfo.com/extension/iss

it may be correct.


----

regards ratatoeey

**Comment by linsui** [comment]
Those code in iss shows registries related with file icons. You need to convert them to a reg file.

**Comment by ratatoeey** [comment]
from https://www.howtogeek.com/382727/what-is-a-reg-file-and-how-do-i-open-one/

A file with the .reg file extension is a Windows Registry file

**Comment by mrlg255** [comment]
Is there premade .reg file or is there some easy way to convert this code?

**Comment by fmod-mathew** [comment]
I just discovered this today and it makes me sad all my nice icons are gone since switching to scoop.

Has there been any progress on this issue? 
Or should I start working on a fix?

**Comment by phanirithvij** [comment]
@fmod-mathew any updates 😁?

**Comment by MathewBlock** [comment]
Yes, I do have an update.

This is my first GitHub contribution, switched account from my work account to my personal account since this was done in non-work time. Looking forward to getting this change in, please let me know if I missed anything.

**Comment by Douglasky** [comment]
Hello guys, I need help on this. Can anyone help?
![SharedScreenshot cm](https://github.com/ScoopInstaller/Extras/assets/138161012/788aa9f3-c80c-4f37-8b97-f98c182c11fc)

**Comment by Douglasky** [comment]
Also, how do I resolve these: couldn't find manifest for VSCODE, and couldn't find manifest for BITWARDEN
