### ISSUE TITLE
[Request] Add firefox eme-free

### ISSUE THREAD

**Issue by ghost** [ScoopInstaller/Extras#2938]
see https://github.com/lukesampson/scoop/issues/3660

latest version for 6 Oct is: https://ftp.mozilla.org/pub/firefox/releases/69.0.2/

**Comment by trip23app** [comment]
that 3660 issue needs to be closed.

**Comment by trip23app** [comment]
possible description could be "firefox with DRM-support disabled by default"
see https://hacks.mozilla.org/2014/05/reconciling-mozillas-mission-and-w3c-eme/

<hr>

autoupdate should be simple.

**Comment by kiedtl** [comment]
> they actually think powershell's long command names are verbose

Well, it is indeed verbose, if you compare `remove-item -r -fo $item` to `rm -rf item`
