### ISSUE TITLE
[Request] Add AudioFlyout

### ISSUE THREAD

**Issue by sandriaas** [ScoopInstaller/Extras#3142]
Replace the Volume/SMTC UI with a custom one.
https://github.com/ADeltaX/AudioFlyout

**Comment by issaclin32** [comment]
The manifest of **AudioFlyout** involves too many system tweaks, which will be hard to maintain.  I don't think it will be able to meet the criteria of the official buckets.

You can use this manifest if you want:
https://github.com/issaclin32/scoop-bucket/blob/master/bucket/audioflyout.json

**Comment by Cyberdroid1** [comment]
How about ModernFlyouts?
