### ISSUE TITLE
[Request] Add Build Tools for Visual Studio 2019

### ISSUE THREAD

**Issue by cmoisei** [ScoopInstaller/Extras#3159]
Would be nice to have the Microsoft C++ Compiler available.

Visit
https://visualstudio.microsoft.com/downloads/

Under All downloads/Tools for Visual Studio 2019/Build Tools for Visual Studio 2019 

"These Build Tools allow you to build Visual Studio projects from a command-line interface. Supported projects include: ASP.NET, Azure, C++ desktop, ClickOnce, containers, .NET Core, .NET Desktop, Node.js, Office and SharePoint, Python, TypeScript, Unit Tests, UWP, WCF, and Xamarin."

**Comment by outforpublic** [comment]
That would be hard since it is installed using the visual studio installer and has multiple add-ons.

**Comment by tratTalks** [comment]
wish @Microsoft would just help everyone that will have to deal with installing that package in a sane, configurable manner.

not doing that is pure sadism.

jokes aside, its just as expected of them. they are the only blockers for this and many other goodies for users and developers.

---

<details><summary>CLICK ME</summary>
<p>

#### aside:

if you want to let @Microsoft know the obvious. just go to https://visualstudio.microsoft.com/downloads/# and click on  the blue **Feedback** button on right side(ensure ad-block doesn't block or interfere with it, I had to disable 'ublock origin'). Rate the page 1 star. And give your feedback about the current situation. 

3 of my suggestions would be-
- installing **Build tools 2019** and 
- ask them to support **installation via scoop**
- and per-user installs like VSCode supports.

The more people make noise about it, the more incentive they will have. I hope.

Another approach would be to boycott their  tools. And use and encourage better tools. Unless users and developers unite to improve the ecosystem. But that is mostly a dream.

</p>
</details>

---

developers always have to wade in cesspools of crap. only to make these installers work in a sub-par manner.

hope you succeed despite all the challenges.
good luck! b(￣▽￣)d

---

cheers tratTalks

**Comment by Airkro** [comment]
How about just `Visual Studio Installer`

**Comment by Adriankhl** [comment]
I suspect this (https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019) may work.

Perhaps also consider this (https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/)

From what I have tested, you simply has to install the individual build tool component and Windows SDK. Then, export the proper `PATH, `LIB`, and `INCLUDE` variable to build c++ software.

**Comment by minonl** [comment]
This issue is actually duplicate with #1861

**Comment by rashil2000** [comment]
#1861
