### ISSUE TITLE
Nearest GNU mirror down for me, can't install emacs

### ISSUE THREAD

**Issue by mauricioralcala** [ScoopInstaller/Extras#3302]
Hi, 

I attempted to install emacs but the emacs.json in scoop-extras attempts to get the file from https://ftpmirror.gnu.org. The problem is that this server seems to fetch from the nearest mirror and in my case, this mirror has been down for a while. I could use a VPN, but the solucion should be a bit more elegant, either upstream from https://ftpmirror.gnu.org or from scoop itself.

**Comment by shytikov** [comment]
Same issue was for me. I would rather prefer to use main download location...
