### ISSUE TITLE
Chromium manifest is incorrectly installing Ungoogled Chromium

### ISSUE THREAD

**Issue by ghost** [ScoopInstaller/Extras#3473]
The Scoop manifest for Chromium is incorrectly installing Ungoogled Chromium.
This has been the case for the last 2 revisions. 

Please edit the manifest to the correct installation as this change has resulted in the browser crashing on startup when updated.

**Comment by bickman** [comment]
@kamiyubidan I use this Chromium for the first time and it doesn't work at all. I was going to check the manifest file and found your issue. Cool, responded so quickly .

**Comment by andselisk** [comment]
The issue is still there. `scoop install chromium` installs Ungoogled Chromium. There are two separate packages, `ungoogled-chromium` and `chromium`, but according to the manifest one can only install Ungoogled Chromium. This behavior makes no sense.

**Comment by kamiyubidan** [comment]
I just made a custom bucket pointing to the correct installation. There are instructions in the Scoop documentation on how to set this up. 

[chromium-hibbiki.json.txt](https://github.com/lukesampson/scoop-extras/files/4786209/chromium-hibbiki.json.txt)
