### ISSUE TITLE
[Request] Add httpie

### ISSUE THREAD

**Issue by kid1412621** [ScoopInstaller/Extras#3589]
https://github.com/jakubroztocil/httpie

**Comment by equinox** [comment]
Someone tried to PR it to the main bucket [here](https://github.com/ScoopInstaller/Main/pull/648), but I'm not sure what's happening with the PR.

**Comment by kid1412621** [comment]
@equinox awh, maybe it should locate in extra bucket?

**Comment by Restia666Ashdoll** [comment]
I dont know what happened myself. You can test it yourself with
`scoop install https://gist.githubusercontent.com/Restia666Ashdoll/147a46b3d8d7a91eb53c8c1c7824d9b7/raw/httpie.json`
I put it in the main bucket because it fulfills all the criteria. aria2 and wget are also in the main bucket.

**Comment by Restia666Ashdoll** [comment]
```
scoop bucket add python https://github.com/TheRandomLabs/Scoop-Python.git
scoop install httpie-py
```

**Comment by Vedabahu** [comment]
This issue is pretty old and is answered [here](https://github.com/ScoopInstaller/Main/pull/648#issuecomment-619765584).
So can @rashil2000 please close this issue.
