### ISSUE TITLE
[Request] Add Microsoft Teams

### ISSUE THREAD

**Issue by NatoBoram** [ScoopInstaller/Extras#3595]
Teams is Microsoft's latest chat app for business.

https://teams.microsoft.com/downloads

**Comment by Ash258** [comment]
Here you have manifest, but for some reason it is not working correctly when executed from linked `current` folder. YOu can test if you have same problem

```json
{
    "version": "1.3.00.362",
    "description": "Office 365's chats, meetings, files and apps together in one place",
    "homepage": "https://teams.microsoft.com/start",
    "license": "Freeware",
    "architecture": {
        "64bit": {
            "url": "https://statics.teams.microsoft.com/production-windows-x64/1.3.00.362/Teams-1.3.00.362-full.nupkg",
            "hash": "sha1:e340fb61e479e391f800d64708e5f4203206d9b0"
        },
        "32bit": {
            "url": "https://statics.teams.microsoft.com/production-windows/1.3.00.362/Teams-1.3.00.362-full.nupkg",
            "hash": "sha1:05d98d262d2349f5028012a8d3f97b356e54fe12"
        }
    },
    "extract_dir": "lib\\net45",
    "shortcuts": [
        [
            "Teams.exe",
            "Microsoft Teams"
        ]
    ],
    "checkver": {
        "url": "https://teams.microsoft.com/downloads/desktopurl?env=production&plat=windows&arch=x64&download=false",
        "regex": "/([\\d.]+)/Teams_windows_x64\\.exe"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://statics.teams.microsoft.com/production-windows-x64/$version/Teams-$version-full.nupkg"
            },
            "32bit": {
                "url": "https://statics.teams.microsoft.com/production-windows/$version/Teams-$version-full.nupkg"
            }
        },
        "hash": {
            "url": "$baseurl/RELEASES"
        }
    }
}

```

**Comment by FriendlyNeighborhoodShane** [comment]
@Ash258 it seems to work correctly here ATM (just updated your manifest to latest version with checkver).

**Comment by FriendlyNeighborhoodShane** [comment]
Also, it would be nice to add a Teams.exe shim.

**Comment by FriendlyNeighborhoodShane** [comment]
Oh nevermind, you are right. It is giving me a problem on a fresh install.

I didn't notice it because I uninstalled a normal install and then installed it with scoop, it didn't wipe its data files.

I just tried moving its data folder (`%APPDATA%\Microsoft\Teams`) and it dosen't show anything on launch anymore.

Maybe some data needs to be initialised, I will try to figure it out.

**Comment by FriendlyNeighborhoodShane** [comment]
@Ash258 I figured it out.

All we need to do in the install script it create a file `%APPDATA%\Microsoft\Teams\desktop-config.json` and write the following text into it:

```
{"isLoggedOut":false}
```

I tried it several times and it worked for me, I believe it should for you too. I think this discovery makes Teams ready for inclusion into the repository.

(This is, to rant, quite frankly terrible programming from the Teams devs. Can't imagine in how many situations it can easily go wrong)

**Comment by FriendlyNeighborhoodShane** [comment]
Actually it's a bit more complex than that, as I just realised. If you launch Teams without doing this, the program *will* create the json, but will not add this key, dumbly enough, and will stay stuck on the white screen.

Can powershell read JSON objects natively? If yes, this will be a big boon.

So what the install script needs to do is:

- If file exists and is a valid json object and contains the `isLoggedOut` key, do nothing
- Otherwise, delete the file and create a new one with just that single key.

**Comment by NatoBoram** [comment]
> Can powershell read JSON objects natively?

I think this should do it

* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-5.1
* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-5.1

**Comment by FriendlyNeighborhoodShane** [comment]
Soooo. I come back to this issue after like a year.

Around the time of my last comment, I tried to... kind of... abuse my workplace's teams license to get a support ticket in for this not-very-work-related issue, but it seems Microsoft is still Microsoft. Checked back in a while to no progress for a simple request where I did most of the digging and guessed a possible solution for (they probably missed an `os.realpath()` call where that key is to be created?).

So fed up, I looked at the weird thingamajig that powershell is and made a post-install to make it work in all cases (that I know).

This is the raw commented script:
```
#!powershell
# Microsoft Office Teams post_install script

# suppress all error messages
$ErrorActionPreference = "silentlycontinue"

# the file, the key, the value it should be set to
$file = ${env:APPDATA} + "\Microsoft\Teams\desktop-config.json"
$key = "isLoggedOut"
$val = $false

try {
  # the file must exist, be a valid JSON and not null
  $json = Get-Content $file | ConvertFrom-Json
  if ($json -eq $null) { throw }
} catch {
  # else start with a blank JSON object
  $json = "{}" | ConvertFrom-Json
}

if (!($json.$key -eq $val)) {
  # if the key is wrong or missing, set the key and write the object back
  New-Item -Force -Path $file -Type "file" | Out-Null
  $json | Add-Member -Force -MemberType "noteproperty" -Name $key -Value $val
  $json | ConvertTo-Json -Compress | Set-Content $file
}

```

This is the latest `checkver`'d JSON for the package, which I have tested to work:
```
{
    "version": "1.4.00.19572",
    "description": "Office 365's chats, meetings, files and apps together in one place",
    "homepage": "https://teams.microsoft.com/start",
    "license": "Freeware",
    "architecture": {
        "64bit": {
            "url": "https://statics.teams.microsoft.com/production-windows-x64/1.4.00.19572/Teams-1.4.00.19572-full.nupkg",
            "hash": "sha1:cdaea19972fe53466c2dfedc105e8b80812afde0"
        },
        "32bit": {
            "url": "https://statics.teams.microsoft.com/production-windows/1.4.00.19572/Teams-1.4.00.19572-full.nupkg",
            "hash": "sha1:90258712334485b893bfb373a0529954f403487d"
        }
    },
    "extract_dir": "lib\\net45",
    "bin": "Teams.exe",
    "shortcuts": [
        [
            "Teams.exe",
            "Microsoft Teams"
        ]
    ],
    "post_install": [
        "$ErrorActionPreference = \"silentlycontinue\"",
        "$file = ${env:APPDATA} + \"\\Microsoft\\Teams\\desktop-config.json\"",
        "$key = \"isLoggedOut\"",
        "$val = $false",
        "try {",
        "  $json = Get-Content $file | ConvertFrom-Json",
        "  if ($json -eq $null) { throw }",
        "} catch {",
        "  $json = \"{}\" | ConvertFrom-Json",
        "}",
        "if (!($json.$key -eq $val)) {",
        "  New-Item -Force -Path $file -Type \"file\" | Out-Null",
        "  $json | Add-Member -Force -MemberType \"noteproperty\" -Name $key -Value $val",
        "  $json | ConvertTo-Json -Compress | Set-Content $file",
        "}"
    ],
    "checkver": {
        "url": "https://teams.microsoft.com/downloads/desktopurl?env=production&plat=windows&arch=x64&download=false",
        "regex": "/([\\d.]+)/Teams_windows_x64\\.exe"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://statics.teams.microsoft.com/production-windows-x64/$version/Teams-$version-full.nupkg"
            },
            "32bit": {
                "url": "https://statics.teams.microsoft.com/production-windows/$version/Teams-$version-full.nupkg"
            }
        },
        "hash": {
            "url": "$baseurl/RELEASES"
        }
    }
}

```

Is there a more formal procedure required? Shall I make a pull request?
