### ISSUE TITLE
[Request] Add FreeFileSync

### ISSUE THREAD

**Issue by kunago** [ScoopInstaller/Extras#3750]
FreeFileSync is a folder comparison and synchronization software that creates and manages backup copies of all your important files. Instead of copying every file every time, FreeFileSync determines the differences between a source and a target folder and transfers only the minimum amount of data needed. FreeFileSync is Open Source software, available for Windows, macOS, and Linux.

link to the website: https://freefilesync.org

**Comment by mertd** [comment]
Note that I am not a lawyer.

In the [FAQ](https://freefilesync.org/faq.php#distribute), Zenju (the author) states 
> The software must be distributed free of charge and without modification to the contents of the installer package. Redistributing the installer package with any files added, removed, or modified is prohibited. The inclusion of the installer package or any of the included files in a different archive, or in a different installer is forbidden. For example, the integration into a third-party automated installation mechanism is forbidden without the prior permission of the author. 

The software does seem to be distributed under the GNU GPL v3 licence:
![grafik](https://user-images.githubusercontent.com/7928036/82621885-47bd7180-9c17-11ea-80bc-76b66237e72a.png)
A copy of this licence can be found in the [source and other downloads](https://freefilesync.org/download.php).

Is there a default way scoop or scoop-extras deals with situations like this?

**Comment by phanirithvij2000** [comment]
I mailed the author just now pointing to this issue, I'm not optimistic about the author allowing this, as auto-update only comes with the donation edition, and scoop by design allows autoupdate.

**Comment by rashil2000** [comment]
Scoop is not a "third-party automated installation mechanism", per se. It uses the official installer itself, and does not modify it. The only difference is that Scoop is clicking Next->Next in the installer, instead of your fingers :)

**Comment by kunago** [comment]
What prevents FreeFileSync from being able to work fine is a small "install.dat" file created on install. It is unique for each installation so copying it to other machines does not work. Unless there is a way to decypher this dat file and create it on each scoop installation, there is not much one can do.

**Comment by phanirithvij** [comment]
The author replied [Screenshot](https://user-images.githubusercontent.com/29627898/144704309-421e5059-0f47-4703-b8ca-a8442330485f.jpg)
I think this issue can be closed. 😢

**Comment by rashil2000** [comment]
Thanks @phanirithvij for following up

**Comment by successtheman** [comment]
I know I am a bit late here, but there is source code available for freefilesync available here https://freefilesync.org/download/FreeFileSync_12.4_Source.zip, is this source only for specific parts of the program? or is there anything else preventing someone from forking freefilesync?

**Comment by rashil2000** [comment]
I couldn't see any license on their website - which might be preventing people from forking and redistributing it

**Comment by phanirithvij** [comment]
> Redistributing the installer package with any files added, removed, or modified is prohibited.

Doesn't forking fall under this?

**Comment by rashil2000** [comment]
Yeah, I guess so
