### ISSUE TITLE
Git Credential Manager for Windows doesn't work?

### ISSUE THREAD

**Issue by david-bakin** [ScoopInstaller/Extras#3763]
Installed `git` via `scoop` as per usual.  Tried to use it for the first time with a repo that requires an ssl client cert - got basic auth errors. It didn't ask me for username or anything.

Did a very little bit of investigation and found the global setting `credential.helper` was set to `manager` - a windows-only feature for managing credentials.  It's supposed to pop-up or something - actually I know little about how to configure it.  

Anyway, disabled that by setting it to `cache`.

But the question is: Was it _supposed_ to work out of the box? Or did scoop not install something it should have?  If the answer is pilot error - as I suspect it is - then just let me know and I'll slink away.

**Comment by HUMORCE** [comment]
> Was it supposed to work out of the box? Or did scoop not install something it should have? If the answer is pilot error - as I suspect it is - then just let me know and I'll slink away.

same value as installer(default)? anyway, `main/git` manifest has updated.
