### ISSUE TITLE
[Request] Add BattleNet

### ISSUE THREAD

**Issue by nitrocode** [ScoopInstaller/Extras#3780]
https://www.blizzard.com/en-us/apps/battle.net/desktop

For some reason that link keeps failing. I found a direct link that was much faster, official, but it was posted on reddit. Anyone taking this ticket should try the first link first but if it has problems, the second link will definitely work.

https://www.reddit.com/r/Blizzard/comments/2fi64z/battlenet_direct_download_client/
http://dist.blizzard.com/downloads/bna-installers/322d5bb9ae0318de3d4cde7641c96425/retail.1/Battle.net-Setup-enUS.exe

**Comment by aj0413** [comment]
https://github.com/Ash258/Scoop-Ash258/blob/master/TODO/BattleNet.json

Seems someone is working on it; it's on the TODO table.

**Comment by Xelbayria** [comment]
I was going to add request for Battlenet. it seems that I don't have to add since this is already added.

**Comment by aliesbelik** [comment]
Available in [games](https://github.com/Calinou/scoop-games) bucket, added in Calinou/scoop-games#1035.
