### ISSUE TITLE
[Request] Add Asar7z

### ISSUE THREAD

**Issue by Airkro** [ScoopInstaller/Extras#3797]
http://www.tc4shell.com/en/7zip/asar/

> Asar7z is a small plugin for the popular 7-Zip archiver. You can use Asar7z with 7-Zip to open, modify, or create .asar archives, which are used for packaging applications based on the Electron framework.

**Comment by everyx** [comment]
to use this plugin, we should have 7zip preset dir for Formats folder to place the plugin dll files https://github.com/ScoopInstaller/Main/issues/992
