### ISSUE TITLE
[Request] Add KDE Connect

### ISSUE THREAD

**Issue by datream** [ScoopInstaller/Extras#3908]
KDE Connect is a free and open-source software that allows you to monitor your Android device's status (i.e. battery, notifications, etc) form your PC, share files and website links between your Android device and PC, or control mouse/keyboard input of your PC from your Android Device

[Homepage](https://kdeconnect.kde.org/)
[Download](https://binary-factory.kde.org/job/kdeconnect-kde_Nightly_win64/)

**Comment by datream** [comment]
So apparently the link in the previous comment is for the nightly version.
> [Download](https://binary-factory.kde.org/job/kdeconnect-kde_Nightly_win64/)
 
Here is the link for Release version.
[Download](https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/)

**Comment by DanielSherlock** [comment]
Was searching for KDE Connect issues today, found this one.

Surely this is closed by #7662?

**Comment by rashil2000** [comment]
Yes
