### ISSUE TITLE
[Request] Add StrokesPlus.net

### ISSUE THREAD

**Issue by Kristinita** [ScoopInstaller/Extras#3939]
### 1. Checklist

1. [x] The app I am requesting [**does not already exist**](https://scoop-docs.netlify.app/apps/?query=StrokesPlus) on **<https://scoop-docs.netlify.app/apps>**
1. [x] [**There is no open issue for this app**](https://github.com/lukesampson/scoop-extras/issues?q=is%3Aissue+is%3Aopen+StrokesPlus)
1. [x] The issue title starts “[Request] Add”
1. [x] The download URL is public and not locked behind a paywall/login

### 2. Package details

1. Software project URL: **<https://www.strokesplus.net/>**
1. Downloads URL: **<https://www.strokesplus.net/Downloads>**
1. What versions does this software have? Installer and Portable
1. What dependencies required for this software? See “[**Resources**](https://www.strokesplus.net/Downloads)” section on official Downloads page
1. Have this software command-line interface (CLI)? No
1. Software summary/short description: Free software, by which user can call hotkeys, macros and other by mouse gestures. See [**official site**](https://www.strokesplus.net/) for more details.

### 3. Note

Please, do not confuse StrokesPlus.net and StrokesPlus, that [**already exist in Scoop**](https://scoop-docs.netlify.app/apps/?query=StrokesPlus). StrokesPlus is no longer maintained software, its latest version [**was released in March 2016**](https://www.strokesplus.com/). StrokesPlus.net is [**actively maintained on April, 2020**](https://www.strokesplus.net/ChangeLog.txt).

Thanks.

**Comment by Xelbayria** [comment]
@Ash258 

I was going to get Strokesplus but noticed that the version is not correct. I saw that the package is from "strokesplus.com" which is no longer maintained. the website need to be corrected by using "strokesplus.net" 

btw sorry about the  pinging

**Comment by rashil2000** [comment]
Please make a PR for your fix

**Comment by Xelbayria** [comment]
Ok... how do I do PR for the fix. This is my first json for Strokesplus.net and got it working.

**Comment by rashil2000** [comment]
You can fork the repository, create a new branch, push/commit your change in that branch, and then create a PR here. See https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md

**Comment by Xelbayria** [comment]
alright. ok. How do I use `checkver` to check for the latest version, so I wouldn't have to update the manifest JSON manually? 

the current version is v0.5.6.6 and the download link is from https://cdn.strokesplus.net/files/StrokesPlus.net_Portable_0.5.6.6.zip

I tried other links like a normal download ( https://www.strokesplus.net/download/latest/portable ), but it doesn't work very well.

**Comment by Xelbayria** [comment]
alright. I ran some tests with a few trials and errors to get it working including the auto-updating part. 
The PR shouldn't be an issue now and hopefully, it will be accepted without any issue. 
your issue is finished now and have a good day! @Kristinita
