### ISSUE TITLE
[Request] Add SteamMover

### ISSUE THREAD

**Issue by ak-42** [ScoopInstaller/Extras#4048]
>Dead, deprecated and obsolete project

>> This program will move Steam Games from/to the Steam Library and remote directories. **This functionality is now included in the Steam client.**

>_Originally posted by @Ash258 in https://github.com/lukesampson/scoop-extras/issues/4041#issuecomment-627279645_

The project is called SteamMover, but what it is is essentially just a GUI for moving a folder and leaving a symbolic link/junction behind. The functionality to move games has been added to Steam, indeed, but I also use this tool to move non-Steam games such as standalone games, Battle.Net/Origin/GOG games, or even just moving a generic folder (like ~/Downloads) and leaving the junction behind. Thus, it's usability is much wider than the narrow use of moving Steam games.
Steam cannot be used to move a non-Steam standalone game, but this project can, thus it is not made obsolete by Steam's functionality.

**Creation of this issue is not an attempt to force the issue or defy your decision, I am only doing this because I cannot leave a coment in [4041.](https://github.com/lukesampson/scoop-extras/issues/4041) I am perfectly happy to accept your decision to decline addition of the software.** The reason why I'm reopening this is because it seems to me that you may have not considered the full scope of usability of the project and thus I kindly ask you to review your decision.
**Regardless of your response, no further issues on this topic will be opened by me.**

**Comment by Ash258** [comment]
You can comment on that issue without any problem as it is not locked or anything.

Other general issue with it is that there are no releases, no installers, no artifacts to download and use it as standalone binary. No website, nothing.

**Comment by ak-42** [comment]
Oh geez, indeed you're right about locking. Sorry, I'm not super familiar with Github interface.

I was referring to this software:
https://www.traynier.com/software/steammover

But it seems I also gave you the wrong Github (I should have checked before just fishing it from my history, since the name is so generic). So all in all, number of fails from me.

The portable binary appears to be here: https://github.com/traynier/traynier.github.io/tree/master/files

There seems to be also no details on the license, so I'm unsure if that would pose a problem.
