### ISSUE TITLE
[Request] Add 010 Editor

### ISSUE THREAD

**Issue by NotWearingPants** [ScoopInstaller/Extras#4290]
Hello, please add 010 Editor to scoop.

010 Editor is a professional text editor and a hex editor.
https://www.sweetscape.com/010editor/

It is a 30 day free trial, and it has a portable version - https://www.sweetscape.com/download/010editor/

The installer is an InnoSetup installer.

Thanks!

**Comment by Vedabahu** [comment]
Look at the irony. Issue Opened in June 16 2020, fixed in May 16 2022. :rofl: :rofl: :rofl:
