### ISSUE TITLE
Redshift Tray 1.9.8 virustotal multiple matches

### ISSUE THREAD

**Issue by grippen** [ScoopInstaller/Extras#4344]
https://www.virustotal.com/gui/file/e70a696d304650a9d440e4bb06ac7a2de1f5d9b09af7ed77560992990b1b522f/detection

**Comment by ltGuillaume** [comment]
These are all false positives and a well-known byproduct of the AutoHotkey interpreter. The executable is nothing more than the exact script as committed to GitHub (you can see the plain text inside `rstray.exe` using any text editor) run through AutoHotkey's `ahk2exe.exe`.
