### ISSUE TITLE
[Bug] Firefox/thunderbird update switches profile

### ISSUE THREAD

**Issue by mateusz-piotrowski** [ScoopInstaller/Extras#4377]
- I have installed Firefox 77.0.1.
- I updated it to 78.0.1 via the following command -->  $ scoop update *
I used this command because I had other apps to update and don't wanted update each one separately.
- After the process completed I ran Firefox from start menu and I saw: my history, open tabs and saved passwords has been lost.
- I don't know what happen but after a angry evening of this situation I remembered of profile manager builtin Firefox.
- I saw 5 new profiles and the oldest one is my profile.
- Do you know why updated Firefox created new profile?

**Comment by mark05e** [comment]
Doesn't seem like there is any [persist configuration](https://github.com/lukesampson/scoop/wiki/Persistent-data) done for the [firefox installer](https://github.com/lukesampson/scoop-extras/blob/master/bucket/firefox.json)

Other browser apps that have persist config (for reference):

1. https://github.com/lukesampson/scoop-extras/blob/master/bucket/tor-browser.json
2. https://github.com/lukesampson/scoop-extras/blob/master/bucket/vivaldi.json
3. https://github.com/lukesampson/scoop-extras/blob/master/bucket/qutebrowser.json
4. https://github.com/lukesampson/scoop-extras/blob/master/bucket/opera.json

**Comment by mateusz-piotrowski** [comment]
Thank you for answer. Unfortunately I no have idea how check what happen.
After this issue occurred on my notebook I installed **Firefox Developer**.
It launched with empty session, but when I checked about:profiles settings I saw profile from previous **Firefox**.
So I changed default profile and removed any other, left profile with **default** name.
But today the same situation happen - **Firefox Developer** started with empty session.
I looked at about:profiles page and met profile with the following name --> **dev-edition-default** marked as default.
So, I removed it, mark "default" profile as default one and change name to --> **dev-edition-default**.
I will watching what happen now.

**Comment by mark05e** [comment]
I do not think it is a config you have to do. The scoop installer script needs to be updated by somebody.

**Comment by slaughtering** [comment]
Yeah this is gonna happen on all firefox editions like esr, beta, nightly, developer... and custom builds like waterfox, and maybe palemoon also.

**Comment by teohhanhui** [comment]
This actually has to do with the changes made in Firefox 67 which makes each installation of Firefox use its own profile setting: https://support.mozilla.org/en-US/kb/dedicated-profiles-firefox-installation#w_what-profile-changes-were-made-in-firefox-67

**Comment by raycheung** [comment]
I'm using `firefox` and having this issue. My current workaround is going to `about:profiles` after the upgrade, then manually switch to the previous profile following with a restart.

**Comment by madhead** [comment]
+1 for this issue.

**Comment by joe733** [comment]
Facing the same issue here. Did anyone try it out without renaming the profiles `default` and `default-release`?

> Doesn't seem like there is any persist configuration done for the firefox installer

Can we tell scoop to create one?

> PS: @mateusz-piotrowski can you updated the issue title to something like `[Bug] Firefox update switches profile`

**Comment by mateusz-piotrowski** [comment]
@joe733 done

**Comment by joe733** [comment]
> Facing the same issue here. Did anyone try it out without renaming the profiles default and default-release?

Yup.. it creates a new profile `default-release-1`  👀 

![image_2021-09-07_20-51-37](https://user-images.githubusercontent.com/38415384/132370898-08be543d-f71d-4a0d-bfc0-098ca50394fd.png)

**Comment by rubendibattista** [comment]
Another related problem is that any new Firefox update adds a new default app. 

![image](https://user-images.githubusercontent.com/8077364/145838958-c7df3cd7-20eb-4a4a-a355-6a6891c37262.png)

**Comment by rubendibattista** [comment]
The persist option in the current manifest looks useless? There's nothing in the `distribution` folder.

**Comment by amreus** [comment]
You get different profiles between launching from the command line and the Start menu since they point to different executables. 

The command line uses the firefox.exe shim. The shim does not respond to command line arguments such as `-p`. 

At the least make it so the command line and start menu open the same profile.

**Comment by rashil2000** [comment]
Please make a PR for your fix!

**Comment by amreus** [comment]
> Please make a PR for your fix!

It looks like `firefox-portable` does persist the profiles and uses the same profile when starting from both the shim.exe and start menu.

Now I am not sure what the difference between the `firefox` and `firefox-portable` apps is?  They both use the same download.  I'll just use `firefox-portable`

**Comment by rubendibattista** [comment]
I don't think switching to portable Firefox fixes the problem. I've been using it for a bit now and after every update it asks to set it as default browser, and if you do profile is switched to a new one.

**Comment by rashil2000** [comment]
That's a different issue, please create a new one!

This one was about losing profile on updates, not about setting default browser.

**Comment by amreus** [comment]
Maybe any `firefox` package should create and use a dedicated profile named `scoop`

To create the profile, the installer could execute: 

    firefox -no-remote -CreateProfile "scoop %USERPROFILE%\scoop\persist\firefox\"

Then any scoop shim for firefox would use the `-p scoop` option.

**Comment by rashil2000** [comment]
How is it different from the current implementation?

The current shim also uses the -p switch (which creates a profile directory if it doesn't exist).

**Comment by amreus** [comment]
Because you made a change which added that just 20 hours ago which I was not aware of.

**Comment by rashil2000** [comment]
Okay, no worries :)

**Comment by amreus** [comment]
I'm still wondering if `firefox-nightly` should also use the same profile. 

And if it's really useful to have both `firefox` and `firefox-portable`.

**Comment by rashil2000** [comment]
> I'm still wondering if `firefox-nightly` should also use the same profile.

It's in the Versions bucket. You can make a PR to use the profile.

> And if it's really useful to have both `firefox` and `firefox-portable`.

The non-portable version will still have the original problem described in this issue.

**Comment by amreus** [comment]
> It's in the Versions bucket. You can make a PR to use the profile.

Yes, I will do it later today.

> The non-portable version will still have the original problem described in this issue.

Yes and is that really what's wanted?

**Comment by rashil2000** [comment]
> Yes and is that really what's wanted?

I don't quite get what you mean. Do you have a different solution in mind?

**Comment by amreus** [comment]
Sorry no I'm still catching up - firefox-portable has been removed apparently. 

The last issue I have is there doesn't appear to be a way to register scoop's firefox shim as a the default browser. So when the OS opens a url, for example when you type `start https://google.com` on the command line, you get the default browser. Bit of an annoyance.

**Comment by rashil2000** [comment]
Hmm, what method do you use to set the default browser? If it's related to a registry key somewhere, we can add a `-p <persist-location>` argument there.

**Comment by amreus** [comment]
> Hmm, what method do you use to set the default browser? If it's related to a registry key somewhere, we can add a -p <persist-location> argument there.

I'm no expert on the subject but have done some searching for methods to register portable apps as Windows default app.  It does involve setting a number of registry keys.  The final selection would need user input, but that is how the Firefox Installer handles it also.

It would be better to add a feature to scoop to "register browser as default" so any browser in scoop could use it.

**Comment by worldofgeese** [comment]
As it looks like the version of Thunderbird that fixes this issue, thunderbird-portable, was removed, is it better to switch to the full-fat release version of Thunderbird assuming profiles will continue to be created on upgrade?

**Comment by rashil2000** [comment]
thunderbird-portable was renamed to thunderbird
