### ISSUE TITLE
windows-terminal: function issue

### ISSUE THREAD

**Issue by ZvonimirSun** [ScoopInstaller/Extras#4531]
As you can see, the shim cmd window will not close itself until the main windows terminal window is closed.

![image](https://user-images.githubusercontent.com/22871764/89242557-6f2bb400-d634-11ea-8209-7d2ca76abfe4.png)

**Comment by gitolicious** [comment]
This is not related to windows-terminal but to scoop shims in general. I would call it a duplicate of https://github.com/lukesampson/scoop/issues/1606
