### ISSUE TITLE
Zoom launching problem version 5.2.0 (with a temporary fix)

### ISSUE THREAD

**Issue by yiwenleo** [ScoopInstaller/Extras#4573]
Zoom has trouble launching from the browser after installing by scoop.
It shows "Need new app to open zoommtg link" and direct to MS Store
The temp solution is to run  "Zoom_launcher.exe" under installation folder 
(`C:\Users\***\scoop\apps\zoom\5.2.0\Zoom_launcher.exe`)

**Comment by FriendlyNeighborhoodShane** [comment]
I am not even able to launch zoom (5.4.7) from the executable. Zoom.exe says that the application was unable to start correctly.

Zoom_launcher.exe actually starts installing itself somewhere else.

**Comment by FriendlyNeighborhoodShane** [comment]
Nevermind, figured it out.

For Windows versions older than 10, you have to extract all the dlls in `win10rt.7z` (should be in the app driectory) to the app directory.

**Comment by brechtm** [comment]
> The temp solution is to run "Zoom_launcher.exe" under installation folder

That seems to install Zoom to the `C:\Users\<username>\AppData\Roaming\Zoom`, so you're no longer running the scope-managed version.

**Comment by brechtm** [comment]
You can register the scoop-managed Zoom for zoomtg:// URLs by importing this into the registry:

```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\zoommtg]
"URL Protocol"=""
@="Zoom (Application Name)"

[HKEY_CURRENT_USER\SOFTWARE\Classes\zoommtg\shell]

[HKEY_CURRENT_USER\SOFTWARE\Classes\zoommtg\shell\open]

[HKEY_CURRENT_USER\SOFTWARE\Classes\zoommtg\shell\open\command]
@="\"C:\\Users\\<USERNAME>\\scoop\\apps\\zoom\\current\\Zoom.exe\" --url=\"%1\""
````

Replace `<USERNAME>` with your username, save this as _zoommtg.reg_ and double-click to import it into the registry.
