### ISSUE TITLE
[Request] Add ProtonVPN

### ISSUE THREAD

**Issue by nitrocode** [ScoopInstaller/Extras#4678]
Their [download page](https://protonvpn.com/download) contains this URL

https://protonvpn.com/download/ProtonVPN_win_v1.16.3.exe

Github: https://github.com/ProtonVPN/win-app

License is GNUv3: https://github.com/ProtonVPN/win-app/blob/master/LICENSE

Scrape-able version
* https://protonvpn.com/download/win-update.json
* https://github.com/ProtonVPN/win-app/blob/master/src/GlobalAssemblyInfo.cs#L16-L17

**Comment by nagromc** [comment]
Can be closed since https://github.com/ScoopInstaller/Nonportable/commit/bbcc39d4b4efebddac8f360b7d76cb973c017428
