### ISSUE TITLE
[Request] Add 1password

### ISSUE THREAD

**Issue by nitrocode** [ScoopInstaller/Extras#4729]
The 1password-cli is in the main bucket and it would be nice if 1password was in the extras bucket.

https://1password.com/downloads/windows/ points to https://app-updates.agilebits.com/download/OPW7

Thanks!

**Comment by issaclin32** [comment]
implemented in `main/1password-cli`

**Comment by aryanprince** [comment]
Can we have the latest [1Password 8](https://1password.com/downloads/windows/) added to main/extra buckets? Not talking about the CLI version

**Comment by aryanprince** [comment]
And just to be clear, OP (@nitrocode) and you (@max-samusevich) were talking about the 1Password 8 desktop app and NOT the 1Password CLI yes?
