### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by NatoBoram** [ScoopInstaller/Extras#4767]
I've noticed a few common type of issues and it would be great to have them formalized in templates.

Here's a few examples : 

* [Request] Add `<app>`
* ~~`<app>`@`<version>`: hash check failed~~
* ~~`<app>`@`<version>`: download via aria2 failed~~

Of course, there's probably more, but I think it would be beneficial to guide requests with appropriate info.

**Comment by Ash258** [comment]
The last two are covered by the core itself. You always get URL with the title
