### ISSUE TITLE
[Request] Add avidemux

### ISSUE THREAD

**Issue by boesi** [ScoopInstaller/Extras#4775]
Can you please add avidemux?

It can be downloaded from [https://www.fosshub.com/Avidemux.html](https://www.fosshub.com/Avidemux.html).

The actual webpage for the project is [http://fixounet.free.fr/avidemux/download.html](http://fixounet.free.fr/avidemux/download.html), but there the download for windows points to an older version.

Thanks a lot.

**Comment by rasa** [comment]
See https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/avidemux
