### ISSUE TITLE
tinymediamanager v4

### ISSUE THREAD

**Issue by Dabombber** [ScoopInstaller/Extras#4821]
From version 4, tinyMediaManager has changed its licensing model from donationware to subscription based. [tinyMediaManager blog](https://www.tinymediamanager.org/blog/v4-future/):
> Since the lion’s share of the work (development, maintenance, deployment, …) remains within the tinyMediaManager team, we decided to charge an annual fee for the ongoing work on the project (starting with v4).

That's their choice and I have no problem with it, but I think the manifest for tinymediamanager should be limited to version 3 as it's essentially a different branch now. 
> tinyMediaManager v3 will remain available and free, but only serious bugs will be fixed and no new features will be added. A mandatory upgrade to v4 will not be necessary, but we want to provide an easy transition for users which want to upgrade.

I'm not actually sure if version 4 could be added in another manifest. There's no criteria listed for the extras bucket, but I would assume the trial versions exclusion from the main bucket still applies.
> * the compiled/packaged version of tinyMediaManager has a limitation concerning the number of loaded objects/API calls of the scraper (currently 50 movies, 10 TV series and about 50 API calls) - unlockable with a license

**Comment by lepicsaintloup** [comment]
I just put an issue #4875. Not sure if this should be merged.
