### ISSUE TITLE
[Feature] Add Windows Terminal Preview

### ISSUE THREAD

**Issue by rashil2000** [ScoopInstaller/Extras#4831]
Windows-Terminal has long left the preview state, and there are now 2 versions available - stable and preview. It'd make sense to move the stable version to the main bucket. 

Also, some new features are only there in Windows-Terminal-Preview. So I think we can add this package to the extras bucket.

**Comment by rashil2000** [comment]
Hey @Ash258, any particular reason for the thumbs down? 

If the stable version can't be added to the main bucket yet, can we at least have the preview here in the extras too? 
I would like to use preview but I don't like the Store method currently.

**Comment by Ash258** [comment]
Windoes terminal is not command line utility, which prevent it from being added in main bucket.

**Comment by rashil2000** [comment]
Oh, I just mentioned shifting it because cmder (which is not a commandline utility) was there in Main too. 

The extras bucket doesn't have restrictions on Preview apps, right?

**Comment by sontek** [comment]
Is the policy for scoop to only add CLI?  So things like VLC / Windows Terminal would be out of scope?
