### ISSUE TITLE
[Request] Add seafile

### ISSUE THREAD

**Issue by dionysius** [ScoopInstaller/Extras#4949]
Project Homepage: https://www.seafile.com/en/download/

Since there is a `nextcloud` client, I'd thought there might be also one for seafile

**Comment by Erisa** [comment]
Worth noting there are effectively three different applications available for Seafile on Windows, all with slightly different goals.
The main "Seafile Client" works as an old-style sync solution where entire folders are synced locally.
Version 1.x of "SeaDrive" maps a network drive and has an intelligent caching method for keeping only accessed files present on disk.
Version 2.x of "SeaDrive" uses the Windows [Cloud Sync Engine](https://docs.microsoft.com/en-us/windows/win32/cfapi/build-a-cloud-file-sync-engine) to provide an experience essentially identical to that of OneDrive.

Of these, am I right to assume Seafile Client is the one referenced by this issue?

**Comment by dionysius** [comment]
Correct, I was referring to the "Desktop Syncing Client for Windows", your 1st point.

**Comment by isavegas** [comment]
It looks like there is a pending PR for `seafile-syncing-client`: #4793. It seems to be stalled on handling automatic installation configuration and hasn't seen any progress in a month, as of today. If that PR is dead, I'll take a look at it. I also would love to have a Seafile client in Scoop.
