### ISSUE TITLE
magicavoxel@0.99.6: Download failed

### ISSUE THREAD

**Issue by fightingcat** [ScoopInstaller/Extras#4964]
Installing 'magicavoxel' (0.99.6) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/ephtracy/ephtracy.github.io/releases/download/0.99.6/MagicaVoxel-0.99.6-win64.zip is not valid

The correct file name is "MagicaVoxel-0.99.6<strong>.2</strong>-win64.zip".

**Comment by issaclin32** [comment]
Fixed in https://github.com/ScoopInstaller/Extras/commit/edb84f5ecbfbff8d80a1e77569a9188689c4daba
