### ISSUE TITLE
[Request] Add Unity Hub

### ISSUE THREAD

**Issue by AbedSHP** [ScoopInstaller/Extras#4976]
Unity is a popular game engine. and Unity Hub a simple tool for install and uninstall Unity (game engine) and manage for the projects.

https://unity3d.com/get-unity/download
https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe

Thanks

**Comment by issaclin32** [comment]
[nonportable/unity-hub-np](https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/unity-hub-np.json)
