### ISSUE TITLE
hexo-client@1.3.5: decompress error

### ISSUE THREAD

**Issue by leganck** [ScoopInstaller/Extras#4986]
scoop install hexo-client
Installing 'hexo-client' (1.3.5) [64bit]
HexoClient-Setup-1.3.5.exe (44.4 MB) [========================================================================] 100%
Checking hash of HexoClient-Setup-1.3.5.exe ... ok.
Extracting dl.7z ... done.
Running installer script...
ERROR Exit code was 2!
Failed to extract files from D:\DevelopTools\Scoop\apps\hexo-client\1.3.5\$PLUGINSDIR\app-32.7z.
Log file:
  D:\DevelopTools\Scoop\apps\hexo-client\1.3.5\$PLUGINSDIR\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=hexo-client%401.3.5%3a+decompress+error
![image](https://user-images.githubusercontent.com/24834938/97392417-aef4f580-191c-11eb-8e3e-5d952db9aabf.png)

**Comment by Ash258** [comment]
They switched to the 64bit only, but the manifest will be removed as there is no working English support.
