### ISSUE TITLE
[Request] Add DisplayCAL

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Extras#5099]
Hi

So frankly I'm too much of a newbie to know exactly needs to be available to effectively add an app to Scoop - especially with autoupdate functionality, but what I do know is the DisplayCAL at least has a portable version in a zip file and a SHA256 hash check, all of which can be found here: https://displaycal.net/#download

Hopefully this is possible and I'll gladly be educated on what's eventually missing to make this an effective candidate for addition.

**Comment by issaclin32** [comment]
implemented in #2173
