### ISSUE TITLE
[Request] Add Open-Shell

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Extras#5100]
Would it be possible to add Open-Shell found on GitHub here: https://github.com/Open-Shell/Open-Shell-Menu

**Comment by schance995** [comment]
I have this so far. It extracts fine but I don't know what to do next.

```
{
    "version":  "4.4.160",
    "description": "Classic style Start Menu for Windows 7, 8, 8.1, 10"
    "license":  "MIT",
    "url":  "https://github.com/Open-Shell/Open-Shell-Menu/releases/download/v4.4.160/OpenShellSetup_4_4_160.exe#/dl.7z",
    "homepage":  "https://github.com/Open-Shell/Open-Shell-Menu",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/Open-Shell/Open-Shell-Menu/releases/download/v$version/OpenShellSetup_$underscoreVersion.exe#/dl.7z",
    }
}
```
Got this: 
![open-shell in scoop](https://user-images.githubusercontent.com/54919210/100322091-be09aa80-2f91-11eb-9e70-c59543994eca.png)
Expecting this:
![open-shell in program files](https://user-images.githubusercontent.com/54919210/100322191-e1ccf080-2f91-11eb-972d-a8b86aadd32d.png)

**Comment by RavenMacDaddy** [comment]
I'm terribly sorry that I personally don't know what needs to be done next to make it a complete package for Scoop, but I do appreciate you for at least attempting to make one.

**Comment by davidxuang** [comment]
I did some investigation and I'd say it's a self-extract archive containing obfuscated (XOR-ed) MSI files. Have no idea why it was packed so.

**Comment by Zliced13** [comment]
Hello, here is my part of the manifest for open shell. I tried to make it portable, but after doing a lot of testing that almost broke my Windows OS, I have concluded that it should be implemented as a non-portable application instead.
Here is my try on the manifest:
```json
{
    "version": "4.4.170",
    "homepage": "https://github.com/Open-Shell/Open-Shell-Menu",
    "description": "A fork of Classic Shell with additonal fixes and more features.",
    "license": "MIT",
    "url": "https://github.com/Open-Shell/Open-Shell-Menu/releases/download/v4.4.170/OpenShellSetup_4_4_170.exe#/package.exe",
    "hash": "0417041CFFED3478F13A840E45EE304CCF8D1F9CA38E4126BC315161AC9F1669",
    "pre_install": [
        "Set-Location $dir; Start-Process \"$dir\\package.exe\" -Wait -Verb 'RunAs' -ArgumentList 'extract64' | Out-Null; Set-Location",
        "Remove-Item \"$dir\\package.exe\" | Out-Null; Rename-Item \"$dir\\*\" 'package.msi' | Out-Null"
    ],
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/Open-Shell/Open-Shell-Menu/releases/download/v$version/OpenShellSetup_$underscoreVersion.exe#/package.exe"
    }
}
```

**Comment by RavenMacDaddy** [comment]
Fair enough, and I appreciate you getting back to this old issue – cheers @Zliced13.

**Comment by Zliced13** [comment]
You can add my bucket if you want to try the manifest file out for yourself.
```shell
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
scoop install open-shell-np
```
