### ISSUE TITLE
The software Everything from this bucket doesn't work.

### ISSUE THREAD

**Issue by NamelessUzer** [ScoopInstaller/Extras#5108]
I found the software Everything from this bucket doesn't work. I can install it without error. But when I run it, it tells "It is creating database" always. It's abnormal. Usually, Everything can create database in seconds.
But If I download the software from its official website and install it by myself. It works very well.
I don't know how to deal with it. Anyone can help?

**Comment by Skyline404** [comment]
same, service mode creates database infinitely

**Comment by Skyline404** [comment]
Same if using everything service mode

**Comment by HUMORCE** [comment]
I have the same problem in the previous few updates (version 1.4.1.986), but it works normally now.

you can modify everything.json to roll back to the previous version, check if it can create database.

I will manually disable everything service every time before update it, now.
