### ISSUE TITLE
[Request] Add Yuzu Emulator

### ISSUE THREAD

**Issue by NatoBoram** [ScoopInstaller/Extras#5249]
> [yuzu emulator](https://github.com/yuzu-emu/yuzu)
> =============
> [![Travis CI Build Status](https://travis-ci.com/yuzu-emu/yuzu.svg?branch=master)](https://travis-ci.com/yuzu-emu/yuzu) [![Azure Mainline CI Build Status](https://dev.azure.com/yuzu-emu/yuzu/_apis/build/status/yuzu%20mainline?branchName=master)](https://dev.azure.com/yuzu-emu/yuzu/) [![Discord](https://img.shields.io/discord/398318088170242053?color=%237289DA&label=yuzu&logo=discord&logoColor=white)](https://discord.com/invite/u77vRWY)
> 
> yuzu is an experimental open-source emulator for the Nintendo Switch from the creators of [Citra](https://citra-emu.org/).
> 
> It is written in C++ with portability in mind, with builds actively maintained for Windows and Linux. The emulator is capable of running several commercial games.
> 
> yuzu only emulates a subset of Switch hardware and therefore most commercial games **do not** run at full speed or are not fully functional.
> 
> Do you want to check which games are compatible and which ones are not? Please visit our [Compatibility page](https://yuzu-emu.org/game/)!
> 
> yuzu is licensed under the GPLv2 (or any later version). Refer to the license.txt file included.
> 
> Check out our [website](https://yuzu-emu.org/)!
> 
> For development discussion, please join us on [Discord](https://discord.com/invite/u77vRWY).
> 
> ### Development
> 
> Most of the development happens on GitHub. It's also where [our central repository](https://github.com/yuzu-emu/yuzu) is hosted.
> 
> If you want to contribute please take a look at the [Contributor's Guide](https://github.com/yuzu-emu/yuzu/wiki/Contributing) and [Developer Information](https://github.com/yuzu-emu/yuzu/wiki/Developer-Information). You should also contact any of the developers on Discord in order to know about the current state of the emulator.
> 
> If you want to contribute to the user interface translation, please check out the [yuzu project on transifex](https://www.transifex.com/yuzu-emulator/yuzu). We centralize translation work there, and periodically upstream translations.
> 
> ### Building
> 
> * __Windows__: [Windows Build](https://github.com/yuzu-emu/yuzu/wiki/Building-For-Windows)
> * __Linux__: [Linux Build](https://github.com/yuzu-emu/yuzu/wiki/Building-For-Linux)
> * __macOS__: [macOS Build](https://github.com/yuzu-emu/yuzu/wiki/Building-for-macOS)
> 
> 
> ### Support
> We happily accept monetary donations or donated games and hardware. Please see our [donations page](https://yuzu-emu.org/donate/) for more information on how you can contribute to yuzu. Any donations received will go towards things like:
> * Switch consoles to explore and reverse-engineer the hardware
> * Switch games for testing, reverse-engineering, and implementing new features
> * Web hosting and infrastructure setup
> * Software licenses (e.g. Visual Studio, IDA Pro, etc.)
> * Additional hardware (e.g. GPUs as-needed to improve rendering support, other peripherals to add support for, etc.)
> 
> We also more than gladly accept used Switch consoles, preferably ones with firmware 3.0.0 or lower! If you would like to give yours away, don't hesitate to join our [Discord](https://discord.gg/VXqngT3) and talk to bunnei. You may also contact: donations@yuzu-emu.org.
>

**Comment by ShadowCreator250** [comment]
Wouldn't this better fit in the games bucket?

**Comment by rashil2000** [comment]
Yes, and I think games bucket already has it

**Comment by Vedabahu** [comment]
The requested application is present in the [Games Bucket](https://github.com/Calinou/scoop-games).
Here is the [link to the manifest](https://github.com/Calinou/scoop-games/blob/master/bucket/yuzu.json).

@rashil2000 Can you please close this issue.
