### ISSUE TITLE
[Request] Add ZeroBrane Studio

### ISSUE THREAD

**Issue by zzfnohell** [ScoopInstaller/Extras#5265]
ZeroBrane Studio is a lightweight Lua IDE with code completion, syntax highlighting, live coding, code analyzer, and debugging support for Lua 5.1, Lua 5.2, Lua 5.3, LuaJIT, and other Lua engines.

https://studio.zerobrane.com/
https://studio.zerobrane.com/download?not-this-time
https://github.com/pkulchenko/ZeroBraneStudio/

**Comment by rashil2000** [comment]
#1335
