### ISSUE TITLE
[Request] Add OpenToonz

### ISSUE THREAD

**Issue by AbedSHP** [ScoopInstaller/Extras#5270]
**Software for the production of 2D animation.**
Based on the software "Toonz", developed by Digital Video S.p.A. in Italy, OpenToonz has been customized by Studio Ghibli, and used for the creation of its works for many years. Dwango has launched the OpenToonz project in cooperation with Digital Video and Studio Ghibli

https://opentoonz.github.io/e/
https://opentoonz.github.io/e/download/opentoonz.html

**Comment by flavio20002** [comment]
Hi, I've tried to add it, but it's very difficult. The installer creates regex and a lot of directories in the filesystem. I will work on it in the next days

**Comment by AbedSHP** [comment]
hi, why?
OpenToonzSetup.exe /?
OpenToonzSetup.exe /VERYSILENT /DIR="Simple"
