### ISSUE TITLE
libreoffice-stable: Version is too new?

### ISSUE THREAD

**Issue by redactedscribe** [ScoopInstaller/Extras#5439]
If I'm understanding this correctly, LibreOffice's stable (LTS?) version is [6.4.7](https://www.libreoffice.org/download/download/) at this moment, however the closest portable version available via their download archive is [6.4.6.2](https://downloadarchive.documentfoundation.org/libreoffice/old/6.4.6.2/) (or a little newer at [7.0.0.3](https://downloadarchive.documentfoundation.org/libreoffice/old/7.0.0.3/)), yet the current version used by scoop's `libreoffice-stable` is the latest at [7.0.4.2](/lukesampson/scoop-extras/commit/1b261cb61531b08b8da6d86362a58f521d0fe7d2). [`libreoffice-fresh` _also_ uses this latest version](/lukesampson/scoop-extras/commit/4a01eca615d8f95112b2f607b2fcb179e3a1d53f), which would seem correct as this is the latest portable version made available by LibreOffice, but it then leaves me thinking `libreoffice-stable`'s version is too new. At minimum, it makes picking a choice between the two confusing as I'm not sure of their difference.

Thanks.

**Comment by SharakPL** [comment]
6.4.7 is not LTS. It's simply previous stable version in case someone needs it, but [release notes](https://www.libreoffice.org/download/release-notes/) state that it's dead. Current stable is 7.0.4.2 though installation through scoop is currently broken #5327
