### ISSUE TITLE
Zoom protocol handler

### ISSUE THREAD

**Issue by jftuga** [ScoopInstaller/Extras#5483]
When I `scoop install` Zoom from the extra bucket, it does not register the `zoommtg` protocol handler.  This is needed for the Zoom single-on feature.

I have this `.reg` file working:

    Windows Registry Editor Version 5.00

    [HKEY_CURRENT_USER\Software\Classes\zoommtg]
    @="URL:Zoom Launcher"
    "URL Protocol"=""
    "UseOriginalUrlEncoding"=dword:00000001

    [HKEY_CURRENT_USER\Software\Classes\zoommtg\DefaultIcon]
    @="\"C:\\Users\\jftuga\\scoop\\shims\\Zoom.exe\",1"

    [HKEY_CURRENT_USER\Software\Classes\zoommtg\shell]

    [HKEY_CURRENT_USER\Software\Classes\zoommtg\shell\open]

    [HKEY_CURRENT_USER\Software\Classes\zoommtg\shell\open\command]
    @="\"C:\\Users\\jftuga\\scoop\\shims\\Zoom.exe\" \"--url=%1\""

However, I am not sure how to best change the user prefix so that it will install for anyone using scoop.

It looks like @Ash258 has something similar working for:

* https://github.com/lukesampson/scoop-extras/blob/master/bucket/picotorrent.json
* https://github.com/lukesampson/scoop-extras/blob/master/scripts/picotorrent/install-associations.reg

In his `json` file, I do not understand what the value of `$dir` will be under the `post_install` section.

It would be really nice if `scoop-extras` version of `Zoom` would automatically install and uninstall this protocol handler.

**Comment by sameyepatch** [comment]
Hello. I don't exactly know what you mean by "user prefix" but I'm going to take a guess that you mean a user placeholder so the script can be used by anyone, right? In that case, use `%USERPROFILE%`.

Regarding the `$dir` variable, [the Scoop wiki](https://github.com/lukesampson/scoop/wiki/Pre--and-Post-install-scripts) sets it as the directory with the current version of the installed app.
