### ISSUE TITLE
KeePass: configuration error when closing

### ISSUE THREAD

**Issue by fritzmg** [ScoopInstaller/Extras#5540]
After a recent `scoop update keepass` I get the following error every time I close KeePass regarding the `KeePass.config.xml` in the program directory (not the user directory):

```
Configuration error

C:\Users\…\scoop\apps\keepass\current\KeePass.config.xml

Failed to save to the specified file!

Access to the path 'C:\Users\…\scoop\apps\keepass\current\KeePass.config.xml' is denied.
```

For some reason KeePass is now trying to save the KeePass.config.xml to the installation directory, rather than the persist directory. I already tried `scoop uninstall keepass` and reinstalling it again, but the problem remains.

**Comment by HUMORCE** [comment]
unable to reproduce,

try `scoop uninstall keepass -p` then install keepass.

_keepass persist data will be deleted._

**Comment by fritzmg** [comment]
Thx, that worked. Not sure what went awry here. Before removing the persisted data when uninstalling I used to have a `…\persist\keepass\KeePass.config.xml` file, which apparently was a Symlink to somewhere else. Now that does not exist any more. My custom settings are still there though, as KeePass actually uses `C:\Users\User Name\AppData\Roaming\KeePass\KeePass.config.xml` to save custom settings (per user).

**Comment by fritzmg** [comment]
This error happens every time when updating KeePass - _if_ KeePass is installed with `--global`. So to reproduce do the following:

1. `scoop install sudo`
2. `sudo scoop install keepass --global`
3. Then when a new version comes out: `sudo scoop update keepass --global`.
4. Start and then close the application.

The issue is the following: after `sudo scoop install keepass--global` the file `C:\Users\…\scoop\apps\keepass\current\KeePass.config.xml` has the following permissions:

<img src="https://github.com/ScoopInstaller/Extras/assets/4970961/5d1d822d-b2ab-40a0-8a8a-f6c2044ae3ee" width="387">

i.e. it gets permissions from the current user (the first blacked out one) with "Full Control". But after `sudo scoop update keepass --global` the file only gets the following permissions:

<img src="https://github.com/ScoopInstaller/Extras/assets/4970961/e5e0bb03-8211-4445-b7ff-5fee9e3bbaf7" width="387">

i.e. the "Full Control" permission for the current user is missing - and the permissions for the "Users" group are not "Full Control". The "Administrators" group has "Full Control" though - and my user is part of the "Administrators" group, but for some reason this is not enough.

I am not sure though this is something that scoop can alleviate?

**Comment by wickles** [comment]
The fix for this was not well received and might be reverted, please refer to https://github.com/ScoopInstaller/Extras/pull/13701#issuecomment-2705566337.

**Comment by fritzmg** [comment]
I see. Do I get this right that this error only happens if you install KeePass globally anyway?

**Comment by wickles** [comment]
For a typical installation, yes as far as I am aware.

For an [advanced installation](https://github.com/ScoopInstaller/Install?tab=readme-ov-file#advanced-installation), it would depend on your permissions in the configured local and global directories.
