### ISSUE TITLE
chromedriver often updated in favour of updating chrome first

### ISSUE THREAD

**Issue by 573** [ScoopInstaller/Extras#5549]
It doesn't make much sense to update chromedriver  in front of googlechrome, because both versions have to match anyways, otherwise:

>1) Error in custom provider, org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 88

Is there something we can do about this dependency ?

**Comment by pratikpc** [comment]
@573 currently Chrome updates are broken.

https://github.com/ScoopInstaller/Extras/issues/7096

Chromedriver checkvers on the other hand are not broken so its receiving updates.

If you could help us update Chrome checkvers, that issue would be resolved!
