### ISSUE TITLE
how-to rename a manifest?

### ISSUE THREAD

**Issue by AntonOks** [ScoopInstaller/Extras#5551]
Hi scoop dev's.

I would suggest to rename [the github.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/github.json) manifest to **_github-desktop.json_**.
This makes it clearer what this really is and also would be the same package name as in Choco.

Question:
- Does this make sense for the community and would a pull be accepted?
- If it be supported, is there any docu or hint how to do it (depreciating, having the new manifest in parallel and adding a "note" to the existing manifest, ..)?

Thanks!

**Comment by HUMORCE** [comment]
github-cli manifest has named gh, so I think this isn't necessary.
maybe you can create a duplicate manifest for it, like this:
https://github.com/ScoopInstaller/Main/blob/master/bucket/gpg.json
https://github.com/ScoopInstaller/Main/blob/master/bucket/gnupg.json
