### ISSUE TITLE
Terminus does not start correctly

### ISSUE THREAD

**Issue by thingumajig** [ScoopInstaller/Extras#5572]
Black screen after start. Button "+" does not work 
![image](https://user-images.githubusercontent.com/8703531/106166524-4fb5b400-619d-11eb-930e-911c26cc0bcb.png)

in console:
![image](https://user-images.githubusercontent.com/8703531/106166874-a91de300-619d-11eb-822f-0913530bff71.png)

Is this Terminus or Scoop problem?

**Comment by issaclin32** [comment]
`terminus` is deprecated (replaced by `tabby`)
