### ISSUE TITLE
libreoffice-fresh fails if MSIEXTRACT_USE_LESSMSI isn't explicitly set

### ISSUE THREAD

**Issue by pensive-fuzz** [ScoopInstaller/Extras#5682]
I was still running into the same issues with libreoffice-fresh that others mentioned in #5661. Playing around with [Ash258's reply](https://github.com/lukesampson/scoop-extras/issues/5661#issuecomment-777221404) I believe I found the issue.

If you set `MSIEXTRACT_USE_LESSMSI` to `$true` or `$false` the install works. However, if it isn't explicitly set (which to my knowledge never happens until you explicitly set it and is the source of the problem) you error with:

```
Could not find 'LibreOffice'! (error 16)
At C:\Users\USER\scoop\apps\scoop\current\lib\core.ps1:510 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find 'LibreOffice'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'LibreOffice'! (error 16)
```

**Comment by issaclin32** [comment]
@pensive-fuzz Does the problem still exist now?
I could not reproduce the problem on **LibreOffice@7.3.2**, but installation works fine.
