### ISSUE TITLE
Signal autoupdater does not support custom install location

### ISSUE THREAD

**Issue by philklc** [ScoopInstaller/Extras#5758]
Scoop apps are installed into `%USERPROFILE%\scoop\apps`, but Signal's installer installs into `%USERPROFILE%\AppData\Local\Programs\signal-desktop\`. When a new version of Signal is released, after clicking the in-app update prompt, a new copy of Signal is installed into the AppData location instead of overwriting Scoop's existing copy with the new version. After updating in this way, launching Signal with the shortcut created by Scoop results in an error due to a database version mismatch.

Since Signal does not seem to support custom install locations, would it be fine if Scoop follows Signal's preferred installation path instead?

**Comment by MunsterPlop** [comment]
Normally you're supposed to use the in-app update if you're managing signal through scoop but signal doesn't have an option to disable auto-update.
It's been discussed here: signalapp/Signal-Desktop#2062 but there hasn't been any news about this feature in a while.
