### ISSUE TITLE
Update: Brave Browser

### ISSUE THREAD

**Issue by cvladan** [ScoopInstaller/Extras#5954]
https://github.com/brave/brave-browser/releases

**Comment by rasa** [comment]
See https://github.com/rasa/scoops/blob/master/bucket/brave.json or even better
https://github.com/ACooper81/scoop-apps/blob/master/bucket/Brave-Portable.json

**Comment by cvladan** [comment]
Thanks

**Comment by fingahoverit** [comment]
Is there any recommandation or special cares about this app?
Or is it just about changing url and checksum ?

**Comment by rasa** [comment]
Yes, a good recommendation is to remove the package here in favor of using either of the two listed [above](https://github.com/lukesampson/scoop-extras/issues/5954#issuecomment-812519400). Better to spread the work around, than to throw all apps into a huge bucket, or two, imo.

**Comment by fingahoverit** [comment]
FYI : New brave installer are no more "portable"
This brave bucket stream is kinda dead then.
You can find portable brave bucket stream with the links above but portable brave is not day to day synchronized with brave releases.
