### ISSUE TITLE
[Request] Add SDL_Image

### ISSUE THREAD

**Issue by boy-in-blue** [ScoopInstaller/Extras#5960]
SDL2 is already included in this bucket. So, it would be convenient to have SDL_Image to go along with it.

https://www.libsdl.org/projects/SDL_image/

**Comment by boy-in-blue** [comment]
And fonts: https://www.libsdl.org/projects/SDL_ttf/

**Comment by g-berthiaume** [comment]
Hi!
I want to re-energize this issues.

SDL is great for teaching game dev on windows.
With the support of this package, student could just use scoop to get started.
```
scoop install pck-config sdl2 sdl-image
```

**Comment by rashil2000** [comment]
Hey @g-berthiaume!

Would you like to make a PR to add your package?

**Comment by g-berthiaume** [comment]
Hi @rashil2000. I can certainly try!

**Comment by rashil2000** [comment]
Yes! 
See here https://scoop-docs.now.sh/docs/concepts/App-Manifests.html#a-simple-example

The docs contain many links to examples - be sure to check them out.

**Comment by g-berthiaume** [comment]
I'm working on it.
While doing so, I made an update to SDL2: https://github.com/ScoopInstaller/Extras/pull/7202

**Comment by g-berthiaume** [comment]
Progress 
- [ ] Adding sdl2_image https://github.com/ScoopInstaller/Extras/pull/7209
- [ ] Adding sdl2_ttf
