### ISSUE TITLE
[Request] Add GeoGebra

### ISSUE THREAD

**Issue by pandaero** [ScoopInstaller/Extras#5979]
Please add GeoGebra (6) to this bucket.

[GeoGebra download page](https://www.geogebra.org/download)

**Comment by davidxuang** [comment]
You may check https://github.com/integzz/scoopet/blob/master/bucket/geogebra.json

**Comment by pandaero** [comment]
cheers!

**Comment by issaclin32** [comment]
[extras/geogebra](https://github.com/ScoopInstaller/Extras/blob/master/bucket/geogebra.json)
