### ISSUE TITLE
tor-browser@10.0.16: "Tor failed to start"

### ISSUE THREAD

**Issue by ferxohn** [ScoopInstaller/Extras#6147]
Hello.

After installing this version, Tor Browser throws an error:

![image](https://user-images.githubusercontent.com/35642546/116763063-141bc780-a9e2-11eb-8022-e4fa5f258ee7.png)

![image](https://user-images.githubusercontent.com/35642546/116763067-1aaa3f00-a9e2-11eb-8d0d-35fcd80c4392.png)

I found that by removing this lines in the JSON manifest, inside the script tag, the problem is solved:

```
"# Persisting profile breaks Tor-Launcher and makes it fallback to config files in Tor folder: move them there",
"movedir \"$dir\\TorBrowser\\Data\\Tor\" \"$dir\\TorBrowser\\Tor\" | Out-Null",
```

I'm not quite sure if this lines are still necessary. So I don't want to create a new pull request without sharing this problem first.

Thank you.

**Comment by HUMORCE** [comment]
#10039
