### ISSUE TITLE
[openvpn@2.4.11] Name / Description unclear, what exactly is this binary?

### ISSUE THREAD

**Issue by RaphaelTarita** [ScoopInstaller/Extras#6192]
I recently needed to install OpenVPN Connect and by running `scoop search` I found the manifest called "openvpn". However, I was not able to determine whether this artifact referred to OpenVPN Access Server (which is the selfhosted VPN Server application) or OpenVPN Connect (which is the client application). The description "A flexible virtual private network (VPN) solution to secure data communications." does not really shine light on that either. 

I then tried to determine it via the current version on scoop, which is 2.4.11. The OpenVPN Access Server [release notes](https://openvpn.net/vpn-server-resources/release-notes/) show that a version 2.4.11 didn't even exist (or atleast it was not documented). I could not find any release notes for OpenVPN Connect, but the most recent version is 3.2.3, which does also not match the version in scoop, 2.4.11.

So what exactly _is_ the `openvpn` manifest? Access Server, Connect, or another application (if yes, which)? As soon as this is determined, I think the name or the description of this manifest should be updated to be clearer about what exactly it represents.

**Comment by issaclin32** [comment]
I am not familiar with the software, but it says **OpenVPN 2.5.5** on the website. Is there a better name for the package?

Also we should definitely add `openvpn-connect`.

![openvpn](https://user-images.githubusercontent.com/27724471/148675445-8d5e462d-34a9-490f-9907-84acbeb81efe.jpg)

![openvpn2](https://user-images.githubusercontent.com/27724471/148675529-f7ceb470-2ea2-4efb-b034-94606628c148.jpg)

**Comment by Xelbayria** [comment]
I've installed OpenVPN-connect v3.3.4.2600. and run it BUT it was blocked by my antivirus because of malwares. I have to ask is it safe to use the software via scoop?

**Comment by HUMORCE** [comment]
@Xelbayria 

**SAFE** in most cases, i mean up to 99%.
and **NO** program can guarantee the security for your OS.

which file(s) are reported?
- shim? (\<SCOOP>\shims\*)
- file(s) in the APPDIR (\<SCOOP>\apps\openvpn-connect\*)

**Comment by Xelbayria** [comment]
ok. Here's the information below: 

C:\Scoop\apps\openvpn-connect\3.3.4.2600\(Command line parameters: "C:\Scoop\apps\openvpn-connect\3.3.4.2600\OpenVPNconnect.exe" -- relaunch --alow-file-access-from-files "C:\Scoop\apps\openvpn-connect\3.3.4.2600\OpenVPNConnect.exe")

That is the reported file.  The Detection ID: SuspiciousBehavior.50F31B667742D14A

I'm not sure if ID helped at all.

**Comment by HUMORCE** [comment]
just over-sensitive.

**Comment by Xelbayria** [comment]
> just over-sensitive.

what do you mean by that?

**Comment by niheaven** [comment]
The reported file is OpenVPN itself, so if you think the software is safe, it is safe. Typically it is reported since it is a VPN.

**Comment by Xelbayria** [comment]
> The reported file is OpenVPN itself, so if you think the software is safe, it is safe. Typically it is reported since it is a VPN.

ah, that's what "over-sensitive" means. Got it

**Comment by HUMORCE** [comment]
@Xelbayria 
i mean the antivirus you are using is over-sensitive, not you.

**Comment by Xelbayria** [comment]
> @Xelbayria i mean the antivirus you are using is over-sensitive, not you.

You really don't need to explain any further.  I already understand what niheaven is saying.
