### ISSUE TITLE
darktable@3.6.0: download via aria2 failed

### ISSUE THREAD

**Issue by netxph** [ScoopInstaller/Extras#6467]
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'darktable' (3.6.0) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 8a8fb7|ERR |       0B/s|C:/Users/netxph/scoop/cache/darktable#3.6.0#https_github.com_darktable-org_darktable_releases_download_release-3.6.0_darktable-3.6.0-win64.exe
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/darktable-org/darktable/releases/download/release-3.6.0/darktable-3.6.0-win64.exe
    referer=https://github.com/darktable-org/darktable/releases/download/release-3.6.0/
    dir=C:\Users\netxph\scoop\cache
    out=darktable#3.6.0#https_github.com_darktable-org_darktable_releases_download_release-3.6.0_darktable-3.6.0-win64.exe

ERROR & 'C:\ProgramData\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\netxph\scoop\cache\darktable.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=12168 --continue --summary-interval 0

**Comment by b-mq** [comment]
It looks like the download URL changed in the subversion (win **3.6.0.1** and osx **3.6.0.3**)

**Win64** https://github.com/darktable-org/darktable/releases/download/release-3.6.0/darktable-3.6.0.1-win64.exe

@netxph you could fix it via changing the "**url**" in the _darktable.json_ file inside <user>\scoop\buckets\extras\bucket\darktable.json

**from**    
"architecture": {
        "64bit": {
            "url": "https://github.com/darktable-org/darktable/releases/download/release-3.6.0/darktable-3.6.0-win64.exe",
            "hash": "aad925988545ff3c50f54243520e8481c695b38b209daa808a490113f6400374"
        }
**to** 
    "architecture": {
        "64bit": {
            "url": "https://github.com/darktable-org/darktable/releases/download/release-3.6.0/darktable-3.6.0.1-win64.exe",
            "hash": "aad925988545ff3c50f54243520e8481c695b38b209daa808a490113f6400374"
        }

**Comment by issaclin32** [comment]
Fixed in https://github.com/ScoopInstaller/Extras/commit/72dcf05c30f40e12341312091ae5df5f1842e0dc
