### ISSUE TITLE
Login issue with jetbrains-toolbox

### ISSUE THREAD

**Issue by liny01-nbsa** [ScoopInstaller/Extras#6499]
Version: (1.21.9547)

When I try to login with JetBrains Account, on the approval-deny screen, clicking Approve button, nothing happens except the button turns grey. Browser did pop up to open with jetbrains-toolbox, however, it doesn't seem to seal the deal to a successful login.

Normal installed one has no issue login.

**Comment by liny01-nbsa** [comment]
This issue still exists for Toolbox version up to 1.21.9712

**Comment by Lutra-Fs** [comment]
jetbrains-toolbox installed via scoop does not create registry entries. 
If you want you may try the following codes:
```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\jetbrains]
@="\"URL: jetbrains Protocol\""
"URL Protocol"="\"\""

[HKEY_CLASSES_ROOT\jetbrains\shell]

[HKEY_CLASSES_ROOT\jetbrains\shell\open]

[HKEY_CLASSES_ROOT\jetbrains\shell\open\command]
@="**replace with your program path**\\jetbrains-toolbox.exe %1"
```
***Replace the path to your actual installation path!***

**Comment by liny01-nbsa** [comment]
Thanks, @Lutra-Fs ! I confirm this works great. Shall the above snippet get generated and included in the output or as a reg file to remind and help users of need. As I find it's needed for login of toolbox via JetBrains account to work properly for my setup.

**Comment by Lutra-Fs** [comment]
Hi, I am not sure how to add it to the manifest or the installation. 
I think it is too long to add to the description.
If we add it to the post-install scripts, I am unsure how to remove it while uninstalling. Furthermore, the protocol registration will be broken if the scoop is in a USB stick (or other portable devices).
I also had a look at the vscode manifest, and I found that their reg files is in the installer, not from outside.  
Pinging @rashil2000 for further help, is there a better way we can suggest the users done?

**Comment by rashil2000** [comment]
You can create files such as install-context.reg and uninstall-context.reg, for example, see here - https://github.com/ScoopInstaller/Extras/tree/master/scripts/vscode

Then you can mention in the manifest note about how to run the reg files if desired.

**Comment by Lutra-Fs** [comment]
will implement soon

**Comment by Lutra-Fs** [comment]
Update: I am not able to make the changes for at least 1 month due to a health issue. If anyone makes the change and creates a PR, that will be good.

**Comment by rashil2000** [comment]
No worries @Lutra-Fs 

Take care :)

**Comment by Lutra-Fs** [comment]
Looks like this issue has been fixed on JetBrains' end. Now every time JetBrains toolbox starts, it will check the protocol registration and start menu folder.

**Comment by rashil2000** [comment]
Should we close this then?

**Comment by Lutra-Fs** [comment]
I think so.

**Comment by devdecrux** [comment]
I am having the same issue as of today. If I install the toolbox app the "normal" way I have no issues login in.
If I installed it through scoop I have to use the auth token. Which ofcourse is such a big deal but I would be very happy if this is resolved somehow.

**Comment by Lutra-Fs** [comment]
> I am having the same issue as of today. If I install the toolbox app the "normal" way I have no issues login in. If I installed it through scoop I have to use the auth token. Which ofcourse is not such a big deal but I would be very happy if this is resolved somehow.
> 
> When I click "log in", a browser window is being opened. Then I click "Approve" and nothing happens. It stays on the message "Waiting for login in the default browser"

https://github.com/ScoopInstaller/Extras/issues/6499#issuecomment-982010106 if you encountered.

**Comment by devdecrux** [comment]
Maybe I don't know how the path should be written, but it's not working for me.
