### ISSUE TITLE
Potplayer | Adding Module folder to persist

### ISSUE THREAD

**Issue by susanonec** [ScoopInstaller/Extras#6544]
I checked the manifest file of potplayer and noticed that Module folder is not in persist directory, which will lead to an error of not finding OpenCodec decoder. And I also noticed that if you run the installer of OpenCodec from potplayer's official site, all it does is extracting opencodec.dll to "your_Potplayer_path\Module\OpenCodec", so I think add this to persist directory can save a lot of work since I think this decoder is important, thanks in advance.

**Comment by rashil2000** [comment]
Hey @susanonec, can you make a PR for your changes?

**Comment by susanonec** [comment]
> 

#7401 
Here I pulled a request, and it's just simply added Module to persist config(I think it's the correct way to persist this directory?).

The thing is, the original installer of Potplayer doesn't include a opencodec decoder, so I was think we can install them on our own if we need one but I don't want it to be removed everytime I update. So maybe it's better to keep the Module directory in the persist?

PS. I don't know why there's a directory "extention" keeped in the persist config, all it has is a directory called extension.

**Comment by susanonec** [comment]
> Hey @susanonec, can you make a PR for your changes?

#7401 Here I made the pull request, simply add the directory name to the persist config.

The thing is, the opencodec decoder is not included in the original installer of Potplayer, so I think we should keep it in that way. But once we installed it on my own I don't want it to be removed after every update. So I think we'd better keep "Module" in this persist config.

PS. I found a name "extention" in the config, but I think this directory should be "extension", maybe it's a redundancy?

**Comment by rashil2000** [comment]
> PS. I found a name "extention" in the config, but I think this directory should be "extension", maybe it's a redundancy?

I feel so. Can you remove it?
