### ISSUE TITLE
discord@0.0.310: autoupdate leads to scoop manifest removal

### ISSUE THREAD

**Issue by valentinpi** [ScoopInstaller/Extras#6596]
This is possibly a duplicate, but I have not found a similar post.

Installing `discord` and running it triggers the auto-updater to run. After that, `scoop` shows the following:
```
PS C:\Users\User> scoop list
...
  discord download *failed*
...
```
```
PS C:\Users\User> scoop status
Scoop is up to date.
These app manifests have been removed:
    discord
These apps failed to install:
    discord
```

**Comment by robinrehbein** [comment]
Yeah, same issue here. Any ideas how to fix?

**Comment by valentinpi** [comment]
@robinrehbein I googled around a bit and it seems one cannot disable Discords autoupdate/it is really hard. So yeah, I don't know.

**Comment by robinrehbein** [comment]
@valentinpi maybe a temporary quick fix is to update the junction of the "current" folder to point to the updated version...

**Comment by jgulotta** [comment]
Previously filed in the main repo: lukesampson/scoop#4355

No solution there either

**Comment by MathewBlock** [comment]
I have a fix for this in the form of an optional script that can configure Discord to disable updates.
I'm preparing a PR right now.
