### ISSUE TITLE
oss-browser

### ISSUE THREAD

**Issue by canbingzt** [ScoopInstaller/Extras#6712]
from the [Readme](https://github.com/aliyun/oss-browser/blob/develop/README-CN.md), newest version is `1.16.0`

**Comment by HUMORCE** [comment]
the manifest performs version checks against the `master` branch, and you are watching the `develop` branch. (the repo sets `develop` as the default branch)

**Comment by HUMORCE** [comment]
the manifest performs version checks following `master` branch, and you are watching the `develop` branch. (the repo sets `develop` as the default branch)
