### ISSUE TITLE
[Request] Add VMware Workstation Player

### ISSUE THREAD

**Issue by lunarwhite** [ScoopInstaller/Extras#6737]
Another awesome virtual machine software program. (free for personal, non-commercial use)

https://www.vmware.com/products/workstation-player.html

> VMware Workstation Player is free for personal, non-commercial use (business and nonprofit use is considered commercial use). If you would like to learn about virtual machines or use them at home, you are welcome to use VMware Workstation Player for free. Students and faculty of accredited educational institutions can use VMware Workstation Player for free if they are members of the VMware Academic Program.

**Comment by ppvnf** [comment]
see https://github.com/ScoopInstaller/Nonportable/issues/87
