### ISSUE TITLE
godot / godot-mono manifest download - switch to github mirror

### ISSUE THREAD

**Issue by YetAnotherCliffhanger** [ScoopInstaller/Extras#6862]
Hello,

Just a suggestion: Could the download location for godot/godot-mono be moved from the "tuxfamily" server to the official github release mirror? The download performance from github is 100+ times faster (no exaggeration! :) ) than from "tuxfamily", where more often than not the download runs into a timeout.

Enclosed are the manifests with the suggested change:

[godot_github_dl_manifests.zip](https://github.com/lukesampson/scoop-extras/files/7164139/godot_github_dl_manifests.zip)

Thanks for a great tool :)

**Comment by rashil2000** [comment]
Hey @YetAnotherCliffhanger :)

Can you send us the manifests in a PR?

**Comment by YetAnotherCliffhanger** [comment]
Hey @rashil2000 ,
Sure - i will do that. Let me just update the changes to the most recent release.
