### ISSUE TITLE
pycharm@2021.2.2: Failed to create virtual environment if run from current folder

### ISSUE THREAD

**Issue by llllllllqq** [ScoopInstaller/Extras#6884]
I installed python from scoop, and pycharm.
Then run pycharm from "C:\Users\MYNAME\scoop\apps\pycharm\current\bin\pycharm64.exe", and create a new project and interpreter, then it show Failed to create virtual environment.
If I clean reinstall pycharm and run it from "C:\Users\MYNAME\scoop\apps\pycharm\2021.2.2\bin\pycharm64.exe", it works fine.

\bin in PATH doesn't matter. I have tested remove it from PATH, nothing help.

**Comment by alealexpro100** [comment]
Issue still exists in pycharm@2021.3.1-213.6461.77.
Found that if I create new project while running from `%USERPROFILE%\scoop\apps\pycharm\2021.3.1-213.6461.77\bin\pycharm64.exe`, it creates needed files in `%APPDATA%\Local\pypa\virtualenv`. 
After that, error `Failed to create virtual environment.` doesn't appear while creating new project running from `%USERPROFILE%\scoop\apps\pycharm\current\bin\pycharm64.exe`, even if I remove all files in `profile` directory.
