### ISSUE TITLE
msiafterburner@4.6.4.16094: hash check failed

### ISSUE THREAD

**Issue by boobayayo** [ScoopInstaller/Extras#6976]
> Installing 'msiafterburner' (4.6.4.16094) [64bit]
MSIAfterburnerSetup.zip (51.8 MB) [===============================================] 100%
Checking hash of MSIAfterburnerSetup.zip ... ERROR Hash check failed!
App:         extras/msiafterburner
URL:         https://download.msi.com/uti_exe/vga/MSIAfterburnerSetup.zip?__token__=exp=zzzz~acl=/*~zzzzzzzz#/dl.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    e71a5b2dd4bf010c6742f8138ba3f6500082c46baf940ba950fe50213d9579e8
Actual:      521cdbe532a8a8dfb3217a4b0b99c6b8f2709b90dcf0d764dbbcbf4b8f1230f9

**Comment by rashil2000** [comment]
Superceded by #7364
