### ISSUE TITLE
How to update (or install) Telegram without error.

### ISSUE THREAD

**Issue by gphg** [ScoopInstaller/Extras#7002]
Telegram has anti-DDoS measurement, even if Telegram itself isn't blocked by your country or region. It might halt your telegram install or updates. 

The error looks something like this:
```
C:\Users\hexat>scoop update telegram
telegram: 3.1.1 -> 3.1.8
Updating one outdated app:
Updating 'telegram' (3.1.1 -> 3.1.8)
Downloading new version
The operation has timed out
At C:\Users\hexat\scoop\apps\scoop\current\lib\install.ps1:130 char:9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : The operation has timed out
```

To fix this is simply access the web site: https://desktop.telegram.org/
Click the link to "Portable version" download: https://desktop.telegram.org/
Then lets your IP indexed on their whitelist database. It will downloads the portable version on your web browser, you can cancel it, then rerun the telegram update (or install),

This is a pain. I have a request to change the bucket url from their remote server into [the GitHub's release page download](https://github.com/telegramdesktop/tdesktop/releases/). From this:
https://github.com/lukesampson/scoop-extras/blob/2a1c22a89f6d367a5f66700819bfbaf53c3dfce7/bucket/telegram.json#L6
Into something like this:
```
https://github.com/telegramdesktop/tdesktop/releases/download/v3.1.8/tportable-x64.3.1.8.zip
https://github.com/telegramdesktop/tdesktop/releases/download/v3.1.8/tportable.3.1.8.zip
```

**Comment by Vedabahu** [comment]
Is it still the same or does it work fine now? Because it works fine for me.
The new persist can be found [here](https://github.com/ScoopInstaller/Extras/blob/master/bucket/telegram.json).
