### ISSUE TITLE
[Request]: 8BitDo Ultimate Software

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7042]
PackageIdentifier: 8bitdoultimatesoftware 
PackageVersion: 1.00
PackageLocale: en-US
Publisher: 8bitdo
PackageName: 8bitdo
License: proprietary
ShortDescription: configuration app for 8bitdo controllers
Installers:

Architecture: x64
InstallerType: zip
InstallerUrl: https://download.8bitdo.com/Ultimate-Software/8BitDo-Ultimate-Software-for-Windows.zip
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by aliesbelik** [comment]
Closing in favor of  #12566.
