### ISSUE TITLE
scoop update; scoop uninstall hwinfo; scoop install hwinfo; hwinfo@7.12-4580: hash check failed

### ISSUE THREAD

**Issue by yagodkin** [ScoopInstaller/Extras#7045]
λ scoop update; scoop uninstall hwinfo; scoop install hwinfo
Updating Scoop...
Updating 'extras' bucket...
Updating 'java' bucket...
Updating 'main' bucket...
Updating 'nirsoft' bucket...
Scoop was updated successfully!
Uninstalling 'hwinfo' ().
'hwinfo' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'hwinfo' (7.12-4580) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 659b68|OK  |    31KiB/s|C:/Users/User/scoop/cache/hwinfo#7.12-4580#https_www.hwinfo.com_files_hwi_712.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of hwi_712.zip ... ERROR Hash check failed!
App:         extras/hwinfo
URL:         https://www.hwinfo.com/files/hwi_712.zip
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    1ca729f1ff7b8fc3c4b4063dc99aa4b79644ce9937ffd0a00dde68cb3f10b9bd
Actual:      0442c098aa986c78d1d159caed4e5bf7a58ca64ca7dac64ea38f6c74e336ba81

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=hwinfo%407.12-4580%3a+hash+check+failed

**Comment by udit** [comment]
Getting same error while updating to 7.14-4610:

```
Updating 'hwinfo' (7.12-4580 -> 7.14-4610)
Downloading new version
Downloading https://www.hwinfo.com/files/hwi_714.zip (-1 B)...

Checking hash of hwi_714.zip ... ERROR Hash check failed!
App:         extras/hwinfo
URL:         https://www.hwinfo.com/files/hwi_714.zip
First bytes: 3C 21 44 4F 43 54 59 50
Expected:    9cafd0d3ac179e44828ca468c910c8ddc587255e9926646dc5ccf62005b516e8
Actual:      e75f2d048b3c137cc7bac995376a983a86626c2c49653d6faaf010da87dc21f1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=hwinfo%407.14-4610%3a+hash+check+failed
```

**Comment by HUMORCE** [comment]
```
> Get-FileHash $env:SCOOP\cache\hwinfo#7.14-4610#https_www.hwinfo.com_files_hwi_714.zip

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          9CAFD0D3AC179E44828CA468C910C8DDC587255E9926646DC5CCF62005B516E8       C:\Users\HUMOR\scoop\cache\hwin…
```

i am sure it can be installed, download this file via curl or browser get same hash value.

please check network settings.

**Comment by rashil2000** [comment]
Facing the same error. The link https://www.hwinfo.com/files/hwi_714.zip is not functional.
