### ISSUE TITLE
Replace google-chrome series broken installer

### ISSUE THREAD

**Issue by Lutra-Fs** [ScoopInstaller/Extras#7096]
Opened as @rashil2000 requested. The affiliated pull request is #7238 now,

**Comment by issaclin32** [comment]
I vote up for adapting @Lutra-Fs 's solution.

This may bring some issues. But it is better than a **obviously broken** one.

We can consider switching to Chrome's official API later, or make our own version if needed.

Another option is to involve @Lutra-Fs 's repo as an affiliation of Scoop, such as the case of [games bucket](https://github.com/Calinou/scoop-games), [nerd-fonts bucket](https://github.com/matthewjberger/scoop-nerd-fonts) or [Java bucket](https://github.com/ScoopInstaller/Java) (previously a repo of *se35710*). Just need to add a few maintainers from Scoop as collaborators.

**Comment by Lutra-Fs** [comment]
> Another option is to involve @Lutra-Fs 's repo as an affiliation of Scoop, such as the case of games bucket, nerd-fonts bucket or Java bucket (previously a repo of se35710). Just need to add a few maintainers from Scoop as collaborators.
If there is anything I can help with, just ping me. My repo is now a fork of Sukka (the original API provider) one with the fix of the problem. It is not a scoop bucket. If the repo needs to be a scoop bucket, we will need to add the relevant part.

**Comment by issaclin32** [comment]
> If the repo needs to be a scoop bucket, we will need to add the relevant part.

Thank you for your great help.
The repo does not have to become a bucket. I just want our maintainers to have write access, 
so that we can fix the problem sooner (even if you are busy).

**Comment by Lutra-Fs** [comment]
> > If the repo needs to be a scoop bucket, we will need to add the relevant part.
> 
> Thank you for your great help. The repo does not have to become a bucket. I just want our maintainers to have write access, so that we can fix the problem sooner in the future (even when you are busy).

Who should be added as a collaborator？I can do it now.

**Comment by issaclin32** [comment]
> Who should be added as a collaborator？I can do it now.

I would suggest the following:
@rasa @niheaven -- They are the early members of *Scoop*. They may not respond quickly but are more experienced.
@stevehipwell @rashil2000 @pratikpc @issaclin32 -- Currently most active members

**Comment by pratikpc** [comment]
Can we not use https://chromeenterprise.google/browser/download/#windows-tab?

Why do we need to use 3rd party sites?

Using the official sites is just safer tbh

**Comment by Jogai** [comment]
This site has an api too: https://chromium.woolyss.com/#api

Its 3rd party too, but its been around for a while.

**Comment by stevehipwell** [comment]
Thanks @Lutra-Fs for the collaboration invite, I'd be happy to help out if this is the approach we're taking.

**Comment by rashil2000** [comment]
> Can we not use https://chromeenterprise.google/browser/download/#windows-tab?
> 
> Why do we need to use 3rd party sites?
> 
> Using the official sites is just safer tbh

I think this is only for stable channel. What about beta, canary, dev etc.?

**Comment by pratikpc** [comment]
@Jogai I also notice that the API is being used by chromium-dev.

It currently states 91.0.4467.0-r869045 as the latest version which isn't exactly true

Is the API reliable? If it is, can you help create a PR to fix the Chrome issue?

Also @Jogai that looks like a primarily Chromium based API. I can't find much regarding Chrome support.

> What about beta, canary, dev etc.?

@rashil2000 we could first start somewhere. For the time being use 3rd party libraries and then move on to more stable and official solutions.

**Comment by rashil2000** [comment]
> @rashil2000 we could first start somewhere. For the time being use 3rd party libraries and then move on to more stable and official solutions.

Yes, that's why we decided to go with @Lutra-Fs's solution :)

**Comment by pratikpc** [comment]
@rashil2000 if we end up using this solution, given this time it is running on GitHub Actions itself, should we fork it as well and bring it under the Scoop organisation?

@Lutra-Fs is well versed with the codebase so @Lutra-Fs probably takes over as primary maintainer in case of future changes being required

We could also check out [VersionHistory API](https://developer.chrome.com/docs/versionhistory/) once to help implement future changes as well

**Comment by rashil2000** [comment]
We can have a generic repository for services like these - creating a separate repo for each app-group (chrome in this case) would not make sense.

**Comment by pratikpc** [comment]
@rashil2000 should we start with google-chrome?

**Comment by rashil2000** [comment]
We can have a folder within that repo called `google-chrome`. But what will we name the repo?

**Comment by issaclin32** [comment]
> We can have a folder within that repo called `google-chrome`. But what will we name the repo?

How about **UpdateTracker**?
It is a blend name, but we can change it later (possibly after the `scoop->scooper` issue is resolved)
