### ISSUE TITLE
angryipscanner request

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7101]
PackageIdentifier: angryipscanner
PackageVersion: 3.7.6
PackageLocale: en-US
Publisher: angryipscanner
PackageName: angryipscanner
License: open source
ShortDescription: network scanner
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://github.com/angryip/ipscan/releases/download/3.7.6/ipscan-3.7.6-setup.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by rashil2000** [comment]
`scoop install ipscan`
