### ISSUE TITLE
iriun Request 

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7105]
PackageIdentifier: iriun
PackageVersion: 2.6.8
PackageLocale: en-US
Publisher: iriun
PackageName: iriun
License: closed source
ShortDescription: webcam emulator between smartphone and pc
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://1758658189.rsc.cdn77.org/WinWebcam-2.6.8.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by aliesbelik** [comment]
Duplicates #6342.
