### ISSUE TITLE
droidcamobs Request

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7107]
PackageIdentifier: Droidcamobs
PackageVersion: 1.3
PackageLocale: en-US
Publisher: droidcamobs
PackageName: droidcamobs
License: open source
ShortDescription: webcam emulator between smartphone and pc
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://files.dev47apps.net/obs/DroidCamOBS.Setup.1.3.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by Jimimaku** [comment]
> PackageIdentifier: Droidcamobs PackageVersion: 1.3PackageLocale: en-USHerausgeber: droidcamobs Paketname: droidcamobsLizenz: Open SourceKurzbeschreibung: Webcam-Emulator zwischen Smartphone und PCInstallationsprogramme:
> 
> Architektur: x64Installationstyp: exeInstallerUrl:https://files.dev47apps.net/obs/DroidCamOBS.Setup.1.3.exeManifestType: singletonManifestVersion: 1.0.0
