### ISSUE TITLE
[Request] Add tutanota

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7112]
PackageIdentifier: tutanota
PackageVersion: 3.84.11
PackageLocale: en-US
Publisher: tutanota
PackageName: tutanota
License: open source
ShortDescription: open source email client
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://mail.tutanota.com/desktop/tutanota-desktop-win.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by aliesbelik** [comment]
Already fixed in #9577, for duplicated #9565.
