### ISSUE TITLE
[Request] Add protonvpn

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7114]
PackageIdentifier: protonvpn
PackageVersion: 1.20.4
PackageLocale: en-US
Publisher: Protonvpn
PackageName: protonvpn
License: open source
ShortDescription: vpn service provider
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://github.com/ProtonVPN/win-app/releases/download/1.20.4/ProtonVPN_win_v1.20.4.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by nagromc** [comment]
Duplicate of #4678
