### ISSUE TITLE
(Request) add Battlenet

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7116]
PackageIdentifier: Battlenet
PackageVersion: 1.3.3
PackageLocale: en-US
Publisher: Blizzard Entertainment
PackageName: Battlenet
License: proprietary
ShortDescription: Blizzard entertainment client app
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://us.battle.net/download/getInstaller?os=win&installer=Battle.net-Setup.exe&id=undefined
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by zachvlat** [comment]
Does anyone find any solution to this?

**Comment by aliesbelik** [comment]
Available in [games](https://github.com/Calinou/scoop-games) bucket, added in Calinou/scoop-games#1035.
