### ISSUE TITLE
(Request) add cisco-webex

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7117]
PackageIdentifier:cisco-webex
PackageVersion: 39.3
PackageLocale: en-US
Publisher: cisco
PackageName: cisco-webex
License: proprietary
ShortDescription: meeting app
Installers:

Architecture: x64
InstallerType: msi
InstallerUrl: https://binaries.webex.com/WebexTeamsDesktop-Windows-Gold/Webex.msi
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by MathewBlock** [comment]
I am working on this, PR incoming shortly.

**Comment by rashil2000** [comment]
Tracked in #5167
