### ISSUE TITLE
(Request) add easyuefi 

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7119]
PackageIdentifier: easyuefi
PackageVersion: 4.6
PackageLocale: en-US
Publisher: hasleo
PackageName: easyuefi
License: proprietary
ShortDescription: partition app
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://www.easyuefi.com/downloads/EasyUEFI_Trial.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by issaclin32** [comment]
We cannot add **paid** apps to official buckets (because we will not be able to check and fix errors regarding to the app)
