### ISSUE TITLE
(Request) add Wechat 

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7160]
PackageIdentifier: Wechat
PackageVersion: 3.3
PackageLocale: en-US
Publisher: Tencent
PackageName: wechat
License: proprietary
ShortDescription: Chinese messaging app
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by SonaliBendre** [comment]
https://github.com/Casuor/AkiWinApps/blob/master/bucket/wechat.json

**Comment by niheaven** [comment]
Use bucket from one of our member: https://github.com/chawyehsu/dorado
