### ISSUE TITLE
(Request) add Kodi

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7164]
PackageIdentifier: Kodi
PackageVersion: 19.1
PackageLocale: en-US
Publisher: Kodi
PackageName: Kodi
License: open source
ShortDescription: open source video player
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://ftp.halifax.rwth-aachen.de/xbmc/releases/windows/win64/kodi-19.1-Matrix-x64.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by felipeqq2** [comment]
Found a manifest [here](https://github.com/Ash258/Shovel-Ash258/blob/main/bucket/Kodi.json).

**Comment by Ash258** [comment]
Do not suggest third-party buckets in official repositories, especially when the bucket/manifest is not compatible with scoop.

Suggesting third-party and unsupervised buckets is security issue and not all users are capable of verifying what they are installing and if it is safe.

**Comment by rashil2000** [comment]
@felipeqq2 instead of pointing to a third party bucket, it will be better if you can make a PR that we can test and verify.
