### ISSUE TITLE
Do non-free-to-use (paid) apps belong to extras?

### ISSUE THREAD

**Issue by telenieko** [ScoopInstaller/Extras#7170]
Triggered by @rashil2000 in [6156](https://github.com/ScoopInstaller/Extras/issues/6156#issuecomment-953852711_):

> I don't think there are any paid applications on Scoop

Do those applications belong to extras? What acceptance criteria shall be applied to freemium and non-free-to-use applications? And.. what happens when a once free to use application ceases to be so... so many questions.

A quick search turned out that there are paid applications in`extras`:

- [FileBot](https://github.com/ScoopInstaller/Extras/blob/master/bucket/filebot.json), via #2708.
- [wavebox10-pro](https://github.com/ScoopInstaller/Extras/blob/master/bucket/wavebox10-pro.json), via #3605
- [renamer](https://github.com/ScoopInstaller/Extras/blob/master/bucket/renamer.json), see #7189 

Though there are several PRs and requests where the concern has been raised which may suggest a discussion/clarification is due to avoid unconsistent criteria by our beloved maintainers (ie: FileBot is in via #2708, registry-workshop is not via #2630) :

- PR
  - imdone, #6156
  - registry-workshop, #5063; which was on #2630
- Requests
  - Glasswire, #6985

Further on, it was previously suggested (2019, by @rasa on #2564) to create a separate bucket (`nonfree`, `paid`). At the time @issaclin32 followed up about that (same #2564) but likes like it had not been done because of lack of permissions to create the repo under the ScoopInstaller org. Maybe this has changed after #4456.

This alternative is consistent with other open source practices, like Debian's non-free repository. It would then have to be decided if that bucket become also "well known" to scoop as `extras` is (specially if FileBot is moved to that eventual new bucket).

So, briefly:

- Do paid apps (trial versions, freemium software, etc) belong to `extras`?
- If not, shall `nonfree` exist inside ScoopInstaller?
- If yes, shall it be made well known to scoop as is `extras` to reduce friction (specialy for users of filebot and/or wavebox10-pro which would then have to be moved)

**Comment by rasa** [comment]
@ScoopInstaller/maintainers Please answer this question:

Should we move the apps in Main/Extras buckets that are correctly labelled Shareware/Proprietary to a new bucket? If so, what should the new bucket be named?:
/polls 'Yes: `NonFree`' 'Yes: `Paid`' 'Yes: `Shareware`' 'No: not worth the trouble'

**Comment by rasa** [comment]
/polls 'Yes: NonFree' 'Yes: Paid' 'Yes: Shareware' 'No: not worth the trouble'

**Comment by niheaven** [comment]
Linux packages manager has a `nonfree` or similar catalog since most of Linux software ARE freeware and adopt FOSS license, but for Windows, this is not the case. Many Windows software are shareware or proprietary that even cannot be shared, so I don't think we could treat them separately.

User use apps that they knew, and could check info with `scoop info xxx`, which shows the license. That's enough.

**Comment by stevehipwell** [comment]
I missed the poll but I'm on the fence between `paid` and it not being worth the effort anyway, so I wouldn't have moved the needle.

**Comment by pratikpc** [comment]
I personally believe if any such decision is taken, it should be taken for new packages only otherwise we break workflows.

Because scoop currently does not have a moved feature

I also am unsure if its worth the effort on its own.

**Comment by telenieko** [comment]
I appears that keeping things simple is the preferred approach, that is: one single repo.

Then just give some guidance on how to fill the license field?

Maybe document somewhere in the lines of:

> For non open source software please specify the kind of Propietary license at play:
> * `Shareware` by [definition](https://en.wikipedia.org/wiki/Shareware) kind of covers: trial versions and freemium
> * `Freeware` [covers](https://en.wikipedia.org/wiki/Freeware) free to use (without limits) but closed source
> Refrain from using the more generic `Propietary` when possible, if unsure raise the question in your pull request.

I will open other issues later about the two longer term proposals of my initial comment (show non-free license label on `scoop search` and extending the `license` field to allow for more detail/notes.
