### ISSUE TITLE
x64dbg@2021-10-25_12-11: download via aria2 failed

### ISSUE THREAD

**Issue by AntonOks** [ScoopInstaller/Extras#7206]
λ  scoop install x64dbg
Installing 'x64dbg' (2021-10-25_12-11) [64bit]
Starting download with aria2 ...
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2021-10-25_12-11.zip
    referer=https://github.com/x64dbg/x64dbg/releases/download/snapshot/
    dir=C:\Users\user\scoop\cache
    out=x64dbg#2021-10-25_12-11#https_github.com_x64dbg_x64dbg_releases_download_snapshot_snapshot_2021-10-25_12-11.zip

ERROR & 'C:\Users\user\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\user\scoop\cache\x64dbg.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=4248 --continue --summary-interval 0 --show-console-readout=false --download-result=hide --max-overall-download-limit=3M

**Comment by rashil2000** [comment]
#7198
