### ISSUE TITLE
Gimp no longer loads after my pull request

### ISSUE THREAD

**Issue by theblobscp** [ScoopInstaller/Extras#7249]
## Bug Report

**Package Name:**  gimp

### Current Behaviour

Gimp's installation process does not work because of the new executable.

### Expected Behaviour

Gimp to install

### Additional context/output

Nope, I don't know PowerShell

### System details

**Windows version:** 10

**OS architecture:** 64 bit

**PowerShell version:** 7.2.0 rc.1

**Comment by pratikpc** [comment]
Additional context/output
Nope, I don't know PowerShell

Can you share screenshots?

**Comment by theblobscp** [comment]
Do you mean of the new .exe?

**Comment by pratikpc** [comment]
No, the logs of scoop install

**Comment by theblobscp** [comment]
It never ends because of the bug

**Comment by rashil2000** [comment]
Please provide accurate steps to reproduce the problem. We would like to help you, but your comments are not very descriptive.

**Comment by theblobscp** [comment]
The entire setup for the exe is different, breaking gimp. Not much else to say.

**Comment by pratikpc** [comment]
@theblobscp can you share screenshots of the same?

**Comment by issaclin32** [comment]
Works fine for me.

I guess the problem is caused by unstable connection. You can try:
```
scoop uninstall gimp
scoop cache rm *
scoop install gimp
```
and see if it fixes the problem.

log:
```
> scoop install gimp
Installing 'gimp' (2.10.28) [64bit]
Download: (OK):download completed.
Checking hash of gimp-2.10.28-setup.exe ... ok.
Extracting gimp-2.10.28-setup.exe ... done.
Running installer script...
Linking D:\scoop\apps\gimp\current => D:\scoop\apps\gimp\2.10.28
Creating shim for 'gimp-console-2.10'.
Creating shim for 'gimp-console'.
Creating shim for 'gimp'.
Creating shim for 'gimptool-2.0'.
Creating shim for 'gimptool'.
Creating shortcut for GIMP (gimp-2.10.exe)
'gimp' (2.10.28) was installed successfully!
```

**Comment by theblobscp** [comment]
The extraction step isn't working for me, I think it's my system

**Comment by theblobscp** [comment]
Never mind, my pc is just slow. Thanks!
