### ISSUE TITLE
[Request] add opentoonz

### ISSUE THREAD

**Issue by AbedSHP** [ScoopInstaller/Extras#7252]
### Information

**Name:** [opentoonz]

**Description:** [Software for the production of 2D animation.]

**Homepage:** [https://opentoonz.github.io/e/]

**Download link(s):** [https://opentoonz.github.io/e/download/opentoonz.html]

**Some indication of popularity/repute:** [https://github.com/opentoonz/opentoonz]

**Comment by pratikpc** [comment]
@AbedSHP could you create a PR for the same?

**Comment by rashil2000** [comment]
#5270
