### ISSUE TITLE
Can't install makehuman

### ISSUE THREAD

**Issue by synthercat** [ScoopInstaller/Extras#7260]
**> scoop status**
Scoop is up to date.
These app manifests have been removed:
    makehuman
These apps failed to install:
    makehuman
**> scoop install makehuman**
ERROR It looks like a previous installation of makehuman failed.
Run 'scoop uninstall makehuman' before retrying the install.
WARN  'makehuman' (1.2.0) is already installed.
Use 'scoop update makehuman' to install a new version.
PS C:\Users\synth\scoop\apps\scoop\current> scoop uninstall makehuman
Uninstalling 'makehuman' (1.2.0).
Unlinking ~\scoop\apps\makehuman\current
Removing older version (1.1.1).
'makehuman' was uninstalled.
PS C:\Users\synth\scoop\apps\scoop\current> scoop install makehuman
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'makehuman' (1.2.0) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: c58fc4|OK  |   2.9MiB/s|C:/Users/synth/scoop/cache/makehuman#1.2.0#http_download.tuxfamily.org_makehuman_releases_makehuman-community-1.2.0-windows.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of makehuman-community-1.2.0-windows.zip ... ok.
Extracting makehuman-community-1.2.0-windows.zip ... done.
Linking ~\scoop\apps\makehuman\current => ~\scoop\apps\makehuman\1.2.0
Creating shim for 'makehuman'.
Can't shim 'makehuman.exe': File doesn't exist.

**Comment by pratikpc** [comment]
Can you show what is present in this folder?

> ~\scoop\apps\makehuman\1.2.0

**Comment by synthercat** [comment]
Folder "addons_for_blender_28x" (4 zip files in here)
makehuman-community-1.2.0-windows.exe
README.txt

Should I remove the folder and retry? I haven't done anything weird, just
>scoop update *

And when it faild I did a
>scoop cache rm 
just in case

After all that I gave the commands of the original post

**Comment by pratikpc** [comment]
@synthercat could you check what this file is?
> makehuman-community-1.2.0-windows.exe

Is it a setup or is it what you would expect to get when you run makehuman.exe?

**Comment by synthercat** [comment]
It's the installation executable. Should I install it manually?

**Comment by pratikpc** [comment]
For the time being

It looks like makehuman has changed its installation file.

**Comment by pratikpc** [comment]
@synthercat would you be willing to assist?

**Comment by synthercat** [comment]
Of course. What do you want?

**Comment by pratikpc** [comment]
@synthercat we would need someone to update the manifest to support the new release model of makehuman

https://github.com/ScoopInstaller/Extras/blob/master/bucket/makehuman.json

@rashil2000 @issaclin32 it looks like we need to fix this ASAP.

**Comment by synthercat** [comment]
Of course. I'll make the commit now, I virus checked the file with Kaspersky (just in case). I don't understand? They changed the file with no version numbering? 

Also by "hash"
Are you guys using SHA256? or any other? I need to know so that I update with the correct one!

**Comment by pratikpc** [comment]
Here the hashes are correct and do not need changes.

We just need to add a pre-install step to extract from the Installer exe.

It looks like there was a issue in the update from 1.1.1 to 1.2.0 #7212  which caused breakage

@Valinor could you help out?

**Comment by Valinor** [comment]
@pratikpc I will check and update the manifest. Thanks for reporting @synthercat

**Comment by pratikpc** [comment]
@synthercat can you check once more?

**Comment by synthercat** [comment]
All fine now! 👍

**Comment by synthercat** [comment]
Thank you
