### ISSUE TITLE
lazarus: post-install works for 64bit package only

### ISSUE THREAD

**Issue by rdipardo** [ScoopInstaller/Extras#7268]
## Bug Report

**Package Name:** lazarus (2.0.12) {32bit}

_I found no existing ticket apart from [this old PR](https://github.com/ScoopInstaller/Extras/pull/4244), which does not address the current issue_

### Current Behaviour

The post-install step invariably calls the 64bit version of `fpcmkcfg.exe`:

https://github.com/ScoopInstaller/Extras/blob/53e014cbf04e4d692cccfe1fc7cc60c25f79e816/bucket/lazarus.json#L22

This prevents the 32bit package from being configured automatically by scoop.

### Expected Behaviour

The path to `fpcmkcfg.exe` should depend on architecture so the configuration can be automatic for both the 32- and 64bit packages.

### Additional context/output

```
PS C:\Users\Rob> scoop install --arch 32bit lazarus
Installing 'lazarus' (2.0.12) [32bit]
lazarus-2.0.12-fpc-3.2.0-win32.exe (160.8 MB) [===================================================================================================================================] 100%
Checking hash of lazarus-2.0.12-fpc-3.2.0-win32.exe ... ok.
Extracting lazarus-2.0.12-fpc-3.2.0-win32.exe ... done.
Linking ~\scoop\apps\lazarus\current => ~\scoop\apps\lazarus\2.0.12
Creating shortcut for Lazarus (lazarus.exe)
Creating shortcut for Lazarus (debug) (startlazarus.exe)
Running post-install script...
& : The term 'C:\Users\Rob\scoop\apps\lazarus\current\fpc\3.2.0\bin\x86_64-win64\fpcmkcfg.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:3 char:3
+ & "$fpcdir\bin\x86_64-win64\fpcmkcfg.exe" -d "basepath=$fpcdir" -o "$ ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Rob\...it\fpcmkcfg.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

'lazarus' (2.0.12) was installed successfully!
```

### Possible Solution

After installing the 32bit package, manually generate the config:

```powershell
cd $env:userprofile\scoop\apps\lazarus\current\fpc\3.2.0\bin\i386-win32
fpcmkcfg.exe -o fpc.cfg
```

### System details

**Windows version:** 10.0.22000.282

**OS architecture:** 64bit

**PowerShell version:** 5.1.22000.282

**Additional software:** Windows Terminal (1.11.2921.0)

**Comment by rashil2000** [comment]
Yes, this is indeed a bug in manifest. Would you like to submit a fix? (I suppose you're more familiar with lazarus)

**Comment by rdipardo** [comment]
Submitted: #7298
