### ISSUE TITLE
x64dbg: Should Scoop use Sourceforge instead of Github?

### ISSUE THREAD

**Issue by infomaniac50** [ScoopInstaller/Extras#7276]
## Bug Report

**Package Name:** x64dbg

### Current Behaviour

Scoop currently tries to fetch this package from Github but all releases except for the latest are deleted. When releases are deleted scoop receives a 404 error until the repo gets updated.

### Possible Solution

I don't know if Scoop has anything against using Sourceforge. There are other manifests that use Sourceforge. I could convert this one using one of the others as a template.

**Related issues**

- #7198
- #7206
- #7275

**Comment by infomaniac50** [comment]
Github didn't like it in the past if you uploaded gigabytes of releases.

There are archives with all releases as long as I can maintain at:

- https://sourceforge.net/projects/x64dbg/files/snapshots/
- https://osdn.net/projects/x64dbg/storage/snapshots/

_Originally posted by @mrexodia in https://github.com/x64dbg/x64dbg/issues/2207#issuecomment-524089905_

**Comment by rashil2000** [comment]
Hey @infomaniac50, thanks for digging in! We have nothing against SourceForge - it will be great if you could switch to it in your PR (earlier discussion at #7207)

**Comment by infomaniac50** [comment]
Sourceforge should work now. I don't think I can run the /verify command.
