### ISSUE TITLE
[Request] Neochat

### ISSUE THREAD

**Issue by SViN24** [ScoopInstaller/Extras#7283]
### Information

**Name:** neochat

**Description:** neochat is a matrix client by KDE, it also has an active windows port since it is multiplatform.

**Homepage:** main git repo: https://invent.kde.org/network/neochat

**Download link(s):** build repo https://binary-factory.kde.org/job/NeoChat_Nightly_win64/

**Some indication of popularity/repute:** in the github mirror repo there are 72 stars, in the private repo there is a healthy amount of issues(157 active,314 closed) and activity.

**Comment by pratikpc** [comment]
> A stable release is available for download for Linux distributions.

> Nightly builds for Windows, MacOS and AppImages can also be downloaded from the binary factory.

No stable release for Windows?

**Comment by SViN24** [comment]
yes similarly to other KDE applications with ports to windows(see okular which is included in the scoop repos) it does not have a stable build as of yet.

**Comment by rashil2000** [comment]
Then this should go in either Nightlies or Versions bucket

**Comment by rashil2000** [comment]
No worries. Copy the issue description from here to there.

**Comment by tech189** [comment]
I have made a manifest for NeoChat, but I'm wondering which bucket it should go in. We already have a lot of nightly apps in Versions, should they be moved to the Nightlies bucket? Or does it slow down scoop autoupdate/search if apps are in many different buckets that it has to check each time?

**Comment by rashil2000** [comment]
Nightlies bucket is no longer recommended/used. All nightly apps should be submitted to Versions.
