### ISSUE TITLE
[Request] Impregnate

### ISSUE THREAD

**Issue by Cr3atable** [ScoopInstaller/Extras#7290]
## Package Request
Add Impregnate (https://github.com/Cumcord/Impregnate).

### Information
Impregnate is the official installer for the Cumcord Discord client modification.

**Name:**
Impregnate

**Description:**
Impregnate is the official installer for the Cumcord Discord client modification.

**Homepage:**
https://cumcord.com/#install
https://github.com/Cumcord/Impregnate/releases

**Download link:**
https://github.com/Cumcord/Impregnate/releases/latest

**Some indication of popularity/repute:**
https://github.com/Cumcord/Cumcord repo has 61 stars.

**Comment by Cr3atable** [comment]
A Cumcord maintainer has made a scoop bucket with Impregnate included if you would like to use it for reference: https://github.com/lexisother/bukkit/blob/master/bucket/impregnate.json

**Comment by rashil2000** [comment]
Great, would you like to send a PR?

**Comment by Cr3atable** [comment]
> Great, would you like to send a PR?

Yep, submitted at #7303
