### ISSUE TITLE
nvcleanstall@1.11.0: Download failed

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Extras#7295]
Download failed! 

---

I can see nothing changed with the resulting download link.

What I get when downloading it manually from their website is this: 

https://nl2-dl.techpowerup.com/files/zExbNGfEY47Yf6N97tXIiQ/1636609014/NVCleanstall_1.11.0.exe

So nothing seems to be changed other than the fact that downloading creates a unique ID. 

So far I haven't figured out how to circumvent this and make a static download link for use with Scoop.

**Comment by rashil2000** [comment]
What is the output of `scoop config SCOOP_REPO`?


Unable to reproduce. The link gives 404 in the browser, but on Scoop, it works:

![image](https://user-images.githubusercontent.com/46838874/141168927-f36c1231-cede-4634-b464-c777962cc05e.png)

**Comment by RavenMacDaddy** [comment]
Using the Shovel fork from @Ash258 [here](https://github.com/Ash258/Shovel-Ash258), but I'm not sure that's the reason.

Rather I've previously had applications not install cause I don't have Scoop in its usual spot; C:\Users\<user>\scoop right?

**Comment by Ash258** [comment]
https://github.com/ScoopInstaller/Extras/issues/6931#issuecomment-930429181
