### ISSUE TITLE
streamlabs-obs@1.6.2: download via aria2 failed

### ISSUE THREAD

**Issue by namv22** [ScoopInstaller/Extras#7300]
> Updating 'streamlabs-obs' (1.6.1 -> 1.6.2)
> Downloading new version
> Starting download with aria2 ...
> Download: 11/11 11:56:22 [ERROR] CUID#8 - Download aborted. URI=https://slobs-cdn.streamlabs.com/Streamlabs+Download: Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operaDownload: Download Results:
> Download: gid   |stat|avg speed  |path/URI
> Download: ======+====+===========+=======================================================
> Download: 738fb1|ERR |       0B/s|C:/Users/namv2/scoop/cache/streamlabs-obs#1.6.2#https_slobs-cdn.streamlabs.com_Streamlabs_OBS_Setup_1.6.2.exe_dl.7z
> Download: Status Legend:
> Download: (ERR):error occurred.
> Download: aria2 will resume download if the transfer is restarted.
> Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.     
> 
> ERROR Download failed! (Error 1) An unknown error occurred
> ERROR https://slobs-cdn.streamlabs.com/Streamlabs+OBS+Setup+1.6.2.exe#/dl.7z
>     referer=https://slobs-cdn.streamlabs.com/Streamlabs+OBS+Setup+1.6.2.exe#/
>     dir=C:\Users\namv2\scoop\cache
>     out=streamlabs-obs#1.6.2#https_slobs-cdn.streamlabs.com_Streamlabs_OBS_Setup_1.6.2.exe_dl.7z
> 
> ERROR & 'C:\ProgramData\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\namv2\scoop\cache\streamlabs-obs.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=20036 --continue --summary-interval 0

Probably a problem with the link

**Comment by rashil2000** [comment]
Unable to reproduce
