### ISSUE TITLE
install path VidCod error

### ISSUE THREAD

**Issue by candrapersada** [ScoopInstaller/Extras#7302]
why install VidCod error
```
Get-Content : Cannot find path 'D:\Applications\Scoop\apps\vidcoder\6.41\VidCod
er.exe.config' because it does not exist.
At line:1 char:17
+ $config = [xml](Get-Content "$dir\VidCoder.exe.config")
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Applications...oder.exe.conf
   ig:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetCo
   ntentCommand

You cannot call a method on a null-valued expression.
At line:2 char:1
+ $elem = $config.CreateElement('add')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At line:3 char:1
+ $elem.SetAttribute('key', 'SettingsDirectory')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At line:4 char:1
+ $elem.SetAttribute('value', "$persist_dir\home")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At line:5 char:1
+ $config.configuration.appSettings.appendChild($elem) | Out-Null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At line:6 char:1
+ $config.Save("$dir\VidCoder.exe.config")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

```

**Comment by rashil2000** [comment]
Edit your issue to fill out the Bug Report template, or the issue will be closed.

**Comment by phanirithvij** [comment]
Can reproduce the bug

```powershell
scoop install vidcoder
Installing 'vidcoder' (6.44) [64bit]
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: a96dbb|OK  |   8.3MiB/s|C:/Users/Rithvij/scoop/cache/vidcoder#6.44#https_github.com_RandomEngy_VidCoder_releases_download_v6.44_VidCoder-6.44-Po
rtable.exe_dl.7z
Download: Status Legend:
Download: (OK):download completed.
Checking hash of VidCoder-6.44-Portable.exe ... ok.
Extracting dl.7z ... done.
Running pre-install script...
Get-Content: Cannot find path 'C:\Users\Rithvij\scoop\apps\vidcoder\6.44\VidCoder.exe.config' because it does not exist.
InvalidOperation:
Line |
   2 |  $elem = $config.CreateElement('add')
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation:
Line |
   3 |  $elem.SetAttribute('key', 'SettingsDirectory')
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation:
Line |
   4 |  $elem.SetAttribute('value', "$persist_dir\home")
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation:
Line |
   5 |  $config.configuration.appSettings.appendChild($elem) | Out-Null
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
InvalidOperation:
Line |
   6 |  $config.Save("$dir\VidCoder.exe.config")
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
```

**Comment by rashil2000** [comment]
Can you make a PR for fixing it?

**Comment by candrapersada** [comment]
No

**Comment by amreus** [comment]
VidCoder appears to persist its settings in a `sqlite` database in `%APPDATA%\VidCoder.sqlite`.

Is there any reason to have the `pre_install` or `persist` sections in the scoop manifest?

**Comment by rashil2000** [comment]
https://github.com/RandomEngy/VidCoder/issues/639#issuecomment-615884800

**Comment by amreus** [comment]
The config file that tells VidCoder to where to store the config databasefile (named `VidCoder.exe.config`) does not exist in the download.  What do you do in this case?  Create it?

**Comment by rashil2000** [comment]
The manifest was added in https://github.com/ScoopInstaller/Extras/pull/3057

I'm not really familiar with the software, I just searched their bug tracker for relevant links. I'd suggest opening an issue there to ask the author.

**Comment by amreus** [comment]
> I'm not really familiar with the software

I'm the same - not really interested in VidCode so much as improving the quality of the buckets. 

To me it is only a minor issue that VidCode uses the `%APPDATA%` folder.

**Comment by amreus** [comment]
@rashil2000, How this is fixed depends on how important "strict" portability is for `scoop`?

I'll start by saying VidCoder is not "strictly" portable. It will always create log files in the `%APPDATA%\VidCoder` folder.  It is not unprecedented for scoop apps to use the `%APPDATA%` folder.  I don't see it as an issue, but others might.  I don't think strict portability is a core philosophy of scoop.  

To get VidCoder to use scoop's `persist` folder, it must be run using the portable version.  The portable version extracts its files to `%APPDATA%\Temp\` each time it runs. It's not ideal but the config is then stored in the `apps\vidcode\current` folder next to the executable, which can then be persisted. 

If it is acceptable for VidCoder to store its config in `%APPDATA%\VidCoder`, we can permanently extract the files to `apps\vidcoder\current\` which would just save startup time by skipping the extraction.

@RandomEngy - did I get that right?

**Comment by rashil2000** [comment]
Portability is highly preferred, but not a strict requirement.
 
If an application is not able to work portably without breaking stuff, then we should avoid it. There are plenty of applications in the buckets which have no way to become portable.

**Comment by RandomEngy** [comment]
@amreus you got that pretty much right. Though it extracts to `%TEMP%\RarSFX0`, or `%LOCALAPPDATA%\Temp\RarSFX0` . That's the default behavior of the WinRar self-extracting executable.

**Comment by amreus** [comment]
VidCoder portable creates the config file in the same (temporary) folder as the executable. The folder is removed on VidCoder exit. I I can not think of a way to have a persistent config in scoop when using the portable executable.

So the options appear to be

  1) Include VidCoder and allow it to use `%APPDATA%` to store the config file
  2) Include VidCoder but do not have any persistent config for the user
  3) Remove VidCoder from scoop.
 
So getting back to the subject of this issue which is that VidCoder doesn't install at all, I'll submit a pull request for the 1st option with a `note` as it seems the most reasonable compromise.

**Comment by rashil2000** [comment]
Sure, thanks
