### ISSUE TITLE
[Request] xmind8 needs to be upgraded

### ISSUE THREAD

**Issue by Absolves** [ScoopInstaller/Extras#7309]
### Information

**Name:** xmind8

**Description:** The latest version of xmind8 is currently v3.7.9, while the version provided by scoop is v3.7.8.

**Homepage:** https://www.xmind.net/

**Download link(s):** https://dl3.xmind.net/xmind-8-update9-windows.zip

**Comment by rashil2000** [comment]
Can you make a PR for the same?

**Comment by issaclin32** [comment]
solved by #7312
