### ISSUE TITLE
geany@1.38: decompress error

### ISSUE THREAD

**Issue by zoof** [ScoopInstaller/Extras#7310]
`geany` is not installing correctly on my setup.  I have `lessmsi` installed and the system `7zip` installed.  The installation fails with `Extracting dl.7z ... ERROR Exit code was 2!`. Going into the installation folder and manually extracting dl.7z, `7z` is tripping up on a single file: `ERROR: Can not open output file : Access is denied. : .\data\filedefs\filetypes.abc`.

**Comment by pratikpc** [comment]
@zoof can you clear the cache directory and reinstall geany?

**Comment by zoof** [comment]
Yes.  I cleared the geany cache and tried to reinstall with the same error.  Then I cleared the entire cache and tried to reinstall, again with the same error.

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Scoop/issues/4647
