### ISSUE TITLE
[Request] eadesktopapp

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7323]
### Information

**Name:** EADesktopApp

**Description:** [next iteration of ea origin]

**Homepage:** [https://www.ea.com/ea-app-beta]

**Download link(s):** [https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe]

**Some indication of popularity/repute:** [next generation of ea origin client app that publish AAA games]

**Comment by rashil2000** [comment]
This is not a portable application. Make a request to the non-portable bucket - https://github.com/TheRandomLabs/scoop-nonportable
