### ISSUE TITLE
[Request] Rockstar Games Launcher 

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7324]
### Information

**Name:** [rockstargameslauncher]

**Description:** [desktop client for AAA games made by rockstar games]

**Homepage:** [https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe]

**Download link(s):** [URL(s)/link(s)]

**Some indication of popularity/repute:** [it used for connect to rockstar based games.]

**Comment by rashil2000** [comment]
This is not a portable application. Make a request to the non-portable bucket - https://github.com/TheRandomLabs/scoop-nonportable
