### ISSUE TITLE
Scratch install don't work anymore (last update)

### ISSUE THREAD

**Issue by Valinor** [ScoopInstaller/Extras#7338]
## Bug Report

**Scratch**

### Current Behaviour
![image](https://user-images.githubusercontent.com/2079654/141741032-d73e6904-3075-402c-a45d-328b68c56a5e.png)

### Expected Behaviour

Correct installation

### Additional context/output

Tested the downloaded version. It's not an autoextractible .exe like previously. It's a classic .exe which is not extractible with 7zip.

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

**Comment by issaclin32** [comment]
`Scratch 3.27.0 Setup.exe` can be opened with WinRAR 6.02. However, when I extract it by `rar.exe`, it gives me an error saying that *it is not an rar archive*. Anyone have some clue to solve this?

**Comment by phanirithvij** [comment]
@issaclin32 currently there's a messy workaround `winrar.exe x dl.7z .\scratch` but this requires making winrar a dependency.

made these changes

```json
    "url": "https://downloads.scratch.mit.edu/desktop/Scratch%203.27.0%20Setup.exe#/setup.exe",
    "depends": "winrar",
    "pre_install": [
        "$Args = @\"",
        "x -IBCK \"$dir\\setup.exe\" \"$dir\"",
        "\"@",
        "Start-Process -Wait winrar.exe -NoNewWindow -ArgumentList $Args",
        "Remove-Item \"$dir\\setup.exe\""
    ],
```

this runs
`winrar.exe x ..` in background (-IBCK which hides the gui, another bad workaround)

**Comment by issaclin32** [comment]
@phanirithvij Thank you so much for testing it out.
I tried `rar.exe`, but did not work. Never thought using `winrar.exe`. :sweat:

**Comment by phanirithvij** [comment]
Thanks for the quick reply.
I only expanded upon your suggestion, I'm currently busy atm. I hope you can make a pr, merge this?

**Comment by issaclin32** [comment]
>  I hope you can make a pr, merge this?

I will make a PR later.

**Comment by phanirithvij** [comment]
@issaclin32 would appreciate if you review the pr
