### ISSUE TITLE
Installing PowerToys doesn't automatically install .NET Core

### ISSUE THREAD

**Issue by yegle** [ScoopInstaller/Extras#7340]
It looks like powertoys should depend on dotnet-sdk?

![image](https://user-images.githubusercontent.com/146133/85929074-a1443c00-b866-11ea-87c7-0518fac072ee.png)

**Comment by cvladan** [comment]
You must install .NET Runtime version 5, NOT 6
I also had to manually download, as I didn't want to enable "Versions" repository.

Someone should include this in setup procedure.

https://dotnet.microsoft.com/en-us/download/dotnet/5.0/runtime

**Comment by inigohidalgo** [comment]
Just as an update to this in case it helps anybody: I have installed PowerToys v0.64.1 through Scoop and I wasn't able to open the FancyZones editor. I had to install dotnet6-sdk from the versions bucket to get it to run. Specifically `dotnet-sdk-6.0.403-win-x64`
