### ISSUE TITLE
The hash of msiafterburner is strange....

### ISSUE THREAD

**Issue by Nuevo009** [ScoopInstaller/Extras#7364]
## Bug Report

**Package Name:** msiafterburner

### Current Behaviour

A few hours ago `msiafterburner` hash failed and I checked there are similar issues and then I make a PR #7358  to fix it .

But it fails again...The actual hash should be the previous version
```
Installing 'msiafterburner' (4.6.4.16094) [64bit]
MSIAfterburnerSetup.zip (51.7 MB) [===========================================================================] 100%
Checking hash of MSIAfterburnerSetup.zip ... ERROR Hash check failed!
App:         extras/msiafterburner
URL:         https://download.msi.com/uti_exe/vga/MSIAfterburnerSetup.zip?__token__=exp=zzzz~acl=/*~zzzzzzzz#/dl.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    521cdbe532a8a8dfb3217a4b0b99c6b8f2709b90dcf0d764dbbcbf4b8f1230f9
Actual:      e71a5b2dd4bf010c6742f8138ba3f6500082c46baf940ba950fe50213d9579e8
```
This is the exact opposite of the problem I encountered before #7356 . Strange.

### Possible Solution
I am not sure what the problem is, so I dare not simply fetch back.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
```
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      0
```
**Additional software:** [(optional) e.g. ConEmu, Git]

**Comment by Nuevo009** [comment]
I check this package info of chocolatey, their [hash](https://github.com/HunterZ/choco/blob/5d6f9deaded3bc882f6c4f79f79bd2ab4560c719/msiafterburner/tools/chocolateyInstall.ps1#L3) is the same as the current version. It should work, and today I try to install it again.
```
Installing 'MSIAfterburner' (4.6.4.16094) [64bit]
MSIAfterburnerSetup.zip (51.8 MB) [===========================================================================] 100%
Checking hash of MSIAfterburnerSetup.zip ... ok.
Extracting dl.zip ... done.
Running pre-install script...
Linking D:\Programs\Scoop\apps\MSIAfterburner\current => D:\Programs\Scoop\apps\MSIAfterburner\4.6.4.16094
Creating shim for 'MSIAfterburner'.
Creating shortcut for MSI Afterburner (MSIAfterburner.exe)
Persisting Profiles
Running post-install script...
'MSIAfterburner' (4.6.4.16094) was installed successfully!
```

It succeeded.
I will try again later.

**Comment by rashil2000** [comment]
Please make a PR if you're successful

**Comment by Nuevo009** [comment]
MSIAfterburner has updated to 4.6.4.16117(4.6.4 beta 4) but their download URL never changed, the hash before is for [4.6.4.16094 (4.6.4 beta 3)](http://web.archive.org/web/20210910073211/https://www.guru3d.com/files-details/msi-afterburner-beta-download.html). I don't know why they push an old version for me yesterday. But now It should work. And I will make a new PR to fix the version number.

**Comment by Nuevo009** [comment]
PR #7372
