### ISSUE TITLE
format-factory@5.9.0.0: decompress error

### ISSUE THREAD

**Issue by CALMorACT** [ScoopInstaller/Extras#7371]

**Comment by BYJRK** [comment]
same error

**Comment by pratikpc** [comment]
Can you share the full logs?

What is printed on the console?

Screenshots would be helpful

**Comment by issaclin32** [comment]
**Format Factory** changed their installer. Unfortunately I can't find a way to extract it properly.

I have [downgraded to the last working version, and disabled update](https://github.com/ScoopInstaller/Extras/commit/001a67f10c3b89dc84148a726f1edc913993fa2d).

Will work on that if we can find a way to extract it.

```
FORMAT-FACTORY#5.9.0.0#HTTP_PUBLIC.PCFREETIME.COM_FFSETUP5.9.0.0.EXE_DL
│  DynActsBLL.dll
│  GenericSetup.exe  -> This file cannot be further extracted.
│  GenericSetup.exe.config
│
├─de
│      GenericSetup.resources.dll
│
├─es
│      GenericSetup.resources.dll
│
├─fr
│      GenericSetup.resources.dll
├─it
│      GenericSetup.resources.dll
│
├─pt
│      GenericSetup.resources.dll
│
└─ru
        GenericSetup.resources.dll
```
