### ISSUE TITLE
potplayer＠211118: hash check failed

### ISSUE THREAD

**Issue by Supremesir** [ScoopInstaller/Extras#7387]
Checking hash of PotPlayerSetup64.exe ... ERROR Hash check failed!
App:         extras/potplayer
URL:         https://t1.daumcdn.net/potplayer/PotPlayer/Version/211118/PotPlayerSetup64.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    fd20ec25bd4d402766f78ef3971d03f23b7b15a5389bdee6ca6d84a149c03579
Actual:      47b26cde535fb5f46a3e4cd0b28c4df95386655492b597a54d8a2f7ea82b8409

**Comment by phanirithvij** [comment]
Can reproduce

**Comment by phanirithvij** [comment]
@issaclin32 can you add the verify label for this issue, I think github-actions will take care of the rest?

**Comment by issaclin32** [comment]
Fixed in https://github.com/ScoopInstaller/Extras/commit/f39b4b8361ce5c0bdc9c9e665b6e87e6d4086bb6

Github actions has been removed by Ash258 recently.
Otherwise it should automatically varify the issue.
