### ISSUE TITLE
pcem@17: download via aria2 failed

### ISSUE THREAD

**Issue by grisha765** [ScoopInstaller/Extras#7429]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://pcem-emulator.co.uk/files/PCemV17Win.zip
    referer=https://pcem-emulator.co.uk/files/
    dir=C:\Users\grisha\scoop\cache
    out=pcem#17#https_pcem-emulator.co.uk_files_PCemV17Win.zip

ERROR & 'C:\Users\grisha\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\grisha\scoop\cache\pcem.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6600 --continue --summary-interval=0 --auto-save-interval=1

**Comment by Lutra-Fs** [comment]
I think we can do nothing about this. It is an upstream issue. The certificate is expired, so it cannot be accessed by default for security reasons. @rashil2000, should we better remove pcem temporarily until it has a new maintainer? I can see the website shows that the main maintainer declared that he decided to quit the development (See https://pcem-emulator.co.uk/index.html, note that the cert is expired)
![image](https://user-images.githubusercontent.com/36790218/143726725-053a21c6-cbe5-4ca1-9b21-8c17e0eb2c00.png)

**Comment by rashil2000** [comment]
Thanks for looking it up @Lutra-Fs!

Maybe we can change to http for the URLs for now and add a note in the manifest about its deprecation? That will be a better workaround for now.
