### ISSUE TITLE
disk2vhd.exe doesn't work on 64 bit windows 10 (need disk2vhd64.exe also)

### ISSUE THREAD

**Issue by TonyApuzzo** [ScoopInstaller/Extras#7431]
## Bug Report

**Package Name:** sysinternals

### Current Behaviour

disk2vhd fails to launch on 64bit windows x86-64 architectures

### Expected Behaviour

disk2vhd64.exe should be installed / launched on 64 bit systems rather than disk2vhd.exe which is the 32 bit version

### Additional context/output

when running `disk2vhd.exe` or `disk2vhd.ps1` the following error popup is shown:

```
---------------------------
Disk2Vhd
---------------------------
Error launching 64-bit version: The system cannot find the file specified.
---------------------------
OK   
---------------------------
```

### Possible Solution

It seems that the disk2vhd64.exe should be installed instead of or in addition to disk2vhd.exe for 64 bit windows.

### System details

**Windows version:** [e.g. 7, 8, 10]
Window 10 21H2

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:**  $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      0

Same error happens with native PS 5.1

**Additional software:** [(optional) e.g. ConEmu, Git]

Windows Terminal

**Comment by rashil2000** [comment]
Hey, can you make a PR for the fix?
