### ISSUE TITLE
deepl: package is upgrading and downgrading again and again

### ISSUE THREAD

**Issue by Lutra-Fs** [ScoopInstaller/Extras#7444]
## Bug Report

**Package Name:** deepl

### Current Behaviour

the package is changing between the newest 2 versions.

### Additional context/output

![网页捕获_30-11-2021_133114_github com](https://user-images.githubusercontent.com/36790218/143975248-f3ba8eea-c42b-4f2d-90f1-116091b7c6e8.jpeg)

**Comment by niheaven** [comment]
This is due to A-B test or CDN problem, and unfortunately there is no way to solve it.
