### ISSUE TITLE
linphone@4.3.2: hash check failed

### ISSUE THREAD

**Issue by donsequitur** [ScoopInstaller/Extras#7457]
I see a recent ticket #7286 for what appears to be the same version (2.3.2) but this is currently failing hash check for me

Checking hash of Linphone-4.3.2-win32.exe ... ERROR Hash check failed!
App:         extras/linphone
URL:         https://www.linphone.org/releases/windows/app/Linphone-4.3.2-win32.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    23ccc2b6d21fcfc13d2f75ed5b6af55eb145ee66af5767b3667bfc4a4c3e8c3b
Actual:      494c9eb3942fd48354d244549e91febb587f965a06834b8eae48f75909eb64ad

**Comment by HUMORCE** [comment]
```
> scoop install linphone
Installing 'linphone' (4.3.2) [64bit]
Linphone-4.3.2-win32.exe (57.9 MB) [==========================================================================] 100%
Checking hash of Linphone-4.3.2-win32.exe ... ERROR Hash check failed!
App:         extras/linphone
URL:         https://www.linphone.org/releases/windows/app/Linphone-4.3.2-win32.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    23ccc2b6d21fcfc13d2f75ed5b6af55eb145ee66af5767b3667bfc4a4c3e8c3b
Actual:      f086b0c83cf396499766bff1a84d715141f6ef3a91fa093c9d9384816bb330f4
```
