### ISSUE TITLE
[Request] AHK v1→v2 converter

### ISSUE THREAD

**Issue by eugenesvk** [ScoopInstaller/Extras#7458]
## Package Request

Now that we have the new version of [AutoHotkey v2](https://github.com/ScoopInstaller/Extras/blob/master/bucket/autohotkey2.json), it might be beneficial to add a syntax converter from v1 to v2

__Question 1__: is it possible to track updates for GitHub projects without releases, e.g. via checking latest commit's date? (otherwise we might need to ask the author to make releases from time to time)
__Question 2__: is it possible to add a "soft" dependency to AutoHotkey v2, i.e. suggest to the user on installation of AutoHotkey v2 that he might also want to install this converter for his old scripts?

### Information

**Name:** AHK-v2-script-converter

**Description:** Automatically converts v1 scripts from AutoHotkey to the new syntax introduced with v2

**Homepage:** https://github.com/mmikeww/AHK-v2-script-converter

**Download link(s):** There are no releases, so it's just a master's branch download https://github.com/mmikeww/AHK-v2-script-converter/archive/refs/heads/master.zip

**Some indication of popularity/repute:** ~13k views on AHK forums, only 30 stars on GitHub

**Comment by rashil2000** [comment]
> is it possible to track updates for GitHub projects without releases, e.g. via checking latest commit's date? (otherwise we might need to ask the author to make releases from time to time)

No, if there are no releases, it will become a nightly app, suitable for Versions bucket.

> is it possible to add a "soft" dependency to AutoHotkey v2, i.e. suggest to the user on installation of AutoHotkey v2 that he might also want to install this converter for his old scripts?

Yes, by using the `suggest` field in manifest.

This is still a work in progress tool, I'd recommend not adding it unless the author makes the first stable release.

**Comment by eugenesvk** [comment]
> No, if there are no releases, it will become a nightly app, suitable for Versions bucket.

Ok, but how would that check for updates in such a case? Do you have a manifest example with git master? The few nightly manifests I've checked still have a rule that points to released binaries with different filenames (that either have a different hash in its name or something), while with git master the `.zip` url is the same, so the only indication of any change would be a new commit. Is there a rule that allows to check for that?

> This is still a work in progress tool, I'd recommend not adding it unless the author makes the first stable release.

Ok, maybe I'd check with the author re. how ready he feels his converter is

**Comment by rashil2000** [comment]
> while with git master the .zip url is the same, so the only indication of any change would be a new commit. Is there a rule that allows to check for that?

We don't need a rule for it. Every time a user downloads the app, it will get the latest commit. There will be no hash in the manifest to verify or update.

**Comment by eugenesvk** [comment]
> There will be no hash in the manifest to verify or update.

Sorry, still a bit confused: then how does the user update it? Would scoop redownload this app on every scoop update (which is fine for nightlies that change all the time, but might not be great for a rarely changed app without releases)?

**Comment by rashil2000** [comment]
> then how does the user update it?

`scoop update <app> --force`. You will have to do this, because the manifest is still the same, but the content to which the URL points is different every time

**Comment by eugenesvk** [comment]
> You will have to do this

Oh, ok, thanks for the clarification, so the are no check mechanisms outside of a file name/content change that signal that the content is new

**Comment by rashil2000** [comment]
Correct

**Comment by eugenesvk** [comment]
The dev also feels it might not be ready yet, so I guess let the users find and evaluate it on their own :)
