### ISSUE TITLE
[Request] Add MinGW MinGW dev libraries for SDL2

### ISSUE THREAD

**Issue by cruelnoise** [ScoopInstaller/Extras#7461]
### Information

**Name:** sdl2 (maybe a -mingw suffix?)

**Description:** Scoop currently only provides Visual C++ dev libraries for SDL2. I would like to have the option to download the MinGW libraries using Scoop.

**Homepage:** http://libsdl.org/index.php

**Download link(s):** http://libsdl.org/release/SDL2-devel-2.0.18-mingw.tar.gz

**Some indication of popularity/repute:**

**Comment by rashil2000** [comment]
Can you make a PR for the same?

**Comment by cruelnoise** [comment]
I wish I could, but I don't know anything about this sort of thing.

**Comment by rashil2000** [comment]
You can refer the existing sdl2 manifest itself

**Comment by rashil2000** [comment]
Tracked in #7867
