### ISSUE TITLE
Standard Notes 3.9.5 update fails

### ISSUE THREAD

**Issue by gregbeck** [ScoopInstaller/Extras#7469]
## Bug Report

**Package Name:** standardnotes

### Current Behaviour

404 error when updating to 3.9.5

```powershell
Updating 'standardnotes' (3.8.21 -> 3.9.5)
Downloading new version
OperationStopped: C:\Users\greg\scoop\apps\scoop\current\lib\install.ps1:130
Line |
 130 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.
```

### Expected Behaviour

Application updates successfully

### Possible Solution

URL is missing -x64. 
Current -> `https://github.com/standardnotes/desktop/releases/download/v3.9.5/standard-notes-3.9.5-win.exe`
Actual -> `https://github.com/standardnotes/desktop/releases/download/v3.9.5/standard-notes-3.9.5-win-x64.exe`

I am also getting a different hash for the download. 
```powershell
> Get-FileHash -Path "standard-notes-3.9.5-win-x64.exe" -Algorithm SHA512 | fl

Algorithm : SHA512
Hash      : ACD38CEC621CBB7BE70C3DC6653BE7CF362B4A5F4C7B7C3B71F0593E700A506C3B3CB74D63EAF15A7E57C303E16ACC0FC061B41A4CAAE2443B962900A0D56446
```

### System details

**Windows version:** [e.g. 7, 8, 10]
10
**OS architecture:** [e.g. 32bit, 64bit]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2

**Comment by rashil2000** [comment]
Can you make a PR for the fix?

**Comment by gregbeck** [comment]
I created a PR. I am not that familiar with the process. Please let me know if there is something I missed.
