### ISSUE TITLE
kdiff3 is not really portable

### ISSUE THREAD

**Issue by wangzq** [ScoopInstaller/Extras#748]
Just installed kdiff3 via this bucket and found it is not working because of missing QT runtime. According to https://mail.kde.org/pipermail/kde-doc-english/2012-February/006852.html kdiff3 is not really portable.

**Comment by wangzq** [comment]
Compared the installed copy and found it contains a subfolder named `plugins` in the `bin` folder which is missing from scoop-installed copy, the key file is `bin\plugins\platforms\qwindows.dll`. Apparently just extracting the exe file as 7z file will not create this `plugins` subfolder. Not sure how to fix it.

**Comment by HUMORCE** [comment]
This issue no longer exists in current version(1.9.6).
