### ISSUE TITLE
[Request] gsmartcontrol (help needed)

### ISSUE THREAD

**Issue by TonyApuzzo** [ScoopInstaller/Extras#7497]
## Package Request
gsmartcontrol

### Information

**Name:** [name of new package]
gsmartcontrol

**Description:** [clear and concise details of what it is]
Hard disk drive and SSD health inspection tool. GUI interface for smartmontools

**Homepage:** [a URL/link]
https://gsmartcontrol.sourceforge.io/home/

**Download link(s):** [URL(s)/link(s)]
https://github.com/ashaduri/gsmartcontrol/releases/download/v1.1.3/gsmartcontrol-1.1.3-win64.exe
https://github.com/ashaduri/gsmartcontrol/releases/download/v1.1.3/gsmartcontrol-1.1.3-win32.exe

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

I have a fork / branch almost ready for PR https://github.com/TonyApuzzo/Extras/tree/add-gsmartcontrol 
but I have a problem with the install in that gsmartcontrol won't run from the shim.

It does work if I run it from the start menu icon.

I don't see a way to customize the shim launcher, if someone can point me to documentation or an example that tweaks the launcher I will try to get it working from the command line.

**Comment by TonyApuzzo** [comment]
Being unable to run gsmartcontrol from the command line is being tracked as a bug in the source project as it seems to have nothing to do with scoop in particular (same thing happens when manually installed).

https://github.com/ashaduri/gsmartcontrol/issues/20

So running gsmartcontrol from the start menu with my existing config does work, but I guess I shouldn't try to go forward with this until/unless the base issue is figured out.

**Comment by rashil2000** [comment]
We can remove the bin entry for now, and keep only the shortcut.

We can add bin later when the issue is resolved.

**Comment by TonyApuzzo** [comment]
good idea, I'll pull the bin out of the config and then submit a PR
