### ISSUE TITLE
[Request] Free Manga Downloader 2 (help needed)

### ISSUE THREAD

**Issue by LazyGeniusMan** [ScoopInstaller/Extras#7504]
### Information

**Name:** Free Manga Downloader 2

**Description:** an active fork of the Free Manga Downloader which is a free open source application written in Object Pascal for managing and downloading manga from various websites.

**Homepage:** [https://github.com/dazedcat19/FMD2](https://github.com/dazedcat19/FMD2)

**Download link(s):** [https://github.com/dazedcat19/FMD2/releases/latest](https://github.com/dazedcat19/FMD2/releases/latest)

**Some indication of popularity/repute:** 
[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=dazedcat19&repo=FMD2&show_owner=true)](https://github.com/dazedcat19/FMD2)

**Additional Information** : Can't directly update from FMD1, need to convert FMD1 user data to FMD2 user data using a converter that they provided.

**Help Needed**
I have an App Manifest almost ready for PR in [https://github.com/LazyGeniusMan/Extras/tree/free-manga-downloader-2](https://github.com/LazyGeniusMan/Extras/tree/free-manga-downloader-2)

I have 2 concern:

1. Auto update setting is on by default. Should I bother change the auto update setting to off by default? the setting is stored in `userdata/settings.json`, the file will not appear if the app is freshly installed (need to open the app first). 
2. User can change where to save the downloaded file. By default it's `./downloads` folder and I have added that folder to persist properties in App Manifest. Is it possible to add dynamic persist folder based on user setting? that setting also stored in `userdata/settings.json`

**Comment by rashil2000** [comment]
> 1. Auto update setting is on by default. Should I bother change the auto update setting to off by default? the setting is stored in `userdata/settings.json`, the file will not appear if the app is freshly installed (need to open the app first).

Check if this file exists in $persist_dir, if it doesn't, create it as part of pre_install and fill it with the settings.

> 2. User can change where to save the downloaded file. By default it's `./downloads` folder and I have added that folder to persist properties in App Manifest. Is it possible to add dynamic persist folder based on user setting? that setting also stored in `userdata/settings.json`

The ./downloads folder is fine.

**Comment by LazyGeniusMan** [comment]
> Check if this file exists in $persist_dir, if it doesn't, create it in $dir as part of pre_install and fill it with the settings.

Uhh, something weird happen. The JSON file is generated as intended, but I can't open the app. I'm pretty sure the JSON file content is correct because if I copy the JSON file content, delete the generated file, create a new JSON file manually, paste the generated JSON file content and then save it, I can open the app and the auto update setting is successfully turned off.

Do you have any idea what might caused this?

this is my pre_install script:
```
"pre_install": [
        "# Turn off Auto Update",
        "if (!(Test-Path \"$persist_dir\\userdata\\settings.json\")) {",
        "    if (!(Test-Path \"$dir\\userdata\")) {",
        "       (New-Item -Type directory \"$dir\\userdata\") | Out-Null",
        "    }",
        "    $json = @{}",
        "    $data = @{\"AutoCheckLatestVersion\" = $false}",
        "    $json.Add(\"update\",$data)",
        "    $json | ConvertTo-Json | Out-File \"$dir\\userdata\\settings.json\"",
        "}"
    ],
```

**Comment by rashil2000** [comment]
Do `Out-File \"$dir\\userdata\\settings.json\" -Encoding ascii`
