### ISSUE TITLE
v2rayn: Add Support for path with space

### ISSUE THREAD

**Issue by SonaliBendre** [ScoopInstaller/Extras#7521]
## Bug Report

**Package Name:** [name of package which has bug(s)]
V2rayn
### Current Behaviour

Pre-Install script doesn't have "" I guess that's why script is throwing error for custom path if any folder name has space
### Expected Behaviour

Path should be enclosed within "" in script
### Additional context/output
Installing 'v2ray' (4.44.0) [64bit]
Loading v2ray-windows-64.zip from cache
Checking hash of v2ray-windows-64.zip ... ok.
Extracting v2ray-windows-64.zip ... done.
Running installer script...
Verifying V2Ray binary...
C:\Program : The term 'C:\Program' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Program Files\scoop\apps\v2ray\4.44.0\v2ctl.exe verify --sig=C:\Pr ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

V2Ray binary is corrupted!

### Possible Solution
Path should be enclosed within "" in script

### System details
Windows 11
**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22000  282

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
Please make a PR for your proposal!

**Comment by issaclin32** [comment]
This is actually a problem of **v2ray**.
`v2ctl.exe` cannot recognize signature file with "path with space".
Will be fixed in ScoopInstaller/Main#3079
