### ISSUE TITLE
Firefox update registers a new app

### ISSUE THREAD

**Issue by rubendibattista** [ScoopInstaller/Extras#7528]
## Bug Report

**Package Name:** firefox

### Current Behaviour

Every update creates a new default app
![image](https://user-images.githubusercontent.com/8077364/145839205-901aa19f-fa8f-466f-944f-609ddb55ac3c.png)

### Expected Behaviour

Just one default app stays even after update

### Additional context/output

Probably related: #4377 

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  1593
```

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration
```
{
    "lastupdate":  "258|2021-12-13 09:32:46",
    "SCOOP_REPO":  "https://github.com/Ash258/Scoop-Core",
    "SCOOP_BRANCH":  "main"
}
```

```json
//# Your configuration here
```

**Comment by issaclin32** [comment]
This sould be sent to https://github.com/Ash258/Scoop-Core, because you are using Ash's branch.

We cannot fix the porblem that is caused by someone else's code.

**Comment by rubendibattista** [comment]
Ok, sorry for the wrong report.

**Comment by Ash258** [comment]
Duplicate of ScoopInstaller/Scoop#2651

**Comment by rubendibattista** [comment]
I don't think it's a duplicate? For what I see, I'm getting the opposite problem: Firefox is registered multiple times?
