### ISSUE TITLE
[Request] SuperSlicer

### ISSUE THREAD

**Issue by GreenCappuccino** [ScoopInstaller/Extras#7541]
## Package Request

The `prusaslicer` and `slic3r` slicers are already in this bucket. It would make sense to also include their emerging competitor and fork (which is already well-appreciated in the 3D printing community), SuperSlicer. This app manifest will be unofficial. I'm planning on writing this app manifest, basing it off of the `prusaslicer` manifest.

### Information

**Name:** `superslicer`

**Description:** G-code generator for 3D printers (Prusa, Voron, Creality, etc.) SuperSlicer is based on PrusaSlicer by Prusa Research. PrusaSlicer is based on Slic3r by Alessandro Ranellucci and the RepRap community.

**Homepage:** https://github.com/supermerill/SuperSlicer

**Download link(s):** https://github.com/supermerill/SuperSlicer/releases

**Some indication of popularity/repute:** 1.7k stars on Github, coverage on [Hackaday](https://hackaday.com/2021/10/26/superslicer-reviewed-another-3dp-slicer/), [All3DP](https://all3dp.com/2/superslicer-3d-slicer-open-source-simply-explained/)

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/pull/7438
