### ISSUE TITLE
Some files cause occasionally Git conflicts on updating Scoop

### ISSUE THREAD

**Issue by maksymgendin** [ScoopInstaller/Extras#7546]
## Bug Report

**Package Name:** issue does not apply to specific packages, the repository itself is affected

### Current Behaviour

Occasionally Git conflicts happen on `.reg` files and manifest `.json` files. `scoop update` throws an error due to that.
I can't understand when exactly this happens. It can be that it happens when new `.reg` files are added to the Git index.
Last time it happened to me with these two `.reg` files which were added two days ago: https://github.com/ScoopInstaller/Extras/tree/master/scripts/everything

### Expected Behaviour

No Git conflicts should happen.

### Additional context/output

Executing a `git reset --hard` didn't help to fix this issue. I had to do this:
```bash
git rm .gitattributes
git add -A
git reset --hard
```
Source: https://stackoverflow.com/a/19588910/7593710

### Possible Solution

Specify how to deal with `.reg` and other text files in `.gitattributes`.

I'm not 100% sure but this could be a solution:
```
# Set default behavior to automatically normalize line endings.
# If Git decides that the content is text, its line endings will be normalized to CRLF in the working tree on checkout.
# In the Git index/repository the files will always be stored with LF.
* text=auto eol=crlf
```

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:**
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  1801
```

**Additional software:** not relevant

#### Scoop Configuration

```json
{
    "lastupdate":  "2021-12-16T08:50:52.5175566+01:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master",
    "aria2-enabled":  true,
    "aria2-warning-enabled":  false
}
```

**Comment by rashil2000** [comment]
Hmm, never faced this problem before. @tukanos could this be related to encoding?

**Comment by tukanos** [comment]
@rashil2000  good question.  The question is, if the filename is correctly encoded.  Only the UTF-16 does not suffice.  You need to know if the file contains BOM, if it LE/BE (little/big endian).

**Comment by rasa** [comment]
I suggest using UTF8 and avoid the BOM nonsense. Every .reg file I have ever created or exported was UTF8 and I've never had an issue.

**Comment by maksymgendin** [comment]
Default encoding of `.reg` files is **UCS-2 LE BOM (UTF-16) with \r\n endings**

**UTF-8** and **UTF-8 BOM** seem to work as well.

More info here: https://gist.github.com/SalviaSage/8eba542dc27eea3379a1f7dad3f729a0

**Comment by rasa** [comment]
> Default encoding of `.reg` files is **UCS-2 LE BOM (UTF-16) with \r\n endings**.

I understand it's the default, but I have never heard that it's *required*. UTF-8 w/o BOM has worked 100% of the time for me.

**Comment by maksymgendin** [comment]
@rasa True. So you would suggest this as the solution, right?
```
*.reg text eol=crlf working-tree-encoding=UTF-8
```

**Comment by rashil2000** [comment]
> I suggest using UTF8 and avoid the BOM nonsense. Every .reg file I have ever created or exported was UTF8 and I've never had an issue.

I understand Windows 10 has redesigned support for newer formats and line endings, but is this also the case for 7 and 8?

**Comment by tukanos** [comment]
> > Default encoding of `.reg` files is **UCS-2 LE BOM (UTF-16) with \r\n endings**.
> 
> I understand it's the default, but I have never heard that it's _required_. UTF-8 w/o BOM has worked 100% of the time for me.

That gist is mentioned in my PR. Simply export reg file from `regedit` or do a `reg export` and you will see that it is always  UTF16LE BOM.

The UTF16LE BOM is recommended and preferred - read the gist why.  You may experience issues with uploading registry files in different encoding.  If something works for you 100% of time it does not mean that it will work for everyone and everywhere 100% of time.  It is always wise to use the recommended solution.

**Comment by maksymgendin** [comment]
I would also vote for this:
```
*.reg text working-tree-encoding=UTF-16LE-BOM eol=CRLF
```
Single issue with this solution would be older Git client versions, since `working-tree-encoding` was added approx. in March 2018.

**Comment by rashil2000** [comment]
Scoop only works on Win7+ 🙃

But can't vouch for point no. 1.

**Comment by rasa** [comment]
Instead of migrating to UTF16 why not replace the `Windows Registry Editor Version 5.00` prefix with `REGEDIT4`? 

All the .reg files in main and extras are currently UTF8, so this means no format converting. I think BOMs and UTF16 will cause more problems that it will solve, imo.

**Comment by lepicsaintloup** [comment]
On #7574 @rashil2000 suggested:
```
PS C:\Users\xxxx> scoop bucket rm extras
PS C:\Users\xxxx> scoop bucket add extras
Checking repo... ok
The extras bucket was added successfully.
```
This seemed to work OK with no errors but I didn't see the list of updated apps under the 'extras' bucket list.

**Comment by rashil2000** [comment]
You will see the list next time you run `scoop update`.

**Comment by issaclin32** [comment]
related discussion: https://github.com/ScoopInstaller/Scoop/pull/4586

**Comment by dsbert** [comment]
https://github.com/ScoopInstaller/Scoop/pull/4654

**Comment by rasa** [comment]
If you try to edit a UTF16-LE file on GitHub, you will see the message
```
We’ve detected the file encoding as UTF-16LE. When you commit changes we will transcode it to UTF-8.
```
I would prefer we stick with formats that the tools we use support.

**Comment by scratch-er** [comment]
I encounter this problem every time and it prevents me from updating!
Even git restore is executed, it still cause conflict and actully the files is not modified at all.
```
Updating 6ec259ca1..de3c07def
error: Your local changes to the following files would be overwritten by merge:
        scripts/everything/install-context.reg
        scripts/everything/uninstall-context.reg
Please commit your changes or stash them before you merge.
Aborting
```

**Comment by rasa** [comment]
@scratch-er Please post the output of the following commands:
```batch
git config -l --show-origin | findstr /r /c:"core\.[aes][uoa]"

git ls-files --eol "%userprofile%\scoop\buckets\extras\scripts\everything"
```

**Comment by scratch-er** [comment]
> 

git config -l --show-origin | findstr /r /c:"core\.[aes][uoa]" outputs nothing.
And here is the `core` section of `~/scoop/buckets/extras/.git/config`
```
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
```
git ls-files --eol "%userprofile%\scoop\buckets\extras\scripts\everything" outputs nothing.

#7661 suggests the following workaround:
```
git rm .gitattributes
git add -A
git reset --hard
```
It works on my machine. I have noted that in `.gitattributes`, something about the line-ending is configured. Is it line-endings 

that caused this problem?

**Comment by rasa** [comment]
@scratch-er I'm sorry you're having troubles. I had the same [experience](https://github.com/ScoopInstaller/Extras/commit/fd46c5fa79cf697681355101bd9746e3670f4071#commitcomment-62391917). In trying to see what's going on, I ran: 

```batch
$ file -i *
install-context.reg:        text/x-ms-regedit; charset=utf-8
uninstall-context.reg:      text/x-ms-regedit; charset=us-ascii
```
and did the same on the original files:

```batch
$ git cat-file blob 5db260c1b9607d9643bcc98b76a8196a6beccffc:./uninstall-context.reg > uninstall-context.reg.orig
$ git cat-file blob 5db260c1b9607d9643bcc98b76a8196a6beccffc:./install-context.reg > install-context.reg.orig

$ file -i *.orig
install-context.reg.orig:   text/x-ms-regedit; charset=utf-8
uninstall-context.reg.orig: text/x-ms-regedit; charset=us-ascii
```
The only difference between the original files, and the current files, is they have a final newline:
```batch
$ diff install-context.reg*
23c23
< @="$app_path -path \"%1\""
---
> @="$app_path -path \"%1\""
\ No newline at end of file

$ diff uninstall-context.reg*
8c8
< [-HKEY_CURRENT_USER\Software\Classes\Drive\shell\Everything\command]
---
> [-HKEY_CURRENT_USER\Software\Classes\Drive\shell\Everything\command]
\ No newline at end of file
```
The only thing I found is that everything/install-context.reg has a UTF-8 dash [here](https://github.com/ScoopInstaller/Extras/blob/211b32a09c974b58da14eae7ce11029f6558368e/scripts/everything/install-context.reg#L14). But if that's the problem, why does git fail on uninstall-context.reg which is pure ASCII? And why doesn't it also fail on [grepwin/install-context.reg](https://github.com/ScoopInstaller/Extras/blob/211b32a09c974b58da14eae7ce11029f6558368e/scripts/grepwin/install-context.reg#L22) which has the same UTF-8 dash? 

I'm stumped.

**Comment by ajkajk** [comment]
I can't add anything to the diagnosis, but for me deleting the json file that git was complaining about allowed the update command to complete without error.  

As a workround for a user this is easier than using git or scoop commands.

**Comment by rashil2000** [comment]
This problem is not just limited to .reg files. Many people have reported that they can't update buckets because of conflicting JSON files. I'm not sure what's the cause though. It affects all buckets. Maybe the .gitattributes file?

**Comment by issaclin32** [comment]
> I'm not sure what's the cause though. It affects all buckets. Maybe the .gitattributes file?

I think the problem is mostly caused by uploading files via Github's web interface. Github will keep `CRLF` rather than replace them by `LF`. This also explains why most of the problems are found in **.reg** files.

**Comment by rashil2000** [comment]
> Github will keep `CRLF` rather than replacing them with `LF`. 

Because we're asking it to, no?

https://github.com/ScoopInstaller/Extras/blob/60f3969aaddc7717f15ec69f620acbb3bff359b8/.gitattributes#L1-L2

**Comment by rashil2000** [comment]
The workaround for now is to remove and add the bucket again

**Comment by maksymgendin** [comment]
Another workaround is to execute this in the bucket directory:
```
git rm .gitattributes
git add -A
git reset --hard
```
But we need a solution here, not workarounds 😄

This error happened to me again recently but this time in app manifests, not in Windows Registry files 🤔
For example when this manifest was added: https://github.com/ScoopInstaller/Extras/blob/master/bucket/elisa.json

**Comment by issaclin32** [comment]
@rashil2000 @r15ch13 Is there any other concerns about using `* text eol=crlf` in **.gitattributes**?
(for example, to avoid some errors in certain files?)

If not so, we can easily change it to `* text eol=lf` and solve the problem.

**Comment by rashil2000** [comment]
I was actually thinking of removing the file altogether. Modern Windows deals alright with LFs, but I'm not sure how the change will affect Win 7/8 users.

**Comment by maksymgendin** [comment]
Not sure if fully removing the `.gitattributes` file will solve this 🤔

This would happen in this case:

> If the text attribute is unspecified, Git uses the `core.autocrlf` configuration variable to determine if the file should be converted.

Couldn't it still break depending on the personal `core.autocrlf` configuration?

I think it would be better to keep the file and to concretize how to handle specific files, e.g. like proposed in my initial comment in **Possible Solution** block.

**Comment by rashil2000** [comment]
We can test it. Can you make a PR?

**Comment by maksymgendin** [comment]
@rashil2000 Here you go #8285

**Comment by maksymgendin** [comment]
One more interesting thing I found out.
Most files use the `ASCII` charset. But there are some with `ISO-8859-1`, `UTF-8` , `WINDOWS-1252` but also exotic ones like `WINDOWS-1258` or `ISO-8859-9`. Is there a need to unify this? Maybe this is something which causes trouble?

```
$ find -type f -not -path "./.git/*" -printf "%f: " -exec uchardet "{}" \; | grep -v ASCII

audioswitcher.json: ISO-8859-1
bes.json: UTF-8
diffpdf.json: WINDOWS-1252
flutter.json: WINDOWS-1252
linqpad.json: WINDOWS-1252
love.json: UTF-8
ontopreplica.json: UTF-8
teamspeak3.json: UTF-8
thunderbird.json: WINDOWS-1258
tortoisesvn.json: UTF-8
totalcommander.json: UTF-8
trojita.json: ISO-8859-9
wireshark.json: UTF-8
install-context.reg: UTF-8
flutter-dev-setup.ps1: UTF-8
```

**Comment by rashil2000** [comment]
We can test the current changes for a while, and if they don't work as intended, we now know where to look next :)

**Comment by maksymgendin** [comment]
@rashil2000 @rasa @tukanos @issaclin32 @scratch-er 
So, some time has passed. The error hasn't happened to me personally anymore. How about you?
Would you like to propagate this fix to other repos like [ScoopInstaller/Main](https://github.com/ScoopInstaller/Main), [ScoopInstaller/Versions](https://github.com/ScoopInstaller/Versions) and [ScoopInstaller/Java](https://github.com/ScoopInstaller/Java)?

**Comment by issaclin32** [comment]
> Would you like to propagate this fix to other repos?

Absolutely.
I have propagated the fix to all official buckets. Thanks for the follow up.

**Comment by maksymgendin** [comment]
Thanks, @issaclin32. Hope it will work flawlessly 😁

**Comment by rashil2000** [comment]
I have also made the change in Tests and BucketTemplate repos
