### ISSUE TITLE
Cryptomator not properly updating Cryptomator.cfg in persist/app/

### ISSUE THREAD

**Issue by mil1i** [ScoopInstaller/Extras#7551]
## Bug Report

**Package Name:** Cryptomator

### Current Behaviour

Upon updating from version 1.6.3 of cryptomator via scoop update cryptomator, and also uninstalling and reinstalling, the version of the application that continues to open is 1.6.3 even though it states it has updated to version 1.6.5.

I performed "scoop cleanup *", verified that only version 1.6.5 was present in the scoop/apps directory and also ran the .exe file directly from the 1.6.5 version directory. The application version is still 1.6.3.

I then went to the scoop bucket cryptomator.json file, and downloaded the msi installer listed there directly and installed it. Upon opening this version application, it was correctly running the version 1.6.5.
https://github.com/ScoopInstaller/Extras/blob/master/bucket/cryptomator.json

Upon further inspection, it seems that scoop is supposed to be updating `scoop/persist/cryptomator/app/Cryptomator.cfg` with the new version:
```less
[JavaOptions]
java-options=-Djpackage.app-version=1.6.3.3362
java-options=-Dcryptomator.appVersion=1.6.3
java-options=-Dcryptomator.buildNumber=msi-3362
```

I manually changed this to the below, and running the application states it is running version 1.6.5.
```less
[JavaOptions]
java-options=-Djpackage.app-version=1.6.5.3397
java-options=-Dcryptomator.appVersion=1.6.5
java-options=-Dcryptomator.buildNumber=msi-3397
```

I compared the md5sum's of the 1.6.3 and 1.6.5 installer to the one installed via scoop. Scoop's version does seem to match with version 1.6.5. So it just appears that scoop updating is not properly updating the Cryptomator.cfg versioning.

```
scoop cryptomator.exe md5sum:
➜ md5sum Cryptomator.exe
e184230cf1d886a88db459ac912b2f5d  Cryptomator.exe
```
```
cryptomator.exe v1.6.3 md5sum:
➜ md5sum /mnt/c/Program\ Files/Cryptomator/Cryptomator.exe
f97bc80f67fd99f06b2fe47a27df03ee  /mnt/c/Program Files/Cryptomator/Cryptomator.exe
```
```
cryptomator.exe v1.6.5 md5sum:
➜ md5sum /mnt/c/Program\ Files/Cryptomator/Cryptomator.exe
e184230cf1d886a88db459ac912b2f5d  /mnt/c/Program Files/Cryptomator/Cryptomator.exe
````
### Expected Behaviour

The application should be running the appropriately installed version; 1.6.5.

### Possible Solution

I am unsure how the persist data is being populated, but the below `post_install` section appears to be working correctly. It's just not updating the `persist/app/Cryptomator.cfg` afterwards.

Perhaps `app/Cryptomator.cfg` needs to be removed from the persist section?

```json
"post_install": [
        "    # Change appdata settings folder",
        "(Get-Content \"$dir\\app\\Cryptomator.cfg\" -Encoding ASCII).replace('~/AppData/Roaming/Cryptomator', './data') | Set-Content \"$dir\\app\\Cryptomator.cfg\" -Encoding ASCII"
],
"persist": [
        "data",
        "app/Cryptomator.cfg"
],
```

### System details

**Windows version:** 10 21H2 19044.1415

**OS architecture:** x64

**PowerShell version:**
```powershell
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1320
```
```pwsh
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      1
```

#### Scoop Configuration

```json
{
  "lastupdate": "2021-12-17T09:45:24.8238577-07:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
> Perhaps `app/Cryptomator.cfg` needs to be removed from the persist section?

Probably. What else does this file store?

**Comment by mil1i** [comment]
cat .\Cryptomator.cfg
```
[Application]
app.mainmodule=org.cryptomator.desktop/org.cryptomator.launcher.Cryptomator
app.classpath=$APPDIR\asm-9.2.jar
app.classpath=$APPDIR\asm-analysis-9.2.jar
app.classpath=$APPDIR\asm-commons-9.2.jar
app.classpath=$APPDIR\asm-tree-9.2.jar
app.classpath=$APPDIR\asm-util-9.2.jar
app.classpath=$APPDIR\httpcore-4.4.14.jar
app.classpath=$APPDIR\jackrabbit-webdav-2.21.5.jar
app.classpath=$APPDIR\jffi-1.3.5-native.jar
app.classpath=$APPDIR\jffi-1.3.5.jar
app.classpath=$APPDIR\jna-5.9.0.jar
app.classpath=$APPDIR\jna-platform-5.9.0.jar
app.classpath=$APPDIR\jnr-a64asm-1.0.0.jar
app.classpath=$APPDIR\jnr-constants-0.10.2.jar
app.classpath=$APPDIR\jnr-ffi-2.2.7.jar
app.classpath=$APPDIR\jnr-fuse-0.5.7.jar
app.classpath=$APPDIR\jnr-posix-3.1.10.jar
app.classpath=$APPDIR\jnr-x86asm-1.0.2.jar

[JavaOptions]
java-options=-Djpackage.app-version=1.6.5.3397
java-options=-Xss5m
java-options=-Xmx256m
java-options=-Dcryptomator.appVersion=1.6.5
java-options=-Dfile.encoding=utf-8
java-options=-Dcryptomator.logDir=./data
java-options=-Dcryptomator.pluginDir=./data/Plugins
java-options=-Dcryptomator.settingsPath=./data/settings.json
java-options=-Dcryptomator.ipcSocketPath=./data/ipc.socket
java-options=-Dcryptomator.keychainPath=./data/keychain.json
java-options=-Dcryptomator.mountPointsDir=~/Cryptomator
java-options=-Dcryptomator.showTrayIcon=true
java-options=-Dcryptomator.buildNumber=msi-3397
java-options=--module-path
java-options=$APPDIR\mods
```

This file looks like it should be updated with each version change.

**Comment by rashil2000** [comment]
Okay, please make a PR to remove it from persist
