### ISSUE TITLE
[Request] Add UltraVNC

### ISSUE THREAD

**Issue by grisha765** [ScoopInstaller/Extras#7560]
### Information

**Name: UltraVNC** [name of new package]

**Description: UltraVNC is a powerful, easy to use and free - remote pc access softwares - that can display the screen of another computer (via internet or network) on your own screen.** [clear and concise details of what it is]

**Homepage: https://uvnc.com/** [a URL/link]

**Download link(s): https://uvnc.com/downloads/ultravnc.html** [URL(s)/link(s)]

**Some indication of popularity/repute: Github 197 stars** [GitHub stars/software reviews etc.]

**Comment by littleli** [comment]
@rashil2000 I'd like to work on this one.

**Comment by rashil2000** [comment]
Go ahead!
