### ISSUE TITLE
[Request] MSEdgeRedirect

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7572]
Package Request
Information
Name: MSEdgeRedirect

Description: A Tool to Redirect News, Search, Widgets, Weather and More to Your Default Browser

Homepage: https://github.com/rcmaehl/MSEdgeRedirect

Download link(s): https://github.com/rcmaehl/MSEdgeRedirect/releases/latest/download/MSEdgeRedirect.exe

Some indication of popularity/repute: Github  539 stars

**Comment by rcmaehl** [comment]
Hiya! I may be able to make a PR for this since I'm working on packages for other platforms as well :)

**Comment by rashil2000** [comment]
Sure, whenever you're ready
