### ISSUE TITLE
[Request] Sozi (help needed)

### ISSUE THREAD

**Issue by LazyGeniusMan** [ScoopInstaller/Extras#7603]
### Information

**Name:** Sozi

**Description:** Zooming presentation editor and player.

**Homepage:** https://sozi.baierouge.fr/

**Download link(s):** https://github.com/sozi-projects/Sozi/releases/download/v21.12.06/sozi-21.12.06-1638805322-windows-x64.zip

**Some indication of popularity/repute:**
[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=sozi-projects&repo=Sozi&show_owner=true)](https://github.com/sozi-projects/Sozi)

### Need Help
I have some question:
- This app have some kind of addon that enable audio & video embedding, but this addon is installed in `<inkscape_dir>\share\extensions`, how do I implement the addon in scoop? because AFAIK scoop not yet support post uninstall script, so If I use post 
install script to copy them to inkscape folder, it won't be removed if this app uninstalled right?
- Is it possible if I create separate app manifest for this addon and then create some kind of symlink from addon app dir to inkscape dir? If yes what;s the name for the addon manifest ? `sozi-extras` ? `inkscape-sozi-extras`? or what?
reference: https://sozi.baierouge.fr/pages/tutorial-media.html

**Comment by rashil2000** [comment]
> * This app have some kind of addon that enable audio & video embedding, but this addon is installed in `<inkscape_dir>\share\extensions`, how do I implement the addon in scoop? because AFAIK scoop not yet support post uninstall script, so If I use post_install script to copy them to inkscape folder, it won't be removed if this app uninstalled right?

You can use a script in the `uninstaller` field for that

> * Is it possible if I create separate app manifest for this addon and then create some kind of symlink from addon app dir to inkscape dir? If yes what;s the name for the addon manifest ? `sozi-extras` ? `inkscape-sozi-extras`? or what?
>   reference: https://sozi.baierouge.fr/pages/tutorial-media.html

That depends on who the plugin is intended for. If it's for Inkscape users, call it inkscape-sozi-plugin, if it's for sozi users, call it sozi-inkscape-plugin

**Comment by LazyGeniusMan** [comment]
> That depends on who the plugin is intended for

It's for inkscape so that it can embed audio/video to SVG files and then sozi use it to create presentation. So I guess technically it's inkscape addon ?

Should I make a different app manifest or make a script on `sozi.json`? I also notice that inkscape dont have persist folder, so when inkscape is updated, the sozi addon will be gone ?

**Comment by rashil2000** [comment]
> It's for inkscape so that it can embed audio/video to SVG files and then sozi use it to create presentation. So I guess technically it's inkscape addon ?

Yes

> Should I make a different app manifest or make a script on `sozi.json`? 

Different manifest

> I also notice that inkscape dont have persist folder, so when inkscape is updated, the sozi addon will be gone ?

Yes. You will need to install the addon again.

**Comment by LazyGeniusMan** [comment]
> Yes. You will need to install the addon again.

Do you have any idea how to handle this? afaik an app manifest can only create persist folder in their app dir right?, Am I allow to add post install script on inkscape manifest to copy again the addon file if the addon is installed?[^1]

[^1]: https://scoop-docs.vercel.app/docs/concepts/Pre--and-Post-install-scripts.html#appdir

**Comment by rashil2000** [comment]
A better solution is to add relevant items to `persist` in the inkscape manifest, otherwise we'll end up hardcoding for every possible addon.

**Comment by LazyGeniusMan** [comment]
Oops, apparently the guide from sozi is either outdated or installler and portable version have different location(?), the extensions actually stored in `%appdata%\Roaming\inkscape\extensions`, So I guess add `post_install` to copy from $dir to extension folder and uninstall script for delete the file on extension folder would be the appropriate method?

**Comment by rashil2000** [comment]
Yes, seems good
