### ISSUE TITLE
[Request] Buckets budgeting app

### ISSUE THREAD

**Issue by maphew** [ScoopInstaller/Extras#7605]
## Package Request

**Buckets** - _Make your budget quick, simple and private._

### Information

**Name:** Buckets\*

**Description:** Cross platform personal budgeting program for Linux, Mac and Windows. _"Buckets gives you an untimed, free trial for as long as you need to decide if it works for you. Really. Buckets is private. Your finances stay on your computer. You control your data again! Buckets has no monthly fee. It costs $49. Once. You're saving money, not shackling yourself to another monthly service. A single license may be used on all your computers and all the computers of family members living in your home."_

**Homepage:** https://www.budgetwithbuckets.com/, https://github.com/buckets/application/

**Download link(s):** https://github.com/buckets/application/releases

**Some indication of popularity/repute:** Not a widely known program yet, currently in range of 100 github stars and a dozen watchers. I personally think it's a sleeper and underrated, so far.

----
\* In it's own nomenclature it's simply _Buckets_, however given how prominent 'bucket' as a word is within Scoop it should probably be called _buckets-app_, _buckets-budgeting_, or similar.

I've started creating an app manifest for it but have run into a couple of problems I don't know how to solve. In future comment I'll show my efforts to date.

**Comment by maphew** [comment]
My work is in my fork in [buckets-budgeting](https://github.com/maphew/scoop-extras/tree/buckets-budgeting) branch.

## Current status

`scoop install bucket\buckets.json` fails:

```
Installing 'buckets' (0.60.1) [64bit]
Loading Buckets-Setup-0.60.1.exe from cache.
WARN  Warning: No hash in manifest. SHA256 for 'buckets#0.60.1#https_github.com_buckets_application_releases_download_v0.60.1_Buckets-Setup-0.60.1.exe' is:
    3384604b06d0ad8050d5e61f398dba69cc7c65c595a8509d1d66463f473fc2fc
Running installer... error.
ERROR Exception calling "Start" with "0" argument(s): "The requested operation requires elevation"
Installation aborted. You might need to run 'scoop uninstall buckets' before trying again.
```

Using elevated permissions works:
```
» sudo scoop install bucket\buckets.json
WARN  Purging previous failed installation of buckets.
Uninstalling 'buckets' ().
'buckets' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'buckets' (0.60.1) [64bit]
Loading Buckets-Setup-0.60.1.exe from cache.
WARN  Warning: No hash in manifest. SHA256 for 'buckets#0.60.1#https_github.com_buckets_application_releases_download_v0.60.1_Buckets-Setup-0.60.1.exe' is:
    3384604b06d0ad8050d5e61f398dba69cc7c65c595a8509d1d66463f473fc2fc
Running installer... done.
Linking ~\scoop\apps\buckets\current => ~\scoop\apps\buckets\0.60.1
Creating shim for 'Buckets'.
Creating shortcut for Buckets (Buckets.exe)
Persisting appdata
'buckets' (0.60.1) was installed successfully!
```

However after that things are messed up:
```
» scoop uninstall buckets
Uninstalling 'buckets' (0.60.1).
Removing shim 'Buckets.exe'.
Removing shim 'Buckets.shim'.
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Buckets.lnk
Unlinking ~\scoop\apps\buckets\current
'buckets' was uninstalled.

» sudo scoop install bucket\buckets.json
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'buckets' (0.60.1) [64bit]
Loading Buckets-Setup-0.60.1.exe from cache.
WARN  Warning: No hash in manifest. SHA256 for 'buckets#0.60.1#https_github.com_buckets_application_releases_download_v0.60.1_Buckets-Setup-0.60.1.exe' is:
    3384604b06d0ad8050d5e61f398dba69cc7c65c595a8509d1d66463f473fc2fc
Running installer... error.
ERROR Exit code was 5!
Installation aborted. You might need to run 'scoop uninstall buckets' before trying again.
```

Further uninstallations have no effect.

**Comment by maphew** [comment]
Regarding the first error, I don't know why elevation is necessary since when I run the setup program manually there is no elevation prompt when double-clicking.

**Comment by rashil2000** [comment]
Try extracting the installer instead of running it - like this https://github.com/ScoopInstaller/Extras/blob/master/bucket/autohotkey.json

**Comment by maphew** [comment]
No that didn't do it, console log below for commit 8aef4c19110bb2fdcc6ef1d449a6362ef3471dcc. However there's something else going on too now. I tried manual install again last night. It started okay and got about 50% complete and just hung there. I let it sit for over an hour and no change.

```
» scoop install bucket\buckets-budgeting.json
Installing 'buckets-budgeting' (0.60.1) [64bit]
Loading Buckets-Setup-0.60.1.exe from cache.
WARN  Warning: No hash in manifest. SHA256 for 'buckets-budgeting#0.60.1#https_github.com_buckets_application_releases_download_v0.60.1_Buckets-Setup-0.60.1.exe_dl.7z' is:
    3384604b06d0ad8050d5e61f398dba69cc7c65c595a8509d1d66463f473fc2fc
Extracting dl.7z ... done.
Running installer... error.
ERROR Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
Installation aborted. You might need to run 'scoop uninstall buckets-budgeting' before trying again.
```

**Comment by rashil2000** [comment]
Then there might be some problem in the setup file. I'd recommend waiting until it gets fixed.

**Comment by amreus** [comment]
There are 2 versions you could use:

`Buckets-0.63.2.exe` <- the portable version.
`Buckets-Setup-0.63.2.exe`  <- the setup version.

I would try to use the portable version if possible. The setup version does ask for elevated permissions.

There are a couple ways you could install the portable version in scoop.

1. Just shim the `Buckets-0.63.2.exe` file directly. It self-extreacts and runs.

2. Extract `Buckets-0.63.2.exe`. This is a little trickier because you will need to perform a second extraction to get to the executable.

This is the contents of the portable exe (`Buckets-0.63.2.exe`)

`$ 7z x Buckets-0.63.2.exe`

```
$PLUGINSDIR\
        app-32.7z
        app-64.7z
        nsis7z.dll
        StdUtils.dll
        System.dll
```

The actual apps are in the `app-32.7z` and `app-32.7z` files. Once those are extracted (depending on architecture), the `Bucket.exe` runs as-is (no install or elevated permissions needed.)

Extracting the `app-64.7z` gives you:

```
Buckets.exe
chrome_100_percent.pak
chrome_200_percent.pak
d3dcompiler_47.dll
ffmpeg.dll
icudtl.dat
libEGL.dll
libGLESv2.dll
LICENSE.electron.txt
LICENSES.chromium.html
locales
natives_blob.bin
resources
resources.pak
snapshot_blob.bin
swiftshader
v8_context_snapshot.bin
```
