### ISSUE TITLE
[Request] Remove Empty Directories (aka RED)

### ISSUE THREAD

**Issue by Xelbayria** [ScoopInstaller/Extras#7618]
Haven't find a duplicated Request and is conformed by XEL 

### Information

**Name:** RED aka "Remove Empty Directories" 

**Description:** [clear and concise details of what it is]
_Quoting from the summary Below:_ 
RED searches and deletes empty directories recursively below a given start folder and shows the result in a well arranged tree. Further you can create some custom rules for keeping and deleting folders. Empty files in directories can also be ignored.

**Homepage:** [a URL/link]
[RED Home](https://www.jonasjohn.de/red.htm)

**Download link(s):** [URL(s)/link(s)]
[Download From Github](https://github.com/hxseven/Remove-Empty-Directories/releases)

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

[SourceForge Review](https://sourceforge.net/projects/rem-empty-dir/reviews)

**Comment by Xelbayria** [comment]
Just a note: 

There are another program also called: 

![Duplicated RED](https://user-images.githubusercontent.com/12866666/147726021-091775cc-438c-4122-8fcc-d2ce57992556.PNG)

There is a reason why i add the full name "Remove Empty Directories" aka RED which is "Extra" and the other is in main bucket

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/commit/0b6b214a9bd9a1d184a1b5279b8b3ba21ca28f75
