### ISSUE TITLE
OneCommander wrong license url and version parsing possible improvement

### ISSUE THREAD

**Issue by m1l** [ScoopInstaller/Extras#7627]
## Bug Report

**Package Name:** onecommander
https://github.com/ScoopInstaller/Extras/blob/master/bucket/onecommander.json

### Current Behaviour

Wrong site for license
Latest version url could be improved

### Expected Behaviour

https://onecommander.com/license.txt

### Possible Solution

There is no need to parse site content for latest version (site text might change in the future) so it might be better to use
https://onecommander.com/version.txt
if possible, which just contains a version number of the latest stable version

url and autoupdate should then both be something like
https://onecommander.com/OneCommander$version.zip
if that txt file can be used to get the $version
Here are the changes:
-Added Templates in persist
-Changed license url
-Description updated
- but I didn't know the proper way to add the text file for version

```json
{
    "version": "3.4.12.0",
    "description": "Modern dual-pane file manager for Microsoft Windows with columns view, tabs, themes, built-in preview, and more",
    "homepage": "https://onecommander.com/",
    "license": {
        "identifier": "Freeware",
        "url": "https://onecommander.com/license.txt"
    },
    "url": "https://onecommander.com/OneCommander3.4.12.0.zip",
    "hash": "73fd10b5ec22501247353f8988647faa39329bd71aad585fa6ff522a2f97d3c6",
    "shortcuts": [
        [
            "OneCommander.exe",
            "OneCommander"
        ]
    ],
    "persist": [
        "Settings",
        "Logs",
        "Templates"
    ],
    "checkver": {
        "url": "https://onecommander.com/",
        "regex": "Download ([\\d.]+)"
    },
    "autoupdate": {
        "url": "https://onecommander.com/OneCommander$version.zip"
    }
}
```

**Comment by rashil2000** [comment]
Please make a PR for this!

You can directly use the txt file URL in checkver's url field.
