### ISSUE TITLE
[Request] miller

### ISSUE THREAD

**Issue by DOFfactory** [ScoopInstaller/Extras#7672]
### Information

**Name:** miller

**Description:** Miller is like `awk`, `sed`, `cut`, `join`, and `sort` for data formats such as CSV, TSV, tabular JSON and positionally-indexed. With Miller, you get to use named fields without needing to count positional indices, using familiar formats such as CSV, TSV, JSON, and positionally-indexed. Then, on the fly, you can add new fields which are functions of existing fields, drop fields, sort, aggregate statistically, pretty-print, and more.

**Homepage:** [https://github.com/johnkerl/miller](https://github.com/johnkerl/miller)

**Download link(s):** [https://github.com/johnkerl/miller/releases](https://github.com/johnkerl/miller/releases)

**Some indication of popularity/repute:** 4.8k stars, 48 releases, 130 forks

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Main/issues/2245
