### ISSUE TITLE
[Request] Add font Cascadia Code

### ISSUE THREAD

**Issue by grisha765** [ScoopInstaller/Extras#7673]
### Information

**Name: cascadia-code ** [name of new package]

**Description: Cascadia is a fun new coding font that comes bundled with Windows Terminal, and is now the default font in Visual Studio as well.** [clear and concise details of what it is]

**Homepage: https://github.com/microsoft/cascadia-code** [a URL/link]

**Download link(s): https://github.com/microsoft/cascadia-code/releases** [URL(s)/link(s)]

**Some indication of popularity/repute: GitHub 18.8k stars ** [GitHub stars/software reviews etc.]

**Comment by rashil2000** [comment]
https://github.com/matthewjberger/scoop-nerd-fonts

**Comment by JustinGrote** [comment]
@rashil2000 I did want to note that cascadia-code has it's own "nerd font" release now separate from what nerd-fonts compiles, so it may be worthwhile having a separate package.
https://github.com/microsoft/cascadia-code/releases/tag/v2404.23
