### ISSUE TITLE
Foobar2000: Renaming playlists folder failed 

### ISSUE THREAD

**Issue by AkariiinMKII** [ScoopInstaller/Extras#7675]
## Bug Report

**Package Name:** Foobar2000

### Current Behaviour

Rename conflict occurs when `playlists` and `playlists-v1.4` folder exits at the same time

### Expected Behaviour

Delete `playlists` folder without renaming

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1320

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
    "lastupdate":  "2022-01-05T18:31:43.4638200+08:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master",
    "aria2-enabled":  true,
    "aria2-max-connection-per-server":  16,
    "aria2-split":  16,
    "aria2-min-split-size":  "1M"
```

**Comment by rashil2000** [comment]
Please make a PR!
