### ISSUE TITLE
everything@1.4.1.1015: download via aria2 failed

### ISSUE THREAD

**Issue by yueguangjifeng** [ScoopInstaller/Extras#7677]
ERROR & 'aria2c.exe' --input-file='scoop\cache\everything.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=5 --split=5 --max-connection-per-server=8 --min-split-size=10485760 --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=33192 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=everything%401.4.1.1015%3a+download+via+aria2+failed

**Comment by rashil2000** [comment]
Not reproducible 

![image](https://user-images.githubusercontent.com/46838874/148226966-781f5e1d-e8af-456e-8618-3af8f5beaa10.png)
