### ISSUE TITLE
cpu-z@1.99: Download via aria2 failed

### ISSUE THREAD

**Issue by holicoweve** [ScoopInstaller/Extras#7679]
Download failed! (Error 1) An unknown error occurred

---
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://download.cpuid.com/cpu-z/cpu-z_1.99-en.zip
    referer=https://download.cpuid.com/cpu-z/
    dir=D:\scoop\cache
    out=cpu-z#1.99#https_download.cpuid.com_cpu-z_cpu-z_1.99-en.zip

ERROR & 'D:\scoop\apps\aria2\1.36.0-1\aria2c.exe' --input-file='D:\scoop\cache\cpu-z.txt' --user-agent='Shovel/1.0 (+https://shovel.ash258.com) PowerShell/7.2 (Windows NT 10.0.19041.0; Win64; x64;)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=36472 --continue --summary-interval 0
ERROR Download failed! (Error 1) An unknown error occurred

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/148328084-729d0516-ad97-43d4-96f7-aaf574c0b69c.png)
