### ISSUE TITLE
qtranslate download url error

### ISSUE THREAD

**Issue by AIR-HH** [ScoopInstaller/Extras#7712]
## Bug Report

**Package Name:** qtranslate

### Current Behaviour
 download failed

### Expected Behaviour
download successful

### Additional context/output
qtranslate.json download address is https://qtranslate2.appspot.com/QTranslate.6.9.0.zip

### Possible Solution
The current download address is http://qtranslate1.appspot.com/QTranslate.6.9.0.exe

### System details

**Windows version:** [10]

**OS architecture:** [64bit]

**Comment by rashil2000** [comment]
https://qtranslate2.appspot.com/QTranslate.6.9.0.zip is accessible. It works.

The URL http://qtranslate1.appspot.com/QTranslate.6.9.0.exe you gave is not safe:

![image](https://user-images.githubusercontent.com/46838874/148915781-8d69f4b4-4375-4df7-803e-586949b941c4.png)
