### ISSUE TITLE
Portable configuration of firefox doesn't open links correctly

### ISSUE THREAD

**Issue by ebugusey** [ScoopInstaller/Extras#7713]
## Bug Report

**Package Name:** firefox

### Current Behaviour

When I open links from other applications, for example someone sends me a link in a messenger, Firefox opens it in a new window and not in my profile.

### Expected Behaviour

Firefox opens links in current window in a new tab and in my profile.

### Additional context/output

Portable firefox always had this problem.
```json
    "bin": [
        [
            "firefox.exe",
            "firefox",
            "-profile \"$dir\\profile\""
        ]
    ],
    "shortcuts": [
        [
            "firefox.exe",
            "Firefox",
            "-profile \"$dir\\profile\""
        ]
    ],
```
This configuration assumes that I will be running Firefox from shim or shortcut. But Firefox also registers itself as a default web browser to handle links. And it registers it's currently installed instance, something like this `C:\Users\<user>\scoop\apps\firefox\96.0\firefox.exe`. As you can see it doesn't include profile argument. It doesn't now it's running in portable mode, it doesn't has information about this portable profile in `%AppData%\Roaming\Mozilla\Firefox\profiles.ini` so I can't even make this portable profile a default.

Recent PR #7573 made firefox portable by default. 

Yes non-portable version had this problem #4377, but it can be solved another way. You can create named profile, make it a default and add argument `-p <profile name>` to your Firefox shortcut.

### Possible Solution

Rollback changes to separate portable and non-portable versions. Firefox currently doesn't has mechanisms to make it fully portable.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 
```
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      1
```

**Additional software:** none

#### Scoop Configuration

```json
{
  "lastupdate": "2022-01-11T10:13:47.6535320+04:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "alias": {
    "st": "scoop-st",
    "i": "scoop-i",
    "ls": "scoop-ls",
    "rm": "scoop-rm",
    "up": "scoop-up",
    "clean": "scoop-clean",
    "show": "scoop-show"
  },
  "shim": "kiennq"
}
```

**Comment by rashil2000** [comment]
This is currently being handled by @amreus in https://github.com/ScoopInstaller/Scoop/discussions/4633

**Comment by HUMORCE** [comment]
![screenshot_20220116074226](https://user-images.githubusercontent.com/4353480/149651632-a8eaa3f7-bee5-401c-9697-730caed5e5d3.png)

```
> cd (scoop prefix firefox)
> .\firefox.exe -P
// select your profile and check [use the selected profile without asking at startup] option.
// set your profile as default at 'about:profiles'

> cat $env:APPDATA\Mozilla\Firefox\profiles.ini
...
Name=scoop
IsRelative=0
Path=C:\Users\HUMOR\scoop\persist\firefox\profile
...
```

i am always stay on my profile, and dont know why `extras/firefox(-*)` sets launch option `-p '$profile'` for `bin` as default.

see also:
https://github.com/HUMORCE/nuke/blob/master/bucket/firefox.json

**Comment by amreus** [comment]
> and dont know why extras/firefox(-*) sets launch option -p '$profile' for bin as default.

I was a little surprised at this change.  I did not think portability was a core goal of scoop.  I thought the `persist` feature was mostly for apps that stored their config in the `apps` folder so the configs would not get deleted on upgrade.  I do not see an issue with apps persisting data in `%APPDATA%` which is an acceptable and expected location for app config files. 

With the change to using `-profile` in the shim, running `firefox -P` no longer works to bring up the Profiles dialog.  This is a problem for some users as it breaks a firefox feature. I do occasionally use a fresh profile for testing.

**Comment by rashil2000** [comment]
Should we remove persist from the manifests then? If many people are facing problem, I'll remove it.
