### ISSUE TITLE
KDE Connect download file 404 error

### ISSUE THREAD

**Issue by DanielSherlock** [ScoopInstaller/Extras#7723]
## Bug Report

**Package Name:** KDE Connect

### Current Behaviour

404 error when fetching file for installation.

### Expected Behaviour

Use a correct link for the file.

### Additional context/output

Output when installing build 843:

```
    The remote server returned an error: (404) Not Found.
    URL https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect- 
    kde_Release_win64/lastSuccessfulBuild/artifact/kdeconnect-kde-21.12.1-843-windows-msvc2019_64-cl.7z is not valid
```

KDE Connect versions (e.g. `21.12.1-843`) have two parts: the version (`21.12.1`) and what looks like an incrementing build number (`843`). As far as I can tell, looking at the KDE binary site, builds with the same version seem to be based off the same commit. They also seem to make a new build every day, at 20:25 (UTC?). Downloads seem to be available for the past 5 days' builds.

The problem comes that the `.../lastSuccessfulBuild/...` url used in the manifest *only* keeps the most recently generated files. This means that for almost 4 hours, between the KDE CI running, and the Scoop autoupdate running, the url in the manifest is wrong, giving the 404 error. This could be avoided if the otherwise identical url, based on the actual build number (e.g. `.../843/...`). This would also allow people to install an older version if necessary (as long as the current version is less than 5 days old).

### Possible Solution

I've not written `checkver` and `autoupdate` manifest sections before, and am not currently in a position to test things right now. Still, based on the Scoop documentation, I think a working solution might look a little like this:

```
    "checkver": {
        "url": "https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Release_win64/",
        "regex": "kdeconnect-kde-(?<version>[\\d.]+)-(?<build>[\\d]+)-windows-msvc(?<vc>\\d+)_64-cl\\.7z</a>",
        "replace": "${version}-${build}"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Release_win64/$matchBuild/artifact/kdeconnect-kde-$version-windows-msvc$matchVc_64-cl.7z"
            }
        },
        "hash": {
            "url": "$url.sha256",
            "regex": "$sha256"
        }
    }
```

This proposal changes the regex to match the version and build separately, then recombines them in the new replace property. It also uses the matched build number in the url, to actually solve the problem.

Note: If KDE kept their files around for longer than 5 days, I would also suggest dropping the build number from the tracked version string. This would avoid Scoop suggesting people install daily rebuilds of the same thing. If there's a way for Scoop autoupdate to update the url without updating the apparent version that might be possible... otherwise the old url would become unusable after 5 days. Or perhaps KDE do keep them around somewhere, and I just haven't found them! But for now, although the proposed solution doesn't make the autoupdate any less spammy hopefully it will it least stop it 404ing.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1320

**Additional software:** N/A

#### Scoop Configuration

```json
//# N/A
```

**Comment by rashil2000** [comment]
Fixed by https://github.com/ScoopInstaller/Extras/commit/b2d2e3a04d85d096a3f357bf31122b78d02ad5c1

KDE's binary factory removes older releases, and Scoop renews the URL every 4 hours, so this got fixed automatically.

**Comment by DanielSherlock** [comment]
I know: that's exactly my point! (In fact, I stayed up late yesterday exactly because I knew, having diagnosed the problem, that the url would soon be updated and I would be able to install it).

But that doesn't change the fact that, for exactly the reasons you gave (and which I also laid out in my issue), as it stands **KDE Connect is not installable for about 3½ hours every day, between the hours of about 20:25 and 00:00**. If this were 3½ hours every month or every week I'd say it's not much of an issue, but *every day* seems a real problem.

Furthermore, I believe **this problem is entirely unnecessary**: although I'm not experience in writing manifests, it looks to me like a small tweak to the `checkver` and `autoupdate` sections will fix this. I have proposed a tweak I think will work.

**Comment by rashil2000** [comment]
I see.

@issaclin32 contributed the manifest for KDE Connect, so perhaps it would be good to ask him.

**Comment by DanielSherlock** [comment]
Alright, thanks for following up on this so quickly!

**Comment by issaclin32** [comment]
@DanielSherlock I have applied your proposed fix in https://github.com/ScoopInstaller/Extras/commit/99e14f128a18d1ec34e7cd328dbef82fda4d0f42. Thank you so much for reporting and testing it.
