### ISSUE TITLE
[Request] add Vysor 

### ISSUE THREAD

**Issue by grisha765** [ScoopInstaller/Extras#7753]
### Information

**Name: vysor** [name of new package]

**Description: Mirror and Control your Phone** [clear and concise details of what it is]

**Homepage: https://www.vysor.io/** [a URL/link]

**Download link(s): https://github.com/koush/vysor.io/releases/download/v4.1.77/Vysor-win-4.1.77.exe** [URL(s)/link(s)]

**Some indication of popularity/repute: github 1k stars** [GitHub stars/software reviews etc.]

**Comment by rashil2000** [comment]
#7153
