### ISSUE TITLE
Rambox 2.0 filename change breaks update/download link for manifes

### ISSUE THREAD

**Issue by AyoungDukie** [ScoopInstaller/Extras#7779]
## Bug Report

**rambox-pro**

### Current Behaviour

Installs fine with current versions; however updates to, or trying to install 2.0.0 will fail. Upstream change to exe name has broken the manifest for version 2.0+

### Expected Behaviour
`scoop Install rambox-pro` or `scoop update rambox-pro` would install/update respectively

### Additional context/output
Rambox has dropped the "Pro" from the exe name, and now has added "-x64" to the file-name

### Possible Solution
Proposed fix in pull #7780

**Comment by DOFfactory** [comment]
Well, although I am not installing rambox-pro but only the community edition rambox, I am receiving a similar error:

```
C:\Users\user>scoop update *
rambox: 0.7.9 -> 2.0.1
Updating one outdated app:
Updating 'rambox' (0.7.9 -> 2.0.1)
Downloading new version
The request was aborted: The connection was closed unexpectedly.
At C:\Users\user\scoop\apps\scoop\current\lib\install.ps1:138 char:9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : The request was aborted: The connection was closed unexpectedly.
```

It is not my firewall or connection. Other packages updated correctly.

**Comment by rashil2000** [comment]
Fixed
