### ISSUE TITLE
[invalid] libreoffice-fresh

### ISSUE THREAD

**Issue by So2Nik** [ScoopInstaller/Extras#7801]
---
name: "Bug Report"
about: "Cannot install libreoffice-fresh."
title: "[invalid] libreoffice-fresh"
labels: "bug"
---

## Bug Report

**Package Name:** libreoffice-fresh

### Current Behaviour

Installing 'libreoffice-fresh' (7.2.5.2) [64bit]
The remote server returned an error: (404) Not Found.
URL https://downloadarchive.documentfoundation.org/libreoffice/old/7.2.5.2/win/x86_64/LibreOffice_7.2.5.2_Win_x64.msi#/dl.ism is not valid

### Expected Behaviour

libreoffice-fresh to be successfully installed.

### Additional context/output

No LibreOffice_7.2.5.2_Win_x64.msi exists in https://downloadarchive.documentfoundation.org/libreoffice/old/7.2.5.2/win/x86_64/.
However, a LibreOffice_7.2.5_Win_x64.msi do exist there.

### Possible Solution

Change https://downloadarchive.documentfoundation.org/libreoffice/old/7.2.5.2/win/x86_64/LibreOffice_7.2.5.2_Win_x64.msi to https://downloadarchive.documentfoundation.org/libreoffice/old/7.2.5.2/win/x86_64/LibreOffice_7.2.5_Win_x64.msi

### System details

**Windows version:** 10 v21H1

**OS architecture:** 64bit

**PowerShell version:** 
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      0

#### Scoop Configuration

```json
{
  "lastupdate": "2022-01-21T10:13:40.8286866+05:30",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}

```

**Comment by rashil2000** [comment]
This manifest is quite hard to maintain. Any reason for using libreoffice-fresh instead of libreoffice-stable?

**Comment by So2Nik** [comment]
No reason. I thought libreoffice-fresh/stable was following the libreoffice-fresh/still convention of Arch Linux. I now have stable installed. I had already searched the libreoffice official download links and became aware of the issue, so I decided to report it.

**Comment by rashil2000** [comment]
I have removed the libreoffice-fresh manifest, and renamed libreoffice-stable to just libreoffice. 

If you see an error "Manifest has been removed", just rename folder ~/scoop/apps/libreoffice-stable to ~/scoop/apps/libreoffice and folder ~/scoop/persist/libreoffice-stable to ~/scoop/persist/libreoffice.

**Comment by ebat79** [comment]
Now i see this error:
```
F:\tmp>scoop reset libreoffice
ERROR 'libreoffice ()' is not installed
```

**Comment by rashil2000** [comment]
What is inside the ~/scoop/apps/libreoffice folder?

**Comment by ebat79** [comment]
```
F:\scoop\apps\libreoffice>dir
 Il volume nell'unità F è Dati
 Numero di serie del volume: 986E-B5D7

 Directory di F:\scoop\apps\libreoffice

17/01/2022  08:46    <DIR>          .
17/01/2022  08:46    <DIR>          ..
17/01/2022  08:41    <DIR>          7.2.5
17/01/2022  08:41    <JUNCTION>     current [F:\scoop\apps\libreoffice-stable\7.2.5]
               0 File              0 byte
               4 Directory  961.880.166.400 byte disponibili
```

**Comment by rashil2000** [comment]
In that same folder, run:

```batch
> rd /s /q current
> mklink /j current 7.2.5
```
