### ISSUE TITLE
[Request] mdloader

### ISSUE THREAD

**Issue by TurboCartPig** [ScoopInstaller/Extras#7808]
### Information

**Name:** Massdrop loader / mdloader

**Description:** (from readme)
> Massdrop Loader is used to read firmware from and write firmware to Massdrop keyboards which utilize Microchip's SAM-BA  bootloader, over the USB connection.

**Homepage:** https://github.com/Massdrop/mdloader

**Download link(s):** https://github.com/Massdrop/mdloader/releases

**Some indication of popularity/repute:** 383 Stars on GitHub.

This might be niche, but it's also pretty small and simple, just a single cli binary. I could make a pr if approved.

**Comment by rashil2000** [comment]
Sure
