### ISSUE TITLE
[rambox/rambox-pro] Package Name/Version Change issue

### ISSUE THREAD

**Issue by Rohaq** [ScoopInstaller/Extras#7818]
Recently the package rambox-pro.json got renamed to rambox.json - removing the Community Edition from the repository entirely.
2cad5465b609aa65042fea6fbef1aecf733f6b22

I'm not sure why this was done: The pro and community editions offer very different requirements - notably that the Pro version requires an account with Rambox to work.

Should this be reverted? Or should we create a new package `rambox-ce.json` for Rambox Community Edition?

**Comment by Rohaq** [comment]
Tagging @niheaven as the original committer.

**Comment by HUMORCE** [comment]
can you make a PR for `rambox-ce`?

**Comment by rashil2000** [comment]
Rambox CE was moved to Versions bucket following its deprecation.

**Comment by Rohaq** [comment]
Okay, good to know - still a bit unexpected that scoop decided to change which edition was installed for those of us already using the Community Edition, though.

**Comment by niheaven** [comment]
Maybe scoop will be added a new feature of smooth migration, but its priority will be very low.
