### ISSUE TITLE
Brave browser won't start in Win 8.1 x64

### ISSUE THREAD

**Issue by quantuumsnot** [ScoopInstaller/Extras#7820]
Brave browser version:  brave 1.32.106-78
OS: Windows 8.1 x64

The error:
![brave scoop bug](https://user-images.githubusercontent.com/12394810/150689374-e5041920-2e9f-4b5b-866d-771dab651280.jpg)

**Comment by rashil2000** [comment]
Does brave-beta work?

**Comment by quantuumsnot** [comment]
There's probably a wrong exe path in 'brave' shortcut created in `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps`. It was pointed to `brave.exe` instead of `brave-portable.exe`

**Comment by rashil2000** [comment]
The manifest has the correct location for shortcut https://github.com/ScoopInstaller/Extras/blob/297854268ca528a08bb516244f4b1c6376b71a29/bucket/brave.json#L23

Run `scoop reset brave` to recreate shim and shortcut

**Comment by quantuumsnot** [comment]
Did it already before posting the issue, yet something changed the target in the shortcut
