### ISSUE TITLE
Fastcopy v4.0.2

### ISSUE THREAD

**Issue by Xelbayria** [ScoopInstaller/Extras#7829]
## Bug Report

**Package Name:** Fastcopy V4.0.2

### Current Behaviour:

It wasn't able to finish the updating of Fastcopy. and It's having trouble looking for fastcopy.exe. It's looking for in the wrong place. Take a look at the Context/Output. I've updated other apps and had no problems. 

### Expected Behaviour:
It should be looking in Scoop's directory where apps is located.

### Additional context/output

Get-ChildItem : Cannot find path 'C:\Users\USERNAME\FastCopy4.0.2_x64' because it does not exist.
At line:3 char:1
+ Get-ChildItem $extract_dir | Move-Item -Destination $dir
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\USERNAME\FastCopy4.0.2_x64:String) [Get-ChildItem], ItemNotFound
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Remove-Item : Cannot find path 'C:\Users\USERNAME\FastCopy4.0.2_x64' because it does not exist.
At line:4 char:1
+ Remove-Item "$dir\$fname", $extract_dir
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\USERNAME\FastCopy4.0.2_x64:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

Can't shim 'FastCopy.exe': File doesn't exist.
### Possible Solution:
 Haven't found one yet

### System details

**Windows version:** Windows 10 Pro

**OS architecture:** 64bit

**PowerShell version:** 
Major  Minor  Build  Revision
-----    -----  -----  --------
5         1      19041  1320

**Additional software:**  None

#### Scoop Configuration

```json
//#{
    "lastupdate":  "2022-01-25T18:40:30.4353717-07:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
NOTE: not sure if this is the right one. I cannot find the folder ~/.config/
what does ~ stand for? 

```

**Comment by Xelbayria** [comment]
Another note: 

I also uninstalled the old version of Fastcopy and install the new version of Fastcopy. I got the same message

**Comment by CrendKing** [comment]
Weird. I [updated](https://github.com/ScoopInstaller/Extras/pull/7825) this bucket because FastCopy bumped a major version and no longer releases zip archive.

I wonder if this is only a problem related to update. What happens if you uninstall then install?

**Comment by CrendKing** [comment]
The error message `Get-ChildItem : Cannot find path 'C:\Users\USERNAME\FastCopy4.0.2_x64' because it does not exist.` could be caused by several different possibilities:

1. Your Scoop failed to download the installer.
2. The installer was unable to run and extract.
3. The PowerShell `Start-Process` doesn't wait long enough for the process to terminate.

For 1 and 2, you can easily verify yourself by going into the installation directory and check files and folders. For 3, I can give you a modified bucket JSON to try.

**Comment by HUMORCE** [comment]
reproduced in PS 5.1 only

**Comment by CrendKing** [comment]
Then I guess it's that `Start-Process -Wait` behaving differently. I could change it to something like `Start-Sleep 5`. Sounds good?

**Comment by niheaven** [comment]
It is PS5's `DirectoryInfo` error, see https://github.com/ScoopInstaller/Scoop/pull/4676#issuecomment-1019443074.

#7831 should be the right fix.

**Comment by CrendKing** [comment]
OK. I'll close my PR.

**Comment by Xelbayria** [comment]
I see. I don't realize the version of PS could make a big difference. Good to see it get fixed.
