### ISSUE TITLE
Firefox loses settings

### ISSUE THREAD

**Issue by DOFfactory** [ScoopInstaller/Extras#7841]
## Bug Report

**Package Name:** Firefox

### Current Behaviour

I must be missing something, but whenever there is an update of Firefox, all the settings, extensions are lost. Is there a way in Firefox to keep/save the profile somewhere? With the update command I do not want to reset the whole app, just update it.

### Expected Behaviour

Save somewhere externally a Firefox profile, or keep it persistent across updates

### System details

**Windows version:** 10

**OS architecture:** 64

**PowerShell version:** N/A

**Additional software:** N/A

#### Scoop Configuration

```json
{
    "SCOOP_BRANCH":  "master",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "lastupdate":  "2022-01-27T08:16:56.9786072+01:00"
}
```

**Comment by rashil2000** [comment]
Firefox settings are stored in AppData folder. Scoop does not manage them.

**Comment by DOFfactory** [comment]
OK, but then why is with every update all the settings gone, incl. extensions

**Comment by rashil2000** [comment]
Can you check the persist folder? It should be ~/scoop/persist/firefox

**Comment by DOFfactory** [comment]
Yes, I can confirm this folder with subfolders and files exists

**Comment by rashil2000** [comment]
Can you copy them to the relevant AppData folder and see if it works?
