### ISSUE TITLE
gcloud@370.0.0: Decompress error

### ISSUE THREAD

**Issue by tribina** [ScoopInstaller/Extras#7844]
Failed to extract files from C:\Users\ai00020\scoop\apps\gcloud\370.0.0\google-cloud-sdk-370.0.0-windows-x86_64-bundled-python.zip.
Log file:
  ~\scoop\apps\gcloud\370.0.0\7zip.log

Loading google-cloud-sdk-370.0.0-windows-x86_64-bundled-python.zip from cache.
Extracting google-cloud-sdk-370.0.0-windows-x86_64-bundled-python.zip ... ERROR Exit code was 2!
ERROR Failed to extract files from C:\Users\ai00020\scoop\apps\gcloud\370.0.0\google-cloud-sdk-370.0.0-windows-x86_64-bundled-python.zip.
Log file:
  ~\scoop\apps\gcloud\370.0.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/lukesampson/scoop-extras/issues/new?title=gcloud%40370.0.0%3a+Decompress+error&body=Failed+to+extract+files+from+C%3a%5cUsers%5cai00020%5cscoop%5capps%5cgcloud%5c370.0.0%5cgoogle-cloud-sdk-370.0.0-windows-x86_64-bundled-python.zip.%0aLog+file%3a%0a++%7e%5cscoop%5capps%5cgcloud%5c370.0.0%5c7zip.log
ERROR This application failed to update: gclou
[7zip.log](https://github.com/ScoopInstaller/Extras/files/7951620/7zip.log)
d

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Scoop/issues/4647
