### ISSUE TITLE
[Bug] Fastcopy install script moves home folder content to %SCOOP%/apps/FastCopy/current/

### ISSUE THREAD

**Issue by Earthnuker** [ScoopInstaller/Extras#7850]
#### Current Behavior
When running `scoop update '*'` after failing to update FastCopy scoop appears to hang, turns out it had started deleting my %USERPROFILE% folder

#### Expected Behavior
scoop should not delete my userprofile folder

#### Additional context/output
```
Updating 'fastcopy' (3.92 -> 4.0.2)
Downloading new version
FastCopy4.0.2_installer.exe (3,3 MB) [============================================================================================================================================] 100%
Checking hash of FastCopy4.0.2_installer.exe ... ok.
Uninstalling 'fastcopy' (3.92)
Removing shim 'FastCopy.exe'.
Removing shim 'FastCopy.shim'.
Removing shim 'FastCopy.ps1'.
Unlinking ~\scoop\apps\fastcopy\current
Installing 'fastcopy' (4.0.2) [64bit]
Loading FastCopy4.0.2_installer.exe from cache
Running pre-install script...
Running installer script...
ERROR Exit code was -1073740791!
<Hangs, ProcessHacker shows powershell process accessing many files in %USERPROFILE%>
```

### System details

**Windows version:** 10

**OS architecture:** 64-bit

**PowerShell version:** 5.1.19041.1320

**Additional software:** <NA>

#### Scoop Configuration
```
```

**Comment by HUMORCE** [comment]
but the installer runs fine on my/other PC, i think your OS is break by something
