### ISSUE TITLE
Paint.net Fail

### ISSUE THREAD

**Issue by paperclipstudio** [ScoopInstaller/Extras#7854]
## Bug Report

**Package Name:** Paint.Net

### Current Behaviour

Install Fails

### Expected Behaviour

Install Paint.net

### Additional context/output

Installing 'paint.net' (4.3.4) [64bit]
The remote server returned an error: (404) Not Found.
URL https://github.com/paintdotnet/release/releases/download/v4.3.4/paint.net.4.3.4.portable.x64.zip is not valid
### Possible Solution

I think it just needs to be updated to the 4.3.7

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:**
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1320

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
Please make a PR for the update

**Comment by paperclipstudio** [comment]
No I think is due to a failing update on my system
