### ISSUE TITLE
why doesn't xdman use javaw.exe in the Portable folder?

### ISSUE THREAD

**Issue by candrapersada** [ScoopInstaller/Extras#7859]
`jre\bin\javaw.exe`
![image](https://user-images.githubusercontent.com/36833664/151645449-bf0b4e17-5e53-4ed9-a5a4-0c5c0be0a97b.png)
![image](https://user-images.githubusercontent.com/36833664/151645497-f5ad6e0c-3b24-45bb-b074-af297773341d.png)
![image](https://user-images.githubusercontent.com/36833664/151645538-b069111b-b0f8-42a5-9b00-612691d2cf0e.png)

**Comment by HUMORCE** [comment]
the package is out of date.

after PR #7869 , standalone JAR instead of MSI installer.
