### ISSUE TITLE
Can not set LibreWolf as default browser

### ISSUE THREAD

**Issue by he3als** [ScoopInstaller/Extras#7873]
## Bug Report

**Package Name:** `librewolf`

### Current Behaviour

Clicking the 'Make Default' button in LibreWolf to set it as the default browser does nothing and does not work. It also does not show up in the modern Settings app for Windows 10/11 and does not show in Control Panel for Windows 8.1 and older.

![librewolf_o586QNhyM5](https://user-images.githubusercontent.com/65787561/151703364-0b1dd159-2e2a-4749-9cf8-6c6762bed6be.gif)

### Expected Behaviour

Clicking the 'Make Default' button should make an entry in the default apps of the modern Settings app and the Control Panel as an option and the button should set LibreWolf as the default browser.

### System details

**Windows version:** 10 21H2

**OS architecture:** amd64

**PowerShell version:** Powershell 5 - Build 19041 - Revision 1237

**Scoop configuration:** Default

**Comment by he3als** [comment]
Using the regular installer would fix this

**Comment by criticic** [comment]
You have to edit the registry. See https://github.com/amreus/scoop-default-browser/blob/main/firefox-default-scoop-template.reg for reference.

**Comment by rashil2000** [comment]
Yes. This is by design. Scoop will not modify the registry to register applications as protocol handlers or type associations. 

But you can select a default browser by providing full path to the application.

**Comment by criticic** [comment]
Btw update to 96.0.3 to get that template to work as earlier versions did not pass parameters (https://gitlab.com/librewolf-community/browser/windows/-/commit/31eb3460391ea449bccd89677226c35489051bb0)

**Comment by he3als** [comment]
@criticic do you know why when i open a link that it opens a whole new librewolf window and it is pretty slow instead of just opening in the current librewolf window open? here is the reg i have got: 
```Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\RegisteredApplications]
"LibreWolf (Scoop)"="Software\\Clients\\StartMenuInternet\\LibreWolf (Scoop)\\Capabilities"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\LibreWolf (Scoop)\shell\open\command]
""="\"C:\\Users\\he3als\\scoop\\shims\\librewolf.exe\""

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\LibreWolf (Scoop)\DefaultIcon]
""="C:\\Users\\he3als\\scoop\\apps\\LibreWolf\\current\\librewolf-portable.exe,0"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\LibreWolf (Scoop)\Capabilities\FileAssociations]
".html"="ScoopLibreWolfHTM"
".htm"="ScoopLibreWolfHTM"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\LibreWolf (Scoop)\Capabilities\URLAssociations]
"https"="ScoopLibreWolfHTM"
"http"="ScoopLibreWolfHTM"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\LibreWolf (Scoop)\Capabilities]
"ApplicationName"="LibreWolf (Scoop)"
"ApplicationIcon"="C:\\Users\\he3als\\scoop\\apps\\LibreWolf\\current\\librewolf-portable.exe,0"
"ApplicationDescription"="LibreWolf"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\LibreWolf (Scoop)]
""="LibreWolf (Scoop)"

[HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibreWolfHTM\shell\open\command]
""="\"C:\\Users\\he3als\\scoop\\shims\\librewolf.exe\" %1"

[HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibreWolfHTM\Application]
; Name in Dialog
"ApplicationName"="LibreWolf (Scoop)"
"ApplicationDescription"="It's LibreWolf."
"ApplicationIcon"="C:\\Users\\he3als\\scoop\\apps\\LibreWolf\\current\\librewolf-portable.exe,0"

[HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibreWolfHTM]
""="LibreWolf (Scoop) HTML Document"```

**Comment by he3als** [comment]
it also opens a temporary cmd window, which is a bit annoying. how can i fix it?

**Comment by criticic** [comment]
Instead of librewolf-portable.exe maybe try librewolf.exe, ( it can be found in (scoop prefix librewolf) > Librewolf > librewolf.exe )

**Comment by criticic** [comment]
@rashil2000 wouldn't it make sense to register the apps, like it is done for vscode. Maybe a script can be added. AFAIK it doesn't require admin perms.

**Comment by rashil2000** [comment]
Check https://github.com/ScoopInstaller/Scoop/discussions/4633

**Comment by criticic** [comment]
maybe add a note with a link to a registry file, which they can use if they want.

**Comment by criticic** [comment]
```
Windows Registry Editor Version 5.00


[HKEY_CURRENT_USER\SOFTWARE\RegisteredApplications]
"Librewolf (Scoop)"="Software\\Clients\\StartMenuInternet\\Librewolf (Scoop)\\Capabilities"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\shell]
[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\shell\open]
[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\shell\open\command]
@="\"C:\\Users\\_USERNAME_\\scoop\\apps\\librewolf\\current\\LibreWolf\\librewolf.exe\" \"%1\""

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\DefaultIcon]
""="C:\\Users\\_USERNAME_\\scoop\\apps\\librewolf\\current\\LibreWolf\\librewolf.exe,0"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\Capabilities\FileAssociations]
".html"="ScoopLibrewolfHTM"
".htm"="ScoopLibrewolfHTM"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\Capabilities\URLAssociations]
"https"="ScoopLibrewolfHTM"
"http"="ScoopLibrewolfHTM"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\Capabilities]
"ApplicationName"="Librewolf (Scoop)"
"ApplicationIcon"="C:\\Users\\_USERNAME_\\scoop\\apps\\librewolf\\current\\LibreWolf\\librewolf.exe,0"
"ApplicationDescription"="Librewolf"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)]
""="Librewolf (Scoop)"

[HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibrewolfHTM\shell]
[HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibrewolfHTM\shell\open]
[HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibrewolfHTM\shell\open\command]
@="\"C:\\Users\\_USERNAME_\\scoop\\apps\\librewolf\\current\\LibreWolf\\librewolf.exe\" \"%1\""

[HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibrewolfHTM\Application]
; Name in Dialog
"ApplicationName"="Librewolf (Scoop)"
"ApplicationDescription"="Librewolf - An independent fork of Firefox, with the primary goals of privacy, security and user freedom."
"ApplicationIcon"="C:\\Users\\_USERNAME_\\scoop\\apps\\librewolf\\current\\LibreWolf\\librewolf.exe,0"

[HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibrewolfHTM]
""="Librewolf (Scoop) HTML Document"
```
@he3als this registry config works for me try this.

**Comment by he3als** [comment]
worked thanks

**Comment by jwmh** [comment]
Can this please be re-opened?
It doesnt appear to be working currently with the latest scoop/librewolf install!  
platform: Windows 20H2 (OS Build 19042.2006).

**Comment by he3als** [comment]
you have to change `_USERNAME_`

also, i would recommend winget or chocolatey for this

**Comment by epicEaston197** [comment]
There really should be an option to make it the default browser this is really annoying and I have no clue on how to edit the registry or anything like that

**Comment by basketshoe** [comment]
> ```
> Windows Registry Editor Version 5.00
> 
> 
> [HKEY_CURRENT_USER\SOFTWARE\RegisteredApplications]
> "Librewolf (Scoop)"="Software\\Clients\\StartMenuInternet\\Librewolf (Scoop)\\Capabilities"
> 
> [HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\shell]
> [HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\shell\open]
> [HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\shell\open\command]
> @="\"C:\\Users\\_USERNAME_\\scoop\\apps\\librewolf\\current\\LibreWolf\\librewolf.exe\" \"%1\""
> 
> [HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\DefaultIcon]
> ""="C:\\Users\\_USERNAME_\\scoop\\apps\\librewolf\\current\\LibreWolf\\librewolf.exe,0"
> 
> [HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\Capabilities\FileAssociations]
> ".html"="ScoopLibrewolfHTM"
> ".htm"="ScoopLibrewolfHTM"
> 
> [HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\Capabilities\URLAssociations]
> "https"="ScoopLibrewolfHTM"
> "http"="ScoopLibrewolfHTM"
> 
> [HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)\Capabilities]
> "ApplicationName"="Librewolf (Scoop)"
> "ApplicationIcon"="C:\\Users\\_USERNAME_\\scoop\\apps\\librewolf\\current\\LibreWolf\\librewolf.exe,0"
> "ApplicationDescription"="Librewolf"
> 
> [HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\Librewolf (Scoop)]
> ""="Librewolf (Scoop)"
> 
> [HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibrewolfHTM\shell]
> [HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibrewolfHTM\shell\open]
> [HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibrewolfHTM\shell\open\command]
> @="\"C:\\Users\\_USERNAME_\\scoop\\apps\\librewolf\\current\\LibreWolf\\librewolf.exe\" \"%1\""
> 
> [HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibrewolfHTM\Application]
> ; Name in Dialog
> "ApplicationName"="Librewolf (Scoop)"
> "ApplicationDescription"="Librewolf - An independent fork of Firefox, with the primary goals of privacy, security and user freedom."
> "ApplicationIcon"="C:\\Users\\_USERNAME_\\scoop\\apps\\librewolf\\current\\LibreWolf\\librewolf.exe,0"
> 
> [HKEY_CURRENT_USER\SOFTWARE\Classes\ScoopLibrewolfHTM]
> ""="Librewolf (Scoop) HTML Document"
> ```
> 
> @he3als this registry config works for me try this. (It will not use scoops persist directory, the profile is present at %appdata%/librewolf)

can confirm this works for mullvad-browser too with small path tweaking 🙇🏻‍♂️

**Comment by Hash6232** [comment]
> @he3als this registry config works for me try this. (It will not use scoops persist directory, the profile is present at %appdata%/librewolf)

Just wanted to mention that all you have to do to use the profile inside the persist directory is replacing each instance of `LibreWolf\\librewolf.exe` with `LibreWolf-Portable.exe`. Not doing that will make programs open a new unrelated browser window instead of using the one you are already using (if you are actually using the profile inside the persist directory that is).
