### ISSUE TITLE
KDE apps get updated daily

### ISSUE THREAD

**Issue by rashil2000** [ScoopInstaller/Extras#7881]
KDE applications get updated daily - kate, okular and kdeconnect - even when there's technically no new release. KDE Binary Factory builds the release version of the apps daily, for some reason. Personally, I think the daily update brings in a lot of bloat.

- We can't move it to _Versions_ bucket because it's not a nightly
- There's no permalink for the latest successful build
- Artifact for each day gets deleted in 72 hours

I don't know how to fix this. @issaclin32 thoughts?

**Comment by criticic** [comment]
https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Release_win64/861/artifact/
One release lasts for 3 days, i think it should be treated as nightly.

**Comment by rashil2000** [comment]
Nightly builds are different, see https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Nightly_win64

**Comment by criticic** [comment]
Both versions nightly(#1054)[1] & release21.12.1(#865)[2] are build from same git commit ie 2cebf5c35feaac11f66b15b2d8812b4bb1bcc8d2

[1] https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Nightly_win64/1054/
[2] https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Release_win64/865/

As for why they do this, I have no idea, onky a kde maintainer would know.

**Comment by criticic** [comment]
Also the builds are released everyday, even if there is no change, https://github.com/KDE/kdeconnect-kde/commits/master

**Comment by rashil2000** [comment]
Ah, I see. Thanks for the detailed analysis. Really strange CI/CD setup they've got there. 

I guess the best option would to move them to Versions, for now.

**Comment by issaclin32** [comment]
> I guess the best option would to move them to Versions, for now.

I guess so. 
I cannot think of any simple solution to this, unless we can find a mirror/reliable third-party site for the files.
