### ISSUE TITLE
godot-mono shim overwrites the one fom the godot package

### ISSUE THREAD

**Issue by heretique** [ScoopInstaller/Extras#7902]
## Bug Report

**Package Name:** [godot-mono]

### Current Behaviour

The `godot-mono` variant's shim is overwriting the one from the `godot` package.

### Expected Behaviour

I am able to use both `godot` and `godot-mono` versions.
### Additional context/output

```
Installing 'godot' (3.4.2) [64bit]
Loading Godot_v3.4.2-stable_win64.exe.zip from cache
Checking hash of Godot_v3.4.2-stable_win64.exe.zip ... ok.
Extracting Godot_v3.4.2-stable_win64.exe.zip ... done.
Running pre-install script...
Linking ~\scoop\apps\godot\current => ~\scoop\apps\godot\3.4.2
Creating shim for 'godot'.
Creating shortcut for Godot (godot.exe)
'godot' (3.4.2) was installed successfully!
Installing 'godot-mono' (3.4.2) [64bit]
Loading Godot_v3.4.2-stable_mono_win64.zip from cache
Checking hash of Godot_v3.4.2-stable_mono_win64.zip ... ok.
Extracting Godot_v3.4.2-stable_mono_win64.zip ... done.
Running pre-install script...
Linking ~\scoop\apps\godot-mono\current => ~\scoop\apps\godot-mono\3.4.2
Creating shim for 'godot'.
WARN  Overwriting shim ('godot.exe' -> 'godot.exe') installed from godot
Creating shortcut for GodotMono (godot.exe)
'godot-mono' (3.4.2) was installed successfully!
```

### Possible Solution

Provide a separate `godot-mono.exe` shim that doesn't overwrite the one from `godot` package.

### System details

**Windows version:** [11]

**OS architecture:** [64bit]

**PowerShell version:** [7.2.1]

**Comment by rashil2000** [comment]
Sounds good. Can you make a PR?

**Comment by heretique** [comment]
If there isn't someone else with more experience that can help with this I could try. I've never done this before but I guess with some research into Scoop's manifest files I could do it.

**Comment by rashil2000** [comment]
You just have to make the `bin` field of the godot-mono.json manifest the same as the `shortcut` field.
