### ISSUE TITLE
These applications manifests have been removed

### ISSUE THREAD

**Issue by ebat79** [ScoopInstaller/Extras#7905]
## Bug Report

**Package Name:** libreoffice-portable
**Package Name:** vscode-portable

### Current Behaviour

This is the output of `scoop status` command:

```
F:\> scoop status
Scoop is up to date
These applications manifests have been removed:
    libreoffice-stable
    vscode-portable
```

### Expected Behaviour

- What to do now?

- Can i preserve the `vscode-portable` and `libreoffice-portable` configurations with another bucket of the same applications?

### System details

**Windows version:** 10

**OS architecture:** 64bit

#### Scoop Configuration

```json
{
    "SCOOP_BRANCH":  "main",
    "SCOOP_REPO":  "https://github.com/Ash258/Scoop-Core",
    "lastupdate":  "258|2022-02-04 09:30:18",
    "MSIEXTRACT_USE_LESSMSI":  true,
    "default-architecture":  "64bit",
    "aria2-enabled":  true
}
```

**Comment by rashil2000** [comment]
See my comment here https://github.com/ScoopInstaller/Extras/issues/7801#issuecomment-1019716706
