### ISSUE TITLE
Error while installing cheat-engine

### ISSUE THREAD

**Issue by Absolves** [ScoopInstaller/Extras#7906]
## Bug Report

**Package Name:** cheat-engine

### Current Behaviour

An error pops up after I install the software. It looks like the cheat-engine installer was not extracted properly by innounp.

### Expected Behaviour

This software installs normally.

### Additional context/output

Installing 'cheat-engine' (7.4) [64bit]
CheatEngine74.exe (3.2 MB) [==================================================================================] 100%
Checking hash of CheatEngine74.exe ... ok.
Extracting CheatEngine74.exe ... done.
Linking ~\scoop\apps\cheat-engine\current => ~\scoop\apps\cheat-engine\7.4
Creating shortcut for Cheat Engine (Cheat Engine.exe) failed: Couldn't find C:\Users\WDAGUtilityAccount\scoop\apps\cheat-engine\current\Cheat Engine.exe
Creating shortcut for Cheat Engine Windows Repair (windowsrepair.exe) failed: Couldn't find C:\Users\WDAGUtilityAccount\scoop\apps\cheat-engine\current\windowsrepair.exe
Creating shortcut for Cheat Engine Tutorial (Tutorial-x86_64.exe) failed: Couldn't find C:\Users\WDAGUtilityAccount\scoop\apps\cheat-engine\current\Tutorial-x86_64.exe
'cheat-engine' (7.4) was installed successfully!

### Possible Solution

Maybe we can just install it? The software can be downloaded normally.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** innounp

**Comment by rashil2000** [comment]
What are the installation parameters in the commandline?

**Comment by Stzx** [comment]
https://github.com/cheat-engine/cheat-engine/issues/2038

Waiting for feedback from the author, if direct downloads are not supported, I think this package should be removed ;(

**Comment by Stzx** [comment]
[It seems to have the answer.](https://github.com/cheat-engine/cheat-engine/issues/2038#issuecomment-1029940572)
