### ISSUE TITLE
[Request] mullvad

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7907]
Package Request Information
Name: Mullvad

Description: Cheap, open source and reliable VPN from Sweden

Homepage: https://mullvad.net/en/pricing/

Download link(s): https://github.com/mullvad/mullvadvpn-app/releases/download/2021.6/MullvadVPN-2021.6.exe

Some indication of popularity/repute: Github  2000 stars

**Comment by rashil2000** [comment]
Why do you open the same request again and again?

https://github.com/ScoopInstaller/Extras/issues/7113
