### ISSUE TITLE
[Request] ivpn

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#7912]
Package Request Information
Name: ivpn

Description: Cheap, open source and reliable VPN from gibraltar

Homepage: https://www.ivpn.net/apps-windows/

Download link(s): https://repo.ivpn.net/windows/bin/IVPN-Client-v3.5.2.exe

Some indication of popularity/repute: Github  83 stars

**Comment by rashil2000** [comment]
Please make a PR!
