### ISSUE TITLE
[Request] Add gyroflow

### ISSUE THREAD

**Issue by KnotUntied** [ScoopInstaller/Extras#7913]
### Information

**Name:** Gyroflow

**Description:** Software for video stabilization.

**Homepage:** https://gyroflow.xyz/, https://github.com/gyroflow/gyroflow

**Download link(s):** [Releases page](https://github.com/gyroflow/gyroflow/releases), [Windows 64-bit release](https://github.com/gyroflow/gyroflow/releases/download/v1.0.0-rc1/Gyroflow-windows64.zip)

**Some indication of popularity/repute:** 273 stars on aforementioned repository as of writing, plus positive reception in [Reddit](https://www.reddit.com/r/rust/comments/skbvqx/announcing_gyroflow_an_advanced_video/). Rewritten in Rust from the original Python code, see legacy repository [here](https://github.com/ElvinC/gyroflow).

**Comment by rashil2000** [comment]
Can you make a PR?

**Comment by KnotUntied** [comment]
Done making the PR, though I admit I skipped reading the contribution guide and used the fork's master branch. My fault.
