### ISSUE TITLE
CrystalDiskInfo: Very slow download speed

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Extras#7922]
## Bug Report

**Package Name:** CrystalDiskInfo

### Current Behaviour

Downloads at 20kb/s

### Expected Behaviour

Downloads at at least 1MB/s to make the download experience good enough.

### Additional context/output

Compared to any other app, this app specifically takes forever to download.

### Possible Solution

I noticed that the source for CrystalDiskMark is hosting CrystalDiskInfo as well and seems to have a comparable storage structure.

Simply replacing "Mark" with "Info" in the URL I could confirm this; https://free.nchc.org.tw/osdn/crystaldiskinfo/

Looking at the two manifests, it's possible that the same structure for autoupdate and URLs could be used to solve the problem.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** 

#### Scoop Configuration

{
  "MSIEXTRACT_USE_LESSMSI": true,
  "SCOOP_REPO": "https://github.com/Ash258/Scoop-Core",
  "SCOOP_BRANCH": "main",
  "lastupdate": "258|2022-02-06 09:19:48"
}

**Comment by rashil2000** [comment]
Please make a PR!
