### ISSUE TITLE
Bug in sweethome3d.json

### ISSUE THREAD

**Issue by cvladan** [ScoopInstaller/Extras#7925]
## Bug Report

sweethome3d.json

### Current Behaviour

Program is unable to save preferences.
When opening a document, there is a message: "Can't save preferences in file system"

### Expected Behaviour

To save preferences.

### Additional context/output

Preferences are saved in `preferences.xml` file, but Scoop created a folder in "persist",
and created soft link to that folder. That soft link should point to a file.

### Possible Solution

Solution is not to create a junction point to folder, but to file.

This solves a problem:

```
cd "%USERPROFILE%\scoop\apps\sweethome3d\current\data"
mklink preferences.xml "%USERPROFILE%\scoop\persist\sweethome3d\data\preferences.xml"
```

**Comment by cvladan** [comment]
Also, I think folders `furniture` and `textures` should be added as persistant data

**Comment by rashil2000** [comment]
Please make a PR for your fix!

**Comment by issaclin32** [comment]
Fixed in https://github.com/ScoopInstaller/Extras/commit/cb79161f1743204adb7933f7e72fbd62e0ac6b6f
