### ISSUE TITLE
[Request] raylib

### ISSUE THREAD

**Issue by criticic** [ScoopInstaller/Extras#7927]
## Package Request
Raylib
### Information
https://github.com/raysan5/raylib
MSVC version will be similar to sdl2 manifest.

**Name:** [name of new package]
Raylib

**Description:** [clear and concise details of what it is]
raylib is a simple and easy-to-use library to enjoy videogames programming.

**Homepage:** [a URL/link]
https://raylib.com

**Download link(s):** [URL(s)/link(s)]
MSVC https://github.com/raysan5/raylib/releases/download/4.0.0/raylib-4.0.0_win64_msvc16.zip
MinGW https://github.com/raysan5/raylib/releases/download/4.0.0/raylib-4.0.0_win64_mingw-w64.zip

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
8.6k stars on github
https://itch.io/games/made-with-raylib

**Comment by tech189** [comment]
Would this require two manifests, one for 32/64bit `msvc16` zip and one for 32/64bit `mingw` zip?

**Comment by criticic** [comment]
>Would this require two manifests, one for 32/64bit msvc16 zip and one 
>for 32/64bit mingw zip?
>
i think so, maybe raylib & raylib-mingw. msvc version should be default.

**Comment by issaclin32** [comment]
@criticic In [sdl2-image.json](https://github.com/ScoopInstaller/Extras/blob/master/bucket/sdl2-image.json), there are some manipulations on `PKG_CONFIG_PATH` and `CMAKE_PREFIX_PATH`.

Is there anything we should **add to env variables** for this package?

**Comment by issaclin32** [comment]
> Here's what I have so far, it just downloads and adds `$dir` to path for now. **raylib.json**

Would you consider sending a PR **to the main bucket**?
`sdl2` packages are in **extras** because there are some elaborations in pre/post install script.

**Comment by tech189** [comment]
I had a look at the sdl2-image manifest but I'm a bit lost! It seems to need a `SDL2_image.pc.in` file which raylib's release zip doesn't include. I found it in the source here: https://github.com/raysan5/raylib/blob/master/raylib.pc.in. Would the script be as simple as creating a `pkgconfig` folder in `lib` with that file inside, plus adding that folder to the `PKG_CONFIG_PATH` and `CMAKE_PREFIX_PATH` env variables?

Also could anyone explain what `"$current_dir = \"$(current_dir $dir)\"",` does?

**Comment by criticic** [comment]
Also could anyone explain what "$current_dir = \"$(current_dir $dir)\"", does?
https://github.com/ScoopInstaller/Scoop/blob/master/lib/install.ps1#L902-L905
Sets variable current_dir to whatever is returned from the above function(passing $dir), i think you should rename it to avoid confusion as both function name & variable name are same.

**Comment by tech189** [comment]
@criticic I made a PR with your suggestions, thanks! Could you try it out (see if the env variables all work correctly) and make any further suggestions there?
