### ISSUE TITLE
EarTrumpet install UX does not match supported install channels

### ISSUE THREAD

**Issue by riverar** [ScoopInstaller/Extras#7929]
## Bug Report

**Package Name:** EarTrumpet

### Current Behaviour

Hi there, I'm one of the EarTrumpet owners 👋. Our users are not getting the default installation experience as our supported installation channels. In this case, the EarTrumpet app is not configured correctly to start with Windows, leading to confusion (and has resulted in an issue filed in our repository).

### Expected Behaviour

EarTrumpet to start up with Windows after Scoop installation.

### Additional context/output

https://github.com/File-New-Project/EarTrumpet/discussions/1053

### Possible Solution

See our [`ChocolateyInstall.ps1`](https://community.chocolatey.org/packages/eartrumpet#files):
```powershell
...
Write-Output "Adding shortcut to Startup"
New-ItemProperty -LiteralPath 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run' -Name 'EarTrumpet' -Value $exePath -PropertyType String -Force -ea SilentlyContinue | Out-Null
```

**Comment by rashil2000** [comment]
Can you please provide a .reg file that the users can run after installing EarTrumpet? The Scoop package will include it.

Note that this is the standard method for managing registry items for Scoop apps. Scoop will not touch the registry and/or any machine/global settings (this is by design).

**Comment by rashil2000** [comment]
You can have a look at the https://github.com/ScoopInstaller/Extras/tree/master/scripts folder, where .reg files (and other similar scripts) are present. Ideally, a .reg file for both adding and removing the startup entry from the registry should be provided.

**Comment by riverar** [comment]
Does Scoop notify the user of these .reg files and/or offer to run them automatically?

**Comment by rashil2000** [comment]
It will notify the users, but will not run them automatically.
