### ISSUE TITLE
Scoop not updating StandardNotes to 3.9.20. Stuck on 3.9.10

### ISSUE THREAD

**Issue by scorchgid** [ScoopInstaller/Extras#7932]
## Bug Report

**standardnotes: 3.9.10** [name of package which has bug(s)]

### Current Behaviour

Scoop is stating that standardnotes: 3.9.10 is the latest version

### Expected Behaviour

Scoop should update standard notes to .20

### Possible Solution

Update manually? But that may cause further issues.

### System details

**Windows version:** 
10
Version	10.0.19044 Build 19044

**OS architecture:** 
64bit

**PowerShell version:** 

windows-terminal 1.11.3471.0 using Powershell.

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1320

**Additional software:** [(optional) e.g. ConEmu, Git]

git 2.35.1.windows.2 [main]

#### Scoop Configuration
```json
{
    "lastupdate":  "2022-02-07T15:21:27.6689666+00:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by hu3rror** [comment]
Hi, What output information do you have after you enter `scoop update`?

**Comment by rashil2000** [comment]
Cannot reproduce:

![image](https://user-images.githubusercontent.com/46838874/152989570-c84638f5-0ed1-4ba1-a036-e0173dc16f4e.png)

**Comment by scorchgid** [comment]
> Hi, What output information do you have after you enter `scoop update`?
![image](https://user-images.githubusercontent.com/6419740/153203932-061fa2c6-abaf-4df9-aa9c-893231709683.png)

I believe this is the error but not sure how to resolve?

**Comment by hu3rror** [comment]
Just follow the code below:)
```pwsh
scoop bucket rm extras; scoop bucket add extras
```

**Comment by scorchgid** [comment]
> > > Hi, What output information do you have after you enter `scoop update`?
> > > ![image](https://user-images.githubusercontent.com/6419740/153203932-061fa2c6-abaf-4df9-aa9c-893231709683.png)
> > 
> > 
> > I believe this is the error but not sure how to resolve?
> 
> Just follow the code below:)
> 
> ```powershell
> scoop bucket rm extras; scoop bucket add extras
> ```

You're an absolute star ⭐thank you
This fixed my issue so I'm good now.
