### ISSUE TITLE
mpv@0.34.0: download via aria2 failed

### ISSUE THREAD

**Issue by ccireedui** [ScoopInstaller/Extras#7934]
PS C:\Users\ccire> scoop install mpv
WARN  Purging previous failed installation of mpv.
Uninstalling 'mpv' ().
'mpv' was uninstalled.
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'mpv' (0.34.0) [64bit]
Starting download with aria2 ...
Download: 02/08 02:35:36 [ERROR] CUID#8 - Download aborted. URI=https://downloads.sourceforge.net/project/mpv-player-winDownload: Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attDownload: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: b5b718|ERR |       0B/s|C:/Users/ccire/scoop/cache/mpv#0.34.0#https_downloads.sourceforge.net_project_mpv-player-windows_release_mpv-0.34.0-x86_64.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://downloads.sourceforge.net/project/mpv-player-windows/release/mpv-0.34.0-x86_64.7z
    dir=C:\Users\ccire\scoop\cache
    out=mpv#0.34.0#https_downloads.sourceforge.net_project_mpv-player-windows_release_mpv-0.34.0-x86_64.7z

ERROR & 'C:\Users\ccire\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\ccire\scoop\cache\mpv.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=9664 --continue --summary-interval=0 --auto-save-interval=1

**Comment by rashil2000** [comment]
Cannot reproduce. Probably some network error.

![image](https://user-images.githubusercontent.com/46838874/152850750-80bca954-9205-4583-84f6-71eb25388458.png)
