### ISSUE TITLE
[Request] Ricochet-refresh : new version

### ISSUE THREAD

**Issue by SonaliBendre** [ScoopInstaller/Extras#7954]
## Bug Report

**Package Name:** [name of package which has bug(s)]
Ricochet-refresh
### Possible Solution

New forked repo is https://www.ricochetrefresh.net/
https://github.com/blueprint-freespeech/ricochet-refresh
### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
Please make a PR to update the manifest

**Comment by SonaliBendre** [comment]
I've asked @TheLastZombie to make PR https://github.com/TheLastZombie/scoop-bucket/commit/3e8b418c7156753a51e1e71c9db4383bed75fbc6
Currently I install and update  from his bucket
