### ISSUE TITLE
[Request] Cwtch

### ISSUE THREAD

**Issue by SonaliBendre** [ScoopInstaller/Extras#7955]
### Information

**Name:** [name of new package]
Cwtch
**Description:** [clear and concise details of what it is]
Cwtch (/kʊtʃ/ - a Welsh word roughly translating to “a hug that creates a safe place”) is a decentralized, privacy-preserving, multi-party messaging protocol that can be used to build metadata resistant applications.
**Homepage:** [a URL/link]
https://cwtch.im/
**Download link(s):** [URL(s)/link(s)]
https://cwtch.im/releases/cwtch-v1.6.0/cwtch-v1.6.0.zip
**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
https://news.ycombinator.com/item?id=27643171

**Comment by rashil2000** [comment]
Please make a PR!

**Comment by SonaliBendre** [comment]
I've asked @TheLastZombie to make PR https://github.com/TheLastZombie/scoop-bucket/commit/3e8b418c7156753a51e1e71c9db4383bed75fbc6
Currently I install and update  from his bucket
