### ISSUE TITLE
[Request] TrafficMonitor - Lite Version

### ISSUE THREAD

**Issue by bin456789** [ScoopInstaller/Extras#7956]
### Information

**Name:** 
TrafficMonitor - Lite Version

**Description:**
Lite version of TrafficMonitor.  Does not required Administrator to run, does not contain GPU, Hard Disk or temperature monitoring

**Homepage:**
https://github.com/zhongyang219/TrafficMonitor

**Download link(s):** 
https://github.com/zhongyang219/TrafficMonitor/releases

**Some indication of popularity/repute:** 
TrafficMonitor full version is already in extras bucket. 
 https://github.com/ScoopInstaller/Extras/blob/master/bucket/trafficmonitor.json

**Comment by rashil2000** [comment]
Can you make a PR? Should be simple.
