### ISSUE TITLE
[Request] Spotify

### ISSUE THREAD

**Issue by itsmeboy0** [ScoopInstaller/Extras#7962]
### Information

**Name:** Spotify
**Description:** Digital music service.

**Homepage:** https://www.spotify.com/

**Download link(s):** https://download.scdn.co/SpotifyFullSetup.exe

**Some indication of popularity/repute:**

**Comment by rashil2000** [comment]
I would recommend installing it from that bucket - it is especially made for Spotify stuff.

**Comment by Luckz** [comment]
> Found this but it's not a known bucket? https://github.com/TheRandomLabs/Scoop-Spotify

I would not recommend that bucket.

The human-maintained bucket is https://github.com/zwxi/Scoop-Spotify

**Comment by sitiom** [comment]
Hmm, I thought this would close if both linked PRs were merged 🤔

**Comment by rashil2000** [comment]
1 is sufficient
