### ISSUE TITLE
Mumble not updating to latest version

### ISSUE THREAD

**Issue by DutchFlander** [ScoopInstaller/Extras#7971]
## Bug Report

**Package Name:** mumble

### Current Behaviour

Since a month now the old stable is available only in extras repository

### Expected Behaviour

Latest should be available:
https://dl.mumble.info/latest/stable/client-windows-x64.msi
https://dl.mumble.info/stable/
<html>
<body>

  | mumble_client-1.4.230.x64.msi | 2022-01-16 17:34 | 31M |  
-- | -- | -- | -- | --

</body>
</html>

### Additional context/output

PS C:\Users\dutch> scoop list mumble
Installed apps matching 'mumble':

  mumble 1.3.4 *global* [extras]

PS C:\Users\dutch>

----------

https://github.com/ScoopInstaller/Extras/blob/master/bucket/mumble.json
```"version": "1.3.4",```
### Possible Solution

Update extrax bucket

### System details

N/A

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-02-15T12:19:34.2439724+01:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
Can you make a PR for the update?
