### ISSUE TITLE
mumble

### ISSUE THREAD

**Issue by DutchFlander** [ScoopInstaller/Extras#7972]
### Information

**Name:**
mumble

**Description:**
already known scoop app

**Homepage:**
https://dl.mumble.info/stable/
<html>
<body>

  | mumble_client-1.4.230.x64.msi | 2022-01-16 17:34 | 31M |  
-- | -- | -- | -- | --

</body>
</html>

**Download link(s):**
https://dl.mumble.info/latest/stable/client-windows-x64.msi

**Some indication of popularity/repute:**
PS C:\Users\dutch> scoop list mumble
Installed apps matching 'mumble':

  mumble 1.3.4 *global* [extras]

It is already in scoop, but not updating since a month now.

**Comment by DutchFlander** [comment]
> Oh, I meant Pull Request, as in a contribution, not a package-request 😅

Sorry, I don't know how to do that (I've never did a pull request ever)...

**Comment by rashil2000** [comment]
It's not very difficult - you can read our [Contributing guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md) to get started :)
