### ISSUE TITLE
[Request] Rancher-Desktop

### ISSUE THREAD

**Issue by Console32** [ScoopInstaller/Extras#7973]
### Information

**Name:** rancher-desktop

**Description:** Kubernetes and Container Management on the Desktop

**Homepage:** [github Page](https://github.com/rancher-sandbox/rancher-desktop)

**Download link(s):** https://github.com/rancher-sandbox/rancher-desktop/releases

**Some indication of popularity/repute:** 2.8k Stars

I can provide the manifest.

**Comment by rashil2000** [comment]
Sure
