### ISSUE TITLE
potplayer@220106: download via aria2 failed

### ISSUE THREAD

**Issue by wu-x20** [ScoopInstaller/Extras#7975]
#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/154208075-8b836081-954b-4ee0-92a0-6b81ea730a0e.png)

**Comment by wu-x20** [comment]
> 

I just download via aria,but it failed

the errors are like this

ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://t1.daumcdn.net/potplayer/PotPlayer/Version/220106/PotPlayerSetup64.exe#/dl.7z
    referer=https://t1.daumcdn.net/potplayer/PotPlayer/Version/220106/PotPlayerSetup64.exe#/
    dir=D:\Scoop\cache
    out=potplayer#220106#https_t1.daumcdn.net_potplayer_PotPlayer_Version_220106_PotPlayerSetup64.exe_dl.7z

ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\potplayer.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=14112 --continue --summary-interval=0 --auto-save-interval=1

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=potplayer%40220106%3a+download+via+aria2+failed

**Comment by rashil2000** [comment]
Aria2 is not very reliable. If it fails, disable it, download your app and enable it again.
