### ISSUE TITLE
throttlestop@9.4.3: Download via aria2 failed

### ISSUE THREAD

**Issue by digrouz** [ScoopInstaller/Extras#7980]
Download failed!

**Comment by digrouz** [comment]
Output of the github action says "INFO: Download failed" it load the file from cache.

**Comment by digrouz** [comment]
shovel.

I've aria2c configured too. But i've tried with it disable too, it not working neither. Also using the URL within a Browser give 404, so I think there is really something changed at techpowerup.

**Comment by rashil2000** [comment]
> shovel but i don't think it's revelant here.

It is totally relevant. Use scoop. Shovel cannot download stuff from techpowerup.

**Comment by digrouz** [comment]
True, thanks for spotting it!
