### ISSUE TITLE
[Request] Add Rcc RPA Framework

### ISSUE THREAD

**Issue by liny01-nbsa** [ScoopInstaller/Extras#7986]
### Information

**Name:** rcc

**Description:** a set of tooling that allows you to create, manage, and distribute Python-based self-contained automation packages - or robots 🤖 as we call them.

**Homepage:** https://github.com/robocorp/rcc#installing-rcc-from-command-line

**Download link(s):** [URL(s)/link(s)] https://downloads.robocorp.com/rcc/releases/latest/windows64/rcc.exe

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

![image](https://user-images.githubusercontent.com/38985073/154513407-e1f32691-d5ad-44d0-b9e1-88b234930a2a.png)

as of 2/17/2022

**Comment by liny01-nbsa** [comment]
Hi, @rashil2000, do you have a good example I can use as reference?

**Comment by rashil2000** [comment]
Plenty of examples in /bucket folder. You can also check the Main bucket. And read the guide: https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md
