### ISSUE TITLE
[Bug] Scoop ignoring available Updates for qbittorrent

### ISSUE THREAD

**Issue by Skince** [ScoopInstaller/Extras#8010]
## Bug Report

**Package Name:** qbittorrent
When doing `scoop update qbittorent` it reports `qbittorrent: 4.3.9 (latest version)`  even though extra was updated to 4.4.1 : https://github.com/ScoopInstaller/Extras/commit/f61c83cf692c77f7cfe693121bbc17ee014e5c29

### Current Behaviour
scoop reporting everything as updated even though bucket has a newer update

### Expected Behaviour
scoop updating the package to available version

### Additional context/output
```
C:\Windows\System32>scoop update qbittorrent
qbittorrent: 4.3.9 (latest version)
C:\Windows\System32>scoop list
Installed apps:

  [...]
  qbittorrent 4.3.9 [extras]
  [...]
C:\Windows\System32>scoop status
Scoop is up to date.
C:\Windows\System32>scoop info qbittorrent
Name: qbittorrent
Description: Free and reliable P2P Bittorent client.
Version: 4.3.9
Website: https://www.qbittorrent.org/
License: GPL-2.0-only (https://github.com/qbittorrent/qBittorrent/blob/master/COPYING)
Manifest:
  C:\Users\user\scoop\buckets\extras\bucket\qbittorrent.json
Installed:
  C:\Users\user\scoop\apps\qbittorrent\4.3.9
Binaries:
  qbittorrent.exe

```

### System details

**Windows version:** 10

**OS architecture:**  64bit

**PowerShell version:** 
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1023
```
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-02-20T11:19:19.1321594+01:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master",
    "aria2-enabled":  false
}
```

**Comment by issaclin32** [comment]
I guess there is an git error when updating the bucket.
(error message will show up when you run `scoop update`)

You can try re-adding the bucket by:
```
scoop bucket rm extras
scoop bucket add extras
```
and see if this solves your problem.

**Comment by Skince** [comment]
Yes that fixed it, but `scoop update *` showed no error previously, does it need a flag?

**Comment by Sei-lus** [comment]
Just commenting because I had the same issue.

**Comment by niheaven** [comment]
Scoop doesn't record previous git sync error (core or bucket update), and this is left to user to resolve some unexpected git pull behavior. If you have some errors, ask here, and search for some solutions.

If you add many buckets, some of them may not be updated for a long time, and scoop cannot figure out the actual reason or if a bucket is uptoupdate.
