### ISSUE TITLE
[Request] Wireshark is available but Npcap is not

### ISSUE THREAD

**Issue by morgenman** [ScoopInstaller/Extras#8012]
### Information

**Name:** Npcap

**Description:** A tool that allows wireshark to capture packets on windows. 
**Homepage:** [https://npcap.com/](https://npcap.com/)

**Download link(s):** [https://npcap.com/dist/npcap-1.60.exe](https://npcap.com/dist/npcap-1.60.exe)

**Some indication of popularity/repute:** Hmm.. I mean, wireshark was popular enough to exist in this bucket, and you sort of need npcap for wireshark to work (for most cases)...

**Comment by rashil2000** [comment]
Npcap's license does not allow distribution through third party means, which includes Scoop.
