### ISSUE TITLE
[Request] Firefox

### ISSUE THREAD

**Issue by Sei-lus** [ScoopInstaller/Extras#8016]
Hello.

I have been having a issue with Firefox package for over a year now but thought it wasn't worth raising it. But lately the firefox package manager has added some persisting files so maybe it can be accomodated.

Currently I use this:
https://github.com/xiaoxiaoflood/firefox-scripts

It adds the possibility of some modding to firefox that is not otherwise possible. It is mostly installed in the user profile, but 2 files are installed into the core firefox installation path. Whenever firefox updates itself by its own means, it persist perfectly, but scoop updates just install a new firefox so I would have to re add those files everytime. I raised the concern to xiaoxiao too but wanted to see scoop perspective.

Xiao adds files to the main firefox path, but also to defaults... so for instance making defaults persist would be a part way solution.

Overall firefox in scoop behaves a bit weird since at the end of the day firefox auto updates so a work around (bandaid) solution for me was to just "hold" firefox in scoop forever.

Just a shout out to see if there is a proper way to work this out.

**Comment by rashil2000** [comment]
cc @HUMORCE

**Comment by Sei-lus** [comment]
I haven't tested the new changes Humorces did. But they seem solid, @rashil2000 can we close this when the pull request gets merged?
