### ISSUE TITLE
How to update vscodium-portable to vscodium?

### ISSUE THREAD

**Issue by wuya666** [ScoopInstaller/Extras#8039]
It seems the `vscodium-portable` app is removed from the bucket, and only `vscodium` app remains, so is there a way to update a vscodium-portable installation to vscodium without losing the configurations? Is there a migration doc or something, I tried to search around but it seems the vscodium-portable app is simply removed without any info on how to migrate to the vscodium app? Thanks.

**Comment by rashil2000** [comment]
- Uninstall vscodium-portable
- Rename ~/scoop/persist/vscodium-portable to ~/scoop/persist/vscodium
- Install vscodium
