### ISSUE TITLE
archwsl@22.2.10.0: hash check failed

### ISSUE THREAD

**Issue by radrow** [ScoopInstaller/Extras#8044]
#### Scoop Configuration

(default)

**Comment by radrow** [comment]
I did it on a clean scoop installation and yes, I retried with `scoop update` and cleared up the cache

**Comment by rashil2000** [comment]
Can you manually download and verify the hash?

**Comment by radrow** [comment]
Wtf. I already installed archwsl through their appx, and when I tried to reproduce the issue with scoop it suddenly worked. Nevermind then, sorry for the hassle.
