### ISSUE TITLE
[Request] IMO (note- MSI installer only)

### ISSUE THREAD

**Issue by SonaliBendre** [ScoopInstaller/Extras#8045]
### Information

**Name:** [name of new package]
IMO
**Description:** [clear and concise details of what it is]

**Homepage:** [a URL/link]
https://imo.im/
**Download link(s):** [URL(s)/link(s)]
imo free video calls and chat
**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
![image](https://user-images.githubusercontent.com/73757361/155697223-675d9fb4-5709-4514-a00c-f1c49d5e2f3b.png)
 More than 200M users

I have no idea about MSI Installers so can't make PR

**Comment by rashil2000** [comment]
You can search in the repo, there are plenty of examples which use MSI

**Comment by SonaliBendre** [comment]
https://github.com/Homebrew/formulae.brew.sh/blob/master/api/cask-source/imo.rb

**Comment by SonaliBendre** [comment]
> You can search in the repo, there are plenty of examples which use MSI

I saw some manifests and also check scoop repo what it does in case of MSI apps but maybe my brain too small to understand

**Comment by SonaliBendre** [comment]
https://github.com/ScoopInstaller/Extras/pull/8046
