### ISSUE TITLE
[ISSUE] With Mailspring not up and running after updating

### ISSUE THREAD

**Issue by Xelbayria** [ScoopInstaller/Extras#8068]
## Bug Report

**Package Name:** mailspring

### Current Behaviour
I updated Mailspring to the latest version and was going to run it to check my mails
The picture below will explain everything
![_map](https://user-images.githubusercontent.com/12866666/156321702-08050a48-1744-4ce6-80a1-5f2c41227c64.png)

I clicked "Okay" as you see in the picture but none was solved. I noticed that the installer it used was  Mailspring-1.10.0-full.nupkg
Mailspring has its own GitHub. Please let me know if there is a solution to fix this? 

### Expected Behaviour

I expected the app to be up and running without any problem.

### System details

**Windows version:** 10 PRO

**OS architecture:** 64bit

**PowerShell version:** 5      1      19041  1320

**Comment by Xelbayria** [comment]
> I'm not a user of this app, so I can't say much. Also the manifest just downloads the package, and does not do anything else.
> 
> You should report this on their GitHub repo.

I already reported an issue regarding this one on their Github. I'm just waiting to hear from here and there to see what's going on.

**Comment by Xelbayria** [comment]
I recommend that the version of Mailspring revert back to 1.9.2 in Scoop. Idk why 1.10.0 is not working. I manually add the 1.9.2 in the folder and it's working. I have been looking at the issues besides mine. I am the only one who is having an issue with this problem. There is a good chance that I'm the only one who uses Scoop to install Mailspring.

I ran a quick test on my laptop which never had the Mailspring and install the v1.10.0 via scoop. It has the same problem shown in the picture above.

**Comment by rashil2000** [comment]
Can you link the issue in their repo here?

**Comment by Xelbayria** [comment]
Here's the link to their repo: 
[Mailspring REPO](https://github.com/Foundry376/Mailspring)

Other links to their issue reporting: 
[Bugs](https://community.getmailspring.com/c/bugs)
[service Issues](https://community.getmailspring.com/c/service-issues)
[Sync Issue](https://community.getmailspring.com/c/sync)
[Packaging Issue](https://community.getmailspring.com/c/packaging)

Note: The issues in REPO are only discussions about objective and what need to be done between programmers, not people who reported bugs or whatever. The other links are where the real issues are being reported.

**Comment by rashil2000** [comment]
No no, I am talking about the issue you reported, whether on GitHub or on the forum.

**Comment by Xelbayria** [comment]
> No no, I am talking about the issue you reported, whether on GitHub or on the forum.

I apologize for not understanding what you are asking. Actually, I sent them an email to hear their opinion regarding Scoop and Mailspring. Why it's not working properly and what makes it different compared to the older version. Time will tell. 

btw, my issue in Github is deleted because it doesn't fit in there. I've learned the hard way. so yeah.

**Comment by rashil2000** [comment]
I tried installing Mailspring 1.10.0, both from Scoop and using their official installer. None of them work. This issue has been reported in their forum though, see https://community.getmailspring.com/t/v1-10-on-windows-better-sqlite3-node-is-not-a-valid-win32-application/4059 and https://community.getmailspring.com/t/database-error-and-unable-to-launch-app-after-installing-v1-10-0/4063

I will revert Mailspring to previous version for the time being.

**Comment by iainnicol** [comment]
Thank you for reverting the Mailspring manifest, due to v1.10.0 having the critical non-startup bug.

The good news is that v1.10.1 has been released, fixing the issue. Because you manually reverted, I'm not sure if you have to manually update to the latest?

**Comment by rashil2000** [comment]
Done
