### ISSUE TITLE
Can't find scoop installed java

### ISSUE THREAD

**Issue by christopinka-vp** [ScoopInstaller/Extras#8070]
## Bug Report

NetBeans

### Current Behaviour

Can't find scoop installed java with JAVA_HOME set in from git-bash with
export JRE_HOME=/c/Users/ChrisTopinka/scoop/apps/openjdk17/current/bin/java
and
export JAVA_HOME=/c/Users/ChrisTopinka/scoop/apps/openjdk17/current/bin/java

### Expected Behaviour

What's needed to find scoop installed java?

Windows  10

OS architecture: 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1320

**Additional software:** [(optional) e.g. ConEmu, Git]
$ scoop list
Installed apps:

  7zip 21.07 [main]
  azure-cli 2.32.0 [main]
  bitwarden 1.30.0 [extras]
  brave 1.34.80-80 [extras]
  coreutils 5.97.3 [main]
  dark 3.11.2 [main]
  docker 20.10.12 [main]
  dockstation 1.5.1 [theseason5_scoop-bucket]
  gawk 5.1.1 [main]
  git 2.35.1.windows.2 [main]
  go 1.17.6 [main]
  grep 3.7 [main]
  idea-ultimate 2021.3.2-213.6777.52 [extras]
  jq 1.6 [main]
  lessmsi 1.10.0 [main]
  maven 3.8.4 [main]
  netbeans 12.6 [extras]
  nodejs 17.5.0 [main]
  notepadplusplus 8.3.1 [extras]
  openjdk 17.0.2-8 [java]
  openjdk11 11.0.2-9 [java]
  openjdk17 17.0.2-8 [java]
  python 3.10.2 [main]
  stack 2.7.3 [main]
  tabby 1.0.170 [extras]
  terraform 1.1.4 [main]
  vim 8.2.2824 [main]
  vscode 1.64.2 [extras]
  which 2.20 [main]

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-03-02T08:19:59.2188847-06:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}

```

**Comment by rashil2000** [comment]
I think you need to set the value of netbeans_jdkhome in ~\scoop\apps\netbeans\current\etc\netbeans.conf
