### ISSUE TITLE
gcloud@375.0.0: Decompress error

### ISSUE THREAD

**Issue by tribina** [ScoopInstaller/Extras#8080]
Failed to extract files from C:\Users\ai00020\scoop\apps\gcloud\375.0.0\google-cloud-sdk-375.0.0-windows-x86_64-bundled-python.zip.
Log file:
  ~\scoop\apps\gcloud\375.0.0\7zip.log

❯ cat ~\scoop\apps\gcloud\375.0.0\7zip.log

7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

Scanning the drive for archives:
1 file, 146679700 bytes (140 MiB)

Extracting archive: C:\Users\ai00020\scoop\apps\gcloud\375.0.0\google-cloud-sdk-375.0.0-windows-x86_64-bundled-python.zip
--
Path = C:\Users\ai00020\scoop\apps\gcloud\375.0.0\google-cloud-sdk-375.0.0-windows-x86_64-bundled-python.zip
Type = zip
Physical Size = 146679700

Sub items Errors: 4

Archives with Errors: 1

Sub items Errors: 4

**Comment by rashil2000** [comment]
See https://github.com/ScoopInstaller/Scoop/issues/4647
