### ISSUE TITLE
[Request] nvui

### ISSUE THREAD

**Issue by xarthurx** [ScoopInstaller/Extras#8085]
### Information

  **Name:** nvui

**Description:** 
Another front-end for `neovim`. Fast and feature-rich.
I tested locally and it is much faster to load than the `goneovim` and `neovim-qt`.
Hope this could be added to `scoop extra` bucket.

**Homepage:** https://github.com/rohit-px2/nvui

**Download link(s):** https://github.com/rohit-px2/nvui/tags

**Some indication of popularity/repute:** github star: 1.5k
Very good and feature-rich nvim front-end, faster than `goneovim` and `neovim-qt`.

**Comment by rashil2000** [comment]
Please make a PR!
