### ISSUE TITLE
[Request] Firefox Developer Edition

### ISSUE THREAD

**Issue by maephisto666** [ScoopInstaller/Extras#8113]
Not really a formal request, sorry.

Firefox Developer Edition was part of the Extras bucket but it disappeared. Is there a specific reason? If not, I would like to reintroduce the manifest myself.

**Comment by rashil2000** [comment]
It is in Versions bucket. Main and Extras repos only contain stable releases.

**Comment by maephisto666** [comment]
Ok I will go to sleep ahahah 

Thank you for the help @rashil2000
