### ISSUE TITLE
Android Studio data folder is not persisted

### ISSUE THREAD

**Issue by Rafeqm** [ScoopInstaller/Extras#8116]
## Bug Report

**android-studio**

### Current Behaviour

Unlike **idea** and **pycharm** that root folders only contain _IDE_ and _profile_ (these folders are persisted), **android-studio** contains 5 folders and none of them is persisted.

### Expected Behaviour

Among the 5 folders, **_plugins_** folder should be persisted so any plugin data will not just sit in old version folder of **android-studio** after update

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2

#### Scoop Configuration

```json
{
  "lastupdate": "2022-03-08T13:18:06.8105284+07:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment]
Please make a PR for the fix

**Comment by Rafeqm** [comment]
Sorry I'm not familiar with tweaking this. Could you give me a reference so at least I can know which code does what?

**Comment by rashil2000** [comment]
You don't need to modify any code. Look for the term `persist` in the repo, there are plenty of examples. You just need to modify the json
