### ISSUE TITLE
sdl2, sdl2-*, libsndfiles: Install and uninstall scripts fail to (un)register `PKG_CONFIG_PATH` and `CMAKE_PREFIX_PATH` (script error)

### ISSUE THREAD

**Issue by HaSa1002** [ScoopInstaller/Extras#8118]
## Bug Report

**Package Name:** sdl2, sdl2-image, sdl2-mixer, sdl2-ttf, libsndfile

### Current Behaviour

The install and uninstall scripts don't register the PKG_CONFIG_PATH and CMAKE_PREFIX_PATH and instead fail to execute:
```powershell
$pcdir = $(current_dir $dir)\lib\pkgconfig
$cmdir = $(current_dir $dir)
```

It throws a command not found error because `current_dir` is not a command.

### Expected Behaviour

It should register both paths to the environment variables.

### Possible Solution

I replaced `$(current_dir $dir)` with `$dir` and it works just fine.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:**
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1320
```

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-03-08T13:12:33.0524517+01:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
This function was removed in https://github.com/ScoopInstaller/Scoop/pull/4722

/cc @niheaven
