### ISSUE TITLE
[Request] add scoop-sd

### ISSUE THREAD

**Issue by grisha765** [ScoopInstaller/Extras#8127]
### Information

**Name: scoop-sd** [name of new package]

**Description: This program to search for packages in the scoop. Powered by https://scoopsearch.github.io/ ** [clear and concise details of what it is]

**Homepage: https://github.com/grisha765/scoop-search-directory** [a URL/link]

**Download link(s): https://github.com/grisha765/scoop-search-directory/releases/download/scoop-ds_v0.2/scoop-sd.exe** [URL(s)/link(s)]

**Some indication of popularity/repute: GitHub stars 0** [GitHub stars/software reviews etc.]

**Comment by rashil2000** [comment]
License missing.


Can you also commnt about this in https://github.com/ScoopInstaller/Scoop/issues/4627? There are a lot of useful suggestions there.
