### ISSUE TITLE
`v2rayn` fail to start

### ISSUE THREAD

**Issue by sperjar** [ScoopInstaller/Extras#8141]
## Bug Report

**Package Name:** v2rayn

### Current Behaviour

This warning when v2rayn starts. Restarting didn't work.

```
Loading GUl configuration file is abnormal, please restart the application
加载GUI配置文件异常，请重启应用
```
![](https://i.bmp.ovh/imgs/2022/03/3e0d6862d20f7dcc.png)

### Expected Behaviour

start normally

### System details

**Windows version:** 11 (22000.556)

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** 

#### Scoop Configuration

```json
{
  "lastupdate": "2022-03-11T16:25:54.8481825+08:00",
  "proxy": "127.0.0.1:7890",
  "aria2-warning-enabled": false,
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "aria2-enabled": true,
  "aria2-enable": true,
  "aria2-split": 32,
  "aria2-max-connection-per-server": 16,
  "aria2-min-split-size": "1M"
}

```

**Comment by issaclin32** [comment]
The problem is caused by that **v2rayn** will crash when `guiNconfig.json` is empty.

Please clear old config file by `scoop uninstall v2rayn -p`, or delete `(SCOOP DIRECTORY)\persist\v2rayn\guiNconfig.json`.
