### ISSUE TITLE
Anydesk link doesn't work

### ISSUE THREAD

**Issue by Fefefo** [ScoopInstaller/Extras#8148]
Anydesk download doesn't work.

```
Installing 'anydesk' (7.0.6) [64bit]
Host sconosciuto. (download.anydesk.com:443)
URL https://download.anydesk.com/AnyDesk.exe is not valid
```

**Comment by rashil2000** [comment]
Working now

**Comment by Fefefo** [comment]
Still doesn't work for me

**Comment by rashil2000** [comment]
Probably geoblocked in your region?

**Comment by Fefefo** [comment]
No, it isn't, I'm from Italy

**Comment by rashil2000** [comment]
Does it work in web browser?

**Comment by Fefefo** [comment]
The website works,
https://download.anydesk.com/AnyDesk.exe doesn't

**Comment by Fefefo** [comment]
I tryed with a vps and anydesk has been correctly installed with scoop, but I don't know why, the website works without the vps too

**Comment by rashil2000** [comment]
I am able to install it without any VPN

![image](https://user-images.githubusercontent.com/46838874/158168201-d2a8b63b-32d9-4583-aafc-3cb2647370d8.png)

(Region: India)
