### ISSUE TITLE
[Request] Google-Assistant-Unofficial-Desktop-Client

### ISSUE THREAD

**Issue by Console32** [ScoopInstaller/Extras#8173]
## Package Request
https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client
### Information

**Name:** Google-Assistant-Unofficial-Desktop-Client

**Description:** Google Assistant for Desktop

**Homepage:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client

**Download link(s):** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases

**Some indication of popularity/repute:** 2.7k Github Stars

Can provide PR

**Comment by rashil2000** [comment]
Sure
