### ISSUE TITLE
[Request] par2cmdline

### ISSUE THREAD

**Issue by pessoalzy** [ScoopInstaller/Extras#8176]
### Information

**Name:**  par2cmdline

**Description:** par2cmdline is a program for creating and using PAR2 files to detect damage in data files and repair them if necessary. It can be used with any kind of file.

**Homepage:** https://github.com/Parchive/par2cmdline

**Download link(s):** https://github.com/Parchive/par2cmdline/releases/download/v0.8.1/par2cmdline-0.8.1-win-x64.zip

**Some indication of popularity/repute:** GitHub stars 479

**Comment by rashil2000** [comment]
Is this a CLI application? In that case the Main bucket is a better place for this.

**Comment by pessoalzy** [comment]
Yes, it's a CLI application. But I'm not sure whether it meets the [first criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket), either "reasonably well-known and widely used" or "developer tool".

If it meets the criteria, I'll close this issue and open one in Main bucket.

**Comment by rashil2000** [comment]
Yes, please open it there
