### ISSUE TITLE
diskgenius English edition is different from Chinese edition

### ISSUE THREAD

**Issue by pessoalzy** [ScoopInstaller/Extras#8185]
## Bug Report

**Related Package Name:** diskgenius

The URL of diskgenius was changed from from CN to EN in #6228. However, The edition with English and the edition with Chinese use different licenses, which means professional license of Chinese edition (for example) won't activate the pro features of English edition.

Based on current DiskGenius manifest, I create [manifest of Chinese edition](https://gist.github.com/pessoalzy/338685169163e8ae6ea2f30cdf9be4be) by change URLs and hash. Considering two editions use the same shim and it's unnecessary to rename either, I add a note "This is in conflict with DiskGenius English edition for overwriting shim.".

I hope we can add both editions. But I'm not sure whether `diskgenius_zh` belongs to Extras bucket or Versions bucket.

**Comment by niheaven** [comment]
Put it on https://github.com/chawyehsu/dorado for this Chinese only manifest?

**Comment by rashil2000** [comment]
Official buckets hold only English manifests. As @niheaven said, you can try @chawyehsu's (one of our maintainer's) bucket.
