### ISSUE TITLE
[Request] Python 3.11

### ISSUE THREAD

**Issue by YSCohen** [ScoopInstaller/Extras#8188]
### Information

**Name:** Python pre-release

**Description:** Alpha release of the newest Python. Even when Python 3.11 goes stable, we should always keep this scoop app as the newest Python pre-release.

**Homepage:** [Python docs](https://docs.python.org/3.11/)

**Download link(s):** [Windows installer](https://www.python.org/ftp/python/3.11.0/python-3.11.0a6-amd64.exe)

**Some indication of popularity/repute:** [Python's GH page](https://github.com/python/cpython) has > 43k stars

**Comment by rasa** [comment]
Try:
```
scoop bucket add versions
scoop update
scoop install python-alpha
```
to install 3.11.0a6 per https://github.com/ScoopInstaller/Versions/blob/master/bucket/python-alpha.json
