### ISSUE TITLE
ani-cli installs mpv even if mpv-git is installed

### ISSUE THREAD

**Issue by x6r** [ScoopInstaller/Extras#8194]
## Bug Report

**Package Name:** ani-cli

### Current Behaviour

installing ani-cli installs mpv but i have mpv-git which is already configured and is available as mpv in PATH

### Expected Behaviour

mpv-git gets accepted as a dependency as it is almost identical to mpv

### Additional context/output

[line 10 in ani-cli.json having mpv as a dependency](https://github.com/ScoopInstaller/Extras/blob/master/bucket/ani-cli.json#L10)

### Possible Solution

i'm not knowledgeable on scoop packages so i'm not entirely sure if that is possible but basically checking if either mpv or mpv-git and depending on which ever is already available

if that is not possible maybe it can not have mpv as a dependency at all and add a simple note to install mpv (or mpv-git)

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.2

**Additional software:**

#### Scoop Configuration

```json
{
  "lastupdate": "2022-03-23T06:52:51.5882149+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": false
}
```

**Comment by rashil2000** [comment]
Please make a PR to make mpv a `suggest` instead of `depends`
