### ISSUE TITLE
[Request] YesPlayMusic

### ISSUE THREAD

**Issue by StudentWeis** [ScoopInstaller/Extras#8202]
### Information

**Name:** YesPlayMusic

**Description:** High appearance level of the third party NetEase cloud player.

**Homepage:** https://github.com/qier222/YesPlayMusic

**Download link(s):** https://github.com/qier222/YesPlayMusic/releases/download/v0.4.3/YesPlayMusic-0.4.3.exe

**Some indication of popularity/repute:** GitHub stars 15.7k

**Comment by rashil2000** [comment]
Please make a PR!
