### ISSUE TITLE
missing comma in bucket/aimp.json

### ISSUE THREAD

**Issue by lexybarton** [ScoopInstaller/Extras#8216]
Hi, There is an error while searching scoop.

`"ConvertFrom-Json: Conversion from JSON failed with error: After parsing a value an unexpected character was encountered: ". Path 'persist', line 37, position 4."  `

I tracked it to ***missing comma in bucket/aimp.json*** which was commited by @issaclin32 couple of hours ago.

This is like my first  ever bug report, I hope it's ok. Have a nice day :-)

**Comment by issaclin32** [comment]
Sorry. I was actually drunk when I did that commit. I should never do that again.

**Comment by rashil2000** [comment]
Hey man, no worries!
