### ISSUE TITLE
gpu-z@2.45.0: Download via aria2 failed

### ISSUE THREAD

**Issue by SettingDust** [ScoopInstaller/Extras#8225]
Download failed! (Error 3) Resource was not found

http://us2-dl.techpowerup.com/files/GPU-Z.2.45.0.exe#/GPU-Z.exe
![图片](https://user-images.githubusercontent.com/19922286/160583072-87af2d82-3ba6-4d9f-9cec-6e8d691585bd.png)

The url I click on site https://us2-dl.techpowerup.com/files/MwWA2GKCH-zgbXJfIFHjvQ/1648590071/GPU-Z.2.45.0.exe

**Comment by rashil2000** [comment]
Paste content of ~/.config/scoop/config.json

**Comment by SettingDust** [comment]
```
{
  "lastUpdate": "258|2022-03-29 17:37:59",
  "SCOOP_REPO": "https://github.com/Ash258/Scoop-Core",
  "SCOOP_BRANCH": "main",
  "proxy": "127.0.0.1:7890"
}
```

**Comment by rashil2000** [comment]
You are using a fork of Scoop.
