### ISSUE TITLE
"everything" persist error

### ISSUE THREAD

**Issue by Befod** [ScoopInstaller/Extras#8233]
## Bug Report

**Package Name:** [everything]

### Current Behaviour

"~\Scoop\persist\everything\Bookmarks.csv"

"~\Scoop\persist\everything\debug.log\"

"~\Scoop\persist\everything\Errorlog.txt\"

"~\Scoop\persist\everything\Filters.csv\"

"~\Scoop\persist\everything\HTTP Server\"

"~\Scoop\persist\everything\Run History.csv\"

"~\Scoop\persist\everything\Search History.csv\"

"~\Scoop\persist\everything\Bookmarks.csv\"

Bookmarks.csv,debug.log,Errorlog.txt,Filters.csv,HTTP Server,Run History.csv and Search History.csv are folders,but not files.

**Comment by rashil2000** [comment]
Except the Bookmarks.csv file, none of the mentioned files are persisted in the manifest
