### ISSUE TITLE
invalid JSON file: win11dragdroptaskbarfix.json

### ISSUE THREAD

**Issue by snowman** [ScoopInstaller/Extras#8240]
## Bug Report

**Package Name:** `win11dragdroptaskbarfix`

### Current Behaviour

The JSON file has un-closed quotes in `pre_install` field.

### Additional context/output

https://github.com/ScoopInstaller/Extras/blob/a0a33b157c22582cd1ecc067e6cefea5396bb1df/bucket/win11dragdroptaskbarfix.json#L12-L20

**Comment by rashil2000** [comment]
Please make a PR for the fix
