### ISSUE TITLE
qutebrowser: Persisting `config` directory is wrong

### ISSUE THREAD

**Issue by The-Compiler** [ScoopInstaller/Extras#8260]
## Bug Report

**Package Name:** qutebrowser

### Current Behaviour

Due to:

https://github.com/ScoopInstaller/Extras/blob/477315eec23e0b79ee79cf5b463d5f9dd89e1582/bucket/qutebrowser.json#L25

scoop persists the `config` directory in qutebrowser's install directory, leading to using a newer qutebrowser with an older [definition of available options](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/config/configdata.yml) (`config/configdata.yml`). This leads to qutebrowser not starting after the upgrade from v2.4.0 to v2.5.0: https://github.com/qutebrowser/qutebrowser/issues/7099

### Expected Behaviour

scoop should not persist any part of the qutebrowser installation. The user config is located in `%APPDATA%\qutebrowser` and not part of the installation.

### Additional context/output

cc @test210820 who reported this in qutebrowser, and @r15ch13 @yigitemres who originally added this in #783.

### Possible Solution

Remove `"persist": "config",` I'm assuming. Not sure what should be done to fix existing broken installations.

### System details / Scoop Configuration

N/A (I don't use scoop, I'm the qutebrowser maintainer)

**Comment by rashil2000** [comment]
Thanks for the detailed report. I have removed the persist https://github.com/ScoopInstaller/Extras/commit/2fcc70d7b70a7cbd691680b3c827d91286fd61b5 

Users who are facing problems should run 
```
scoop uninstall qutebrowser 
scoop update
scoop install qutebrowser 
```
