### ISSUE TITLE
gpu-z@2.45.0: Download failed

### ISSUE THREAD

**Issue by atraholt** [ScoopInstaller/Extras#8267]
The remote server returned an error: (404) Not Found

**Comment by atraholt** [comment]
does it matter? the URL in gpu-z.json is a 404 for me regardless of what I use to fetch it.

**Comment by rashil2000** [comment]
> does it matter?

Yes

**Comment by atraholt** [comment]
that was a rhetoric question, the URL is wrong.

**Comment by rashil2000** [comment]
You need to answer the question

**Comment by atraholt** [comment]
main on  master
❯ git remote -v
origin  https://github.com/ScoopInstaller/Main (fetch)
origin  https://github.com/ScoopInstaller/Main (push)

**Comment by atraholt** [comment]
oh I guess this is more interesting to you;
Base on  main
❯ git remote -v
origin  https://github.com/shovel-org/Base (fetch)
origin  https://github.com/shovel-org/Base (push)

**Comment by rashil2000** [comment]
You are using a fork of scoop. gpu-z will not download using that.
