### ISSUE TITLE
irfanview@4.60: download via aria2 failed

### ISSUE THREAD

**Issue by kokomugi** [ScoopInstaller/Extras#8279]
#### Scoop Configuration

```json
//# Your configuration here
```

ERROR Download failed! (Error 1) An unknown error occurredERROR https://www.irfanview.info/files/iview460_x64.zip
    referer=https://www.irfanview.info/files/
    dir=C:\Users\username\scoop\cache
    out=irfanview#4.60#https_www.irfanview.info_files_iview460_x64.zip
https://www.irfanview.info/files/iview460_plugins_x64.zip
    referer=https://www.irfanview.info/files/
    dir=C:\Users\username\scoop\cache
    out=irfanview#4.60#https_www.irfanview.info_files_iview460_plugins_x64.zip

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/162314658-76bef8f5-cc1a-422d-9830-8d01f152accc.png)
