### ISSUE TITLE
windowsspyblocker@4.38.0: download via aria2 failed

### ISSUE THREAD

**Issue by XINNLI** [ScoopInstaller/Extras#8280]
#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by XINNLI** [comment]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://github.com/crazy-max/WindowsSpyBlocker/releases/download/4.38.0/WindowsSpyBlocker.exe
    referer=https://github.com/crazy-max/WindowsSpyBlocker/releases/download/4.38.0/
    dir=D:\Program Files\Scoop\cache
    out=windowsspyblocker#4.38.0#https_github.com_crazy-max_WindowsSpyBlocker_releases_download_4.38.0_WindowsSpyBlocker.exe

ERROR & 'D:\Program Files\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Program Files\Scoop\cache\windowsspyblocker.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=15660 --continue --summary-interval=0 --auto-save-interval=1

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/162350489-ef606594-7675-455e-88fe-03d7e9375f42.png)
