### ISSUE TITLE
Please update vscode and vscodium to latest version currently 1.66.1

### ISSUE THREAD

**Issue by rahulmr** [ScoopInstaller/Extras#8293]
vscode and vscodium to be updated to latest version
![image](https://user-images.githubusercontent.com/10260232/162643233-08755123-8708-4862-8cbc-64f267be21e0.png)

**Comment by rashil2000** [comment]
Both of them are already at 1.66.1

https://github.com/ScoopInstaller/Extras/blob/master/bucket/vscode.json
https://github.com/ScoopInstaller/Extras/blob/master/bucket/vscodium.json

**Comment by rahulmr** [comment]
@rashil2000 Thanks it seems I had issue with local installation `scoop status *` not showing updates for `vscode` and `vscodium` , had to remove the bucket and add it again using below commands.
```
scoop bucket rm extras
scoop bucket add extras
scoop status *
```
