### ISSUE TITLE
[Request]  Screen2Gif

### ISSUE THREAD

**Issue by Console32** [ScoopInstaller/Extras#8297]
## Package Request
https://github.com/NickeManarin/ScreenToGif

### Information

**Name:** screen2gif

**Description:** Capture screen and convert to gif 

**Homepage:** 
https://www.screentogif.com/
https://github.com/NickeManarin/ScreenToGif

**Download link(s):** https://github.com/NickeManarin/ScreenToGif/releases

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.] 17k Github Stars

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/blob/master/bucket/screentogif.json

**Comment by Console32** [comment]
Ah, the product name does not have a 2 in it, thanks.

**Comment by powerAn2020** [comment]
@Console32 The software update url  has been updated, please correct it.
