### ISSUE TITLE
emacs@28.1: hash check failed

### ISSUE THREAD

**Issue by cmssato19** [ScoopInstaller/Extras#8300]
#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by cmssato19** [comment]
I reset the scoop but could not install emacs.

`
PS C:\WINDOWS\system32> scoop cache rm emacs
Deleted: 0 files,  B
PS C:\WINDOWS\system32> scoop uninstall emacs
ERROR 'emacs' isn't installed correctly.
Removing older version (28.1).
'emacs' was uninstalled.
PS C:\WINDOWS\system32> scoop install emacs
WARN  Purging previous failed installation of emacs.
ERROR 'emacs' isn't installed correctly.
Removing older version (28.1).
'emacs' was uninstalled.
Installing 'emacs' (28.1) [64bit]
emacs-28.1.zip (86.3 MB) [====================================>                                                             ]  38%
Checking hash of emacs-28.1.zip ... ERROR Hash check failed!
App:         extras/emacs
URL:         https://ftpmirror.gnu.org/gnu/emacs/windows/emacs-28/emacs-28.1.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    b7ab71fef1d176c7ba76b1438afbacad4dadced129835c6dbcc23eb9f98a3fed
Actual:      7ffd4e0085ea8f7d46212d96d1bdc8f49825ae8ea945fb5a3e707a8d64aec5eb

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=emacs%4028.1%3a+hash+check+failed
`

**Comment by rashil2000** [comment]
The expected hash is correct: https://www.online-convert.com/result#j=6b8ace9e-c14f-45d0-8f59-9a8e49a23cd0

**Comment by rashil2000** [comment]
Your download is not happening correctly. You need to ensure a stable internet connection or maybe try again in some time.

**Comment by cmssato19** [comment]
Thank you very much.
I was able to complete the installation.
