### ISSUE TITLE
networkminer@2.7.3: Hash check failed

### ISSUE THREAD

**Issue by gema-arta** [ScoopInstaller/Extras#8302]
Hash check failed!
App:         extras/networkminer
URL:         https://www.netresec.com/?download=NetworkMiner#/dl.zip
First bytes: 80 75 3 4 20 0 0 0
Expected:    f7f095aa0210af73e02f7dbb4d8ccc43b96516147b9a731757dd3f0e79575e8c
Actual:      cf477b651c3bcc70d6f5d50f9bdcb6d8cf2dd85b7018109ff474b9df3c7a0f7e

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/commit/6eaf32aade6bebbf985d59c6a079940a708a39e7
