### ISSUE TITLE
Discord does not work with Windows Focus Assist when installing through Scoop.

### ISSUE THREAD

**Issue by lderkzen** [ScoopInstaller/Extras#8317]
## Bug Report

**Package Name:** discord

### Current Behaviour

Installing Discord through scoop causes issues with Windows' Focus Assist. 
- It is not possible to set Discord as a priority app within Focus Assist, as it is not an option. 
- Also, notifications will appear under the header `com.squirrel.Discord.Discord` instead of `Discord`. 

I'm unclear if whether or not this is the cause but, when Discord is installed through regular means a folder named **"Discord"** is created within **"%LocalAppData%"**. When installed through scoop, this folder is not created.
It may also be caused by some registry keys not being set.

### Expected Behaviour

- When installing Discord through Scoop, it should be possible to assign it a priority within Windows Focus Assist.
- Notifications within Focus Assist should properly show "Discord" as origin instead of "com.squirrel.Discord.Discord".

### Additional context/output

It may help knowing I'm running an almost freshly installed Windows 10 OS on completely cleaned drives. External causes are unlikely.

I'd be happy to add additional information as requested.

### System details

**Windows version:** 10 Home 21H2 Build 19044.1645

**OS architecture:** 64bit

**PowerShell version:**
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1645
```

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-04-14T13:38:13.1157201+02:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
I've never used Focus Assist, but does it not allow using user-provided app paths?

Regarding notifications, we extract the Squirrel package instead of running the Squirrel installer, so I'm afraid that display name cannot be changed.

**Comment by lderkzen** [comment]
@rashil2000 

I'm unsure on whether that is or isn't the reason and Googling it does not really give me more insight.
My assumption is that something within the `%LocalAppData%` "Discord" folder, which is only created using the regular installer, is the cause.

Either way, neither is a large issue, so if the cause is not already know nor abundantly clear, it may not be worth the time. I definitely don't plan to do research into the inner workings of Windows Focus Assist either. I've made do with just using the installer instead. Just passing my findings along as potential bug and happy to supply additional information if needed.

**Comment by rashil2000** [comment]
Scoop's Discord actually has a bunch of other problems - https://github.com/ScoopInstaller/Extras/issues/8051 and https://github.com/ScoopInstaller/Extras/pull/8154 so even I'd personally recommend using its own installer for now.
