### ISSUE TITLE
tern-subtitle-file-translator : download url error

### ISSUE THREAD

**Issue by GregAMO** [ScoopInstaller/Extras#8333]
## Bug Report

**Package Name:** [tern-subtitle-file-translator]

### Current Behaviour
"homepade"  "version" "url" error

### Expected Behaviour

"homepade"  "version" "url" update

### Additional context/output

"version": "2.2.0"
"homepage": "https://tern.1c7.me",
"url": "https://github.com/1c7/Translate-Subtitle-File/releases/download/2.2.0/Tern_Windows_2.2.0.zip"

### Possible Solution
"version": "4.1.0",
"homepage": "https://github.com/1c7/Translate-Subtitle-File",
"url": "https://github.com/1c7/Translate-Subtitle-File/releases/download/4.1.0/Tern_Windows_4.1.0.zip"

### System details

**Windows version: [10]

**OS architecture:** [64bit]

**Comment by rashil2000** [comment]
Hi, please make a PR for the fix!
