### ISSUE TITLE
tabby@1.0.175: download via aria2 failed

### ISSUE THREAD

**Issue by themrhead** [ScoopInstaller/Extras#8339]
Installing 'tabby' (1.0.175) [64bit]
Starting download with aria2 ...
Download: 04/19 10:57:28 [ERROR] CUID#8 - Download aborted. URI=https://github.com/Eugeny/tabby/releases/download/v1.0.1Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://github.com/Eugeny/tabby/releases/download/v1.0.175Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 35d440|ERR |       0B/s|C:/Tools/cache/tabby#1.0.175#https_github.com_Eugeny_tabby_releases_download_v1.0.175_tabby-1.0.175-setup.exe_dl.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://github.com/Eugeny/tabby/releases/download/v1.0.175/tabby-1.0.175-setup.exe#/dl.7z
    referer=https://github.com/Eugeny/tabby/releases/download/v1.0.175/tabby-1.0.175-setup.exe#/
    dir=C:\Tools\cache
    out=tabby#1.0.175#https_github.com_Eugeny_tabby_releases_download_v1.0.175_tabby-1.0.175-setup.exe_dl.7z

ERROR & 'C:\Tools\apps\aria2\current\aria2c.exe' --input-file='C:\Tools\cache\tabby.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=10300 --continue --summary-interval=0 --auto-save-interval=1

#### Scoop Configuration

```json
{
  "lastupdate": "2022-04-19T09:51:30.1514939-03:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by DoveBoy** [comment]
https://github.com/ScoopInstaller/Extras/pull/8337

**Comment by DoveBoy** [comment]
https://github.com/ScoopInstaller/Extras/pull/8349
