### ISSUE TITLE
tabby@1.0.176: download via aria2 failed

### ISSUE THREAD

**Issue by kennisyoung** [ScoopInstaller/Extras#8346]
ERROR https://github.com/Eugeny/tabby/releases/download/v1.0.176/tabby-1.0.176-setup.exe#/dl.7z
    referer=https://github.com/Eugeny/tabby/releases/download/v1.0.176/tabby-1.0.176-setup.exe#/
    dir=C:\MyApps\Scoop\\cache
    out=tabby#1.0.176#https_github.com_Eugeny_tabby_releases_download_v1.0.176_tabby-1.0.176-setup.exe_dl.7z
```

true url：https://github.com/Eugeny/tabby/releases/download/v1.0.176/tabby-1.0.176-setup-x64.exe

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/issues/8339
