### ISSUE TITLE
Tabby binary name changed from version 174 to 175, current is 176. Gotta add a -x64

### ISSUE THREAD

**Issue by christophacham** [ScoopInstaller/Extras#8352]
## Bug Report

**Package Name:** [tabby]

### Current Behaviour

Your download link is broken, the file you reference does not exist. The filename changed from e.g. tabby-1.0.174-setup.exe to tabby-1.0.176-setup-x64.exe, the new naming includes a -x64.
### Expected Behaviour

The download link is not broken, and scoop can download and install the software. 

### Possible Solution

add an -x64 to correct it.

### System details

**Windows version:** [11]

**OS architecture:** [64bit]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/pull/8349
