### ISSUE TITLE
gcc-arm-none-eabi: arm-none-eabi-gdb requires Python 2.7

### ISSUE THREAD

**Issue by Gigahawk** [ScoopInstaller/Extras#8361]
## Bug Report

**Package Name:** gcc-arm-none-eabi

### Current Behaviour

Running `arm-none-eabi-gdb` from `cmd` produces the following error:
![image](https://user-images.githubusercontent.com/10356230/164426845-a65b882c-8e49-4e09-96f6-8daa667da4d5.png)

Infuriatingly, doing the same thing in `powershell` will just fail silently:
![image](https://user-images.githubusercontent.com/10356230/164426936-f4d833f6-2e4b-4a42-b895-d0a1110da490.png)

### Expected Behaviour

gdb should start:
![image](https://user-images.githubusercontent.com/10356230/164427234-950db3fd-46c8-4e8f-a385-8a14748141b4.png)

### Possible Solution

Installing a 32-bit Python 2.7 fixes the issue: https://www.python.org/ftp/python/2.7.18/python-2.7.18.msi

Using `python27` from the versions bucket also works if you specify 32bit:
```
scoop bucket add versions
scoop install python27 -a 32bit
```

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1645

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-04-20T22:33:21.7374718-07:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment]
Can you add a suggest for versions/python27 in the manifest?

Does it work with 64bit python2.7? If not, the 32bit should be mentioned in the notes section.

**Comment by Gigahawk** [comment]
Unfortunately it doesn't work with 64bit python27:
![image](https://user-images.githubusercontent.com/10356230/164561680-18651e93-77f3-435d-ab45-5bc212ff7e35.png)

Powershell again fails silently.
