### ISSUE TITLE
Discord javascript error on launch

### ISSUE THREAD

**Issue by maphew** [ScoopInstaller/Extras#8370]
## Bug Report

**Package Name:** Discord

### Current Behaviour

When launched there are two popup error windows. When dismissed there is nothing, back to normal Windows. This is fresh install of Discord. The error happens every time, no obvservable changes.

> A JavaScript error occurred in the main process
> 
> Uncaught exception:
>  Error: [object Object]
>     at Updater._handleSyncResponse (C:\ProgramData\scoop\apps\discord\1.0.9004-11\app\app-1.0.9004\resources\app\common\updater.js:170:13)
>     at Updater.setPinnedManifestSync (C:\ProgramData\scoop\apps\discord\1.0.9004-11\app\app-1.0.9004\resources\app\common\updater.js:325:17)
>     at Object.update (C:\ProgramData\scoop\apps\discord\1.0.9004-11\app\app-1.0.9004\resources\app\app_bootstrap\appUpdater.js:58:15)
>     at startUpdate (C:\ProgramData\scoop\apps\discord\1.0.9004-11\app\app-1.0.9004\resources\app\app_bootstrap\bootstrap.js:167:14)
>     at App.startApp (C:\ProgramData\scoop\apps\discord\1.0.9004-11\app\app-1.0.9004\resources\app\app_bootstrap\bootstrap.js:202:3)
>     at Object.onceWrapper (events.js:422:26)
>     at App.emit (events.js:315:20)
>     at App.EventEmitter.emit (domain.js:467:12)

Followed by:

> Discord portable
>
> Command failed

### Expected Behaviour

Discord open and running.

### Additional context/output

```
C:\> scoop install -g discord
...snip...
Installing 'discord' (1.0.9004-11) [64bit]
discord-portable-win32-1.0.9004-11.7z (56.5 MB) [=======================================================] 100%
Checking hash of discord-portable-win32-1.0.9004-11.7z ... ok.
Extracting discord-portable-win32-1.0.9004-11.7z ... done.
Linking C:\ProgramData\scoop\apps\discord\current => C:\ProgramData\scoop\apps\discord\1.0.9004-11
Creating shortcut for Discord (discord-portable.exe)
Persisting data
Persisting log
'discord' (1.0.9004-11) was installed successfully!
```

### System details

**Windows version:** 10

**OS architecture:** 64

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [scoop-installed.txt](https://github.com/ScoopInstaller/Extras/files/8542455/scoop-installed.txt)

#### Scoop Configuration
```
» scoop config

lastupdate                        SCOOP_REPO                           SCOOP_BRANCH
----------                        ----------                           ------------
2022-04-22T09:03:06.8741782-07:00 https://github.com/lukesampson/scoop master
```

**Comment by MathewBlock** [comment]
I just did a fresh install of Discord, however I have been unable to reproduce the error you are seeing.
It looks like something going wrong with the pinned manifest but I'm certainly no expert.

Could you try downloading the zip version from here: https://portapps.io/app/discord-portable
See if that version runs okay when unpacked?

**Comment by maphew** [comment]
Yes the 7z from that link runs without issue (discord-portable-win32-1.0.9004-11).

On launch it immediately downloaded 4 updates without any of my intervention. I see the beginning of the error from the scoop package begins _"Error: [object Object] at Updater._handleSyncResponse"_, perhaps related?

**Comment by MathewBlock** [comment]
Perhaps try uninstalling Discord with `scoop uninstall discord -p` to remove the persistent data.

We mostly just unpack that zip you tried, the only difference is we redirect the data and log directories to scoops persist directory, so if there is something wrong in there it won't be touched by a normal uninstall.

**Comment by maphew** [comment]
Thanks for suggestion, but that didn't change anything. The problem seems to be the global install. If I install in user profile it works fine.

**Comment by rashil2000** [comment]
Perhaps all applications from Portapps are not meant to be used as Admin?

**Comment by MathewBlock** [comment]
I can reproduce your issue by installing Discord globally.

Usually Discord is hardcoded to write module updates and settings to your user profile.
However with the portable version those folders are redirected locally.

The app seems to have trouble reading / writing to that location when it's not run as admin.
It doesn't seem to matter whether I redirect the data to the persist dir or not, without admin rights it gets errors.

I suspect @rashil2000 might be right, although I haven't tested any other Portapps.

**Comment by rashil2000** [comment]
Portable apps are usually made so that people can install and run them anywhere even if they don't have admin access, that must be the reason why a global install throws errors when the app is not launched as admin. 

I'm closing this as the workaround is simple: install discord as a non-global app :)
