### ISSUE TITLE
[Request] Is it possible to add GNU Screen?

### ISSUE THREAD

**Issue by johan718** [ScoopInstaller/Extras#8374]
## Package Request
Please add GNU Screen.

### Information

**Name:** [name of new package]
Screen

**Description:** [clear and concise details of what it is]
Screen allows one to connect to serial ports among other features. It would be a nice addition as right now the only other option that I know of is Putty which is not necessarily a command-line tool.

**Homepage:** [a URL/link]
http://www.gnu.org/software/screen/

**Download link(s):** [URL(s)/link(s)]
https://git.savannah.gnu.org/cgit/screen.git

https://github.com/shyouhei/screen [Mirror]

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
Screen has 13 contributors on Github and the latest version, 4.9.0 was released 3 months ago.

**Comment by rasa** [comment]
Where is a non-Cygwin based Windows binary. I've looked at https://packages.msys2.org/search?q=Screen and don't see it anywhere. Have you tried running it in WSL?

**Comment by johan718** [comment]
@rasa No, I haven't tried looking for it on WSL yet. I was hoping I wouldn't have to, honestly. Should I have checked?

**Comment by rashil2000** [comment]
Scoop is just a package manager, which needs a source for the binaries to install.

GNU Screen works only on Cygwin. Even MSYS2 is incompatible with Screen. You should use Cygwin and its setup program (or alternatively, [apt-cyg](https://github.com/kou1okada/apt-cyg)) to install Screen.
