### ISSUE TITLE
package update-libreoffice 7.3.1 -> 7.3.2

### ISSUE THREAD

**Issue by AdmnJ** [ScoopInstaller/Extras#8380]
## Bug Report

**Package Name:** libreoffice

### Current Behaviour
Current version in bucket is 7.3.1.

### Expected Behaviour
Current version on upstream mirror is 7.3.2.
https://www.libreoffice.org/download/download/
https://download.documentfoundation.org/libreoffice/stable/7.3.2/win/x86_64/LibreOffice_7.3.2_Win_x64.msi.mirrorlist 

### Possible Solution

Update package in bucket to 7.3.2

**Comment by AdmnJ** [comment]
@StudentWeis Sorry if this is not the preferred place to request this.

**Comment by rashil2000** [comment]
It will get updated automatically once this page is updated: http://download.documentfoundation.org/libreoffice/portable/

**Comment by AdmnJ** [comment]
> It will get updated automatically once this page is updated: http://download.documentfoundation.org/libreoffice/portable/

Yeah, I figured that one out while I was writing a manifest for another app, sorry about the post.
