### ISSUE TITLE
openvpn failed to install 

### ISSUE THREAD

**Issue by sasasqt** [ScoopInstaller/Extras#8397]
## Bug Report

**openvpn** 

### Current Behaviour

failed to install it with admin privilege 
DEBUG:  760+         if( >>>> test-path "$dir\$target" -pathType leaf) {
DEBUG:  760+         if( >>>> test-path "$dir\$target" -pathType leaf) {
DEBUG:  759+     foreach( >>>> $dir in $path.split(';')) {
DEBUG:     ! SET $dir = ''.
DEBUG:  760+         if( >>>> test-path "$dir\$target" -pathType leaf) {
DEBUG:  760+         if( >>>> test-path "$dir\$target" -pathType leaf) {
DEBUG:  759+     foreach( >>>> $dir in $path.split(';')) {
DEBUG:     ! SET $foreach = ''.
DEBUG:  764+  >>>> }
DEBUG:     ! SET $bin = ''.
DEBUG:  887+         if( >>>> !$bin) { abort "Can't shim '$target': File doesn't exist."}
DEBUG:  887+         if(!$bin) {  >>>> abort "Can't shim '$target': File doesn't exist."}
DEBUG:  143+ function abort($msg, [int] $exit_code=1)  >>>> { write-host $msg -f red; exit $exit_code }
DEBUG:     ! CALL function 'abort'  (defined in file 'C:\Users\PC\scoop\apps\scoop\current\lib\core.ps1')
DEBUG:  143+ function abort($msg, [int] $exit_code=1) {  >>>> write-host $msg -f red; exit $exit_code }
Can't shim 'bin\openvpn.exe': File doesn't exist.
DEBUG:  143+ function abort($msg, [int] $exit_code=1) { write-host $msg -f red;  >>>> exit $exit_code }
DEBUG:   37+  >>>> }
DEBUG:    4+  >>>> exit $LASTEXITCODE

--------

Installing 'openvpn' (2.5.5) [64bit]
Loading OpenVPN-2.5.5-I602-amd64.msi from cache
Checking hash of OpenVPN-2.5.5-I602-amd64.msi ... ok.
Running pre-install script...
Linking ~\scoop\apps\openvpn\current => ~\scoop\apps\openvpn\2.5.5
Creating shim for 'openvpn'.
**Can't shim 'bin\openvpn.exe': File doesn't exist.**

### Expected Behaviour
installs correctly

### Additional context/output
'scoop update' was executed before executing 'scoop update *'
'scoop install openvpn' creates 2 folders. only folder "2.4.10" contains the actual openvpn files, but the "current" folder is linked to folder "2.5.5", which only contains one file: "setup.msi_".
"openvpn#2.5.5#https_swupdate.openvpn.org_community_releases_OpenVPN-2.5.5-I602-amd64.msi_setup.msi_" has been downloaded in cache folder.

 Directory of C:\*\scoop\apps\openvpn

04/27/2022  06:42 AM    <DIR>          .
04/27/2022  06:42 AM    <DIR>          ..
04/27/2022  06:42 AM    <DIR>          2.4.10
04/27/2022  06:50 AM    <DIR>          2.5.5
04/27/2022  06:42 AM    <JUNCTION>     current [\??\C:\*\scoop\apps\openvpn\2.5.5]

-------

 Directory of C:\*\scoop\apps\openvpn\2.4.10

04/27/2022  06:42 AM    <DIR>          .
04/27/2022  06:42 AM    <DIR>          ..
04/27/2022  06:42 AM    <DIR>          bin
04/27/2022  06:42 AM    <DIR>          config
04/27/2022  06:42 AM    <DIR>          config-auto
04/27/2022  06:42 AM    <DIR>          doc
04/27/2022  06:42 AM    <DIR>          easy-rsa
04/27/2022  06:42 AM    <DIR>          include
12/15/2021  08:04 AM            28,553 license.txt
04/27/2022  06:42 AM    <DIR>          log
04/27/2022  06:42 AM    <DIR>          res
04/27/2022  06:42 AM    <DIR>          sample-config

-------

 Directory of C:\*\scoop\apps\openvpn\2.5.5

04/27/2022  06:50 AM    <DIR>          .
04/27/2022  06:50 AM    <DIR>          ..
04/27/2022  06:39 AM         4,411,392 setup.msi_

-------

 Directory of C:\*\scoop\apps\openvpn\current

04/27/2022  06:50 AM    <DIR>          .
04/27/2022  06:50 AM    <DIR>          ..
04/27/2022  06:39 AM         4,411,392 setup.msi_

### System details

**Windows version:** 10 19044.1645

**OS architecture:** 64bit

**PowerShell version:** 5.1.19041.1645

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration
{
    "lastupdate":  "2022-04-27T05:57:29.0524191-05:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}

**Comment by issaclin32** [comment]
Installation works fine on my VM with fresh installed Win10.

Since you have OpenVPN 2.4.10 installed previously, I would assume that OpenVPN was not properly removed.
You can go to **Settings** -> **Installed Apps** to see if OpenVPN still exists there.
If so, then **uninstall it**, and it should work fine.
