### ISSUE TITLE
[Request] utools

### ISSUE THREAD

**Issue by junjieim** [ScoopInstaller/Extras#8399]
### Information

**Name:** [utools]

**Description:** [新一代效率工具平台]

**Homepage:** [a https://u.tools/]

**Download link(s):** [[URL(s)/link(s)](https://res.u-tools.cn/version2/uTools-2.6.3.exe)]

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

**Comment by issaclin32** [comment]
It looks like a great app.

Unfortunately I couldn't find any official documentation/manual written in English. Which makes maintaining the package a problem for our team. If we accept a Chinese app, should we also accept a Russian one? We cannot guarantee that there will always a member to know these languages.

By the way. *uTool*'s English user interface is not complete yet. (tested on a VM with English version of Win10)

If you want to install the app via *Scoop*, you can either [start your own bucket](https://github.com/ScoopInstaller/BucketTemplate),
or use [the package in my personal bucket](https://github.com/issaclin32/scoop-bucket/blob/master/bucket/utools.json) by:
```
scoop bucket add issaclin32 https://github.com/issaclin32/scoop-bucket
scoop install utools
```

**Comment by junjieim** [comment]
@issaclin32 Noted and thank you!
