### ISSUE TITLE
wiztree won't start without admin privileges

### ISSUE THREAD

**Issue by rogerlga** [ScoopInstaller/Extras#8404]
## Bug Report

**Package Name:** wiztree

### Current Behaviour

App won't start if user doesn't have admin privileges.

### Expected Behaviour

Start app even if the user doesn't have admin privileges.

### Additional context/output

A UAC window will be shown on the first app run. The app should start in "non-admin" mode when the user chooses "No" in the UAC.

### Possible Solution

The initial contents of the WizTree3.ini could be:
```ini
[frmWizTreeMain]
actWindowsContextMenu_Checked=FALSE
actRunAsAdmin_Checked=FALSE
```

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1

**Additional software:** n/a

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-04-28T17:19:00.0914266-03:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by issaclin32** [comment]
This should be fixed now.
Run:
 ```
scoop update
scoop uninstall wiztree -p
scoop install wiztree
```
and it should work fine.

**Comment by rogerlga** [comment]
> Thanks for reporting the issue. I just modified the script. Run:
> 
> ```
> scoop update
> scoop uninstall wiztree -p
> scoop install wiztree
> ```
> 
> and it should work fine.

Thank you! It worked flawlessly.
