### ISSUE TITLE
[Request] Hoppscotch

### ISSUE THREAD

**Issue by daydar-ilx** [ScoopInstaller/Extras#8415]
### Information

**Name:** Hoppscotch

**Description:** Hoppscotch is light-weight, web based API development suite. It was built from ground up with ease of use and accessibility in mind providing all the functionality needed for API developers with minimalist, unobtrusive UI. It is free-to-use and as an added perk completely Open Source!

**Homepage:** [Hoppscotch](https://github.com/hoppscotch/hoppscotch)

**Download link(s):** https://github.com/hoppscotch/hoppscotch/releases

**Some indication of popularity/repute:** 43k stars on GitHub

**Comment by rashil2000** [comment]
This application is a PWA. It cannot be installed by Scoop.

**Comment by nagromc** [comment]
Hoppscotch offers a desktop app now: https://github.com/hoppscotch/releases/releases

Please reopen the issue.
