### ISSUE TITLE
linphone@4.3.2: hash check failed

### ISSUE THREAD

**Issue by StarPicard** [ScoopInstaller/Extras#8438]
Checking hash of Linphone-4.3.2-win32.exe ... ERROR Hash check failed!
App:         extras/linphone
URL:         https://www.linphone.org/releases/windows/app/Linphone-4.3.2-win32.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    dcf97d646e812a12cf1702e5234c8c6ba430e818bb2cf873e0ccd57cffcbc281
Actual:      ce49a97fcb91d6d96c62754973506f1460457e0b20b3215645dfc3bb5370f74f

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by StarPicard** [comment]
Thx, it was an error with my git, wich prevented the update. But now I get this error again:

App:         extras/linphone
URL:         https://www.linphone.org/releases/windows/app/Linphone-4.4.1-win64.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    58daca857ca34ac5f76740823a6b8c46defdb901c71e65c6ff56ab5a0952a1d4
Actual:      e05a2e960c5ef91ceac6c0481205c9ad48b3eeb19b266d28a15b2f0104a7fdb0

**Comment by rashil2000** [comment]
Please open a new issue
