### ISSUE TITLE
Streamlink 3.2.0 Crash - amd64

### ISSUE THREAD

**Issue by everonline** [ScoopInstaller/Extras#8451]
## Bug Report

Package Name: streamlink

### Current Behaviour

```ps
raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cp36-win_amd64.pyd', Cannot load '_raw_ecb.pyd': [WinError 193] %1 is not a valid Win32 application
```

### Expected Behaviour

usage: streamlink [OPTIONS] <URL> [STREAM]

### Additional context/output

Streamlink amd64 is crashing.

### Possible Solution

As workaround I used the most recent Win32 version - h**ps://github.com/beardypig/streamlink-portable/releases/download/3.2.0/streamlink-portable-3.2.0-py3.10.0-win32.zip

The amd64 under this version (python 3.10) also crash.

[Also reported on](https://github.com/beardypig/streamlink-portable/issues/32)

### System details

Windows version: 10

OS architecture: 64bit

PowerShell version:

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      3

#### Scoop Configuration

```json
{
  "lastupdate": "2022-05-10T13:28:55.2281279+01:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by bastimeyer** [comment]
The package config is using unofficial "portable" builds that get pulled from a private repository.
https://github.com/ScoopInstaller/Extras/blob/2de320499ec9689161188263700ca9af62416f13/bucket/streamlink.json

Streamlink provides official portable builds for Windows now, in addition to the installers:
- https://github.com/streamlink/windows-builds
- https://github.com/streamlink/windows-builds#notes
- https://streamlink.github.io/latest/install.html#windows-binaries

Please note the ffmpeg differences between the installers and portable builds (see the linked readme), so you'll probably want to either add a wrapper script for launching streamlink, which sets `--ffmpeg-ffmpeg` to the bundled ffmpeg executable, or you'll have to create/update the user's config file.

**Comment by tech189** [comment]
I updated it to the latest official build and added a wrapper script here: https://github.com/ScoopInstaller/Extras/commit/907e32abe4df35bc9902a778a9d4b4015f0cb28f. Let me know if it works!

**Comment by bastimeyer** [comment]
`%*` in the wrapper batch script will break the passed argv. This was reported on the old unofficial portable repo:
https://github.com/beardypig/streamlink-portable/issues/19
where you've taken the wrapper script from:
https://github.com/beardypig/streamlink-portable/blob/96efe8edf51106c38f688f0767a6333326f75f6a/resources/streamlink.bat#L5

**Comment by bastimeyer** [comment]
https://stackoverflow.com/a/5338799/15776887

**Comment by tech189** [comment]
> We can skip creating a batch script here, we can directly pass arguments to the `.exe` shim

Done in https://github.com/ScoopInstaller/Extras/commit/72f6c0cd72d0139b5a7afa7fa360f4219638a647. That's much more simple!

> `%*` in the wrapper batch script will break the passed argv.

I tried messing around with different quotes and escaping but I can't get it work, streamlink seems to always strip the quotes around "foo | bar". Does it work for you when using the installer (i.e. not portable/Scoop)?

**Comment by bastimeyer** [comment]
> streamlink seems to always strip the quotes around "foo | bar"

This has nothing to do with streamlink. This is a fundamental issue with Windows batch scripting, as I pointed out in my link above.

I think you can close this issue now. The updated package should be working fine. Thanks.
