### ISSUE TITLE
anki: Autoupdate doesn't work because URLs have changed

### ISSUE THREAD

**Issue by trallnag** [ScoopInstaller/Extras#8457]
## Bug Report

**Package Name:** anki

### Current Behaviour

The autoupdater is not finding new versions of Anki. It's stuck at version `2.1.49`, while the latest version is `2.1.51`.

### Expected Behaviour

Latest versions after `2.1.49` should be available via Scoop.

### Additional context/output

The reason for the autoupdater not finding new versions is the URL. The autoupdater checks this URL:

    https://github.com/ankitects/anki/releases/download/$version/anki-$version-windows.exe#/dl.7z

But recently Anki has changed it's naming schema.

![image](https://user-images.githubusercontent.com/24834206/167856013-47a80b79-e3c5-4442-aaff-cf9ad90c0df8.png)

https://github.com/ankitects/anki/releases

### Possible Solution

I'm not sure.

- Manually add missing versions.
- Adjust autoupdater url.

**Comment by issaclin32** [comment]
Thanks for reporting. It should be fixed now.
