### ISSUE TITLE
Reference to an auto-closed issue

### ISSUE THREAD

**Issue by JuanMM94** [ScoopInstaller/Extras#8463]
Hello, I'm opening this issue to reference #8460, which states the current problem with a hash check.

**Comment by rashil2000** [comment]
What version are you trying to install?

**Comment by JuanMM94** [comment]
> What version are you trying to install?

Whichever _scoop install teamviewer_ throws at me. Hash check fails but force update tells me I have the latest version. I had to install the app by skipping the hash check.

_scoop update_ doesn't do anything, either.

**Comment by rashil2000** [comment]
No need to be rude. 

Paste the output of `scoop update`.

**Comment by JuanMM94** [comment]
I did not intend to sound rude. I'm sorry.

Anyways, upon further inspection, I came across these:
```
Updating Scoop...
Updating 'extras' bucket...
error: Your local changes to the following files would be overwritten by merge:
	bucket/elisa.json
	bucket/filelight.json
Please commit your changes or stash them before you merge.
Aborting
Updating 'main' bucket...
error: Your local changes to the following files would be overwritten by merge:
[...]
```

So I deleted the listed json's and it worked. Dunno why they were failing though since I've never touched these files. Don't know why they failed. I leave the issue open just in case anyone wants to tell me why they would fail or if I'm doing something wrong.

Thanks for the help and sorry again for the tone.

**Comment by rashil2000** [comment]
This error happens sometime. If it happens again, run this:
```
scoop bucket rm extras
