### ISSUE TITLE
retroarch@1.10.3: hash check failed

### ISSUE THREAD

**Issue by ricardobsp** [ScoopInstaller/Extras#8469]
#### Scoop Configuration

```json
{
  "lastUpdate": "2022-05-14T17:13:26.6850052-03:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```
Checking hash of RetroArch.7z ... ERROR Hash check failed!
App:         extras/retroarch
URL:         https://buildbot.libretro.com/stable/1.10.3/windows/x86_64/RetroArch.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    3b48f22a4ea1ecf65259e4f93ad12500042adb461690aa34d23f909242465f31
Actual:      924f40b63e0cf9aaa0f89c34c75d0c85c26f921c6563917405b099b11ff7ae4c

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/Extras/commit/6736317b10ff102c5dc2a947ce9d54b34f37e9d0
