### ISSUE TITLE
[Request] FreeRapid

### ISSUE THREAD

**Issue by NatoBoram** [ScoopInstaller/Extras#8490]
### Information

**Name:** FreeRapid

**Description:**
> FreeRapid is an easy to use Java downloader that supports downloading from Rapidshare, Youtube, Facebook, Picasa and other file-sharing services, include the new ones like mega.co.nz.
> Simply copy and paste your links from a browser to this application. FreeRapid Downloader will handle the rest itself. No more clicking or uncomfortable waiting. 

**Homepage:** https://wordrider.net/freerapid/index.html

**Download link(s):** https://wordrider.net/freerapid/download.htm

Downloads are hidden behind ad-walls. Specifically, the kind of ad-wall that FreeRapid is made to bypass.

Source code can be downloaded with `git svn clone http://svn.wordrider.net/svn svn.wordrider.net`. Username and passwords are `wordrider`.

**Some indication of popularity/repute:** About 3K topics posted in its forum: https://wordrider.net/forum/index.php?9

**Comment by Vedabahu** [comment]
This app was last updated on 18th May 2014. It also uses Java 6 or 7. So can you please move this issue to the [ScoopInstaller/Versions](https://github.com/ScoopInstaller/Versions) repo.

**Comment by NatoBoram** [comment]
I just finished cloning it with `git svn` and its latest changes look like this:

> * 98ec202fa - (HEAD -> master, git-svn) CeskaTelevize.cz - fixed for more link types (5 months ago) <ntoskrnl>
> * 854ea0e6a - git-svn-id: http://svn.wordrider.net/svn@5826 40407085-c429-0410-a8d0-eb1a82597f6e (5 months ago) <ntoskrnl>
> * 484a7aa16 - NovaPlus - updated (5 months ago) <ntoskrnl>
> * f0b108018 - CeskaTelevize.cz - fixed (5 months ago) <ntoskrnl>
> * 89c8c2d90 - YouTube.com - fixed (11 months ago) <ntoskrnl>
> * 4377db178 - Mega.nz - support new link format (1 year, 3 months ago) <ntoskrnl>
> * 7811dc7d2 - YouTube.com - support non-DASH formats (1 year, 3 months ago) <ntoskrnl>
> * 3cd414621 - YouTube.com - fixed and added AV1 formats (1 year, 3 months ago) <ntoskrnl>
> * 4fdab37ad - ulozto update (2 years, 2 months ago) <Vity>

I think it's updated solely through its plugins.

* Moved to https://github.com/ScoopInstaller/Versions/issues/532
