### ISSUE TITLE
Something terribly wrong just happened

### ISSUE THREAD

**Issue by CrendKing** [ScoopInstaller/Extras#8498]
Look at the commit history: https://github.com/ScoopInstaller/Extras/commits/master. All apps were "updated" to version "1.2_2022-05-15" five hours ago, which is wrong. Some apps, such as XnView MP, is not updated from source. Others, such as Prime95, contain wrong download url now.

Please take a look at. The earliest excavator link seems to be https://github.com/ScoopInstaller/Extras/runs/6478163301.

Sorry for not following the template. I think this is not an individual problem, rather a systematic issue.

**Comment by CrendKing** [comment]
https://github.com/ScoopInstaller/Extras/runs/6484336525 seems to fix the problems for now. What's the root cause of the original problem? Any way to prevent from happening again?

**Comment by rashil2000** [comment]
The problem happens when you use an internal variable in the checkver script (see inscape history in commits)

**Comment by issaclin32** [comment]
The problem is caused by a recent PR, which has `$version` in checkver script. ([related code](https://github.com/ScoopInstaller/Extras/pull/8489/files#diff-7bcd65ce73227a38d6c8d590c1a3faab39e491051108850b7b0c865ec482025aR34))

I will update PR checks to avoid the problem in the future.
Thank you for reporting!

**Comment by CrendKing** [comment]
Are you referring to https://github.com/ScoopInstaller/Extras/pull/8489? Are you saying if someone creates a PR with `$version` in check ver script, and types `/verify` in a comment, ALL apps will be forced to update to a wrong version? Shouldn't the `/verify` only act on the affected app alone?

I mean this seems pretty disastrous. We can't prevent people from creating incorrect or even malicious PR, no?

**Comment by CrendKing** [comment]
I see. Thanks. Still, error from one manifest propagating to the whole bucket seems to be an issue. Ideally the error should be contained within that manifest.
