### ISSUE TITLE
logseq 0.6.9 hash check error

### ISSUE THREAD

**Issue by hornyjailfish** [ScoopInstaller/Extras#8502]
Checking hash of logseq-win-x64-0.6.9.exe ... ERROR Hash check failed!
App:         extras/logseq
URL:         https://github.com/logseq/logseq/releases/download/0.6.9/logseq-win-x64-0.6.9.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    9989fec8adb583461a148e7f0ba4fb495161be197e9f309d10e380a932404d63
Actual:      5c6680342f2a49c7d39ee5b2386ad9957d53d9008097a32f008a549ddac1a696

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/169118205-5e147a8e-fd79-4769-bc1a-cf74e2c03e66.png)
