### ISSUE TITLE
PureRef out of date

### ISSUE THREAD

**Issue by theatlaso** [ScoopInstaller/Extras#8506]
Latest PureRef version is 1.11.1 (released in 2020)
The scoop version is 1.9.2 (released in 2017)

**Comment by issaclin32** [comment]
**PureRef** requires you to pay before downloading it.
Version 1.9.2 is the last version that you can download for free.

For details, check: https://www.pureref.com/download.php

**Comment by theatlaso** [comment]
You don't have to pay, you can just type 0 in the custom amount

**Comment by issaclin32** [comment]
> You don't have to pay, you can just type 0 in the custom amount

Ok. Thanks for the info.

**Comment by terrehbyte** [comment]
To clarify for others, this means that the manifest will only point at 1.11.1 and probably won't be updated to newer versions. Newer download URLs appear to require a "key" query parameter that is generated by either paying or inputting a value of 0 for the payment.
