### ISSUE TITLE
bulk-crap-uninstaller: Fails to install correctly

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Extras#8512]
## Bug Report

**Package Name:** bulk-crap-uninstaller

### Current Behaviour

For some reason, even though the structure of the archive is seemingly unchanged, only one file ends up (or two, if you've a settings file) in the app dir.

![image](https://user-images.githubusercontent.com/67732686/169653184-1374cbd8-e8f9-4067-b2a5-2b1974ab1e18.png)

I couldn't even find the file 'Bulk-Crap-Uninstaller.html' in the archive.

Here's what the contents of the archive looks like:

![image](https://user-images.githubusercontent.com/67732686/169653220-86cbeb48-c337-4a96-b9cc-38dee6879b1d.png)

... and the Extract dir portion of the manifest is unchanged since it seemingly didn't need to be; 

![image](https://user-images.githubusercontent.com/67732686/169653257-10e66344-6c45-43b6-a5f4-3aa570523889.png)

The contents of the 'win-x64' dir:

![image](https://user-images.githubusercontent.com/67732686/169653285-bef940a7-43e4-4a74-97fd-5d7c48666e06.png)

Current CLI output upon attempted installation:

![image](https://user-images.githubusercontent.com/67732686/169653477-abab6125-9cd1-4fe4-ac98-2e9a8ec47ca4.png)

Is someone able to tell what is happening?

### Expected Behaviour

Since the structure is the same, I expect the app to install cleanly like previous versions of the app.

### Additional context/output

The manifest has recently been updated by myself after confirming that the contents of archive are the same and hence seemingly many parts of the manifest could be left as-is.

With the latest release, they changed the archive type from 7z to ZIP.

### Possible Solution

At the moment, not sure.

### System details

**Windows version:** 11 - 22000.613

**OS architecture:** 64bit

**PowerShell version:** 7.2.4

#### Scoop Configuration

rootPath               : F:\Backup\Scoop
lastUpdate             : 2022-05-21 14:24:03
aria2-warning-enabled  : False
MSIEXTRACT_USE_LESSMSI : True
SCOOP_REPO             : https://github.com/ScoopInstaller/Scoop
SCOOP_BRANCH           : master

**Comment by RavenMacDaddy** [comment]
Now I see that apparently only two files are extracted, even though the directories in Extract dir are the same;

![image](https://user-images.githubusercontent.com/67732686/169652515-d2f41d04-f93c-49d0-8dca-879bf94b958e.png)

**Comment by RavenMacDaddy** [comment]
Interestingly, the file 'Bulk-Crap-Uninstaller.html' is not even present in the archive at all from what I can see.

**Comment by AkariiinMKII** [comment]
The archive is renamed to `Bulk-Crap-Uninstaller.html` and I don't know why
![image](https://user-images.githubusercontent.com/6019344/169662558-22a34829-cc2e-4a6c-a301-67ac4233f9bc.png)

**Comment by AkariiinMKII** [comment]
I tried to use another URL and it works
```
"url": "https://ftp.halifax.rwth-aachen.de/osdn/bulk-crap-uninstaller/77343/BCUninstaller_5.3_portable.zip",
"hash": "494ca88f25a50d1768a76f753e8a98fec9cd686f75beb9280938cd48dfa8eaf8"
```
seems there is an error when handling with cached file name
