### ISSUE TITLE
[Request] windowsdesktop-runtime: Change release from Current to LTS

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Extras#8514]
### Information

**Name:** windowsdesktop-runtime

**Description:** Looking at the release cadence from the developer Microsoft, it's clear that the Current release doesn't overlap, which means it's not only out-of-date, but also not secure to use in the future;

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#cadence

Problem is I haven't found a reliable way yet to make the manifest non-dependent of manual updates in regards to the Checkver URL (and the corresponding eventual regex).

https://dotnet.microsoft.com/en-us/download/dotnet/6.0 could be used to check the line ".NET Desktop Runtime < version >" with regex, but eventually that URL would have to be updated manually when v8 is released (and so forth), hence I don't find that a satisfactory solution to the issue.

The Github and its release page for the project includes every kind of version/release and is stating v5 as the latest release even now; https://github.com/dotnet/runtime

The fact that '(recommended)' is present on the Homepage could possibly be used with some form of regex since the full version number is displayed to the right, but I'm personally not sure how to do it.

**Homepage:** https://dotnet.microsoft.com/en-us/download/dotnet

**Download link(s):** 

At the time of writing: 

x64: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.5-windows-x64-installer
x86: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.5-windows-x86-installer

**Some indication of popularity/repute:** 

![image](https://user-images.githubusercontent.com/67732686/169656556-bea7991a-aa9c-4498-ba51-00087860fa51.png)

**Comment by rashil2000** [comment]
LTS is present in the Versions bucket: https://github.com/ScoopInstaller/Versions/blob/master/bucket/windowsdesktop-runtime-lts.json

We can move it here, if required

**Comment by RavenMacDaddy** [comment]
I don't know about required, but definitely recommended based on the reasons mentioned.

**Comment by rashil2000** [comment]
Both are now in Extras
