### ISSUE TITLE
[Request] Eget

### ISSUE THREAD

**Issue by OzakIOne** [ScoopInstaller/Extras#8521]
### Information

**Name:** Eget

**Description:** Easily install prebuilt binaries from GitHub

**Homepage:** [Github](https://github.com/zyedidia/eget)

**Download link(s):** [Release page](https://github.com/zyedidia/eget/releases/tag/v1.0.1)

**Some indication of popularity/repute:** 271 Star atm

**Comment by Vedabahu** [comment]
I am working on it.
