### ISSUE TITLE
[Feature Request] potplayer: Persist PxShader

### ISSUE THREAD

**Issue by Hayxi** [ScoopInstaller/Extras#8529]
**Package Name:** [potplayer](https://github.com/ScoopInstaller/Extras/blob/master/bucket/potplayer.json)

**Feature Request:** Add `PxShader` Directory to persist.

**Comment by issaclin32** [comment]
example of using `PxShader`: https://github.com/bloc97/Anime4K/issues/40

(this is a reminder, no need to modify anything)
