### ISSUE TITLE
[Request] ProtonVPN Windows Client

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Extras#8624]
### Information

**Name:** [name of new package]
proton-vpn

**Description:** [clear and concise details of what it is]
The Proton VPN app for Windows is the best way to stay secure and private when surfing the internet. It is open source, easy to use, and packed with useful security features.

**Homepage:** [a URL/link]
https://protonvpn.com/download-windows

**Download link(s):** [URL(s)/link(s)]
https://protonvpn.com/download/ProtonVPN_win_v2.0.0.exe

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
https://github.com/ProtonVPN/win-app
https://www.pcmag.com/reviews/protonvpn
https://www.techradar.com/reviews/protonvpn

**Comment by issaclin32** [comment]
> Duplicate of #4678

Thanks for reminding me.
