### ISSUE TITLE
[Request] musikcube: Replace 32bit vesion with milkdrop2 version

### ISSUE THREAD

**Issue by KaranKad** [ScoopInstaller/Extras#8658]
### Information

**Name:** musikcube

**Description:** Terminal-based music player, audio engine, metadata indexer, and server.

**Homepage:** https://github.com/clangen/musikcube

**Download link(s):** https://github.com/clangen/musikcube/releases/download/0.97.0/musikcube_win32_with_milkdrop2_0.97.0.zip

**Some indication of popularity/repute:** 3k github stars

I was thinking if we could replace 32bit version of musikcube with milkdrop version. There isn't much difference between normal version and milkdrop one other than the visualizer. 64bit version of musikcube with milkdrop is not available.

OR

Should I create a new package with name musikcube-milkdrop.

I think replacing 32bit version in regular manifest would be better as there isn't much difference between them.

**Comment by rashil2000** [comment]
Hmm, any idea why it's not there for 64bit (there must be a catch)?

**Comment by KaranKad** [comment]
I don't know. 
Author mentions that milkdrop does not work with 64bit version
https://github.com/clangen/musikcube/issues/462#issuecomment-1003949707

Also, `musikcube-cmd.exe` is the binary for cli version instead of `musikcube.exe`
