### ISSUE TITLE
GIMP 2.0 need a change of the installer 

### ISSUE THREAD

**Issue by Xelbayria** [ScoopInstaller/Extras#8674]
## Bug Report

**Package Name:** GIMP v2.10.30

### Current Behaviour

It's very simple. You can do the same thing I did to see the problem: 
1) Open GIMP and wait for it to finish loading
2) Go to Menu: `Filter` -> `Python-fu` -> `Console` 
3) click the `Console` and wait

the result is that you will see nothing show up. Python-fu's Console is not being called and there are issues within GIMP where it's not working with Python. it has to do with PATH that GIMP is using to find the libraries of Python or Plug-ins. It's complicated.

This is not a problem with Scoop, There is a solution for this. 

### Expected Behaviour

When I clicked `Console` via the menu, I expected to see a console showing up/popping up. 

### Possible Solution

I recommend that the installer is to be changed to [Portable](https://portableapps.com/downloading/?a=GIMPPortable&n=GIMP%20Portable&s=s&p=&d=pa&f=GIMPPortable_2.10.30.paf.exe)

This is from the portable website that Scooper could use to install the apps as portable without any issue. 

I ran the same action with this GIMP portable. The console showed up without any problem. 

### System details

**Windows version:** 10 pro

**OS architecture:** 64bit

EDIT: 
On note, The portable app is already on the same version as the official version of GIMP

**Comment by rashil2000** [comment]
Hi! Can you make a PR for the same?

**Comment by Xelbayria** [comment]
> Hi! Can you make a PR for the same?

I wasn't experienced enough to do PR. Sorry about that.

**Comment by Xelbayria** [comment]
hmm...
I mentioned the issue with GIMP's path not finding the files where it needs to call `python-fu`'s console. 
```
    "installer": {
        "script": [
            "Push-Location \"$dir\"",
            "Get-ChildItem -Filter '*.debug' -Recurse | Remove-Item -Recurse",
            "if ($architecture -eq '64bit') {",
            "   Rename-Item 'lib\\gimp\\2.0\\plug-ins\\twain\\twain,3.exe' 'twain.exe'",
            "   Remove-Item 'lib\\gimp\\2.0\\plug-ins\\twain\\twain,1.exe'",
            "   Get-ChildItem -Filter '*,1*' -Recurse | Rename-Item -NewName { $_.name -Replace ',\\d','' }",
            "   Get-ChildItem -Filter '*,*' -Recurse | Remove-Item",
            "} else {",
            "   Rename-Item 'lib\\gimp\\2.0\\plug-ins\\twain\\twain,1.exe' 'twain.exe'",
            "   Remove-Item 'lib\\gimp\\2.0\\plug-ins\\twain\\twain,3.exe'",
            "   Get-ChildItem -Filter '*,1*' -Recurse | Remove-Item",
            "   Get-ChildItem -Filter '*,*' -Recurse | Rename-Item -NewName { $_.name -Replace ',\\d','' }",
            "}",
            "$defpath = \"`nPATH=`${gimp_installation_dir}\\bin`n\"",
            "$defenv = Get-Content 'lib\\gimp\\2.0\\environ\\default.env' -Raw",
            "$defenv += $defpath",
            "$defenv += \"PYTHONPATH=`${gimp_installation_dir}\\lib\\gimp\\2.0\\python;`${gimp_plug_in_dir}\\plug-ins\\python-console\"",
            "$defenv | Set-Content 'lib\\gimp\\2.0\\environ\\default.env'",
            "$pyenv = Get-Content 'lib\\gimp\\2.0\\environ\\pygimp.env' -Raw",
            "$pyenv + '__COMPAT_LAYER=HIGHDPIAWARE' | Set-Content 'lib\\gimp\\2.0\\environ\\pygimp.env'",
            "$pyint = Get-Content 'lib\\gimp\\2.0\\interpreters\\pygimp.interp' -Raw",
            "$pyint = $pyint -Replace '(python|python2)=(.*)', \"`$1=$dir\\bin\\pythonw.exe\"",
            "$pyint = $pyint -Replace 'py::python2', 'py::python'",
            "$pyint | Set-Content 'lib\\gimp\\2.0\\interpreters\\pygimp.interp'",
            "Pop-Location"
        ]
        ```
     I doubted this is correct because this is related to Python.  The above is from GIMP.json
     
     if anyone is kind enough to find an alternative to correct the JSON info above. I would be happy to run some tests to ensure that it's working as intended.  You only need to provide the changed info above. so I can copy it and run some tests with the pasted info into GIMP.json

**Comment by Lutra-Fs** [comment]
I have tested GIMP on my own devices. If replacing default.env (in $installation-dir/lib//gimp/2.0/environ) with the [version](https://gist.github.com/Lutra-Fs/1ae07d908ef8b3e22635752724f46673) I upload to gist, the console can start correctly. I am not sure about the reason but it worked on my Windows 11 devices.

**Comment by Lutra-Fs** [comment]
> I have tested GIMP on my own devices. If replacing default.env (in $installation-dir/lib//gimp/2.0/environ) with the [version](https://gist.github.com/Lutra-Fs/1ae07d908ef8b3e22635752724f46673) I upload to gist, the console can start correctly. I am not sure about the reason but it worked on my Windows 11 devices.

make sure to download zip from the page and then extract it... the content should be the same but the sizes are slightly different.

**Comment by Xelbayria** [comment]
Dang... so that was the cause?!?! 

that fixed my issue on my Windows 10 pro.  I know why. hmm 🤔

**Comment by Lutra-Fs** [comment]
@rashil2000 should we add a hint as a temporary solution? The file can be also upload to scripts folder.

**Comment by Lutra-Fs** [comment]
> @rashil2000 should we add a hint as a temporary solution? The file can be also upload to scripts folder.

I can make a PR for that

**Comment by rashil2000** [comment]
Sure!

**Comment by Lutra-Fs** [comment]
Should I add a note or change the script by copying and pasting from script folder?

**Comment by rashil2000** [comment]
Changing the script should be better, as new users might not be able to make changes themselves

**Comment by Lutra-Fs** [comment]
> Changing the script should be better, as new users might not be able to make changes themselves

thanks, PR #8915 has been submitted to fix the issue

**Comment by Xelbayria** [comment]
The issue is back with `GIMP 2.10.34` and I am looking in the correct path to make python-console functioning properly.

**Comment by Xelbayria** [comment]
Will someone answer the question above, please? 

I screwed up by doing `scoop cleanup gimp` after updating GIMP when I should have looked at the solution I had for Pythonfu Console to show up and work properly?

**Comment by Lutra-Fs** [comment]
@Xelbayria Could you reopen this issue or create a new one? a very wired issue. I am happy to assist you on solving this.
