### ISSUE TITLE
[qbittorrent-enhanced] Error 404 on update

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [ScoopInstaller/Extras#8687]
## Bug Report

**Package Name:** qbittorrent-enhanced

### Current Behaviour
Error when updating `4.4.2.10 -> 4.4.3.12`

### Expected Behaviour
No error during update.

### Additional context/output

```
qbittorrent-enhanced: 4.4.2.10 -> 4.4.3.12
Updating one outdated app:
Updating 'qbittorrent-enhanced' (4.4.2.10 -> 4.4.3.12)
Downloading new version
OperationStopped: G:\Scoop\apps\scoop\current\lib\install.ps1:107
Line |
 107 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.
```

### Possible solution
Looking at the [JSON ](https://github.com/ScoopInstaller/Extras/blob/dd7cbac8a50755f680f8b6d63641824a9a390de9/bucket/qbittorrent-enhanced.json#L8) for this app, the download link points to `qbittorrent_enhanced_4.4.3.12_Qt6_setup.exe.`

But the newest version indexed by scooop is a fix for Qt6 users only, and the filename is `qbittorrent_enhanced_4.4.3.12_Qt6_setup_fix.exe`.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.4

**Additional software:** mingit-busybox instead 

#### Scoop Configuration

```json
{
  "lastupdate": "2022-06-14T12:54:40.6949057+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "alias": {}
}
```

**Comment by issaclin32** [comment]
Fixed in https://github.com/ScoopInstaller/Extras/commit/e9c150595d681686af0a228ada72cf2ac6c2a982

**Comment by issaclin32** [comment]
> Note: in the future that link may change again, to the previous form whithout the `_fix` at the end.

That is why I only changed `url`, but didn't change `autoupdate` -> `url`. Thanks for reporting.
