### ISSUE TITLE
klogg needs update to latest version

### ISSUE THREAD

**Issue by mpela81** [ScoopInstaller/Extras#8688]
## Bug Report

**Package Name:** klogg

### Current Behaviour

klogg package is currently at outdated version `20.12.0.813`

### Expected Behaviour

klogg package should be updated to latest version, currently `22.06.0.1288`

### Additional context/output

It looks like the release file name format has been changed, for example: `klogg-22.06.0.1288-Win-x64-Qt5-portable.zip`

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.4

**Comment by rashil2000** [comment]
Hi! Can you make a PR for it?
