### ISSUE TITLE
[Request] SMPlayer

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#8701]
Package Request Information
Name: SMPlayer

Description: a video player forked from MPV

Homepage: https://www.smplayer.info/en/info

Download link(s): https://www.fosshub.com/SMPlayer.html/smplayer-22.2.0-x64.exe

PS: I know there is a similar package https://github.com/ScoopInstaller/Extras/pull/429. But, the old request is portable version

**Comment by issaclin32** [comment]
The app can be extracted and work properly. Unfortunately *SMPlayer*'s repo has protected their link from direct download.

Probably someone can give us a good idea about how to solve this.

Under **Chrome**, The link `https://www.fosshub.com/SMPlayer.html?dwl=smplayer-22.2.0-x64.exe` resolves to something like: `https://download.fosshub.com/Protected/expiretime=1655445161;badurl=aHR0cHM6Ly93d3cuZm9zc2h1Yi5jb20vU01QbGF5ZXIuaHRtbA==/679febd20b4060ecec245dca1507cd8a31ab884d211f09b289865079430e5eae/5b8e6ac059eee027c3d78a0d/621cc4b90d4819d031b5b0e0/smplayer-portable-22.2.0.0-x64.7z`, but this cannot work in direct downloads.

**Comment by elovelan** [comment]
Have you seen [Scoop Wiki: Autoupdate: Special cases for FossHub and SourceForge](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#special-cases-for-fosshub-and-sourceforge) and [`scoop/lib/core.ps1`: `handle_special_urls`](https://github.com/ScoopInstaller/Scoop/blob/d63b7d6f01bb33c473172715d1007751baf937de/lib/core.ps1#L1058-L1073)? It should work if you use the recommended conventions. Happy to open a PR if not.

**Comment by issaclin32** [comment]
> Have you seen [Scoop Wiki: Autoupdate: Special cases for FossHub and SourceForge](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#special-cases-for-fosshub-and-sourceforge) and [`scoop/lib/core.ps1`: `handle_special_urls`](https://github.com/ScoopInstaller/Scoop/blob/d63b7d6f01bb33c473172715d1007751baf937de/lib/core.ps1#L1058-L1073)? It should work if you use the recommended conventions. Happy to open a PR if not.

It works fine. Thank you for the info.
