### ISSUE TITLE
[Request] resfetch

### ISSUE THREAD

**Issue by furtidev** [ScoopInstaller/Extras#8707]
### Information

**Name:** [name of new package]
resfetch

**Description:** [clear and concise details of what it is]
A fast and minimal alternative to neofetch

**Homepage:** [a URL/link]
https://github.com/furtidev/resfetch

**Download link(s):** [URL(s)/link(s)]
https://github.com/furtidev/resfetch/releases/download/1.0.1/resfetch.exe

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
null

**Comment by Vedabahu** [comment]
I am working on it.

**Comment by rashil2000** [comment]
This project is too new, and cannot be added to any official buckets.

Besides, it offers little value, and moreover the official client of libmacchina, called macchina-cli, already exists in the Main bucket. https://github.com/ScoopInstaller/Main/blob/master/bucket/macchina.json
