### ISSUE TITLE
Update freecad to 0.20.0 + broken checkver and autoupdate

### ISSUE THREAD

**Issue by JanuszSamborski** [ScoopInstaller/Extras#8718]
## Bug Report

**Package Name:** freecad
### Current Behaviour

Current version is stuck on 0.19.3

### Expected Behaviour

Version should be updated to 0.20.0

### Additional context/output

Filenames for releases of freecad are a total mess, auto update can be as well removed completely since there's a slim chance that it'll work.
Eg. in current URL `https://github.com/FreeCAD/FreeCAD/releases/download/0.20/FreeCAD-0.20.0-WIN-x64-portable-1.zip` file name contains path version, but `/download/` stops at minor version. Not to mention random `-1` at the end of filename, which shows up in a few of the previous versions (I think I've seen `-2` as well somewhere).
`extract_dir` should be removed as well for 0.20.0 version.

### Possible Solution

```json
{
    "version": "0.20.0",
    "description": "A free and open-source multi-platform parametric 3D modeler.",
    "homepage": "https://www.freecadweb.org",
    "license": "LGPL-2.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/FreeCAD/FreeCAD/releases/download/0.20/FreeCAD-0.20.0-WIN-x64-portable-1.zip",
            "hash": "618ee903684879306a27cf76ebdf68b8587cd66be376d703eb8ad5452293edd4"
        }
    },
    "bin": "bin\\FreeCADCmd.exe",
    "shortcuts": [
        [
            "bin\\FreeCAD.exe",
            "FreeCAD"
        ]
    ],
    "checkver": {
        "url": "https://api.github.com/repos/FreeCAD/FreeCAD/releases",
        "regex": "FreeCAD-([\\d.]+)-WIN-x64-portable(-\\d+)?\\.(zip|7z)"
    }
}
```

**Comment by tech189** [comment]
@issaclin32 is it possible that we might need to add the `-1` at the end of the file name to the version number and in checkver? I suspect they silently re-release an updated binary without changing the version number which would lead to hash mismatches. Should we leave it for now and add it later if this is the case?

**Comment by issaclin32** [comment]
> @issaclin32 is it possible that we might need to add the `-1` at the end of the file name to the version number and in checkver? I suspect they silently re-release an updated binary without changing the version number which would lead to hash mismatches. Should we leave it for now and add it later if this is the case?

I think you are right. This description:
> the larger installer version "-2" provides a fully functional FEM environment. If you don't need FEM simulations, you can opt for the smaller installer version "-1"

only makes sense for [version 0.19.4](https://github.com/FreeCAD/FreeCAD/releases/tag/0.19.4), but not for [0.20-beta](https://github.com/FreeCAD/FreeCAD/releases/tag/0.20beta1). (FreeCAD-0.20.0beta-WIN-x64-installer **-5** .exe)

I tried to find snapshots for older 0.20-beta revisions on archive.org. Unfortunately I couldn't find one.
