### ISSUE TITLE
signal@5.46.0: Hash check failed

### ISSUE THREAD

**Issue by kvithayathil** [ScoopInstaller/Extras#8720]
Hash check failed!
App:         extras/signal
URL:         https://updates.signal.org/desktop/signal-desktop-win-5.46.0.exe#/dl.7z
First bytes: 77 90 144 0 3 0 0 0
Expected:    02c1615f7ffd16513122d425fde1c34e253b9ffeecd438b8ba66a6fdb26f65e324d367f9bd31e7fd0af41aedec3498df5f2bff6a5b3049e331e40c2bec24be1b
Actual:      1df4ba518cfe3eafbbd0e37b5687d4696ed1d711a4c3dbfcfbba1e0502f4a55377a81143b8a80b69aaa18063242dd55c19deda201b81dac341f05d99479a36ea

**Comment by tech189** [comment]
Related to #8719, I think it might be an upstream issue
