### ISSUE TITLE
[Request] Nutstore Network Disk 坚果云

### ISSUE THREAD

**Issue by b4imetu** [ScoopInstaller/Extras#8726]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Nutstore Network Disk 坚果云

**Description:** Nutstore Official Website|Enterprise Network Disk|Team Network Disk|Personal Cloud Disk|Synchronous Cloud Disk. Share your files anytime, anywhere, with any device

**Homepage:** https://www.jianguoyun.com/

**Download link(s):** https://www.jianguoyun.com/static/exe/installer/NutstoreWindowsWPFInstaller.exe

**Some indication of popularity/repute:** To me, Nutstore is as important as the OneDrive

**Comment by niheaven** [comment]
Suggest submitting issue at https://github.com/chawyehsu/dorado

**Comment by b4imetu** [comment]
> Suggest submitting issue at https://github.com/chawyehsu/dorado

https://github.com/chawyehsu/dorado/issues/88

Now I get it, Thanks anyway ^^
