### ISSUE TITLE
[Request]  Forkgram

### ISSUE THREAD

**Issue by sayeed205** [ScoopInstaller/Extras#8739]
### Information

**Name:** [Forkgram Desktop]

**Description:** [Fork of Telegram Desktop messaging app with extra features]

**Homepage:** [https://github.com/Forkgram/tdesktop]

**Download link(s):** [https://github.com/Forkgram/tdesktop/releases/download/v4.0.0/Telegram.zip]

**Some indication of popularity/repute:** [101 GitHub stars/4k+ GitHub forks.]

**Comment by SonaliBendre** [comment]
https://github.com/ScoopInstaller/Extras/pull/8743
