### ISSUE TITLE
Installing `flutter` does not set all relevant environment config

### ISSUE THREAD

**Issue by ZaLiTHkA** [ScoopInstaller/Extras#8740]
## Bug Report

**Package Name:** `flutter`

### Current Behaviour

installing `flutter` through `scoop` downloads and configures everything _well enough_ to use it from the command line, along with exposing all relevant tools through the `PATH` environment variable.

### Expected Behaviour

installing `flutter` through `scoop` _does not_ configure the `FLUTTER_ROOT` environment variable, which certain third-party systems also look for.

### Additional context/output

_for me personally_, this came up as an error launching VSCode with the Flutter extension already installed, where VSCode complained that it could not locate the Flutter SDK.

checking the Dart website FAQ, I see the following entry:

> Why can’t Dart Code find my Dart/Flutter SDK? [#](https://dartcode.org/faq/#why-cant-dart-code-find-my-dartflutter-sdk)
>
> Dart Code generally will try to find Dart and/or Flutter automatically, searching plces including:
> 
> * Paths in the `PATH` environment variable
> * Paths in the `.packages` or `.dart_tool/package_config.json` files created by pub when running `pub get`
> * The `dart.sdkPath` and `dart.flutterSdkPath` settings in VS Code
> * A `.flutter` or `vendor/flutter` folder in your current project
> * The `FLUTTER_ROOT` environment variable
> * `~/snap/flutter/common/flutter` (on Linux)
>
> Depending on how you launch VS Code it may not inherit the `PATH` variable from your terminal. For information on how best to set your `PATH` see [Configuring PATH and Environment Variables](https://dartcode.org/docs/configuring-path-and-environment-variables/).
> 
> Note: If Dart Code detects that you have a Flutter project open then it will prefer to use the version of the Dart SDK that is bundled in the Flutter SDK, otherwise it will prefer to use a version of Dart directly from your `PATH`.

### Possible Solution

based on the above information, and looking through other Scoop package `json` files, I believe the best solution here is to add the following snippet to the `bucket/flutter.json` file in this bucket repository:

```json
{
    "env_set": {
        "FLUTTER_ROOT": "$dir"
    }
}
```

> #### OPEN QUESTION
> 
> I'm opting to start this with an issue log rather than a PR, because I need some input on the following first:
> 
> * **should this use `$dir`, `$originalDir`, or `$persistDir`?**
> 
> looking at the [current installation script logic](https://github.com/ScoopInstaller/Scoop/blob/93db5f47f1063c3a147153eef266fc34d65dc46e/lib/install.ps1), I see these three variables defined on lines 48 through 50, though I'm not perfectly clear which would be the best to use _here_.
> 
> ultimately, I think we want the path to always point to the active version (in case multiple are installed), so this should _probably_ use the symlinked path..
> 
> for example: update the variable using `C:\\Users\\<username>\\scoop\\apps\\flutter\\current`, **not** `C:\\Users\\<username>\\scoop\\apps\\flutter\\3.0.2`.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** `7.2.4`

**Additional software:** n/a

#### Scoop Configuration

```json
{
  "lastupdate": "2022-06-21T13:38:43.5958722+02:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by issaclin32** [comment]
Thank you for the detailed bug report. I have added:
```
"env_set": {
    "FLUTTER_ROOT": "$dir"
}
```
into the script.

> should this use $dir, $originalDir, or $persistDir?

Definitely `$dir`.

* $dir -> `(SCOOP_DIR)\apps\flutter\current`
This is the most common way to add env variables. You can see it many packages like `gcc`, `cuda`, `python`, `perl`, ...

* $original_dir ->  `(SCOOP_DIR)\apps\flutter\3.0.2`
This is mainly designed for apps that does not work under symlinks/junctions, or if the app resolves the junction (`flutter\current`) to the actual folder (`flutter\3.0.2`) by itself.

* $persist_dir -> `(SCOOP_DIR)\persist\flutter`
For example, if there is a `config` folder put in the *persist* field. Then, `$dir\config` will be a junction that points to `$persist_dir\config`.
Therefore, this will only work if the target (whether a file or directory) is **persisted**. Also, it is not preferred because `$dir\config` can just work fine, unless there is a specific reason use `$persist_dir`.

**Comment by ZaLiTHkA** [comment]
> Thank you for the detailed bug report...

no problem at all, glad I could help.

> Definitely `$dir`.

thank you for the clarification, I'm having fun digging through all the different moving parts that make "scoop" what it is.. this definitely helps me understand it a bit better. 👍🏼
