### ISSUE TITLE
[Request] lapce

### ISSUE THREAD

**Issue by ibra** [ScoopInstaller/Extras#8760]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** lapce

**Description:** a lightning-fast and powerful code editor written in Rust.

**Homepage:** https://lapce.dev/

**Download link(s):** https://github.com/lapce/lapce/releases

**Some indication of popularity/repute:** over 12.5k GitHub stars, 240 issues, and over 200 total pull requests.

**Comment by tech189** [comment]
It's already in Extras: https://github.com/ScoopInstaller/Extras/blob/master/bucket/lapce.json

You can install it with `scoop install lapce`.
