### ISSUE TITLE
tortoisesvn@1.14.3.29387: download via aria2 failed

### ISSUE THREAD

**Issue by 129duckflew** [ScoopInstaller/Extras#8772]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://osdn.mirror.constant.com//storage/g/t/to/tortoisesvn/1.14.3/Application/TortoiseSVN-1.14.3.29387-x64-svn-1.14.2.msi
    referer=https://osdn.mirror.constant.com//storage/g/t/to/tortoisesvn/1.14.3/Application/
    dir=C:\Users\Administrator\scoop\cache
    out=tortoisesvn#1.14.3.29387#https_osdn.mirror.constant.com_storage_g_t_to_tortoisesvn_1.14.3_Application_TortoiseSVN-1.14.3.29387-x64-svn-1.14.2.msi
https://raw.githubusercontent.com/ScoopInstaller/Extras/master/scripts/tortoisesvn/tortoisesvn-install-tools.reg.templ
    referer=https://raw.githubusercontent.com/ScoopInstaller/Extras/master/scripts/tortoisesvn/
    dir=C:\Users\Administrator\scoop\cache
    out=tortoisesvn#1.14.3.29387#https_raw.githubusercontent.com_ScoopInstaller_Extras_master_scripts_tortoisesvn_tortoisesvn-install-tools.reg.templ
https://raw.githubusercontent.com/ScoopInstaller/Extras/master/scripts/tortoisesvn/tortoisesvn-install.reg.templ
    referer=https://raw.githubusercontent.com/ScoopInstaller/Extras/master/scripts/tortoisesvn/
    dir=C:\Users\Administrator\scoop\cache
    out=tortoisesvn#1.14.3.29387#https_raw.githubusercontent.com_ScoopInstaller_Extras_master_scripts_tortoisesvn_tortoisesvn-install.reg.templ
https://raw.githubusercontent.com/ScoopInstaller/Extras/master/scripts/tortoisesvn/tortoisesvn-uninstall.reg
    referer=https://raw.githubusercontent.com/ScoopInstaller/Extras/master/scripts/tortoisesvn/
    dir=C:\Users\Administrator\scoop\cache
    out=tortoisesvn#1.14.3.29387#https_raw.githubusercontent.com_ScoopInstaller_Extras_master_scripts_tortoisesvn_tortoisesvn-uninstall.reg

ERROR & 'C:\Users\Administrator\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Administrator\scoop\cache\tortoisesvn.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=27876 --continue --summary-interval=0 --auto-save-interval=1

**Comment by tech189** [comment]
No issues here, could you try again with aria2 disabled?

**Comment by 129duckflew** [comment]
When I disabled aria2 , it worked
