### ISSUE TITLE
android-studio error installing

### ISSUE THREAD

**Issue by klauern** [ScoopInstaller/Extras#880]
I'm getting this error when installing `android-studio`.  I'm not sure what the underlying issue is, though, but I think for the time being, it's broken for me, which means it's quite likely broken for others:

```ps1
C:\Users\klauer
λ  scoop cache rm *
C:\Users\klauer
λ  scoop uninstall android-studio; scoop install android-studio
Uninstalling 'android-studio' (3.1.0.16).
'android-studio' was uninstalled.
Installing 'android-studio' (3.1.0.16) [64bit]
android-studio-ide-173.4670197-windows.zip (854.2 MB) [========================================================================================================================================] 100%
Checking hash of android-studio-ide-173.4670197-windows.zip... ok.
Extracting... Unzip failed: Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find a part of the path 'C:\Users\klauer\scoop\apps\android-studio\3.1.0.16\_tmp\android-studio\gradle\m2repository\org\jetbrains\kotlin\android\extensions\org.jetbrains.kotlin.android.extensions.gradle.plugin\1.2.30\org.jetbrains.kotlin.android.extensions.gradle.plugin-1.2.30-sources.jar.md5'."
```

**Comment by rasa** [comment]
This filename is 268 characters long:
`C:\Users\klauer\scoop\apps\android-studio\3.1.0.16\_tmp\android-studio\gradle\m2repository\org\jetbrains\kotlin\android\extensions\org.jetbrains.kotlin.android.extensions.gradle.plugin\1.2.30\org.jetbrains.kotlin.android.extensions.gradle.plugin-1.2.30-sources.jar.md5`
On many file systems, Windows has a 260 character limit on paths. See https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by Lutra-Fs** [comment]
I have tried to install android-studio with scoop and no error during installation. I think the issue has been solved. I have a look at the newest zip installer file, and the path length has been optimized shorter.
