### ISSUE TITLE
sysinternals: Can't shim 'handle64.exe': File doesn't exist.

### ISSUE THREAD

**Issue by mattia72** [ScoopInstaller/Extras#8803]
scoop install sysinternals

gives the following error:

    ...
    Creating shim for 'FindLinks64'.
    Creating shim for 'handle'.
    Can't shim 'handle64.exe': File doesn't exist.

#### Scoop Configuration
```json
{
  "lastUpdate": "2022-07-05T11:01:13.6675922+02:00",
  "aria2-warning-enabled": false,
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by tech189** [comment]
That's odd, maybe the download failed part way. Could you run `scoop cache rm sysinternals` to delete the download and then reinstall?

**Comment by mattia72** [comment]
I've tried rm cache and reinstall, but it didn't work:

    PS >  scoop cache rm sysinternals
    Removing https_download.sysinternals.com_files_SysinternalsSuite.zip...
    Removing https_download.sysinternals.com_files_SysinternalsSuite.zip...
    Deleted: 2 files, 91,5 MB
    PS >  scoop install sysinternals
    Updating Scoop...
    Updating 'extras' bucket...
    Updating 'main' bucket...
    ...   
    Scoop was updated successfully!
    WARN  Purging previous failed installation of sysinternals.
    ERROR 'sysinternals' isn't installed correctly.
    Removing older version (2022.May.11).
    'sysinternals' was uninstalled.
    Installing 'sysinternals' (2022.May.11) [64bit]
    Starting download with aria2 ...
    Download: Download Results:
    Download: gid   |stat|avg speed  |path/URI
    Download: ======+====+===========+=======================================================
    Download: 50b032|OK  |   1.9MiB/s|c:/home/scoop/cache/sysinternals#2022.May.11#https_download.sysinternals.com_files_SysinternalsSuite.zip
    Download: Status Legend:
    Download: (OK):download completed.
    Checking hash of SysinternalsSuite.zip ... ok.
    Extracting SysinternalsSuite.zip ... done.
    Linking C:\home\scoop\apps\sysinternals\current => C:\home\scoop\apps\sysinternals\2022.May.11
    Creating shim for 'accesschk'.
    ...
    Creating shim for 'handle'.
    Can't shim 'handle64.exe': File doesn't exist.
    PS >

That's odd, indeed:

    7z l C:\home\scoop\cache\sysinternals#2022.May.11#https_download.sysinternals.com_files_SysinternalsSuite.zip | grep -i handle
    STDIN
    2020-03-02 05:57:06 .....      1016688       430801  handle.exe
    2020-03-02 05:53:40 .....       591736       249308  handle64.exe
