### ISSUE TITLE
[Request] guiscrcpy

### ISSUE THREAD

**Issue by SonaliBendre** [ScoopInstaller/Extras#8818]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [name of new package]
GuiScrcpy
**Description:** [clear and concise details of what it is]
A full fledged GUI integration for the award winning open-source android screen mirroring system -- scrcpy
**Homepage:** [a URL/link]
https://guiscrcpy.srev.in/
**Download link(s):** [URL(s)/link(s)]
https://github.com/srevinsaju/guiscrcpy/releases

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

1.7k stars

**Comment by SonaliBendre** [comment]
I'm confused because there are 2 versions - pyqt5 & pyside2 . pyqt5 doesn't work in Windows 11 and pyside2 has some dependency errors

**Comment by issaclin32** [comment]
> I'm confused because there are 2 versions - pyqt5 & pyside2 .
> pyqt5 doesn't work in Windows 11

I think it is fine. We can just add **Windows version check** in `pre_install`.

> and pyside2 has some dependency errors
Have you tried to solve the issue in some ways? (for example, install the dependency). Would be grateful if you can provide more information about this.

**Comment by Lutra-Fs** [comment]
What is the difference between it and qtscrcpy? 
I have tested the qt5 version on my Windows 11 device and it works well. I think it has been fixed [upstream](https://github.com/srevinsaju/guiscrcpy/pull/266). Related to https://github.com/srevinsaju/guiscrcpy/issues/265
