### ISSUE TITLE
[Request] libre-speed-cli

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Extras#8833]
### Criteria

For a package to be acceptable in the Main bucket, it should be:

- [x] a non-GUI tool
- [ ] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Information

**Name:** [name of new package]
libre-speed-cli

**Description:** [clear and concise details of what it is]
Command line client for librespeed.org

**Homepage:** [a URL/link]
https://github.com/librespeed/speedtest-cli

**Download link(s):** [URL(s)/link(s)]
https://github.com/librespeed/speedtest-cli/releases/download/v1.0.9/librespeed-cli_1.0.9_windows_amd64.zip
https://github.com/librespeed/speedtest-cli/releases/download/v1.0.9/librespeed-cli_1.0.9_windows_386.zip

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
https://alternativeto.net/software/librespeed-cli/about/
https://github.com/librespeed/speedtest-cli

**Comment by KrisSchneider** [comment]
But doesn't the extras bucket require a package to have a GUI at least?

**Comment by tech189** [comment]
It's just anything that doesn't fit the [requirements for Main](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket) - there's no requirement for a GUI.
