### ISSUE TITLE
[Request] Spyder ide

### ISSUE THREAD

**Issue by Vedabahu** [ScoopInstaller/Extras#8838]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [X] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [X] the latest stable version of the program

### Information

**Name:** Spyder IDE
**Description:** The Scientific Python Development Environment. An IDE for machine learning in python.

**Homepage:** https://www.spyder-ide.org/

**Download link(s):**
[Spyder_64bit_full.exe](https://github.com/spyder-ide/spyder/releases/download/v5.3.1/Spyder_64bit_full.exe)
[Spyder_64bit_lite.exe](https://github.com/spyder-ide/spyder/releases/download/v5.3.1/Spyder_64bit_lite.exe)

**Some indication of popularity/repute:** 7.1k Stars and 1.4k forks.

I advice creating 2 manifests for The full version and Lite version.

**Comment by Zliced13** [comment]
Sorry for the late PR. If you want it, you can add it from my personal bucket:
```
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
```
```
scoop install spyder
```
Or
```
scoop install spyder-lite
```

**Comment by Vedabahu** [comment]
> Sorry for the late PR. If you want it, you can add it from my personal bucket:
> 
> ```
> scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
> ```
> 
> ```
> scoop install spyder
> ```
> 
> Or
> 
> ```
> scoop install spyder-lite
> ```

Thank you so much.
