### ISSUE TITLE
gremlin bat should use under its own folder.

### ISSUE THREAD

**Issue by ciaranchen** [ScoopInstaller/Extras#8842]
## Bug Report

**Package Name:** apache-tinkerpop-gremlin-console  &  apache-tinkerpop-gremlin-server

### Current Behaviour

The bat files of these two packages need to be used under its own `bin\` folder. 

But the bat files can be used globally through "bin" option.

### Possible Solution

Remove this line from the package:

```
# bucket\apache-tinkerpop-gremlin-console.json
    "bin": "bin\\gremlin.bat",

# bucket\apache-tinkerpop-gremlin-server.json
    "bin": "bin\\gremlin-server.bat",
```

### System details

**Windows version:** 10

**OS architecture:** 64bit

**Comment by issaclin32** [comment]
fixed in #8855
