### ISSUE TITLE
[Request] Add Podman Desktop

### ISSUE THREAD

**Issue by nagromc** [ScoopInstaller/Extras#8848]
### Information

**Name:** Podman Desktop

**Description:** Podman Desktop enables you to easily work with containers from your local environment. Podman Desktop leverages Podman Engine to provide a lightweight and daemon-less container tool.

**Homepage:** https://podman-desktop.io/

**Download link(s):**
- Installer: https://github.com/containers/podman-desktop/releases/download/v0.0.5/podman-desktop-0.0.5-setup.exe
- Standalone: https://github.com/containers/podman-desktop/releases/download/v0.0.5/podman-desktop-0.0.5.exe

**Some indication of popularity/repute:** This is the official desktop client made by Red Hat. It doesn’t fully meet the requirements ATM (30 forks only) but it is only a matter of time because the app is quite new ([first release](https://github.com/containers/podman-desktop/releases/tag/v0.0.1) on 2022-03-17).

I can implement the app manifest.

**Comment by issaclin32** [comment]
> This is the official desktop client made by Red Hat. It doesn’t fully meet the requirements ATM (30 forks only) but it is only a matter of time because the app is quite new ([first release](https://github.com/containers/podman-desktop/releases/tag/v0.0.1) on 2022-03-17).

I think **made by RedHat** alone meets the criteria.

> I can implement the app manifest.
Yes. Please.
