### ISSUE TITLE
[Request] add Raindrop.io

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Extras#8849]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [name of new package]
raindropio-desktop 
MIT License

**Description:** [clear and concise details of what it is]
All-in-one bookmark manager. Raindrop.io is the best place to keep all your favorite books, songs, articles or whatever else you come across while browsing.

**Homepage:** [a URL/link]
https://raindrop.io/

**Download link(s):** [URL(s)/link(s)]
https://github.com/raindropio/desktop/releases/download/v5.5.5/Raindrop.io-5.5.5-full.nupkg
https://github.com/raindropio/desktop/releases/download/v5.5.5/Raindrop.io-Setup-5.5.5.exe

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
https://github.com/raindropio/desktop
https://compile.blog/raindrop-io-review/
https://www.g2.com/products/raindrop-io/reviews
https://alternativeto.net/software/raindrop-io/about/
https://github.com/raindropio/app

**Comment by issaclin32** [comment]
implemented in #8862
