### ISSUE TITLE
[Request] Xplorer

### ISSUE THREAD

**Issue by SonaliBendre** [ScoopInstaller/Extras#8872]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [name of new package]
Xplorer
**Description:** [clear and concise details of what it is]
Cross-platform File Explorer.
Powered by the web
**Homepage:** [a URL/link]
https://xplorer.space/
**Download link(s):** [URL(s)/link(s)]
https://github.com/kimlimjustin/xplorer/releases
**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
2.4K

**Comment by SonaliBendre** [comment]
its our/their who wants to install it

**Comment by cjerrington** [comment]
While it's widely known, there isn't a stable version yet. That's still pretty important from a general software and Scoop's perspective.
