### ISSUE TITLE
[bug] RTSS and msiafterburner profiles are not separated for each users

### ISSUE THREAD

**Issue by Daviteusz** [ScoopInstaller/Extras#8909]
## Bug Report

**Package Name:** rtss, msiafterburner

### Current Behaviour

I have two users on my computer. After setting up RTSS and msiafterburner for my account, then when I log into the other account the settings are identical. 
This should not be the case, since the profiles are saved separately in C:/Users/-user-/scoop/presist/

### Expected Behaviour

RTSS profiles should be separate for each user

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:**

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  169

**Additional software:**

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-07-22T16:27:16.0807535+02:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}

```

**Comment by tech189** [comment]
That's odd, on my machine settings are being saved to persist and not outside my Scoop installation. Could you confirm that you are running two copies of Scoop, one in each users' home folder? I have before created a new user and continued using my old Scoop installation in the PATH without noticing. You can check with `Get-Command scoop` from both users to make sure they are different.

**Comment by Daviteusz** [comment]
I'll check it out.
