### ISSUE TITLE
Flyctl, Coder should be in main bucket?

### ISSUE THREAD

**Issue by kotx** [ScoopInstaller/Extras#8910]
`flyctl` (extras) is really similar to `railway` (main), both manage cloud resources on Fly.io and Railway respectively. It also fits the main bucket requirements. Therefore [`flyctl`](https://github.com/superfly/flyctl) should be in the main bucket.
Also seems to be true for [`coder`](https://github.com/coder/coder) as well.

**Comment by issaclin32** [comment]
I am fine with this change, but I want some opinions from other maintainers:
@rashil2000 @tech189

**Comment by rashil2000** [comment]
Thumbs up from me!

**Comment by tech189** [comment]
Fine by me!

**Comment by issaclin32** [comment]
Moved the packages:
https://github.com/ScoopInstaller/Extras/commit/6c94883622ff18dfdaf6dcff3eb775da6d304246
https://github.com/ScoopInstaller/Main/commit/34791996725dc6f1d7332806ecd420ed32327b62
