### ISSUE TITLE
[Request] add Pinta 

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Extras#8919]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [name of new package]
pinta (This requires innoup to extract the files.)

**Description:** [clear and concise details of what it is]
Simple and powerful image editing software. Very similar to Paint.NET
MIT X11 License

**Homepage:** [a URL/link]
https://www.pinta-project.com/

**Download link(s):** [URL(s)/link(s)]
https://github.com/PintaProject/Pinta/releases/download/2.0.2/Pinta.exe

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
https://alternativeto.net/software/pinta/about/
https://github.com/PintaProject/Pinta/
https://www.linuxinsider.com/story/75531.html
https://lifehacker.com/pinta-brings-paint-nets-just-enough-image-editing-to-ev-5467593

**Comment by issaclin32** [comment]
implemented in #8927
