### ISSUE TITLE
[Request] VokoscreenNG

### ISSUE THREAD

**Issue by joe733** [ScoopInstaller/Extras#8926]
## Package Requested: `vokoscreenNG`

- [X] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [X] the latest stable version of the program

### Information

**Name:** VokoscreenNG

**Description:**: A powerful screencast creator

**Homepage:** https://linuxecke.volkoh.de/vokoscreen/vokoscreen.html

**Download link(s):** https://github.com/vkohaupt/vokoscreenNG/releases

**Some indication of popularity/repute:**  [617 🌟 & counting](https://github.com/vkohaupt/vokoscreenNG) 

[![image](https://user-images.githubusercontent.com/38415384/180972656-7e1085ea-cd18-4198-a87f-d467a537c488.png)]( https://github.com/vkohaupt/vokoscreenNG)

**Comment by KrisSchneider** [comment]
Does anyone know what installer type this is? It's neither innosetup or dark.

**Comment by Zliced13** [comment]
Done in #9425
