### ISSUE TITLE
Visual C doesn't install

### ISSUE THREAD

**Issue by YSCohen** [ScoopInstaller/Extras#8930]
## Bug Report

**Package Name:** `visualc`

### Current Behaviour
```
PS ~ > scoop install visualc
Installing 'visualc' (16.00.30319.01) [64bit]
The remote server returned an error: (404) Not Found.
URL https://go.microsoft.com/fwlink/?LinkId=165122&clcid=0x409#/vs_expbsln_x64_enu.cab is not valid
```

### Expected Behaviour
It should install normally

### Additional context/output
[see above]

### Possible Solution
fix the url?

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.5

**Additional software:** N/A

#### Scoop Configuration

```json
{
  "lastupdate": "2022-07-26T10:32:25.8827299-04:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "aria2-enabled": false
}
```

**Comment by Lutra-Fs** [comment]
Duplicated, see #6905
