### ISSUE TITLE
VS Code not creating shim 

### ISSUE THREAD

**Issue by cjerrington** [ScoopInstaller/Extras#8938]
## Bug Report

**Package Name:** VS Code

### Current Behavior

After installing vscode with `scoop install vscode` it downloads and installs and copied my extensions from the regular install of VS Code from Microsoft and when launching VS Code and checking `scoop which vscode` I get the default launch location from the main proper install. When checking the `shims` folder there is no vscode shim. 

### Expected Behavior

install vscode from scoop, updates the install to copy current extension installs to scoop data dir, update shim to point the scoop install. When you run `scoop which code` it would refer the user to the scoop dir and not `C:\Program Files\Microsoft VS Code\bin\code.cmd`

### Additional context/output

Previously had VS Code installed from [https://code.visualstudio.com/](https://code.visualstudio.com/) and running. Installed VS Code from scoop which was also an update to the previous install. After the install from scoop I still can call `code` from a terminal and it brings up the install from https://code.visualstudio.com/ instead of scoop. 

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`] 
Same output from either PS 5.1 and 7.2.5

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      5

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-07-27T08:59:14.5184600-05:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}

```

**Comment by issaclin32** [comment]
`scoop which` will show other programs in PATH even if it is not installed with *Scoop*.

The [vscode package](https://github.com/ScoopInstaller/Extras/blob/master/bucket/vscode.json) only adds `$dir\bin` to PATH, which only contains `code.cmd`.

Therefore, if you still have the old installation (the one in `C:\Program Files\`) in your PATH, it is expected that `vscode` points to the old installation.

**Comment by cjerrington** [comment]
I see what was going on. `code` was found in the system PATH and the scoop was added to the user PATH. Windows loads the system PATH first then user PATH. After removing `C:\Program Files\Microsoft VS Code\bin` from my system PATH (`$ENV:PATH`) `scoop which code` pulls the right path now. 

I was under the impression after looking at the `scoop which` command it would browse the scoop dir first, then use the `Get-Command` module to find it elsewhere on the system.

**Comment by issaclin32** [comment]
Closing the issue because it is considered settled.
Feel free to **leave comment** / **open a new issue** if needed.
