### ISSUE TITLE
[Request] add Czawka GUI

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Extras#8940]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [name of new package]
czawka-gui

**Description:** [clear and concise details of what it is]
A GUI for czawka.

**Homepage:** [a URL/link]
https://github.com/qarmin/czkawka/

**Download link(s):** [URL(s)/link(s)]
https://github.com/qarmin/czkawka/releases/download/5.0.0/windows_czkawka_gui.zip

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
https://github.com/qarmin/czkawka/
https://www.slant.co/topics/1465/~best-software-tools-to-find-duplicate-files
https://www.ghacks.net/2021/05/28/find-duplicate-files-and-more-with-open-source-cross-platform-tool-czkawka/

**Comment by cjerrington** [comment]
This is what I have to get this started... Still learning how to get the `apppackage.json` files created

```json
{
    "version":  "5.0.0",
    "description" : "Multi functional app to find duplicates, empty folders, similar images etc. ",
    "license":  "MIT ",
    "extract_dir":  "",
    "url":  "https://github.com/qarmin/czkawka/releases/download/5.0.0/windows_czkawka_gui.zip",
    "depends":  "",
    "homepage":  "https://github.com/qarmin/czkawka",
    "hash":  "",
    "bin":  "czkawka_gui.exe"
}
```
