### ISSUE TITLE
adding extras bucket

### ISSUE THREAD

**Issue by Banana021s** [ScoopInstaller/Extras#8943]
guys I wanna add extras bucket but it doesn't work.  it only shows me (`checking repo...`). anybody can help me ?

**Comment by issaclin32** [comment]
Does this also happen to other buckets like *Nonportable*? (`scoop bucket add nonportable`)

**Comment by Banana021s** [comment]
yea I all the buckets

**Comment by issaclin32** [comment]
Try re-install *git* (and remove all settings by `-p`), and see if this solves the problem.
```
scoop uninstall git -p
scoop install git
```

I guess the problem is related to git's `ls-remote` command, but I'm not sure how to reproduce the problem.

**Comment by Banana021s** [comment]
thank u a lot, my problem fixed with this idea
