### ISSUE TITLE
ERROR 'anydesk' isn't installed correctly.

### ISSUE THREAD

**Issue by nothingbutlucas** [ScoopInstaller/Extras#8950]
#### Scoop Configuration

```json
{
    "lastupdate":  "2022-07-29T19:26:51.6019688-03:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

When I try to install anydesk it seems like the hashes are different:

```powershell
> scoop install anydesk
WARN  Purging previous failed installation of anydesk.
ERROR 'anydesk' isn't installed correctly.
Removing older version (7.0.10).
'anydesk' was uninstalled.
Installing 'anydesk' (7.0.10) [64bit]
AnyDesk.exe (3.7 MB) [========================================================================================] 100%
Checking hash of AnyDesk.exe ... ERROR Hash check failed!
App:         extras/anydesk
URL:         https://download.anydesk.com/AnyDesk.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    d7b9f1141c649c08254a4978f98211a5ab3b10591693fcf271409e36beae2933
Actual:      7c20393e638d2873153d2873f04464d4bad32a4d40eabb48d66608650f7d4494

Please try again or create a new issue by using the following link and paste your console output:
https:////
```

As the url of the output is not shown, I assume this is the place to generate this issue, otherwise, where should I generate it?

Thanks :)

**Comment by issaclin32** [comment]
Fixed by version update (https://github.com/ScoopInstaller/Extras/commit/155334e4890b3cf5c0f2c0b74700968da322eb9f)

The file URL for *AnyDesk* is `https://download.anydesk.com/AnyDesk.exe`. (does not contain any version info)
Therefore, when *AnyDesk* updates, *Scoop* need about 1-2 hours to catch up with the updates.

**Comment by nothingbutlucas** [comment]
Okey... but the installation keeps failing. Maybe it need a couple of days more?
