### ISSUE TITLE
Manifest 'autohotkey-installer' is removed from the Extra bucket

### ISSUE THREAD

**Issue by glloyd0314** [ScoopInstaller/Extras#8953]
## Bug Report

autohotkey-installer

### Current Behaviour

The manifest of Version 1.1.34.03 is removed for the Extra bucket.

### Expected Behaviour

Hope it could be back soon. I could not find any reason to remove it while the not-install version is still in the bucket.

### System details

Windows version: Windows 10 Pro 21H2 19044.1766

OS architecture: 64bit

PowerShell version: PowerShell 7.2.5

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-07-30T12:59:08.6594548+08:00",
  "proxy": "localhost:10809",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by issaclin32** [comment]
It has been moved to *Nonportable* bucket as `autohotkey-np`.
related discussions: https://github.com/ScoopInstaller/Extras/discussions/8936
