### ISSUE TITLE
[Request] EverythingToolbar

### ISSUE THREAD

**Issue by yenfeng-shetiko** [ScoopInstaller/Extras#8958]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [name of new package]
EveryToolbar
**Description:** [clear and concise details of what it is]
Everything integration for the Windows taskbar.
**Homepage:** [a URL/link]
https://github.com/stnkl/EverythingToolbar
**Download link(s):** [URL(s)/link(s)]
https://github.com/stnkl/EverythingToolbar/releases/download/0.7.4/EverythingToolbar-0.7.4.msi
**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
https://github.com/stnkl/EverythingToolbar/stargazers

**Comment by tech189** [comment]
There is a way to install it without admin rights ([here](https://github.com/stnkl/EverythingToolbar/wiki/Installation-per-user-(experimental))), but it's experimental and doesn't always work. If that's not okay then we should add the full installer to the non portable bucket.

**Comment by ppvnf** [comment]
Is there any update on this?

**Comment by ppvnf** [comment]
See discussion in https://github.com/ScoopInstaller/Nonportable/issues/88#issuecomment-1312605860

**Comment by yenfeng-shetiko** [comment]
> See discussion in [ScoopInstaller/Nonportable#88 (comment)](https://github.com/ScoopInstaller/Nonportable/issues/88#issuecomment-1312605860)

Thank you. I will close this window.
