### ISSUE TITLE
[Bug] Doesn't update apps like Sysinternals which uses date for versioning

### ISSUE THREAD

**Issue by RavenMacDaddy** [ScoopInstaller/Extras#8962]
#### Current Behavior
Doesn't update apps like Sysinternals which uses date for versioning.

#### Expected Behavior
Since running `scoop info sysinternals` does mention that a new version is available, as well as checking the corresponding bucket (extras) manually confirms this, I expect this is a bug isolated to the status/update functions of Scoop.

#### Additional context/output
![image](https://user-images.githubusercontent.com/67732686/182024618-fa3dc606-1f6f-4f73-b8ab-8358f4c4dcd9.png)

#### Possible Solution
I'm not sure since I'm currently not any form of programmer apart from creating manifests.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.5

**Additional software:** Can't think of any that could impact this function of Scoop.

#### Scoop Configuration

rootPath               : F:\Backup\Scoop
lastUpdate             : 2022-07-31 12:52:40
aria2-warning-enabled  : False
MSIEXTRACT_USE_LESSMSI : True
SCOOP_REPO             : https://github.com/ScoopInstaller/Scoop
SCOOP_BRANCH           : master

**Comment by rashil2000** [comment]
`script` field in the `checkver` of sysinternals can be added which will replace month name with month number.

**Comment by RavenMacDaddy** [comment]
Tried to wrap my head around doing that by reading the documentation, but wasn't able to.

Would you mind elaborating or making a PR that does it?
