### ISSUE TITLE
Scoop can't shim shell.exe for nilesoft-shell

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Extras#8971]
## Bug Report

**Package Name:** [name of package which has bug(s)]
nilesoft-shell

### Current Behaviour
Scoop can't shim "shell.exe" for nilesoft-shell. That is because the package from Nilesoft's website is now compressed used inno setup instead of using the standard .zip compression.

### Expected Behaviour
nilesoft-shell should install without any problems.

### Additional context/output
```
PS C:\Users\krist> scoop install nilesoft-shell -k
Installing 'nilesoft-shell' (1.7) [64bit]
WARN  Cache is being ignored.
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 9a715a|OK  |       0B/s|C:/Users/krist/scoop/cache/nilesoft-shell#1.7#https_nilesoft.org_download_shell.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of shell.zip ... ok.
Extracting shell.zip ... done.
Running pre_install script...
Linking ~\scoop\apps\nilesoft-shell\current => ~\scoop\apps\nilesoft-shell\1.7
Creating shim for 'shell'.
Can't shim 'shell.exe': File doesn't exist.
```
![(WindowsTerminal)I0W2r8_08-01-2022](https://user-images.githubusercontent.com/101912712/182278337-9b407c1f-d70c-4da8-bd3c-9f39236d8bbb.jpg)

### Possible Solution
In order to extract the package now, you have to use innoup or innoextract. 

InnoExtract has no problem extracting the files into a folder from the package with this command:
`innoextract -e "$home\Downloads\nilesoft-shell-1.7.exe" -d "$home\Downloads\nile"`
![(explorer)g2O5n2_08-01-2022](https://user-images.githubusercontent.com/101912712/182279289-778640ce-f4a8-4854-92eb-9fe2380cdbab.jpg)
![(%pn)-t0a5P7_08-01-2022](https://user-images.githubusercontent.com/101912712/182279404-b5471b8e-4e3c-4e10-b4f6-17b8edbfdb90.jpg)

innoup has a few problems when extracting the files in a folder from the package with this command:
```
cd "$home\Downloads";
innounp.exe -x "$home\Downloads\nilesoft-shell-1.7.exe" -dDIR -n;
```
![(explorer)i2d4n9_08-01-2022](https://user-images.githubusercontent.com/101912712/182279896-d1866e0d-1ae0-4a35-82a0-99bca10fff34.jpg)
![(explorer)N2d1a3_08-01-2022](https://user-images.githubusercontent.com/101912712/182280142-ef400b86-6d93-497e-be12-8dc7063b50e6.jpg)

### System details

**Windows version:** [e.g. 7, 8, 10]
10

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.5

**Additional software:** [(optional) e.g. ConEmu, Git]
git, gsudo, innoup, and innoextract.

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-08-01T20:42:06.7022635-06:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master",
    "aria2-warning-enabled":  false
}
```

**Comment by HUMORCE** [comment]
```
❯ innounp.exe -v .\nilesoft-shell-1.7.exe
; Version detected: 6100 (Unicode)
Size        Time              Filename
--------------------------------------
   1110240  2022.08.01 14:31  {app}\shell,1.dll
    273120  2022.08.01 14:31  {app}\shell,1.exe
   1138912  2022.08.01 14:31  {app}\shell,2.dll
    218848  2022.08.01 14:31  {app}\shell,2.exe
   1066208  2022.08.01 14:31  {app}\shell,3.dll
    285408  2022.08.01 14:31  {app}\shell,3.exe
     14993  2022.08.01 13:55  {app}\shell.shl
      1422  2022.08.01 14:03  {app}\readme.txt
      3356  2022.08.02 06:41  install_script.iss
--------------------------------------
```

shell,1.[dll|exe]: x86_64
shell,2.[dll|exe]: arm64
shell,3.[dll|exe]: x86
