### ISSUE TITLE
[Request] OpenTabletDriver

### ISSUE THREAD

**Issue by pynappo** [ScoopInstaller/Extras#8986]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program
 
### Information

**Name:** OpenTabletDriver

**Description:** OpenTabletDriver is an open source, cross-platform, low latency, user-mode tablet driver.

**Homepage:** https://opentabletdriver.net

**Download link(s):** https://github.com/OpenTabletDriver/OpenTabletDriver/releases/

**Some indication of popularity/repute:** 1.4k GitHub Stars, 200 Forks

I've made a Scoop manifest for this package that I already use. The program saves configuration/plugins under `$env:LOCALAPPDATA/OpenTabletDriver`.

**Comment by tech189** [comment]
Does this package require admin to install? If not, please send a PR for your manifest!

**Comment by pynappo** [comment]
It does not require admin, about to send a PR right now.
