### ISSUE TITLE
[Request] Komf

### ISSUE THREAD

**Issue by LazyGeniusMan** [ScoopInstaller/Extras#8997]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [ ] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** komf

**Description:**  Komga metadata fetcher 

**Homepage:** https://github.com/Snd-R/komf

**Download link(s):** https://github.com/Snd-R/komf/releases

**Some indication of popularity/repute:**
[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=Snd-R&repo=komf&show_owner=true)](https://github.com/Snd-R/komf)

### Notes
This is an app to fetch metadata for Komga. It's a 3rd party app but it's quite popular to be used with Komga, even Komga's official discord server have dedicated channel for this app. But right now the stats did not fulfill the requirement of 100 stars and 50 forks. Should I wait till it reach the requirement to add the app in this repo? or a companion app for popular app is excluded in the popularity requirement?

**Comment by KrisSchneider** [comment]
Created pull request #9264
