### ISSUE TITLE
gcloud: pre_install script: Cannot find path because it does not exist.

### ISSUE THREAD

**Issue by AntonOks** [ScoopInstaller/Extras#9026]
λ  scoop update gcloud
gcloud: 396.0.0 -> 397.0.0
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Updating one outdated app:
Updating 'gcloud' (396.0.0 -> 397.0.0)
Downloading new version
Loading google-cloud-sdk-397.0.0-windows-x86_64-bundled-python.zip from cache.
Checking hash of google-cloud-sdk-397.0.0-windows-x86_64-bundled-python.zip ... ok.
Uninstalling 'gcloud' (396.0.0)
Unlinking ~\scoop\apps\gcloud\current
Installing 'gcloud' (397.0.0) [64bit] from extras bucket
Loading google-cloud-sdk-397.0.0-windows-x86_64-bundled-python.zip from cache.
Running pre_install script...
ERROR Exit code was 2!
Move-Item:
Line |
   2 |  Move-Item "$dir\google-cloud-sdk\*" "$dir\" | Out-Null
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\<user>\scoop\apps\gcloud\397.0.0\google-cloud-sdk' because it does not exist.
Remove-Item:
Line |
   3 |  Remove-Item "$dir\google-cloud-sdk", "$dir\dl.zip_" -Force -Recurse
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\<user>\scoop\apps\gcloud\397.0.0\google-cloud-sdk' because it does not exist.
Linking ~\scoop\apps\gcloud\current => ~\scoop\apps\gcloud\397.0.0
Creating shim for 'gcloud'.
Can't shim 'bin\gcloud.cmd': File doesn't exist.

**Comment by issaclin32** [comment]
Thank you for reporting.
The problem is related to a recent update in Scoop Core (https://github.com/ScoopInstaller/Scoop/pull/5065).
I will search the bucket to see if there are more cases like this.
