### ISSUE TITLE
Scoop is not persisting PeaZip config in persist folder.

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Extras#9046]
## Bug Report

**Package Name:** [name of package which has bug(s)]

### Current Behaviour

Scoop is not persisting the config I set for PeaZip, resulting in PeaZip going back to the default config when it is updated by Scoop.

Where the peazip config should be stored in the Scoop folder:
![(explorer)g4X6P1_08-14-2022](https://user-images.githubusercontent.com/101912712/184554381-b71d57ec-71f2-4f80-b85d-40f5c91dc45b.jpg)

Where the peazip config is actually being stored in the Scoop folder:
![(explorer)20H8z5_08-14-2022](https://user-images.githubusercontent.com/101912712/184554765-60122faf-ec58-4cca-9b96-a3280b04e377.jpg)

### Expected Behaviour

When Scoop updates PeaZip it should keep the current config, not eliminate it. 

### Additional context/output

before update:
![(peazip)e624k3_08-14-2022](https://user-images.githubusercontent.com/101912712/184554403-fdf3b193-9fd4-4889-b4dc-326472a76b1d.jpg)

after update:
![(peazip)w5o5s6_08-14-2022](https://user-images.githubusercontent.com/101912712/184554407-65fc0441-6707-448e-b01b-d532204fd6e0.jpg)

the command I used to test this:
` scoop update peazip --force`
```
peazip: 8.7.0 -> 8.7.0
Updating one outdated app:
Updating 'peazip' (8.7.0 -> 8.7.0)
Downloading new version
Loading peazip_portable-8.7.0.WIN64.zip from cache.
Checking hash of peazip_portable-8.7.0.WIN64.zip ... ok.
Uninstalling 'peazip' (8.7.0)
Removing shim 'peazip.shim'.
Removing shim 'peazip.exe'.
Unlinking ~\scoop\apps\peazip\current
Installing 'peazip' (8.7.0) [64bit] from extras bucket
Loading peazip_portable-8.7.0.WIN64.zip from cache.
Extracting peazip_portable-8.7.0.WIN64.zip ... done.
Running pre_install script...
Linking ~\scoop\apps\peazip\current => ~\scoop\apps\peazip\8.7.0
Creating shim for 'peazip'.
Creating shortcut for PeaZip (peazip.exe)
Persisting res\altconf.txt
Persisting res\bookmarks.txt
Persisting res\conf.txt
Persisting res\conf-lastgood.txt
Persisting res\custedit.txt
'peazip' (8.7.0) was installed successfully!
```
![(WindowsTerminal)s4o7Z7_08-14-2022](https://user-images.githubusercontent.com/101912712/184554570-deb3a8e8-ec8c-44d3-bdb2-ce941e29dad4.jpg)

### System details

**Windows version:** [e.g. 7, 8, 10]
10

**OS architecture:** [e.g. 32bit, 64bit]
64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
7.2.6

**Additional software:** [(optional) e.g. ConEmu, Git]
gsudo, git, Windows Terminal.

#### Scoop Configuration

```json
{
  "lastUpdate": "2022-08-14T14:28:33.4755549-06:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "master",
  "aria2-warning-enabled": false
}
```

**Comment by issaclin32** [comment]
Thank you for reporting.

The problem is caused by that `res\altconf.txt` (and some other files) are not included in the first place in newer versions of *PeaZip*, so *Scoop* created it as a folder by default.

**Comment by KrisSchneider** [comment]
Oh, so that's why it did that, thank you fixing the package @issaclin32.
