### ISSUE TITLE
Installation of Miniconda3 does not take place properly

### ISSUE THREAD

**Issue by panospanousis** [ScoopInstaller/Extras#9060]
## Bug Report

**Miniconda 3:** 

### Current Behaviour

I am doing a fresh installation of miniconda 3 through scoop. I am using the the powershell prompt 5.1 and the command 
``` scoop install miniconda3 ```

The installation does not go wellas it opens the installation window and requires me to select the directory to install. I choose the folder miniconda within Scoop - Apps directory and it fails to perform shim. At the end the folder miniconda within scoop is empty and conda command cannot be used.
 
### Expected Behaviour

I the past when I used the same command 

```scoop install miniconda3```

I was never get to see the installation window and the installation was taking place within the directory scoop - Apps - miniconda.
Inside the miniconda folder I could see the existence of two folders current and 4.12.0 which contained the necessary files for conda to be available.

### Additional context/output

I have checked online about this issue, I found a correction with the quotes on the json file. However, the current json file that I have it is the corrected one. That issue and correction was reported back in 2018

### System details

**Windows 10:** 

**OS architecture: 64Bit** 

**PowerShell version: 5.1.19041.1682** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-08-17T10:10:19.9023727+02:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by TuanWorkMail** [comment]
Hi, I still encounter this issue, here is the terminal output:

Installing 'miniconda3' (4.12.0) [64bit] from extras bucket
Loading Miniconda3-py39_4.12.0-Windows-x86_64.exe from cache.
Checking hash of Miniconda3-py39_4.12.0-Windows-x86_64.exe ... ok.
Running installer...

At this point the installation dialog box popup and I have to choose an installation path

**Comment by issaclin32** [comment]
@TuanWorkMail I think your bucket might be failed to update.

Run:
(1) `scoop bucket rm extras`
(2) `scoop bucket add extras`
and install again to see if it works.

**Comment by TuanWorkMail** [comment]
It works!

I just reinstall Windows and because of Git's dubious ownership change, it prevent me to update scoop.
Change scoop directory owner to my new account, run scoop update and miniconda3 works

Thanks @issaclin32!
