### ISSUE TITLE
Some packages are failing auto update

### ISSUE THREAD

**Issue by shiena** [ScoopInstaller/Extras#9062]
## Bug Report

**Package Name:** goneovim

### Current Behaviour

v0.6.3 is released but auto update is failing.
https://github.com/ScoopInstaller/Extras/runs/7898685308?check_suite_focus=true#step:3:246

### Expected Behaviour

goneovim should be updated to v0.6.3

### Additional context/output

If you search the Excavator action log for `autoupdate available`, you will find more packages that failed to update.

**Comment by issaclin32** [comment]
The *Excavator* bot was being blocked for exceeding number of connections.
It is working fine now (https://github.com/ScoopInstaller/Extras/commit/7601fe1a547212252cf567ebc07f5437e0ea1715)
