### ISSUE TITLE
[Request] add 7TSP

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Extras#9065]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [name of new package]
7tsp 

**Author:** 
devillnside

**License:** 
Freeware | Proprietary

**Description:** [clear and concise details of what it is]
A Portable Program that allows for easy theme changing on Windows 7-11.

**Homepage:** [a URL/link]
https://www.deviantart.com/devillnside/art/7TSP-GUI-2019-Edition-804769422

**Download link(s):** [URL(s)/link(s)]
https://wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d73ee700-e53d-4b03-88b3-033ae11157f0/ddb5026-538eb731-5ad1-4af9-8489-d8e54e94e62d.zip?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImV4cCI6MTY2MDg2NTEwNSwiaWF0IjoxNjYwODY0NDk1LCJqdGkiOiI2MmZlYzdmOTNjZjdjIiwib2JqIjpbW3sicGF0aCI6IlwvZlwvZDczZWU3MDAtZTUzZC00YjAzLTg4YjMtMDMzYWUxMTE1N2YwXC9kZGI1MDI2LTUzOGViNzMxLTVhZDEtNGFmOS04NDg5LWQ4ZTU0ZTk0ZTYyZC56aXAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.xSwgSDOPh1MB8nlZqmiWZIM5r1YQWeJxlZg1ZHmPyPo&filename=7tsp_gui_2019_edition_by_devillnside_ddb5026.zip

https://www.droidmirror.com/download/7tsp-gui-v0-6-zip   
https://skinpacks.com/7tsp-gui-2019-edition/ 
http://www.filefacts.com/se7en-theme-source-patcher-info 
https://vsthemes.org/en/software/3022-7tsp.html 

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]\
https://zetamods.com/7tsp-change-windows-10-icons/
https://www.deviantart.com/devillnside/art/7TSP-GUI-2019-Edition-804769422
https://7tsp-build.software.informer.com/0.4/
https://vsthemes.org/en/software/3022-7tsp.html
https://www.makeuseof.com/how-to-make-windows-10-look-like-windows-11/

**Comment by issaclin32** [comment]
implemented in https://github.com/ScoopInstaller/Extras/commit/ca8034c1ee75e590c4f14c43ab901f9407756f20
