### ISSUE TITLE
[Request] Legendary

### ISSUE THREAD

**Issue by Aziks0** [ScoopInstaller/Extras#9070]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Legendary

**Description:** Legendary is a free and open-source replacement for the Epic Games Launcher

**Homepage:** https://github.com/derrod/legendary

**Download link(s):** https://github.com/derrod/legendary/releases

**Some indication of popularity/repute:**

[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=derrod&repo=legendary&show_owner=true)](https://github.com/derrod/legendary)

**Comment by thefexcos791** [comment]
![image](https://user-images.githubusercontent.com/108440782/185773425-10158176-9c3d-457c-a7a9-49fa7f4a3596.png)
It's already in the games bucket, with this now it's even double

**Comment by issaclin32** [comment]
> It's already in the games bucket, with this now it's even double

Oh. Forgot to check that first. Thank you for reminding.

**Comment by Aziks0** [comment]
Oops. I did not know that a "games" bucket existed 😅. Sorry for that!
