### ISSUE TITLE
filezilla@3.60.2: download via aria2 failed

### ISSUE THREAD

**Issue by Suyu6** [ScoopInstaller/Extras#9075]
#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by issaclin32** [comment]
The file is accessible now. Looks like a site issue.

Feel free to open a new issue / leave comment if needed.

**Comment by Suyu6** [comment]
> The file is accessible now. Looks like a site issue.
> 
> Feel free to open a new issue / leave comment if needed.

![image](https://user-images.githubusercontent.com/64906597/185824552-5aee0d68-a27b-4d6b-a68e-a12b0c647ffc.png)
