### ISSUE TITLE
[Bug] - URL is not valid

### ISSUE THREAD

**Issue by nixeo** [ScoopInstaller/Extras#9077]
Installing 'so' (0.4.7) [64bit] from extras bucket
The remote server returned an error: (404) Not Found.
URL https://github.com/samtay/so/releases/download/v0.4.7/so-v0.4.7-x86_64-pc-windows-msvc.zip is not valid

Valid link:
https://github.com/samtay/so/releases/download/v0.4.7/so-x86_64-pc-windows-msvc.zip

**Comment by rashil2000** [comment]
Can you make a PR for the fix?

**Comment by ViCrack** [comment]
> Can you make a PR for the fix?

I can fix it.
