### ISSUE TITLE
mousejiggler

### ISSUE THREAD

**Issue by VioletFlare** [ScoopInstaller/Extras#9087]
## Bug Report

**Package Name:** mousejiggler

### Current Behaviour

The url in mousejiggler.json

https://github.com/cerebrate/mousejiggler/releases/download/1.8.42/mousejiggler-1.8.42-net.zip

doesn't work anymore

### Expected Behaviour

-

### Additional context/output

-

### Possible Solution

The url should be updated.

### System details

**Windows version:** 10

**OS architecture:** 64

**PowerShell version:** -

**Additional software:** -

#### Scoop Configuration

```json
//# -
```

**Comment by tech189** [comment]
The URL seems fine to me, does it work for you now? It might have been temporarily unavailable.

**Comment by VioletFlare** [comment]
Sorry, it's probably caused by the dumb network policies in the environment I work in. I thought it was just this URL but it appears everything else from the repository gets 403.

**Comment by tech189** [comment]
Ah, no worries!
