### ISSUE TITLE
Filezilla installation return a 403 Forbidden error

### ISSUE THREAD

**Issue by Manukineko** [ScoopInstaller/Extras#9088]
## Bug Report

**Filezilla:**

### Current Behaviour

1 - `scoop install filezilla`
2 - The link to the zip file is right but Scoop return a 403 Forbidden error
![Filezilla403Error](https://user-images.githubusercontent.com/43104858/186348720-789bd15b-1ac8-4908-92d7-5701d446c819.png)

### Expected Behaviour

Filezilla can be installed

### Additional context/output

1 - Maybe similar to issue #9075 3 days ago
2 - Clicking the link open the web browser and the file can be downloaded
![FilezillaFileIsAvailable](https://user-images.githubusercontent.com/43104858/186349468-9c2471b3-70bc-450a-8254-c834878ab52d.png)

#### Scoop Configuration
Scoop is up-to-date as well as the Extras bucket.
No issue with other package.

**Comment by noirotm** [comment]
I'm encountering the same issue on running `scoop update --all`:

![image](https://user-images.githubusercontent.com/280166/186370970-580928ae-be5f-44fe-9bf5-a873b86788d9.png)

This stops the update completely and exits scoop which prevents other apps from updating unless doing so one by one.

**Comment by ViCrack** [comment]
Maybe need have an option in the scoop manifest to change the user-agent download header

**Comment by Lovecrafts-Cat** [comment]
Same issue here, reporting to bring attention to this.
