### ISSUE TITLE
gcc-arm-none-eabi: package outdated

### ISSUE THREAD

**Issue by diggit** [ScoopInstaller/Extras#9091]
**Package Name:** gcc-arm-none-eabi

Arm changed their toolchain naming convention and thus broke checkver version extraction and autoupdate.
prev: `gcc-arm-11.2-2022.02-mingw-w64-i686-arm-none-eabi.zip`
now: `arm-gnu-toolchain-11.3.rel1-mingw-w64-i686-arm-none-eabi.zip`

**Comment by tech189** [comment]
I updated it just now, let me know if it's all correct.

**Comment by diggit** [comment]
Tested right now and works well. Thank you!
