### ISSUE TITLE
[Request] Setup script for MPV so it can be used as a default app on Windows 10/11

### ISSUE THREAD

**Issue by DanyGee** [ScoopInstaller/Extras#9135]
## Bug Report

**Package Name:** mpv

### Current Behaviour

After selecting the mpv.exe from scoop folder as a default app for a video file, windows does not register it.

### Expected Behaviour

After selecting the mpv.exe from scoop folder as a default app for a video file, windows should register it and open mpv when running a supported video file.

### Additional context/output
![bitmoji](https://sdk.bitmoji.com/render/panel/35115333-7f99-467c-9705-d3ae6929374a-745f69d2-472f-42b3-b658-d9cc54437208-v1.png?transparent=1&palette=1&width=246)

### Possible Solution
Setup script? (saw a similar issue with irfanview and the solution was to request a setup script)

### System details

**Windows version:** 10 and 11

**OS architecture:** 64 bit

**PowerShell version:**
Major | Minor | Build | Revision
5        | 1         | 22000 | 832

**Additional software:** git

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-08-30T10:00:53.8572495+02:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by Valinor** [comment]
Not reproductible here. After selecting the mpv.exe from scoop folder as a default app for a video file, windows register it.

![image](https://user-images.githubusercontent.com/2079654/187898589-8f828239-40c3-43ca-b66a-be734d183c90.png)

![image](https://user-images.githubusercontent.com/2079654/187898736-fef24405-e0d7-428f-83fe-594c5479829a.png)

Maybe you select the wrong mpv, mpv.exe work here.
I'm not seeing  any special script in irfanview. Can you point me this past issues?

**Comment by DanyGee** [comment]
I'm sure I've selected the proper one.
Maybe it conflicts with [previous mpv version's](https://sourceforge.net/projects/mpv-player-windows/files/) assignments to video files (upon installation)?
Maybe uninstalling the other version wasn't enough?
I don't know how hacky is this automatic assignement of filetypes there.

And this was the hint from irfanview:
https://github.com/ScoopInstaller/Scoop/issues/4252

**Comment by tech189** [comment]
I'm not sure there's any need for an installation script. I am able to set mpv as the default video player using the following steps:

- `scoop install mpv`
- Right click a .mp4 video, press Open with > Choose another app
- Scroll down to More apps and then press Look for another app on this PC
- Navigate to your Scoop installation folder and go to apps > mpv > current (NOT any other version)
- Select mpv.exe, the video will play in mpv
- Then right click the video again, press Open with > Choose another app
- Select mpv and tick the box Always use this app to open .mp4 files
- Press OK
- Now all .mp4 videos will automatically open in mpv

**Comment by DanyGee** [comment]
My current non scoop assignment.
Renamed MPV folder to break it and set the new one for scoop mpv:
![image](https://user-images.githubusercontent.com/26818551/188106676-9f13d84f-3138-4a59-aedf-8a556bbd9208.png)

I follow the steps to choose another app, select the mpv.exe from C:\Users\MYUSER\scoop\apps\mpv\current and system does not start the video, neither creates new assignment = just shows the app select dialog again.

**Comment by tech189** [comment]
That's odd, I'm using Windows 11 too. Could you try setting it to Movies & TV first and then back to scoop\apps\mpv\current\mpv.exe?

If that doesn't work, can you try Settings > Apps > Default apps > Search for .mp4 in file type box at the top > choose mpv.exe?

**Comment by DanyGee** [comment]
Both tricks didn't change anything.

**Comment by tech189** [comment]
Here's a reg file that should fix your problem:

```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\.mp4]
@="scoop-mpv"

[HKEY_CURRENT_USER\Software\Classes\scoop-mpv]
@="MP4 File"

[HKEY_CURRENT_USER\Software\Classes\scoop-mpv\DefaultIcon]
@="C:\\Users\\<username-goes-here>\\scoop\\apps\\mpv\\current\\mpv.exe,0"

[HKEY_CURRENT_USER\Software\Classes\scoop-mpv\shell]

[HKEY_CURRENT_USER\Software\Classes\scoop-mpv\shell\open]

[HKEY_CURRENT_USER\Software\Classes\scoop-mpv\shell\open\command]
@="\"C:\\Users\\<username-goes-here>\\scoop\\apps\\mpv\\current\\mpv.exe\" \"%1\""
```

After filling in your username/location of scoop, save this to a file with a `.reg` extension and run it to add it to the registry. See if that makes mpv show up in the Open with > Choose another app menu.

If not, this program [SetUserFTA](https://kolbi.cz/blog/2017/10/25/setuserfta-userchoice-hash-defeated-set-file-type-associations-per-user/) is very useful and can set a default app for a given file extension and ProgId (the first part of the reg file). Someone made a Scoop manifest which you can use [by adding their bucket and running `scoop install setuserfta`](https://scoop.sh/#/apps?q=setuserfta&s=0&d=1&o=false). Then finally you can run `SetUserFTA .mp4 scoop-mpv`.

That should immediately take effect. The icon will load after restarting File Explorer. Let me know if it works for you.

**Comment by DanyGee** [comment]
Sorry for the late response.
Adding reg keys did not help.
**But SetUserFTA did.**
Thank you!

**Comment by tech189** [comment]
Excellent! Just to let you know if you need to set it up again, add the reg files first then run the SetUserFTA command. It requires the above reg values to be set as it refers to the Software Class `scoop-mpv`.

**Comment by electronicdreamer** [comment]
I had this problem too and couldn't find any way to fix it. setuserfta was possibly a solution but I couldn't for the life of me find which progid to use.

So I just completely uninstalled the scoop version of mpv and got one of the shinchiro builds. It works flawlessly and can now set it as default. Weird :/
