### ISSUE TITLE
[Request] notepads

### ISSUE THREAD

**Issue by SiyuChen** [ScoopInstaller/Extras#9136]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** notepads

**Description:** A modern, lightweight text editor with a minimalist design.

**Homepage:** [www.notepadsapp.com](https://www.notepadsapp.com/)

**Download link(s):** https://github.com/0x7c13/Notepads/releases

**Some indication of popularity/repute:** 6.7k GitHub star

**Comment by rasa** [comment]
The Non-portable bucket already has this app [here](https://github.com/ScoopInstaller/Nonportable/blob/master/bucket/notepads-np.json), so I am going to close this, but feel free to reopen if I am misinterpreting your request.
