### ISSUE TITLE
filezilla@3.60.2: Error and retry loop

### ISSUE THREAD

**Issue by mathijshenquet** [ScoopInstaller/Extras#9164]
## Bug Report

**Package Name:** filezilla

### Current Behaviour

Install with `scoop install filezilla` from `extras` bucket fails with an error and then enters an indefinitely long retry loop.

See additional output for more info.

### Expected Behaviour

_n/a_

### Additional context/output

````
Installing 'filezilla' (3.60.2) [64bit] from extras bucket
Loading dummy.txt from cache
Checking hash of dummy.txt ... ok.
Running pre_install script...
Running installer script...
WARN  Downloading FileZilla...
Invoke-WebRequest:
Line |
  10 |      Invoke-WebRequest $url -OutFile "$dir\dl.zip" -UserAgent $userage …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
WARN  Checking file integrity...

ERROR: The system cannot find the file specified.
~\scoop\apps\filezilla\3.60.2\dl.zip



System ERROR:
The system cannot find the file specified.
WARN  File check failed. Retrying
WARN  Downloading FileZilla...
[...]
WARN  File check failed. Retrying
WARN  Downloading FileZilla...
[...etc...]
````

### Possible Solution

Looking at the errors it looks like the mirror is not responding.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.6

**Additional software:** -

#### Scoop Configuration

```json
{
  "lastupdate": "2022-09-05T09:42:05.5114999+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by mathijshenquet** [comment]
NB: I see there is some retry logic in [filezilla.json](https://github.com/ScoopInstaller/Extras/blob/master/bucket/filezilla.json) with 5 retry attempts. The retry loop of the bug report is at least much longer than this.

**Comment by mathijshenquet** [comment]
It turns out that the mirror is down causing the retry loop. The loop is infinite because the retry logic is incorrect.

````
if ($retry_count > 5) { error 'Could not download the installer. The network might be unstable.'; break }",
````

the should be `5 -le $retry_count`

**Comment by issaclin32** [comment]
Thank you for reporting.

It looks like *FileZilla* has put more strict restrictions on user-agent, which is causing the download to fail.

I updated the user-agent in https://github.com/ScoopInstaller/Extras/commit/b18828c3f71ad65f0340bb35e6c484bd0e6be806.
