### ISSUE TITLE
Filezilla: Abuse of third-party infrastructure

### ISSUE THREAD

**Issue by codesquid** [ScoopInstaller/Extras#9179]
Hello,

the Scoop Installer is abusing the infrastructure at https://filezilla-project.org/ or one of its subdomains. Our infrastructure is meant to be used only by humans and FileZilla itself, not third-party installers. The Scoop installer is even using fake user agents to circumvent abuse prevention.

If you want to re-distribute FileZilla using scoop, you absolutely must host the binaries on your own infrastructure.
For redistribution, please take note of https://filezilla-project.org/license.php and https://filezilla-project.org/trademark_policy.php

Regards,
Tim Kosse

**Comment by rashil2000** [comment]
Hi Tim! 

Thanks for letting us know directly. Unfortunately, Scoop does not have any server or storage hosting infra (it is entirely community driven and unfunded). For small packages, we utilize GitHub's repo storage itself, here https://github.com/ScoopInstaller/Binary. We will see if we can put up Filezilla there for Scoop's usage. 

/cc @issaclin32 


Relevant manifest: https://github.com/ScoopInstaller/Extras/blob/master/bucket/filezilla.json

**Comment by issaclin32** [comment]
Thank you for reminding us.

I updated the package to use https://github.com/ScoopInstaller/Binary as file source, so that Scoop Installer will not download from https://filezilla-project.org/ anymore.
