### ISSUE TITLE
The description of this app should be changed to avoid confusion with hibit-uninstaller.

### ISSUE THREAD

**Issue by KrisSchneider** [ScoopInstaller/Extras#9216]
### Discussed in https://github.com/ScoopInstaller/Extras/discussions/9215

<div type='discussions-op-text'>

<sup>Originally posted by **KrisSchneider** September 10, 2022</sup>
https://github.com/ScoopInstaller/Extras/blob/b8c529beb093b55524052881f6b618513fc86295/bucket/hibit-system-information.json#L3</div>

**Comment by issaclin32** [comment]
Sorry, I did not check carefully. Thank you for reminding.

I removed the discussion #9215 since the problem has been solved.

**Comment by KrisSchneider** [comment]
> Sorry, I did not check carefully. Thank you for reminding.
> 
> I removed the discussion #9215 since the problem has been solved.

Your welcome ☺!
