### ISSUE TITLE
Telegram@4.1.1: No URL Protocol handler for tg://

### ISSUE THREAD

**Issue by H-Tung** [ScoopInstaller/Extras#9244]
## Bug Report

**Package Name:** Telegram

### Current Behaviour

No response when open `tg://` link in browser as there's no protocol handler.

### Possible Solution

I added the registry myself, but unable to write the scripts. Here's the export for .reg.

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\tg]
@="URL:tg protocol"
"URL Protocol"=""

[HKEY_CURRENT_USER\SOFTWARE\Classes\tg\DefaultIcon]
@="Telegram.exe"

[HKEY_CURRENT_USER\SOFTWARE\Classes\tg\Shell]

[HKEY_CURRENT_USER\SOFTWARE\Classes\tg\Shell\Open]

[HKEY_CURRENT_USER\SOFTWARE\Classes\tg\Shell\Open\Command]
@="\"$SCOOP\\apps\\telegram\\current\\Telegram.exe\" -- \"%1\""
```
### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.6

**Comment by Zliced13** [comment]
Should this registry protocol also be added for the telegram forks as well. @HUMORCE  @H-Tung

**Comment by Zliced13** [comment]
Also, sorry for the necro posting.

**Comment by HUMORCE** [comment]
Make it an option.
