### ISSUE TITLE
renpy@8.0.3: hash check failed

### ISSUE THREAD

**Issue by CO-2** [ScoopInstaller/Extras#9245]
ERROR Hash check failed!
App:         extras/renpy
URL:         https://www.renpy.org/dl/8.0.3/renpy-8.0.3-sdk.7z.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    a51808b980ff1a972003a42efb6812c3b021f70ea374b84b714dc8f4f10e06e0
Actual:      ca2e66a886b80a3533281ca6b9ae7f1c3caa04baa1b9cd2bd592b4c3c7fab09a

**Comment by DECEMBERFL0WER** [comment]
I'm experiencing the same error, with the exact same output.

My Scoop configuration:

```json
{
    "lastUpdate":  "2022-09-19T00:17:10.3035704+02:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```
