### ISSUE TITLE
vcredist-2010 post install script runs indefinitely

### ISSUE THREAD

**Issue by lripoche** [ScoopInstaller/Extras#9247]
## Bug Report

**Package Name:** vcredist

### Current Behaviour

vcredist-2010 post-install script runs indefinitely. 

While trying to install vcredist through scoop : 
```
Installing 'vcredist2010' (10.0.40219.473) [64bit] from extras bucket
Starting download with aria2 ...
Download: Download Results:                                           B(55%)]
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 1114fb|OK  |   5.4MiB/s|C:/Users/ContainerAdministrator/scoop/cache/vcredist2010#10.0.40219.473#https_download.microsoft.com_download_E_E_0_EE05C9EF-A661-4D9E-BCE2-6961ECDF087F_vcredist_x86.exe
Download: 07c96a|OK  |   5.1MiB/s|C:/Users/ContainerAdministrator/scoop/cache/vcredist2010#10.0.40219.473#https_download.microsoft.com_download_E_E_0_EE05C9EF-A661-4D9E-BCE2-6961ECDF087F_vcredist_x64.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of vcredist_x64.exe ... ok.
Checking hash of vcredist_x86.exe ... ok.
Linking C:\ProgramData\scoop\apps\vcredist2010\current => C:\ProgramData\scoop\apps\vcredist2010\10.0.40219.473
Running post_install script...
# => never ends
```

#### Steps to Reproduce

1. Create following dockerfile
```
FROM mcr.microsoft.com/windows/servercore:ltsc2019

SHELL ["powershell"]
RUN Set-ExecutionPolicy RemoteSigned -scope CurrentUser
RUN irm get.scoop.sh -outfile 'install.ps1'
RUN .\install.ps1 -RunAsAdmin
RUN scoop install --global aria2 git
RUN scoop bucket add extras
RUN scoop install --global vcredist
```
2. Ensure that your docker desktop is running on windows containers (Right click on Docker Desktop service icon > Switch to Windows containers)
3. Build it: `docker build --no-cache .`

### Expected Behaviour

`scoop install --global vcredist` should install all versions of vcredist correclty. 

### Additional context/output

This bug only occurs in a windows servercore docker container, could not reproduce it on my windows 11 pro laptop. 

### System details

* **VcRedist Package Version**: 14.32.31332.0
* **VcRedist 2010 Version**: 10.0.40219.473
* **PowerShell Version**: 5.1.22000.832
* **Operating System**: Microsoft Windows 11 Pro 10.0.22000 Build 22000
* **Docker Desktop Version**: 4.12.0

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-09-16T14:26:09.6847310+02:00" 
}
```

**Comment by HUMORCE** [comment]
show GUI when install the manifest on VM(win 10 LTSC 2021) with powershell 5.1

**Comment by smathema** [comment]
same here, when installing `scoop install -g vcredist` I see that the installation is stuck at `Microsoft Visual C++ x64 Redistributable Setup` as shown under `Processes` tab and `vcredist_x64.exe` under `Details` tab of a Task Manager, and as soon as I kill that process everything run normal.

please let know if there is a workaround or a solution to this issue

**Comment by smathema** [comment]
on checking the vcredist2010 install configuration file `https://github.com/ScoopInstaller/Extras/blob/master/bucket/vcredist2010.json`, found that the configuration needs to change the "post_install" commands to use `/q` instead of `/quite`

replicating solution:
1. download vcredist 2010 x64: https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe
2. open powershell as admin and change working directory to when the file was downloaded
3. FAILURE: when installing using command:  `.\vcredist_x64.exe /fo /quite /norestart`, this opens up a user interface, which is why it is getting stuck
4. SUCCESS: when installing using command: `.\vcredist_x64.exe /fo /q /norestart`

**Comment by HUMORCE** [comment]
> 3. FAILURE: when installing using command: .\vcredist_x64.exe /fo /quite /norestart, this opens up a user interface, which is why it is getting stuck
> 4. SUCCESS: when installing using command: .\vcredist_x64.exe /fo /q /norestart

typo in step 3

`/quiet` == `/q` != `/quite`

I was switch back to `Start-Process` to resolve this issue for now.
