### ISSUE TITLE
[Request] authme

### ISSUE THREAD

**Issue by dtantono** [ScoopInstaller/Extras#9253]
Package Request Information
Name: Authme

Description: an authenticator app

Homepage: https://authme.levminer.com/#downloads or https://github.com/Levminer/authme

Download link(s): https://github.com/Levminer/authme/releases/download/3.3.4/authme-3.3.4-windows-x64-installer.exe

PS: Github 70 stars

**Comment by KrisSchneider** [comment]
Created pull request #9265
