### ISSUE TITLE
[Request] shell 

### ISSUE THREAD

**Issue by sayeed205** [ScoopInstaller/Extras#9275]
### Information

**Name:** [name of new package]

**Description:** [clear and concise details of what it is]

**Homepage:** https://nilesoft.org/

**Download link(s):** https://nilesoft.org/download

**Some indication of popularity/repute:** 120+ Stars on GitHub

**Comment by KrisSchneider** [comment]
It's already added in scoop.
https://scoop.sh/#/apps?q=nilesoft&s=2&d=1&o=true

**Comment by sayeed205** [comment]
> It's already added in scoop. https://scoop.sh/#/apps?q=nilesoft&s=2&d=1&o=true

Aah sorry. Didn't notice that.
