### ISSUE TITLE
[Request] Nvy

### ISSUE THREAD

**Issue by RMichelsen** [ScoopInstaller/Extras#9277]
### Information

**Name:** Nvy

**Description:** Nvy is a minimal [Neovim](https://neovim.io/) client for Windows written in C++

**Homepage:** [https://github.com/RMichelsen/Nvy](https://github.com/RMichelsen/Nvy)

**Download link(s):** [https://github.com/RMichelsen/Nvy/releases/download/v0.3.2/Nvy.exe](https://github.com/RMichelsen/Nvy/releases/download/v0.3.2/Nvy.exe)

**Some indication of popularity/repute:** 169 Stars and 10+ forks

**Comment by tan-wei** [comment]
Great if merged.
