### ISSUE TITLE
[Request] Sidekick

### ISSUE THREAD

**Issue by SiyuChen** [ScoopInstaller/Extras#9294]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Sidekick

**Description:** Sidekick is designed for the ultimate online work experience and brings together every web tool you use.

**Homepage:** https://www.meetsidekick.com/

**Download link(s):** https://www.meetsidekick.com/download/

**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]

**Comment by KrisSchneider** [comment]
Done in #9317
