### ISSUE TITLE
Renamer‘s persets is not in the persist.

### ISSUE THREAD

**Issue by CronusLM** [ScoopInstaller/Extras#9312]
## Bug Report

**Package Name:** [renamer]

### Current Behaviour

Renamer‘s persets is not in the persist.

### Expected Behaviour

Add the Renamer‘s persets to persist.

### System details

**Windows version:** 10

**OS architecture:** 64bit
**PowerShell version:** 
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682

#### Scoop Configuration
```json
{
    "lastUpdate":  "2022-09-24T22:06:57.0886998+08:00",
    "SCOOP_REPO":  "https://ssh.fastgit.org/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master",
    "aria2-warning-enabled":  false,
    "aria2-enabled":  false
}
```

**Comment by KrisSchneider** [comment]
Fixed in #9315
