### ISSUE TITLE
dbvis out of date

### ISSUE THREAD

**Issue by gort08** [ScoopInstaller/Extras#9313]
## Bug Report

dbvis

### Current Behaviour

dbvis version is 13.0.5

### Expected Behaviour

Latest version is Version 14.0 (released on 2022-09-20)

### Additional context/output

Support for 32bit architecture dropped in 14.0. Seems to be causing the autoupdate to fail.

https://www.dbvis.com/releasenotes/

**Comment by KrisSchneider** [comment]
While this manifest is getting fixed. Try some alternative software like **dbeaver** or **heidisql**.
