### ISSUE TITLE
[Request]  Ludwig

### ISSUE THREAD

**Issue by SiyuChen** [ScoopInstaller/Extras#9326]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Ludwig 

**Description:** Ludwig is a unique search engine that helps you find the right English sentences and to feel more confident about it!

**Homepage:** https://ludwig.guru

**Download link(s):** https://ludwig.guru/download

**Comment by KrisSchneider** [comment]
Done in #9340
