### ISSUE TITLE
[Request] add Antares

### ISSUE THREAD

**Issue by yabbal** [ScoopInstaller/Extras#9328]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [X] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [X] the latest stable version of the program

### Information

**Name:** Antares SQL

**Description:** Antares is an SQL client based on [Electron.js](https://github.com/electron/electron) and [Vue.js](https://github.com/vuejs/vue)

**Homepage:** https://antares-sql.app/

**Download link(s):** https://antares-sql.app/downloads/

**Some indication of popularity/repute:** 783 ⭐and 58 forks

**Comment by KrisSchneider** [comment]
@AbbalYouness Do you mind renaming your issue to:
### **[Request] add Antares**

This is to avoid confusing with other issues in the future.
