### ISSUE TITLE
calibre installation is confusing

### ISSUE THREAD

**Issue by Siddhant** [ScoopInstaller/Extras#9331]
## Bug Report

calibre and calibre-normal

### Current Behaviour

I get two results for "calibre", both same versions. Which one should I really install?

```
> scoop search calibre
Results from local buckets...

Name           Version Source Binaries
----           ------- ------ --------
calibre-normal 6.5.0   extras
calibre        6.5.0   extras
```

### Expected Behaviour

Can scoop help in some way on selecting the "right" calibre to install? The suffix "-normal" doesn't really help. It isn't obvious (at least to me) which one to select.

### Possible Solution

Not sure. I checked the calibre website to see if they have two types of calibre, but they don't.

Maybe add a column to the search result, say "Comment", to help the user decide?

### System details

**Windows version:** 8 

**OS architecture:**  64bit

**PowerShell version:** 5.1.19041.1682

**Additional software:** none

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-09-26T11:40:59.6230672+05:30",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by KrisSchneider** [comment]
`calibre-normal` is the same as `calibre`. The only difference is `calibre` stores it's settings in the same folder as the executable. And `calibre-normal` stores it's settings in "~\AppData\Roaming\calibre". 

Links to the app manifests: 
https://github.com/ScoopInstaller/Extras/blob/master/bucket/calibre.json
https://github.com/ScoopInstaller/Extras/blob/master/bucket/calibre-normal.json
