### ISSUE TITLE
[Request]  Add openElement

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#9337]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [openElement]

**Description:** [WEBSITE EDITOR WITH TOTAL CONTROL
MODIFY ANY ELEMENT AND STYLE THE WAY YOU WANT]

**Homepage:** [https://openelement.uk/index.htm]

**Download link(s):** [https://openelement.uk/Download.htm]

**Some indication of popularity/repute:** [Cannot find it like that]

**Comment by KrisSchneider** [comment]
Does anyone know what the installer type is? It's neither an innosetup nor a wixburn installer.

**Comment by ViCrack** [comment]
It's an `Advanced Installer`

`openElement.exe  /extract`

**Comment by KrisSchneider** [comment]
@ViCrack Thank you. Also, I found out scoop has a program that allows for the extraction of files from `Advanced Installer` installers, it's called `uniextract2`.

**Comment by ViCrack** [comment]
@KrisSchneider 

 As usual with ` /extract:`, uniextract2 is unnecessary.

![11](https://user-images.githubusercontent.com/18179821/192525873-359250ca-53f8-4e97-8c78-1c94c727b3ba.png)
![22](https://user-images.githubusercontent.com/18179821/192525985-a8dbb05f-4271-4ee9-80d0-751a9ee532c4.png)

**Comment by KrisSchneider** [comment]
@ViCrack You are right. Uniextract2 isn't needed. I found I could just use this command instead:
`Start-Process "$home\Downloads\openElement.exe" -Wait -WindowStyle Hidden -ArgumentList @('/extract', '/exenoui')`

**Comment by anderlli0053** [comment]
Closing as per #9346

**Comment by anderlli0053** [comment]
Also, thank you @KrisSchneider @ViCrack

**Comment by KrisSchneider** [comment]
Don't close the issue just yet,

**Comment by KrisSchneider** [comment]
@anderlli0053 Also, your welcome.
