### ISSUE TITLE
[Request] ContextMenuForWindows11

### ISSUE THREAD

**Issue by ppvnf** [ScoopInstaller/Extras#9348]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [X] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [X] the latest stable version of the program

### Information

**Name:** ContextMenuForWindows11

**Description:** Add Custom Context Menu For Windows11

**Homepage:** https://github.com/ikas-mc/ContextMenuForWindows11

**Download link(s):** https://github.com/ikas-mc/ContextMenuForWindows11/releases

**Some indication of popularity/repute:** more than 500 GitHub stars and very useful to customize/fix Windows 11

**Comment by KrisSchneider** [comment]
Sorry to say this, but UWP packages currently cannot be added to scoop because they are simply not made to be portable. I explained here is this related issue (#9274). The free trial for [this app](https://apps.microsoft.com/store/detail/custom-context-menu/9PC7BZZ28G0X) lasts forever, it doesn't require a purchase.

**Comment by ppvnf** [comment]
Somehow I missed that, thanks!

**Comment by ppvnf** [comment]
> Sorry to say this, but UWP packages currently cannot be added to scoop because they are simply not made to be portable. I explained here is this related issue (#9274). The free trial for [this app](https://apps.microsoft.com/store/detail/custom-context-menu/9PC7BZZ28G0X) lasts forever, it doesn't require a purchase.

Would it be possible in [Nonportable](https://github.com/ScoopInstaller/Nonportable)?

**Comment by Zliced13** [comment]
It can be put into the nonportable bucket, but it requires a certificate to be installed in order for the application to be installed. I don't know if this certificate could harm the user's system, and I don't want to risk it on my system either. Just stick with app already offered in the MS Store.

**Comment by Zliced13** [comment]
This is the certificate I'm talking about:
![(explorer)85y4C9_10-16-2022](https://user-images.githubusercontent.com/101912712/196060194-dbc31564-fec1-4749-8535-2fb44492724c.jpg)

**Comment by Zliced13** [comment]
@ppvnf Sorry if this causes any inconvience for you.

**Comment by ppvnf** [comment]
> @ppvnf Sorry if this causes any inconvenience for you.

Np, I think scoop is more convenient than MS, but I was more curious to know if it was possible to add it to nonportable
