### ISSUE TITLE
[Request]  VirusTotalUploader (unofficial)

### ISSUE THREAD

**Issue by ppvnf** [ScoopInstaller/Extras#9349]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [X] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [X] the latest stable version of the program

### Information

**Name:** VirusTotalUploader (unofficial)

**Description:**  C# Open-Source Winforms application for uploading files to VirusTotal

**Homepage:** https://github.com/SamuelTulach/VirusTotalUploader

**Download link(s):** https://github.com/SamuelTulach/VirusTotalUploader/releases

**Some indication of popularity/repute:** more than 700 stars and 105 forks. Suggested on the official VirusTotal website: https://support.virustotal.com/hc/en-us/articles/115002179065-Desktop-apps

P.S.: I am not sure the portable version adds a context menu option to scan files like installing does

**Comment by KrisSchneider** [comment]
Done in #9357

**Comment by 3xploiton3** [comment]
> Done in [#9357](https://github.com/ScoopInstaller/Extras/pull/9357)

can you make it name virustotal for easy to search
