### ISSUE TITLE
[Request] Add Cinny

### ISSUE THREAD

**Issue by kfiven** [ScoopInstaller/Extras#9381]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** cinny

**Description:** A Matrix client with a focus on a simple, elegant, and secure interface.

**Homepage:** https://cinny.in

**Download link(s):** https://github.com/cinnyapp/cinny-desktop/releases

**Some indication of popularity/repute:** https://github.com/cinnyapp/cinny

**Comment by Zliced13** [comment]
Sure, looks awesome.
