### ISSUE TITLE
[Request] IconViewer

### ISSUE THREAD

**Issue by ppvnf** [ScoopInstaller/Extras#9388]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [X] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [X] the latest stable version of the program

### Information

**Name:** IconViewer

**Description:**  IconViewer is a free Windows Explorer extension that lets you easily view, copy, and save icons contained within programs and libraries. Open a file's Properties box, select the "Icons" tab, and view the icons contained in the file. 

**Homepage:** https://www.botproductions.com/iconview/iconview.html

**Download link(s):** https://www.botproductions.com/iconview/download.html

**Some indication of popularity/repute:** Old software, but still very useful since it still works on Windows 10 (I didn't try Win 11 yet) and it is the only way I know of extracting .icon files from .exe ones

**Comment by Zliced13** [comment]
Done in #9435.
