### ISSUE TITLE
Update Everything is not possible if service is not installed

### ISSUE THREAD

**Issue by tty7tyil** [ScoopInstaller/Extras#9422]
## Bug Report

**Package Name:** everything

### Current Behaviour

```
PS> $(Get-Service -Name Everything).Status
Get-Service : Cannot find any service with service name 'Everything'.
At line:1 char:3
+ $(Get-Service -Name Everything).Status
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Everything:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand


PS> $(Get-Service -Name Everything -ErrorAction SilentlyContinue).Status


PS> scoop update everything
everything: 1.4.1.1020 -> 1.4.1.1021
...
Running pre_uninstall script...
ERROR Admin rights are required to stop Everything service
```

### Expected Behaviour

Update should run if service is not installed.

### Additional context/output

I see the `pre_uninstall` script checks for if service is stopped (issue #9221, commit https://github.com/ScoopInstaller/Extras/commit/42ace35a79cd9051c40171a680fc5d53ae2ca929), but does not consider the case that service is not installed.  
I have a habit of uninstalling the service manually myself before each `scoop update everything`, because in the past it will cause problem during `scoop cleanup`.  I would like to keep doing it myself instead of giving the `pre_uninstall` script admin privilege.

### Possible Solution

I am no PowerShell expert, but I think the fix would be rather straight forward?

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 5.1

#### Scoop Configuration

```json
{
    "lastUpdate":  "2022-10-08T07:35:53.3805218+01:00",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by Zliced13** [comment]
> ```
> Running pre_uninstall script...
> ERROR Admin rights are required to stop Everything service
> ```
>

Did you start PowerShell in administrator mode?
![(firefox)s0x590_10-09-2022](https://user-images.githubusercontent.com/101912712/194778478-6624e049-c3ea-45bb-8dea-643acd0c4620.jpg)

**Comment by tty7tyil** [comment]
> > ```
> > Running pre_uninstall script...
> > ERROR Admin rights are required to stop Everything service
> > ```
> >
> 
> Did you start PowerShell in administrator mode?
> ![(firefox)s0x590_10-09-2022](https://user-images.githubusercontent.com/101912712/194778478-6624e049-c3ea-45bb-8dea-643acd0c4620.jpg)

No, but the point is the script should not ask for admin privilege if the service is already **uninstalled**.  Currently it only checks for `stopped`.

**Comment by genotrance** [comment]
Slightly different for me - I don't have admin access so Everything is installed and being used without admin or the service running. Scoop has no clue so is always asking for admin to update and uninstall, making it unsuitable for Everything.

**Comment by Zliced13** [comment]
Alright this PR should solve your issue @tty7tyil

Here is my terminal output:
![(WindowsTerminal)m14507_10-11-2022](https://user-images.githubusercontent.com/101912712/195183012-47913d85-ee83-4c2a-aad3-9b3b7ff062ee.jpg)
```
krist@DESKTOP-7E5L82P > scoop install everything_fixed                                                                      13:28:39
Installing 'everything_fixed' (1.4.1.1022) [64bit] from MyScoop bucket
Loading Everything-1.4.1.1022.x64.zip from cache.
Checking hash of Everything-1.4.1.1022.x64.zip ... ok.
Extracting Everything-1.4.1.1022.x64.zip ... done.
Running pre_install script...
Linking ~\scoop\apps\everything_fixed\current => ~\scoop\apps\everything_fixed\1.4.1.1022
Creating shim for 'Everything'.
Creating shortcut for Everything (Everything.exe)
Running post_install script...
'everything_fixed' (1.4.1.1022) was installed successfully!
Notes
-----
To add Everything to right-click context menu, run:
reg import "C:\Users\krist\scoop\apps\everything_fixed\current\install-context.reg"
krist@DESKTOP-7E5L82P > scoop uninstall everything_fixed -p                                                                 13:28:46
Uninstalling 'everything_fixed' (1.4.1.1022).
Running pre_uninstall script...
The operation completed successfully.
Removing shim 'Everything.shim'.
Removing shim 'Everything.exe'.
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Everything.lnk
Unlinking ~\scoop\apps\everything_fixed\current
Removing persisted data.
'everything_fixed' was uninstalled.
```

**Comment by tty7tyil** [comment]
Tips: you need to edit the `manifest.json` file under folder given by command `scoop prefix everything`, for existing installation to run `pre_uninstall` script without asking for admin permission.

**Comment by tty7tyil** [comment]
@Zliced13 No.  It's just that to update to a fixed version, scoop needs to run the `pre_uninstall` script of the current version first, which does not have the fix.  Once that is done it's all good.

**Comment by Zliced13** [comment]
@tty7tyil oh ok good to know. Thanks for clarification.
