### ISSUE TITLE
[Request] request for helix editor

### ISSUE THREAD

**Issue by 9034725985** [ScoopInstaller/Extras#9438]
Just found out about Helix Editor,  `A Kakoune / Neovim inspired editor, written in Rust.`
Looks like already implemented at 
https://github.com/dodorz/scoop/blob/master/Helix.json

### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks) 14.1k stars, 885 forks
- [x] the latest stable version of the program https://github.com/helix-editor/helix/releases/tag/22.08.1

### Information

**Name:** [name of new package] Helix Editor

**Description:** "A post-modern modal text editor."

**Homepage:** [https://helix-editor.com/](https://helix-editor.com/)

**Download link(s):** [https://docs.helix-editor.com/install.html](https://docs.helix-editor.com/install.html)

**Some indication of popularity/repute:** [https://news.ycombinator.com/item?id=33147270](https://news.ycombinator.com/item?id=33147270 '236 points and front page on hacker news')

**Comment by Zliced13** [comment]
It's already added to the scoop bucket, https://scoop.sh/#/apps?q=helix&s=2&d=1&o=true
