### ISSUE TITLE
Stellarium trouble to update to version 1.0

### ISSUE THREAD

**Issue by git136975643** [ScoopInstaller/Extras#9457]
https://github.com/Stellarium/stellarium

**Comment by amorphobia** [comment]
While waiting for PR been reviewing and merging, I have added the manifest to my bucket: [siku/stellarium](https://github.com/amorphobia/siku/blob/20e1bfe933279a54e969098a10ebefe804acb3c1/bucket/stellarium.json)

Note: it will be moved to [deprecated](https://github.com/amorphobia/siku/tree/master/deprecated) once the PR been merged.
