### ISSUE TITLE
[Request] Winget-Install-GUI

### ISSUE THREAD

**Issue by ppvnf** [ScoopInstaller/Extras#9475]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [X] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [X] the latest stable version of the program

### Information

**Name:** Winget-Install-GUI (WiGui)

**Description:** WiGui is a tool to search, select and install Apps at once with Winget package manager 

**Homepage:** https://github.com/Romanitho/Winget-Install-GUI

**Download link(s):** https://github.com/Romanitho/Winget-Install-GUI/releases

**Some indication of popularity/repute:** Contrary to Scoop, adding a task to update Winget on taskmgr doesn't work. Winget-Install-GUI is useful specially to install and configure https://github.com/Romanitho/Winget-AutoUpdate

https://github.com/Romanitho/Winget-Install-GUI/issues/65

**Comment by Zliced13** [comment]
This application does not meet the requirements for extras bucket. We will have to wait for it to reach **at least 100 stars and 50 forks.**

**Comment by Zliced13** [comment]
Of course, if you don't want to wait. You can create an app manifest for the app in your own bucket.

**Comment by Zliced13** [comment]
@ppvnf 
There is a scoop bucket that already contains the app you are looking for. https://github.com/404NetworkError/scoop-bucket
