### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by naderi** [ScoopInstaller/Extras#9496]
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\scoop\apps\avidemux\2.8.1\dl.7z
C:\scoop\apps\avidemux\2.8.1\dl.7z
Open ERROR: Cannot open the file as [7z] archive

ERRORS:
Is not archive

**Comment by Zliced13** [comment]
Until this mainfest is fixed, please use **avidemux-nightly** from the versions bucket.

**Comment by Zliced13** [comment]
Sorry if this causes any inconvenience for you.

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/issues/9689#issuecomment-1308564396
