### ISSUE TITLE
[Request] windynamic

### ISSUE THREAD

**Issue by ppvnf** [ScoopInstaller/Extras#9510]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [X] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [X] the latest stable version of the program

### Information

**Name:** windynamic

**Description:** Port of macOS Mojave Dynamic Desktop feature to Windows 10 

**Homepage:** https://github.com/t1m0thyj/WinDynamicDesktop

**Download link(s):** https://github.com/t1m0thyj/WinDynamicDesktop/releases/tag/v5.1.0

**Some indication of popularity/repute:** 3.3k stars

**Comment by sitiom** [comment]
Already exists: [`windynamicdesktop`](https://github.com/ScoopInstaller/Extras/blob/master/bucket/windynamicdesktop.json)
