### ISSUE TITLE
[Bug] torrenttools unable to read config.yml and trackers.json

### ISSUE THREAD

**Issue by Ravencentric** [ScoopInstaller/Extras#9527]
## Bug Report

**Package Name:** torrenttools

### Current Behaviour

torrenttools unable to read [config.yml and trackers.json](https://fbdtemme.github.io/torrenttools/configuration.html) which are used to store user configuration. These are currently located in `~\scoop\apps\torrenttools\current` but torrenttools reads these from the following:
> On windows:
> * System location: inside the install prefix (defaults to: ``C:\Program Files\torrenttools``)
> * User location: ``%APPDATA%\torrenttools`` (defaults to: ``C:\Users\{username}\AppData\Roaming\torrenttools``)

### Expected Behaviour
torrenttools will read [config.yml and trackers.json](https://fbdtemme.github.io/torrenttools/configuration.html).

### Additional context/output

I got around this issue by manually creating ``C:\Users\{username}\AppData\Roaming\torrenttools`` and putting the config.yml and trackers.json in there.

### Possible Solution

N/A

### System details

**Windows version:** Windows 11 Pro 22H2

**OS architecture:** 64bit

**PowerShell version:**
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  608
```

**Additional software:** N/A

#### Scoop Configuration

```json
{
    "last_update":  "2022-10-21T14:05:54.7838012+05:30",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/ScoopInstaller/Scoop"
}

```

**Comment by HUMORCE** [comment]
for the manifest, this is the expected behaviour.

```
> torrenttools --config <path_to_config> --trackers-config <path_to_trackers> ...command and args...
```

Try:

- `Set-Alias` or `function` in powershell profile
- `scoop help shim`
- create a self-use manifest to fixed the arguments
