### ISSUE TITLE
Add FirefoxPWA

### ISSUE THREAD

**Issue by CryoRenegade** [ScoopInstaller/Extras#9531]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** [name of new package]
PWAsForFirefox
**Description:** [clear and concise details of what it is]
A tool to install, manage and use Progressive Web Apps (PWAs) in Mozilla Firefox.
**Homepage:** [a URL/link]
https://github.com/filips123/PWAsForFirefox
**Download link(s):** [URL(s)/link(s)]
https://github.com/filips123/PWAsForFirefox/releases/tag/v2.1.2
**Some indication of popularity/repute:** [GitHub stars/software reviews etc.]
986 stars, 21 forks

**Comment by CryoRenegade** [comment]
#9532

**Comment by candrapersada** [comment]
how to run FirefoxPWA on Scoop aftar install?
![gambar](https://github.com/ScoopInstaller/Extras/assets/36833664/761ba3d7-71b3-454f-a221-5da074c90fd3)
