### ISSUE TITLE
[Enhance] Add command to absolutely uninstall Windows-Terminal.

### ISSUE THREAD

**Issue by hungpham3112** [ScoopInstaller/Extras#9546]
![image](https://user-images.githubusercontent.com/75968004/197371139-de6267a1-4a14-4408-8994-960fd82b081e.png)

Because Windows-Terminal uses OpenConsole as background process so when you uninstall it, you need to kill OpenConsole at first.
So I suggest to add 

```pwsh
Stop-Process -Name OpenConsole
```
into windows-terminal uninstall script.

**Comment by HUMORCE** [comment]
this may terminate the process the users working on.

**Comment by hungpham3112** [comment]
We can print the message to warn users to close the Terminal. If they still want to uninstall then kill OpenConsole processes and uninstall Windows-Terminal.

> this may terminate the process users working on.

**Comment by HUMORCE** [comment]
> We can print the message to warn users to close the Terminal. If they still want to uninstall then kill OpenConsole processes and uninstall Windows-Terminal.

please re-check the contents of the screenshot you sent.
