### ISSUE TITLE
[Request] armips

### ISSUE THREAD

**Issue by minhngoc25a** [ScoopInstaller/Extras#9560]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** armips

**Description:** An assembler for various ARM and MIPS platforms.

**Homepage:** https://github.com/Kingcom/armips (Github Repo)

**Download link(s):** 
* https://github.com/Kingcom/armips/releases (stable build)
* https://buildbot.orphis.net/armips/ (automated builds)

**Some indication of popularity/repute:** 278 stars and 63 forks at the time of writing.

**Comment by CryoRenegade** [comment]
Wouldnt this app be more apt for the Main branch seeing as it is a cli application?
