### ISSUE TITLE
[Request]  Add B1 Free Archiver

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#9564]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** B1 Free Archiver

**Description:** Most friendly and simple free file archiver

**Homepage:** http://b1.org/

**Download link(s):** http://b1.org/download

**Some indication of popularity/repute:** http://b1.org/awards.jsp

**Comment by anderlli0053** [comment]
> The stable (not redirected) download URL could not be found.

I understand, the full standalone installer is located at the following link http://b1.org/smart-download/0/os=windows&standalone=true/B1FreeArchiver_1.7.120.exe?cnq=1666787629049&type=.exe , which is composited also..

**Comment by niheaven** [comment]
The standalone installer could be extracted by 7-zip, that's not the problem. The only thing here is a download URL...

**Comment by anderlli0053** [comment]
URL fragment function also cannot be used i assume

**Comment by niheaven** [comment]
Since there's `cnq=` in the URL, maybe it's a required token? So really sorry, it's out of scoop's scope, at least now.

**Comment by anderlli0053** [comment]
> Since there's `cnq=` in the URL, maybe it's a required token? So really sorry, it's out of scoop's scope, at least now.

OK no, worries, but, what if i repack it and upload it to somewhere, is then still valid and possible to include it in this bucket? Or must it be from the original devs only?

Also should i close the issue?

**Comment by niheaven** [comment]
It should from original download link, not third-party one.

Keep this issue opened, and let's wait. Maybe b1 will change its URL? haha

**Comment by Zliced13** [comment]
Here is a permanent link for the standalone app: https://b1.org/smart-download/0/os=windows&standalone=true/B1FreeArchiver_1.7.120.exe

Also, the app's context menu integration does not work when placed in a directory that is not **`C:\Program Files`**.

**Comment by Zliced13** [comment]
This is the warning I get, I try to enable the context menu integration:
![(B1Manager)I3v638_10-26-2022](https://user-images.githubusercontent.com/101912712/198139680-d6ee429a-7c08-4b7b-9557-ee1ecee3edbc.jpg)

**Comment by Zliced13** [comment]
@anderlli0053 are you ok with no context menu integration? If you wanted context menu integration, a non-portable version will have to be created.

**Comment by anderlli0053** [comment]
@Zliced13 I am OK, i personally just need the app to read and write .b1 files

**Comment by anderlli0053** [comment]
Thanks!
