### ISSUE TITLE
[Request]  Add Tutanota mail desktop client

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#9565]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Tutanota Client

**Description:** Desktop client for Tutanota mail service

**Homepage:** https://tutanota.com/

**Download link(s):** https://tutanota.com/#download

**Some indication of popularity/repute:** Cannot say for the built application, but source code repository has over 482 forks and 4.9k stars

**Official source code repo**: https://github.com/tutao/tutanota

**Comment by anderlli0053** [comment]
@Zliced13  Thank you, also should i close the issues that are completed or not?

**Comment by Zliced13** [comment]
@anderlli0053 don't close it, keep it open until the PR is merged into `ScoopInstaller:master`

**Comment by anderlli0053** [comment]
> @anderlli0053 don't close it, keep it open until the PR is merged into `ScoopInstaller:master`

OK
