### ISSUE TITLE
ldplayer deactivates Windows Virtual Machine Platform

### ISSUE THREAD

**Issue by perguto** [ScoopInstaller/Extras#9574]
## Bug Report

**Package Name:** ldplayer

### Current Behaviour

ldplayer deactivates the Virtual Machine Platform without warning, rendering WSL2 unusable. `scoop uninstall ldplayer` didn't revert

### Expected Behaviour / Possible Solution

I don't know whether deactivating the Virtual Machine Platform is necessary, but if it is, at least `scoop uninstall ldplayer` should revert the setting.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.6

**Additional software:** Windows Subsystem for Linux 2

#### Scoop Configuration

```json
{
    "last_update":  "2022-10-26T18:38:44.3259849+02:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/lukesampson/scoop"
}
```

**Comment by HUMORCE** [comment]
When you run the app, it prompts that you need to turn off certain Windows features or something to run and requests administrator rights to change them, then you confirm the request and restart your computer.

> scoop uninstall ldplayer should revert the setting.

Scoop cannot handle this and will not.

_btw, this manifest should be removed, IMO_

**Comment by Zliced13** [comment]
Should a poll be created on the discussions part of this repo?

**Comment by HUMORCE** [comment]
as I said before, this will not be considered a bug. Scoop cannot dynamically record your changes to OS, so it cannot revert them when you uninstall the app.

if you have a better solution, please reopen this issue.
