### ISSUE TITLE
Installing or updating '7tt' (task bar tweaker) shows GUI installer (since 5.14)

### ISSUE THREAD

**Issue by reinpeter** [ScoopInstaller/Extras#9583]
## Bug Report

7tt

### Current Behaviour

Intead of silent update/install, it shows installer gui

### Expected Behaviour

Silent update

**Comment by HUMORCE** [comment]
cannot reproduce

```
> scoop install 7tt
Installing '7tt' (5.14) [64bit] from extras bucket
7tt_setup.exe (1.8 MB) [==============================================================] 100%
Checking hash of 7tt_setup.exe ... ok.
Running pre_install script...
Running installer... done.
Linking ~\scoop\apps\7tt\current => ~\scoop\apps\7tt\5.14
Creating shim for '7+ Taskbar Tweaker'.
Creating shortcut for 7+ Taskbar Tweaker (7+ Taskbar Tweaker.exe)
Persisting 7+ Taskbar Tweaker.ini
'7tt' (5.14) was installed successfully!
```

**Comment by reinpeter** [comment]
![image](https://user-images.githubusercontent.com/7688388/198363137-afab8997-eada-43e1-9e2c-5f2118d69a4d.png)

Is there a way to get a verbose log or smth?
I'm running as a normal user without admin rights.
Win 10 all latest updates.
No traces of 7tt found on system...

**Comment by HUMORCE** [comment]
![screenshot_20221027181451](https://user-images.githubusercontent.com/4353480/198367242-75619f18-0739-46d9-ae57-dd7c3c91453b.png)

reproduced when install it through powershell 5.1

**Comment by niheaven** [comment]
7tt's setup could be extracted by 7zip, but the `uninstaller.nsis` will break extraction.

![image](https://user-images.githubusercontent.com/5832170/198684457-12a051b1-9951-4c5a-a4fc-4b608a6acc67.png)

**Comment by HUMORCE** [comment]
related: #5231
