### ISSUE TITLE
[Request]  Tencent Meeting

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#9615]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Tencent Meeting

**Description:** Video conferencing app by Tencent

**Homepage:** https://meeting.tencent.com/

**Download link(s):**  https://updatecdn.meeting.qq.com/cos/947a8fd1faf0d491148980605952049b/TencentMeeting_0300000000_3.11.6.402.publish.exe

**Some indication of popularity/repute:**  Cannot find any as everything on the page is in Chinese and even the webpage translator doesn't work on them properly.

**Comment by niheaven** [comment]
Really recommand using winget to install it...

**Comment by anderlli0053** [comment]
> Really recommand using winget to install it...

Ok, thanks
