### ISSUE TITLE
[Request] Clash-Verge

### ISSUE THREAD

**Issue by ivaquero** [ScoopInstaller/Extras#9628]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** clash-verge

**Description:** A Clash GUI based on tauri. Supports Windows, macOS and Linux.

**Homepage:** https://github.com/zzzgydi/clash-verge

**Download link(s):** https://github.com/zzzgydi/clash-verge/releases/download/v1.1.2/Clash.Verge_1.1.2_x64_portable.zip

**Some indication of popularity/repute:** GitHub stars 2.3k

**Comment by b4imetu** [comment]
✔️ https://github.com/ScoopInstaller/Extras/pull/10655
