### ISSUE TITLE
[Request] Volume²

### ISSUE THREAD

**Issue by Arkoth79** [ScoopInstaller/Extras#9632]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [+- ] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [+] the latest stable version of the program

### Information

**Name:** Volume²

**Description:** advanced Windows volume control

**Homepage:** [https://github.com/irzyxa/Volume2](https://github.com/irzyxa/Volume2)

**Download link(s):** [https://github.com/irzyxa/Volume2/releases/](https://github.com/irzyxa/Volume2/releases/)

**Some indication of popularity/repute:** 518 stars

**Comment by Zliced13** [comment]
@Arkoth79 Could you please check the boxes in your comment?
![(firefox)c8e6l4_11-02-2022](https://user-images.githubusercontent.com/101912712/199618194-de82bc94-fb8f-49b6-ba06-30d7f81f3c07.jpg)

**Comment by Zliced13** [comment]
Thank you.
