### ISSUE TITLE
[CHANGE] FreeTube not being updated to the latest version 

### ISSUE THREAD

**Issue by Xelbayria** [ScoopInstaller/Extras#9634]
## Bug Report

**Package Name:** Freetube

### Current Behaviour

The version of Freetubeshould have been updated to the late version but it hasn't since the new version is out at (NOV 1, 2022 @ 9:25pm). I took a look at the JSON file. the REGEX for the version of Freetube is incorrect. 

### Expected Behaviour

The Freetube app is to be updated to the latest version via Github's "ACTIONS". 

### Possible Solution

The REGEX for JSON to check for Freetube's version needs to be changed. 

### System details

**Windows version:** 10

**OS architecture:** 64

**PowerShell version:** 7.2.7

**Comment by Zliced13** [comment]
Could you show how you would fix the `checkver`?

**Comment by Zliced13** [comment]
@Xelbayria  do you urgently need a fixed version of this app?

**Comment by Zliced13** [comment]
Just incase you need it I have a fixed version in my personal bucket which you can use until the **freetube** manifest in this bucket is fixed.

```
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
```
```
scoop install freetube_fixed
```

**Comment by Xelbayria** [comment]
> Just incase you need it, I have a fixed version in my personal bucket which you can use until the **freetube** manifest in this bucket is fixed.
> 
> ```
> scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
> ```
> 
> ```
> scoop install freetube_fixed
> ```

Thanks, I'll use it for now.
