### ISSUE TITLE
Skype can't be installed

### ISSUE THREAD

**Issue by nebojsa-simic** [ScoopInstaller/Extras#9655]
#### Scoop Configuration
```json
{
    "last_update":  "2022-11-04T15:53:44.1134192+01:00",
    "scoop_branch":  "master",
    "scoop_repo":  "https://github.com/lukesampson/scoop"
}
````

### Steps to reproduce

```
~ λ scoop install skype
Installing 'skype' (8.88.0.401) [64bit] from extras bucket
The request was aborted: Could not create SSL/TLS secure channel.
URL https://download.skype.com/s4l/download/win/Skype-8.88.0.401.exe is not valid
```

Clicking on the link downloads the file without problems.
I tried some things like:
```
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
```
but no luck.

**Comment by Zliced13** [comment]
Microsoft discontinued the desktop apps for skype, that is why the download links are not up anymore.

**Comment by nebojsa-simic** [comment]
@Zliced13 thank for taking the time and looking at the problem, but I don't think your answer explains the problem. 
As I wrote above, opening the download link in the browser, will download the file without problems.

Maybe the problem is in the incompatibility of thesecurity protocols the PowerShell is using to download the file and the Microsoft download server is providing (the irony of not being able to download things from Microsoft servers using PowerShell).

**Comment by Zliced13** [comment]
Have you tried installing the file using **aria2**?

**Comment by Zliced13** [comment]
I was wrong, I thought Microsoft discontinued the Skype desktop app. I checked the website just now, and Download links for the app is up and functional.
