### ISSUE TITLE
[Request] Microsoft Visual J# Version 2.0 Redistributable Package

### ISSUE THREAD

**Issue by ppvnf** [ScoopInstaller/Extras#9666]
### Criteria

For a package to be acceptable in the Java bucket, it should be:

- [X] a runtime environment or software development kit for Java
- [X] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [X] the latest stable version of the program
- [X] the full version i.e. not a trial version
- [X] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)
- [X] downloadable without having to sign in or use user-dependant cookies

### Information

**Name:** Microsoft Visual J# Version 2.0 Redistributable Package

**Description:** The Microsoft Visual J#™ Redistributable Package version 2.0 includes everything you need to run your Visual J# applications on a computer that already has the Microsoft .NET Framework v2.0 installed.

**Homepage:** https://www.microsoft.com/en-us/download/details.aspx?id=4712

**Download link(s):** https://download.microsoft.com/download/9/a/0/9a01eb1e-fe80-41af-a3f8-ea41220918f7/vjredist.exe

**Some indication of popularity/repute:** Microsoft's Java clone

**License:** https://social.msdn.microsoft.com/Forums/en-US/28a369b0-c1dc-4276-ac65-f063578fb139/redistributable-license?forum=visualjsharpgeneral

**Comment by se35710** [comment]
Moved to Extra since it's not a Java runtime.

**Comment by ppvnf** [comment]
I guess I should try to add this to non portable since I think a silent install isn't possible
https://github.com/ppvnf/expert-parakeet/blob/master/bucket/vjredist.json
