### ISSUE TITLE
[Request] Yuescript

### ISSUE THREAD

**Issue by gphg** [ScoopInstaller/Extras#9686]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [v] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [v] the latest stable version of the program

### Information

**Name:** Yuescript

**Description:** A Moonscript dialect compiles to Lua.

**Homepage:** https://github.com/pigpigyyy/Yuescript

**Download link(s):** https://github.com/pigpigyyy/Yuescript/releases

**Some indication of popularity/repute:** Yuescript is derived from [Moonscript language](https://github.com/leafo/moonscript) 0.5.0 and continuously adopting new features to be more up to date. It supports most of the features from Moonscript language, it generate Lua codes in the same way like the original compiler.

**Comment by gphg** [comment]
Yuescript has two archives (download file links): 

1) module: the dll file (on Linux, it's ".so"), and 
2) tool: binary executable (command-line).

More detail explained on: https://yuescript.org/doc/#usage

**Comment by Zliced13** [comment]
do you want a manifest for the module .dll file?

**Comment by gphg** [comment]
> Do you want a manifest for the module .dll file?

Yes.
