### ISSUE TITLE
[Request]  Perfetto

### ISSUE THREAD

**Issue by anderlli0053-storage** [ScoopInstaller/Extras#9693]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Perfetto

**Description:** Perfetto is a production-grade open-source stack for performance instrumentation and trace analysis. It offers services and libraries and for recording system-level and app-level traces, native + java heap profiling, a library for analyzing traces using SQL and a web-based UI to visualize and explore multi-GB traces.

**Homepage:** https://perfetto.dev/

**Download link(s):** https://github.com/google/perfetto/releases

**Some indication of popularity/repute:** 203 forks and 1.4k stars

**Comment by anderlli0053** [comment]
Thanks
