### ISSUE TITLE
[Request]  Avogadro

### ISSUE THREAD

**Issue by anderlli0053-storage** [ScoopInstaller/Extras#9694]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Avogadro

**Description:** Avogadro is an advanced molecule editor and visualizer designed for cross-platform use in computational chemistry, molecular modeling, bioinformatics, materials science, and related areas. It offers flexible high quality rendering and a powerful plugin architecture

**Homepage:** https://avogadro.cc/

**Download link(s):** https://sourceforge.net/projects/avogadro/files/latest/download

**Some indication of popularity/repute:** https://sourceforge.net/projects/avogadro/reviews/

**Comment by Zliced13** [comment]
There is an **Avogadro 2** that is currently in development unlike this version, do you want me to add that one instead. Or do you want me to add this old version?

**Comment by anderlli0053** [comment]
Thank you very much
