### ISSUE TITLE
[Request]  Wind financial tool

### ISSUE THREAD

**Issue by anderlli0053-storage** [ScoopInstaller/Extras#9696]
### Criteria

For a package to be acceptable in the Extras bucket, it should be:

- [x] a well-known and widely used tool (e.g. if it's a GitHub project, it should have at least 100 stars and 50 forks)
- [x] the latest stable version of the program

### Information

**Name:** Wind financial tool

**Description:** A financial data tool

**Homepage:** https://www.wind.com.cn

**Download link(s):** https://d-cdn.wind.com.cn/windnet/WFT_Setup_CHS.zip

**Some indication of popularity/repute:**  Cannot find the webpage for it

**Comment by niheaven** [comment]
Please don't request non-English apps in official buckets.

**Comment by niheaven** [comment]
And why do you plan to install Wind via Scoop? Its huge size, Excel plugin, update mechanism, etc. are totally incompatible with Scoop.

I use it every day and never thought portable installation of it.

**Comment by niheaven** [comment]
This was discussed before, in an old post. Sorry and I will add it in the issue template.

Believe me, the installation process of WFT will never be *easier*.
