### ISSUE TITLE
[Request] win-vind

### ISSUE THREAD

**Issue by shishirong** [ScoopInstaller/Extras#9712]
### Information

**Name:** 
`win-vind`

**Description:** 
`win-vind provides a lightweight hybrid UI system of CUI and GUI for Windows. And everything is inspired by Vim and its plugins. Simply put, it is a Vim-oriented toy box consisting of various useful features`

**Homepage:** [[https://github.com/pit-ray/win-vind](https://github.com/pit-ray/win-vind)]

**Download link(s):** [[win-vind_4.4.0-rc1_64bit_portable](https://github.com/pit-ray/win-vind/releases/download/v4.4.0-rc1/win-vind_4.4.0-rc1_64bit_portable.zip)]

**Comment by anderlli0053** [comment]
Thanks
