### ISSUE TITLE
[Bug]: RivaTuner Statistics Server / rtss - not persisting all user configs

### ISSUE THREAD

**Issue by luxzg** [ScoopInstaller/Extras#9789]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

rtss

### Expected/Current Behaviour

"Regular" RTSS keeps these folders and files on uninstall because they contain user-made changes:

- \Profiles
- \Plugins\Client\*.cfg
- \Plugins\Client\Overlays\*.ovl

scoop package only persists this folder:

- \scoop\persist\rtss\Profiles
- \scoop\persist\rtss\Plugins\Client\Overlays

Note that `\Plugins\Client\*.cfg` are missing. This means that any plugin configurations added or configured by user will be reset on update & deleted on cleanup.

It would be expected to at least persist files in this manner:
`\Plugins\Client\*.cfg`

### Steps to Reproduce

```console
scoop install rtss

Open RTSS and enable and configure plugins offered, eg I've added and enabled custom overlay and hotkey to toggle it.

When new version is released:
scoop update rtss

Customizations will be gone.
```

### Possible Solution

This is related to the issue I've just reported for MSI Afterburner ( https://github.com/ScoopInstaller/Extras/issues/9788 )

Either persist files `\Plugins\Client\*.cfg` or add a Note for user to move the files manually before cleanup deletes them.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
b4ebfb2dc (HEAD -> master, origin/master, origin/HEAD) jackett: Update to version 0.20.2267

'java' bucket:
fec2bd1a (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.362-3.0.202211181811

'main' bucket:
e13981012 (HEAD -> master, origin/master, origin/HEAD) tflint: Update to version 0.43.0
```

### Scoop Config

```console
last_update          scoop_repo                              scoop_branch
-----------          ----------                              ------------
19.11.2022. 16:05:54 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Zliced13** [comment]
@luxzg Do you mind sharing the names of the files you want persisted from the `\Plugins\Client\` folder?

**Comment by luxzg** [comment]
Not at all.

After I've uninstalled RTSS (choosing to KEEP user files during uninstall) I was left with 2 files in my `\Plugins\Client\` folder:
```
HotkeyHandler.cfg
OverlayEditor.cfg
```

As the name says `HotkeyHandler` keeps settings about hotkeys setup in RTSS Settings, while `OverlayEditor` keeps settings about the current Overlay in use.
As is scoop seems to keep overlay configuration (designs) in `\scoop\persist\rtss\Plugins\Client\Overlays` but overlay wouldn't be applied if the overlay name in use is named differently and thus not expected by RTSS defaults.

I've just realized that it is possible that I could be wrong because this was my first install through scoop, and default install doesn't have these files (created only after settings are selected and applied), but json seems to be confirming what I'm seeing:

```
"persist": [
        "Plugins\\Client\\Overlays",
        "Profiles"
    ],
```

In my case it would need two more files at least:
```
Plugins\\Client\\HotkeyHandler.cfg,
Plugins\\Client\\OverlayEditor.cfg
```

**Comment by luxzg** [comment]
I'll post here results of rtss_fixed install:

```
PS C:\Users\lux_z> scoop install rtss_fixed
Installing 'rtss_fixed' (7.3.3) [64bit] from MyScoop bucket
%5BGuru3D.com%5D-RTSS.zip (22,6 MB) [=============================================] 100%
Checking hash of %5BGuru3D.com%5D-RTSS.zip ... ok.
Extracting %5BGuru3D.com%5D-RTSS.zip ... done.
Running pre_install script...
MethodInvocationException: C:\Users\lux_z\scoop\apps\scoop\current\lib\install.ps1:1037
Line |
1037 |          Invoke-Command ([scriptblock]::Create($script -join "`r`n"))
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Create" with "1" argument(s): "At line:5 char:59 +
     | 'HotkeyHandler.cfg', 'OverlayEditor.cfg' | ForEach-Object {if (!(Test … +
     | ~ Missing closing '}' in statement block or type definition.  At line:5 char:157 + …
     | \Plugins\Client\$_")) {New-Item "$dir\Plugins\Client\$_" | Out-Null}) +
     | ~ Unexpected token ')' in expression or statement."
Linking ~\scoop\apps\rtss_fixed\current => ~\scoop\apps\rtss_fixed\7.3.3
Creating shim for 'RTSS'.
Remove-Item: C:\Users\lux_z\scoop\apps\scoop\current\lib\core.ps1:692
Line |
 692 |              Remove-Item -Path "$shim.$path_app" -Force -ErrorAction S …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | An object at the specified path C:\Users\lux_z\scoop\shims\rtss.shim. does not exist.
WARN  Overwriting shim ('rtss.exe' -> 'RTSS.exe') installed from rtss
Creating shortcut for RivaTuner Statistics Server (RTSS.exe) failed: Couldn't find C:\Users\lux_z\scoop\apps\rtss_fixed\current\RTSS.exe
Persisting Plugins\Client\Overlays
Persisting Profiles
Persisting Plugins\Client\HotkeyHandler.cfg
Persisting Plugins\Client\OverlayEditor.cfg
Running post_install script...
'rtss_fixed' (7.3.3) was installed successfully!
```

Observations:
- `scoop\persist\rtss_fixed\Plugins\Client\HotkeyHandler.cfg` is persisted but it looks like a *folder*
- `scoop\persist\rtss_fixed\Plugins\Client\OverlayEditor.cfg` is persisted but it looks like a *folder*
- in the apps folder I have `RTSSSetup733.exe` seems it did not expand/extract properly
- tried with `sudo` but same error and result

**Comment by Zliced13** [comment]
Thank you, I'll will fix this as soon as I can.

**Comment by Zliced13** [comment]
@luxzg Try uninstalling **rtss_fixed** with this command:
```
scoop uninstall rtss_fixed -p
```
Then update scoop:
```
scoop update
```
Afterwards, reinstall **rtss_fixed**
```
scoop install rtss_fixed
```

**Comment by luxzg** [comment]
`scoop install rtss_fixed`
Install was success.
I see two files in persist folder, empty files.
Opened app, settings, enabled two settings, set one hotkey.
`scoop uninstall rtss_fixed` without p
Files still persisting
`scoop install rtss_fixed`
running RTSS.exe, checking settings, everything remembered.

Thank you, I think it's ready! You've been great! :)
