### ISSUE TITLE
[Request]: Dolphin

### ISSUE THREAD

**Issue by areen-c** [ScoopInstaller/Extras#9801]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

dolphin

### Description

A file manager focusing on usability. KDE's file manager that lets you navigate and browse the contents of your hard drives, USB sticks, SD cards, and more.

### Homepage

https://github.com/KDE/dolphin

### Download Link(s)

https://binary-factory.kde.org/job/Dolphin_Release_win64/

### Some Indication of Popularity/Repute

well-known linux file manager

**Comment by Zliced13** [comment]
Done, now wait.

**Comment by areen-c** [comment]
thanks
