### ISSUE TITLE
[Bug]: Unable to uninstall TortoiseSvn version 1.14.3.29387 fully

### ISSUE THREAD

**Issue by opariffazman** [ScoopInstaller/Extras#9803]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

TortoiseSvn

### Expected/Current Behaviour

Got this error when uninstalling this specific TortoiseSvn version
```ERROR Couldn't remove '~\scoop\apps\tortoisesvn\1.14.3.29387'; it may be in use.```

When I attempt to cleanup, scoop says access is denied
`Remove-Item : Cannot remove item C:\Users\opari\scoop\apps\tortoisesvn\1.14.3.29387\bin\intl3_tsvn.dll: Access to the
path 'intl3_tsvn.dll' is denied.`

### Steps to Reproduce

```console
scoop uninstall tortoisesvn
scoop cleanup tortoisesvn
```

### Possible Solution

Information I got when running `scoop status` is **Install failed, Manifest removed**

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
6e864ae48 (HEAD -> master, origin/master, origin/HEAD) portfolio-performance: Update to version 0.59.4

'main' bucket:
586a94bf4 (HEAD -> master, origin/master, origin/HEAD) schemacrawler: Update to version 16.19.1
```

### Scoop Config

```console
last_update  : 2022-11-21T10:50:44.0236807+08:00
scoop_branch : master
scoop_repo   : https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Zliced13** [comment]
@opariffazman Have you tried using the command in Administrator mode in PowerShell?

**Comment by opariffazman** [comment]
> @opariffazman Have you tried using the command in Administrator mode in PowerShell?

Yes, I tried running as Administrator as well getting same error of access denied.

**Comment by Zliced13** [comment]
Have you tried locating your scoop directory, and manually deleting the folder, `scoop\apps\tortoisesvn\1.14.3.29387`?

**Comment by tech189** [comment]
You may need to restart first or use a tool such as LockHunter or File Locksmith which is now a part of PowerToys.

**Comment by opariffazman** [comment]
I'm not sure how or what happened, but today I ran `scoop update` to ensure my PowerToys got the File Locksmith feature and then a `scoop cleanup` suddenly able to remove TortoiseSvn. Thanks anyway!
