### ISSUE TITLE
[Bug]: Windows Defender detects discord-portable.exe binary as a Trojan

### ISSUE THREAD

**Issue by otavio-silva** [ScoopInstaller/Extras#9831]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

discord

### Expected/Current Behaviour

The file should be working normally like previously.

### Steps to Reproduce

```console
>scoop install discord
>%USERPROFILE%\scoop\apps\discord\1.0.9007-14\discord-portable.exe
```

### Possible Solution

Windows Defender accuses the binary `discord-portable.exe` of being a Trojan:Win32/Sabsik.FL.B!ml, don't know how to solve that.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'404NetworkError' bucket:
6ccc1d5 (HEAD -> main, origin/main, origin/HEAD) jazz2-resurrection: Update to version 1.2.0

'extras' bucket:
5f8d4e57c (HEAD -> master, origin/master, origin/HEAD) wpsoffice: Update to version 11.2.0.11417

'games' bucket:
318fa9b2 (HEAD -> master, origin/master, origin/HEAD) vita3k: Update to version 2921-aefc71e

'java' bucket:
59307f6b (HEAD -> master, origin/master, origin/HEAD) temurin-nightly-jre: Update to version 20.0.0-24.0.202211230349

'main' bucket:
5d278db22 (HEAD -> master, origin/master, origin/HEAD) qemu: Update to version 7.2.0-rc2

'nerd-fonts' bucket:
14e63c7 (HEAD -> master, origin/master, origin/HEAD) (chore): add descriptions to default nerd font manifests (#211)

'nonportable' bucket:
3aa5cbb (HEAD -> master, origin/master, origin/HEAD) xampp-np: Update to version 8.1.12-0

'versions' bucket:
aa4ed757 (HEAD -> master, origin/master, origin/HEAD) v-weekly: Update to version 2022.47
```

### Scoop Config

```console
last_update         scoop_branch scoop_repo
-----------         ------------ ----------
23/11/2022 11:42:42 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by otavio-silva** [comment]
Also, it is possibly a security vulnerability?

**Comment by rasa** [comment]
This most likely is a false positive. See https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper

**Comment by HUMORCE** [comment]
in this case, it is up to you to consider whether to add it to the whitelist or not.

> Also, it is possibly a security vulnerability?

YES, when a subsequent version of an app is replaced with a malicious progrm. that's why official bucket usually only adds well-known apps.

some (3rd party) buckets contain apps that have been reported as trojan or virus, such as injectors/miners.
