### ISSUE TITLE
[Bug]: cpu-z@2.03 hash err

### ISSUE THREAD

**Issue by Elypha** [ScoopInstaller/Extras#9832]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

cpu-z

### Expected/Current Behaviour

Expected:    cce36729a38af3e6aa055d0466f117c306cce37d443add282da4482d4a8ec13d
Actual:      1d4f587e9ccf54645d6073827237a23271c29f4cbfb3d0542b2950bb0131d5f0

### Steps to Reproduce

```console
just run `scoop update *`
```

### Possible Solution

update hash

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
17a5e1c00 (HEAD -> master, origin/master, origin/HEAD) age(chore): Fix checkver

'main' bucket:
6fea0867d (HEAD -> master, origin/master, origin/HEAD) wasmer: Update to version v3.0.1
```

### Scoop Config

```console
last_update         scoop_branch scoop_repo
-----------         ------------ ----------
23/11/2022 23:10:34 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Elypha** [comment]
may be related to #9507

**Comment by tech189** [comment]
Sometimes apps push a minor update without updating the version number, nothing Scoop can do to automatically catch this, sadly.

If you submit an issue in the format like mine here (use the link Scoop outputs at the end of the error message): #9833 then the github-actions bot should fix it for you :)

**Comment by Elypha** [comment]
> Sometimes apps push a minor update without updating the version number, nothing Scoop can do to automatically catch this, sadly.
> 
> If you submit an issue in the format like mine here (use the link Scoop outputs at the end of the error message): #9833 then the github-actions bot should fix it for you :)

Thanks for the explanation. 
Sorry for a re-open comment, but actually I did see the report link and I clicked it, but then I was redirected from 
`https://github.com/ScoopInstaller/Extras/issues/new?title=cpu-z%402.03%3a+hash+check+failed`
to
`https://github.com/ScoopInstaller/Extras/issues/new/choose`, which brings me here to submit an issue
I'm not sure if that happens to me only, or if it indicates something being mis-configured

**Comment by tech189** [comment]
That's odd, it doesn't redirect for me. Not sure why that's happening for you. Can you go to https://github.com/ScoopInstaller/Extras/issues/new/ instead?

**Comment by sdellenb** [comment]
That link also leads me to the "choose" page:
![grafik](https://user-images.githubusercontent.com/2712168/204131814-2455e4a6-3eb5-4896-a74f-5cb236760261.png)

I don't see any option to create a new [hash-fix-needed](https://github.com/ScoopInstaller/Extras/issues?q=label%3Ahash-fix-needed) issue (I just wanted to to so for w10privacy).
