### ISSUE TITLE
[Bug]: Missing quotes in ZAProxy runner

### ISSUE THREAD

**Issue by githubkuyaya** [ScoopInstaller/Extras#9843]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

zaproxy

### Expected/Current Behaviour

I am experiencing a problem with the zap.bat file (the runner file, which is invoked when running "zap"). The last line of the file runs the zaproxy jar file but does not wrap quotes around the path. Thus, java fails to find the jar file. If quotes are wrapped around the variable, the command succedes.

### Steps to Reproduce

```console
PS> scoop in zaproxy
PS> # Wait for command to finish, restart the shell
PS> zap
```

### Possible Solution

The current line is:
`java %jvmopts% -jar %~dp0zap-2.12.0.jar%*`

Fix it with the following line:
`java %jvmopts% -jar "%~dp0zap-2.12.0.jar%*"`

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
bf774ddd5 (HEAD -> master, origin/master, origin/HEAD) lagrange: Update to version 1.14.0

'java' bucket:
7ec73041 (HEAD -> master, origin/master, origin/HEAD) temurin11-nightly-jre: Update to version 11.0.18-4.0.202211241816

'main' bucket:
ee203d5b8 (HEAD -> master, origin/master, origin/HEAD) polaris: Update to version 0.14.0

'nerd-fonts' bucket:
bc46c8c (HEAD -> master, origin/master, origin/HEAD) Delugia-Nerd-Font: Update to version 2111.01.1
```

### Scoop Config

```console
PS> scoop config

last_update         scoop_repo                              scoop_branch
-----------         ----------                              ------------
25/11/2022 09:49:17 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
cannot reproduced, may caused by the path contains special characters.

file `zap.bat` has not been changed by Scoop,
please report to developers of the app: https://github.com/zaproxy/zaproxy
