### ISSUE TITLE
[Bug]: github-actions bot keeps reverting megasync's version to older one

### ISSUE THREAD

**Issue by jasongodev** [ScoopInstaller/Extras#9882]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

magasync

### Expected/Current Behaviour

megasync 4.8.1 is being reverted to 4.7.3 by github-actions bot

Here's the recent erroneous commit:
https://github.com/ScoopInstaller/Extras/commit/c4aea3d50a09f2708379ca6d83a9387c04e7c9b9

### Steps to Reproduce

```console
PS C:\Users\jason> scoop info megasync

Name        : megasync
Description : Client for automated synchronization between local folder and MEGA cloud
Version     : 4.8.1.0 (Update to 4.7.3.0 available)
Bucket      : extras
Website     : https://mega.nz
License     : Freeware
Updated at  : 12/1/2022 12:31:27 AM
Updated by  : github-actions[bot]
Installed   : 4.8.1.0
Binaries    : MEGAsync.exe
Shortcuts   : MEGAsync
```

### Possible Solution

Please help.

### Scoop and Buckets Version

```console
PS C:\Users\jason> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
9e22242a3 (HEAD -> master, origin/master, origin/HEAD) stash: Update to version 0.18.0

'main' bucket:
2410508d5 (HEAD -> master, origin/master, origin/HEAD) trid: Update to version 2.24-22.11.30

'php' bucket:
31f073f (HEAD -> master, origin/master, origin/HEAD) php8.0: Update to version 8.0.26
```

### Scoop Config

```console
PS C:\Users\jason> scoop config

last_update          scoop_branch scoop_repo
-----------          ------------ ----------
12/1/2022 1:32:31 AM master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\Users\jason> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by HUMORCE** [comment]
This is an expected bug, we cannot get latest version of `megasync` now.

**Comment by jasongodev** [comment]
How about checking its VirusTotal hash page which shows the file version of the installer and the program itself? This might be the best way to automate it for now.

See this link: https://www.virustotal.com/gui/file/3c5db4f98ce373725edf4b8ffb83fdedc7341f08c8514aa339e4ce44f4953e80/details

Take note of the url, the hash we use in scoop is the same hash that can be used to create the VirusTotal url of megasync. Also works with the 32-bit version of installer. The hash in VirusTotal resolves to the information of the installer.

![Screenshot_20221201_032928](https://user-images.githubusercontent.com/36266783/204890809-00b5e169-bf8e-47c4-9ec8-bb5f68928256.png)

**Comment by HUMORCE** [comment]
this will cause the bot to download installers each time it runs update check, even app is not updated.
