### ISSUE TITLE
[Bug]: Ungoogled-chromium opens in a new window completely fresh.

### ISSUE THREAD

**Issue by zachvlat** [ScoopInstaller/Extras#9910]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

Ungoogled-Chromium

### Expected/Current Behaviour

When I pin ungoogled-chromium to taskbar and I open it, it opens completely fresh with no profiles.

### Steps to Reproduce

```console
windows 11 pro 22H2

scoop install extras/ungoogled-chromium

I pin the app to taskbar from Scoop Apps folder (from start menu).

I open it and it opens completely new.
```

### Possible Solution

One solution is to never pin the app to taskbar and use it from start menu, either by pin it to Start or just use it from the Scoop Apps folder.

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'anderlli0053_DEV-tools' bucket:
c376b95d1 (HEAD -> master, origin/master, origin/HEAD) nheko-nightly: Update to version 20221205-59703d

'extras' bucket:
7f2ba648c (HEAD -> master, origin/master, origin/HEAD) wavebox: Update to version 10.108.14.2

'java' bucket:
b24e0e5d (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.362-5.0.202212021814

'main' bucket:
68f3aede6 (HEAD -> master, origin/master, origin/HEAD) gping: Update to version 1.5.0

'nonportable' bucket:
6c49cce (HEAD -> master, origin/master, origin/HEAD) spotx-np: Update to version 1.6-20221204-ee520a

'versions' bucket:
30ce9447 (HEAD -> master, origin/master, origin/HEAD) ipfilter-nightly: Update to version 1670256141
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2022-12-05T21:21:15.8533832+02:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by HUMORCE** [comment]
![screenshot_20221206054231](https://user-images.githubusercontent.com/4353480/205826356-5b51ac43-8e07-4b7b-9ac6-103071cd89e1.png)

1. Pin shortcut created by Scoop:
  - press win key then typing `chromium` for searching shortcut created by Scoop.
  - all shortcuts created by Scoop: `C:\Users\<USERNAME>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps`

2. Edit shortcut manully:
`C:\Users\<USERNAME>\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`

**Comment by zachvlat** [comment]
Very nice! Thank you. But still opens chromium in a seperate icon which is a little weird...
![image](https://user-images.githubusercontent.com/28532979/205911078-fe202521-777a-4fe9-831a-228b749dca85.png)

**Comment by HUMORCE** [comment]
> opens chromium in a seperate icon which is a little weird...

idk, it works fine, as the screenshot.

**Comment by zachvlat** [comment]
> > opens chromium in a seperate icon which is a little weird...
> 
> idk, it works fine, as the screenshot.

is there any documentation you found it, or all by yourself?

**Comment by HUMORCE** [comment]
app's launch options will not save to shortcut properties, when you pinned an running application directly from taskbar.

> Can you explain me step by step how did you solve this?

![screenshot_20221213152407](https://user-images.githubusercontent.com/4353480/207373656-3194c6ef-6110-4e00-a781-08cc21641a27.png)

**Comment by HUMORCE** [comment]
Exception case:
`profile/userdata` will be stored to default path, if you set the browser(Chromium, Firefox, etc.) installed by Scoop as your default browser and open an links outside of the browser.

Removing `--user-data-dir` works fine for this case: https://github.com/HUMORCE/nuke/blob/master/bucket/ungoogled-chromium.json

Realted:
- https://github.com/ScoopInstaller/Extras/issues/8779
- https://github.com/ScoopInstaller/Extras/issues/9548

For security issue and convenience to use:
install (main)default browser using its official installer.
