### ISSUE TITLE
[Request]:  HP Support Assistant

### ISSUE THREAD

**Issue by anderlli0053** [ScoopInstaller/Extras#9912]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

HP Support Assistant

### Description

HP Support Assistant is a one-stop solution for connected, contextual support. Aided with a new user interface and other usability enhancements, HP Support Assistant helps you maintain your HP devices— enabling you to prevent or resolve problems by using automated updates and self-help options. What’s more, HP Support Assistant guides you to expert support when you need it. 

### Homepage

https://support.hp.com/us-en/help/hp-support-assistant

### Download Link(s)

https://ftp.ext.hp.com/pub/softpaq/sp142501-143000/sp142943.exe

### Some Indication of Popularity/Repute

It is installed on more or less on every HP laptop and HP tower PCs.

Don't know where to look for "Repute"

For more info:

http://h10032.www1.hp.com/ctg/Manual/c06593496.pdf

**Comment by HUMORCE** [comment]
I think you should create the request in [nonportable bucket](https://github.com/ScoopInstaller/Nonportable).

**Comment by anderlli0053** [comment]
@HUMORCE  Will do, should this be closed then?

**Comment by HUMORCE** [comment]
> should this be closed then?

yes, this program is not portable.
