### ISSUE TITLE
qbittorrent-enhanced: url is wrong

### ISSUE THREAD

**Issue by StarsbySea** [ScoopInstaller/Extras#9930]
```powershell
Updating 'qbittorrent-enhanced' (4.4.5.10 -> 4.5.0.10)
Downloading new version
OperationStopped: C:\Users\<>\scoop\apps\scoop\current\lib\install.ps1:111
Line |
 111 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.
```

**Comment by ykz0608** [comment]
same problem, in version **4.5.0.10** download  link is  
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-$version/qbittorrent_enhanced_$version_qt6_x64_setup.exe#/dl.7z

but the rule is
 https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-$version/qbittorrent_enhanced_$version_qt6_setup.exe#/dl.7z

so cannot identify the download link

**Comment by swift-lee** [comment]
same here #9936 , and seems like automated issue handler cannot handle the issue correctly 😂
[https://github.com/ScoopInstaller/Extras/actions/runs/3640419465/jobs/6145063988#step:3:350](https://github.com/ScoopInstaller/Extras/actions/runs/3640419465/jobs/6145063988#step:3:350)
