### ISSUE TITLE
[Request]: FanControl

### ISSUE THREAD

**Issue by kennedy** [ScoopInstaller/Extras#9943]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 100 stars and/or 50 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

FanControl

### Description

FanControl is a highly customizable fan controlling software for Windows. 

There is no installation; unzip package and start `FanControl.exe`

### Homepage

https://getfancontrol.com/

### Download Link(s)

https://github.com/Rem0o/FanControl.Releases/blob/master/FanControl.zip?raw=true
https://github.com/Rem0o/FanControl.Releases/releases/tag/V138

### Some Indication of Popularity/Repute

star: 7k
fork: 264
latest commit: Dec 5, 2022

**Comment by Zliced13** [comment]
It's already being added in, #9668. I did that.

**Comment by kennedy** [comment]
Thanks Zliced13

**Comment by Zliced13** [comment]
@kennedy If you want to add it from my personal bucket, you can add it by running these commands:
```
scoop bucket add MyScoop 'https://github.com/Zliced13/MyScoop'
```
```
scoop install fan-control
```
