### ISSUE TITLE
avidemux@2.8.1: decompress error

### ISSUE THREAD

**Issue by Bennyhill500** [ScoopInstaller/Extras#9993]
`PS C:\Users\benny> scoop install avidemux
WARN  Purging previous failed installation of avidemux.
ERROR 'avidemux' isn't installed correctly.
Removing older version (2.8.1).
'avidemux' was uninstalled.
Installing 'avidemux' (2.8.1) [64bit] from extras bucket
Loading Avidemux_2.8.1.VC++.64bits.exe from cache
Checking hash of Avidemux_2.8.1.VC++.64bits.exe ... ok.
Extracting dl.7z ... ERROR Exit code was 2!
Failed to extract files from C:\Users\benny\scoop\apps\avidemux\2.8.1\dl.7z.
Log file:
  ~\scoop\apps\avidemux\2.8.1\7zip.log`

[7zip.log](https://github.com/ScoopInstaller/Extras/files/10227344/7zip.log)

**Comment by HUMORCE** [comment]
#3691

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Extras/issues/9689#issuecomment-1308564396
